### ISSUE TITLE
[Question] Unmap Moving Tabs

### ISSUE THREAD

**Issue by alivefromupstairs** [gdh1995/vimium-c#100]
in my keyboard (custom layout) `shift+,` and `shift+,` or `;` and `:` respectively move tabs around. I could not find the keys corresponding to that behavior in the chearsheet.

i tried a combination of
```
unmap ;
unmap ,
unmap <s-,>
unmap <s-.>
```
to no avail.

I also get this error:
```
There're 2 errors found. Please see logs of background page for more details.
The related option "Ignore keyboard layout" is enabled
```
---

Also, is there a key to close chromium entirely? `x` opens a new tab on one tab (which is nice).

**Comment by gdh1995** [comment]
On the help dialog, there's a button of "Show advanced commands" at the bottom right corner:

![image](https://user-images.githubusercontent.com/5547703/71790643-71ad3780-306c-11ea-9839-c4720c3b9eef.png)

So you may click it and then **all** mappings will be visible. Vimium C's default mappings include `map >> moveTabRight` and `map << moveTabLeft`.

The error tip means some keys has not been mapped, so you may delete one line of the four and see how many errors will be left. Then you will find two buggy items and delete them. (I think they're `<s-,>` and `<s-.>`).

`removeTab` support an option named `allow_close`, so `map x removeTab allow_close` will make <kbd>X</kbd> only close a current tab while never reopen a new tab.

**Comment by alivefromupstairs** [comment]
```
unmap <<
unmap >>
```
works.
