### ISSUE TITLE
Automate a series of clicks?

### ISSUE THREAD

**Issue by 11100010** [gdh1995/vimium-c#1001]
Is it possible to map a key to automate a seriresof clicks?
Such as, I want the automation of clicks would be first "Linkhints.activate" the "SL" button, then "Linkhints.click" the "AH" button that represents "Not interested" in the popup menu. Please take a look at the following screenshot to know what "SL", "AH" buttons mean

![Screenshot 2023-08-22 at 08 28 33](https://github.com/gdh1995/vimium-c/assets/87060114/a05d8d79-f30f-4b5d-bfee-492b6e70953f)

**Comment by 11100010** [comment]
Maybe this could help
https://github.com/gdh1995/vimium-c/wiki/Auto-run-a-tree-of-commands

**Comment by gdh1995** [comment]
Yes `runKey` is exactly designed to do so. And here's a small tip: `a+300wait+b` means an extra sleeping of about 300ms between two commands of `a` and `b`. By default the sleeping time between any two commands is 50ms, so `a+300wait+b` means to run `a`, sleep for 400ms and then run `b`.

**Comment by 11100010** [comment]
I asked ChatGPT to find out the element name of the option:

> ❯❯❯what is its element name in html
In HTML, the "Don't recommend this channel" option in the YouTube popup menu does not have a specific element name. It is typically implemented using a combination of HTML, CSS, and JavaScript to create the popup menu and handle the user's selection. The specific implementation may vary depending on the website or application.

Still not figure it out what kind of "Linkhints" with what syntax should I use for my case.

I think "LinkHints.click" could help:
> Click selected text, focused element or the nearest clicked (use direct=true|element|sel|focus|click|sel,focus,click)(LinkHints.click)

But have no idea how to take advantage of it.
The only use I make out of it, which is also learn from you, is:
> map . LinkHints.click action="focus" match="video"

TBH, as a freking noob, find a lil hard to learn without examples.
