### ISSUE TITLE
sortTabs according to the tab titles

### ISSUE THREAD

**Issue by anglimath** [gdh1995/vimium-c#1005]
Is it possible to use sortTabs to sort the tabs according to the titles (or domains)? 

Equivalently, how could I cluster the tabs based on the titles, such that "*.youtube.com" are clustered in one group, "*.google.com" are clustered in another group.

**Comment by gdh1995** [comment]
`may xxx sortTabs order="host"` should help.

**Comment by anglimath** [comment]
It works. Thanks a lot!
