### ISSUE TITLE
页面滚动

### ISSUE THREAD

**Issue by MOldtime** [gdh1995/vimium-c#1006]
在一个网页中，可能会多个区域可以滚动，如何切换这些区域呢

**Comment by backuponeday** [comment]
按 `f` 后有个 `Tag`是红色的, 先选择红色的 `Tag`后就可滚动了. 或者使用 `gf` 切换不同的frame

**Comment by MOldtime** [comment]
> 按 `f` 后有个 `Tag`是红色的, 先选择红色的 `Tag`后就可滚动了. 或者使用 `gf` 切换不同的frame

感谢你的解答
