### ISSUE TITLE
Automatically focus the first result in vomnibar when searching is disabled

### ISSUE THREAD

**Issue by nzl-thu** [gdh1995/vimium-c#1008]
**What command or commands**

map o Vomnibar.activate engines="history, tab" icase

**How should a feature do**

我希望vomnibar只实现tab search和history search，在搜索时「默认focus第一个选项」，就像Vomnibar.activateHistory和Vomnibar.activateTabs一样，请问有办法实现这一点吗？谢谢！
虽然如上所示，我设置了engines="history, tab"，此时vomnibar确实只搜索history和tabs了，但是它并不会默认focus第一个tab，如果我按enter，它仍然会进行搜索（虽然我的engines里面并没有包含search）

**Browser and OS**

Google Chrome | 116.0.5845.179 (Official Build) (arm64)
-- | --
Revision | 17ff023f3eb4f6883321db9399bfc65560ef84a9-refs/branch-heads/5845@{#1745}
OS | macOS Version 13.3.1 (a) (Build 22E772610a)

**Comment by gdh1995** [comment]
`map o Vomnibar.activate engines="history, tab" icase autoSelect`

**Comment by nzl-thu** [comment]
十分感谢😁😁
