### ISSUE TITLE
Is there a macro functionality on Vimium C?

### ISSUE THREAD

**Issue by rafaelmuynarsk** [gdh1995/vimium-c#101]
Sometimes while using Vimium C I realize I'm repeating some patterns that could be automated with a macro... Is there any configuration on Vimium C that allows me to create macros similar to the way we can create them on Vim? Or this kind of functionality would imply permission problems to implement on browsers?

**Comment by gdh1995** [comment]
Most of the commands support a "count" prefix, but there's no macros to call several commands during one key.

The main problem is it's too complex

**Comment by rafaelmuynarsk** [comment]
Do you mean complex to guarantee that the macro will be executed correctly with no mistakes? I was actually thinking on a more simple implementation of it, like storing the pressed keys and the interval of time between them on a queue so it can be replicated later...

As the `f` key sometimes changes the letters for the same elements on pages from time to time, I think it'd be prone to fail depending on how the user is using it... But still, this functionality would have some value on some situations...

**Comment by gdh1995** [comment]
Maybe a command can be mapped to a group of background commands, which have no influence on web page content.

But up to now Vomnibar / FindMode / Marks only uses web `<input>` to accept typed characters, so a list of keys will not work on them.

A better solution is to use AutoHotKey or something else to map a key to some other keys globally. AutoHotKey can also map different keys on different software windows.

**Comment by rafaelmuynarsk** [comment]
You mean creating a logic that works something like this:

1. Vimium C sends a command to a background process so this background process starts recording the keys..
2. Vimium C sends another command to the background process so it stops recording...
3. Vimium C sends a third command to the background process to make it execute the list of keys that it has created.

Is that what you thought?

I use Linux though... But I could perfectly use `cnee`  and `xdotool` in place of `AutoHotKey` there.

**Comment by gdh1995** [comment]
Um, I mean:
1. add something like `macro <c-f> <c-a><c-b>jk12<c-d>` to key mappings
2. press `<c-f>` to do the 3rd point, and it execute those keys.

**Comment by rafaelmuynarsk** [comment]
I think the time between the keys on the first item would be an issue though... But leaving aside how the background process would work. How would you implement this communication between the extension and the background process? It'd be a script that works independent from Vimium C extension, right?

**Comment by gdh1995** [comment]
It's not "independent".

Vimium C has a special system process, and a "background page" runs in the process. This process runs 
scripts in `background/` (defined in `manifest.json`) and allows Vimium C to copy/paste text, operate tabs and so on.

**Comment by rafaelmuynarsk** [comment]
Ah, sorry... I don't understand much about how web extension work. I was thinking about executing a script outside the extension in a language that is not javascript. Like executing a piece of nodejs, python or bash code that would work only on my computer. This kind of thing is not possible from within the extension, right?

**Comment by gdh1995** [comment]
Yes, completely impossible. A normal web extension can only runs JavaScript code and has NO ACCESS to system resources like file system, list of system processes, network MAC address and so on.

**Comment by rafaelmuynarsk** [comment]
I see... So the `cnee` solution that I've said would not work. Wouldn't it be the same for `AutoHotkey`? I've never used it but from what I've seen on their page it's an automation tool that is not necessarily to be used on frontend javascript...

**Comment by gdh1995** [comment]
AutoHotKey (aka. AHK) is a tool to map one or more keys to some of its commands, like moving windows, sending messages (mouse/keyboard/system-native ones) to windows, simulating other keyboard events or mouse movement, calling system APIs/commands and so on. So with it you may press a special composed key to run a sequential list of actions.

On macOS there's a similar tool but I've forgotten its name; on Linux I know little but GNOME has a inner key mapping tool, which may also be useful.

For example, my AutoHotKey settings includes:
```
; Win---># ; Shift--->+ ; Ctrl--->^ ; Alt--->!
!h:: Send {Left}
!j:: Send {Down}
!k:: Send {Up}
!l:: Send {Right}

!CapsLock:: CapsLock
CapsLock:: Escape

; Win 键 + F10 键关闭屏幕
#F10::
KeyWait F10
KeyWait LWin ;释放Win键才激活下面的命令
DllCall("LockWorkStation")
Sleep 1000
SendMessage 0x112,0xF170,2,,Program Manager ;关闭显示器。0x112:WM_SYSCOMMAND，0xF170:SC_MONITORPOWER。2：关闭，-1：开启显示器
Return
```

Then I can use <kbd>Alt+J</kbd> just as <kbd>ArrowDown</kbd>.

**Comment by rafaelmuynarsk** [comment]
So the AutoHotKey wouldn't be included inside the extension, it would work only on the computer that it's installed because it's communicating with Vimium C through an API, wouldn't it? 

I think it'd also be possible to implement this macro with three POST requests on my localhost using the fetch API... Is there any limitation on using a normal API with a web extension?

**Comment by gdh1995** [comment]
I mean AutoHotKey simulates keyboard messages in the system level, and Chrome/Firefox receives those messages and let a current web page know them, just like normal keyboard pressing made by you. Then Vimium C will receive such keyboard events and trigger mapped commands.

AutoHotKey supports `Sleep` to wait a while before sending a next keyboard message, which is very useful.

As for http requests, a web extension can not listen on port - it can only request some others, so this point's also impossible.

**Comment by rafaelmuynarsk** [comment]
I see... I'd have to find an alternative to AutoHotKey to follow this path though...

I actually already have a script that is a macro for the graphical interface that works on Linux. But in the end, the way we execute the macro makes all the difference and I never use it because it's not practical to execute a script to record and then execute its output file to play the macro. I'm starting to think that Vimium C would be a good way of executing it... 

I wouldn't listen to a port with the extension though... I could do it in the traditional way, I make a backend API to listen to the POST requests from Vimium C and the macro logic would be invisible for Vimium C. I would send only metadata (on vim language qa, q, @a)... It's possible to do it in this way, right?

**Comment by gdh1995** [comment]
No.

Vimium C learns what keys you're pressing through a event listener on your web page, so a macro tool just needs to simulate keyboard messages before a browser software receives real keyboard messages.

In this way everything only takes charge of its own part:
1. System gets a key is being pressed and generate a message
2. a tool like AutoHotKey hooks the message and covert it to a sequence of commands
- 1. you may configure it to do whatever you want, _including **running a bash script**_
3. if the converted commands includes a simulated keyboard message (named `A`):
- 1. AutoHotKey returns `A` to system
- 2. system dispatches `A` to a Chrome window
- 3. Chrome dispatches a KeyboardEvent instance for msg A to a current web page
- 4. Vimium C's event listener (in "content" environment)on web page grabs this message
- 5. if this message means a key is in the key mappings :
  - 1. Vimium C's listener in content sends a message withe the key, to its background process
  - 2. the JavaScript code in background process analyses what to do and execute it

The keypoint to hook is `Step 2`, so there's no http messsages needed.

**Comment by rafaelmuynarsk** [comment]
I think we have different implementations in mind... Look, on Linux I can create a macro with a single command like this:

![create macro](https://user-images.githubusercontent.com/44415096/71799395-eadc6880-3033-11ea-8217-1048f9ce41f6.gif)

Basically, it'll generate a file (qa.macrofile) and with this file I use the same command line with other parameters to replay the macro. It works like this (in this second example I'm not moving the mouse or typing anything myself):

![executing a macro](https://user-images.githubusercontent.com/44415096/71799436-0c3d5480-3034-11ea-808d-2d5db462f684.gif)

The point of using the HTTP message is more for reusing this command line that is quite simple to use. There'd be no need for creating a queue of key presses or adding a complex logic inside Vimium C. Your first point in this issue was that creating a macro functionality would be too complex. So why not using an already existing macro tool that works on the operating system level?

**Comment by gdh1995** [comment]
But there're too many places where Vimium C can do nothing, or can not run into a stable result:
* it can not input in a text box according to a list of keys
* it can not operator buttons on browser windows (address bar, menu button and so on)
* it does not run on priviledged pages like `chrome://extensions`, neither on JS-disabled pages
* it can do locate an iframe accurately
* it can not record new macros by itself
  * the only reliable way I can imagine is that you paste a list of keys into a text box.

So a simpler and easy-to-maintain way is to use another assistant tool to hook and simulate keyboard actions in a system level.

**Comment by gdh1995** [comment]
Hello. Vimium C v1.92+ has a new feature to use one key to run a list (or tree) of commands, and it has been published on Chrome and Firefox stores. You may see https://github.com/gdh1995/vimium-c/wiki/Auto-run-a-tree-of-commands for how to write mappings.
