### ISSUE TITLE
using Vimium C on Twitter and you want to select a video, you encounter a problem with video controller.

### ISSUE THREAD

**Issue by M0hamedMagdy** [gdh1995/vimium-c#1013]
**Describe the bug**

If you are using Vimium C on Twitter and you want to select a video, you might encounter a problem.  When you select a video, the video controller does not appear on the screen. This means you cannot pause, rewind, or adjust the volume of the video. 

**To Reproduce**
F > Select Video 

**Browser, OS and Vimium C versions**

- Browser name: Microsoft Edge 
- Browser version: 117 
- Vimium C version: 1.99.99
- OS name and version: Windows 11 22H2

**Comment by gdh1995** [comment]
There has been a similiar issue: #687, and these comments may help:
- https://github.com/gdh1995/vimium-c/issues/687#issuecomment-1218024513
- https://github.com/gdh1995/vimium-c/issues/687#issuecomment-1214142290
