### ISSUE TITLE
Toggle focus/highlight of last copied link using LinkHints.activateCopyLinkUrl

### ISSUE THREAD

**Issue by cesm1980** [gdh1995/vimium-c#1019]
For example, i am manually copying to the clipboard a few links in a youtube video list, by using "LinkHints.activateCopyLinkUrl" i am able to use linkhints to sucessfully get the link i want, and then i paste the clipboard in a program, the problem is that now, unless i visually memorize the link text i don't know anymore which one i just copyied, when doing this in a list with several elements with links, it gets hard to get track of this, isn't there a specific command/option toggle for this function to NOT lose the blue highlight after the link gets copied to the clipboard so that i have a visual clue which link was last copied? Or then a different way to get the link and select the text in the element, i also tried autocopy after using LinkHints.activateSelect but it only copies text, not the link itself.

**Comment by gdh1995** [comment]
If you have been in the mode of `LinkHints.activateCopyLinkUrl`, you may press `Ctrl` to switch to a new mode named `Copy link URL one by one`, and then you may select a few links and their URLs are joined with the "new line" character and copied.

To copy both text and URL, you may try:
```
# the format is "link-text : link-url"
map xxx LinkHints.activateCopyLinkText access=":${innerText||title} : ${url}"
# or try the format of "link-text (link-url)"
map yyy LinkHints.activateCopyLinkText access=":${innerText||title} (${url})"
```

**Comment by cesm1980** [comment]
Very interesting... yeah, i tried it and i think it works fine for my workflow, thanks! Sure is a interesting different way of doing this, it's perhaps even better than the suggestion i have of keeping a highlight there, great!

**Comment by gdh1995** [comment]
If you haven't enabled the option `Use the link's name and characters for link-hint filtering`, then you may press Tab to reinit LinkHints while keeping old copied list.

**Comment by cesm1980** [comment]
Ok great, seems to work fine! Issue solved then, despite being different from what i expected but work as fine.
