### ISSUE TITLE
[Question] Changelog

### ISSUE THREAD

**Issue by alivefromupstairs** [gdh1995/vimium-c#102]
Have I overlooked [release notes](https://github.com/gdh1995/vimium-c#release-notes) in `vimium-c`'s option page somewhere?

**Comment by gdh1995** [comment]
What items / issues do you find?

**Comment by alivefromupstairs** [comment]
> What items / issues do you find?

I don't follow.

My question was, are there release notes "offline" in the options page? I get notified when new versions of extensions come out, and would like to know what changed without the need to open github.

**Comment by gdh1995** [comment]
Um, Vimium C only shows a notification box every time it arrives in a new bigger "minor" version, like `v1.79.***` to `v1.80.***`, while upgrades silently when only "patch" version changes.

**Comment by gdh1995** [comment]
The detailed changelog has been moved into https://github.com/gdh1995/vimium-c/blob/master/RELEASE-NOTES.md, and then the file is not put into released extension packages, to make the extension file size (showing on Chrome Web Store) look smaller.

I just keep several "release notes" of a current minor version in README.md, and it is indeed in extension packages. But, there's no link to open it locally on options page. If you can find the extension folder, you may open it using Microsoft Notepad or other editors.

**Comment by alivefromupstairs** [comment]
I'm an extension to do the notifying and this is beside the point.
Could you please add a link in the options page similar to this:
![image](https://user-images.githubusercontent.com/46059092/71998379-ca80f980-323f-11ea-9459-82c0317a0220.png)

**Comment by gdh1995** [comment]
OKay, maybe I can add a link at the bottom of Vimium C's help dialog.

BTW, currently you can type `vimium://changelog` on Vomnibar to jump to the changelog file on GitHub.

**Comment by alivefromupstairs** [comment]
I have yet to start actively using that; it sounds very useful. I'll look into it.

**Comment by gdh1995** [comment]
Hello, Vimium C v1.80.0 has been published and will be visible on Chrome Web Store in a few days. The links to release notes are: 1) at bottom-left corner of options page, 2) and bottom-right corner of help dialog.
