### ISSUE TITLE
Vomnibar no longer working for `file://` URLs

### ISSUE THREAD

**Issue by zeke-jeske** [gdh1995/vimium-c#1021]
**Describe the bug**

In the last two weeks, the Vomnibar stopped working for me when opening filesystem URLs in browser, e.g. `file:///Users/myuser/downloads/my-document.pdf`. Whether I type the entire URL into the Vomnibar or select it from the list of suggestions, when I press enter to open the URL the Vomnibar closes and nothing happens.

**To Reproduce**

1. Go to a page where the Vomnibar works, like this one.
2. Press `O`, `o`, `B`, or `b` to open the Vomnibar.
3. Type in a URL for a local file beginning with `file:///` or select one from the list of suggestions below the input field.
4. Press enter.

**Browser, OS and Vimium C versions**

- Browser name: Google Chrome
- Browser version: 118.0.5993.88
- Vimium C version: 1.99.99
- OS name and version: macOS Sonoma v14.0 on a 14-inch 2021 MacBook Pro with an M1

**Comment by gdh1995** [comment]
Not reproduced on my Chrome 118 + macOS. Have you seen this problem again in the recent week?

If Vomnibar can show on a local HTML file, or a local folder page like `file:///`, then I guess your problem is because your keyboard focus is grabbed by Chrome's built-in PDF Viewer, so Vimium C can not receive your shortcut keys.

**Comment by zeke-jeske** [comment]
Yep, I'm still getting this problem. It happens with HTML files, PDF files, images, anything. Prior to a few weeks ago, this has always worked, so I don't think it's an issue with keyboard focus.

**Comment by gdh1995** [comment]
do other key mappings work? like linkhints.



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 14, 2023 03:16 AM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Vomnibar no longer working for `file://` URLs(Issue #1021)




 
Yep, I'm still getting this problem. It happens with HTML files, PDF files, images, anything. Prior to a few weeks ago, this has always worked, so I don't think it's an issue with keyboard focus.

**Comment by zeke-jeske** [comment]
[Web links can't go from a non-local website to a local file](https://stackoverflow.com/a/12711835/13289145), so link hints aren't relevant to this issue. If I have a `file://` URL on my clipboard, `p` or `P` does not work to open it. If I use `ge` and replace the current URL with a `file://` URL, it also doesn't work (nothing happens).

My best guess is that Chrome has some security feature that's preventing extensions from opening local files, but you would know more about this than me.

**Comment by zeke-jeske** [comment]
Wait! I figured it out! Chrome has now added an option in [the extension's options page](chrome://extensions/?id=hfjbmagddngcpeloejdejnfgbamkjaeg) to "Allow access to file URLs", and it is **disabled by default**. Enabling this makes Vimium C work again. [This change was initiated in Chrome v. 118.](https://developer.chrome.com/docs/extensions/whatsnew/#changes-to-file-scheme)

<img width="759" alt="Screenshot 2023-11-14 at 1 18 51 PM" src="https://github.com/gdh1995/vimium-c/assets/56773338/4ca99521-47d2-44a8-9409-22e9aed2c2ac">

**Comment by Gattocrucco** [comment]
I have the same problem in Firefox.

I could not find how to make it work though. There is no per-extension option for allowing local files like in Chrome.

**Comment by zeke-jeske** [comment]
@Gattocrucco [Try this](https://github.com/fastaddons/GroupSpeedDial/issues/36#issuecomment-788283828)

**Comment by Gattocrucco** [comment]
It works, thanks!

I thought that kind of thing could only disable the security feature globally, but ostensibly it just does it for Vimium-C.
