### ISSUE TITLE
如何发送一个按键组合Ctrl+PageDn或Ctrl+Up？

### ISSUE THREAD

**Issue by lededev** [gdh1995/vimium-c#1022]
**What command or commands**
我以前左手切换到临近标签用的是S和D
```
map S previousTab
map D nextTab
```
但vivaldi浏览器提供的标签切换功能有点多，previousTab,nextTab通常被设置为最近访问的标签而不是物理临近标签，切换临近标签的功能也有，但用的是别的可配置热键：
![image](https://github.com/gdh1995/vimium-c/assets/30518126/338285a6-6a28-4caa-bc0a-f2b52c8e6649)
因此我希望将S和D设置为发送Ctrl+PageUp和Ctrl+PageDn
```
map S dispatchEvent [Ctrl down] [PageUp down] [PageUp up] [Ctrl up]
map D dispatchEvent [Ctrl down] [PageDn down] [PageDn up] [Ctrl up]
```
搜了一下已有issues没找到类似的范例，烦请给个例子，谢谢。

**Comment by lededev** [comment]
又搜了一下，这个问题似乎与 https://github.com/gdh1995/vimium-c/issues/802 类似，在vimium-c插件里似乎实现不了，以前我还回复过那个issue的，看来我还是写StrokesPlus.net脚本来实现吧。

**Comment by lededev** [comment]
最后用StrokesPlus.net定义了将鼠标右键按下时上下滚轮映射到Ctrl+PageUp/Dn，放弃用键盘左手热键来操作这个功能了。

**Comment by gdh1995** [comment]
这个绕过的办法听起来不错。

我有个疑问：
> vivaldi浏览器提供的标签切换功能有点多，previousTab,nextTab通常被设置为最近访问的标签而不是物理临近标签

请问你这儿想表达的下边这句话的意思吗？
- 默认状态下，Vimium C 默认的 previousTab 会起到“上一个标签页（按时间）”的效果

还是说，Vimium C 的 previousTab 目前是按顺序跳转的，而你想要它按时间跳转？

想跳到按时间的上一个标签页，可以用 `shortcut userCustomized1 command="visitPreviousTab"` 这个命令来配置”自定义快捷键 1“的功能。但 Vimium C 的 `visitPreviousTab` 目前不会记住当前跳转的是时间上第几个标签页，所以没有”下一个标签页（按时间）“的功能——也就是说，第一次 `visitPreviousTab` 从 A 跳到 B 的话， 第二次 `visitPreviousTab` 会从 B 跳回 A
