### ISSUE TITLE
Run command from custom page / extension script

### ISSUE THREAD

**Issue by Lubsch** [gdh1995/vimium-c#1024]
Is there a way to run a command from the script header of a page?

I've set my homepage to file:///\<path\>.html, basically to my own blank.html. My workflow consists of opening a lot of new browser windows. While I can launch the Vomnibar using the shortcut, it would be convenient to open it on page load.

**How should a feature do**

When a user has done such steps:

Add an injector and a custom script to their page / extension.

then Vimium C should do:

Execute the commands specified in that script on page load.

**Browser and OS**

- Browser name: Firefox
- OS: `Linux 6.5.8 #1-NixOS SMP PREEMPT_DYNAMIC Thu Oct 19 21:11:09 UTC 2023`
- Vimium version: `1.99.995`
- Firefox version: `119.0`

Edit: Put code blocks around os version to escape issue link

**Comment by gdh1995** [comment]
You may follow steps in https://github.com/gdh1995/vimium-c-helpers/issues/16#issuecomment-917598571 :
> `shortcut createTab $then="Vomnibar.activate"` should work

**Comment by gdh1995** [comment]
Vimium C doesn't "trust" web-pages, so you can not use a `<script>` to call Vimium C's commands.

**Comment by Lubsch** [comment]
Okay, that's unfortunate in my case. Thanks for answering!
