### ISSUE TITLE
can't hint embeded link form youtube ot spotify in twitter

### ISSUE THREAD

**Issue by Monirzadeh** [gdh1995/vimium-c#103]
hi
if you have a link in twitter timeline from youtube or spotify  you can't hint them
other link work fine
you can test that with bellow link
youtube: https://twitter.com/YouTube/status/1207787568718217216
spotify : https://twitter.com/Spotify/status/1214582078228054016

**Comment by gdh1995** [comment]
1. Yes sometimes Vimium C doesn't know a node is clickable.
2. Fortunately, in this case there's a work-around:
- 1. press <kbd>f</kbd> to enter `LinkHints` mode
- 2. press <kbd>F2</kbd> to tell Vimium C "find those with `.onclick` actions"
- 3. then Vimium C will re-run LinkHints and now they're hinted.

This feature of finding elements with `.onclick` needs to be run manually for performance reason, and you'll have to press <kbd>F2</kbd> again if you scroll down / refresh the page and get another Youtube/Spotify item.

**Comment by Monirzadeh** [comment]
thanks

**Comment by gdh1995** [comment]
BTW, on Firefox Vimium C can hint them directly, thanks to a useful feature of Firefox which cuts down the cost to check `.onclick`.
