### ISSUE TITLE
Vimium C 尚未运行在当前页面上

### ISSUE THREAD

**Issue by happyQQQ** [gdh1995/vimium-c#1039]
Vimium C 如何在chrome或Firefox内部网页运行？比如新标签页，设置页？

**Comment by gdh1995** [comment]
chrome的话，去 `chrome://flags` 把 `#extensions-on-chrome-urls` 改成 Enabled，然后重启浏览器，再去 Vimium C 设置里勾选：
![image](https://github.com/gdh1995/vimium-c/assets/5547703/277ec289-71ed-41d5-9066-162fbec34f99)

Firefox 的话，没有类似机制，但如果你用第三方的新标签页扩展，可以修改对方扩展，来主动加载 vimium c，这样就能用了。
参考 https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions

**Comment by happyQQQ** [comment]
谢谢
________________________________
发件人: Dahan Gong ***@***.***>
发送时间: 2023年12月4日 3:29
收件人: gdh1995/vimium-c ***@***.***>
抄送: happyQQQ ***@***.***>; Author ***@***.***>
主题: Re: [gdh1995/vimium-c] Vimium C 尚未运行在当前页面上 (Issue #1039)


chrome的话，去 chrome://flags 把 #extensions-on-chrome-urls 改成 Enabled，然后重启浏览器，再去 Vimium C 设置里勾选：
image.png (view on web)<https://github.com/gdh1995/vimium-c/assets/5547703/277ec289-71ed-41d5-9066-162fbec34f99>

Firefox 的话，没有类似机制，但如果你用第三方的新标签页扩展，可以修改对方扩展，来主动加载 vimium c，这样就能用了。
参考 https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions

―
