### ISSUE TITLE
<a-C>为无效的映射

### ISSUE THREAD

**Issue by YandLiu** [gdh1995/vimium-c#104]
<a-C>既没有效果也没法unmap
![image](https://user-images.githubusercontent.com/26127104/72216131-1352ee00-3571-11ea-9dd9-337f8aec7cd1.png)
unmap会出错，不管是`<a-c>`还是`<a-s-c>`

**Comment by gdh1995** [comment]
最新版的话，写法是`<a-s-c>`，帮助里的`<a-C>`是默认配置中出现了笔误，不用管它，直接`map <a-s-c> ...`就行
