### ISSUE TITLE
希望能将自定义的搜索引擎添加到右键菜单中方便搜索

### ISSUE THREAD

**Issue by shishirong** [gdh1995/vimium-c#1041]
希望能将自定义的搜索引擎添加到右键菜单中方便搜索，就像Search from Popup or ContextMenu这种：
![image](https://github.com/gdh1995/vimium-c/assets/16620315/92b37312-4f0e-4b22-9182-1d341bac6f86)

**Comment by gdh1995** [comment]
不打算做这个，因为 Vimium C 设计上是要用键盘控制浏览器做事情，但右键菜单本身必须用鼠标、触摸板之类的才能弹出来，这个操作已经超出 vimium c 范围了。

**Comment by shishirong** [comment]
很多键盘都有上下文菜单键的啊
![image](https://github.com/gdh1995/vimium-c/assets/16620315/123c34ac-6a07-450d-bf97-6aae3c47e18f)

或者是否有别的方式能快速地通过指定的搜索引擎搜索选择的文字

**Comment by gdh1995** [comment]
浏览器不允许 vimium c 模拟菜单键的效果。

至于搜索选中文字，可以，已经有了这么一个快捷键——`autoOpen`，它支持参数 `keyword=搜索引擎关键字`，比如：
```
# 用 bi 搜索，默认是 必应
map xxx autoOpen keyboard="bi"
```
