### ISSUE TITLE
DokuWiki sidebar rendering broken in Firefox

### ISSUE THREAD

**Issue by philipphutterer** [gdh1995/vimium-c#1043]
It seems that Vimium-C breaks the rendering of the sidebar in the CMS DokuWiki with [bootstrap3 template](https://www.dokuwiki.org/template:bootstrap3) in Firefox. As an example, open a public DokuWiki page with this template (e.g., https://kb.meinbergglobal.com/kb/start) in Firefox and Chrom*. This is a very specific bug, I know, but I think this should not happen.

<table><tr valign="top">
<td><p>Firefox:</p><img src="https://github.com/gdh1995/vimium-c/assets/34458455/f2e32e01-36cb-459d-9ab7-e6099769a947" width="200" /></td>
<td><p>Chrome:</p><img  src="https://github.com/gdh1995/vimium-c/assets/34458455/51b20f7a-46b6-4b3c-94f2-6db6ddad440f" width="200" /></td>
</tr></table>

**Comment by gdh1995** [comment]
Hello, Vimium C v1.99.997 has been published on Firefox Add-Ons, and you may take a try by reloading the page manually.

**Comment by philipphutterer** [comment]
Works. Thank you!
