### ISSUE TITLE
Vomnibar改进意见

### ISSUE THREAD

**Issue by YandLiu** [gdh1995/vimium-c#105]
Vomnibar默认只显示10项结果，用tab键和方向键都只能在这10个结果里循环，想显示更多结果需要用鼠标滚轮。
可以增加个选项使得tab和方向键可以自动切换到另外10个结果中吗？

**Comment by gdh1995** [comment]
PageDown、Shift+下箭头、Ctrl+Shift+F 都可以向下翻页，直接输入搜索词+空格+偏移量也可以跳过指定个数的结果。PageUp、Shift+上箭头、Ctrl+Shift+B 向上翻页。

**Comment by YandLiu** [comment]
这些都远没有敲tab方便啊，能把结果弄成连续展示而不是10个一组10个一组展示就更好了

**Comment by gdh1995** [comment]
在设置页面的“自定义快捷键”里添加
```
mapkey <tab> <pagedown>
mapkey <s-tab> <pageup>
```

连续展示这个近期不一定有时间做，我还要再想想。

**Comment by gdh1995** [comment]
新的`mapkey`用法已经写完初版了，zip文件下载地址参见 https://github.com/gdh1995/vimium-c/issues/89#issuecomment-580084311 （安装方式参考 https://github.com/gdh1995/vimium-c/issues/110#issuecomment-578690423 ），新的写法是：

```
mapkey <tab:o> <pagedown>
mapkey <s-tab:o> <pageup>
```

这样这个映射只在Vomnibar里生效，不影响别的模式。

**Comment by YandLiu** [comment]
感谢，我之前的说法不够准确
我的意思是从第10个结果之后，按下tab把第1~10个结果替换成第2~11个结果，再按下tab变成第3~12这样，流畅无缝展示更多结果

**Comment by gdh1995** [comment]
这种“连续”我感觉不实用，因为一次tab后出的内容太少了。
