### ISSUE TITLE
The character 'ç' does not work with LinkHints

### ISSUE THREAD

**Issue by maykot** [gdh1995/vimium-c#1051]
**Describe the bug**

The character 'ç' does not work with LinkHints.

**To Reproduce**

1. Characters used for link hints: jdkslaçueiwophgnvmc
2. Trigger LinkHints on any webpage
3. LinkHints will show "Ç" for some link
4. Press "ç" (on a pt-BR keyboard with the input method set to pt-BR)
5. Link won't open

**Browser, OS and Vimium C versions**

- Browser name: Brave
- Browser version: 1.60.125 Chromium: 119.0.6045.199 (Official Build) (64-bit) 
- Vimium C version: 1.99.99
- OS name and version: Windows 11 Version 22H2 (Build 22621.2792)

**Comment by gdh1995** [comment]
Um it's a configurable feature: by default, Vimium C enables `Ignore layout if a key is not located in 7-bit ASCII`:
![image](https://github.com/gdh1995/vimium-c/assets/5547703/6554d316-1027-4b1a-afec-1f3b045ffcfe)

And this switch makes Vimium C always treat a `ç` in pt-BR as `;`.

1. You may turn off this switch
2. If you do like the showing `Ç`, then you may add `mapKey <;:l> ç` to make `LinkHints` treat `;` as `ç`
![image](https://github.com/gdh1995/vimium-c/assets/5547703/3d8a9edf-d329-4031-a2af-93b7ec3fb74c)

**Comment by maykot** [comment]
Oh, makes sense. My bad for not seeing that.

Works perfectly now, thanks for the reply!
