### ISSUE TITLE
关于自定义界面样式设置、皮肤设置问题

### ISSUE THREAD

**Issue by touero** [gdh1995/vimium-c#1054]
我在其中 `自定义界面样式设置` 设置了vimium推荐的[theme](https://github.com/philc/vimium/wiki/Theme) 但却不生效。请问配置通用吗，我应该如何配置自己的theme，感谢。

**Comment by gdh1995** [comment]
不通用，因为 vimium-c 用的 css class name、id 变短了些，一些样式的实现方式也变了。

需要你重新编写 css，参考 https://github.com/gdh1995/vimium-c/wiki/Style-the-UI-of-Vimium-C-using-custom-CSS#basic-structure

**Comment by touero** [comment]
ok, 部分正常设置了但是搜索框还是不行, 同时我不是很清楚如何在devtool中直接定位到包含某个的class, 目前我掌握了按f后出现按钮知道他是LH, 但是其他的还不知道其他元素如何快速定位和修改
![image](https://github.com/gdh1995/vimium-c/assets/61647484/2975212d-6e1d-4773-8c2d-b609942db5d7)
感谢您的回答

**Comment by gdh1995** [comment]
搜索框是独立的 iframe，需要用 `/* #omni */` 来标志“后续自定义样式属于 vomnibar”

**Comment by touero** [comment]
感谢
