### ISSUE TITLE
建议「用于定位链接和按钮的序号字符」可以设置透明度

### ISSUE THREAD

**Issue by Excel-VBA-2019** [gdh1995/vimium-c#106]
如图所示：

![](https://i.loli.net/2020/01/15/xdg2KY9AzjRUwv4.jpg)

![](https://i.loli.net/2020/01/15/f6QrcTOd18ZjqWt.jpg)

图一中的`G`、`SG`、`AG`、`H`、`SH`把小图标给挡住，一时之间都不知`G`、`SG`、`AG`、`H`、`SH`代表着什么。

建议插件增加一个关于透明度的设置，以数字表示。比方说取值范围[0, 100]，默认值取100，就是现在的呈现的形式（照顾没有变动需求的朋友），如果取0则完全透明。

**Comment by gdh1995** [comment]
Vimium C设置界面，显示高级选项后，在“自定义界面样式”里添加
``` css
.LH { opacity: 0.7; }
```

另外如果提示符号之间重叠了的话，Space、Shift+Space可以切换不同提示符号的Z轴叠放顺序，Tab可以重新初始化LinkHints（没有输入前缀字符时） / 切换提示符号的显隐关系（输入了至少一个前缀字符时）

**Comment by Excel-VBA-2019** [comment]
> Vimium C设置界面，显示高级选项后，在“自定义界面样式”里添加
> 
> ```css
> .LH { opacity: 0.7; }
> ```
> 
> 补充：这儿0.7表示“不透明”度时70%，也可以写成"`70%`"，最大是100%，最小0
> 
> 另外如果提示符号之间重叠了的话，Space、Shift+Space可以切换不同提示符号的Z轴叠放顺序，Tab可以重新初始化LinkHints（没有输入前缀字符时） / 切换提示符号的显隐关系（输入了至少一个前缀字符时）

谢谢回复。
