### ISSUE TITLE
Option for setting default color mode in settings (dark / light)

### ISSUE THREAD

**Issue by PsyNyde** [gdh1995/vimium-c#1060]
I know there's a button to toggle dark mode but having a default button instead of choosing the browser is providing would be great.

also my reason for making this issue i can't figure out how do I remove the bright border in dark mode:
<details><summary>Preview for dark mode:</summary>

![image](https://github.com/gdh1995/vimium-c/assets/75927811/b5c94a8f-f6fd-4866-9372-489eac762ea0)
</details>

the border isn't present with light mode. also when the body doesn't have `has-dark` class:
<details><summary>Preview for light mode:</summary>

![image](https://github.com/gdh1995/vimium-c/assets/75927811/504c982c-81e8-44b2-91c7-bd0cccfd8219)
</details>

**Comment by gdh1995** [comment]
1. You may partially select the checkbox of `Auto switch between light and dark mode`:

![image](https://github.com/gdh1995/vimium-c/assets/5547703/58da3428-16bc-4cfd-8ea4-7fc7f02f259b)

2. The light border is added by intent, to ensure you may recognize what content belongs to Vomnibar and what doesn't. 
- a. as you see, there's no border shadow in dark mode, so a slim border should be helpful.

**Comment by PsyNyde** [comment]
aah I'm extremely sorry. Idk how i missed the option. i switched it to light mode initially and it seem to work perfectly fine <3. sorry for the hustle.
