### ISSUE TITLE
openUrl doesn't work as expected for chrome urls

### ISSUE THREAD

**Issue by anglimath** [gdh1995/vimium-c#1061]
map *** openUrl url="chrome://history/syncedTabs"

will open "chrome://history/", which is a new issue in the latest version of Chrome (works as expected in the old version).

**Comment by gdh1995** [comment]
It's a bug of the `chrome://history/` page - if you refresh the page of `chrome://history/syncedTabs`, the page will also go to `chrome://history/`.

**Comment by anglimath** [comment]
Thank you!
