### ISSUE TITLE
可不可以增加一个退出 编辑模式的 按键, Add another key to mimic [ESC] function

### ISSUE THREAD

**Issue by fish1968** [gdh1995/vimium-c#1066]
**What command or commands**
Many video platforms use "ESC" key to exist full screen mode, and activation of vimium affects shortcut keys bund with a video spead extension (Video speed controller) that I am using. So in some cases, I want to adjust the speed of video, then I
1. Press "i" to enter edit mode, so my *Video speed controller* works [*Vimium-c*]
2. Adjust speed of the video [*Video speed controller*]
3. Press "Esc" to exit edit mode, so my vimium function activate, and usually the video would get out of full screen [*Vimium-c*]
4. If my video is not in full screen mode, use vimium to press certain key

If "Esc" is not the only key to exit "Edit" mode, experience to work with other extensions might be improved

**How should a feature do**
Let "\" key works the same as "Esc"
When a user has done such steps:

then Vimium C should do:

**Browser and OS**

- Browser name: Chrome 119
- OS name: Chrome OS Version 119

**Comment by fish1968** [comment]
虽然看视频的时候，基本上也不用 vimium 来调整啥，但是不回到 normal mode ，就感觉没安全感。。。

**Comment by gdh1995** [comment]
Recomment this usage of `enterInsertMode`:
```
map <a-/> enterInsertMode key="<a-/>"
```

And then, after pressing `Alt+/`, Vimium C will enter a speical `InsertMode` which can only be exited by a second `Alt+/` .

**Comment by fish1968** [comment]
This mapping is really useful! Truly thanks for you help!
Could you expalin the "key" attribute's usage to me? My guess is, this `key` is a parameter designed for `enterInsertMode`,  that specify the key to exit insert mode, and if `key` is not given, then by default it would be `esc`.

**Comment by gdh1995** [comment]
Yes the `key` is just what you said, and its value may be any valid single "long" key or punctuation mark.
- a long key is a key which can only be described by at least 2 characters, like `<a-/>`
- a punctuation mark is something like `.`, `;` and so on.

**Comment by fish1968** [comment]
Thanks for your information, and have a good weekend!
