### ISSUE TITLE
First custom search engine not working

### ISSUE THREAD

**Issue by leok610** [gdh1995/vimium-c#1069]
After changing the first item in the custom search engines option, that item no longer works.

It appears from testing that the problem is being the first item in the list, because when anything else is above that item, it functions as normal. I discovered this because I put the Amazon search engine first, since I alphabetize my custom options. At first I thought it was a syntax issue, but then I realized that moving the item to lower in the list made it work again.

This bug doesn't affect the first item in the default list (Bing), but I reproduced it with both Amazon and YouTube. Attached are some Minimal Working Examples to help you reproduce it.

**To Reproduce**

1. Go to Vimium C options
2. Import one of the MWE files attached with "single" in the file name
3. Open a new tab and navigate to a website.
4. Activate the Vomnibar with "o" and type in either "az" or "yt", depending on the settings file.
5. Observe that the listed shortcut does not work
6. Import one of the MWE files with "double' in the name
7. Go back to the other website tab.
8. Activate the Vomnibar and type in either "az" or "yt".
9. Observe that the custom search engine is now working.
10. Go back to the Vimium C options and delete the first blank line in the custom search engines.
11. Go back to the other website, retest the Vomnibar search, and it will not work.

**Search Not Working**
![az_not_working_settings](https://github.com/gdh1995/vimium-c/assets/18314476/e3d0ca98-7941-4832-92dc-67d3d3831922)
![az_not_working_vomnibar](https://github.com/gdh1995/vimium-c/assets/18314476/ebc7a71a-2199-4c99-8a51-754a09aa8c79)

**Search Working**
![az_working_settings_blank](https://github.com/gdh1995/vimium-c/assets/18314476/67e1a6db-e148-4a91-b953-2b89b6ab8086)
![az_working_vomnibar](https://github.com/gdh1995/vimium-c/assets/18314476/e13893c8-1da4-4ff4-8089-b08562f200a3)

**Browser, OS and Vimium C versions**

- Browser name: MS Edge
- Browser version: 120.0.2210.91 (Official build) (64-bit)
- Vimium C version: 1.99.99
- OS name and version: Windows 11 Pro
[vimium_c-test_single_yt.json](https://github.com/gdh1995/vimium-c/files/13830804/vimium_c-test_single_yt.json)
[vimium_c-test_double_az.json](https://github.com/gdh1995/vimium-c/files/13830805/vimium_c-test_double_az.json)
[vimium_c-test_double_yt.json](https://github.com/gdh1995/vimium-c/files/13830807/vimium_c-test_double_yt.json)
[vimium_c-test_single_az.json](https://github.com/gdh1995/vimium-c/files/13830808/vimium_c-test_single_az.json)

**Comment by gdh1995** [comment]
Um it's because of a very interesting typo of yours - the backslash in `Default search engine` ate the line of `az|xxx: xxxxxx`:
![image](https://github.com/gdh1995/vimium-c/assets/5547703/fa85f2c4-f90d-4114-8ea9-44c0313bebca)

This typo met a inner implementation detail of Vimium C, and I'll bypass it in a future version.

**Comment by leok610** [comment]
Great, thank you for finding the mistake and fixing the problem!
