### ISSUE TITLE
Vomnibar current tab history

### ISSUE THREAD

**Issue by ww7** [gdh1995/vimium-c#107]
Request of feature to show history of current tab. 
Same to what we can see if hold click on the `go back` button.
It's would be useful when you just browse much in current tab.

**Comment by gdh1995** [comment]
Well, unfortunately there is no browser API for an extension to access such "history“ on Chrome and Firefox.

**Comment by ww7** [comment]
Also no keyboard shortcuts.

**Comment by gdh1995** [comment]
Um, I don't know what shortcut to show the lists. Maybe there're not very many people who are using it.

**Comment by ww7** [comment]
I think peoples just use it with mouse.

**Comment by gdh1995** [comment]
Yes.

And the list is so private that few support new APIs to expose it to web extensions.

**Comment by ww7** [comment]
Thanks for explain!
