### ISSUE TITLE
How to avoid closing tab on `Ctrl+W`

### ISSUE THREAD

**Issue by gmankab** [gdh1995/vimium-c#1075]
so, vim deletes backwards on ctrl-w by default, but browsers closes tab on ctrl-w

i have a vim habit, so i usually accedentaly close tabs

please bind delete backwards on ctrl-w, or disable this sourcut at all so then tabs will not close

**Comment by gdh1995** [comment]
Chrome doesn't allow Vimium C to block its built-in `Ctrl+W` shortcut by `map <c-w> blank`, but there's indeed a solution:

You may open `chrome://extensions/shortcuts` and assign `Ctrl+W` to Vimium C's `Custom shortcut 1`, like:
![image](https://github.com/gdh1995/vimium-c/assets/5547703/c68609af-d01f-44d4-9732-d1c09401f357)

And then, to avoid a warning of `userCustomized1 has not been configured`, you may add such a key mapping:
```
shortcut userCustomized1 command="blank"
```

![image](https://github.com/gdh1995/vimium-c/assets/5547703/89db55ce-882b-416a-89bc-9b8207222ccd)

**Comment by gmankab** [comment]
thank you

**Comment by Sargates** [comment]
@gdh1995 
I know this is closed and sorry for ping,  but is there a way to implement `shortcut userCustomized1 command="blank"`
with some logic to close the window only if a text box is not focused? I also have the problem of accidentally closing tabs while typing, but I use CTRL-W in my browser too often to effortlessly live without it.
I'm not familiar enough with vimscript to know if it's even possible to embed a conditional check within the mapping and I don't know what (if any) APIs are exposed for checking if a text box is focused within the custom mappings.
