### ISSUE TITLE
filtered LinkHints stuck on `Hit <Enter> to proceed`

### ISSUE THREAD

**Issue by ww7** [gdh1995/vimium-c#108]
Try to use filtered LinkHints on Firefox (macOS)
Have issue if only one link left - stuck on `Hit <Enter> to proceed`

vimium-c 1.79.3

**Comment by gdh1995** [comment]
then both `<esc>` and `<enter>` have no influence to the HUD?

**Comment by ww7** [comment]
Tried on the google and other sites. But works on github.
`<esc>` works and clear input.

**Comment by gdh1995** [comment]
Hello, Vimium C v1.80.0 has been published on Firefox Add-ons and you may have a try.
