### ISSUE TITLE
Escaping browser's address bar

### ISSUE THREAD

**Issue by Lcchy** [gdh1995/vimium-c#1084]
**How should a feature do**

When a user has done such steps:

1. Click on the url bar to enter a url
2. Try to escape the url bar via `Escape` in order to scroll the page with Vimium-C keybindings
3. See that it is impossible

then Vimium C should do:

Maybe implement a global shortcut like Tridactyl does with `Ctrl+,` ?
Could an action triggered by a Firefox add-on shortcut allow for this?

I have tried to find solutions to this problem in the wiki and the issue tracker, sorry if I missed something.

**Browser and OS**

- Browser name:  Firefox 121.0.1
- OS name: Fedora 39
- Vimium C 1.99.997

**Comment by gdh1995** [comment]
Browsers including Firefox and Chrome haven't provided such an API to let a web-extension move focus from address bar to page content.

If you do want to use a shortcut, here's a trick which is far from perfect:
1. add `shortcut userCustomized1 command="reopenTab"` to Custom Key Mappings on Vimium C Options page
2. open `about:addons` manually and assign a shortcut to `Custom shortcut 1` of Vimium C, like this:

![image](https://github.com/gdh1995/vimium-c/assets/5547703/8ab92fef-5919-459a-a7ea-7b56f75c1222)
![image](https://github.com/gdh1995/vimium-c/assets/5547703/990f5092-f24c-44e6-a9fc-2d26cd7fa2cc)

Warning: although this trick does "move focus to page content", it will destroy you current page and "reopen" it, so all your writting and scrolling positions will be lost.

**Comment by Lcchy** [comment]
I have found another way that I am now using, in case anyone comes by this issue:

When the url bar is focused, hitting Ctr+H opens the history sidebar while also defocusing the url bar.
Hitting it again closes the sidebar and refocuses the page without a reload, it even restores the cursor position.
