### ISSUE TITLE
Send a link to an extention

### ISSUE THREAD

**Issue by Monirzadeh** [gdh1995/vimium-c#109]
hi
i usually use [Persepolis](https://github.com/persepolisdm/persepolis) as download manager.
can you add an option for send hint link to their extension or any other extension as an input.
is it possible?

**Comment by gdh1995** [comment]
This may be beyond what Vimium C should do, so I think you may use the command `LinkHints.activateModeToCopyLinkUrl` to copy a link URL and then paste it in another software like a download manager. On Windows, some download managers like [Thunder](http://x.xunlei.com/) can even auto find URLs in the system clipboard and then evoke itself.

**Comment by Monirzadeh** [comment]
hello
i use that for some of my script.
if we have an option to send an option to send link option with a tag to clipboard it can be useful.
i think about two methode
1. vimium c can send link to specific program (mpv,download manager,bash script,etc) it is a little complicated
2. better way user can set tag for send to clipbard
for example `pm` send to clipbard with `mpv` tag
`pd` send to clipboard with `downloadlink` tag
`pt` send to send to clipboard with `addtotorrent` tag
now i can write an script to check my clipboard if it has specific tag that can handle that link automatically to play with mpv, download with my download manager or add to my torrent client
it help to handle all of them inside browser and don't need to switch to another program

**Comment by gdh1995** [comment]
I like the 2nd - the feature is almost ready. You may try the latest feature "`Substitution for
clipboard text`" on Vimium C v1.80.0, and it supports `sed `-like syntax to do regexp replacing on your text to paste.

BTW, the first is impossible - extensions are limited by browsers and can not access other programs and processes.

**Comment by gdh1995** [comment]
Um, maybe I need to add a feature to make `LinkHints` apply a "temporary" `sed` rule to text, but not a static list.

**Comment by Monirzadeh** [comment]
i try to use that 
`c/test/youtube/g`
and i yank some link (https://www.youtube.com) 
it not change to https://www.test.com
do i something wrong?
is there any documentation about this feature?

**Comment by Monirzadeh** [comment]
> Um, maybe I need to add a feature to make `LinkHints` apply a "temporary" `sed` rule to text, but not a static list.
can i deligate this function to specific key
i am not use that for all link.
for example i use that yf for ynak link but sometime i need to send that to specific program 
if i use `youtube/mytag/g` it is copy that test.com
but if i can set specific key for example `s` for use that regex
in this mode  s can work like yank and yank hint mode but affect regex on result

**Comment by gdh1995** [comment]
Then you may write:
```
map Fs LinkHints.activateModeToCopyLinkUrl sed="p/youtube/mytag/g"
map Fd LinkHints.activateModeToCopyLinkUrl sed="p/bilibili/tag2/i"
```.

**Comment by gdh1995** [comment]
It would be like "c/youtube/test/"



---Original---

**Comment by Monirzadeh** [comment]
i use this code. at the first it is work
`map sy LinkHints.activateModeToCopyLinkUrl sed="c/youtube/test/g"`
but after a while it stop working.
if i set `c/youtube/test/g` in Substitution for clipboard text

**Comment by gdh1995** [comment]
this is only a demo: the "sed" option has not been implemented yet. it may arrive at v1.80.1



---Original---

**Comment by Monirzadeh** [comment]
Ok so it is not work on custom map key for now
so i will wait
just one point `\` is not accept in sed for and get error 
for example i try use `use sed="c/https:\/\/www.youtube.com/\[mytag\]https:\/\/www.youtube.com/g"`

**Comment by gdh1995** [comment]
The key point is, the whole `sed=...` is an option, and the substring after `=` will be unescaped using `JSON.parse`, so the real string which clipboard module gets is: `c/https://www.youtube.com/[mytag]https://www.youtube.com/g` .

In this case, a correct option should look like: `sed="c/^https:\\/\\/www\\.youtube\\.com/[mytag]https:\\/\\/www.youtube.com/"`. Note that `[` and `]` in "target string" don't need to be escaped - it's not a regexp, but the `newSubStr` parameter of `String::replace` ([doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace)).

BTW, `g` in regexp means to replace "all occurrences", and in this case it seems useless.

### About `sed` syntax

The `/` character next to `c/p/s/cp` can be replaced to another character, if only: 1) it's ascii, 2) and it's not a letter, so you may write ```sed="c`https://www\\.youtube\\.com`[mytag]...`i"```, in which ``` ` ``` is the delimiter.

**Comment by Monirzadeh** [comment]
thanks today i update to 1.80.1 and it's work prefect

**Comment by Monirzadeh** [comment]
hi @gdh1995 
i try to add some tag to any url with new feature.
 on my system sed work fine for me with this command
```bash
echo https://google.com | sed 's/^/\[mytag] /'
````
but it dosent has `s` option
i try to send any url to my script instead of write find and replace command for any kind of url 
i can't find any useful command to do this with find and replace
do i something wrong or it's not possible now

**Comment by gdh1995** [comment]
Um, I cannot get what you wanted.


What're you writing and what code lines didn't work?



---Original---

**Comment by Monirzadeh** [comment]
Problem solved
Sorry I delete the post
So sorry 💔
