### ISSUE TITLE
Shortcut to yank the link and link text as markdown

### ISSUE THREAD

**Issue by guidomz** [gdh1995/vimium-c#1091]
Request enhancement: keyboard shortcut to yank and the link text in one step, and output to clipboard in markdown format.
Essentially a combination of yv&lt;shift-v>y and yf&lt;Letters>.

**Comment by gdh1995** [comment]
You may try:
```
map F LinkHints.activateCopyLinkText access="[${innerText}](${href})"
```

**Comment by guidomz** [comment]
This really did the trick. Thanks.

**Comment by guidomz** [comment]
> You may try:
> 
> ```
> map F LinkHints.activateCopyLinkText access="[${innerText}](${href})"
> ```

This really did the trick. Thanks

**Comment by die4live** [comment]
> You may try:
> 
> ```
> map F LinkHints.activateCopyLinkText access="[${innerText}](${href})"
> ```

Is there a similar way to copy current tab's link and title in markdown format?
