### ISSUE TITLE
Shortcut to pop current tab to new window

### ISSUE THREAD

**Issue by gnodar01** [gdh1995/vimium-c#1092]
### New Command Request:

Create a key, such as `w` (lowercase) that performas the action of "Moving the current tab into a new window".

### Purpose:

The `W` key performs the action of: "Move tab to next window". 

I have a tiling window manager, that will automatically tile my windows as they are created. Sometimes I will, (1) create a new window with `cmd-n` (which the tiling window manager automatically arranges to my desired location on screen), (2) press `` cmd-` `` to cycle back to my previous window, (3) press `W` so that vimium-c will move the tab on the old window to the new window.

I would like it so that I can simply press `w`, and it will pop the current tab into a new window, and my tiling window manager will automatically move it to the desired location. All in one step.

## How should a feature do

**When a user has done such steps:**

Press `w` (or some other key, I don't care which)

**Then Vimium C should do:**

Pop the current tab into a new window

## Browser and OS

- Browser name:  Chrome - Version 121.0.6167.160 (Official Build) (x86_64)
- OS name: MacOS - Sonoma 14.3.1
- Vimium-C version: latest

**Comment by gdh1995** [comment]
You may bind a key sequence to the command named `moveTabToNewWindow`, like:
```
map w moveTabToNewWindow
```

![image](https://github.com/gdh1995/vimium-c/assets/5547703/7e208508-a8af-4722-91f7-c735ac4eccc1)

**Comment by gnodar01** [comment]
Ah, I feel silly. I don't see that information on my help screen, but I totally forgot to check the list of available commands in the wiki.  Thanks so much for answering so quickly!

**Comment by gdh1995** [comment]
If you didn't see the command `moveTabToNewWindow` in help dialog, then you may click:
![image](https://github.com/gdh1995/vimium-c/assets/5547703/431cbfb4-916d-4c0b-ae04-c8468ca95a35)

**Comment by gnodar01** [comment]
It's not a problem for me personally, but just fyi:

This is what I see:
![Screenshot 2024-02-14 at 11 33 56 AM](https://github.com/gdh1995/vimium-c/assets/8888732/f23f5da9-0f71-4138-9e92-0f3ce5dfe6f9)


After I map it, I see it, but I didn't have the text there when it was unmapped:
![Screenshot 2024-02-14 at 11 36 34 AM](https://github.com/gdh1995/vimium-c/assets/8888732/517b7e84-c600-43e8-8968-eb31461d0279)

I see you're using version 2.01, which as far as I can tell is not available on the Chrome/Firefox store yet. So maybe that was a new feature added then.

Anyway thank you for your help!

**Comment by gdh1995** [comment]
Um it's because I made the snapshot on Vimium C Options pages - Vimium C will only list all (mapped and non-mapped) commands on its options page.

As for v2.01, it's still under development.
