### ISSUE TITLE
Jump back to previous position with `` not working as expected

### ISSUE THREAD

**Issue by ni554n** [gdh1995/vimium-c#1097]
**Describe the bug**

Let's say, I'm in the middle of a webpage, I press `gg` to go up, then I press double tick expecting to jump back to the previous position as per the [README](https://github.com/gdh1995/vimium-c#keyboard-bindings):

```
``      jump back to the position before the previous jump
          -- that is, before the previous gg, G, n, N, / or `a
```

But vimium-c just shows `Created local mark [ last ]` without jumping to the position.
I've tried it on vimium, and it works as expected there.

**Browser, OS and Vimium C versions**

- Browser name: Chrome
- Browser version: 122.0.6261.69
- Vimium C version: 1.99.99
- OS name and version: Windows 11

**Comment by gdh1995** [comment]
Sorry it's a bug and no solution to bypass it in Vimium C v1.99.90+.

Vimium C v2.0+ will fix this, but it may still require a few months.
