### ISSUE TITLE
set selection caret to top of document after scrollToTop

### ISSUE THREAD

**Issue by wis** [gdh1995/vimium-c#110]
it's annoying when you go to top of document with `gg` (scrollToTop) after searching for something, and search again, it will match only whats after the previous selection caret position

demonstration:
gif:
![giff5](https://user-images.githubusercontent.com/9993663/73131849-f1e70d00-401a-11ea-876f-e21ca3b12e5c.gif)

1: re/load document:
![pic-window-200126-0849-13](https://user-images.githubusercontent.com/9993663/73131722-fad6df00-4018-11ea-9b86-eff409f0a12b.png)
2: scroll down to read
![pic-window-200126-0847-40](https://user-images.githubusercontent.com/9993663/73131719-f5799480-4018-11ea-8de2-8205c3465e1c.png)
3: _search for something at current document scroll position_ *_but it starts matching from the top_* <b>*</b>, _so keep pressing `n` until you go back to document scroll position you were reading at_:
![pic-window-200126-0848-34](https://user-images.githubusercontent.com/9993663/73131721-f8748500-4018-11ea-9e04-77f590428037.png)
4: exit visual mode and `gg`
![pic-window-200126-0849-13](https://user-images.githubusercontent.com/9993663/73131722-fad6df00-4018-11ea-9b86-eff409f0a12b.png)
5. search for something, it starts matching from the last visual selection cursor position, not the current scroll position of the document, (or the beginning of the document after `scrollToTop`) 
![4](https://user-images.githubusercontent.com/9993663/73131779-d2031980-4019-11ea-9591-8f6dcad4fb1f.png)

this issue can be solved as I described in the title or with a general solution for the issue I mentioned  in step 3 and marked with an <b>*</b>, which is to start matching from the current document scroll position.

**Comment by gdh1995** [comment]
Thanks, and I'll try to implement it in days.

**Comment by gdh1995** [comment]
Please try this version: [vimium_c-1.80.0-chrome-0eb482d.zip](https://github.com/gdh1995/vimium-c/files/4116681/vimium_c-1.80.0-chrome-0eb482d.zip).

Please:
1. unpack the .zip file to a folder
2. open `chrome://extension`, check "Developer mode" and then load the folder as an extension
3. open Vimium C Options page, and add these to "custom key mappings":

```
unmap gg
map gg scrollToTop sel="clear"
```

And then take a try to find and scroll.

**Comment by wis** [comment]
off topic:
it's so kind of you to build and link it, but I have to build it myself because I need to edit the source to be able to use my keyboard layout. 
$ `git diff`: 
```diff
diff --git a/content/mode_visual.ts b/content/mode_visual.ts
index b43f5a5b..269644f3 100644
--- a/content/mode_visual.ts
+++ b/content/mode_visual.ts
@@ -748,22 +748,27 @@ var VVisual = {
   },
 
 keyMap_: {
-  l: VisualAction.char | VisualAction.inc, h: VisualAction.char | VisualAction.dec,
-  j: VisualAction.line | VisualAction.inc, k: VisualAction.line | VisualAction.dec,
+  // l: VisualAction.char | VisualAction.inc, h: VisualAction.char | VisualAction.dec,
+  // j: VisualAction.line | VisualAction.inc, k: VisualAction.line | VisualAction.dec,
+  o: VisualAction.char | VisualAction.inc, n: VisualAction.char | VisualAction.dec,
+  e: VisualAction.line | VisualAction.inc, i: VisualAction.line | VisualAction.dec,
   $: VisualAction.lineBoundary | VisualAction.inc, 0: VisualAction.lineBoundary | VisualAction.dec,
   "}": VisualAction.paragraph | VisualAction.inc, "{": VisualAction.paragraph | VisualAction.dec,
   ")": VisualAction.sentence | VisualAction.inc, "(": VisualAction.sentence | VisualAction.dec,
   w: VisualAction.vimWord | VisualAction.inc, /* same as w */ W: VisualAction.vimWord | VisualAction.inc,
-  e: VisualAction.word | VisualAction.inc, b: VisualAction.word | VisualAction.dec,
+  // e: VisualAction.word | VisualAction.inc, b: VisualAction.word | VisualAction.dec,
+  s: VisualAction.word | VisualAction.inc, b: VisualAction.word | VisualAction.dec,
   /* same as b */ B: VisualAction.word | VisualAction.dec,
   G: VisualAction.documentBoundary | VisualAction.inc, g: { g: VisualAction.documentBoundary | VisualAction.dec },
 
-  o: VisualAction.Reverse, a: { w: VisualAction.LexicalWord, s: VisualAction.LexicalSentence },
+  r: VisualAction.Reverse, a: { w: VisualAction.LexicalWord, s: VisualAction.LexicalSentence },
+  // o: VisualAction.Reverse, a: { w: VisualAction.LexicalWord, s: VisualAction.LexicalSentence },
 
   y: VisualAction.Yank, Y: VisualAction.YankLine, C: VisualAction.YankWithoutExit,
   p: VisualAction.YankAndOpen, P: VisualAction.YankAndNewTab,
 
-  n: VisualAction.FindNext, N: VisualAction.FindPrevious,
+  f: VisualAction.FindNext, F: VisualAction.FindPrevious,
+  // n: VisualAction.FindNext, N: VisualAction.FindPrevious,
   "<f1>": VisualAction.HighlightRange, "<a-f1>": VisualAction.HighlightRange,
 
   v: VisualAction.VisualMode, V: VisualAction.VisualLineMode, c: VisualAction.CaretMode,
diff --git a/tests/unit/keyboard-layouts.js b/tests/unit/keyboard-layouts.js
index a869535e..ca925ca4 100644
--- a/tests/unit/keyboard-layouts.js
+++ b/tests/unit/keyboard-layouts.js
@@ -17,6 +17,14 @@ asdfghjklöä
 yxcvbnm,.-
 `,
 
+`# my colemak-mod-dh
+
+[]12345-67890=
+;qwfpb'luj
+/arstgkneio
+zxcdv\\mh,.
+`,
+
 `# Spanish
 
 1234567890'¡
```
tick  the ```[ x ] Ignore keyboard layout``` option
and mapkeys:
```
# remap default qwerty to colemak-dh
mapkey ` `
mapkey 1 [
mapkey 2 ]
mapkey 3 1
mapkey 4 2
mapkey 5 3
mapkey 6 4
mapkey 7 5
mapkey 8 -
mapkey 9 6
mapkey - 7
mapkey = 8
mapkey \ 9

mapkey q ;
mapkey w q
mapkey e w
mapkey r f
mapkey t p
mapkey y b
mapkey u '
mapkey i l
mapkey o u
mapkey p y
mapkey [ j

mapkey a /
mapkey s a
mapkey d r
mapkey f s
mapkey g t
mapkey h g
mapkey j k
mapkey k n
mapkey l e
mapkey ; i
mapkey ' o

mapkey z z
mapkey x x
mapkey c c
mapkey v d
mapkey b v
mapkey n \ 
mapkey , h
mapkey . , 
mapkey / . 


mapkey ~ ~
mapkey ! {
mapkey @ }
mapkey # !
mapkey $ @
mapkey % #
mapkey ^ $
mapkey & %
mapkey * _
mapkey ( ^
mapkey ) &
mapkey _ *
mapkey + (
mapkey | )

mapkey Q :
mapkey W Q
mapkey E W
mapkey R F
mapkey T P
mapkey Y B
mapkey U "
mapkey I L
mapkey O U
mapkey P Y
mapkey { J

mapkey A ?
mapkey S A
mapkey D R
mapkey F S
mapkey G T
mapkey H G
mapkey J K
mapkey K N
mapkey L E
mapkey : I
mapkey " O

mapkey Z Z
mapkey X X
mapkey C C
mapkey V D
mapkey B V
mapkey N |
mapkey < H
mapkey > < 
mapkey ? > 
```
can you think of a solution for different layouts? I'm not familiar on why do vimium and vimium-c use the key code and not the key character of the keyup event, can you explain that?

on topic:
it work's :+1: 
about the general solution I mentioned in the top post, after some more thought, I think it can be implemented but it would slow down the document text match method a little bit, because you'd need to get the position of each parent node of each matched text relative to to the document, like so:
``` .js
function getCoords(elem) {
  let box = elem.getBoundingClientRect();
  return {
    top: box.top + window.pageYOffset,
    left: box.left + window.pageXOffset
  };
}
```
and the first match selection jump should be to the *nearest* match to the current window scroll positions (window.scrollX & window.scrollY), then to the next after it as you'd expect from vim when you press `n` repeatedly.

I want to contribute, but I don't like working with a slow code-reload-test cycle, would you consider using Webpack with a Typescript loader instead of Gulp going forword? I developed a Typescript boilerplate extension that uses Webpack and reloads the extension automatically when you make a change to any file in the dist directory.

**Comment by gdh1995** [comment]
### about key mappings

How will you feel if you uncheck the `Ignore keyboard layout` option ? The options means that Vimium C uses [KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) to recognize key events. While if unchecked, Vimium C uses [KeyboardEvent.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key), which will follow your system keyboard layout.

I think the `mapkey` items you listed would only re-translate `.code` into your current keyboard layout.

Vimium C does use `.keyCode` in a few cases, but it prefers `.key` and `.code` to `.keyCode`.

### about compilation

I haven't learnt and used Webpack (my skills are too old).  I once saw `create-react-WebExtension` but since Vimium C doesn't use frontend JS frameworks, I haven't spent time in learning it.

If you have some knowledge we may discuss it in a new specific issue. Any PR is also welcomed.  Thanks very much.

BTW, I prefer ways which don't increase sizes or running cost of compressed JS code (or if only I can write JS code to edit code and remove extra parts). Therefore, I expect no `export` or `define` - this is just why I'm stilling using Gulp - the common practice of Webpack looks not so suitable for me.

Another keypoint is, currently the main of my rest time is used to implement new features - there're always something to add - so I won't spend much time in investigating Webpack until there has been a persuasive solution. Sorry for the inconvenience.

### about `scroll and find`

The current behavior is to follow the "last" position of "caret". On vim, the caret moves when you "scroll" up or down, so you see that it always searches from current "scroll position". But on browsers, a page can have a scroll position of `x=..., y...`, as well as a "caret" position of `what node + how many offset`. 

Just now I tested on VS Code and Notepad++, and on them `Ctrl+F` also starts from not scroll position but caret position.

**Comment by wis** [comment]
**about key mappings**
oh yea, I remember now that it used to work with my keyboard layout by default but I had do what I described above to be able to use n,e,i,o instead of h,j,k,l in visual mode.
** about compilation **
I understand, the setup is quite simple you wouldn't need to maintain it instead of working on features/bugs.  
I agree on code size.
wouldn't you like to use modules and use `import` to import modules, functions or npm packages with Webpack? then you'd be able to use a very useful package that I love, [webextension-polyfill-ts](https://github.com/Lusito/webextension-polyfill-ts), check it out.

**about scroll and find**
I understand, but this is not Vim's behavior, when your cursor/view is in the middle of a file and you search for something with `/<somthing>` it jumps to the nearest match.
right now when you search you search for something with '/', it looks through the whole dom for text matches, right? what if you get with it the coords relative to the top of the document of the parent node of each match's text node, and sort them by how close they are to the window.scrollY and maybe window.scrollX? 
I know that you can't get a text node's coords and that a text node's parent element (which you can get its coords) can be in a big paragraph, but we can borrow some code from the [caret browsing extension](https://chrome.google.com/webstore/detail/caret-browsing/fklpgenihifpccgiifchnihilipmbffg?hl=en) to get the exact coords of part of a text node.

**Comment by gdh1995** [comment]
1. Another usage of `mapkey` for single modes has been in my plan, which I finish `vimium://cd`. It'll be a hard work and takes about a week or more.
2.
- 1. Can web extension use `import` ? I haven't tried it. If we use it and let webpack compile it into lots of `export/define` and `require`, then it's not useful, as for me.
- 2. I once think I can convert all code with `export` and `import`, and then use tree-shaking (like `rollup`?) to reduce all the code into one "flat" file. Only an idea.
- 3. the `polyfill` is a bit large. I need more time to read it.
3.
- 1. It sounds possible, but heavy work ...
- 2. I have another idea: maybe we can move caret to "first character" of the current viewport, and then `window.find` will follow the position.
  - 1. According to my memory, some code `Vimium` is for this feature, though I'm not sure. I'll read Vimium again.

**Comment by gdh1995** [comment]
The idea to set caret position to first text of current viewport seems to depend on #3 - both of them requires a method to iter all visible text nodes.

I'll take a try when the new usage of `mapkey` gets finished.

As for `mapkey`, I'd like to add this: `mapkey <f'v> s` or `mapkey <f:v> s`, and it means to only map `f` to `s` in VisualMode (`l` -> `LinkHints`, `o` -> `Vomnibar`, `f` -> `FindMode`, and `v` -> `VisualMode`). What do you think about? Which one do you prefer between `<f'v>` and `<f:v>` ?

**Comment by gdh1995** [comment]
Here's a base version of new `mapkey` usages: [vimium_c-1.80.0-fx-69eecd3.zip](https://github.com/gdh1995/vimium-c/files/4132258/vimium_c-1.80.0-fx-69eecd3.zip) [vimium_c-1.80.0-chrome-69eecd3.zip](https://github.com/gdh1995/vimium-c/files/4132259/vimium_c-1.80.0-chrome-69eecd3.zip), and with it you may map a same key to different keys in different modes. For example, `mapkey <f:o> <f2>` will only make Vomnibar treat `f` as `<f2>`.

Valid mode ids are:
https://github.com/gdh1995/vimium-c/blob/69eecd36ab6d5b3ae9f30339f413f7e16414f75a/types/vimium_c.d.ts#L475-L481

Then `Insert = "i", Link = "l", Omni = "o", Find = "f", Visual = "v" and Marks = "m"`.
