### ISSUE TITLE
hotkey for move tab conflicts with youtube speed control hotkeys

### ISSUE THREAD

**Issue by Zedroid** [gdh1995/vimium-c#1103]
on youtube using 
<< >>
move tabs instead of speeding up or slowing down
how do i disable it, below is not working
![image](https://github.com/gdh1995/vimium-c/assets/14794946/5c44e509-3116-4f87-a848-a8a78fa3e0dc)

**Comment by Zedroid** [comment]
![image](https://github.com/gdh1995/vimium-c/assets/14794946/fa3c484c-8a56-413b-94c1-b312eaa830e9)
so sorry i figured it out by myself

**Comment by gdh1995** [comment]
Your first usage of exclusion rules should also work, if only:
1. click `Save Options`, and then the `keys` column shoud become `< >`
2. test `<<` and `>>` on a HTTP webpage, but not Vimium C Options page, because the `patterns` requires HTTP/HTTPS protocol.
