### ISSUE TITLE
输入具体的网址的一部分后，反而不在结果中显示

### ISSUE THREAD

**Issue by YandLiu** [gdh1995/vimium-c#1110]
Win 11，Firefox 123.0.1，扩展最新版
调出来这个框框的时候，是可以看到这个斗鱼直播的历史记录的
![图片](https://github.com/gdh1995/vimium-c/assets/26127104/e540d4e3-65fa-4caa-acbc-42203363f062)

但是输入douyu.com之后，反而没有了
没有添加任何屏蔽词

**Comment by gdh1995** [comment]
没输入词的时候，会显示已关闭的标签页（标记了`↶`），而有搜索词后只搜索历史记录、收藏夹和打开的标签页。

这个现象说明“已关闭的标签页”里有这条，但历史记录里没有，不确定为什么。有两个猜测：
- 这条历史记录刚刚被别的插件自动或者手动删了
- vimium c 的读历史记录的代码出错了，导致实际上没取到任何历史记录，也就搜不出来

所以麻烦你测测其它历史记录能否被正常搜出来。

**Comment by gdh1995** [comment]
我自己的 firefox 123 上复现不了这个问题

**Comment by YandLiu** [comment]
我有点明白了，应该是Firefox的问题
这个斗鱼直播是Ctrl+Shift+N新建了个浏览器窗口时，Firefox自动打开的网页，我看到是个斗鱼直播后马上关掉了
想着还是可以看看，就又想打开，然后就出现了这个问题

**Comment by gdh1995** [comment]
默认的 firefox 里 ctrl+shift+n 不是创建新窗口吧，我 windows 下按它没反应；

搜索词为空时，显示最近关闭的标签页；如果有具体搜索词，就只在“历史记录”里搜，所以假如如你所说，新标签页不会存到历史记录，那么确实会出现这个问题。

但是我刚才测试里，手动设置新窗口的页面url，发现它能正常进历史记录，就不确定你这个为什么了。

测试用了个全新的 firefox 123，win11，设置页面上改动只有这一条：
![image](https://github.com/gdh1995/vimium-c/assets/5547703/9ea0be3f-1700-4683-bfed-56c38d259c85)

**Comment by YandLiu** [comment]
Ctrl+Shift+N在Firefox应该是恢复刚关闭的窗口（非页面）
我遇到的问题应该是曾经清掉过douyu.com的历史记录，但使用该快捷键恢复窗口时这个并不会再写到历史记录里

**Comment by gdh1995** [comment]
确实存在这个现象，而且 Firefox 63 上就有了，看起来是 Firefox 的 bug。
