### ISSUE TITLE
mapKey and link hinting

### ISSUE THREAD

**Issue by Opisek** [gdh1995/vimium-c#1113]
I use a Dvorak keyboard layout and was happy to see that I can use `mapKey` or the ignore keyboard layout setting to use Vimum-C with all my muscle memory.

Unfortunately, one thing still troubles me: Link hinting displays the letters after `mapKey`, not before. For example, on my layout, the letter `o` maps to the QWERTY letter `s`. So if a link hint tells me to press the letter `o`, it will apply `mapKey` to it and end up pressing `s`.

Furthermore, when I enable "Use the link's name and characters for link-hint filtering" and try typing the link name using my layout, for example "abc", it will still be remapped using `mapKey` to "ani" in my case.

Could a setting for disabling `mapKey` for link hinting be added?
Another option (for me) would be to have the option to ignore keyboard layout always, except for link hinting.

**Comment by chjayakrishnajk** [comment]
Read this wiki page https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout

i - insert mode
l - link hints
f - find mode
v - visual mode
m - marks
o - omnibar

this is the format mapkey <newkey:mode> <oldkey>
Eg: mapkey <n:v> <j>, this will map n to j

**Comment by Opisek** [comment]
Thanks, that's great! Somehow I missed it reading the wiki.
