### ISSUE TITLE
打开的本地网页文件无法使用键盘操作

### ISSUE THREAD

**Issue by dufei99** [gdh1995/vimium-c#1115]
'file:///D:/test/index.html'浏览器中打开本地html文件的浏览，无法使用这个快捷键操作。希望能适配一下。

**Comment by gdh1995** [comment]
浏览器的扩展设置里，点进扩展程序详情，里边有一个允许访问文件网址，开启就好



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月28日(周四) 中午11:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [gdh1995/vimium-c] 打开的本地网页文件无法使用键盘操作 (Issue #1115)




 
'file:///D:/test/index.html'浏览器中打开本地html文件的浏览，无法使用这个快捷键操作。希望能适配一下。
