### ISSUE TITLE
question: is it possible to remap vomnibar's shift+delete

### ISSUE THREAD

**Issue by agzam** [gdh1995/vimium-c#112]
I like the feature where you can close tabs in Vomnibar, by pressing `Shift+Delete`. I think that is not very convenient keybinding for Mac users, because it forces you to press `Fn+Shift+Delete` (without `Fn`, `Delete` works as `Backspace`). It makes it even harder if you use an external keyboard that doesn't even have `Fn` key, e.g.: Kinesis Advantage.

Is it possible somehow to rebind that action to be something else, maybe `Ctrl+D`?

**Comment by gdh1995** [comment]
`mapkey <c-d> <s-delete>` should work.

And as I said in https://github.com/gdh1995/vimium-c/issues/110#issuecomment-579234137 , there's a plan to support pre-mode `mapkey`s.

**Comment by agzam** [comment]
Oh.. cool. This worked. Thank you very much!
