### ISSUE TITLE
LinkHints.activateOpenUrl, background and queue

### ISSUE THREAD

**Issue by anglimath** [gdh1995/vimium-c#1122]
The objective: 

map xxx for the following purpose, 
Open multiple urls in background tabs without simulating the click (in a queue). 

I know one possible way to achieve this is 
1. map xxx LinkHints.activateOpenUrl reuse="new-bg", 
2. press alt to change to queue mode. (Message: Open multiple URLs directly)

However, how can I use a single key to achieve this? (not simulating a sequence of keys)

I have tested all possible combinations of the followings, none works exactly as expected
LinkHints.activateOpenUrl
LinkHints.activateWithQueue 
mode="open-direct"
mode="queue" 
reuse="new-bg"
mode="cur-queue"
...

Could you please give me some hints? Many thanks!

**Comment by gdh1995** [comment]
You may try:
```
map xxx LinkHints.activateOpenUrl reuse="new-bg" mode=62
```

But the usage of `mode=<number>` is not recommended, because the number may changes when I think it's necessary...

I'll add a new way to achieve this effect using `mode=<string>`.

**Comment by anglimath** [comment]
Thanks! It works.
