### ISSUE TITLE
Request command to toggle "Disable for once"

### ISSUE THREAD

**Issue by ww7** [gdh1995/vimium-c#113]
Web applications often use keyboard shortcuts. Command for toggle Vimium-C would be helpful.

**Comment by gdh1995** [comment]
`enterInsertMode` may help.


Or add `map <f7&gt; openUrl url="vimium://status toggle <f7&gt;"` (Vimium C should auto-convert some spaces in `"..."` into `\u0020`).



---Original---

**Comment by ww7** [comment]
thanks, both works  
`map Z openUrl url="vimium://status\u0020toggle"`
`map i enterInsertMode`

**Comment by gdh1995** [comment]
Um, the content from mail looks too ugly, so I've updated.

If `map Z openUrl url="vimium://status\u0020toggle"`, then `Z` will turn off Vimium C "totally", so you will have no shortcut to re-enable it. For this issue, there's an advanced usage: `map Z openUrl url="vimium://status toggle ^ Z"`, and then `Z` can always be used to toggle status.

**Comment by gdh1995** [comment]
Oops, on v1.80.1 released yesterday, the usage of `toggle ^ Z` still works, but `toggle ^ <f7>` breaks...

**Comment by ww7** [comment]
I'm tried `map Z openUrl url="vimium://status toggle ^ Z"` – for me it's only disable or enable once, not toggle (macos Firefox)
It's should works with Shift+Z in toggle mode?

**Comment by gdh1995** [comment]
It should with Shift+Z.
Next to "^" is a list of keys, which is separated by " " (exact one space). So "Z" means Shift+Z.
V1.80.1 has a bug when parsing "<...&gt;" in this list, so long keys and a-/c-/m- keys won't work. I've fixed it in master branch, but a publish process on Chrome Web Store is very long and I can not begin to publish v1.80.2 until v1.80.1 has passed their reviews.



---Original---

**Comment by gdh1995** [comment]
Sorry, after a new test, I found the usage has been totally broken...

`Z` will be translated into `z`, so only `map z openUrl url="vimium://status toggle ^ z` works, but a lower-case key is not suitable in daily use...

I'm fixing it. And it seems a new version is urgent.

**Comment by gdh1995** [comment]
V1.80.2 has been published on Firefox Add-ons, and you may have a try.
