### ISSUE TITLE
How to add different clickable elements for different hosts?

### ISSUE THREAD

**Issue by fenajy** [gdh1995/vimium-c#1132]
I tried this
```
env bcc host=":https://*.bandcamp.com/"
map f LinkHints.activate clickable=".discover-pill,.playbutton,.message"

env kgg host=":https://kinogo.biz/"
map f LinkHints.activate clickable="ul.player-tabs>li"

env gtt host=":https://www.github.com/"
map f LinkHints.activate clickable="code"
```
but I got the following errors
```
2 Errors:
Key "f" has been mapped to LinkHints.activate.
Key "f" has been mapped to LinkHints.activate.
```
how to do it right?

**Comment by chjayakrishnajk** [comment]
try to unmap 'f' by "unmap f"

**Comment by fenajy** [comment]
```
env bcc host=":https://*.bandcamp.com/"
map f LinkHints.activate clickable=".discover-pill,.playbutton,.message"

env kgg host=":https://kinogo.biz/"
unmap r
map f LinkHints.activate clickable="ul.player-tabs>li"

env gtt host=":https://www.github.com/"
unmap f
map f LinkHints.activate clickable="code"
```
The error goes away
but then all the added settings stop working
Only the last one works

**Comment by chjayakrishnajk** [comment]
https://github.com/gdh1995/vimium-c/wiki/Map-a-key-to-different-commands-on-different-websites

Check the last example, you've use some runKey

**Comment by fenajy** [comment]
> [https://github.com/gdh1995/vimium-c/wiki/Map-a-key-to-различные-команды-на-различных-веб-сайтах](https://github.com/gdh1995/vimium-c/wiki/Map-a-key-to-different-commands-on-different-websites)
> 
> Проверьте последний пример: вы использовали runKey

I went through the link but still can't get it to work
can you make an example for my case?

**Comment by fenajy** [comment]
> https://github.com/gdh1995/vimium-c/wiki/Map-a-key-to-different-commands-on-different-websites
> 
> Check the last example, you've use some runKey

I went through the link but still can't get it to work
can you make an example for my case?

**Comment by gdh1995** [comment]
There's no "scoped map" syntax in custom key mappings, so you may not use `env` to indicate "mappings below is under some conditions".

To use `runKey`:
```
env bcc host=":https://*.bandcamp.com/"
env kgg host=":https://kinogo.biz/"
env gtt host=":https://www.github.com/"

map <v-f_bcc> LinkHints.activate clickable=".discover-pill,.playbutton,.message"
map <v-f_kgg> LinkHints.activate clickable="ul.player-tabs>li"
map <v-f_gtt> LinkHints.activate clickable="code"
run f LinkHints.activate expect="bcc:<v-f_bcc>;kgg:<v-f_kgg>;gtt:<v-f_gtt>"
```

**Comment by gdh1995** [comment]
LinkHints also supports `clickableOnHost` parameter, and with it you may simplify the mapping above:
```
map f LinkHints.activate clickableOnHost="bandcamp.com##.discover-pill,.playbutton,.message;kinogo.biz##ul.player-tabs>li;www.github.com##code"
```
