### ISSUE TITLE
Unable to search selected text in search engine 

### ISSUE THREAD

**Issue by chjayakrishnajk** [gdh1995/vimium-c#1133]
**Describe the bug**
I was trying to select text using LinkHints.activateSelect and then search using autoOpen, but it is not working I have to press 'enter' in order to copy it and then use autoOpen to search it in search engine in new tab

**To Reproduce**

map sg autoOpen keyword="google"
map yv LinkHints.activateSelect

https://github.com/gdh1995/vimium-c/assets/69712032/1c372a60-c31e-4970-8d32-eb3b87e08e72

Go to any website and press 'yv' to select text and press the key according to the hints and then press sg it won't work, now try to press 'enter', this copies the text and when you press 'yv' again now it searches

**Browser, OS and Vimium C versions**

- Browser name:  Brave
- Browser version: version 1.65.132 Chromium: 124.0.6367.202 Official Build 64-bit
- Vimium C version: C 1.99.99
- OS name and version:  Windows and 11

**Comment by chjayakrishnajk** [comment]
When I click yv and select a text, it is in visual mode, so the 'sg' is not working. When I press 'esc' and then press sg it is searching, because it quit visual mode. Can't I search in the visual mode

**Comment by gdh1995** [comment]
In Vimium C v1.99, You may use `P` to search selected word in a new tab when in visual mode.

And in Vimium C v2, it will be `p` - no shift needed by default.

You may write such a mapping to adjust `p`'s behavior:
```
map v enterVisualMode reuse="new-fg" keyword="google"
```
