### ISSUE TITLE
How do you change search engine for 'p' and 'P' shortcuts?

### ISSUE THREAD

**Issue by LaptopDev** [gdh1995/vimium-c#1134]
I don't know where to specify to use a different search engine than google. 
I have my default search engine in Firefox set to search.brave.com already but the shortcut will search google for my clipboard instead of search.brave.com.

appreciate the help

**Comment by chjayakrishnajk** [comment]
Go to Vimium-C options, you'll see Default search engine, change it to your preference

**Comment by LaptopDev** [comment]
thanks, works as expected with
`https://search.brave.com/search?q=$s Brave`
