### ISSUE TITLE
Featuer request: commands for simple text-editing

### ISSUE THREAD

**Issue by parisni** [gdh1995/vimium-c#114]
hi

first of all, this plugin is promizing.

one thing I guess is missing is to allow shortkey in editing mode.
for example when writing in a textarea, I d´like to add shortkey for 
- delete previous word
- go to previous/next word
- go to previous/next line

this beavior exist in the vomnibar, that would be fantastic in any textarea/input fields

thanks

**Comment by gdh1995** [comment]
Sorry but Vimium C is not designed to be an "online text editor". In the meanwhile, there have been some web extensions supporting such VIM-like editing usages, and you may use https://chrome.google.com/webstore/detail/wasavi/dgogifpkoilgiofhhhodbodcfgomelhe .

Similar topics have been discussed for some days in https://github.com/philc/vimium/issues/3405 .

**Comment by gdh1995** [comment]
It's easy to only add 3~4 new commands for word-level operations to Vimium C, but I'm not sure whether it's worth - a full-featured editor is very hard to implement, and large, of course.

BTW, on Chrome Ctrl+Left, Ctrl+Right, Ctrl+Backspace can do such actions.

**Comment by parisni** [comment]
thanks for the pointer. I am looking for much basic solution.
the cvim extension provides such shortkeys and I mapped them to
<M-b> : previous word
<M-Delete> : delete previous word

and so on.

Do you think that might be easy to implement in your library ?

**Comment by gdh1995** [comment]
Well, it's indeed easy now, and I can add it tomorrow, so the new command will be in v1.81.2. I'll upload a .zip file for you to test.

The Chrome Web Store takes 3~5 days to verify every new version of Vimium C, and for now they're verifying v1.81.1 ...

**Comment by parisni** [comment]
wow. incredible. thanks

**Comment by gdh1995** [comment]
Here's a test version: [vimium_c-1.80.1-chrome-7609c36.zip](https://github.com/gdh1995/vimium-c/files/4142624/vimium_c-1.80.1-chrome-7609c36.zip), [vimium_c-1.80.1-fx-7609c36.zip](https://github.com/gdh1995/vimium-c/files/4142625/vimium_c-1.80.1-fx-7609c36.zip). And please load it following steps in https://github.com/gdh1995/vimium-c/issues/110#issuecomment-578690423.

Then you can add this to custom key mappings:
```
mapkey <a-b> <f3edit>
map <f3edit> editText sel args=["move","backward","word"]
mapkey <a-f> <f3editf>
map <f3editf> editText sel args=["move","forward","word"]
```

The `<f3edit>` is a fake key name, just to notify Vimium C that this key should trigger command even when you are typing in an input/textarea. This kinds of key names should match `/^f\d/`.

The `sel` option means `args` should be passed to [Selection::modify](https://developer.mozilla.org/en-US/docs/Web/API/Selection/modify), while if no such an option or it's false, then Vimium C runs `document.execCommand(args[0], false, args[1])`.

Another option `dom` is also a boolean option, and it tells Vimium C to always runs `args` even when you are not typing in an input/textarea.

**Comment by parisni** [comment]
working great so far  for moving ! 

 I guess cool features are also:
- delete word foward/backward (<a-d> / <a-delete<)
-  go up/down (<c-p> / <c-n>)

many thanks, hope this will be helpful to others

**Comment by gdh1995** [comment]
A new version supporting sequential actions: [vimium_c-1.80.1-chrome-93c7356.zip](https://github.com/gdh1995/vimium-c/files/4143423/vimium_c-1.80.1-chrome-93c7356.zip)
```
# delete a forward word
mapkey <a-f> <f3editf>
map <f3editf> editText run="extend,forward,word,exec,delete,"
```

The `run` option means a list of directive, which will be splitted into a list of 3-directive groups, and in each 3-directive group the first can only be `extend`, `modify` or `exec`, and `extend` & `modify` are for `Selection::modify`, `exec` are for `Document::execCommand`, and the later 2 directives are function arguments.

You can assemble any numbers of directives as you like, and please read https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand for the list of available document commands and https://developer.mozilla.org/en-US/docs/Web/API/Selection/modify for available selection operations.

**Comment by parisni** [comment]
fantastic! 
However the vomnibar does not provide the shortkey anymore. Looks like they have been overwride ?  

Here is my config:
```
mapkey <a-b> <f3edit>
map <f3edit> editText run="move,backward,word,exec,move,"

mapkey <a-f> <f3editf>
map <f3editf> editText run="move,forward,word,exec,move,"

# delete a forward word
mapkey <a-d> <f3rmf>
map <f3rmf> editText run="extend,forward,word,exec,delete,"

# delete forward character
mapkey <c-d> <f3rmcf>
map <f3rmcf> editText run="extend,forward,character,exec,delete,"

# delete backward word
mapkey <a-backspace> <f3rm>
map <f3rm> editText run="extend,backward,word,exec,delete,"

# delete backward character
mapkey <c-h> <f3rmc>
map <f3rmc> editText run="extend,backward,character,exec,delete,"

mapkey <c-e> <f3end>
map <f3end> editText run="move,forward,lineboundary,exec,move,"

# not used because mapped to select text. use home instead
# mapkey <c-a> <f3bg>
# map <f3bg> editText run="move,backward,lineboundary,exec,move,"


mapkey <c-k> <f3rmline>
map <f3rmline> editText run="extend,forward,lineboundary,exec,delete,"
```

**Comment by gdh1995** [comment]
Then use `<a-d:i>` instead of `<a-d>` - `:i` means it's only for InsertMode.

Doc: https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout (the paragraph of "Since v1.80.1, this directive takes effects in all modes, ")

**Comment by parisni** [comment]
perfect !

**Comment by parisni** [comment]
Any idea how to mapkey for up/down (appreciable to edit online markdown files for eg)?
I tried those but did not work:

```
mapkey <c-n:i> <Down>
mapkey <c-p:i> <Up>
```

**Comment by gdh1995** [comment]
`Selection`'s document is in https://developer.mozilla.org/en-US/docs/Web/API/Selection/modify, and `move,backward,line` and `move,forward,line` should work as up/down.

BTW, `mapkey` only works inside Vimium C, while there's no API to send mapped target keys to browsers or other extensions.

**Comment by parisni** [comment]
many thanks
