### ISSUE TITLE
Keyboard shortcut to Toggle LinkHints Filtering

### ISSUE THREAD

**Issue by bhuwan-saini-alation** [gdh1995/vimium-c#1147]
**How should a feature do**

When a user has done such steps:

If I press a keyboard shortcut e.g, Option + Shift + V, I can toggle Vimium-C between alphabetic link hints or search through link text and press enter. 

then Vimium C should do:

_Toggle this setting_ 

![image](https://github.com/gdh1995/vimium-c/assets/161409004/3e05a5f0-1654-47c1-9e77-3f32629b0e11)

**Browser and OS**

- Browser name: Chrome 125.0.6422.142 
- OS name: Mac OS Sonoma 14.5

**Comment by gdh1995** [comment]
Please try such a key mapping:
```
map <a-s-v> toggleSwitchTemp key="filterLinkHints"
```

Then `Alt+Shfit+V` will switch the mode of following LinkHints modes:
- only on a current tab
- if a tab is refreshed, then the configuration will be reset
- this mapping can only be triggered when Vimium C is in normal mode

**Comment by bhuwan-saini-alation** [comment]
Awesome, exactly what I needed!
