### ISSUE TITLE
broken excluded for Youtube keyboard shortcuts

### ISSUE THREAD

**Issue by raingart** [gdh1995/vimium-c#115]
My settings worked correctly until version v1.80.0. _I downloaded this release and checked everything works._

Already in version 1.80.1 they broke.

Does not work `Shift + >` and `Shift + <` - speed-up/down

ex options:
Patterns:
`^https?://www\.youtube\.com/*`
keys:
`- < < <s-\> > > F N \ f n s t`

**Comment by gdh1995** [comment]
Yes there's a regression about it and should have been fixed in the master branch. v1.80.2 will be released in the next week.



---Original---

**Comment by gdh1995** [comment]
Hello, v1.80.2 includes a fix for this, and has been published on Chrome Web Store and Firefox Add-ons. Please take a try.

**Comment by raingart** [comment]
Yes, the error is gone, thanks
