### ISSUE TITLE
Feature request: map <ctrl-i> <enter> in Vomnibar

### ISSUE THREAD

**Issue by henrysheehy** [gdh1995/vimium-c#1155]
# Feature request for Vomnibar

In Vomnibar, map `<ctrl-i>` to `<enter>` search term, instead of its current function, which is to tab down the list.

# Thank you

Thank you for this great app!

**Comment by gdh1995** [comment]
You may try such a key mapping rule:
```
mapKey <c-i:o> <enter>
```

**Comment by henrysheehy** [comment]
That's amazing, thank you, and sorry for having missed it!
