### ISSUE TITLE
(SOLVED) how to view URL of selected link?

### ISSUE THREAD

**Issue by alon-to** [gdh1995/vimium-c#1162]
**UPDATE**: as is often the case with this impressive extension, the functionality I was looking for was already available. Both `LinkHints.activateOpenVomnibar url` and `LinkHints.activateHover` work very well for my desired use case of viewing the URL of a link without clicking on it. Thank you!

-------------
**Desired functionality**
1. User activates link hints on the page
2. User selects a link
3. Vimium-C displays the link's URL (perhaps in the Vomnibar or HUD)

**Additional context**
* I regularly want to know the destination URL of a link on the page
* My current workaround for the above is to activate `LinkHints.activateCopyLinkUrl`, then paste it into Chrome address bar. Drawbacks with this approach include 1) extra steps, 2) potentially important clipboard content is overwritten.

Happy to share more if helpful, and would be great to learn if this is already possible (this extension constantly surprises me with already existing functionality). Thanks for reviewing this!

**Comment by gdh1995** [comment]
Why do you want to "paste it into Chrome address bar"?

- To open a link without clicking, you may use `LinkHints.activateOpenUrl`
- To view and edit a link's URL, you may use `map <xxx> LinkHints.activateOpenVomnibar url`
- To just show it on HUD (or browser's URL HUD if possible), you may use `LinkHints.activateHover`

**Comment by alon-to** [comment]
Thanks so much! I've updated the title of this issue and will now close it.
