### ISSUE TITLE
Mod+Space pasting link or title in VomniBar

### ISSUE THREAD

**Issue by HappyCthulhu** [gdh1995/vimium-c#1163]
**Describe the bug**

I already reported about this bug. It was fixed, now it appear again:
https://github.com/gdh1995/vimium-c/issues/435

Problem is, shortcut `mod+Space` changes language on my system. So, i cant change language while im trying to find some link in Vomnibar.

**To Reproduce**

* Open VomiBar (for example, with `Shift`+`B`)
* Type smth, that will make few links appear in Vomnibar
* User shortcut `Mod`+`Space`

P.S. `Mod`-button == Windows-key

**Browser, OS and Vimium C versions**

- Browser name: Google Chrome
- Browser version: 125.0.6422.60 (Official Build) (64-bit)
- Vimium C version:  1.99.99
- OS name and version: Manjaro 24.0.1

**Comment by gdh1995** [comment]
What's the current test result if you follow https://github.com/gdh1995/vimium-c/issues/435#issuecomment-922367789 ?

**Comment by HappyCthulhu** [comment]
> What's the current test result if you follow [#435 (comment)](https://github.com/gdh1995/vimium-c/issues/435#issuecomment-922367789) ?

```
	Event	Code	Key	Modifiers	KeyCode (legacy)	Timestamp
1	keydown	MetaLeft	Meta		91	8.478
2	keydown	Space	GroupNext	Meta	32	8.557
3	keyup	Space	GroupNext	Meta	32	8.609
4	keyup	MetaLeft	Meta	Meta	91	8.743
```

**Comment by gdh1995** [comment]
Oh I see the root case. Thanks for this bug report.

I'll fix it and a new version of v2.x will arrive in days.

**Comment by HappyCthulhu** [comment]
Working like a charm. Closing issue
