### ISSUE TITLE
Question: open url-at-point in a foreground tab

### ISSUE THREAD

**Issue by agzam** [gdh1995/vimium-c#1165]
I am a knee-deep in a self-inflicted headache for a seemingly simple task.

So, I find myself very often having to find something on the page, and then open the url-at-point in a new, foreground tab - the native behavior in Brave (Chrome should be the same) is pressing `Ctrl+Shift+Return`.

I wanted to rebind that to a simpler key - after an injury it hurts for me to reach for certain keys. After almost an hour, I still couldn't figure it out.

I have found enormously interesting features I was not aware of, like[ runKey](https://github.com/gdh1995/vimium-c/wiki/Map-a-key-to-different-commands-on-different-websites) 

and openUrl with [vimium://parse](https://github.com/gdh1995/vimium-c/wiki/Vimium-inner-URLs#vimiumparse), but the documentation is so dense and I feel it lacks some good examples and better explanations, I just couldn't figure out how that even works. 

I assumed that in my case I could just use `openUrl` with some params, but I couldn't figure out how to pass the url-at-point as a parameter.

Please, give me a guidance. Thanks a lot!

**Comment by gdh1995** [comment]
Um if you have used `FindMode` to find and then focus a link (HTML `<a>` element), then you may use `LinkHints.click`:
```
map <f9> LinkHints.click direct="focused" mode="newtab-active"
```

**Comment by agzam** [comment]
Works perfectly. Thank you very much! Please consider revisiting documentation for the advanced features I mentioned. I think they are incredibly powerful and the extension provides immeasurable value by packing those in. I think more people should know about them. I tried to understand how the stuff works, but I couldn't really figure it out. A couple more practical examples would be great. I know that English is not your native language, and neither is it mine. I wanted to help improve the docs, but I failed to understand the features.

**Comment by gdh1995** [comment]
Thanks for your appreciation. The biggest problem prevent myself from writing document is I'm a bit lazy... The second biggest is I'm a individual developer and have no so much rest time to do so.

**Comment by agzam** [comment]
I Oh, no, I'm sorry. I didn't mean this to be a guilt-inducing message. I absolutely acknowledge that you do not owe me, or anyone else, a single thing. If anything, it's me who owes you a great deal of gratitude and appreciation for this amazing extension you've made and already poured countless hours of your life into.

It's a life-saving tool that, if suddenly I couldn't use it anymore, I would feel lost. From the bottom of my heart, a huge thank you for this incredible gift.

I should probably spend some more time exploring the aforementioned features and understand them better, and perhaps try to contribute a couple of paragraphs of improved documentation. I think those things are very cool, and my inability to understand them better makes me feel like I'm missing out.

**Comment by gdh1995** [comment]
Ah thanks again.

But Vimium C's source code is not well-commented, and what's worse is I've added too many tricks into it so it's not easy to understand for most other people...
