### ISSUE TITLE
`o` is always opening query words in a new tab like `O`

### ISSUE THREAD

**Issue by ni554n** [gdh1995/vimium-c#1168]
**Browser, OS and Vimium C versions**

- Browser name: Chrome
- Browser version: 126
- Vimium C version: 2.11
- OS name and version: Windows 11

**Comment by gdh1995** [comment]
Did you search for a query by press Enter directly? When no suggestion were selected?

If so, then it's a new feature of Vimium C v2.xxx, and you may turn off it by uncheck `Prefer the browser's default search engine` on Vimium C Options page.

**Comment by ni554n** [comment]
Thanks. Unchecking that option solved the issue.

**Comment by gdh1995** [comment]
I may add some code so that `Vomnibar.activate` can open in current even with this new option enabled.
But this will make the default search engine of `o` and `O` different - then `o` uses Vimium C's, while `O` uses a browser's .

What do you think about this difference?

**Comment by ni554n** [comment]
I welcome this change. Personally, I trained myself to use `CTRL+L` when I needed the browser default search engine because of the auto completion and that's the only feature I miss from Vimium.

So I suggest this option should be _disabled_ by default and the new behavior should be mentioned in the help section to reduce confusion.

![image](https://github.com/user-attachments/assets/6caa6266-d91d-448c-89ea-cbe27e0cfeb6)

By the way, there's also a similar bug in the `ge` command. It is really useful to highlight a word and then press `ge` to edit the word and search. But the result always opens in the new tab like `gE`. It doesn't happen with normal `ge` with URL.

**Comment by gdh1995** [comment]
Hello v2.11.1 has been released days ago. So now do `o` and `ge` work on your browser?

**Comment by ni554n** [comment]
Yes, I'm on that version. `o` is working as expected, but `ge` is not.

**Comment by gdh1995** [comment]
well, it's a feature. I'll add a switch to disable this feature of "auto seaching words in a new tab".
