### ISSUE TITLE
Strange code editor behavior

### ISSUE THREAD

**Issue by raingart** [gdh1995/vimium-c#117]
There are no errors. But the syntactic check is reported to be there.

The error appeared after uncommenting the line
`unmapAll`

![Screenshot from 2020-02-02 16-43-13](https://user-images.githubusercontent.com/13064767/73609969-54bc4380-45db-11ea-9567-c1ee7be45393.png)

**Comment by gdh1995** [comment]
Vimium C has default key mappings (when "custom key mappings" is empty), and if you remove "unmapAll", then in the below mapped keys there're a few which have been mapped.

The error message is in the console of background page

**Comment by raingart** [comment]
I didn’t think about looking at the console on the background page. And on the settings page in the console is empty. The only thing that indicated that this was a css style name error.

The main thing that works. And there is no blocking the ability to save the settings. Even with invalid syntax.
