### ISSUE TITLE
Vomnibar not using custom css style after latest update

### ISSUE THREAD

**Issue by Avn3s** [gdh1995/vimium-c#1171]
**Describe the bug**
After the latest update, the vomnibar isn't using the custom css I've set in the settings.

**Screenshots**
![image](https://github.com/user-attachments/assets/66ebb99d-2ac0-4e23-8932-a4b2b76a1393)
CSS^

![image](https://github.com/user-attachments/assets/907fa601-89cc-415b-b3e7-35a2121c7ffb)
Vomnibar^

**To Reproduce**

Update the extension to the latest version.

**Browser, OS and Vimium C versions**

- Browser name: Google Chrome
- Browser version: 109.0.5414.168 (Official Build) (64-bit)
- Vimium C version: 2.11
- OS name and version: Windows 8.1

**Comment by gdh1995** [comment]
Sorry it's indeed a bug of Vomnibar, and there's no way to work it around in v2.11 .

I'll fix it in days.

**Comment by Avn3s** [comment]
Yay thanks its working now!
![image](https://github.com/user-attachments/assets/921bca14-3634-4ffb-9e82-f938d5774c4b)

**Comment by kun-codes** [comment]
@Avn3s sorry for the ping, can you share me your css? It looks good

**Comment by Avn3s** [comment]
actually its a very slightly modified version of [rose pine for vimium c](https://github.com/rose-pine/vimium-c).
However if you would still like my config, here it is:
CSS:
[css.txt](https://github.com/user-attachments/files/16714103/css.txt)
Custom search stuff:
[custom_search_engines.txt](https://github.com/user-attachments/files/16714104/custom_search_engines.txt)

**Comment by kun-codes** [comment]
Thanks a lot. Thanks again for the quick reply
