### ISSUE TITLE
Unable to map <enter> in insert mode <xxx:i>

### ISSUE THREAD

**Issue by kauderk** [gdh1995/vimium-c#1173]
**Describe the bug**

`mapKey <a-k:i> <enter>` should map k to enter

By the way `mapkey <i:v> k` does work

**Browser, OS and Vimium C versions**

- Browser name: Chrome
- Browser version: 126.0.6478.127 (Official Build) (64-bit) (cohort: Stable) 
- Vimium C version: 2.11
- OS name and version: Windows10 - Windows_NT x64 10.0.19045

**Comment by gdh1995** [comment]
Please note `mapKey` directives can only take effect inside Vimium C.

So the `mapKey <a-k:i> <enter>` does work, but usually Vimium C does nothing on a `<enter>` keydown event when in insert mode.

Do you mean `mapKey <a-k:o> <enter>` (`o` means Vomnibar)?

If you do want a new line, then you may need `editText`:
```
map <a-k:i> editText run=["exec","insertText","\n"]
```

**Comment by kauderk** [comment]
Much appreciated. This solves it.
