### ISSUE TITLE
创建标记和使用 / 搜索会在某些网站上失去跳转功能

### ISSUE THREAD

**Issue by Xinli-GUMP** [gdh1995/vimium-c#1174]
**例如在https://leetcode.cn/problems/count-complete-tree-nodes/description/ 和 https://ai.ashuiai.com/chat/ 中，当我使用m创建一个网页标记时，无法通过 *`* 键进行跳转；使用 / 搜索文字时，也无法跳转。我记得之前某个版本是能够跳转的。**

**Browser, OS and Vimium C versions**

- Browser name: Chrome
- Browser version: 126.0.6478.182
- Vimium C version: 2.11
- OS name and version: Windows23H2

**Comment by gdh1995** [comment]
麻烦说详细点，``` ` ``` 键+字母不能从哪儿跳到哪儿，搜索文字后是否退出搜索框、按什么键不能跳转到哪儿呢？

**Comment by Xinli-GUMP** [comment]
> 麻烦说详细点，`` ` `` 键+字母不能从哪儿跳到哪儿，搜索文字后是否退出搜索框、按什么键不能跳转到哪儿呢？

使用`m+字母`创建标签后，按`+字母`跳转，此时右下角会弹出跳转到标记，但实际上并没有发生跳转；
使用`/` 搜索也是同样，按下`/+字符`后，会显示查询到的个数，然后回车，并不会发生跳转，按`n`键查询下一个也不会发生跳转(之前版本是没这个问题的)

**Comment by gdh1995** [comment]
`m` 和 ``` ` ```（Marks 系列）命令是用来跳转网址、顺带滚动整个网页的。但你给的例子里，这俩网页都是”顶满窗口高“，而不是在最右边有个浏览器自动显示的”整个页面级别”的竖直方向滚动条，那 Marks 系列命令就不知道要怎么滚动页面区域了。

所以，你说的“并没有发生跳转”是说没滚动吗？如果是的话，这是 Marks 功能的局限性，不支持“记忆并还原”任意局部区域的滚动；如果是不能跳转网址，麻烦说说是在哪个 url 的网页上怎么创建的网址、又在哪个 url 的网页上跳不回去。

`/` 不发生跳转的话，https://leetcode.cn/problems/count-complete-tree-nodes/description/ 上我搜“遍历”重现了问题，确定是有 
bug，但不确定修掉 bug 后能不能跳转。

搜索模式跳转失败的原因有很多，因为扩展程序毕竟不是浏览器自己，好些高级功能浏览器都没开放出来。不过如果以前是好的，那应该有办法吧。

**Comment by gdh1995** [comment]
哦，在你印象里， ``` ` ``` 命令以前能跳转吗？

**Comment by gdh1995** [comment]
哦，在你印象里，在这俩网站上，``` ` ``` 命令以前能跳转吗？

**Comment by Xinli-GUMP** [comment]
> 哦，在你印象里，在这俩网站上，`` ` `` 命令以前能跳转吗？

抱歉我的描述可能带来了歧义，我的意思正是“没有发生滚动”。在我印象中, 以前版本在这俩网站上`/ + 字符 + 回车` 是能够滚动到字符页面的，按`n` 也可以滚动到下一个出现此字符的页面，毕竟Chrome的`C-F`就能实现这个功能，但是目前版本无法滚动。至于
`` ` `` 似乎一直以来都是无法滚动的。

**Comment by gdh1995** [comment]
chrome 最近（两年内）对搜索接口做了升级，有时候会自动滚动，使得搜索到的结果被显示出来，我误以为始终能自动滚动了。

下一版 2.11.2 会回滚对应代码来修复这个问题，但手动滚动效果会比 chrome 自动滚动的效果略差，下一版内来不及改进了，以后再看有没有好办法吧。

见 commit 0c728b72 。

**Comment by gdh1995** [comment]
@Xinli-GUMP 你好，2.11.3 又对滚动逻辑做了更新，优先尝试浏览器内置的“搜索时自动滚动”，如果失败了再手动滚动。

请你尝试看看有没有新的问题。

另外，这个尝试会引入最多约 200ms 的滚动延迟，因此如果想关闭它，可以改自定义快捷键：
```
map / enterFindMode scroll="instant"
```

**Comment by Xinli-GUMP** [comment]
> @Xinli-GUMP 你好，2.11.3 又对滚动逻辑做了更新，优先尝试浏览器内置的“搜索时自动滚动”，如果失败了再手动滚动。
> 
> 请你尝试看看有没有新的问题。
> 
> 另外，这个尝试会引入最多约 200ms 的滚动延迟，因此如果想关闭它，可以改自定义快捷键：
> 
> ```
> map / enterFindMode scroll="instant"
> ```

好的，非常感谢。
另外，辛苦了！
