### ISSUE TITLE
谷歌翻译和取消翻译可以扩展为可用命令吗

### ISSUE THREAD

**Issue by awaken233** [gdh1995/vimium-c#1175]
**What command or commands**

翻译和取消翻译（调用chrome 的内置翻译）

<img width="462" alt="image" src="https://github.com/user-attachments/assets/727e81a4-153b-4187-9715-fba93376b71a">

vimium-c 可否内置快捷键绑定到切换翻译（按一下翻译，再按一次取消翻译）

**Comment by gdh1995** [comment]
这个是浏览器内置模块，Vimium C 没相应权限，所以调用不了它。
