### ISSUE TITLE
After the update, the VC is not defined   

### ISSUE THREAD

**Issue by Ares-Chang** [gdh1995/vimium-c#1178]
**Describe the bug**

After updating the version, the VC is not defined

There are prompts on every page, The relevant permissions required after the update have been provided

![image](https://github.com/user-attachments/assets/37f96013-b4fa-4210-85a4-95a528dff591)
![image](https://github.com/user-attachments/assets/ba0ada13-4f25-4d57-86ab-921e53bb8cad)

**Browser, OS and Vimium C versions**

- Browser name:  Chrome
- Browser version: 126.0.6478.183 (正式版本) （64 位） (cohort: Stable) 
- Vimium C version:  2.11.1
- OS name and version: 
	- 版本	Windows 11 专业版
	- 版本号	23H2
	- 操作系统版本	22631.3880

**Comment by gdh1995** [comment]
confirmed it's a bug, so it will be fixed in 2.11.2.

**Comment by Ares-Chang** [comment]
Thank you very much and look forward to the new release

**Comment by romseguy** [comment]
![Capture d’écran du 2024-07-27 13-03-07](https://github.com/user-attachments/assets/7782d063-7af8-447d-b27b-cd0f5a4e5cbe)
![Capture d’écran du 2024-07-27 13-02-39](https://github.com/user-attachments/assets/dfd6c939-5906-4b78-b29e-eb62bcf09752)

**Comment by Ares-Chang** [comment]
New version fixed, thanks🫡
