### ISSUE TITLE
webpage flashing with closeDownloadBar command

### ISSUE THREAD

**Issue by Monirzadeh** [gdh1995/vimium-c#118]
hi
when i try to close download bar web page flash for a second
is it possible to stop that. it is annoying

**Comment by gdh1995** [comment]
As far as I've found, It has been the most safe way to do this.


Um, there are some other extensions which can do so without flashing. But all of them require a a permission to control your download history, And some of them will even remove all the download history on a new file beginning to download



---Original---

**Comment by Monirzadeh** [comment]
so i think has flash is better than unnecessary permission.
if you find a better way without flashing please reopen this issue
thank good job
