### ISSUE TITLE
Is there any way to remove the tab left of the current tab?

### ISSUE THREAD

**Issue by ni554n** [gdh1995/vimium-c#1180]
To reduce context switching in my brain, I prefer to operate from my current tab. Currently, to close a bunch of tabs from the left, I have to repeat `J` and `x` multiple times.

I wish Vimium-C has a `removeLeftTab` command like `removeRightTab`, so that I can remap it to `X`, and close old tabs from current tab by just pressing `XXXXX`.

**Comment by ni554n** [comment]
Those commands are removing the current tab. I would like the exact behavior of `removeRightTab`, but left.

**Comment by gdh1995** [comment]
`map X removeRightTab` and then `-3X` will remove 3 left tabs.

**Comment by gdh1995** [comment]
Or, `map X removeRightTab count=-1` and then `3X` remove 3 left tabs.

**Comment by ni554n** [comment]
> Or, `map X removeRightTab count=-1` and then `3X` remove 3 left tabs.

Oh, yes!!! This is perfect. Thank you so much.
