### ISSUE TITLE
切换滚动目标

### ISSUE THREAD

**Issue by dzp-immortal** [gdh1995/vimium-c#1184]
## 需求
Surfingkeys 有个命令 `cs` 可以切换滚动目标，在浏览 `mdbook` 和带目录的博客时特别好用，在 `Vimium C` 试了 `gf`，达不到相似的效果。

## 系统信息：
名称 	Firefox(librewolf)
版本 	128.0-2
版本 ID 	20240712182945
发行 ID 	io.gitlab.librewolf-community
用户代理 	Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0
操作系统 	Linux 6.10.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 04 Aug 2024 05:11:32 +0000
操作系统主题 	Adwaita / Adwaita
应用程序二进制文件 	/usr/lib/librewolf/librewolf

## Vimium C
版本	1.99.997
上次更新	2024年7月28日

**Comment by gdh1995** [comment]
用 `LinkHints.activateHover` 来选中目标，即可滚动它或者它的的外层对象

**Comment by dzp-immortal** [comment]
感谢你的回答，配置了一下快捷键，已经可以用了
map ;s LinkHints.activateHover
虽然多了一个选择目标的过程，但也算可以接受。
