### ISSUE TITLE
Regex support in find mode

### ISSUE THREAD

**Issue by phuclv90** [gdh1995/vimium-c#1194]
**What command or commands**

A command to search using regex instead of literal strings, because sometimes I need to find a specific pattern or search for multiple strings

**How should a feature do**

When a user has done such steps:

1. Press `/` or a new command

then Vimium C should do:

Search using regex

**Comment by directentis1** [comment]
Just need to put `\r` in the end  of your pattern.
I though it was already mentioned in docs? 🤔

**Comment by directentis1** [comment]
https://github.com/philc/vimium/wiki/Find-Mode#case-sensitivity-and-regexps

**Comment by phuclv90** [comment]
ooop sorry I searched in the github search box and didn't find that. Previously I missed the `Treat find queries as JavaScript regular expressions` because I looked for "regex" instead 🤦
