### ISSUE TITLE
LinkHints behavior on Firefox is affected by whether the 'switch to new tab' option is checked

### ISSUE THREAD

**Issue by parogen** [gdh1995/vimium-c#1195]
Is it possible to set the starting mode of `LinkHints.activateWithQueue` to the one associated with `Ctrl`? I noticed searching through the issues, there is `mode=cur-queue` (same as `Shift`) and `mode=open-direct` (seemingly for `Alt`, but the tooltip is not the same and can't switch to `Ctrl` or `Shift` modes of the original `LinkHints.activateWithQueue`), but I can't seem to find the one for `Ctrl`.

**Comment by parogen** [comment]
Actually I didn't realize I had the option checked to switch to links when opening them in Firefox itself. That made it so that the Vimium behavior was swapped. For example, `LinkHints.activateOpenInNewForegroundTab` with the Firefox option checked acted like `LinkHints.activateOpenInNewTab`, without switching, and vice versa. Maybe that should be looked into.

**Comment by gdh1995** [comment]
Um, sorry but it's a feature that LinkHints may be "affected" by "what your browser thinks CtrlKey should do".

**Comment by parogen** [comment]
I have since turned off the Firefox option. I guess it was just a semantics thing because it doesn't match the Vimium function name.
