### ISSUE TITLE
How to toggle a window's fullscreen state

### ISSUE THREAD

**Issue by parogen** [gdh1995/vimium-c#1198]
I'm trying to `mapKey` to `<f11>` but when I do so, I don't get the fullscreen function effect. But I noticed that when I make a new window through vimium from a fullscreened window, the new window also fullscreens, which seems to me vimium should be capable of doing so through a `map` or `mapKey`. Is there a workaround or alternative?

**Comment by gdh1995** [comment]
`mapKey` directives can only take effect inside Vimium C, which means such a `mapKey <xxx> <f11>` can not make your browser do what a real `F11` will make it do.

As for toggle fullscreen state, you may try a similar way:
```
map xxx toggleWindow states="fullscreen,maximized"
# or 
# map xxx toggleWindow states="fullscreen,normal"
# or even
# map xxx toggleWindow states="fullscreen,normal,maximized"
```

The only disadvantage of the `toggleWindow` command is:
- it can not read from your browser what state the window is in before it becomes fullscreen
- so you have to tell Vimium "one or more next states" after the `fullscreen` word.

**Comment by parogen** [comment]
This works well enough for me, thanks!
