### ISSUE TITLE
question: how to map a key to another extension

### ISSUE THREAD

**Issue by agzam** [gdh1995/vimium-c#120]
Let's say if I have configured Pocket extension's shortcut in `chrome://extensions/shortcuts` to be `Option+Shift+p`, but i want to bind that action in Vimium-c to be just `gp`, i.e. when I press `gp` it would activate Pocket extension and save current page to Pocket. 
How can I make something like that to work?

Similarly: is it possible to map to browser native keys, e.g., 
if I want to bind `gd` to do `Cmd+Option+L` - which on Mac takes you to Downloads page, is that possible?

**Comment by gdh1995** [comment]
1. currently impossible, because Vimium C don't know what to send messages to other extensions.
2. It's somehow possible, only for such a case of "open a page": `map gd openUrl chrome://download`
- 1. only on Chrome, but not on Firefox because of its limits.

**Comment by agzam** [comment]
1. So even not possible by "emulating" pressed keys? i.e. you can't force Vimium-c, to emulate "Option+Shift+p" when other, more mnemonically recognizable shortcut is pressed, like `gp`?

2. Cool, I added something like this:

    map gds openUrl url="chrome://downloads"
    map ghs openUrl url="chrome://history"
    map ge openUrl url="chrome://extensions"
    map gE openUrl url="chrome://extensions/shortcuts"

and all that worked nicely.

**Comment by gdh1995** [comment]
1. Indeed not possible. Extensions can not "simulate" keyboard events, because browsers don't provide such APIs.

**Comment by agzam** [comment]
I see. Thank you for your help. I'm gonna close this now.

**Comment by agzam** [comment]
But wait, what is then "Shortcut forwarding tool" extension for? Now, I'm confused.

**Comment by gdh1995** [comment]
Vimium C provides 6 places to let you assign shortcuts to itself, and the forwarding tool lets you assign 32 extra shortcuts to Vimium C.
