### ISSUE TITLE
How to unmap the default `map ? showHelp`

### ISSUE THREAD

**Issue by screw-hand** [gdh1995/vimium-c#1210]
**Describe the bug**

I am unable to `unmap` the default `map ? showHelp` in Vimium C. This creates a conflict with modern websites that use `?` to display their own shortcut keys (such as GitHub), leading to potential interference. When Vimium C captures `?`, I miss the chance to utilize some websites' native shortcut functionalities.

Although I can use `i enterInsertMode` to temporarily bypass Vimium C and access the website's shortcuts, this adds an extra operation step since I also have to switch back by pressing `esc`.

**To Reproduce**

1. Attempt to update `Custom key mappings` based on the source from [Vimium C settings template](https://github.com/gdh1995/vimium-c/blob/master/settings-template.json#L21) and documentation.
2. Add the following key mappings:
   ```
   unmap ? showHelp
   unmap <s+/> showHelp
   ```

The following errors are encountered:

```
2 Errors:
unmap: only needs one mapped key: unmap ? showHelp.
unmap: only needs one mapped key: unmap <s+/> showHelp.
```

**Browser, OS and Vimium C versions**: 
- Vimium C: 2.11.3
- Browser: Microsoft Edge 128
- OS: Windows 11

Thank you to the author for the ongoing maintenance and contributions.

**Comment by gdh1995** [comment]
Um, `unmap` only accepts 1 parameter and it should be a mapped key sequence.

So you may try `unmap ?`.

BTW, Vimium C Options page has its special mapping and `?` will be still showHelp if only it's not mapped to another command.
So please test it on a common web page like Bing search result.

**Comment by screw-hand** [comment]
Thank you for your patient answers, and for the reminder about Vimium C Options.👍

**Comment by screw-hand** [comment]
Thank you for your patient answers, and for the reminder about Vimium C Options.👍
