### ISSUE TITLE
How to copy current tab's link and title in markdown format?

### ISSUE THREAD

**Issue by die4live** [gdh1995/vimium-c#1211]
**What command or commands**

att

**How should a feature do**

I wonder to know if there is such a short, like a combination of existing commands:

Copy page's info (use type=url/title/frame, decoded)(copyCurrentUrl)
Copy current tab's title (copyCurrentTitle)

to copy `[CurrentTitle](CurrentUrl)`

I tried to ask in a similar [issue](https://github.com/gdh1995/vimium-c/issues/1091#issuecomment-2316531473), but no response maybe because it is closed.

**Comment by doneself** [comment]
you may try: 
`map gy copyCurrentUrl format="[${title}](${url})"`

**Comment by die4live** [comment]
Great, it works and thanks a lot.

**Comment by gdh1995** [comment]
Um, sorry Vimium C has few documents. The `format` may be found in its source code.
https://github.com/gdh1995/vimium-c/blob/fd4b10aacd417ac8f4ed0950b5744ad759ce872a/background/typed_commands.d.ts#L86-L91

**Comment by snsnsjsn** [comment]
Hi ， how can I do the action like copying the title in the Vomnibar ，
for example , I type  o, and key word abc to filter the listing result ,and up or down arrow to select target tab , then ctrl+t to copy the title of selected target tab . so I will get title of specfic very quickly
