### ISSUE TITLE
LinkHints.activate always shows 2 matches using ID

### ISSUE THREAD

**Issue by kevb1973** [gdh1995/vimium-c#1219]
**Describe the bug**

I'm adding hotkeys to a page I use with the following settings:
```
env sudoku host=":https://www.sudokuslam.com/"
run h <v-h> expect="sudoku:<v-sudh>"
map <v-h> Vomnibar.activateHistory
map <v-sudh> LinkHints.activate match="#get-hint-go"

```
Only one link hint is shown (as expected since it matches unique ID), but it has the number "2" indicating there is another unseen hint. This stops auto selection of single hint and requires pressing enter to activate it.

**To Reproduce**

1. Add URL specific bind to configuration.
2. Go to https://www.sudokuslam.com
3. Start a new puzzle
4. Press 'h' to activate the hint link.

Expected: Pressing 'h' will activate the hint automatically.
I have confirmed that the "Require Enter when filtering hints" option is disabled.

![image](https://github.com/user-attachments/assets/6e09b42b-67b9-4204-8b4a-b061514f6d86)

**Browser, OS and Vimium C versions**

- Browser name: Firefox 
- Browser version: 130.0
- Vimium C version: 1.99.997
- OS name and version: NixOS (unstable)

**Comment by gdh1995** [comment]
I have no idea. Not reproduced on Firefox 130.0 + Vimium C v1.99.997 + Win 11.

Maybe some other extension on your Firefox added some "clickable" elements?

And you may try `LinkHints.click` which also supports `match=...` and will click it at once.
