### ISSUE TITLE
Mapping the < or > keys results in a warning.

### ISSUE THREAD

**Issue by nikhilweee** [gdh1995/vimium-c#123]
I used the following custom keymapping for the `<` and '>` keys and even though the keys work fine, the UI results in a warning.

Here's the mapping I used.
```
map , scrollPageUp
map . scrollPageDown
map < scrollToTop
map > scrollToBottom
```

Here's the output of the log in the background page.
```
inactive key: {<: 0}<: 0 with <
commands.js:1 inactive key: {>: 0}>: 0 with >
commands.js:1 Key Mappings: 2 errors found.
```

Since the `<` and `>` keys work fine after the mapping, I don't think there should be a warning.

![image](https://user-images.githubusercontent.com/8774119/73934962-8435bd80-4905-11ea-9b55-b3e4e14aa8df.png)

**Comment by gdh1995** [comment]
Um, there's a default key mapping list in Vimium C, and it includes `map << moveTabLeft`, so your `<` and it were conflicted. Just add `unmap <<` before it.

Maybe I can add some more checks to auto skip such conflicts caused by default key mappings. Thanks for this report.

**Comment by nikhilweee** [comment]
Oh right, that makes sense. Thanks for your help!
