### ISSUE TITLE
个人建议

### ISSUE THREAD

**Issue by yyy33** [gdh1995/vimium-c#124]
![20200205-SneezeSpring_ZH-CN1577114008_1920x1080](https://user-images.githubusercontent.com/51548147/74037667-b1639800-49f9-11ea-976c-fc30c3487d74.jpg)
![2020-02-07-22-30-53](https://user-images.githubusercontent.com/51548147/74037677-b9bbd300-49f9-11ea-8ffd-779edbc0e98a.png)

作者你好这两个地方有办法改进吗？
第一张图片框中的部分需要鼠标悬浮在上面才会显示
第二张图片框中的部分需要鼠标中键悬浮在上面滚动才能滚动

**Comment by gdh1995** [comment]
1. 使用`模拟鼠标移动到网页内容上（LinkHints.activateModeToHover）`这个命令，然后输入字符选择上传按钮，能触发显示子菜单
2. 默认的 <kbd>F</kbd> 对应“LinkHints.activate”，会把可以滚动的区域、子页面区域这两类，用红色字体的标识标记出来，如下图。所以按“24”之后，再触发`scrollDown`之类的命令就能滚动它了。

![image](https://user-images.githubusercontent.com/5547703/74078042-83fe0500-4a60-11ea-9895-795025667eff.png)

**Comment by yyy33** [comment]
谢谢,软件很棒
