### ISSUE TITLE
Allow displaying tabs only from current window

### ISSUE THREAD

**Issue by ww7** [gdh1995/vimium-c#125]
Firefox have Containers for tabs, it's like separate spaces for certain tabs, it's like separate browser windows (sessions) inside one window.

Chrome now implementing this feature.

`activateTabSelection currentWindow` with this feature after some switching between Containers start to show all tabs, but not current window (container). I use Simple Tab Group were found this issue.

**Comment by gdh1995** [comment]
Do you mean it fail on a latest Chrome? Or on both Chrome and Firefox with "Firefox Multi-Account Containers"?

**Comment by gdh1995** [comment]
Well, in my tests today, the `chrome.tabs.query({currentWindow:true}, ...)` API will return alls tabs of both test groups in a same window. So I wonder what's your situation when you thought Vomnibar was showing tabs in a "current" group.

**Comment by ww7** [comment]
I mean Firefox. Now it works.
