### ISSUE TITLE
gi无法激活文本输入框

### ISSUE THREAD

**Issue by git708** [gdh1995/vimium-c#1254]
www.icourse163.org 顶部的输入框无法用gi激活

**Comment by git708** [comment]
chrome 130.0.6723.70
vimium-c 2.11.3

**Comment by awaken233** [comment]
我的可以激活

chrome 130.0.6723.117
vimium-c 2.11.3

**Comment by git708** [comment]
> 我的可以激活
> 
> chrome 130.0.6723.117 vimium-c 2.11.3

**Comment by git708** [comment]
> 我的可以激活
> 
> chrome 130.0.6723.117 vimium-c 2.11.3

我的chrome也升到这个版本了，还是不行。
