### ISSUE TITLE
个人建议

### ISSUE THREAD

**Issue by yyy33** [gdh1995/vimium-c#126]
![2020-02-09-18-50-44](https://user-images.githubusercontent.com/51548147/74100780-69658200-4b6d-11ea-97bf-e60b2218a39b.png)
作者作者你好这种应该不属于链接，但是确实需要点击

**Comment by gdh1995** [comment]
图里“DL”对应了包括绿色按钮、问题的开头文字在内的那个区域，试了一下可以展开问题内容。
