### ISSUE TITLE
Is there way to skip URL encoding in custom search engine?

### ISSUE THREAD

**Issue by ni554n** [gdh1995/vimium-c#1268]
I have a custom search engine for the Wayback Machine using: `wa: https://web.archive.org/web/*/$s Web Archive`.

However, when I send a query such as `wa https://example.com/test`, it opens the page with the URL encoded like this: `https://web.archive.org/web/*/https%3A%2F%2Fexample.com%2Ftest`.

This format is not supported by the Wayback Machine. How can I ensure it opens the URL like this instead?
`https://web.archive.org/web/*/https://example.com/test`

**Comment by eastarpen** [comment]
replace '$s' with '$S'

```
wa: https://web.archive.org/web/*/$s Web Archive.
```
