### ISSUE TITLE
Can't go into visual mode

### ISSUE THREAD

**Issue by benhormann** [gdh1995/vimium-c#128]
Vimium C 1.80.2, Firefox and Chrome

On a particular site I get mesage "Create a selection before entering visual mode."
Maybe it is something simple, but I didn't find any commands for making a selection.

Repro:
open https://unpkg.com/browse/jquery@3.4.1/dist/
hit v

**Comment by gdh1995** [comment]
Currently this situation requires a real mouse click from you, near the text you want to select.
Some similar extensions like VimFx have a feature of selecting text through LinkHints, but I haven't implemented it in Vimium C.



---Original---

**Comment by benhormann** [comment]
Hmm, it would be nicer to drop into caret mode at (or somewhere near) the top of the page.
P.S. I figured out how to create a selction with find (/). Note that in regular vimium it says it put me in caret mode, but the cursor is not visible.

**Comment by gdh1995** [comment]
Vimium / Vimium C will try finding a long paragraph to put caret there, but its logic is very simple and often fails, so you'll have to use FindMode / a real mouse to select some text first.

I just tested philc/Vimium on the URL you gave, and I think it auto selects an "invisible" area and put caret there, so you can not see it, neither move/extend selection.
