### ISSUE TITLE
Capslock as escape key

### ISSUE THREAD

**Issue by SylEleuth** [gdh1995/vimium-c#129]
I've mapped escape key to capslock on my system. When I open vomnibar and want to leave it, capslock (as esc key) is not working. I heave to reach actual esc key. Is it possible to do something with that?

**Comment by gdh1995** [comment]
mapkey can msp any other keys to escape in Vimium C.


But how do you map a real capslock key to escape? I've done so using AutoHotKey, and my CapsLock can exit Vomnibar as expected.



---Original---

**Comment by gdh1995** [comment]
Sorry, the comment before made a mistake: actually <kbd>CapsLock</kbd> is always skipped by Vimium C (no keys can mean it).

<hr/>

This may be related to how you map CapsLock. I guess you do such mapping in another browser extension ?

**Comment by aaronclimbs** [comment]
I've used [uncap](https://github.com/susam/uncap) to remap ESC to CapsLock and I see the same issue. Pressing <CapsLock> works to exit to normal mode from viewing all links mode, but not to exit the vomnibar. Is there a difference in how the key listener works in these two instances?

**Comment by gdh1995** [comment]
@aaronclimbs What will Vomnibar of Vimium C do, if you enable the advanced option `Ignore keyboard layout` ? Up to now Vomnibar works just like this is forced to be enabled.

And could you do a test and press <kbd>CapsLock</kbd> on http://gdh1995.cn/vimium-c/keyboard-test.html , when your `uncap` is running ? The page will report the detailed key event information and it can be helpful a lot.

**Comment by gdh1995** [comment]
Hello, I've reproduced this issue using `uncap`, so please try this version:
[vimium_c-1.80.3-chrome-0ecf497.zip](https://github.com/gdh1995/vimium-c/files/4318537/vimium_c-1.80.3-chrome-0ecf497.zip); [vimium_c-1.80.3-firefox-0ecf497.zip](https://github.com/gdh1995/vimium-c/files/4318536/vimium_c-1.80.3-firefox-0ecf497.zip).

* unzip the files into an empty folder
* if on Chrome, open chrome://extensions/ and enable the "developer mode"
* if on Firefox, open about:debugging#/runtime/this-firefox manually
* click the "load extension" button and select the manifest.json

**Comment by aaronclimbs** [comment]
Works great. Thanks for the quick fix.
