### ISSUE TITLE
hide cursor when scrolling with keyboard

### ISSUE THREAD

**Issue by parisni** [gdh1995/vimium-c#133]
Hi,

Several vim plugin provide option to hide the cursor when scrolling
 with the keyboard. That´s useful because usually the cursor makes
hoover popup trigger

Thanks !

**Comment by gdh1995** [comment]
Oh I once thought Chrome has did this on scrolling, but on Chrome 80 it does not. Thanks for your report.

**Comment by gdh1995** [comment]
Hello, Vimium C v1.81 has been released in all 3 platforms, and you may have a try.

**Comment by gdh1995** [comment]
Note: The way Vimium C uses to prevent hover effects has some negative impact on performance, as said in #175 , so in a next release, This feature will be disabled by default, and you'll need to add an option of `keepHover=false` to `scroll*` commands to enable it manually.
