### ISSUE TITLE
有一个影响小的bug  ？ （已解决不是bug）

### ISSUE THREAD

**Issue by 154798760** [gdh1995/vimium-c#134]
这扩展很好。
就是有个对我来说的bug

前提有2个同时运行时，才触发bug
1：在vim c 设置
```
map cc createTab url="https://manhua.dmzj.com/update_1.shtml"
map cb createTab url="https://www.bilibili.com/"
```

2：用autohotkey软件，设置
```
;;音量控制 按下capslock + 鼠标滚动 上、下、点击
CapsLock & WheelUp::Send {Volume_Up 1}  
CapsLock & WheelDown::Send {Volume_Down 3} 
````

当这2个设置完成后，在浏览器按下capslock + 鼠标滚动下时，就会触发vim c 设置里的
map cc createTab url="https://manhua.dmzj.com/update_1.shtml。
只有有浏览器才会这样，在文件夹按下autohotkey的快捷键会有问题。大概是vim c bug？

有点烦恼，不知什么问题，但这设快捷键又用了多年。
谢谢

**Comment by gdh1995** [comment]
只触发 `cc` 吗？在Win10 64位、AHK u64 1.1.32.0、Chrome 80 x64上无法复现。

请禁用 Vimium C 后在 http://gdh1995.cn/vimium-c/keyboard-test.html 上测试：1）正常按 C ；2）按住CapsLock 并 滚动鼠标滚轮；来看看程序具体收到了什么信号。

**Comment by 154798760** [comment]
解决了，谢谢。应该是我的ahk太旧了。
