### ISSUE TITLE
add ctrl + enter to .com

### ISSUE THREAD

**Issue by Monirzadeh** [gdh1995/vimium-c#135]
please add `ctrl` + `enter` to add .com at in Vomnibar like browser address bar

**Comment by gdh1995** [comment]
If `www.` + “the query word” + `.com` is a domain, then Vomnibar can auto select it now. Is it not enough?

Ctrl+Enter has been used to force Vimium C to open selected item in a new tab.

**Comment by Monirzadeh** [comment]
no i thinks it is better to be like default browser Address bar behavior
it is my personal though about this function
1. i usually handle open in this tab or new tab in with `o` and `t` (i decide about that before open Vomnibar)
2.  i think `ctrl` + `enter` for open in new tab is not so frequent (you can replace that with `ctrl` + `shift` + `enter`)
3. you should type at the least 4 unnecessary character (`.com`)  to open a new a website. 
4. i think open a new website with type address and press `ctrl` + `enter` is so familiar than current behavior

**Comment by gdh1995** [comment]
Do you often visit a new website, which you have never visited before?

The last comment of mine means, currently, if the wanted website has been visited on your current browser, then Vimium C will know that "your query is a hostname of the website", and then show the whole hostname as the first suggestion item, so <kbd>Enter</kbd> will be enough.

**Comment by Monirzadeh** [comment]
can you add this as check mark option?

**Comment by gdh1995** [comment]
Hello, here's a test version in which Vomnibar uses <kbd>Alt+Enter</kbd> to auto complete `www.` and `.com`:
[vimium_c-1.80.3-chrome-0ecf497.zip](https://github.com/gdh1995/vimium-c/files/4318537/vimium_c-1.80.3-chrome-0ecf497.zip); [vimium_c-1.80.3-firefox-0ecf497.zip](https://github.com/gdh1995/vimium-c/files/4318536/vimium_c-1.80.3-firefox-0ecf497.zip).

**Install**:
* unzip the files into an empty folder
* if on Chrome, open `chrome://extensions/` and enable the "developer mode"
* if on Firefox, open `about:debugging#/runtime/this-firefox` manually
* click the "load extension" button and select the extension folder or `manifest.json`

**Extended usages**: if you want to use <kbd>Ctrl+Enter</kbd> to do auto completing, you may add these to "Custom key mappings" on Vimium C Options page:
```
mapkey <c-enter:o> <a-enter>
mapkey <c-s-enter:o> <c-enter>
```

And then `Ctrl-Enter` will do auto completing, and `Ctrl+Shift+Enter` will force to open URLs in a new tab.

**Comment by Monirzadeh** [comment]
thanks it is work fine
