### ISSUE TITLE
Wikipedia pop-ups

### ISSUE THREAD

**Issue by Bumbadawg** [gdh1995/vimium-c#136]
Hi there sir, i love your fork so far
_even the bottom part of your README had me fam. I dig thy local trouble :D_
Anyway: whenever 'F'in on a Wikipedia page, in Firefox, opening a link in the background (about:config special recipe), the links opens, but on the still current page, the mouse-hovering pop-up keeps displaying.
![vendetta](https://user-images.githubusercontent.com/1251056/76441331-24747b80-63b7-11ea-8b42-89daf0df1437.png)

Thus, only 2 way of removing it: 
- moving the mouse away from the pop-up (urrkk)
- switching tab through Vimium (2 keys pressed, so long to achieve)

Is there any mean to hack around wikipedia mouse-hover stealing ?
Thanks gdh

**Comment by gdh1995** [comment]
There has been a special command for this usage: `LinkHints.unhoverLast`. So if there're:
```
# there's "map F LinkHints.activateModeToOpenInNewTab" by default
map q LinkHints.unhoverLast
```

And then you can press `q` to let Vimium C notify the page "a mouse is moving away from" the last clicked item, after `F` works.

**Comment by Bumbadawg** [comment]
It works great, thanks for having this option.
Do you consider adding an option to automatically have it unhovering on websites (like this one) ? Quality of life but not mandatory at this point =)

**Comment by gdh1995** [comment]
Hello, here's a test version and when a new tab is opened by LinkHints, it will accept a next <kbd>Escape</kbd> to "unhover" (blur) the link before, and if you add an option of `autoHover` to `LinkHints.activate*` (e.g.: `map f LinkHints.activate autoHover`), then it will blur the link at once, without waiting for an Escape . 
[vimium_c-1.81.3-firefox-f197269.zip](https://github.com/gdh1995/vimium-c/files/4362890/vimium_c-1.81.3-firefox-f197269.zip)


* unzip the files into an empty folder
* if on Chrome, open `chrome://extensions/` and enable the "developer mode"
* if on Firefox, open `about:debugging#/runtime/this-firefox` manually
* click the "load extension" button and select the extension folder or `manifest.json`

**Comment by Bumbadawg** [comment]
Thanks for the addition !

With `LinkHints.activateModeToOpenInNewTab autoHover`:
- on **Wikipedia**: doesn't unhover on escape for the first, then unhover on the next links.
- on **Github**: unhover on escape press, then automatically unhover the following links.

**Comment by gdh1995** [comment]
Sorry for my typo - The option name is "autoUnhover"



---Original---

**Comment by Bumbadawg** [comment]
No problem.
It doesn't seem to work for the first LinkHint hit and still requires to press "escape"

**Comment by gdh1995** [comment]
Um, try this version: [vimium_c-1.81.3-firefox-02ddf41.zip](https://github.com/gdh1995/vimium-c/files/4394076/vimium_c-1.81.3-firefox-02ddf41.zip) ? Here's my test:
* on my Firefox 74 x64 on Win 10
* write `map f LinkHints.activateModeWithQueue autoUnhover` and save options
* open https://fr.wikipedia.org/wiki/Bisque
* press <kbd>F</kbd> and select "cuisine française" by `SA`:
![image](https://user-images.githubusercontent.com/5547703/77766721-feb7c980-707a-11ea-9cb3-6b6071347c94.png)
* then a new tab is opened, and the link is indeed "unhovered" at once, so no card will be shown

**Comment by Bumbadawg** [comment]
This one works ! Cheers man
