### ISSUE TITLE
u 快捷键的建议

### ISSUE THREAD

**Issue by mightyang** [gdh1995/vimium-c#137]
个人感觉默认把 u 的快捷键改成 s 比较方便，一呢，s 就在 d  旁边，浏览网页俩手指头就够了，二呢，目前 s 也没分配什么命令。不一定完全遵照 vim 的规则，浏览器既然采用快捷键来浏览，能用一个手指头绝对不用第二个。

**Comment by gdh1995** [comment]
在扩展程序的设置页面（Chrome下是chrome-extension://hfjbmagddngcpeloejdejnfgbamkjaeg/pages/options.html）可以调整，方式是在“自定义快捷键”里填：
```
map w scrollPageUp
map s scrollPageDown
```

如果需要取消映射，用`unmap`。
