### ISSUE TITLE
Lost all movement keys?

### ISSUE THREAD

**Issue by GLodi** [gdh1995/vimium-c#138]
First of all let my thank you for the work you are doing with vimium-c. I really love it.
Second, after the last update (1.81.1) I seem to have lost all the movement keys (J,K,D,U). I can't figure out why. I'm using Firefox 74 under ArchLinux.

Thanks for your help.

**Comment by root-ali** [comment]
First Thank you for your good word 

and i has same problem too

**Comment by gdh1995** [comment]
oops, maybe some logic breaks in release mode. Thanks for report and I'll fix it in 12 hours.



---Original---

**Comment by gdh1995** [comment]
Oh it's a null pointer crash only in the released package for Firefox. V1.18.2 has been released to fix it.
