### ISSUE TITLE
PDF viewer doesn't go to next page in presentation mode

### ISSUE THREAD

**Issue by agzam** [gdh1995/vimium-c#139]
Sorry, I couldn't find a repo for Vimium-C PDF Viewer, reporting the issue here.

It seems PDF Viewer (in fullscreen mode) doesn't scroll continuously to the next page if you keep pressing `<j>`.

**Comment by gdh1995** [comment]
Do other commands like <kbd>F</kbd> and <kbd>O</kbd> of Vimium C work well on PDF Viewer's tab on your browser? Do <kbd>J</kbd> and <kbd>K</kbd> work when not in fullscreen mode?

**Comment by agzam** [comment]
I have misspoken - it seems it's called "presentation mode" in the extension.

**Comment by gdh1995** [comment]
Please test this: [pdf-viewer-mod-by-gdh1995.zip](https://github.com/gdh1995/vimium-c/files/4387681/pdf-viewer-mod-by-gdh1995.zip), [vimium_c-1.81.3-chrome-91c4e3a.zip](https://github.com/gdh1995/vimium-c/files/4387737/vimium_c-1.81.3-chrome-91c4e3a.zip)

**Install**:
* unzip a zip file into an empty folder
* if on Chrome, open `chrome://extensions/` and enable the "developer mode"
* if on Firefox, open `about:debugging#/runtime/this-firefox` manually
* click the "load extension" button and select the extension folder or `manifest.json`

**Comment by agzam** [comment]
Loaded both extensions. This is what it looks like in presentation mode:

![vimium-c-pdf](https://user-images.githubusercontent.com/1091022/77677465-f9f4f780-6f4c-11ea-814e-88bbb5a0e2d2.gif)

I turned it on and kept pressing <J>.
_Don't mind that it's showing only half of the screen (I was just capturing half of it)_

But you can see the huge blank gap between the pages?

**Comment by agzam** [comment]
Anyway, I think if there was an option to hide the top toolbar (this thing):

![image](https://user-images.githubusercontent.com/1091022/77678066-ded6b780-6f4d-11ea-91df-2ed3ddc9215a.png)

I would simply use Browser's fullscreen mode instead. Presentation mode is kinda lame, doesn't allow you zoom-in, etc.

**Comment by gdh1995** [comment]
Oh the PDF Viewer's zip file won't auto replace the version from Chrome Web Store (while the Vimium C's zip file does replace), so in the snapshot you were still seeing the old version of PDF Viewer.

Please turn off the old version whose ID is `nacjakoppgmdcpemlfnfegmlhipddanj`, ensure the one from the zip file is enabled, and then try it.

**Comment by agzam** [comment]
Deleted both extensions, loaded unpacked and tested it. Pressing `<j>` in presentation mode fixes it - now it jumps page to page, but it breaks scrolling in the default mode - instead of scrolling, now it goes page to page.

To reiterate my opinion - I think presentation mode as it is right now, is pretty useless. That unless you build features like zooming-in/out or two-page view.

Maybe it would be better to make it possible to hide the toolbar and then Browser's own full-screen mode can be used for distraction-free reading (instead of presentation-mode). I would even suggest perhaps it's better to disable presentation mode altogether (if that's possible at all).

But that's only my opinion, of course as the author please feel free to do what you think is the best. I am in no position to dictate what you should be doing, please don't get me wrong. I am extremely grateful for the extensions you've built, I use them every single day, they make my life little bit better. Thank you!

**Comment by gdh1995** [comment]
Sorry today I could not reproduce the buggy behavior of breaking scrolling smoothly in the default mode. Maybe more tests are needed.

The main part of PDF Viewer for Vimium C is completely from https://github.com/mozilla/pdf.js , which is also the source project of Rob--W's "PDF Viewer" extension (https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm). And I haven't added any other features into it except support for Vimium C.

**Comment by gdh1995** [comment]
Vimium C and PDF Viewer for Vimium C have released new versions, so does this issue still exist on Vimium C v1.81.4?

**Comment by agzam** [comment]
This is fixed. Thank you.

 I have discovered another (more critical bug), but I don't have a good way to reproduce it. Basically sometimes, (I think) when a link doesn't directly tied to a pdf document and instead calls a javascript function that leads to the document, PDF viewer extension fails to recognize it and simply won't show anything. The only workaround is to [ temporarily ] disable the extension and click on the link again. 

Once I find a good, reproducible case, I'll file a bug for this.

**Comment by gdh1995** [comment]
Hello, this scrolling issue of `j` / `k` in presentation mode will occur again in v1.83.0 and v1.83.1 because some APIs are removed, and will be fixed in v1.83.2 and a new version of PDF Viewer for Vimium C.
