### ISSUE TITLE
切换标签页时，切到谷歌新标签页等页面时失效

### ISSUE THREAD

**Issue by libukong007** [gdh1995/vimium-c#140]
1.80.3版本，切换标签页时，切换到谷歌主页、谷歌应用商店等页面时，无法使用。

**Comment by gdh1995** [comment]
百度主页可以吗？

可以的话，就是浏览器限制了扩展程序的作用范围，为了避免扩展程序伪造应用商店页面

**Comment by libukong007** [comment]
方便即时通讯吗，我的qq328326235  或者我加你啊。跪谢~~

**Comment by gdh1995** [comment]
发着就行

**Comment by gdh1995** [comment]
我现在在加班，想尽量走文字记在这儿，这样以后闲下来梳理的时候不至于忘掉

**Comment by libukong007** [comment]
百度主页可以继续切换，谷歌商店，和新开谷歌主页就不行了。

**Comment by gdh1995** [comment]
谷歌商店没办法，安全考虑限制了。

“新开谷歌主页”是说新标签页，还是从收藏夹/手动输入URL打开的页面？搜索结果页面能吗？能的话就说明Vimium C工作正常，不能的话就是bug了

**Comment by libukong007** [comment]
切换到infinity 、one tab 等插件时也不行了，我一直用的vimium，就是这个问题。看到你的这个版本说是可以解决，就下载了，发现现在也不行啊，是要如何改设置啊。

**Comment by libukong007** [comment]
谷歌搜索结果的页面一直可以用的。

**Comment by libukong007** [comment]
我就是想解决 切换标签页中断的问题

**Comment by libukong007** [comment]
就是一旦切换到这些插件，谷歌主页，就中断了。

**Comment by libukong007** [comment]
网址过滤规则 可以解决这个问题吗。我没设置过这个选项

**Comment by gdh1995** [comment]
需要对方扩展程序主动允许并申请加载Vimium C才行。你可以：
* 安装重定向新标签页的扩展，然后设置成Ctrl+T重定向到百度之类
  * 比如 https://chrome.google.com/webstore/detail/newtab-adapter/cglpcedifkgalfdklahhcchnjepcckfn
* 安装”微度新标签页修改版“试试，这个是我修改后的微度扩展，支持Vimium C
* 你自己修改你正在用的新标签页类的插件
  * 步骤介绍: https://github.com/gdh1995/vimium-c/issues/24#issuecomment-428899877
  * 具体文档: https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions

**Comment by gdh1995** [comment]
如果只是需要“切换到左/右标签页”之类的快捷键，不需要<kbd>F</kbd>的提示标记和搜索条的话，可以设置全局快捷键， 打开 chrome://extensions/shortcuts 就能看到了

**Comment by libukong007** [comment]
这个对我们大量的技术小白来说就搞不定了啊。你能抽空出个图文或者视频教程嘛，真的很多像我这样的小白在等解决这个问题呢。

**Comment by libukong007** [comment]
需要F 和O 这些常用功能啊

**Comment by gdh1995** [comment]
这周没时间，我今天加班的活还没干完呢。

其实没几步，核心就是找到想要改的扩展程序 所在的文件夹，改 `manifest.json` 和 `index.html`，你可以用网页翻译阅读 https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions 试试。

微度新标签页修改版 是我自己用的，你也可以试试，基本的新标签页功能都有，只是原版好久不维护了，界面风格和 infinity 这种有差距。

One Tab 这种就只能你自己改了。我自己机子上基本上没有直接安装的扩展，都是我把扩展安装后复制走文件夹，添加支持Vimium C，然后手动在 Chrome 里加载这些文件夹，这样我需要的页面上都有”F“，但每个人常用的扩展都有区别，还是要你会改才行。

**Comment by libukong007** [comment]
你可以抽空把你软件上的功能录个视频详细讲解给我们这些小白嘛。另外，我在媒体工作，也在北京。你方便加我个微信,或者我加你嘛。技术上的这类选题我也很关注，后边有合适的选题也想向你请教呢。

**Comment by libukong007** [comment]
我的微信号是18701476120

**Comment by gdh1995** [comment]
临时翻译一篇文档还行。但做视频就更麻烦了，我还欠了几个issue没修、两个大功能没做呢。

**Comment by draymondgewade** [comment]
> 如果只是需要“切换到左/右标签页”之类的快捷键，不需要 F 的提示标记和 O 的搜索条的话，可以设置全局快捷键， 打开 chrome://extensions/shortcuts 就能看到了

![image](https://user-images.githubusercontent.com/43830206/161723503-bcd2ff46-c770-4a6f-a557-b6eae8d15d8f.png)
并没有看过全局快捷键里有切换标签页的全局快捷键

**Comment by gdh1995** [comment]
截图里是 vimium，不是vimium c，请重新确认你想用什么插件



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月5日(周二) 下午5:27
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [gdh1995/vimium-c] 切换标签页时，切到谷歌新标签页等页面时失效 (#140)




  
如果只是需要“切换到左/右标签页”之类的快捷键，不需要 F 的提示标记和 O 的搜索条的话，可以设置全局快捷键， 打开 chrome://extensions/shortcuts 就能看到了
  

 并没有看过全局快捷键里有切换标签页的全局快捷键

**Comment by draymondgewade** [comment]
> 截图里是 vimium，不是vimium c，请重新确认你想用什么插件
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年4月5日(周二) 下午5:27 收件人: ***@***.***&gt;; 抄送: "Dahan ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [gdh1995/vimium-c] 切换标签页时，切到谷歌新标签页等页面时失效 (#140) 如果只是需要“切换到左/右标签页”之类的快捷键，不需要 F 的提示标记和 O 的搜索条的话，可以设置全局快捷键， 打开 chrome://extensions/shortcuts 就能看到了 并没有看过全局快捷键里有切换标签页的全局快捷键 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;
明白了, 感谢
