### ISSUE TITLE
Some pages break on F press after a certain distance is scrolled down

### ISSUE THREAD

**Issue by Bumbadawg** [gdh1995/vimium-c#141]
Example page used https://en.wikipedia.org/wiki/2019%E2%80%9320_coronavirus_pandemic
Pressing F at the first scroll downs works.
After ~1000px are scrolled, F doesn't work anymore. I used a temporary container to clean the browser cache but it persisted.
I tried Vanilla FF, clean settings of Vimium C, more characters for the "F" function, still happening.

**Comment by gdh1995** [comment]
Confirmed. Thanks. I'll fix this in one day.

**Comment by Bumbadawg** [comment]
Awesome, you're super fast!

**Comment by IzakMarais** [comment]
I get the problem that F doesn't work any-more on this page: https://www.eurogamer.net/ without needing to scroll down first.

**Comment by GLodi** [comment]
I should also mention that some pages also break the vomnibar (o and O)

**Comment by gdh1995** [comment]
Thank you, and could you gvoe some example pages?



---Original---

**Comment by GLodi** [comment]
It's weird because it's inconsistent
 - ansa.it (italian news agency) : j,k,d,u,f,o don't work
 - ebay.it : f doesn't work
 - twitch.tv : j,k,d,u don't work but both f and o do
I'm still using firefox 74 under archlinux

**Comment by gdh1995** [comment]
What's your version of Vimium C ? V1.81.1 has a typo which broke scrolling, and v1.81.2 should have fixed it.

This issue is because of a typo about `f` and the patch is not released yet.

**Comment by GLodi** [comment]
I'm already using v1.81.2

**Comment by GLodi** [comment]
I may have had to restart Firefox, now everything seems to work. Thanks.
