### ISSUE TITLE
Select the first result by default for tabs and bookmarks in vomnibar

### ISSUE THREAD

**Issue by sherifkandeel** [gdh1995/vimium-c#144]
This was [a similar issue](https://github.com/philc/vimium/issues/568) on vimium. 

I find the default behaviour to search google for the word a bit counter intuitive, specially while using vomnibar to navigate already open tabs. 

An alternative would be to have this as a configurable option.

**Comment by gdh1995** [comment]
Please test this: [vimium_c-1.81.3-chrome-91c4e3a.zip](https://github.com/gdh1995/vimium-c/files/4387737/vimium_c-1.81.3-chrome-91c4e3a.zip)

**Install**:
* unzip a zip file into an empty folder
* if on Chrome, open `chrome://extensions/` and enable the "developer mode"
* if on Firefox, open `about:debugging#/runtime/this-firefox` manually
* click the "load extension" button and select the extension folder or `manifest.json`

**Comment by gdh1995** [comment]
Vimium C v1.81.4 has been released, and Vomnibar will auto select the first result in bookmarks, history and tabs mode.

If someone wants to turn off it, please add an option `autoSelect=false` to `Vomnibar.activate***` commands.
