### ISSUE TITLE
I cannot select scrollable element without a scroll bar.

### ISSUE THREAD

**Issue by crocket** [gdh1995/vimium-c#147]
YouTube sidebar often doesn't have a scroll bar, but it is scrollable.
So, I often cannot choose the YouTube sidebar after pressing `f`.

There are many scrollable elements without a scroll bar.

**Comment by gdh1995** [comment]
`LinkHints` will show a red hint marker for those "scrollable", and after one selects such a marker `j` will scroll the area, but if there's no marker for one area, then it means the page is using JavaScript to manually deal with scrolling requests.

If there're some demo URLs and snapshots, maybe I can improve the detection logic - while of course it's not always possible.

**Comment by crocket** [comment]
The sidebar on youtube.com shows a scrollbar only when the mouse cursor is on the sidebar.

![youtube sidebar](https://user-images.githubusercontent.com/748856/77986117-46777300-7351-11ea-8af4-26417e27b0f2.png)

On [London Real YouTube channel](https://www.youtube.com/channel/UCCZVmatSqIMTTB8uExk8xEg), there are scrollable elements.

![youtube channel scrollable elements](https://user-images.githubusercontent.com/748856/77986288-af5eeb00-7351-11ea-8058-cbcb299f63cf.png)

On [slant](https://www.slant.co/topics/6128/~pixel-art-games), you can also see a scrollable element without a scrollbar.

![slant scrollable element](https://user-images.githubusercontent.com/748856/77986458-167c9f80-7352-11ea-873e-a0371790e704.png)

If I press `;fs`, SurfingKeys extension displays hints for those scrollable elements.

**Comment by gdh1995** [comment]
The 1st snap on Youtube: it's strange that I found "the box is scrollable on Chrome" - according what I saw in its source code, it should be never scrollable. I'll test more in days.

2nd snap of "latest interviews": you may use LinkHints to click the left/right buttons - my touchpad could not directly scroll the boxes left or right, so I think it's OKay for Vimium C to treat them as not scrollable.

3rd of slant: the left/right arrow buttons are also hinted by LinkHints.

**Comment by gdh1995** [comment]
> If I press `;fs`, SurfingKeys extension displays hints for those scrollable elements.

Then how does SurfingKeys scroll the boxes, on what keyboard shortcuts?

**Comment by crocket** [comment]
> Then how does SurfingKeys scroll the boxes, on what keyboard shortcuts?

`0` scrolls all the way to the left
`$` scrolls all the way to the right.
`j` scrolls down.
`k` scrolls up.
`d` scrolls half a page down.
`e` and `u` scroll half a page up.
The usual scrolling keys apply.

**Comment by gdh1995** [comment]
Confirmed that SurfingKeys can find them, though it also shows some wrong hints after `;fs` on some sites.

The sidebar of YouTube uses a dynamic CSS style to make it "scrollable only when a mouse is on it"; the other places use JavaScript code to do real scrolling, so it's somehow "correct" that Vimium C thinks they are not scrollable.

Maybe I can add a new mode like `LinkHints.activateModeToScroll` to also show hints for such elements.

**Comment by gdh1995** [comment]
Here's a new version, and `map f LinkHints.activate scroll="force"` will make `LinkHints` think more elements are clickable.

Please test this: [vimium_c-1.81.4-chrome-611e169.zip](https://github.com/gdh1995/vimium-c/files/4431478/vimium_c-1.81.4-chrome-611e169.zip), [vimium_c-1.81.4-firefox-611e169.zip](https://github.com/gdh1995/vimium-c/files/4431651/vimium_c-1.81.4-firefox-611e169.zip).

**Install**:
* unzip a zip file into an empty folder
* if on Chrome, open `chrome://extensions/` and enable the "developer mode"
* if on Firefox, open `about:debugging#/runtime/this-firefox` manually
* click the "load extension" button and select the extension folder or `manifest.json`

**Comment by crocket** [comment]
In chrome, vivaldi, and brave, the chrome extension fixed the issue.
In firefox, it fixes the issue, but I can't shift the focus of scroll back to the main contents with `f` on youtube.com

**Comment by gdh1995** [comment]
`map Ff LinkHints.activateModeToHover` may help, because it simulates "mouse hover" events on a target element and notifies Scroller to select the target.

**Comment by crocket** [comment]
`Ff` correctly puts the scroll focus back to the main contents, but having two shortcuts for the same thing is confusing. I still haven't understood how it works.

**Comment by gdh1995** [comment]
* `LinkHints.activateMode` simulates "click" action.
* `LinkHints.activateModeToHover` simulates "mouse hover" action, and it has a side effect of notifying Scroller to remember an element or its container should be scrolled

**Comment by crocket** [comment]
What are you going to do?

**Comment by gdh1995** [comment]
What? Sorry I don't understand your last comment.

**Comment by crocket** [comment]
It seems you figured out how to fix the issue. How are you going to fix this issue?
Do you need more information from me?

**Comment by gdh1995** [comment]
Um, the zip file is just the version that "fixes" this issue: the 3 examples you gave are "not scrollable by default", and all require pages' JavaScript code / special CSS status to do scrolling; but Vimium C can not recognize whether an element is "scrollable if relaxing some rules" or not, so I added an option of `scroll="force"` to let users choose what rules it should use.

If you agree that this version is enough, then a new release will arrive in next 5~10 days with logic in this zip file.

**Comment by crocket** [comment]
I think the new version is good enough. I'd like some documentation on LinkHints.activate and LinkHints.activateModeToHover because I didn't know they existed.

**Comment by gdh1995** [comment]
Sorry but in recent months (years?) I have no enough patience and time to write documents - I would rather write new features or relax & sleep ...

**Comment by gdh1995** [comment]
On the Vimium C Options page, press `?` and you may see a help dialog of Vimium C, and click "show advanced commands" at its bottom-right corner to see the whole list of available commands.

**Comment by gdh1995** [comment]
On the Vimium C Options page, press `?` and you may see a help dialog of Vimium C, and click "show advanced commands" at its bottom-right corner to see the whole list of available commands.

**Comment by crocket** [comment]
`show available commands` shows parameters and parameter values of functions. Ideally, I'd like some documentation for `scroll`. But, feel free to solve this issue in any way you want to.

**Comment by gdh1995** [comment]
v1.81.5 has been released.

**Comment by crocket** [comment]
Thank you.
