### ISSUE TITLE
能否增加"关闭重复标签页"

### ISSUE THREAD

**Issue by lazycatme** [gdh1995/vimium-c#148]
能否增加: 多个标签页重复时, 关闭重复的剩余1个呢

**Comment by gdh1995** [comment]
呃回头我想想。能否具体描述你觉得该怎么找到其它要关闭的标签页？
* 只对当前标签页找重复的，还是所有的都找重复的？
* 找所有的话，保留第一个、最后一个、还是最近访问的那个标签页？
* 基于URL完整匹配，还是忽略URL里“#”后边的内容？
* 是否要检查这些标签页的标题是否一致？

**Comment by lazycatme** [comment]
我使用的一般情况, 同一个窗口开了几个相同url的标签, 我觉得保留最后访问关闭同一个窗下其他url一致的标签, 当然, 有参数可选能按个人所需配置就更好了~

**Comment by gdh1995** [comment]
测试版用法：`map Xa closeOtherTabs filter="url"` 表示只按网址“#”之前的部分筛选重复标签页，如果`filter=`右边是url+hash，则按完整网址筛选，如果是url+hash+title，则同时要求标题相同；目前只会在当前窗口的标签页里筛选。

Please test this: [vimium_c-1.81.4-chrome-611e169.zip](https://github.com/gdh1995/vimium-c/files/4431478/vimium_c-1.81.4-chrome-611e169.zip), [vimium_c-1.81.4-firefox-611e169.zip](https://github.com/gdh1995/vimium-c/files/4431651/vimium_c-1.81.4-firefox-611e169.zip).

**Install**:
* unzip a zip file into an empty folder
* if on Chrome, open `chrome://extensions/` and enable the "developer mode"
* if on Firefox, open `about:debugging#/runtime/this-firefox` manually
* click the "load extension" button and select the extension folder or `manifest.json`

**Comment by gdh1995** [comment]
新版v1.81.5已发布。
