### ISSUE TITLE
PDF Viewer, feature request: Make it possible to hide the toolbar

### ISSUE THREAD

**Issue by agzam** [gdh1995/vimium-c#150]
It would be nice if there's a toggle to hide the toolbar.

![image](https://user-images.githubusercontent.com/1091022/78465286-89667d00-76a8-11ea-90c2-eb5d80e2f9b2.png)

Thanks you!

**Comment by gdh1995** [comment]
Well, in fact this is a feature suggestion for https://github.com/mozilla/pdf.js . I don't like to add too many features by myself, beacuse it would make further merging from pdf.js more difficult.

**Comment by agzam** [comment]
Good to know. I'll close the issue then. Thank you!
