### ISSUE TITLE
PDF Viewer: Cmd/Ctrl+F binding conflicts with browser's Cmd+Shift+F

### ISSUE THREAD

**Issue by agzam** [gdh1995/vimium-c#151]
Keybinding to for Find feature of PDF viewer seems to be conflicting with Browser's built-in `Cmd/Ctrl+Shift+f` keybinding

![image](https://user-images.githubusercontent.com/1091022/78465324-190c2b80-76a9-11ea-9b35-6ed373f63af4.png)

Expected behavior: Pressing `Cmd+Shift+f` should not toggle Find panel

![image](https://user-images.githubusercontent.com/1091022/78465333-422cbc00-76a9-11ea-9fe5-3d240e2b7016.png)

**Comment by gdh1995** [comment]
Confirmed, and I'll release a new version when pdf.js arrives in a new version.
