### ISSUE TITLE
快速跳转到某标签页

### ISSUE THREAD

**Issue by StephenWu5** [gdh1995/vimium-c#153]
我可以提个需求吗？就是我已经安装了一个插件显示标签页的序号，输入2gt，发现右移两个标签页，我的目的是要跳转到序号为2的标签页。你能实现它吗？

if you can't see my words，you can translate them in google. this question is important to me.

**Comment by gdh1995** [comment]
有个命令是firstTab, 使用时加个前缀2就行



---原始邮件---
发件人: "StephenWu5"<notifications@github.com&gt;
发送时间: 2020年4月10日(周五) 中午12:07
收件人: "gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [gdh1995/vimium-c] 快速跳转到某标签页 (#153)




 
我可以提个需求吗？就是我已经安装了一个插件显示标签页的序号，输入2gt，发现右移两个标签页，我的目的是要跳转到序号为2的标签页。你能实现它吗？
 
if you can't see my words，you can translate them in google. this question is important to me.

**Comment by StephenWu5** [comment]
谢谢大佬
