### ISSUE TITLE
Enhancement: Add date/time in "history" (CTRL-O) results

### ISSUE THREAD

**Issue by afilp** [gdh1995/vimium-c#154]
When I searched in history I was not sure if the results were sorted with DESC date/time, so that I can use the latest URL parameters of some URL:

![image](https://user-images.githubusercontent.com/7850073/79113774-55ffae80-7d8a-11ea-9b2b-ec9ebd141af8.png)

Apart from that, I believe it would be useful to have the date/time on history access (maybe on bookmarks too), as proposed above.

The button could also be "sticky" among different searches (i.e. remember its status, so we only have to press/depress it once to choose if we want to see the "more info" date/time or not).

Thanks!

**Comment by gdh1995** [comment]
Hello, I've implemented a base version and you may take a try: [vimium_c-1.84.1-chrome-571003e.zip](https://github.com/gdh1995/vimium-c/files/4944346/vimium_c-1.84.1-chrome-571003e.zip), [vimium_c-1.84.1-firefox-571003e.zip](https://github.com/gdh1995/vimium-c/files/4944347/vimium_c-1.84.1-firefox-571003e.zip).

The time string is not added by default, you'll need to add some keywords to the `styles` of `Vomnibar settings`:
* `time` means to show time spans relative to "now"
* `time absolute-time` means to show local time strings
* `time absolute-num-time` means to show standard date time strings (only including English characters)

For example, `{ ..., "style": "mono-url time absolute-time" }` means the second one.

How to install .zip: https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package

**Comment by gdh1995** [comment]
Hello, Vimium C v1.84.2 has been released on Firefox Add-ons and Chrome Web Store, and Edge Addons is verifying it, so you may take a try.
