### ISSUE TITLE
Document scroll parameter for LinkHints.activate

### ISSUE THREAD

**Issue by crocket** [gdh1995/vimium-c#155]
1.81.5 added scroll parameter to LinkHints.activate, but scroll parameter is not documented in Vimium C Command Listing, yet.

**Comment by gdh1995** [comment]
The `scroll` option is to support #147 , so you may read the comments to see what it solves.

`LinkHints,activate` has too many parameters, so currently I recommend users who want to know advanced usages read the source code (sorry for this but I have no much rest time to write doc) ...

https://github.com/gdh1995/vimium-c/blob/dc16f7f111d68869a27c770767588f6a95107f6b/types/messages.d.ts#L205-L227

**Comment by crocket** [comment]
Perhaps, you want to tell users to read the source code somewhere.

**Comment by gdh1995** [comment]
https://github.com/gdh1995/vimium-c/wiki/List-of-all-commands has been updated and I added a link to `types/messages.d.ts`, although for commands which operates tabs and windows, there's still no 
option list for them.

**Comment by crocket** [comment]
I don't know that's enough, but I'm going to close it for now.
