### ISSUE TITLE
`ge` and `gE` go up the URL path instead of launching a vomnibar.

### ISSUE THREAD

**Issue by crocket** [gdh1995/vimium-c#156]
`ge` and `gE` are supposed to launch a vomnibar with the current URL.
If I press either of `ge` and `gE`, https://www.youtube.com/watch?v=ARSvLiG-5iU becomes https://www.youtube.com

I expected `ge` and `gE` to show a vomnibar with the current URL.

**Comment by gdh1995** [comment]
What're your key mappings? Have you enabled the option `Ignore keyboard layout`? And what's your system keyboard layout?

**Comment by crocket** [comment]
Custom key mappings

```
mapKey e u
unmap <f2>
map f LinkHints.activate scroll="force"
map <a-h> LinkHints.activateModeToHover
```

After removing `mapKey e u`, `ge` and `gE` started working as expected.
I didn't know `gu` and `gU` was somehow mapped to going up the URL path.

**Comment by crocket** [comment]
The following custom key mappings fix the issue.

```
map e scrollPageUp
unmap <f2>
map f LinkHints.activate scroll="force"
map <a-h> LinkHints.activateModeToHover
```
