### ISSUE TITLE
suggestion about vomnibar

### ISSUE THREAD

**Issue by in-character** [gdh1995/vimium-c#157]
1. Vomnibar.activateInNewTab
建议在搜索结果中，将书签放到历史记录的上方，我觉得user 搜索书签的频率会远大于搜索历史记录的频率

2. Vomnibar.activateBookmarksInNewTab
调用Vomnibar.activateBookmarksInNewTab使用自定义搜索引擎搜索时，前面要加  ":o"，我觉得这样太繁琐了，Vomnibar.activateInNewTab就可以直接使用搜索引擎的关键字进行搜索，Vomnibar.activateBookmarksInNewTab可以同样实现吗

**Comment by gdh1995** [comment]
1. `map g Vomnibar.activate mode="bomni"` 可以让书签更优先；或者用 `:b` 前缀临时切换到纯书签模式
2. 不可以，`activateBookmarksInNewTab`里的`Bookmarks`意思就是纯书签模式。

**Comment by in-character** [comment]
大佬，你不是该好好编写个wiki了，像这些参数的配置每次都亲自回答，不累吗

**Comment by gdh1995** [comment]
“写wiki”想着就累，就一直拖着了Orz

**Comment by in-character** [comment]
`map f Vomnibar.activateInNewTab mode="bomni" exitOnClick`
图片中第一条历史记录，第二个是书签。。。
![Screenshot from 2020-04-18 13-14-37](https://user-images.githubusercontent.com/52375886/79644400-c3d71c00-8176-11ea-961f-50127ee98a0d.png)

**Comment by in-character** [comment]
press “Down” key，focus第一条结果时， 如下图
![Screenshot from 2020-04-18 13-23-14](https://user-images.githubusercontent.com/52375886/79644574-d867e400-8177-11ea-9f23-ae1ee42c0e5c.png)

press “Down” key， focus第二条结果时， 如下图
![Screenshot from 2020-04-18 13-23-16](https://user-images.githubusercontent.com/52375886/79644607-0e0ccd00-8178-11ea-8189-4310ea448e3a.png)

**Comment by gdh1995** [comment]
没看懂，这两张图一样吧？



---Original---

**Comment by gdh1995** [comment]
哦看懂了。`bomni`意思是把书签当作“5分钟前访问过”处理，综合排序时仍然同时参考字符串匹配度和最近访问时间这两个因素。

**Comment by in-character** [comment]
我在想将  `:o`  变为大写的 `:O` 是不是更好一点。

**Comment by sisrfeng** [comment]
> 当作“5分钟前访问过”处理
能不能把这个时长 改成可配置的变量？

**Comment by gdh1995** [comment]
不打算改，就算是加一个数字配置项也不会够，总有遇到对排序不满意的时候，总不能让用户自定义一个函数来打分。

另外，如果书签最近 5 分钟里被访问过，在历史记录里就会排到高分，不用担心搜不到。
