### ISSUE TITLE
Feature request: autoCopy when autoOpen

### ISSUE THREAD

**Issue by krtns** [gdh1995/vimium-c#159]
First of all thanks for constantly adding new features to this extension and making it better. I was a user of vimium but switched to vimium-c for the autoOpen feature (saw your comment in one of vimium's issue)

I would like to autoCopy the selected text when I autoOpen it in another tab. Is this possible?

**Comment by gdh1995** [comment]
Do you mean "copy text and open/search it in another tab"? Currently you have to do them separately with Vimium C.

**Comment by ks-net-positive** [comment]
Wow, thanks for the quick reply. Yeah, I would like to do both of them in one keystroke

**Comment by gdh1995** [comment]
Why do you want it? It's possible to implement it, but I wonder a real use case.

**Comment by ks-net-positive** [comment]
When I read an article, I use autoOpen to google stuff (technical terms, etc) I find new. I want to keep track of what items were new to me. For this I use a clipboard manager which keeps track of what I copied. So if I want to add text the clipboard history and also search for it, I have to autoCopy it and also autoOpen it using two keystrokes. I want to do both of them using one keystroke.

I agree this is a very rare use case and probably only useful to few people. I would be willing to make a local code change to a specific file/function in which autoOpen is implemented to also autoCopy it..

**Comment by gdh1995** [comment]
A convincing use case. Then I'll implement it in a next version, which will arrive in about one month.

**Comment by ks-net-positive** [comment]
Oh, thanks! Are you planning to create another action like autoCopyAndOpen which will do this?

**Comment by gdh1995** [comment]
It may be a new option, like `map CC autoOpen copy=true`.

**Comment by gdh1995** [comment]
Hello, you may try this: [vimium_c-1.81.5-chrome-45bc0bc.zip](https://github.com/gdh1995/vimium-c/files/4523108/vimium_c-1.81.5-chrome-45bc0bc.zip), 
[vimium_c-1.81.5-firefox-45bc0bc.zip](https://github.com/gdh1995/vimium-c/files/4523106/vimium_c-1.81.5-firefox-45bc0bc.zip)

**Install**:
* unzip a zip file into an empty folder
* if on Chrome, open `chrome://extensions/` and enable the "developer mode"
* if on Firefox, open `about:debugging#/runtime/this-firefox` manually
* click the "load extension" button and select the extension folder or `manifest.json`

**Comment by ks-net-positive** [comment]
Hey! Thanks for the quick implementation! Will check it out :)

**Comment by gdh1995** [comment]
Hello, v1.83.0 has been released on Chrome Web Store and Firefox Add-ons, and you may take a try.
