### ISSUE TITLE
add langmap setting

### ISSUE THREAD

**Issue by KamiGim** [gdh1995/vimium-c#16]
can you guy make this setting possible like this extension [cVim](https://github.com/1995eaton/chromium-vim) I want to use this for my own language keyboard also
Thanks

**Comment by gdh1995** [comment]
Um, sorry but I know little about keyboard layouts, so I can not understand code about it in the original project https://github.com/philc/vimium well.

(I think) currently this extension should have partly supported European languages like German, and if not or you're using some others, you may use Vimium instead.

(For web developers) if you know about JavaScript and keyboard layout detection, code suggestions and PRs are welcomed.

**Comment by gdh1995** [comment]
Closed, because I've merged the whole logic about ignoreKeyboardLayout in https://github.com/philc/vimium. Thanks anyway for your contribution.
