### ISSUE TITLE
marks unable to be set?

### ISSUE THREAD

**Issue by TheSre** [gdh1995/vimium-c#160]
Firstly, thanks so much for all your work!
It seems like setting new marks no longer works (local and global). I can still jump to existing marks, but I'm unable to set new marks and jump to them. It just says that the mark is not set, so it seems like they aren't being created for some reason. I'm not sure if this is related to the latest update, but I've only noticed this today.
Thanks,
Sean

**Comment by gdh1995** [comment]
What's the detailed error tip? Sorry I didn't reproduce it.

**Comment by TheSre** [comment]
It just says "Global mark not set : 'v'." Before getting that message, I created the mark and the message (in the same location, the pop-up area where searching is also done) was "Created global mark : 'v'."

**Comment by gdh1995** [comment]
Are both two <kbd>v</kbd> lower-case? Is there `map *** Marks.activate swap` in your key mappings?

**Comment by TheSre** [comment]
Yes, they are both lower-case. Here are my relevant key mappings: 
```
map go Marks.activate swap
map m Marks.activateCreateMode swap
```

**Comment by TheSre** [comment]
Yes, they are both lower-case. Here are my relevant key mappings: 
```
map go Marks.activate swap
map m Marks.activateCreateMode swap
```

**Comment by gdh1995** [comment]
Oh it's a bug which only broke release versions of Vimium C, and fortunately it seems that only Marks are affected.

**Comment by gdh1995** [comment]
Oh it's a bug which only broke release versions of Vimium C, and fortunately it seems that only Marks are affected.

**Comment by TheSre** [comment]
Sorry, I'm a bit confused as to what you mean the solution is...should I change my version of Vimium C?

**Comment by gdh1995** [comment]
You can wait a new release version of Vimium C, or compile the `v1.81.5` version of code by yourself, or use these zip files: [vimium_c-1.81.5-chrome-debug.zip](https://github.com/gdh1995/vimium-c/files/4519796/vimium_c-1.81.5-chrome-debug.zip), or [vimium_c-1.81.5-firefox-debug.zip](https://github.com/gdh1995/vimium-c/files/4519808/vimium_c-1.81.5-firefox-debug.zip)

**Install**:
* unzip a zip file into an empty folder
* if on Chrome, open `chrome://extensions/` and enable the "developer mode"
* if on Firefox, open `about:debugging#/runtime/this-firefox` manually
* click the "load extension" button and select the extension folder or `manifest.json`
