### ISSUE TITLE
searchas searchanother 设定搜索引擎参数不起作用

### ISSUE THREAD

**Issue by Tback1** [gdh1995/vimium-c#161]
我自己试图定义豆瓣电影和豆瓣图书作为搜索关键字
db|: https://www.douban.com/search?cat=1001&q=%s 豆瓣图书
dm|: https://www.douban.com/search?cat=1002&q=%s 豆瓣电影

map sdb searchInAnother keyword="db"
map sdm searchInAnother keyword="dm"

但是每次按下sdb或者sdm都是 没有未找到该名称的搜索引擎

于是我按照另一个[issus](https://github.com/gdh1995/vimium-c/issues/1#issuecomment-276855344)的说明,导入了recommend设定,
随便测试了一组
map GG searchInAnother keyword="g"
g|gg|ggg|Google|google|个: https://www.google.com/search?ie=utf-8&q=$s \
  www.google.com re=/^(?:\.[a-z]{2,4})?\/search\b.*?[#&?]q=([^#&]*)/i \
  blank=https://www.google.com Google

依旧是找不到该名称的搜索引擎

**Comment by gdh1995** [comment]
db, dm的定义是写在自定义快捷键里了，还是自定义搜索引擎里了？点保存了吗

**Comment by gdh1995** [comment]
哦我复现成功了，我查查

**Comment by gdh1995** [comment]
是提示文字显示错了，应该显示“未识别到搜索词”。就是这个功能需要根据当前网页的 URL 识别出来搜索词，才能用指定的搜索引擎去搜索。

就是如果你当前网页的URL匹配不到“自定义搜索引擎”配置的那些规则，就没法跳转了

**Comment by Tback1** [comment]
@gdh1995 明白了错误的原因了~我本来理解成了这个searchas与searchanother是当例如我用v模式选择了一段文字后,快捷利用预定义搜索引擎去搜索的功能~

现在是不明白的部分,不懂就问吧:   那现在我好奇的是,设定这样一个根据URL匹配的本意是想用来做什么??是想在什么场景下实现什么功能呢?

**Comment by gdh1995** [comment]
切换搜索引擎，比如对百度的结果不满意，就切换到谷歌，或者必应

**Comment by gdh1995** [comment]
> 例如我用v模式选择了一段文字后,快捷利用预定义搜索引擎去搜索

这个可以用 autoOpen 做，默认搜索选中文字，没有的话就搜索剪贴板里的文字

**Comment by Tback1** [comment]
> > 例如我用v模式选择了一段文字后,快捷利用预定义搜索引擎去搜索
> 
> 这个可以用 autoOpen 做，默认搜索选中文字，没有的话就搜索剪贴板里的文字

autoOpen只能用默认的搜索引擎搜索吧?
比如我在任意某个网页上复制了一本书的名字,默认的搜索引擎是Google,想要按下sdb调用豆瓣图书搜索,应该用searchInAnother对么?但是按您的设定,似乎又不行?

**Comment by gdh1995** [comment]
`map *** autoOpen keyword="db"`

**Comment by sunshinesDL** [comment]
> searchInAnother 切换搜索引擎，比如对百度的结果不满意，就切换到谷歌，或者必应
> 
> searchAs 切换搜索词，比如保留一个词典网页，在别的程序上复制词语到剪贴板，然后浏览器里用快捷键立即搜索新词

非常感谢您的解释，读懂这个快捷键的内容了 😁😁
