### ISSUE TITLE
dark mode, not working?

### ISSUE THREAD

**Issue by in-character** [gdh1995/vimium-c#162]
系统应用了黑色主题，firefox也是黑色，vimium设置中也勾选了“ Auto switch between light and dark mode”， 然而，没有生效

os：ubuntu 19.10
screenshot:
![Screenshot from 2020-04-23 03-28-27](https://user-images.githubusercontent.com/52375886/80071674-0603b300-8513-11ea-8182-5d4888665bbd.png)

**Comment by gdh1995** [comment]
可能是最近 1.81.* 这几个版本的代码压缩脚本的问题（#160），试试这个未压缩的版本能不能用：[vimium_c-1.81.5-chrome-debug.zip](https://github.com/gdh1995/vimium-c/files/4519796/vimium_c-1.81.5-chrome-debug.zip), or [vimium_c-1.81.5-firefox-debug.zip](https://github.com/gdh1995/vimium-c/files/4519808/vimium_c-1.81.5-firefox-debug.zip)

**Install**:
* unzip a zip file into an empty folder
* if on Chrome, open `chrome://extensions/` and enable the "developer mode"
* if on Firefox, open `about:debugging#/runtime/this-firefox` manually
* click the "load extension" button and select the extension folder or `manifest.json`

**Comment by in-character** [comment]
他自己又好了，可以是我重启了一下系统

**Comment by gdh1995** [comment]
哦你是不是刚刚修改的黑色主题？受浏览器提供的接口的限制，在Vimium C里生效需要一分钟左右。

**Comment by in-character** [comment]
的确是新设置的系统黑色主题，确定刷新了好几遍

**Comment by gdh1995** [comment]
测了一下Vimium C v1.81.5 + Win 10 + Firefox 74，刷新设置页面时成功检测到了暗色模式并变暗。估计是Firefox在Linux下兼容性叕出问题了。
