### ISSUE TITLE
关于 Vimium C 的整体性思考

### ISSUE THREAD

**Issue by in-character** [gdh1995/vimium-c#163]

**Comment by in-character** [comment]
> 按照重要顺序，依次排列

1. 简易模式  专业模式

   - 设计

     ```
     新设计一个针对新用户的配置界面，专业模式可以沿用原本的vimium配置页面。
     1. 当时我新安装vimium的时候，进入配置界面，第一眼感觉，这个扩展很牛B，第二眼，我想直接卸了，继续用我的鼠标手势操作
     
     ```

     - 基本配置，保留一些常用到重要的基本配置

     - 配置快捷键，仅保留常用快捷键

       操作标签页方面：

       浏览方面：pageUp/Down、back/forward、..

       功能性方面：进入下一页、静音、静音其它标签页、focusInput、vomnibar

     - 其它

       鼠标悬浮到某个快捷键配置上，展示功能介绍弹窗

       其它人性化设计 ...

   

   

2. 新标签页适配主流的手势插件（1-3个），新标签页增加一些基本功能，走简洁风格

   ```
   一次开发，配套vimium发挥的作用很大，此项性价比极高
   
   ```

   - 一个搜索框，可以自定义搜索引擎，搜索框可以设置自动隐藏

   - 配置本地上传壁纸或者沿用桌面壁纸

   - 黑暗模式

     

   

3. vomnibar接口的重新设计

   - vomnibar  加 参数， 让用户自定义（在简易模式中，通过复选框，让用户选择参数）

     vomnibar：   书签，历史，使用自定义搜索引擎，

     ​					  是否新标签页打开

     

   

4. 在扩展安装页面列举与原版vimium的对比，对比优势。（此项有一定弊端，商业竞争方面）

   ```
   以上三点就是要介绍的竞争优势，不然拿什么吸引用户，当用户搜索vimium的时候，对比结果时首先看的就是已安装用户量，vimium-c目前劣势很大。
   作者有时间也应该写邮件向国内主流的chrome插件商店推广
   努力就是为了拿成果，vimium-c的用户量一直上不去，你看着不难受吗。上不去不就是因为没亮点，用户自然首先选择用的多的那一个。
   ```

**Comment by gdh1995** [comment]
谢谢你的意见。

主要是我懒得写帮助，一直在做新的功能。图形化帮助界面的话开发量也很多。

新标签页的话我自己定制化了一版“微度新标签页修改版”，不过它已经几年没更新了。如果某个扩展程序主动申请运行Vimium C，那Vimium C是能跑在上边的，比如我定制的“PDF Viewer for Vimium C”。

Vimium C 自己不会集成新标签页功能，之前集成过三年多被不少人要求改，还有直接打一星的。
有现成的开源的优秀新标签页的话，我可以稍稍修改它来在上边跑Vimium C，并发布出来。你有建议吗？

Vomnibar 功能上是挺多的，而且支持动态切换模式，比如搜索词前缀“`:b `”是书签模式，"`:o `"是混合模式；强制新标签页打开的话可以用Ctrl+Enter、后台新标签页打开是Ctrl+Shift+Enter。

简介信息的话回头我可以改改说明，但其实以前有几条对比这两年刚被我删掉，回头我再琢磨琢磨怎么说来得合适。

用户量的话我现在基本全靠中文界面吸引人。去年夏天我才实现的中文翻译，在此之前3500~4000人稳定了一年，确实有点打击人；后来就开始慢慢涨了。

**Comment by in-character** [comment]
---

- 主要思路

  1. 建一个针对新用户的简易配置页面

     - 在设计时，里面的快捷键指令选择好后基本就算是**长期固定**的

     - 图形化帮助目前可以放弃这一点，可以把指令的介绍放到一块去

     - 对指令赋值，不要用`map ...`

       例如：  `名称   指令    一个框框让用户输入按键`

       ​			 后退     goBack      `此处是一个输入框`

- 新标签页

  1. 并不是要集成到vimium-c，在安装页面介绍里，放一个安装链接

  2. 以前只尝试过试用chrome里的新标签页，是否开源并不清楚，8成是没有

     这个虽也有一点缺陷，但已经算是不错的

     ```
     https://chrome.google.com/webstore/detail/dream-afar-new-tab/henmfoppjjkcencpbjaigfahdjlgpegn
     ```

     

- vomnibar

  1. 这就是我最想吐槽的，太多写死的模式

     讲真的这项功能很强，但在使用的时候不要要让用户太繁琐的，让用户实现最流畅的操作，高度自定义的配置，用户会在这一点上上瘾的，用户在使用的过程中会慢慢修正，最终找到最适合自己的

- 简介

  简易有亮点后再修改， 对比vimium，主打精简配置，但却是普通用户最实用的功能，方面对功能配置快捷键，同时又具有vimium专业的配置界面

**Comment by in-character** [comment]
总结一下已有或者未来的优势

- 主打简易却实用性很强的   `简易配置页面`，  在去网上找个极简风格的UI，修改一下

- 定制好的外部新标签

  用户可以一键安装，用户都是很懒的存在，谁想亲自去自定义个新标签页

- vomnibar的高度自定义

- 最后能做的就是去做推广了，写邮件推荐，拍个小视频/录屏

这些都是原版vimium没有但竞争力很强的优势

**Comment by gdh1995** [comment]
你希望vomnibar在哪些地方允许自定义？
目前支持自己写CSS样式，或者用自己写的html文件替换掉内置的html文件，就能随便改了。不过这些都需要知道基础的编写网页的知识



---原始邮件---
发件人: "夜"<notifications@github.com&gt;
发送时间: 2020年4月23日(周四) 晚上6:41
收件人: "gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Dahan Gong"<gdh1995@qq.com&gt;;
主题: Re: [gdh1995/vimium-c] 关于vimium的整体性思考 (#163)




 
总结一下已有或者未来的优势
  
 
主打简易却实用性很强的   简易配置页面，  在去网上找个极简风格的UI，修改一下
 

 
定制好的外部新标签
 
用户可以一键安装，用户都是很懒的存在，谁想亲自去自定义个新标签页
 

 
vomnibar的高度自定义
 

 
最后能做的就是去做推广了，写邮件推荐，拍个小视频/录屏
 
 
这些都是原版vimium没有但竞争力很强的优势

**Comment by in-character** [comment]
调用vomnibar参数：
- 搜索内容上：是否包含书签、历史记录、二者展示的优先级...
- 行为上：打开标签页所在位置(此页，右侧，末尾）、
- 功能上：支持自定义的搜索引擎...

除了预先定义好的1-2个普遍适用的vomnibar模型，用户定义自己倾向的模型，调用时别在输参数（除了一些极特殊的情况），没几个愿意在调用时输参数，这可能需要重新设计接口
例如，在专业模式下： `map vomnibarModel1  后面是一堆定义好的参数`

**Comment by gdh1995** [comment]
Vomnibar 目前支持这些参数：
``` typescript
  interface GlobalOptions {
    mode: string;
    currentWindow?: boolean;
    newtab: boolean | BOOL;
    keyword: string;
    url?: true | string | null;
    exitOnClick?: boolean;
    autoSelect?: boolean | null | BOOL;
    preferTabs?: "new" | "new-opened" | "newOpened";
    noTabs?: boolean;
    icase?: boolean;
    searchInput?: boolean;
    tree?: boolean; // show tabs in tree mode
  }
```

* `map Vomnibar.activate mode="omni"`表示混合模式，`mode="bookm"`表示书签模式，等等。
* `keyword="b"`可以预先输入"`b `"，也就是立即进行百度搜索
* `newtab=true` 表示只按回车的时候也在新标签页打开网址

不过设置新标签页位置的参数还没有，回头我加一个。

**Comment by in-character** [comment]
```
默认：
一个搜索框
搜索结果：
	第一序列：为默认搜索引擎，如果使用自定义搜索关键字，则替换为自定义搜索
	第二序列：为书签搜索结果合集
	第三序列：为历史记录搜索结果集
```

Vomnibar配置选项

- 搜索内容

  - 内容：默认索引擎 书签 历史记录

    > 备注：如果勾选默认搜索引擎，则其在搜索结果中始终为第一序列
    >
    > ​			即使未勾选默认搜索引擎，当使用自定义搜索keyword时，仍激活自定义引擎搜索

    展示：是否隐藏第一条“引擎搜索项的展示”

    ​			书签和历史记录的展示优先级

- 行为

  - 输入后，按enter键的默认行为（使用搜索引擎或者激活第一条搜索结果）

    ​				按ctrl-enter

    ​				按alt-enter

  - 打开位置

    ​		此页 | 新标签页 | 末尾

  - 关闭后的返回页

    ​		左侧 | 原标签页

  - exitOnClick

**Comment by gdh1995** [comment]
书签、标签页和历史记录的排序是综合“访问时间”和“搜索词相似度”共同算出来的，`bomni`模式会认为书签的访问时间是“5分钟前”，`omni`模式下对于书签只使用“搜索词相似度”来排序。

`Enter`会打开当前选中的搜索结果条目，如果没选中则打开输入的文字。

“关闭标签页后返回哪一个”不该由Vomnibar控制，因为打开标签页后可以做任意操作再关闭。可以设置`removeTab` 命令。

`removeTab`支持`goto=""/left/right/previous`参数，表示：按浏览器默认；左侧；右侧；前一个访问的。

Vomnibar的`exitOnClick`参数表示点击搜索面板之外的地方，自动关闭搜索面板。

**Comment by in-character** [comment]
对于vimium的一些核心东西，感觉你像不打算变动

omni的算法有关的文件是？还是调用的浏览器接口

**Comment by gdh1995** [comment]
匹配和排序完全是自己算的，只有历史记录列表、收藏夹列表本身是走接口渠道的

一些逻辑掉的话有兼容性问题，而且必要性不大。

**Comment by in-character** [comment]
感觉大家都不在一个脑回路上   O__O "…

**Comment by gdh1995** [comment]
哦哦我之前是在说有些参数已经有了。

以后实现界面的话可以参考你列的这些。

omni算法的文件在background/completion.ts 和 front/vomnibar.ts
