### ISSUE TITLE
How to exit insert mode on Google Document

### ISSUE THREAD

**Issue by amufaamo** [gdh1995/vimium-c#165]
How can I use vimium c for Google document?

**Comment by gdh1995** [comment]
Press "Esc" for several times, and then try pressing <kbd>f</kbd> ?

**Comment by amufaamo** [comment]
When I keep pressing Esc, then I could use vimium C. Thank you.

**Comment by amufaamo** [comment]
Sorry, I could use vimium C, but I cannot recover to insert mode. Do you know how to ?

**Comment by gdh1995** [comment]
I just tested it, and found that:
* if Vimium C is in normal mode (no LinkHints / find mode / visual mode / marks / vomnibar), then if press <kbd>Esc</kbd> the caret gets focused again.
* sometimes Google Docs auto focused the caret after Vimium C executed a command

So you may also try such methods.
