### ISSUE TITLE
Allow shortcut while focus is in chrome omnibox

### ISSUE THREAD

**Issue by afilp** [gdh1995/vimium-c#166]
I have `CONTROL-Y` as a shortcut for `activateTabSelection`

`map <c-y> Vomnibar.activateTabSelection icase`

When the focus is inside chrome's omnibox, this does not work:
![image](https://user-images.githubusercontent.com/7850073/80513068-2e623600-8987-11ea-9e39-992f8266fdcc.png)

Can this somehow work? (or is it impossible?)

P.S. My use case is to use vivium-c 'activateTabSelection' while I am in a new page.

**Comment by gdh1995** [comment]
type 'v' and a space charactee to enter Vimium C mode, and then type ":t" to enter 'tab' mode, then you can search.


This search is always case-sensitive.


Currently there's no way to move focus from the address bar to the page itself. But you can install an extension like NewTab Adapter, to make focus in your wanted page, instead of the address bar, when you create a new tab.



---Original---

**Comment by afilp** [comment]
Thank you, I added the NewTab Adapter and it is very good.

1. How can we assign a keyboard shortcut to focus back to the omnibar? 
Do we have such a command? 
(so that we can do this fast without the browser's CTRL-L, F6?)

2. I put a simple web page from my website as "New Page". I tried to programmatically invoke some vimium-c commands through that page (by pressing some links), but I failed. Is there a way to have the commands of vimium-c exposed so that we programmatically call them through our own web page?

Thanks!

access the Vomnibar javascript? I tried to use javascript

**Comment by afilp** [comment]
The problem is that even if we use a "control" combination (example: `map <c-m> Vomnibar.activateTabSelection icase`), when the cursor is in a text input it does not work. 

Example:

![image](https://user-images.githubusercontent.com/7850073/80600399-00d3c600-8a35-11ea-8ddc-a6f7527b628d.png)

**Comment by gdh1995** [comment]
1. No, browser does not provide any API to an web-extension to move keyboard focus to the address bar
2. There's no API for common HTTP pages, but Vimium C does provide an API for other web extensions to call its commands. So if you can write JavaScript code and know something about extensions, then you can:
  * call `chrome.runtime.sendMessage("(ID of Vimium C)", {...})`
  * the message format is in https://github.com/gdh1995/vimium-c/blob/874c40249ead165dfecc5274019f643dc838f7ef/types/messages.d.ts#L568-L574
  * it will be handled by https://github.com/gdh1995/vimium-c/blob/874c40249ead165dfecc5274019f643dc838f7ef/background/commands.ts#L288
  * the ID of a source extension must be in the `Allow list of other extension IDs` on Vimium C Options page
3. Sorry but I haven't met such a tool
4. Vimium C only consumes keys whose main key is F1~F12, when it's in a common insert mode (an text box is focused)
  * for example, both `<f8>` and `<f6><s-f8>` are usable when in insert mode
  * if you add

```
mapkey <c-m> <f13>
map <f13> Vomnibar.activateTabSelection icase
```

to the `Custom key mappings` option, then you may use Ctrl+M to activate tab-mode Vomnibar in both normal mode and insert mode

**Comment by gdh1995** [comment]
As for myself, I've configured `Go one tab left` and `Go one tab right` on `chrome://extensions/shortcuts`, and then to focus a tab, I just need to press a shortcut key and hold on, until the tab gets active.

**Comment by afilp** [comment]
You are great! 
All this info helps a lot, thanks!

I did this and it is a fantastic solution, it always opens!

**Comment by gdh1995** [comment]
There's a command of "visitPreviousTab", so what you want means to call the `previousTab` (or `nextTab`) command and then `visitPreviousTab` command. I think it's hard to find a strategy to merge them into a new command - when do you want to go left, and when to go back?

> `Go one tab left` and `Go one tab right` on `chrome://extensions/shortcuts`

I' using Alt+C and Alt+V for the two shortcuts, so they can work anywhere.

**Comment by ocsiker** [comment]
When I press T to search through my tabs, the result just displays tabs in 'normal' and ignores tabs in incognito. Whereas it works perfectly in incognito.
In normal:
![image](https://user-images.githubusercontent.com/57534329/136114163-076a9204-51f7-4b68-b0e8-1f2c39bccccf.png)
In incognito:
![image](https://user-images.githubusercontent.com/57534329/136114395-a43c67bb-5903-484f-a329-d7d0c7f72156.png)

**Comment by sisrfeng** [comment]
what else can "vimium c mode' can do?

:t can not work as you said.

Thx!

**Comment by gdh1995** [comment]
@sisrfeng `:t` should be used as this snapshot shows - you may need to type `v`, a space character, `:` and then `t` :

![Snipaste_2022-02-07_10-49-52](https://user-images.githubusercontent.com/5547703/152716967-3a407c10-4f9c-43f8-a2fd-5d1c915a01ba.png)

The `v *****` uses the same search engine of Vomnibar, so it can also search in history, bookmarks, opened tabs and use custom search engines.

@ocsiker Now Vimium C supports a boolean parameter named `incognitoTabs` in `Vomnibar.activate***`, so:
```
map o Vomnibar.activate incognitoTabs
```

will make Vomnibar always search in all types of tabs.
