### ISSUE TITLE
Use `String.toLocaleUpperCase()` on hint chars

### ISSUE THREAD

**Issue by roket1428** [gdh1995/vimium-c#167]
I'm not sure that vimium-c uses `String.toUpperCase()` at all but would be nice to have local upper case letters. Like in Turkish, capital `i` is `İ` instead of `I` unlike in English.

**Comment by gdh1995** [comment]
Sorry I know little about languages except English and Chinese. Do you mean "when you press <kbd>Shift> + <kbd>i</kbd>, then will be `i` (unicode code point: 105)" ?

Up to now, Vimium C does convert all characters for LinkHints into their lower-case versions when storing settings, and convert to upper-case versions when LinkHints uses them.

So, in your case, is it not enough?

**Comment by roket1428** [comment]
> Sorry I know little about languages except English and Chinese. Do you mean "when you press Shift + i, then will be `i` (unicode code point: 105)" ?

It is `İ`, not `i` which means its code point is `130`.

> Up to now, Vimium C does convert all characters for LinkHints into their lower-case versions when storing settings, and convert to upper-case versions when LinkHints uses them.
>
> So, in your case, is it not enough?

Seems like it is not, just because of capitalizing `i`, to be honest. :D


Although, the idea behind using `toLocaleUpperCase` method instead of `toUpperCase` method is, to allow *all* languages to behave correctly in terms of the language's standards.

You can see more details about the Turkish alphabet in here: https://en.wikipedia.org/wiki/Turkish_alphabet#Letters

BTW, I also realized that non-English characters doesn't work for example `ü`, `ş`, `ç` in hint characters. So, you might want to take a look at that to or I could create another issue. :D

**Comment by gdh1995** [comment]
what's your linkhints characters and system keyboard layout (IME)?



---Original---

**Comment by gdh1995** [comment]
Um, try this version? [vimium_c-1.81.5-chrome-b451930.zip](https://github.com/gdh1995/vimium-c/files/4567913/vimium_c-1.81.5-chrome-b451930.zip), [vimium_c-1.81.5-firefox-b451930.zip](https://github.com/gdh1995/vimium-c/files/4567915/vimium_c-1.81.5-firefox-b451930.zip)

**Install**:
* unzip a zip file into an empty folder
* if on Chrome, open `chrome://extensions/` and enable the "developer mode"
* if on Firefox, open `about:debugging#/runtime/this-firefox` manually
* click the "load extension" button and select the extension folder or `manifest.json`

**Comment by roket1428** [comment]
> what's your linkhints characters and system keyboard layout (IME)?
I have no idea what do you mean.

> Um, try this version? [vimium_c-1.81.5-chrome-b451930.zip](https://github.com/gdh1995/vimium-c/files/4567913/vimium_c-1.81.5-chrome-b451930.zip), [vimium_c-1.81.5-firefox-b451930.zip](https://github.com/gdh1995/vimium-c/files/4567915/vimium_c-1.81.5-firefox-b451930.zip)
> 
> **Install**:
> 
>     * unzip a zip file into an empty folder
> 
>     * if on Chrome, open `chrome://extensions/` and enable the "developer mode"
> 
>     * if on Firefox, open `about:debugging#/runtime/this-firefox` manually
> 
>     * click the "load extension" button and select the extension folder or `manifest.json`

Still the non-English characters doesn't work.

BTW, I'm using Gentoo GNU/Linux with Firefox Nightly on X11.

**Comment by gdh1995** [comment]
Vimium C has released a new version (v1.83.0). During my tests on Win10, it supports `i` (`ı`) and `'` (`i`) letters in a keyboard layout of Turkish (the "TUR" one).

If it still fails on your system, I expect more detailed descriptions.

**Comment by roket1428** [comment]
> Vimium C has released a new version (v1.83.0). During my tests on Win10, it supports `i` (`ı`) and `'` (`i`) letters in a keyboard layout of Turkish (the "TUR" one).
> 
> If it still fails on your system, I expect more detailed descriptions.

The main problem is not whether `i` or `ı` works, the main problem is, that you can't use neither of `ü`, `ö`, `ş`, `ç`, non-English characters in general.

BTW, this time, it behaves like `i` and `ı` are the same characters. :D

**Comment by gdh1995** [comment]
According to tests on Chrome, you need to configure your browser's UI language to Turkish, to let Vimium C know you want a Turkish version of upper-case letters. So on a Chrome with English UI, both the letters will be converted to `I`.

What mode are you in, when you say `can't use neither of ü, ö, ş, ç, non-English characters in general`? LinkHints, Vomnibar, VisualMode or the default normal mode?

**Comment by roket1428** [comment]
> According to tests on Chrome, you need to configure your browser's UI language to Turkish, to let Vimium C know you want a Turkish version of upper-case letters. So on a Chrome with English UI, both the letters will be converted to `I`.
I'm using Firefox with en-US UI. And I think most people do that as well even though their native langue is not English.
 
> What mode are you in, when you say `can't use neither of ü, ö, ş, ç, non-English characters in general`? LinkHints, Vomnibar, VisualMode or the default normal mode?
Sorry for not explicitly mentioning it. It was LinkHints

**Comment by gdh1995** [comment]
I just modified the logic and now Vimium C will auto de-duplicate characters like `ı` and `i`, and you can test it by modifying LinkHints characters, saving options and refreshing the options page.

On my laptop, the 4 example non-English characters works in LinkHints mode, so do you have enabled `Ignore keyboard layout`? If it's enabled, then all keyboard events will be treated as in a English layout, so LinkHints will only get `]`, `,`, `;` and `.`.

Test version: [vimium_c-1.83.1-firefox-11e67a4.zip](https://github.com/gdh1995/vimium-c/files/4605109/vimium_c-1.83.1-firefox-11e67a4.zip)
