### ISSUE TITLE
Number for map

### ISSUE THREAD

**Issue by amufaamo** [gdh1995/vimium-c#168]
Can I use 1,2,3 for command?

Like "map 1 createTab"

I think I got error when I use number

**Comment by gdh1995** [comment]
numbers are used as count prefix. For example, `3j` means to scroll down by 3 times of steps (100px -&gt; 300px).
If you do want to use it, then you'll need mapkey in custom key mappings:


mapkey 1 <fake1&gt;
mapkey 2 <fake2&gt;
map <fake1&gt; scrollDown
# or other commands


The above lets Vimium C treat '1' as a fake key 'fake1', so it's not a count prefix any more.



---Original---

**Comment by amufaamo** [comment]
So how can I write when I want to create tab using 1?

**Comment by gdh1995** [comment]
mapkey 1 <fake1&gt;
map <fake1&gt; createTab



---Original---

**Comment by amufaamo** [comment]
Does it mean I should write both?
For my vimium C, it doesn't look working.

**Comment by gdh1995** [comment]
yes, write&nbsp; both.


give a screen snapshot of your key mappings?



---Original---

**Comment by gdh1995** [comment]
Please write
```
mapkey 1 <fake1>
map <fake1> createTab
```

The old `&gt;` is `>`, escaped by GitHub.
