### ISSUE TITLE
map <esc> in `o` `O` and `T`

### ISSUE THREAD

**Issue by cheecheeo** [gdh1995/vimium-c#170]
I have the following settings:
```
mapKey <c-c> <esc>
mapKey <c-c> <c-]>
unmap <c-e>
```

when i want to navigate to another tab or use the vomnibar i can't use <c-c> to close out the search bars. is there a way i can map <c-c> to close these out?

Version 1.83.0

**Comment by gdh1995** [comment]
the syntax is: mapkey source target
so the second one overrides the first one; and c-] is not an escape key, but c-[ is.


so just remove the second one, or replace the second with ... c-[&nbsp;



---Original---

**Comment by cheecheeo** [comment]
hmm. i updated my config to this:
```
mapkey <c-c> <c-[>
```

and when i type `o` to bring up the omnibar then <c-c> to close it, it doesn't close. i have to press <esc>.

same with `O` and `T`.

**Comment by cheecheeo** [comment]
actually, my bad. <c-c> does work. but it works assuming i'm using a qwerty layout. let me workaround that.

thank you!

**Comment by gdh1995** [comment]
there' an advanced option named "ignore keyboard layout" and you may take a try



---Original---

**Comment by gdh1995** [comment]
Or change the c-c to c-*** (the letter what C means in your keyboard layout)



---Original---

**Comment by cheecheeo** [comment]
yup. for dvorak keyboard i did
```
mapkey <c-i> <c-[>
```

in case anyone else sees this issue...

**Comment by meteorsh** [comment]
Is it possible to `mapKey jk <c-[>`

**Comment by gdh1995** [comment]
@meteorsh No, the source key of `mapKey` must be a single "composed key".
