### ISSUE TITLE
How should I do if there's multi div which contains scrollbar

### ISSUE THREAD

**Issue by mttbx** [gdh1995/vimium-c#171]
How can I scroll to the right div?
For example in the page: https://element.eleme.cn/#/zh-CN/component/icon

**Comment by gdh1995** [comment]
Use `LinkHints.activateModeToHover` to "select" a link/button which is included by the area you want, and then press `j` / `k` to scroll

**Comment by mttbx** [comment]
Thanks, that'll do it

**Comment by maciejmotyka** [comment]
Very useful hack!
I think it deserves to be featured in the Wiki.
