### ISSUE TITLE
map快捷键语法疑问

### ISSUE THREAD

**Issue by xiaoyaoyuxin** [gdh1995/vimium-c#172]
填写完自定义键盘映射，保存后，还需要做其他什么操作，才能生效吗？searchAs也没能成功实现。

研究了半天，也没能实现搜索选定的文字，文档也查看了，没能找到方案，只能冒昧地发个issue问一下了。

感谢作者的开发。

**Comment by gdh1995** [comment]
你的键盘映射怎么写的？
在网页上按了什么键、右下角有没有显示vimium c的灰色提示条？



---原始邮件---
发件人: "xiaoyaoyuxin"<notifications@github.com&gt;
发送时间: 2020年5月8日(周五) 晚上6:44
收件人: "gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [gdh1995/vimium-c] map快捷键到openauto，始终无效 (#172)




 
填写完自定义键盘映射，保存后，还需要做其他什么操作，才能生效吗？
 
研究了半天，也没能实现搜索选定的文字，文档也查看了，没能找到方案，只能冒昧地发个issue问一下了。
 
感谢作者的开发。

**Comment by xiaoyaoyuxin** [comment]
抱歉，第一次提供的信息不完整。

我如下写：map <qq> autoOpen

也试过<c><s><aa> <cc> <ss><s-cc>等写法，都无效。

新建一个页面，选定了某些文字，按键完全没有反应。

**Comment by xiaoyaoyuxin** [comment]
我还写了下面两条
`map <h> goBack
map <l> goForward`
想用小写的hl来代替HL实现前进和后退，也没有效果。

但以上三种功能，从“显示所有命令”页面看，都已经成功映射了。

难道是浏览器的问题?我用的vivaldi，基于chormium的第三方浏览器。

但默认的键位功能都没有问题，可以正常用。

**Comment by gdh1995** [comment]
写法问题，单个字符做一个键的话，不要带尖括号，简而言之：
```
map qq autoOpen
map h goBack
map <a-l> goForward
map <f8> autoOpen
```

也就是只有1）需要按下alt、ctrl、meta、shift；2）或者主键本身是由多个字符组成；这些时候需要用尖括号包起来。

**Comment by gdh1995** [comment]
`<q>` 会被理解为依次按下<kbd>&lt;</kbd>，<kbd>q</kbd>，<kbd>&gt;</kbd>这三个键; `<qq>`则是<kbd>qq</kbd>，又因为实际上没有这个键，所以永远也没法触发它。

**Comment by xiaoyaoyuxin** [comment]
明白了，多谢 r

> `<q>` 会被理解为依次按下<，q，>这三个键; `<qq>`则是qq，又因为实际上没有这个键，所以永远也没法触发它。

可以了！原来是写法问题，我就觉得应该是个我忽略了个很小的问题。

看了一下设置里的示例，确实没有单字符的示例，不知道能否加一个例子呢?

再一次表示感谢！
