### ISSUE TITLE
Custom CSS doesn't work for the HUD with dark mode on

### ISSUE THREAD

**Issue by maxigaz** [gdh1995/vimium-c#173]
When `Auto switch between light and dark mode` is enabled in the Options (and dark theme is used systemwise), Custom CSS rules don’t affect the HUD, only the Vomnibar and the Find Bar. (I haven’t tested styling hints.) If I disable this option, styling the HUD works as expected.

Using Firefox 75.0 for Linux with VImium C v1.83.1.

(I’ve mentioned this in #78, I just thought I would be better to open a separate issue for this.)

**Comment by gdh1995** [comment]
I think it's just because the selectors in your custom CSS code are not "privileged" enough.

The code will be appended to default CSS code, and then your browser will decide what is prior to another.

**Comment by gdh1995** [comment]
For example:
```.HUD:after { background: red; }```

should be ```.HUD.D:after { background: red; }```, so that it will (only) apply in dark mode

**Comment by maxigaz** [comment]
> should be `.HUD.D:after { background: red; }`, so that it will (only) apply in dark mode

You’re right! `.D` was the missing part. Thanks a lot for your help!

**Comment by maxigaz** [comment]
I've just created a wiki page that summarises what I learned in this and the other thread.
