### ISSUE TITLE
建议：当扩展不可用时，图标灰化

### ISSUE THREAD

**Issue by Zd036** [gdh1995/vimium-c#174]
是否考虑像vimium一样，当扩展不可用时（比如新标签页），将图标灰化，便于用户确认扩展状态。

**Comment by gdh1995** [comment]
这些页面上Vimium C始终不可用，而一般来说很容易区分浏览器内置的页面和普通页面。所以灰化显示的意义不大，但是会稍微增加内存消耗和CPU负担。

**Comment by gdh1995** [comment]
开启高级选项的“在浏览器右上角显示动态图标”后，如果Vimium C在某页面上运行了并根据网址过滤规则或者某个命令而处于暂停状态，是会显示灰色图标的。

**Comment by gdh1995** [comment]
开启高级选项的“在浏览器右上角显示动态图标”后，如果Vimium C在某页面上运行了并根据网址过滤规则或者某个命令而处于暂停状态，是会显示灰色图标的。

**Comment by Zd036** [comment]
了解了，感谢回复
