### ISSUE TITLE
Option to disable domain suggestion as first result in Vomnibar

### ISSUE THREAD

**Issue by maxigaz** [gdh1995/vimium-c#176]
For example, even if you have nothing else from GitHub but `https://github.com/gdh1995/vimium-c` in your history/bookmarks, when you press `o` and start typing `github`, the first item is always `github.com` in the Vomnibar. Can you give me some pointers on how to do disable this behaviour?

If there’s no way to disable it, could you add an option for it?

**Comment by gdh1995** [comment]
You may use `Vomnibar.activateHistory`, `Vomnibar.activateBookmarks` and `Vomnibar.activateTabSelection` to limit query ranges.

Or `:h xxxx` will make Vomnibar only search in history items, whatever `Vomnibar.*` command you trigger.

**Comment by maxigaz** [comment]
> You may use `Vomnibar.activateHistory`, `Vomnibar.activateBookmarks` and `Vomnibar.activateTabSelection` to limit query ranges.

I know about these. I prefer having them combined in a single list (`Vomnibar.activate`), but domain completion is something I’ve never used, so I have to press Tab once more than in Vimium (which doesn’t have this feature) a lot of times.

> Or `:h xxxx` will make Vomnibar only search in history items, no matter what `Vomnibar.*` command you trigger.

OK, that’s good to know. Although I’d still be interested in whether domain completion could be made optional.

**Comment by gdh1995** [comment]
well, let me add a new option.



---Original---

**Comment by gdh1995** [comment]
BTW, when I use Vimium, it also search in domain list, like this:

![image](https://user-images.githubusercontent.com/5547703/82521940-8b05da80-9b5a-11ea-8297-f76ee9b274ae.png)

**Comment by maxigaz** [comment]
> BTW, when I use Vimium, it also search in domain list, like this:
> 
> ![image](https://user-images.githubusercontent.com/5547703/82521940-8b05da80-9b5a-11ea-8297-f76ee9b274ae.png)

I was wrong about that one. Sorry!

> well, let me add a new option.

Thank you very much!

**Comment by gdh1995** [comment]
Hello, you may try this: [vimium_c-1.83.2-chrome-9041514.zip](https://github.com/gdh1995/vimium-c/files/4671136/vimium_c-1.83.2-chrome-9041514.zip), [vimium_c-1.83.2-firefox-9041514.zip](https://github.com/gdh1995/vimium-c/files/4671137/vimium_c-1.83.2-firefox-9041514.zip).

You may add this to key mappings: `map o Vomnibar.activate engines=15`
(bookmark = 1, history = 2, tab = 4, search = 8, domain = 16)

**Install**:
* unzip a zip file into an empty folder
* if on Chrome, open `chrome://extensions/` and enable the "developer mode"
* if on Firefox, open `about:debugging#/runtime/this-firefox` manually
* click the "load extension" button and select the extension folder or `manifest.json`

**Comment by maxigaz** [comment]
Hi! I’ve just tried it and it works very well with Firefox. Thank you!
