### ISSUE TITLE
“RunningCheese”定制版火狐添加vimium-c 实现全局可用  的可行性？

### ISSUE THREAD

**Issue by i-workstation** [gdh1995/vimium-c#178]
- RunningCheese 火狐下载地址

  https://www.runningcheese.com/firefox

思路：

1. 

   下载解压后，在路径`\Profiles\V10\chrome\SubScript\`下有一个脚本文件`MouseGestures.uc.js`，通过这个脚本可以实现浏览器全局的鼠标手势操作

2. 

   能否参考这一点实现vimium-c的全局操作

**Comment by gdh1995** [comment]
也许可以改吧。Vimium C 前端脚本可以做到只依赖 browser.runtime.connect 这一个接口，原理上应该能载入一些 firefox 内置的 js 文件来做到和后端交流。

不过排错太费事了，而且实现了也没法发到扩展商店里，我不太想折腾这个。

只是要全局用的话：
* 需要使用 Vimium C 的 UI 界面的话，我一般新开一个新标签页然后用
* 其它不带界面的命令你可以设置浏览器的全局快捷键来触发。位置不够的话还能用 Shortcut Forwarding Tool 扩容。

**Comment by gdh1995** [comment]
另外看了一下，它的内置新标签页是用扩展实现的，如果只是想在这个页面上用Vimium C，可以修改这个扩展本身。

参考 https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions#notes-for-firefox ，添加这么一段 js 就够了，我印象中 manifest 都不用改。
``` javascript
browser.runtime.sendMessage('vimium-c@gdh1995.cn', { handler: 99 }).then(res => {
  const { host } = res;
  console.log(host); // for example, log "d1ba02e9-ec90-46dc-8623-69e15961cc86"
  // localStorage.vimiumHost = host; // may cache it for further usages
  const injector = `moz-extension://${host}/lib/injector.js`;
  const script = document.createElement('script');
  script.src = injector;
  document.head.appendChild(script);
});
```
