### ISSUE TITLE
Mode indicators dark theme switch

### ISSUE THREAD

**Issue by maciejmotyka** [gdh1995/vimium-c#179]
Currently, it's possible to switch Vomnibar to a dark theme using `toggleVomnibarStyle` which is great feature, however, the mode indicators (Insert, Visual, Caret, Line) stay white and hurt my eyes in the evenings.
Could you make them obey the `toggleVomnibarStyle` as well?

**Comment by gdh1995** [comment]
There's a global dark mode. If you enable the advanced option of `Auto switch between light and dark mode`, then Vimium C will turn into dark mode in a while when your system goes dark mode.

Or you can write rules in `Custom CSS for Vimium C UI` to make UI dark directly. Here's a wiki page: https://github.com/gdh1995/vimium-c/wiki/How-to-style-the-UI-of-Vimium-C-using-Custom-CSS

**Comment by maciejmotyka** [comment]
Unfortunately, I don't have a proper OS dark mode in MATE desktop as it's based on Gnome 2, not Gnome 3. I can select a dark-colored theme, but it doesn't trigger any response Vimium C. I don't know if all other popular distros have implemented OS level dark mode. That's why I think triggering the dark/bright mode manually could be a useful addition.

I tried the CSS way and come up with 2 custom rules which I cannot make to work together. I can change the background of the find dialog:
```
/* #find */
.r{background:#999}
```
or I can change background of the mode indicators
```
/* #ui */
.HUD:after{background:#999}
```
but not both at the same time. When I paste both of them into `Custom CSS for Vimium C UI` box in the options whichever comes first is active and the other is not.
```
/* #find */
.r{background:#999}

/* #ui */
.HUD:after{background:#999}
```

**Comment by gdh1995** [comment]
Um, v1.83.2 imports a regression when parsing custom CSS. I'll fix it in a few weeks.

**Comment by gdh1995** [comment]
Hello, you may try this: [vimium_c-1.83.2-chrome-9041514.zip](https://github.com/gdh1995/vimium-c/files/4671136/vimium_c-1.83.2-chrome-9041514.zip), [vimium_c-1.83.2-firefox-9041514.zip](https://github.com/gdh1995/vimium-c/files/4671137/vimium_c-1.83.2-firefox-9041514.zip).

Fix a bug when parsing custom CSS.

**Install**:
* unzip a zip file into an empty folder
* if on Chrome, open `chrome://extensions/` and enable the "developer mode"
* if on Firefox, open `about:debugging#/runtime/this-firefox` manually
* click the "load extension" button and select the extension folder or `manifest.json`

**Comment by maciejmotyka** [comment]
Checked in Vivaldi - the problematic CSS works well now. Thanks!

**Comment by mangkoran** [comment]
> There's a global dark mode. If you enable the advanced option of `Auto switch between light and dark mode`, then Vimium C will turn into dark mode in a while when your system goes dark mode.
> 
> Or you can write rules in `Custom CSS for Vimium C UI` to make UI dark directly. Here's a wiki page: https://github.com/gdh1995/vimium-c/wiki/How-to-style-the-UI-of-Vimium-C-using-Custom-CSS

Sorry for bumping old issue. How can I set vimium to dark mode? There is a switch in vomnibar to switch between light and dark mode, but the setting is reset after relaunching firefox.
