### ISSUE TITLE
"[[" does not go to previous link

### ISSUE THREAD

**Issue by KevinJohnMulligan** [gdh1995/vimium-c#182]
The function associated with keybinding for going "back" in history is not working.

As an example of this behaviour, I navigated from https://github.com/gdh1995/vimium-c to the issues page and was unable to travel back up the history list using "[[".  However this behaviour seems to happen on most (or all sites, it worked at one point but hasn't worked recently).

Vimium-C outputs: **"No links to go to prev"** - which means that the _previous-links_ function must have been called.

I have attached a picture of the behaviour and my current configuration JSON file.

![vimium-c](https://user-images.githubusercontent.com/52432231/82795226-481f6c00-9ea6-11ea-9367-71adc01d6478.png)

`{
	"name": "Vimium C",
	"@time": "5/25/2020, 4:44:36 PM",
	"time": 1590396276818,
	"environment": {
		"extension": "1.83.2",
		"platform": "win",
		"chrome": 81
	},
	"extAllowList": [
		"# modified versions of X New Tab and PDF Viewer,",
		"# NewTab Adapter, and Shortcuts Forwarding Tool, ",
		"# The great suspender",
		"hdnehngglnbnehkfcidabjckinphnief",
		"nacjakoppgmdcpemlfnfegmlhipddanj",
		"cglpcedifkgalfdklahhcchnjepcckfn",
		"clnalilglegcjmlgenoppklmfppddien",
		"klbibkeccnjlkjkiokjodocebajanakg",
		""
	],
	"grabBackFocus": true,
	"showAdvancedOptions": true
}`

**Comment by gdh1995** [comment]
`goNext` and `goPrevious` can only find links of next/prev in the page, so they do work on `https://github.com/gdh1995/vimium-c/issues?page=4&q=is%3Aissue+is%3Aclosed`.

**Comment by KevinJohnMulligan** [comment]
Hi Mr. Gong, 

This extension is really amazing! 

Thank you for your fast response, I did some more searching and realised that the feature I was actually wanting to use is "H" to go back in history, and "L" to go forward in history. Therefore, I'm closing this issue.
