### ISSUE TITLE
unlimited loop

### ISSUE THREAD

**Issue by Monirzadeh** [gdh1995/vimium-c#183]
I have a command like this:
```
map ss do-somthing
```
I know I can 20ss to repeat my command for  20 time
how can I make that a loop or set that repeat as part of code
for example press `sms` do my command for 1000 time?

**Comment by gdh1995** [comment]
map key command count=1000


The min / max of count are -9999 and 9999.



---Original---

**Comment by Monirzadeh** [comment]
thanks
