### ISSUE TITLE
 vimium-c第一次安装在新版edge上，无法显示指令

### ISSUE THREAD

**Issue by lyjhyjyes** [gdh1995/vimium-c#184]
今天第一次安装在edge上，刚开始指令页面的显示“向左移动标签页 (moveTabLeft)”，关机后，第二次打开vimium c编辑，发现变成“向左移动标签页 ”，少了后面的指令，导致我不知道如何编辑新的快捷键

**Comment by gdh1995** [comment]
在Vimium C设置页面上，帮助对话框里才会显示命令名字
