### ISSUE TITLE
C-n to tab through Vomnibar options?

### ISSUE THREAD

**Issue by GLodi** [gdh1995/vimium-c#185]
Is there any way to use a custom mapping to cycle through Vomnibar links/options instead of using tab? I'm used to using C-n in emacs when I need to select one of multiple options.

**Comment by gdh1995** [comment]
use mapkey in custom key mappings, like:

```
mapkey <c-n:o> <tab>
mapkey <c-p:o> <s-tab>
```

**Comment by GLodi** [comment]
Thanks! That does work, however it seems that Firefox doesn't allow me to rebind single shortcuts (Ctrl+N is New Window). I'll probably use another keybinding. Thanks anyway!
