### ISSUE TITLE
Error when compiling from source

### ISSUE THREAD

**Issue by sooqua** [gdh1995/vimium-c#186]
Cloning & compilation looks successful:
<details>
14:55:08 in …/code/chromium/extensions via ⬢ v14.3.0
 ❯ git clone https://github.com/gdh1995/vimium-c.git
Cloning into 'vimium-c'...
remote: Enumerating objects: 737, done.
remote: Counting objects: 100% (737/737), done.
remote: Compressing objects: 100% (462/462), done.
remote: Total 49537 (delta 527), reused 447 (delta 253), pack-reused 48800
Receiving objects: 100% (49537/49537), 15.43 MiB | 6.83 MiB/s, done.
Resolving deltas: 100% (38696/38696), done.

14:55:15 in …/code/chromium/extensions via ⬢ v14.3.0 took 4s
 ❯ ./vimium-c

14:55:24 in …/vimium-c on  master is 📦 v1.83.3 via ⬢ v14.3.0
 ❯ npm install typescript
npm notice created a lockfile as package-lock.json. You should commit this file.
+ typescript@3.9.5
added 1 package from 1 contributor and audited 1 package in 1.137s
found 0 vulnerabilities

14:55:44 in …/vimium-c on  master [!] is 📦 v1.83.3 via ⬢ v14.3.0
 ❯ npm install pngjs
+ pngjs@3.4.0
added 1 package from 12 contributors and audited 2 packages in 1.08s
found 0 vulnerabilities

14:59:12 in …/vimium-c on  master [!] is 📦 v1.83.3 via ⬢ v14.3.0
 ❯ node scripts/tsc
Patch TypeScript/lib/tsc.js: succeed
Can not load terser, so skip uglifying
[front]      WRITE: front/vomnibar.js
[front]      WRITE: lib/injector.js
[front]      WRITE: scripts/.ts.front.build
(node:6917) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'icons/enabled.bin'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6917) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6917) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[pages]       SKIP: background/utils.js
[pages]       SKIP: background/settings.js
Can not load terser, so skip uglifying
[pages]      WRITE: pages/loader.js
[pages]      WRITE: pages/options.js
[pages]       SKIP: background/exclusions.js
[pages]      WRITE: pages/options_base.js
[pages]      WRITE: pages/options_checker.js
[pages]      WRITE: pages/options_ext.js
[pages]      WRITE: pages/show.js
[pages]      WRITE: scripts/.ts.pages.build
Can not load terser, so skip uglifying
[background] WRITE: background/commands.js
[background] WRITE: background/completion.js
[background] TOUCH: background/exclusions.js
[background] WRITE: background/help_dialog.js
[background] WRITE: background/main.js
[background] WRITE: background/others.js
[background] TOUCH: background/settings.js
[background] WRITE: background/tools.js
[background] TOUCH: background/utils.js
[background] WRITE: scripts/.ts.background.build
Can not load terser, so skip uglifying
[content]    WRITE: lib/keyboard_utils.js
[content]    WRITE: content/frontend.js
[content]    WRITE: content/request_handlers.js
[content]    WRITE: content/extend_click.js
[content]    WRITE: content/commands.js
[content]    WRITE: content/key_handler.js
[content]    WRITE: content/port.js
[content]    WRITE: content/dom_ui.js
[content]    WRITE: content/scroller.js
[content]    WRITE: content/link_hints.js
[content]    WRITE: content/pagination.js
[content]    WRITE: content/link_actions.js
[content]    WRITE: content/hint_filters.js
[content]    WRITE: content/local_links.js
[content]    WRITE: content/omni.js
[content]    WRITE: content/hud.js
[content]    WRITE: content/insert.js
[content]    WRITE: content/visual.js
[content]    WRITE: content/mode_find.js
[content]    WRITE: content/marks.js
[content]    WRITE: lib/utils.js
[content]    WRITE: lib/dom_utils.js
[content]    WRITE: content/injected_end.js
[content]    WRITE: lib/env.js
[content]    WRITE: lib/polyfill.js
[content]    WRITE: scripts/.ts.content.build
</details>

Then I get this error when loading unpacked extension in chrome:

![New Project](https://user-images.githubusercontent.com/4979209/83874590-6440ca00-a73e-11ea-94fd-f1854188a7e9.png)

And no mapped shortcuts are working...

**Comment by gdh1995** [comment]
Please try this:
Npm install terser
delete scripts/.*.build
run ./scripts/tsc again


I'm not sure what's wrong because I haven't done this from a fresh clone for years. I'll look at it tomorrow



---Original---

**Comment by sooqua** [comment]
> Please try this:
> Npm install terser
> delete scripts/.*.build
> run ./scripts/tsc again
This fixed the error. Could you edit the build instructions as well?

**Comment by gdh1995** [comment]
OK. Commit 3009674 has fixed it.
