### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by matheusfillipe** [gdh1995/vimium-c#187]
Would it be possible to add the move tab functionality? Like move the current tab to the left or right.

**Comment by gdh1995** [comment]
There're `moveTabLeft` and `moveTabRight`.

You may see them on Vimium C Options page:
* click "Show all commands" and show the help dialog
* scroll to bottom and click "Show Advanced Options"
* then the dialog will list more commmands

**Comment by matheusfillipe** [comment]
Oh thanks! I might be just blind :P

That was quite fast support! Thanks a lot!
