### ISSUE TITLE
Is there a way to map custom key map on specific website?

### ISSUE THREAD

**Issue by Jinkiesz** [gdh1995/vimium-c#188]
The title says it all. For example since in youtube key J, K and L already used i would like to map them to something different

**Comment by gdh1995** [comment]
No, but you can disable specific keys on some websites: add exclusion rules.

**Comment by gdh1995** [comment]
Maybe I'll add it in an indirect way in a few months - recently I got a new idea about how to implement and apply host-specific options.

**Comment by gdh1995** [comment]
Hello, v1.88.0 has been released, and I added a `runKey` to do this ^_^.

Please read https://github.com/gdh1995/vimium-c/wiki/Map-a-key-to-different-commands-on-different-websites to get its usages.
