### ISSUE TITLE
change visual mode shortcuts ?

### ISSUE THREAD

**Issue by pseudomyne** [gdh1995/vimium-c#189]
hi, 
thank you for vimium ;)
Is there a way to change visual mode shortcuts ? (emacs "heretic" here...)

**Comment by gdh1995** [comment]
Something like `mapkey <k:v> j` and `mapkey <j:v> k` may help.

Please see some usages `mapKey` on https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout .

**Comment by pseudomyne** [comment]
Thanks. Here are working remappings : 
`mapkey <b:v> e `
`mapkey <e:v> b `

The following won’t work here though :
`mapkey <b:v> k `
`mapkey <e:v> l `

Any idea why ?
(Firefox and french keyboard layout here)

**Comment by gdh1995** [comment]
What was VisualMode doing when you had added the fist one:
```
mapkey <b:v> e
mapkey <e:v> b
```

?

Maybe the first part also failed, and when you pressed `b` / `e` VisualMode got different keys and triggered some other commands.

The default actions of `b` and `e` are to jump forward/backward by word.

**Comment by pseudomyne** [comment]
Nope. I confirm that `mapkey <b:v> e` and `mapkey <e:v> b `work (jump by word). I just tried to invert them because as 'b' stands more at the right, I find more intuitive to make this key jump forward.

**Comment by gdh1995** [comment]
So, `mapkey <b:v> e` can make selection jump right by a word?

It's strange because in my tests `mapkey <b:v> k` worked (Chrome 83, Win19)

**Comment by pseudomyne** [comment]
mapkey <b:v> e jumps by a word to the **right**.
Here is Arch /Firefox.

**Comment by gdh1995** [comment]
Then what `b` does if `mapkey <b:v> k` ? `k` is to move caret to an upper line

**Comment by pseudomyne** [comment]
Oh ! I miserably inverted the way to do it. What I actually wanted was :
`mapkey <k:v> b`
`mapkey <l:v> e`
and this works fine. Sorry for your time here ):
