### ISSUE TITLE
"Don't let pages steal the focus in loading"   not working in opera

### ISSUE THREAD

**Issue by the-one-step** [gdh1995/vimium-c#190]
- system info
Ubuntu 18.04   
Opera browser,  the latest version

**Comment by the-one-step** [comment]
![Opera Snapshot_2020-06-22_111014_extensions](https://user-images.githubusercontent.com/52375886/85245050-02d86500-b479-11ea-8464-000f6a180a09.png)

**Comment by the-one-step** [comment]
创建新标签页  和 启动opera 的时候, 这个功能没有 take effect

**Comment by gdh1995** [comment]
“在新网页上阻止文本框自动获取键盘焦点”不是这个意思，它是阻止JavaScript去focus一个文本框，而你说的是应该是浏览器地址栏的问题。

希望 Ctrl+T 后能直接操作网页？https://chrome.google.com/webstore/detail/newtab-adapter/cglpcedifkgalfdklahhcchnjepcckfn

**Comment by the-one-step** [comment]
现实略微骨感
