### ISSUE TITLE
Firefox PDF viewer: j and k don't smooth scroll

### ISSUE THREAD

**Issue by torresjrjr** [gdh1995/vimium-c#194]
In the PDF viewer, the keys `j` and `k` jump to the beginning of the next or previous page respectively. 
The expected behavior would be a horizontal smooth scroll, like in the Chrome version. 
The keys `n` and `p` already jump to the next or previous page.
Additionally, the keys `d` and `u` don't anything. They don't scroll half a page.

I'd like the internal key bindings or code to be adjusted to `j` and `k` for smooth scrolling. 
Is there already a way in the settings to change this?

Is this feasible? Thank you.

Browser: Firefox
Version: 1.83.4
Last Updated: 15 June 2020

**Comment by gdh1995** [comment]
Sorry but I have only published "PDF Viewer for Vimium C" on Chrome Web Store, so the page you saw was not mine but the built-in module of Firefox, and then it doesn't allow Vimium C to run on its pages.

BTW, I once mistakenly named my one "PDF Viewer" in about 3 years ago, but I've renamed it to "PDF Viewer for Vimium C" for about 2 years.

**Comment by gdh1995** [comment]
Up to now I have not published a Firefox version of PDF Viewer for Vimium C yet. I'm still hesitate to do so because it can be heavy to maintain a new extension.

**Comment by torresjrjr** [comment]
I see. Is there anyway I could help or contribute? Is there another possible solution?

**Comment by gdh1995** [comment]
The official module is https://github.com/mozilla/pdf.js, a very standard project, so you may file new issues to them to change behavior of `j` / `k`.

As for working with Vimium C, it needs to publish a new extension, which is just like PDF Viewer for Vimium C, to Firefox Add-ons.

**Comment by torresjrjr** [comment]
OK. Thank you for your response. I'll see about it.
