### ISSUE TITLE
[Feature request] Command "Vomnibar.activateIncognito"

### ISSUE THREAD

**Issue by vort3** [gdh1995/vimium-c#195]
Can we please have a new command that opens Vomnibar, but after you press Enter, selected page/search opens in new incognito (private in Firefox) window? I use Firefox and if this feature exists, please tell me how to do that, but I didn't find that in List of all commands page.

**Comment by gdh1995** [comment]
Vimium C v1.84.0 has been published, and you may write mappings like `map o Vomnibar.activate incognito` to do so.

**Comment by vort3** [comment]
`map O Vomnibar.activate incognito` worked for me, didn't know you can do that, thanks!

**Comment by gdh1995** [comment]
Um, I just added it into v1.84.0, and the commit is c226120

**Comment by gdh1995** [comment]
@foxjaw Sorry. `map g Vomnibar.activateInNewTab incognito` should work in v1.99.997.
