### ISSUE TITLE
在使用chrome系浏览器时，Vimium-C在可视模式下无法选择文本

### ISSUE THREAD

**Issue by younger-1** [gdh1995/vimium-c#196]
我主要是用 CentBrowser（基于 chrome 开发），在发现 Vimium-C 比 vimium 可定制更好后切换到了 Vimium-C，并把 vimium 卸载了

经过一番设置，使用时发现基础功能中的可视模式居然无法选择文本，具体体现在：
1. 在启用了 Vimium-C 的网页，点击某处文字，按下 v（或 V），右下角提示：自由选择模式（或 整行选择模式）
2. 按 hjkl，光标无法移动，反而是页面滚动了
3. 按 c，没反应，右下角提示也保持不变

于是，我想一定是我的配置有问题，就把 Vimium-C 卸了重装，重新按上面的3步操作走了一遍，依旧是上面描述的那样。

接着，我把浏览器所有插件都禁用了，重新按上面的3步操作走了一遍，依旧是上面描述的那样。

我猜8成是我使用的浏览器 CentBrowser 的问题，于是我切到新版 Edge，在它的应用商店下载安装 Vimium-C ，安装 Vimium-C，没作任何配置，重新按上面的3步操作走了一遍，依旧是上面描述的那样。

嗯，一定是MS的问题，我这么想着，在 google chrome 安装 Vimium-C，没作任何配置，重新按上面的3步操作走了一遍，依旧是上面描述的那样。又下了个 vimium 发现可视模式可以正常使用。

我开始慌了，难道这插件不支持 chrome系浏览器，可Google应用商店和MS应用商店里的评论和github的issues都没提到这个问题。那就一定是我的问题，我笔记本的问题。为了确认，我把 firefox 的 vimium 换成了 Vimium-C，没作任何配置，居然可以用了！

what？我又装了 基于 firefox 的 waterfox-current 和 waterfox-classic ,安装 Vimium-C，没作任何配置，没错，可以正常使用。那么插件真的不支持 chrome系浏览器吗

为了进一步确认，又下了 Brave（基于 chrome 开发），vivaldi（基于 chrome 开发）, 安装 Vimium-C，没作任何配置，重新按上面的3步操作走了一遍，依旧是上面描述的那样，都无法使用无法可视模式。

当然，也可能是我笔记本的问题。希望作者有空可以看一下。

**Comment by gdh1995** [comment]
这是 v1.84.0 的bug，v1.84.1 正在审核中，等正式发布就能用了。

目前的办法是，刷新VisualMode出错的页面，先进入一次FindMode，再退出，这个页面上VisualMode就能正常用了

**Comment by younger-1** [comment]
我的天，你这回复速度 💯 

好的，这样确实可以用了 😃

**Comment by gdh1995** [comment]
谢谢反馈。Firefox上v1.84.1已经在北京时间昨晚正式发布了，所以会有区别。

Firefox上发版基本上几十秒就能自动批准，Chrome和Edge都有人工审核的流程，快的今晚就能过，长的话要三四天。

此问题的原因是，VisualMode 从 v1.84.0 开始依赖了 FindMode 的一些数据，如果FindMode没初始化过就有后续问题。修复此问题的提交是 a3542e94c107435a18757f20ef04de9020633182 。

**Comment by younger-1** [comment]
thx

**Comment by younger-1** [comment]
想问下有没有快捷键能映射到 打开历史记录，就是那个历史记录标签页

 `map gh Vomnibar.activateHistory` 是打开一个 Vomnibar ，我想要 按下 ctrl-那样的效果

**Comment by gdh1995** [comment]
`map gh openUrl chrome://history` ?

**Comment by younger-1** [comment]
可以了。`openUrl`真好用 🥰 

还想问下，`map sh Vomnibar.activateHistory tree=true`中 `tree` 是什么作用呢

**Comment by gdh1995** [comment]
tree是想根据标签页的“A打开B”的关系拼出来一个树，但浏览器提供的这个关系很脆弱，稍微点几个按钮就没了，我又不想在Vimium C里自己维护一套，后来就基本放弃这个功能了，只是留了个选项。

**Comment by younger-1** [comment]
哈哈，好的。了解了

**Comment by gdh1995** [comment]
Chrome 商店里 v1.84.1 已经发布了

**Comment by younger-1** [comment]
Wwwwow! Nice
