### ISSUE TITLE
The extension "PDF Viewer for Vimium C" from Chrome Web Store can not run on Microsoft Chromium Edge 

### ISSUE THREAD

**Issue by h-lujian** [gdh1995/vimium-c#197]
The extension can not run after the latest update on July 5th.
Microsoft Windows 10 Pro for Workstations, Build 19041.388
Microsoft Chromium Edge Stable,  Version 83.0.478.64 (Official build) (64-bit)
Extension 2.4.456.3

**Comment by gdh1995** [comment]
It requires a version of Vimium  which is published to the Edge Add-ons, so you can open https://microsoftedge.microsoft.com/addons/detail/aibcglbfblnogfjhbcmmpobjhnomhcdo to install Vimium and then it should work.

**Comment by h-lujian** [comment]
Oh..it works. thanks a lot.

**Comment by gdh1995** [comment]
If you do want to use Chrome Web Store version of Vimium C, you need to open the Developer Tools of PDF Viewer for Vimium C, and then switch to Console and run `localStorage.targetExtensionInjector = "targetExtensionInjectorhfjbmagddngcpeloejdejnfgbamkjaeg"`. Then you can reload the page to see if it work.
