### ISSUE TITLE
wired function of Esc

### ISSUE THREAD

**Issue by Monirzadeh** [gdh1995/vimium-c#199]
OS: ubuntu 20.04
WM: bspwm
Browser: Brave
i remap shift as Esc with this command
```
xcape -e 'Shift_L=Escape'
```
everything work fine but some time (usually when i open a tweet with image) when i press shift to Esc vimium-c act as multiple back key in history instead of Esc
it is not happen all the time so how should i get some log about that.
[xcape](https://github.com/alols/xcape)

**Comment by Monirzadeh** [comment]
```
	Event	Code	Key	Modifiers
1	keydown	ShiftLeft	Shift	
2	keyup	ShiftLeft	Shift	
3	keydown	Escape	Escape	
4	keyup	Escape	Escape	
5	keydown	Escape	Escape	
6	keyup	Escape	Escape	
7	keydown	ShiftLeft	Shift	
8	keyup	ShiftLeft	Shift	
9	keydown	Escape	Escape	
10	keyup	Escape	Escape	
11	keydown	Escape	Escape	
12	keyup	Escape	Escape	
13	keydown	ShiftLeft	Shift	
14	keyup	ShiftLeft	Shift	
15	keydown	Escape	Escape	
16	keyup	Escape	Escape	
17	keydown	Escape	Escape	
18	keyup	Escape	Escape	
```

**Comment by gdh1995** [comment]
According to the last comment, I think with your `xcape` `one L-Shift` means `two Escape keys`. And because this is what your browser got, Vimium C has no way to recognize "it should have meant only one Escape".


> multiple back key in history instead of Esc

What does this mean? Sorry I don't understand it.

**Comment by Monirzadeh** [comment]
it like press `H` (`Go back in history`) multiple time

**Comment by gdh1995** [comment]
This seems a behavior of Twitter - some pages uses Escape to go back.

**Comment by Monirzadeh** [comment]
> This seems a behavior of Twitter - some pages uses Escape to go back.

i know but some time it back to DM,bookmarks,etc if it present in my history (Escape not go back to that pages if you are in timeline)

**Comment by gdh1995** [comment]
If you enter FindMode, click the web page and activate LinkHints again, will L-Shift exit both the two modes? If it does, then Vimium C grabs the Escape keys correctly; if not, then there may be some bugs in Vimium C in such situations.

**Comment by Monirzadeh** [comment]
> If you enter FindMode, click the web page and activate LinkHints again, will L-Shift exit both the two modes?

No. just exist last mode (LinkHints)

**Comment by gdh1995** [comment]
Hello, I've updated https://gdh1995.cn/vimium-c/keyboard-test.html to record more, could you test again?

**Comment by Monirzadeh** [comment]
one L-Shift key press:
```
1 | keydown | ShiftLeft | Shift | Shift | 16
-- | -- | -- | -- | -- | --
2 | keyup | ShiftLeft | Shift |   | 16
3 | keydown | Escape | Escape |   | 27
4 | keyup | Escape | Escape |   | 27


```

**Comment by gdh1995** [comment]
The old is:
> one key press:
> 1 | keydown | ShiftLeft | Shift |  
> 2 | keyup | ShiftLeft | Shift |  
> 3 | keydown | Escape | Escape |  
> 4 | keyup | Escape | Escape |  
> 5 | keydown | Escape | Escape |  
> 6 | keyup | Escape | Escape

The new is
> one key press:
> 1 | keydown | ShiftLeft | Shift |   | 16
> 2 | keyup | ShiftLeft | Shift |   | 16
> 3 | keydown | Escape | Escape |  | 27 
> 4 | keyup | Escape | Escape |   | 27

What have you changed on the key mapping tool?

It seems all the info in the latest list meets what I expect. So I think maybe your browser, Brave, has some special actions on Escape followed by Shift ?

Could you test it on Firefox / Chromium + your system, or Brave + Windows/macOS ?

**Comment by Monirzadeh** [comment]
i kill all xcap with this comment 
`pkill xcap`
and 
run  bellow command again i think at the first i have 2 xcap i do all of them again
pkill xcape(without xcape command):
```
1 | keydown | ShiftLeft | Shift | Shift | 16
2 | keyup | ShiftLeft | Shift |   | 16
```
one `xcape -e 'Shift_L=Escape'` command
```
1 | keydown | ShiftLeft | Shift | Shift | 16
-- | -- | -- | -- | -- | --
2 | keyup | ShiftLeft | Shift |   | 16
3 | keydown | Escape | Escape |   | 27
4 | keyup | Escape | Escape |   | 27
```
two `xcape -e 'Shift_L=Escape'` command
```
1 | keydown | ShiftLeft | Shift | Shift | 16
-- | -- | -- | -- | -- | --
2 | keyup | ShiftLeft | Shift |   | 16
3 | keydown | Escape | Escape |   | 27
4 | keyup | Escape | Escape |   | 27
5 | keydown | Escape | Escape |   | 27
6 | keyup | Escape | Escape |   | 27
```

**Comment by gdh1995** [comment]
Then the keypoint is why a simulated Escape triggers "go back in history" on some pages on Brave.

* what it will do, if you set custom key mappings to a single line of`unmapAll` (and click "Save Options") on the Vimium C Options page?
* what it will do, if you have disabled Vimium C and refreshed the page?
* what the Shift_L will do on Chromium/Firefox on your system when xcape is being used?

**Comment by Monirzadeh** [comment]
it not happen again, i close this issue and reopen that if i experience that again and find more clue about that.
thanks for your help
