### ISSUE TITLE
Keys in PDF reader don't work

### ISSUE THREAD

**Issue by welovelain** [gdh1995/vimium-c#20]
Installed this extension, as I was told keys would work while browsing PDF files. Well, doesn't work =)

**Comment by gdh1995** [comment]
Test it on Chrome 67 stable x64 on Win 10 build 1803, and Vimium++ works well on pages of the PDF Reader extension from Chrome Web Store.

**Comment by welovelain** [comment]
I have chromium 63, going to update to latest version and check again, thanks

**Comment by gdh1995** [comment]
@welovelain Sorry to bother you so late, were you using the official PDF Viewer extension (whose id is oemmndcbldboiebfnladdacbdfmadadm, and its sources is in https://github.com/mozilla/pdf.js), or my customized "PDF Viewer for Vimium C" (whose id is nacjakoppgmdcpemlfnfegmlhipddanj)?

**Comment by welovelain** [comment]
Tried PDF Viewer for Vimium C, it works allright there. Guess it's closed then =) Thanks for good extensions

**Comment by gdh1995** [comment]
> that your vimium is only working in your pdf viewer extension

Yes. This is because Chrome doesn't allow an extension to run on another extension without some specific tricks - pages of my customized PDF Viewer extension always actively send requests to Vimium C  to download needed scripts.
