### ISSUE TITLE
Hints letter selection seems random

### ISSUE THREAD

**Issue by SolitudeSF** [gdh1995/vimium-c#200]
vimium scatters single letter hints all around the page
![image](https://user-images.githubusercontent.com/10168645/88833005-52c5ec80-d1da-11ea-8ee4-49b7395bd3cf.png)

vim vixen/surfingkeys predictably place them on first elements
![image](https://user-images.githubusercontent.com/10168645/88833114-725d1500-d1da-11ea-9aeb-352451ccbfda.png)

tridactyl is a bit worse, since it prioritizes sidebar in this example, but still more predictable
![image](https://user-images.githubusercontent.com/10168645/88833184-8c96f300-d1da-11ea-92d9-5a52b6eb8d68.png)

so, my issue would be that easiest to reach (single letter) hints should come first on the page.

**Comment by gdh1995** [comment]
Um, this works as designed. Both Vimium C and its original project "Vimium" use a pseudo-random algorithm to:
* distribute all hint markers with a same first letter
* so that when you press a first key, then in a local region there tends to be fewer markers, compared with the second snapshot.

**Comment by SolitudeSF** [comment]
okay, thanks for the explanation.

**Comment by gdh1995** [comment]
@agenbite Not easy to do so. But you may try `Filtered Hints` mode (see https://github.com/philc/vimium/wiki/Using-Link-Hints#filtered-hints ), which is also supported in Vimium C now.
