### ISSUE TITLE
What does 'W' mean, in the  'o' search results?

### ISSUE THREAD

**Issue by dungc** [gdh1995/vimium-c#201]
![image](https://user-images.githubusercontent.com/12635468/88874260-3b761600-d251-11ea-9309-722e62483bd0.png)

**Comment by gdh1995** [comment]
It's "Website", which means Vimium C searches in a domain list and finds it. The domain list is created from your browsing history list.

**Comment by dungc** [comment]
Thank you for reply, this really help me.There is a search result that bothers me.Now i know how to remove it.
