### ISSUE TITLE
Best way to execute bookmarklet? (javascript bookmark)

### ISSUE THREAD

**Issue by jlnbdt** [gdh1995/vimium-c#203]
Hi,

I wonder what is the best way to execute a bookmarklet:

- I tried to open it with _Vomnibar.activateBookmarks_ but I get "Impossible d'évaluer de scripts ici" (impossible to evaluate scripts here). That's strange, because it seems to me that it worked before.
- Perhaps it's possible to bypass the Vomnibar and directly execute a bookmarklet through a key mapping?
- Is there any way to replace simple javascript code using some variables (like qutebrowser's {url} or {title}) ie. open an url with: `map X createTab url="https://my_online_bookmark_service/link={url}&title={title}"` ?

Thanks

**Comment by gdh1995** [comment]
the first "impossible...": what page were you on? vimium c can only execute js urls on normal http(s) pages, and some page may even refuse external js code.
currently Vimium C doesn't try it best to bypass such limits, so maybe I'll update it in some days.


as for run bookmarklet, there's an alternative command: openUrl. and it supports many useful options.
For me it's night now. I'll explain it in the next noon.



---Original---

**Comment by jlnbdt** [comment]
> the first "impossible...": what page were you on? vimium c can only execute js urls on normal http(s) pages, and some page may even refuse external js code. currently Vimium C doesn't try it best to bypass such limits, so maybe I'll update it in some days.

Unfortunately, it's not working anywhere. I tried it from several web pages, and the result is always the same.

> For me it's night now. I'll explain it in the next noon.

Thanks, I'll wait :)

**Comment by gdh1995** [comment]
Vimium C use `<script>...</script>` to run JS code, so it will be affected by Content-Security-Policy and iframes' `allow-scripts` tag. As far as I've tested, it works on `https://github.com/*`, but not on `https://raw.githubusercontent.com/*` .

You may try `map X createTab url="https://my_online_bookmark_service/link=$s" url_mask="$s"`.

Currently there's no mark keys for tab titles, but I'll add it soon.

**Comment by gdh1995** [comment]
BTW, in v1.84.3, although not released yet, `openUrl` has 4 masks: `url_mask`, `host_mask`, `tabid_mask` and `title_mask`.

**Comment by jlnbdt** [comment]
Thanks for these explanations.
I tried 
`map wsh createTab url="https:///my_online_bookmark_service/post=$s" url_mask="$s"` but it opens a research in my default search engine with this long url, instead of open it.

**Comment by gdh1995** [comment]
There should be a well-formatted URL. Please put your real mapping here and I think it may contain some typos.

**Comment by gdh1995** [comment]
Um, your example URL `https:///my_online_...` has too many <kbd>/</kbd> characters next to the first ":".

**Comment by jlnbdt** [comment]
Erf… stupid mistake.
Thanks, works like a charm! :+1:
