### ISSUE TITLE
Scroll Does Not Work For Scrollable Components Other Than The Website Itself

### ISSUE THREAD

**Issue by abbietapmer** [gdh1995/vimium-c#206]
The extension's scroll function does not work for secondary scrollable components in a webpage.

**Comment by gdh1995** [comment]
You can click a wanted area before using keys to scroll it, or the command of `LinkHints.activateModeToHover` is used to select such an area - you just need to select a link or button in the area, then Vimium C will scroll it.

Refer: #147 and #171 .

**Comment by abbietapmer** [comment]
Thanks. I wish it was one of the featured commands.
