### ISSUE TITLE
Custom possition for LinkHints activateModeWithQueue and activateModeToOpenInNewTab 

### ISSUE THREAD

**Issue by pointtonull** [gdh1995/vimium-c#208]
Thanks a lot for your amazing plugin. Combined with _keynav_, makes it possible for me to use a computer.

<Alt F> (LinkHints.activateModeWithQueue) is my favorite feature, it makes browsing a pleasure.

I only wish it would honor browser setting on where to put the new tabs. Or, alternatively, it would be great if it had a setting option to choose **vimium-c**'s behavior.

i.e.:

- **vimium-c** <alt F> behavior: tabs are open next to the current one, left to previously open related tabs
- my browser default behavior: new tab open at the end, right of any other tab
- _firefox_'s default: new tab open after previously open related tabs

Do you think it's a worthy feature?

Edited 16/08/2020 to better explain the problem.

**Comment by gdh1995** [comment]
`map t createTab position="end"`.

**Comment by pointtonull** [comment]
> `map t createTab position="end"`

Thanks for your promptly reply. I understand this mapping would allow to create a new empty tab at the end. But this is not what I was looking for. 

I was talking about being able to customize where to open new tab with <A-f> (Link Hints with Queue), or with <F> (Link Hints to New Tab).

Is there a way to do it? (I could not find any in the documentation or in source code)

**Comment by gdh1995** [comment]
Um, seems not existed. Maybe I'll add this feature in this month or the next one.

**Comment by pointtonull** [comment]
Thanks, you are very kind.

**Comment by gdh1995** [comment]
Please test this: [vimium_c-1.84.3-firefox-1cf32a5.zip](https://github.com/gdh1995/vimium-c/files/5092083/vimium_c-1.84.3-firefox-1cf32a5.zip).
* Installation: see https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package .
* Usage: `map ... LinkHints.activateMode*** position="default"`

**Comment by pointtonull** [comment]
I tested several settings using Firefox 79.0 (64-bit) / Linux AMD64

All of these are working perfectly:

- :heavy_check_mark: `map t createTab position="end"`
- :heavy_check_mark: `map t LinkHints.activateModeWithQueue "`
- :heavy_check_mark: `map t LinkHints.activateModeWithQueue position="start"s`
- :heavy_check_mark: `map t LinkHints.activateModeWithQueue position="begin"`
- :heavy_check_mark: `map t LinkHints.activateModeWithQueue position="before"`
- :heavy_check_mark: `map t LinkHints.activateModeWithQueue position="after"`

These are not working:

- :x: `map t LinkHints.activateModeWithQueue position="end"`
- :x: `map t LinkHints.activateModeWithQueue position="default"`

Both of them produce this error in the console:
```
Unchecked lastError value: Error: isPlaying is not defined 2 background.js:365
    <anonymous> moz-extension://cca877b4-6284-46f4-a686-8cfe0201d2c0/background.js:365
```

**Comment by gdh1995** [comment]
The old package contains a typo, so please try this: [vimium_c-1.84.3-firefox-1cf32a5-fix.zip](https://github.com/gdh1995/vimium-c/files/5094560/vimium_c-1.84.3-firefox-1cf32a5-fix.zip)

BTW, the line of console output is not Vimium C's.

**Comment by pointtonull** [comment]
It's working perfectly now.
Thank you very much :pie: :spark

**Comment by pointtonull** [comment]
Confirmed, I had switch to the released version and it's working as expected.
Thank you very much
