### ISSUE TITLE
Google docs support

### ISSUE THREAD

**Issue by ayroblu** [gdh1995/vimium-c#211]
Hey, I saw this: https://github.com/philc/vimium/issues/3367
Tried it on google docs, but I can't just press esc and use vimium keys. I also don't think I can use setup commands like "cmd+alt+t" or similar to trigger the vomnibar for example.
Am I doing something wrong? 

PS: I'm not sure what other feature differences there are between the original vimium and this one for non Chinese users?

**Comment by gdh1995** [comment]
Vimium C has changed very much logic, so I'm not sure what's wrong in your case. I'll test Google Docs again with Vimium in days.

**Comment by gdh1995** [comment]
Have you tried long-pressing <kbd>Esc</kbd> from the Google Docs' mode of inputting text?

**Comment by gdh1995** [comment]
> I can't just press esc and use vimium keys

Try this: **press and hold on** Escape for a while, until you see a yellow border on the whole page (top frame), and then normal **key mappings in Vimium C ** will be usable.

Holding on Escape will trigger a function whose logic is somehow like the command `parentFrame`, and when it succeeds, the cursor will lose focus and the top frame will get the focus, so Vimium C enters its Normal Mode, from a plain Insert Mode.



> cmd+alt+t

Well, there's a bug when triggering Vomnibar through global shortcuts on Google Docs. I'll fix it in the next weeks.

**Comment by ayroblu** [comment]
Ahh yes I get the yellow frame flash which works thanks!

Just as an example:
```
map <c-s-l> LinkHints.activateMode
```
on a normal site, it shows the hints, but on g docs, it doesn't do anything as gdocs doesn't have this shortcut, but it swallows it (I'm using a mac so it's ctrl-shift-l, I realised my example wasn't good because it wasn't the keys I use specifically)
I was wondering if maybe I'm specifically doing it wrong, i.e. there is a different way or using cmd or something

**Comment by gdh1995** [comment]
On Google Docs, when you can see the caret or text selection area, then Vimium C is usually in its Insert Mode. Vimium C enters this mode whenever a text box is focused.

In this mode, Vimium C ignores most keys, except these:
* global shortcuts configured on `chrome://extensions/shortcuts`
* those keys composed with F1~F12, like `<f7>`, `<c-f8>` and `<a-s-f2>`
* those keys including the "`:i`" tag, like `<c-v:i>`

wiki:
* https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box

**Comment by ayroblu** [comment]
I can confirm that both of these don't work for me on gdocs, but do work on normal inputs

```
map <c-t:i> Vomnibar.activateTabSelection
# with the correct mapping in chrome://extensions/shortcuts
shortcut userCustomized1 command="Vomnibar.activateTabSelection"
```

**Comment by gdh1995** [comment]
Yes, there's a bug make Vomnibar fail in such a situation, but some other commands like switching tabs work.

All affected are `LinkHints.activate*`, `Vomnibar.activate*` and `scroll*`.

Commit ad87e66f04ab2a2198a888aaf6b03904a5e38527 should fix this bug. And please test this zip file: [vimium_c-1.85.0-chrome-a8b205a-mod.zip](https://github.com/gdh1995/vimium-c/files/5130779/vimium_c-1.85.0-chrome-a8b205a-mod.zip)

Test steps: https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package

**Comment by ayroblu** [comment]
Cool thanks. Is there anything I need to do when you update the store? Do I need to uninstall the extension and reinstall it to go back to the official one?

**Comment by gdh1995** [comment]
yes you'll need to reinstall the store version



---Original---

**Comment by gdh1995** [comment]
Hello, v1.85.1 has been released on Microsoft Edge Add-ons, Firefox Add-ons and Chrome Web Store, and you may take a try.

**Comment by ayroblu** [comment]
Thanks works as intended!
