### ISSUE TITLE
Copying URL from PDF copies it with the `chrome-extension://` prefix

### ISSUE THREAD

**Issue by infokiller** [gdh1995/vimium-c#213]
I think it used to work fine (copying the original URL), but now it copies to my clipboard the URL of the PDF extension, although the Vimium C message says it's copying the correct URL (i.e. it shows `Copied: https://...`).

**Comment by gdh1995** [comment]
Um, no. It never really works.

When showing a copied URL, Vimium C strips a prefix of `chrome-extension://<ext-id>/`, so it looks like you're copying the PDF link, but up to now the real copied is always the whole URL of an extension's tab.

I'll take a try to find how to fix this incompatibility. I've got an idea to make `map *** copyCurrentUrl type="frame"` work, but the default behavior of `copyCurrentUrl` is to copy not frame URLs but tab URLs, so maybe I need more time and more tests.

**Comment by gdh1995** [comment]
Hello, v1.85.1 has been released on Microsoft Edge Add-ons, Firefox Add-ons and Chrome Web Store, and a new PDF Viewer for Vimium C is also on Chrome Web Store, so you may take a try.

**Comment by infokiller** [comment]
Thanks a lot for working on this so quickly.
I still see the old behavior (with the `chrome-extension://` prefix) with Vimium C 1.85.1 and PDF Viewer for Vimium C 2.6.324. Am I using the right versions?

**Comment by gdh1995** [comment]
what's your used key and related key mappings?


as said above, it needs type=frame



---Original---

**Comment by infokiller** [comment]
I tried: `map yy copyCurrentUrl type="frame"`

**Comment by gdh1995** [comment]
Confirmed.

Here's a work-around: use `map yy autoCopy url decode`.

**Comment by infokiller** [comment]
Thanks, works great now!
