### ISSUE TITLE
mapKey相关提问

### ISSUE THREAD

**Issue by Delayless** [gdh1995/vimium-c#215]
真的很抱歉，中英文都看了，我实在没看懂mapKey的用法。
我之前用vimium里的映射是
```
map J scrollPageUp
map K scrollPageDown
```
但是在caret和visual模式下不能使用，我的理解是直接把map改成mapKey就可以实现，但是尝试了不行。
然后又尝试先map J 到scrollpagedown，然后再mapKey J J还是不对，所以只好来提issue了，请问怎样解决我的需求呢？
如果能map J 5j这种用法那更好。先感谢您回答。

**Comment by gdh1995** [comment]
scroll 这种命令是不在任何模式里时（也就是说在默认的normal mode）才会触发的，大部分命令都是这样。所以caret、visual模式下一般是执行不了命令列表里的其它命令的，只能执行固定的一些绑定：

https://github.com/gdh1995/vimium-c/blob/9db8e909cccf469ca204561d5a9bd7d376030733/background/commands.ts#L612-L617

`mapkey <...:v> ...` 可以让指定的键来代替上边写死的键，来执行visual mode下定义的某个任务。

**但也有一个例外：**虽说visual mode会拒绝不认识的键（并且阻止normal mode执行它们），但带有 F+数字 的键会被放过去，所以：
```
mapkey <c-j:v> <f110>
map <c-j> scrollDown
```

表示：VisualMode下把 Ctrl+J 视为 F110 这个键，被VisualMode放过去，然后被normal mode接到并仍然按 Ctrl+J 查找绑定的命令，找到 scrollDown并执行。

`mapkey <J:v>` 的解析有bug，在设置页面会被转成 `<s-j:v>` 但实际中不会用这个方法来表示一个键，等发新版本吧。你可以先带 Alt、Ctrl 之类的键用着。

=====

另外，VIM里的 `5j` 在这里应当是：`map <c-j> scrollDown count=5`。虽说normal mode支持 5j 的按键序列，但是 visual mode 会拦截 5，除非也用 `mapkey <5:v> <f111>` 这种办法绕过去。

**Comment by Delayless** [comment]
谢谢您耐心回答，逻辑我是大概懂了，但是突然发现pagedown只是翻页，并不能达到移动光标选中文本的作用。你说visual会拦截5,可是我发现visual模式也可以通过{num}{motion}（e.g:5j）移动，但是却没法映射到单键/组合键。

**Comment by gdh1995** [comment]
总结一下就是visual mode有自己的map 列表，而且是不可修改的，所以它拦截了5、j、k等键来移动光标或者复制文字等，其它不认识的键一般会丢弃，只有带 F+数字 的键才会放过去让其它模式处理。这里 5j 的处理是 visual mode自己解析了 5 和 j 并决定要移动光标的。

目前修改visual mode行为的唯一办法，就是用 mapkey 提前改变visual mode接收到的键名。

从 background/commands.ts 里可以看到 visual mode 并没有“将光标向下移动半个屏幕”的命令，所以如果你想要这么做的话，目前来说没有直接办法。但是有个极端 trick 的办法，我一会再说

**Comment by Delayless** [comment]
嗯嗯 可以写到README的高级用法里面。

**Comment by gdh1995** [comment]
editText 这个命令支持调用 document.execCommand 和 Selection.modify，所以可以说是能任意地移动光标。

```
map <c-j:v> <f110>
map <c-j> editText dom run="auto,forward,paragraph" count=5
```

这样 c-j 表示光标向下移动 5 个段落，其中 forward 表示 向下、向右， paragraph表示距离是一段。

**Comment by Delayless** [comment]
嗯嗯，功能实现了，接下来就是提升体验了。加油，把vim装进浏览器里（斜眼笑）

**Comment by gdh1995** [comment]
1.85.1版已经发布了，`mapkey <J:v> ...` 这个写法可以用了

**Comment by Delayless** [comment]
赞，那就是这样写吗
```
mapkey <J:v> editText dom run="auto,forward,paragraph" count=5
```

**Comment by gdh1995** [comment]
map 和 mapkey不一样，还是要分两条命令写

**Comment by danny1879** [comment]
> 嗯嗯，功能实现了，接下来就是提升体验了。[，]，[]）]）

请教，我还是不明白，怎么修改v模式下的方向键映射？我不想用hjkl移动光标，想改成jkli。感谢。

**Comment by danny1879** [comment]
> > 嗯嗯，功能实现了，接下来就是提升体验了。[，]，[]）]）
> 
> 请教，我还是不明白，怎么修改v模式下的方向键映射？我不想用hjkl移动光标，想改成jkli。感谢。

已经解决。谢谢
