### ISSUE TITLE
有两个地方需要改进一下

### ISSUE THREAD

**Issue by MaxSherry** [gdh1995/vimium-c#216]
1.  添加pagedown和pageup键的映射, 起因是我的翻页是做的如下的映射  
```
map <c-b> scrollFullPageUp
map <c-f> scrollFullPageDown
```
但是出现的问题,有些页面在整页翻页的时候,上一页的最底部和下一页的最顶部这块区间没有衔接上;  所以我想使用原始键盘的 pageup 和 pagedown 来代替
```
mapKey <c-b> <pageup>
mapKey <c-f> <pagedown>
```
这样的配置不起作用   

2. 在进行查找的时候, 不想使用循环查找, 查找到底部后,给出相应的提示到底部了

**Comment by gdh1995** [comment]
1. mapkey 只在 Vimium C 内部生效，不会也无法影响到浏览器。
2. 如果你觉得需要衔接，可以给滚动命令加参数 dir，比如：
```
map <c-b> scrollFullPageDown dir=0.92
```
3. 不循环的查找暂不支持，我回头想想

**Comment by gdh1995** [comment]
v1.85.2 已经发布了，在没指定 "`\r`" 或者 指定了“`\R`”后，使用“`\A`”可以关闭循环查找，"`\a`" 恢复循环查找。

输入完搜索词后，按 Ctrl+J/K 可以查找下一个、上一个地方，所以按几次 Ctrl+J 后看不到选择区域变化时，就说明找不到了。

右侧显示的搜索词的计数 始终是循环查找模式下全文的可能匹配的数量。
