### ISSUE TITLE
Dracula theme for the omnibar

### ISSUE THREAD

**Issue by NetherKing1357** [gdh1995/vimium-c#217]
The CSS used to set [Dracula Theme for vimium](https://github.com/dracula/vimium/blob/master/vimium-dracula.css) doesn't seem to do anything on vimium-c. I tried and failed to implement it using the vimium-c CSS classes. Could I get some help on the CSS?

**Comment by gdh1995** [comment]
Most class names can been seen in https://github.com/gdh1995/vimium-c/blob/master/front/vomnibar.html . A easy way to find class names and ids of page elements is, to open the Developer Tools and pick the Vomnibar iframe.

**Comment by NetherKing1357** [comment]
Here are my Custom CSS settings:
```/* omni */
#bar.D:after{background:#000;border-color:#666;}
```
Here are my Vomnibar settings:
```
{
  "maxMatches": 10,
  "queryInterval": 333,
  "sizes": "77,3,44",
  "styles": "light: dark",
  "actions": ""
}
```
No changes are seen in bar. I'm able to alter the color of the bar by changing the color values in `iframe.R.UI.Omnibar > html.light: > head > style#dark` but not through the Vimium C options. Am I missing something?

Sorry for the rookie questions.

**Comment by gdh1995** [comment]
Your CSS has some mistakes - there's neither `/* omni */ nor `#bar.D:after`, and please use `/* #omni */` and `#bar` instead.

The below should work
``` css
/* #omni */
#bar{background:#fff;border-color:#666;}
```

And the keyword of `light:` seems not so suitable, you may set `"styles": "dark is-dark"` and then `<html>` will have a classname of `is-dark`, so you can write CSS like `.is-dark #bar {background:#fff}`.

**Comment by NetherKing1357** [comment]
Thanks, this works! Could you please change the [wiki page](https://github.com/gdh1995/vimium-c/wiki/Style-the-UI-of-Vimium-C-using-Custom-CSS#using-your-styles-with-dark-mode) to reflect these mistakes? Would be much appreciated!

**Comment by ugirc** [comment]
> Thanks, this works! Could you please change the [wiki page](https://github.com/gdh1995/vimium-c/wiki/Style-the-UI-of-Vimium-C-using-Custom-CSS#using-your-styles-with-dark-mode) to reflect these mistakes? Would be much appreciated!

Can you share you setting code? I also want to use  `Dracula Theme for vimium` in vimium-c. Thanks!

**Comment by binhtran432k** [comment]
@ugirc, This is my port from `Dracula Theme for vimium` to vimium-c: https://github.com/binhtran432k/vimium-c-dracula

**Comment by z872845991** [comment]
> @ugirc, This is my port from `Dracula Theme for vimium` to vimium-c: https://github.com/binhtran432k/vimium-c-dracula

Thank you, bro. It does work!
