### ISSUE TITLE
希望edge商店可以同步更新

### ISSUE THREAD

**Issue by lycleg** [gdh1995/vimium-c#220]
哈喽，非常感谢开发这个插件。希望可以同步更新edge商店的版本

**Comment by gdh1995** [comment]
edge商店版在 https://microsoftedge.microsoft.com/addons/detail/aibcglbfblnogfjhbcmmpobjhnomhcdo

我发版都是一起发的，不过edge和chrome商店都要审核，审核花的时间不一样。最新版是 v1.85.2，chrome刚批准了，edge还没。Firefox版是系统自动审批所以一般最快。

**Comment by gdh1995** [comment]
v1.85.2 的 edge商店版 已经发布了。

**Comment by lycleg** [comment]
非常感谢，3Q。可以搞个付费模式就好了哈哈

**Comment by gdh1995** [comment]
现在是有个打赏链接， https://github.com/gdh1995/vimium-c#donate ，打赏与否全凭自愿。纯 JS 写的浏览器插件很难做付费，因为破解起来完全没有障碍。
