### ISSUE TITLE
Overview of global/local marks

### ISSUE THREAD

**Issue by technodrome** [gdh1995/vimium-c#221]
First of all, sincerely thank you for a fantastic extension :)

I'd like to add a feature request - when working local/global marks, their management is very cumbersome. A feature (HUD like when pressing `?`) would be absolutely brilliant where all global and local marks would be listed, ideally with `X` button to clear that one single specific mark.

AFAIK, currently we have only `Marks.clearLocal` and `Marks.clearGlobal` which is not ideal - they remove either all or nothing. Moreover, there's no way to show all local marks for all pages, as `clearLocal` only clears marks scoped to that specific page - not all local marks.

For both local and global marks, one has to reassign a mark if one doesn't need it anymore - but you never know what's actually assigned to that letter without actually pressing the mark and checking what's assigned there.

Marks overview is missing as without that, it's hard to orientate.

**Comment by gdh1995** [comment]
Um, in fact there's a way to use a browser's inner feature to view all marks:
* open Vimium C Options page
* press <kbd>Ctrl+Shift+I</kbd> to open the Developer Tools
* choose the "Application" (Chromium) or "Storage" (Firefox) panel
* expand the "local storage" menu item at the left side, and click the URL in its child items
* then you'll see some `key-val` items, and those keys starting with `vimiumMark` and `vimiumGlobalMark` are local / global marks

**Comment by technodrome** [comment]
Thank you for your reply.

I am not sure how you gauged the interest in this feature by saying it has "quite low frequency". My wild guess is, it has very much to do with the fact that it is not documented well. I had to hunt through issues and source code to actually find out how it works, what `swap` does, etc. My colleagues use vimium-c but did not know how to use this because it is not explained well.

Without feature ocumentation available at release time with proper examples of how to set them up, usage will be low without doubt.

While I absolutely appreciate your work and this fantastic extension, I strongly believe accessing marks the way you described is not user friendly. The point is, adding finished and polished features trumps adding heaps of new features all the time. Better polish what we have than keep adding new features without actually explaining how to use them in the first place.

Just my two cents.

**Comment by gdh1995** [comment]
Um, this project does lack documents - it's because of my personal habits, well, as you said, that I've assigned most time adding new features.

As for the feature of viewing marks, it has a special reason: Vimium C is built from Vimium and most features of the `Marks` mode is very similar with Vimium's. Vimium has much more users while there're no new issues or discussions in recent years about "adding a view of marks".

BTW, in Vimium local marks are "decentralized" into "local storages" of all used websites, so technically there's no way to list local marks and only global marks can be shown. I changed this behavior in a very early version of Vimium C, and thought it enough to view on the Developer Tools.

**Comment by technodrome** [comment]
All rigt, thanks for clearing that up.

**Comment by thisdavej** [comment]
I agree that it would be great if global/local mark management could be handled through the Vimium UI.  As an end user, here's some alternative ways I arrived at as an interim solution to handle local mark management:

### Viewing and removing local marks in Vimium

If I create a local mark "p" on https://github.com/jlevy/the-art-of-command-line, there will be a key created in the Chrome `localStorage` of that URL in the following format:

```text
vimiumMark|https://github.com/jlevy/the-art-of-command-line|p
```

To show the Vimium local marks that exist on a given web page:

- Navigate to the web page in the browser.
- Press the `F12` key to launch Developer Tools
- Select the `Console` tab.
- Enter the following command:

```js
Object.keys(localStorage).filter(v => v.startsWith('vimiumMark')).forEach((x, i) => console.log(x))
```

To delete all local marks for a given page:

```js
Object.keys(localStorage).filter(v => v.startsWith('vimiumMark')).forEach((x, i) => localStorage.removeItem(x))
```

To delete the local mark "p", paste the following lines together into the console:

```js
mark = 'p'
const regex = new RegExp(`^vimiumMark.*${mark}$`);
Object.keys(localStorage).filter(v => v.match(regex)).forEach((k, i) => localStorage.removeItem(k))
```

To accomplish the same goal with a more graphical approach:

- Install the [Storage Area Explorer](https://chrome.google.com/webstore/detail/storage-area-explorer/ocfjjjjhkpapocigimmppepjgfdecjkb?hl=en) Chrome extension.
- Restart Chrome to activate the extension.
- Press the `F12` key to launch Developer Tools
- Select the `Storage Explorer` tab (This was added when the extension was installed above.)
- Select the `window.localStorage` tab (It's probably already selected by default.)
- Scroll down and review the the Vimium mark entries that are in the format of `vimiumMark|<url>|<shortcut_key>`.
  - For example `vimiumMark|https://github.com/jlevy/the-art-of-command-line|p` is a key I see when exploring the storage for `https://github.com/jlevy/the-art-of-command-line` which provides the location of local mark `p`.
- If desired, click the red delete icon on the far right of the row entry to delete the mark.

**Comment by gdh1995** [comment]
@thisdavej Thanks. There's only a small issue that `Vimium C` saves all local and global marks into its own storage, so a user need to open "Vimium C Options" to run those JS code.

Chrome (or Firefox)'s `Developer Tools` has its own UI to show `localStorage` items:
![image](https://user-images.githubusercontent.com/5547703/149605520-8bd4dff3-aa1a-47bc-a90d-540f25684b90.png)

And, Vimium C is planning to move all items in its `localStorage` into `chrome.storage.local`, so I'll add a Wiki page to talk about new ways to list marks.

**Comment by gdh1995** [comment]
Hello, I've added a wiki page: https://github.com/gdh1995/vimium-c/wiki/Show-all-marks

**Comment by thisdavej** [comment]
@gdh1995 thanks for the reply!  I was confusing your project with the philc/vimium project so my apologies for the confusion.  Your project looks really awesome - thanks!

**Comment by CouscousPie** [comment]
Is it possible to browse through and go to local/global marks via omnibar somehow?
