### ISSUE TITLE
Vimium bindings not working on PDF from websites

### ISSUE THREAD

**Issue by vtwang** [gdh1995/vimium-c#222]
When opening local PDFs (`file:///`), vimium c works perfectly. I am able to smoothly scroll with `j`/`k` and access table of contents with `f`. However, smoothly scrolling and clicking on links does not work when opening a PDF from a website.
See this example [PDF](https://www.nature.com/articles/ng.3390.pdf?origin=ppub) from nature.com

Vimium C | 1.85.2
PDF Viewer for Vimium C | 2.7.21
Brave | 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)
OS | macOS Version 10.15.6 (Build 19G2021)

**Comment by gdh1995** [comment]
If you install the official "PDF Viewer" extension from Chrome Web Store, then will it hook the page and show its customized PDF Viewer page?

The PDF needs "Buy article"... so I can not test it now.

**Comment by vtwang** [comment]
This [PDF](https://www.nature.com/articles/s41467-020-18363-2.pdf) shouldn't have a paywall.
The page loads using the PDF Viewer for Vimium C

![image](https://user-images.githubusercontent.com/29390846/92946472-b6bc1180-f424-11ea-8576-5ac6637c99c9.png)

**Comment by gdh1995** [comment]
Does Vimium C work on pages of other PDF URLs?

During my tests, when you open it in a new tab, it will auto jump to something like `chrome-extension://hkhendnifojnfdngnldfaeakojokgiio/https://www.nature.com/articles/s41467-020-18363-2.pdf`, and then Vimium C should work well.

If the shown URL on the address bar keeps unchanged, then please open the Developer Tools (on Chrome it's Ctrl+Shift+I), switch to "Console" panel and post a snapshot here. Maybe some errors happened.

**Comment by vtwang** [comment]
Vimium C does not work on pages of other PDR URLS, only on local PDFs (`file:///`). URL on the address bar is unchanged (https://www.nature.com/articles/ng.3390.pdf?origin=ppub)

![image](https://user-images.githubusercontent.com/29390846/92953084-14edf200-f42f-11ea-802b-b6618dc33866.png)


![image](https://user-images.githubusercontent.com/29390846/92952912-c4769480-f42e-11ea-84c6-6351ceb23636.png)

**Comment by gdh1995** [comment]
well, this is indeed a strange bug.&nbsp;i'll look at it in days.


the stange point is the localStorage should not be null...



---Original---

**Comment by gdh1995** [comment]
As a working around, please open the options panel of PDF Viewer for Vimium C, and turn off the last option named "
Prefer keeping URLs in the address bar unchanged". This option is to make this extension work better with Zotero, so if you don't use it then it will have no impact to turn off it.

![image](https://user-images.githubusercontent.com/5547703/92983412-c6476300-f4d5-11ea-8230-87df407e5505.png)

**Comment by gdh1995** [comment]
Um please try this version of PDF Viewer for Vimium C: [dist-2.7.22.zip](https://github.com/gdh1995/vimium-c/files/5212073/dist-2.7.22.zip) when "Prefer keeping URLs unchanged" is turned on (aka. enabled).

How to test it: https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package

**Comment by vtwang** [comment]
I tested version 2.7.22 and it doesn't fix the problem. Even though I have "Prefer keeping URLs unchanged" enabled, the URL is different.

Original URL: https://www.nature.com/articles/ng.3390.pdf?origin=ppub
Actual URL: chrome-extension://jdhjdiafclggchhlblinipaodhegahlp/https://www.nature.com/articles/s41467-020-18363-2.pdf

![image](https://user-images.githubusercontent.com/29390846/93002705-cb70d600-f506-11ea-82c7-99f794fea64e.png)


![image](https://user-images.githubusercontent.com/29390846/93002668-8fd60c00-f506-11ea-9fe8-af42a41c3c5e.png)

**Comment by gdh1995** [comment]
as for Vimium C not working, according to the snapshot you need to allow it on Vimium C options first.



About the URL changing: I'm not sure why, so I need more tests.



---Original---

**Comment by gdh1995** [comment]
Please unzip this attachment, replace the `pdfHandler.js` in the above zip file, and then reload the PDF Viewer for Vimium C extension. [pdfHandler-fixed.zip](https://github.com/gdh1995/vimium-c/files/5213690/pdfHandler-fixed.zip)

According to your snapshot, the unzipped extension has a new extension ID of `jdhjdiafclggchhlblinipaodhegahlp`, so you need to open Vimium C Options page, go to the bottom, find `Allow list of other extension IDs`, add this ID to the list, click `Save Options` and then reload the PDF tab.

**Comment by vtwang** [comment]
I followed your instructions and now everything works! I can use vimium-c to navigate the PDF with `j`/`k`/`f` 
Thank you for looking into this.

**Comment by gdh1995** [comment]
Hello, a new version of PDF Viewer for Vimium C has been released, so you may switch back to the web store version.
