### ISSUE TITLE
newTab可以调用Infinity的页面吗？

### ISSUE THREAD

**Issue by housegold** [gdh1995/vimium-c#223]
使用问题，但是直接用Infinity会焦点地址栏，infinity已连接。

可以在helper里面调用Infinity的页面吗，或者修改Infinity的代码。

**Comment by gdh1995** [comment]
聚焦到地址栏的时候，你url填的是什么？

"infinity已连接"是什么意思？

我确实改过一版 infinity 的代码，能让 vimium c 跑起来

**Comment by housegold** [comment]
Vimium c 连接上infinity了，但是地址栏会自动聚焦。
想用Helper连接infinity的，url填chrome-extension://dbfmnekepjoapopniengjbcpnbljalfg/index.html
还没实现。

**Comment by gdh1995** [comment]
new tab adapter 里可以选择让地址栏不自动聚焦啊

**Comment by housegold** [comment]
Helper连接infinity成功了。
但是infinity面板里的按钮不能选择。gf也没有用。

**Comment by gdh1995** [comment]
呃好吧，这个不是我理解的“连接”。官方版infinity和我没关系，所以自然不支持用vimium c的快捷键，你要自己改造它的html文件才行。

自己改造的步骤：https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions

或者用我改好的（适合chrome商店版Vimium C）：
[Infinity-7.3.22_0.zip](https://github.com/gdh1995/vimium-c/files/5243700/Infinity-7.3.22_0.zip)

**Comment by housegold** [comment]
1、最后一个z会显示，都输入是没反应。
2、配置：
     用于定位链接和按钮的序号字符:sadewcgqz

**Comment by gdh1995** [comment]
“最后一个z会显示”是说什么？

**Comment by housegold** [comment]
会提示输入z按键，但是好像有时不响应。
感觉和自定义序号有关系，只定义了左手的按键。

**Comment by gdh1995** [comment]
你是说触发`LinkHints.activate***`命令进入提示模式后，显示的序号里有“`Z`”这个字符，但是你按下”`Z`“的时候没有点击对应按钮？是的话，请在出现这个问题的时候截图，我需要参考所有显示的序号和右下角的提示条的内容等信息，能给出现问题的页面网址最好。

**Comment by gdh1995** [comment]
没啥新问题的话，我先关issue了，有问题的话再reopen吧。

**Comment by housegold** [comment]
1、油猴脚本“视频网html5播放小工具”的快捷键看视频很方便。
2、但是“播放下一集”的快捷键是“n”，和vimc的搜索功能重复。
3、现在把脚本的“视频下一集”修改为按键s。
4、可以映射组合键，到“下一集”的按键吗。如：<ga>映射为<s>。

**Comment by housegold** [comment]
4、可以映射组合键，到“下一集”的按键吗。如：映射"ga"为"s"。

**Comment by gdh1995** [comment]
Vimium C 不能调用其它扩展的功能，它里边的映射只能在扩展内部生效。

**Comment by housegold** [comment]
西瓜视频查看回复的链接，有时没有提示。

**Comment by housegold** [comment]
![image](https://user-images.githubusercontent.com/342557/95669362-9792da00-0bb2-11eb-8725-5a5073a70f64.png)

**Comment by gdh1995** [comment]
目前不支持自行指定哪些页面元素可以点，不过正打算这几个月做这个新功能。

**Comment by housegold** [comment]
https://www.douyin.com/
抖音的下一页快捷键怎么设置？没有文字。

**Comment by gdh1995** [comment]
@housegold  这个是 `goNext` 命令的事情，可以往 `“下一页”的关键词` 里添加一个 `.xgplayer-playswitch-next` ，注意要用逗号隔开。

**Comment by housegold** [comment]
完美，谢谢。

**Comment by gdh1995** [comment]
> 目前不支持自行指定哪些页面元素可以点，不过正打算这几个月做这个新功能。

补充一下，这个功能已经做了： https://github.com/gdh1995/vimium-c/wiki/Add-or-remove-hints#zh

**Comment by housegold** [comment]
新功能，已经用上了。

右键快进视频，怎么加前缀数字呀？
run ss #key=%27%2C39%2CArrowRight+(de)-de

**Comment by housegold** [comment]
map <a-1> Vomnibar.activateTabs
可以直接显示标签编号吗？重按<alt>按键可以显示，但是有点麻烦。

**Comment by housegold22** [comment]
map F LinkHints.activateOpenInNewTab
请问怎么能每次都在，当前页面右边的第一个标签页打开？
就是不要添加到队列最后，添加到队列第一个。

**Comment by gdh1995** [comment]
> 添加到队列最后

这个是走默认的浏览器处理“鼠标点击”的逻辑。

> 添加到队列第一个

可以倒是可以，但副作用是可能和一些网页自己写的JS代码冲突，导致部分时候模拟点击没反应。

方法是绑定快捷键的时候添加参数：
```
map f LinkHints.activate newtab="force-mode"
```

**Comment by housegold22** [comment]
b站f键点击，右边的列表《接下来播放》没有反应。
关闭了其他扩展，页面打开后前几次可以跳转，几次之后就没反应，鼠标点击可以跳转。

**Comment by gdh1995** [comment]
我好像查过，B站页面写得有问题不兼容。我再看看怎么改

**Comment by gdh1995** [comment]
@housegold 右侧推荐视频里，标题其实会有 2 个可点击对象，需要注意选择偏右侧的那个，比如下图画红圈的。

![image](https://github.com/gdh1995/vimium-c/assets/5547703/5ab0eda6-75d6-4dd2-92f3-d8b15b5117d4)

在 Chromium 系的浏览器里，如果页面刚加载好就按 f，可能遇到每个标题只显示 1 个提示块的情况，这时候按 Tab，或者等一会 esc 掉再按 f，都能显示出来第 2 个提示块。一般来说页面加载完等 1~2s 就能显示 2 个提示块了。

在 Firefox 里，应该随时都能显示 2 个提示块。

如果你开了哪个插件后，始终只能看到 1 个提示块，麻烦把有冲突的插件名字和版本告诉我，我看看能不能兼容。

**Comment by frostwd** [comment]
> 呃好吧，这个不是我理解的“连接”。官方版infinity和我没关系，所以自然不支持用vimium c的快捷键，你要自己改造它的html文件才行。
> 
> 自己改造的步骤：https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions
> 
> 或者用我改好的（适合chrome商店版Vimium C）： [Infinity-7.3.22_0.zip](https://github.com/gdh1995/vimium-c/files/5243700/Infinity-7.3.22_0.zip) （用法：https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package ）

这个扩展用不了，还有新的吗？
![image](https://github.com/gdh1995/vimium-c/assets/138142526/f9125068-a1bc-4ebd-93ce-213a803e26d1)

**Comment by gdh1995** [comment]
这只是一个warning，其实还能用。


如果想改到新版mv3的话，我试过很不好用，首先要目标插件支持，其次必须同时锁死目标插件和Vimium C的版本才能注入。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月29日(周四) 晚上11:48
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [gdh1995/vimium-c] newTab可以调用Infinity的页面吗？ (#223)




  
呃好吧，这个不是我理解的“连接”。官方版infinity和我没关系，所以自然不支持用vimium c的快捷键，你要自己改造它的html文件才行。
 
自己改造的步骤：https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions
 
或者用我改好的（适合chrome商店版Vimium C）： Infinity-7.3.22_0.zip （用法：https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package ）
  
这个扩展用不了，还有新的吗？
