### ISSUE TITLE
[Question] Open Vomnibar without showing browse history

### ISSUE THREAD

**Issue by ivanddm** [gdh1995/vimium-c#224]
Hi there,

Is there a way or mode to activate the Vomnibar without showing the browse history list? That is if I press `o`, I just want the the simple Vomnibar input box to appear and not the history (the list will populate only once I start typing).

**Comment by gdh1995** [comment]
Um, no, there' not. Why do you want this? By default, it lists closed tabs when query is empty, and this is the only way to list closed tabs .

**Comment by ivanddm** [comment]
Not for a particular reason actually, just being picky here, and that's why I'm not really requesting this as I understand probably most users including yourself, prefer the current UI. I am probably used to the look of traditional Vimium and Surfingkeys. I just prefer a minimalistic look when I open the Vomnibar and get results only when I start typing. That's all. But don't worry about it. 

I've been using your extension for the last couple of days testing your new `LinkHints.activateModeToSelect` command , and I'm really enjoying it and everything seems to be working quite find.

Thanks again for this!

**Comment by gdh1995** [comment]
Hello, here's a version supporting a special trick for this issue: [vimium_c-1.85.2-chrome-7da3617.zip](https://github.com/gdh1995/vimium-c/files/5256085/vimium_c-1.85.2-chrome-7da3617.zip).

Usage: add such CSS text to "Custom CSS for Vimium C UI":
``` css
/*#omni*/
.no-query#list { height: 0 !important }
```

Then when query is empty, the list's height is always 0 pixels, so that you won't see it ^_^

**Comment by ivanddm** [comment]
Excellent! I just tried it out, and it is just what I wanted. Thanks a lot for this!

I'm closing this issue then. Take care my friend!
