### ISSUE TITLE
PDF files do not load when 'Prefer keeping URLs in the address bar unchanged' is set to true

### ISSUE THREAD

**Issue by RyanPersson** [gdh1995/vimium-c#225]
In my browser (Chrome Version 85.0.4183.121), PDFs fail to load when the option 'Prefer keeping URLs in the address bar unchanged' is set to true.
Here is a screen capture of a pdf failing to load, as well as the console output when this occurs.
![image](https://user-images.githubusercontent.com/33065214/94291812-eed94f00-ff10-11ea-82c7-5aa4f7bd81a8.png)

If I then set "Prefer keeping URLs in the address bar unchanged" to false & reload the page, the pdf loads & the console error is solved. 
Here is a screencapture of the same page as before after toggling the option to false & reloading the page.
![image](https://user-images.githubusercontent.com/33065214/94292031-424b9d00-ff11-11ea-8af6-64e73ed6f530.png)

**Comment by RyanPersson** [comment]
Apologies, I just realized I accidentally posted this issue on the wrong extension.
This issue is with "PDF Viewer for Vimium C", Not "Vimium C"

**Comment by gdh1995** [comment]
Hello, this project does accept issues about "PDF Viewer for Vimium C", so feel free to put your problems here.

I'll take a look at this crash in days.

The main part of PDF Viewer is from https://github.com/mozilla/pdf.js/, and the new option you mentioned above is made by myself, so it may require more feedbacks before it runs prefectly.

**Comment by gdh1995** [comment]
Have you tested on a fresh user-data folder of Chrome? I can not reproduce this when opening http://mutuslab.cs.uwindsor.ca/schurko/introphyschem/handouts/mathsht.pdf on Chrome 84.0.4147.105 (x64, Win10). You may test Chrome easily using `chrome.exe --user-data-dir=%TMP%\gud`.

**Comment by RyanPersson** [comment]
Okay, I tried reproducing it using a fresh user-data folder. 

I was initially unable to reproduce it, but by testing different parts of my config, I was able to reproduce it with a fresh user-data when the chrome setting "Block third party cookies" is set to true.

![image](https://user-images.githubusercontent.com/33065214/94375991-75865b80-00cc-11eb-8f94-a3636af64433.png)

Here is the same console error, on Chrome 85.0.4183.121 (Official Build) (64-bit), with only Vimium C + PDF Viewer for Vimium C installed, third party cookies disabled, & 'Prefer keeping URLs in the address bar unchanged' set to true.

**Comment by RyanPersson** [comment]
I am guessing that third party cookies are necessary for the PDF viewer to keep the same url, rather than changing the URL to something like this: `chrome-extension://nacjakoppgmdcpemlfnfegmlhipddanj/http://*.pdf`, as it does when the option  'Prefer keeping URLs in the address bar unchanged' is enabled.

If that is the case, is it possible to either have that setting automatically toggle off when third party cookies are disabled, OR display some user message when a PDF fails to load in this way, telling them they can resolve it by changing the setting?

**Comment by gdh1995** [comment]
Seems I can work around it using try/catch, just like a similar issue before on Brave. I'll try it later.


BTW, maybe this is a bug of chrome, since they once promised no limits on normal websites would be applied on extension iframes, in an issue of Chromium about CSP limiting scripts.



---Original---

**Comment by gdh1995** [comment]
Hello, I've published a new version of "PDF Viewer for Vimium C". Does it work now?

**Comment by RyanPersson** [comment]
Yes, the issue seems to be resolved!
It is now working with `Prefer keeping URLs in the address bar unchanged : True` & Third party cookies disabled.
Thanks for your work & an awesome extension!
