### ISSUE TITLE
被 The Great Suspender 插件挂起的页面 nextTab and previousTab 不起作用

### ISSUE THREAD

**Issue by vritser** [gdh1995/vimium-c#226]
Chrome version: 85.0.4183.121
Vimium version: 1.86.0

PS: 像插件的 option 页面、Chrome 的 extension 页面 vimium 貌似都无法控制

**Comment by gdh1995** [comment]
去 chrome://extensions/shortcuts 里配置全局快捷键就行了



---原始邮件---
发件人: "vritser"<notifications@github.com&gt;
发送时间: 2020年9月26日(周六) 晚上6:42
收件人: "gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [gdh1995/vimium-c] 被 The Great Suspender 插件挂起的页面 nextTab and previousTab 不起作用 (#226)

**Comment by gdh1995** [comment]
chrome自己的页面里确实无法控制，权限不足，不只是vimium c，实际上其它扩展也没法控制。其它扩展的options页面上 vimium c也没权限去控制它们。能做的就是用全局快捷键，这个不管当前页面是什么都会生效，大部分标签页相关的命令都能在被全局快捷键触发时正常执行任务。可以参考 https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box

**Comment by vritser** [comment]
了解了，感谢答复
