### ISSUE TITLE
Using `map <c-i> toggleSwitchTemp` results in `unknown option name ""`

### ISSUE THREAD

**Issue by infokiller** [gdh1995/vimium-c#227]
I wanted to map `<C-i>` to temporarily disable the extension (like I can do from the icon with "Disable once"), but after I use the mapping `map <c-i> toggleSwitchTemp` and press `<C-i>` I get the message `unknown option name ""`.

**Comment by gdh1995** [comment]
`toggleSwitchTemp` is used to change some options, so for what you want, there's another command named `enterInsertMode`, and insert mode supports pressing `<esc>` to exit itself.

Or if you want a more complete way to "disable once", which will be just like the "Disable once" button, then you can use `map <c-i> openUrl url="vimium://status\u0020toggle\u0020^\u0020<c-i>". And here's the document of this usage: https://github.com/gdh1995/vimium-c/wiki/Enable-or-Disable-all-frames-by-a-shortcut

**Comment by infokiller** [comment]
Thanks a lot for this great project and the quick response, and sorry I missed that wiki page.
I tried using `map <c-i> openUrl url="vimium://status\u0020toggle\u0020^\u0020<c-i>"` and it works _almost_ like I want but has one issue: if I'm on a URL where I defined excluded keys, `toggle` goes from being enabled to disabled, but I can't go back to it being partially enabled. Ideally toggling would go from partially enabled to disabled, then back to partially enabled. Is there a way to do what I want?
Thanks!

**Comment by gdh1995** [comment]
Um, there's no URL format to do so. I'll add one in a few weeks or months.



---Original---

**Comment by gdh1995** [comment]
as a work around, you may map another key to open 'vimium://status reset', and then you can press two keys to let vimium c reset its status.



---Original---

**Comment by infokiller** [comment]
Thanks a lot! I've opened https://github.com/gdh1995/vimium-c/issues/229 and will close this issue.
