### ISSUE TITLE
[Feature Request] Filtered Hints

### ISSUE THREAD

**Issue by sunnypp** [gdh1995/vimium-c#23]
I read from Vimium's Wiki about Filtered Hints:

> On the options page, you can choose to use filtered hints instead of alphabet hints. With filtered hints, the labels beside each clickable thing consist of digits. However, instead of typing those digits, you can also type the link text itself. Vimium excludes links which do not match the text you have typed. And when just one link is left, it is activated.

Somehow I like the idea of knowing what to type to navigate to a link in advance.  I wonder if this is implemented or can be put onto the TODO list?

**Comment by gdh1995** [comment]
Um, the only thing blocking me from implementing filtered hints is that this work is so complicated and hard. Since I have no much rest time, this feature will take me at least one month to migrate and more time to fix new conflicts and edge cases.

Well, I'll put it onto the TODO list, and you may use it before Chrome 72. ○|￣|_

**Comment by agzam** [comment]
This I believe is the only major feature that still holds me back from leaving Vimium "classic".

**Comment by pdoak** [comment]
Has this been implemented yet?

**Comment by gdh1995** [comment]
Um, it will arrive in about the end of this year - currently the work has not begun.

**Comment by pdoak** [comment]
That sounds promising. Thank you.

**Comment by gdh1995** [comment]
Hello everyone, here's an alpha version of "Filtered Hints": 
[vimium_c-1.79.0-chrome-aabcd53.zip](https://github.com/gdh1995/vimium-c/files/3917127/vimium_c-1.79.0-chrome-aabcd53.zip)
[vimium_c-1.79.0-fx-aabcd53.zip](https://github.com/gdh1995/vimium-c/files/3917128/vimium_c-1.79.0-fx-aabcd53.zip)

**Comment by gdh1995** [comment]
Hello, Vimium c v1.79.1 has been released on Chrome Web Store and Firefox Add-ons, and you may have a try then.

It adds support for LinkHints across same-origin frames, and the Filtered Hint mode.

**Comment by MushiTheMoshi** [comment]
is there a way to switch between filtered and normal keys on the go? just like alt+f does ...

**Comment by gdh1995** [comment]
> is there a way to switch between filtered and normal keys on the go? just like alt+f does ...

`Ctrl+F2` or `Meta+F2` in LinkHints mode; in normal mode you may use `map ... toggleSwitchTemp key="filterLinkHints"` .

If you don't like `Ctrl+F2`, you may use `mapKey` to change it. For example, `mapKey <f6:l> <c-f2>` will make `F6` work as `Ctrl+F2` only in LinkHints mode. https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout#pre-mode-mapkey

**Comment by MushiTheMoshi** [comment]
Thanks a lot for your fast response!

**Comment by blasterpistol** [comment]
Is it possible to keep an alphabet mode on `f` and bind a filtered mode on some other key?

**Comment by gdh1995** [comment]
@blasterpistol  You may write: `map gf LinkHints.activate useFilter` .
