### ISSUE TITLE
右下角显示 Vimium C 已暂停 如何关闭

### ISSUE THREAD

**Issue by ugirc** [gdh1995/vimium-c#231]
我的系统是ubuntu20.04 中文

这里 Vimium C 已暂停 应该等价于 insert mode，不过我想知道能不能关掉这个提示？

![image](https://user-images.githubusercontent.com/46078304/95014670-f3250b00-067a-11eb-91cb-8f8fc3802e5c.png)

**Comment by gdh1995** [comment]
vimium c设置，高级选项，勾上“在暂停识别快捷键时隐藏右下角提示框”，保存，然后再试试。

**Comment by ugirc** [comment]
> vimium c设置，高级选项，勾上“在暂停识别快捷键时隐藏右下角提示框”，保存，然后再试试。

可以了，谢谢！
