### ISSUE TITLE
fuzzy matching?

### ISSUE THREAD

**Issue by tami5** [gdh1995/vimium-c#232]
Hi there, I'm super used to fzf and other fuzzy search matching and I wonder if there is an option to enable in order make O o fuzzy?. 9 time of 10 I wold write gitvimiumc instead of git vimium-c  in order to open vimium github repo.

Thanks

**Comment by gdh1995** [comment]
No, currently there's not.

Closed because this is a duplicate of #169.

**Comment by tami5** [comment]
Thanks, Hope this one feature be available someday 


Sent from Yahoo Mail for iPhone


On Tuesday, October 6, 2020, 11:32 AM, Dahan Gong <notifications@github.com> wrote:




No, currently there's not.

Closed because this is a duplicate of #169.
