### ISSUE TITLE
Is there a way to access vimium api

### ISSUE THREAD

**Issue by tami5** [gdh1995/vimium-c#236]
Hi there, I'm thinking of developing a plugin that will integrate with vimium-c, I wonder if its even possible to communicate with, retrieve and execute command with vimium-c from vim or shell

Thanks

**Comment by gdh1995** [comment]
do you mean to call Vimium C's commands from JS code of another web extension ?



---Original---

**Comment by tami5** [comment]
Yes, but more specifically from shell or vim, which is external to the web browser

**Comment by gdh1995** [comment]
Yes there's one API for other extensions to call Vimium's commands. For example, the below will make Vimium C run Caret mode.
``` javascript
chrome.runtime.sendMessage('hfjbmagddngcpeloejdejnfgbamkjaeg', {
    handler: "command",
    command: "enterVisualMode",
    count: 1,
    options: { mode: "caret" }
})
```

The `command` and `options` keys are just like those configured in `map <xxx> cmd ...` rules.

**Comment by tami5** [comment]
> Yes there's one API for other extensions to call Vimium's commands. For example, the below will make Vimium C run Caret mode.

But it can't be used for example in shell script?

**Comment by gdh1995** [comment]
No, unless you write another web extension to receive messages from shell scripts and forward them to Vimium C.
