### ISSUE TITLE
Question: is it possible to switch focus when there are multiple scrollable regions?

### ISSUE THREAD

**Issue by infokiller** [gdh1995/vimium-c#237]
Some pages have multiple scrollable regions, for example a menu and a main page ([example](https://developers.google.com/sheets/api/guides/concepts)).
In these cases, when you scroll the page with vimium-c, only one of the regions will be scrolled, and you need to manually click with the mouse on the other region in order to be able to scroll it.
There's the `gf` keybinding to switch to another iframe. Is there a similar command to switch the focus of the scrolling commands?

Thanks!

**Comment by gdh1995** [comment]
Try this:press `f` and select a dark-red mark, or trigger `LinkHints.activateModeToHover` and select any mark.

**Comment by infokiller** [comment]
Thanks! `LinkHints.activateModeToHover` works for me. Ideally, I'd be able to use a keybinding to navigate between these regions (like `gi` and `gf`), but I think this should work well enough for now.
