### ISSUE TITLE
Can't exclude keybindings with multiple keys (like `gi`)

### ISSUE THREAD

**Issue by infokiller** [gdh1995/vimium-c#238]
When I try to exclude keybindings with multiple keys and then click save, they are overwritten with single chars. For example, here is how it looks before I save:

![image](https://user-images.githubusercontent.com/10516814/95823427-47dd1b80-0d36-11eb-8d6d-18e897145ba2.png)

And then after I save:

![image](https://user-images.githubusercontent.com/10516814/95823439-4c093900-0d36-11eb-985b-787548c75ee2.png)

**Comment by gdh1995** [comment]
Yes, this is working as intended.

**Comment by infokiller** [comment]
So there is no way to exclude `gi` without excluding `gs` (or any other shortcut starting with `g`)? or exclude `gi` without excluding `i`?

**Comment by gdh1995** [comment]
Yes, no way to exclude `gi` without affecting `gs`; but `g` is enough to exclude `gi`, when keeping `i` working as expected.

**Comment by infokiller** [comment]
Does it make sense to support excluding `gi` without excluding `gs`?
I would expect that if the user presses `g`, vimium-c will swallow the key and wait for the next one. If the next char is `i`, vimium-c will interpret it as the command for `gi`, but if the next char is `s`, it needs to pass `gs` to the page.
Is the issue that vimium can't pass `gs` to the page in this case?

**Comment by gdh1995** [comment]
Vimium C, and other extensions, can not "swallow a key and pass it to pages in a while", which is a basic limitation rule of browsers.

Currently it can only dispatch "simulated" keys, but such keys are very very different from browsers' native key events.

**Comment by infokiller** [comment]
Thanks for the explanation, I actually ran into this issue with my another complementary extension I'm working on ([Web Search Navigator](https://github.com/infokiller/web-search-navigator)), but wasn't able to verify if an extension can simulate key presses for the page or not. I guess the answer is no.
