### ISSUE TITLE
[Feature Request]  Extensions on "chrome://" URLs

### ISSUE THREAD

**Issue by JimMoen** [gdh1995/vimium-c#239]
Chrome and Chromium now support a flag "chrome://flags/#extensions-on-chrome-urls". 
![extension](https://user-images.githubusercontent.com/32241529/95827337-2d229b00-0d66-11eb-8b0e-2ac447d0cb6e.png)
Could Vimium-C run on the pages?

**Comment by gdh1995** [comment]
The flag is a mystery, and I can not find documents about it. I once tried for some times but always failed in making extensions work on such URLs.

BTW, according to its description, it requires a explicitly declared permission item, which may be confusing and annoying for new users.

**Comment by JimMoen** [comment]
[这个扩展声明了需要启用该选项](https://chrome.google.com/webstore/detail/chrome-plugin-dns-cache-c/bdpfccanhacmnpdiejhlgglghjmcnlmp?hl=zh-CN)

[声明地点在这里](https://github.com/Yiniau/chrome-plugin-dns-cache-clean/blob/1eede565db34f0bb8737a6686e0fbdae4c961785/manifest.json#L15)

或许这里可以使用"chrome://*"通配？

**Comment by davidhdez** [comment]
I love to use my new tab using daily.dev extension, how would I use that in combination with your addon new tab as well? thank you.

**Comment by gdh1995** [comment]
@davidhdez Hello, today I find https://app.daily.dev/?ref=landing can be used to replace its extension (although some CSS styles are different), and Vimium C can work well on the web page.

**Comment by gdh1995** [comment]
Hello. Vimium C v1.89.0 has been released on Firefox Add-ons, and being verifying by Chrome Web Store and MS Edge Add-ons. So you may take a try when it gets visible.

After `#extensions-on-chrome-urls` is enabled on `chrome://flags`, then Vimium C will auto inject to the native New Tab Page. You may turn off this injection by uncheck a new option and click "Save" on Vimium C Options:

![image](https://user-images.githubusercontent.com/5547703/113606642-de9deb80-967a-11eb-9b8a-a8f3aa948679.png)

This feature only works on Chrome's "native New Tab Page", but not those modified by browser vendors. For example, MS Edge uses `"https://ntp.msn.cn/edge/ntp?...` as its NTP, while I haven't found a way to make Vimium C run on it.

**Comment by gdh1995** [comment]
BTW, next versions of Vimium C will also be able to work on other `chrome://*` tabs (and also on Edge, Brave and so on). Up to 2021/4/26, the master branch has supported it.
