### ISSUE TITLE
Can I use it in CaretTab？

### ISSUE THREAD

**Issue by newdee** [gdh1995/vimium-c#24]
I use the CaretTab as my new tab, but in my new tab ,  I cannot use vimium, until opening other tabs.

**Comment by gdh1995** [comment]
Sorry, but as I said in https://github.com/gdh1995/vimium-c/issues/20#issuecomment-423015015,  Vimium C can only run on modified versions of other extensions.

If you're interested in doing by yourself, here's a tutorial: https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions

**Comment by gdh1995** [comment]
BTW, could you speak Chinese? Then we may talk in it.

**Comment by newdee** [comment]
当然，全世界都是中国人～


主要有两个问题，vim插件确实好用，不过每次打开新标签页的时候，都会自动跳到地址栏。另外新标签页程序我用的carettab，可以自己定制，但是没有快捷键设置，而且vim插件也没法在里面用。所以想看看有没有办法在空白页或者新标签页使用vimium，另一个看看能不能隐藏地址栏。后者是以前chrome的一个compact navigation实验特性，现在已经没有了。前者目前也没找到方法～

**Comment by gdh1995** [comment]
我这个就是针对”自动聚焦地址栏“来做的，办法是这个插件接管了newtab页，然后newtab页里用js额外打开配置的真实的新标签页，再自动关掉自己。

我用Windows，所以平时Ctrl+T的快捷键我都不怎么用，直接在Vimium C里绑定 Alt+T 到 createTab就可以（更快、更省资源地）直接打开指定页面了。

**Comment by gdh1995** [comment]
你可以改carettab的html，引入Vimium C的lib/injector.js，然后manifest里改CSP放行Vimium C的js文件，就能引入Vimium C 了。参考 https://github.com/gdh1995/vimium-c/tree/master/weidu 的index.html和manifest.json

**Comment by newdee** [comment]
好！我回头试试，非常感谢～

**Comment by gdh1995** [comment]
Any problems?

**Comment by newdee** [comment]
> Any problems?

非常抱歉，最近时间忙的焦头烂额，我会抽空弄，这个issue我先关了吧，之后有问题我重新开
