### ISSUE TITLE
Is it possible to use vimium-c in online pdf page?

### ISSUE THREAD

**Issue by ugirc** [gdh1995/vimium-c#242]
[http://cs231n.stanford.edu/slides/2017/cs231n_2017_lecture2.pdf](http://cs231n.stanford.edu/slides/2017/cs231n_2017_lecture2.pdf)

![image](https://user-images.githubusercontent.com/46078304/97081333-567bda80-1634-11eb-9bf5-ea82279b364f.png)

can I use `j k` to scroll the page in pdf?

**Comment by gdh1995** [comment]
You may try "PDF Viewer for Vimium C": a modified version of the extension [PDF Viewer](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm) from [PDF.js](https://github.com/mozilla/pdf.js/)
* [Visit PDF Viewer for Vimium C on Chrome Web Store](https://chrome.google.com/webstore/detail/pdf-viewer-for-vimium-c/nacjakoppgmdcpemlfnfegmlhipddanj)

**Comment by ugirc** [comment]
> You may try "PDF Viewer for Vimium C": a modified version of the extension [PDF Viewer](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm) from [PDF.js](https://github.com/mozilla/pdf.js/)
> 
> * [Visit PDF Viewer for Vimium C on Chrome Web Store](https://chrome.google.com/webstore/detail/pdf-viewer-for-vimium-c/nacjakoppgmdcpemlfnfegmlhipddanj)

Thank you, it works !
