### ISSUE TITLE
同一页面多个上一页、下一页，希望能选择某一个

### ISSUE THREAD

**Issue by rockcor** [gdh1995/vimium-c#243]
很喜欢这个插件，感谢作者

**Comment by gdh1995** [comment]
这么做选择的话实现起来太麻烦了，建议直接用 F 键触发 LinkHints 来选择按钮。

或者等到下一版本 goNext 将会支持按标签页网址识别下一页，可以在“处理剪贴板文字”这个配置里指定相应识别规则

**Comment by rockcor** [comment]
我的想法是1]]（页面中第一个下一页）、2]]（页面中第二个下一页）这样，类似于选择文本框的 数字+gi，这样好实现吗

**Comment by gdh1995** [comment]
太麻烦了，建议换个思路：

下一页关键词里，支持填入css选择器（需要以`.#[`开头），也就是说你能让goNext优先选择任意一个按钮。

**Comment by rockcor** [comment]
我的应用场景是使用同一页面中多个下一个按钮，每个都有可能用到，这样不是固定一个了吗

**Comment by gdh1995** [comment]
好吧，还是建议直接用 F 键触发 LinkHints 来选择按钮。

回头我给linkhints加一个“只显示特定CSS选择器的按钮”的功能吧。

**Comment by rockcor** [comment]
好的，就这样吧，作者辛苦了

**Comment by gdh1995** [comment]
新版 v1.87.0 在chrome商店和firefox商店都发布了， map的时候带上参数 "match=..."就行，比如：
```
map f LinkHints.activate match="a,button"
```

**Comment by rockcor** [comment]
还有edge商店也发布下，麻烦了XD

**Comment by rockcor** [comment]
有edge商店也发布下，麻烦了XD

**Comment by gdh1995** [comment]
在等反馈bug，这周内发布

**Comment by gdh1995** [comment]
你好，v1.87.2 今天已经在edge store上发布了
