### ISSUE TITLE
Omnibar feature should be as feature complete as the Vomnibar

### ISSUE THREAD

**Issue by wis** [gdh1995/vimium-c#244]
I commented out the key mappings I have for `Vomnibar.activateEditUrlInNewTab`, `Vomnibar.activate`, `Vomnibar.activateInNewTab`, and `Vomnibar.activateTabSelection` to force myself to start using the Omnibar feature yesterday, I found it faster, much faster to open and show up (faster than inserting an iframe and rendering/updating it to to show suggestions), I'm sure it's also less resource intensive.

Instead of using the key mappings I commented out, I use the `Ctrl+L` shortcut to jump to the address bar and type v to replace the highlighted URL, and use search engines I have in Vimium, if I want to open the search query in a new tab I hold `Alt` when I press enter.

But it's not clear from the search suggestions text what the _type_ of results are, I'm never sure what's gonna happen when I hit enter on a highlighted search suggestion, open/navigate to that URL or jump to existing tab.

one annoying thing I find is that when I come back to the tab I used the Omnibar feature in, when I press key mappings keys like `j` to scroll down, Chromium still has the address bar focused, not the web page, so instead of scrolling the '`j`' is inserted in the address bar, I don't think anything can be done in the extension to fix this (steal focus from address bar to the web page, when coming back to tab that made Omnibar query), do you? 

Edit: I searched the issues and read their comments, so I now know about `:t` and `:b` and use them.
I think I may have an answer to the question above, it's doable, you do it in your other extension NewTab Adapter, it even works for new tab URLs that are have the `chrome://` or `chrome-extension://` schema!, _How does it work_? I couldn't find out by reading NewTab Adapter's source code, is it uglified? and is it open-source (googled for a repo, didn't find an), if not will you open-source it? ...I just tested Vimium C, it works the same.. when it opens new tabs, the address bar is not focused.

**Comment by gdh1995** [comment]
Thanks for this feedback.

>  it's not clear from the search suggestions text what the type of results are

Oh it does lack some info, I'll add some hints.

> steal focus from address bar to the web page

An extension can not do so, because there's no browser API for it. Someone has filed an issue for Firefox, but it's very old and lacks recent activities: https://bugzilla.mozilla.org/show_bug.cgi?id=1341416.

> NewTab Adapter

No, it can not move focus. It just create a tab with given URL, so the focus is set on content page by your browser, while no methods can keep a current page as is and move focus from address bar to the page.

The source code is at https://github.com/gdh1995/vimium-c-helpers.

**Comment by gdh1995** [comment]
> it's not clear from the search suggestions text what the type of results are

Hello, I've made some changes to the shown text, and please try: [vimium_c-1.87.2-chrome-bb50d72.zip](https://github.com/gdh1995/vimium-c/files/5754307/vimium_c-1.87.2-chrome-bb50d72.zip), [vimium_c-1.87.2-firefox-bb50d72.zip](https://github.com/gdh1995/vimium-c/files/5754309/vimium_c-1.87.2-firefox-bb50d72.zip).

Usage: add ` type-letter ` to the `"styles"` field of the "Vomnibar settings" textbox, on Vimium C Options page, and then search on omnibox with `v ...`.

Wiki about .zip files: https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package .

**Comment by gdh1995** [comment]
Hello, v1.88.0 has been released on Firefox and Chrome extension stores, and you may add ` type-letter` to the `"styles"` field (note: words should be wrapped with space characters).

**Comment by wis** [comment]
Now it's clear which suggestion result is a current open tab and which is history, thank you. :clap: 

Two more things, in the Vomnibar can show you the last n active tabs of currently open tabs, when you type `:t` in the Omnibar the results are tabs with "t" in their title, not the last n active tabs.
Also the Vomnibar opens new tab next to the current tab, I've found that holding alt and pressing enter opens the tab at the end of all tabs of current window, sometimes even in another window, not the current window.

**Comment by gdh1995** [comment]
> when you type `:t` in the Omnibar the results are tabs with "t" in their title, not the last n active tabs

It's a feature, and I just added a description for it: the "How to switch what to search in when keep Vomnibar showing?" question in https://github.com/gdh1995/vimium-c/wiki/How-to-...-on-Vomnibar .

> holding alt and pressing enter

If only Alt key is down, then Vomnibar should usually open URL in new-foreground tab. But, if you're selecting a suggestion for a recently-closed tab session, then Vomnibar will always resume the closed tab - Chrome will decide where to resume it, including another window or a new window.

Alt is used to auto complete `"www." + query + ".com"`, when: no suggestion is being selected (highlighted) (then open the query directly), and your query matches the RegExp of `/^\w+(-\w+)?$/)`. A special case is, when there's a known domain suggestion, then Vomnibar will prefer the domain to "www.*.com".

**Comment by Zeioth** [comment]
Something I've noticed about vomnibar on firefox is that pressing ESC won't close it. Not a big deal.

**Comment by gdh1995** [comment]
@Zeioth Usually it's because another iframe of your current tab has grabbed keyboard focus back, and a clue is that Vomnibar will be transparent if it loses focus.

If you find <kbd>Escape</kbd> does nothing when Vomnibar has keyboard focus, please check whether you're selecting some characters in the input bar, because Vomnibar will prefer cancelling selection in query words to exiting.

If your're not in such situations, then it may be a new bug.
