### ISSUE TITLE
<a-xx>不工作

### ISSUE THREAD

**Issue by zhangaz1** [gdh1995/vimium-c#246]
* macos
* f正常工作
* F正常工作
* <a-f>不工作(测试发现所有alt组合键都不工作)
* 用edge和chrome测试结果一样

用键盘测试Opt(alt)按键正常

难道是组合键冲突?能通过配置把command映射为alt?

**Comment by gdh1995** [comment]
macOS拦截了alt+字母的组合键，会变成输入某种特殊字符，所以vimium-c捕捉不到这种。建议换组合键，或者手动map对应的特殊字符到命令，或者找找怎么去系统设置里关



---原始邮件---
发件人: "zhangaz1"<notifications@github.com&gt;
发送时间: 2020年11月9日(周一) 上午10:05
收件人: "gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [gdh1995/vimium-c] <a-xx&gt;不工作 (#246)




 
macos
 
f正常工作
 
F正常工作
 
不工作(测试发现所有alt组合键都不工作)
 
用edge和chrome测试结果一样
 
用键盘测试Opt(alt)按键正常
 
难道是组合键冲突?能通过配置把command映射为alt?

**Comment by gdh1995** [comment]
想测试Alt+字母对应的特殊字符的话，可以查系统设置，也可以去 http://gitee.gdh1995.cn/vimium-c/keyboard-test.html 实际测测

**Comment by zhangaz1** [comment]
谢谢回复,已经重新map到其他键了

unmap <a-n>
map zn performAnotherFind

unmap <a-p>
map zp togglePinTab

可以用了

**Comment by gdh1995** [comment]
这是一次测试结果：
<img width="646" alt="alt_key_test_20210103211220" src="https://user-images.githubusercontent.com/5547703/103479423-771c9980-4e08-11eb-87b5-72252e4b9f7b.png">

所以按Alt的时候确实是被 macOS 转成了别的字母，如果你 map 的时候也是用的相应字母，应该也是能触发的。
