### ISSUE TITLE
feature request: simulate mouse double click action on selected-words in visual-mode? which will be very useful in translation

### ISSUE THREAD

**Issue by saleo** [gdh1995/vimium-c#247]
amazing plugin , thanks a ton.

**Comment by gdh1995** [comment]
&nbsp;Sorry, it seems I misunderstood this issue.
do you mean you have another extension and it recognizes double click to show a translation card?



---Original---

**Comment by gdh1995** [comment]
no, there's no brower API to show a contextmenu.



---Original---

**Comment by gdh1995** [comment]
well, let's discuss about the top requirement: do ypu have another extension which show a popup dialog on double click, or just want to click the "translate" item in the right-click context menu?
If the first one, then maybe Vimium C can simulate the behavior and trigger the same actions; if the second, then there's no browser API to do so.



---Original---

**Comment by saleo** [comment]
It's the first one: the saladict.  And could you please tell me how to simulate the below action, thanks in advance.

> With mouse, select the words and double click to popup the translation.

Ps, the translation extension i used is :

[沙拉查词\-聚合词典划词翻译 \- Chrome 网上应用店](https://chrome.google.com/webstore/detail/%E6%B2%99%E6%8B%89%E6%9F%A5%E8%AF%8D-%E8%81%9A%E5%90%88%E8%AF%8D%E5%85%B8%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91/cdonnmffkdaoajfknoeeecmchibpmkmg)

**Comment by gdh1995** [comment]
我在沙拉查词写了个issue (https://github.com/crimx/ext-saladict/issues/1155)，大概会添加一个全局快捷键 (见`chrome://extensions/shortcuts`) 来负责在页面内对选中文字显示浮层，或者走Vimium C命令去给沙拉查词发消息。

I've reported this issue to Saladict, and now the response is, Saladict's author may add a browser-level shortcut (configured on `chrome://extensions/shortcuts`) to show the float panel, or add code to accept messages from other extensions.

If the second way comes true, then this mapping will help (replace the `<xxxx>` below with what key you want):
```
map <xxxx> sendToExtension id="saladict@crimx.com" raw data={"type":"SALADICT_SEARCH_SELECTION"}
```

BTW, the `saladict@crimx.com` is the ID of Saladict's Firefox version, and you may need to use a real ID installed in your browser.

**Comment by gdh1995** [comment]
v1.88.0 已经在 Firefox、Chrome 商店里发布，微软Edge的扩展商店版还在等审核。

新版添加了命令`LinkHints.click`，只要指定 dblclick，然后在选择文字后触发这个命令，沙拉查词就会收到消息显示面板。具体设置如下：
* 添加到Vimium C 的自定义快捷键：
```
# 把 Ctrl+Shift+F 绑定到“双击”命令，并且在 VisualMode 下也生效
mapkey <c-s-f> <v-f3>
map <v-f3> LinkHints.click dblclick
```
* 启用沙拉查词设置页面“查词习惯”一栏的双击查词：
![image](https://user-images.githubusercontent.com/5547703/103513159-011a4000-4ea5-11eb-9c1f-4af62b0144e4.png)
* 然后选择一段文字，按 Ctrl+Shift+F 试试吧。


注：如果把 `<c-s-f>` 换成 `<c-f:v>`，则快捷键变成 Ctrl+F，且只会在 VisualMode 下生效，不影响其他状态。

**Comment by saleo** [comment]
谢谢，棒极了！thx, awesome

**Comment by yuyang0** [comment]
@gdh1995 请教下，这个模拟双击是怎么实现？扩展的代码看半天没找到相关代码

**Comment by gdh1995** [comment]
@yuyang0 你是要看具体代码怎么实现下边这个命令的吗？
```
mapkey <c-s-f> <v-f3>
map <v-f3> LinkHints.click dblclick
```

1. 命令名字是`LinkHints.click`，定义在 `background/key_mappings.ts`，等价于 `kFgCmd.linkHints` + 参数 `{ direct: true, m: HintMode.DEFAULT }`
2. `kFgCmd.linkHints` 在 `content/commands.ts` 里定义为 `linkActivate` (从 `content/link_hints.ts` 导入的 `activate`)
3. `content/link_hints.ts#activate` 遇到 `options.direct` 会转入 `activateDirectly`
4. `activateDirectly` 执行 `findAnElement_` 寻找可点击元素
- 1. 在 `direct` 不是字符串的时候会处理成 `"em,sel,f,h"`（以后会改成更复杂的，默认值由 `options.match` 决定）
- 2. `element` 意思是找 `options.match` 这个 CSS 选择器匹配上的元素，没指定 `.match` 的时候就跳过
- 3. `selected` 意思是找当前选择的文字
5. `activateDirectly` 执行闭包里的 `next_`，最终执行 `coreHints.e`（也就是 `content/link_actions.ts` 的 `executeHintInOfficer`）来执行点击操作
6. `executeHintInOfficer` 在 `mode1_` (来自 `options.mode` 和 `options.m`) 是 `HintMode.DEFAULT` 时，对普通元素节点执行 `defaultClick`
7. `defaultClick` 检查到 `options.dblclick` 是 `true`，所以调用 `click_async` 时传入 `kClickAction.BaseMayInteract + 1`
8. `click_async` 计算 `result: ActionType` 得到 `ActionType.dblClick`，于是在第一次 `mouse_(element, CLK, ...)` 后
- 1. 执行第二次 `click_async` 并传入 `kClickButton.primaryAndTwice`，模拟第二次点击
- 2. 再执行 `mouse_(element, "dblclick", ...)` 模拟双击事件
