### ISSUE TITLE
External configuration loading

### ISSUE THREAD

**Issue by akemrir** [gdh1995/vimium-c#248]
Is there option to load configuration without user interaction?
I am preparing live usb for my self and I want to load custom css with bash script.

**Comment by gdh1995** [comment]
&nbsp;No, and it's almost impossible to do it.
&nbsp;
But there's another way to run a live usb: run your browser with a specified folder which has a well-configured Vimium C.



---Original---

**Comment by akemrir** [comment]
Ah, right. Run firefox with profile from command line, modify config and use prepared profile.
I'll check this out.

**Comment by akemrir** [comment]
It worked, thanks for suggestion.
