### ISSUE TITLE
When searching using the HUD, the HUD loses focus after every character

### ISSUE THREAD

**Issue by YorickPeterse** [gdh1995/vimium-c#251]
Version: Vimium C 1.87.0, Firefox 84, Linux.

Settings:  [vimium_c-20201123_143954.json.txt](https://github.com/gdh1995/vimium-c/files/5583310/vimium_c-20201123_143954.json.txt)

When searching by pressing `/`, the search HUD shows up. Earlier today I noticed that every time I type a character, the HUD loses focus. I'm pretty sure this wasn't happening before the weekend. To work around this, after every character pressed you need to select the HUD input box again.

If any more information is necessary, please let me know!

**Comment by gdh1995** [comment]
Is it reproducible on all pages, including Vimium C Options?

**Comment by gdh1995** [comment]
It seems your customized UI CSS causes it? Could you test the case of deleting it?

**Comment by YorickPeterse** [comment]
> Is it reproducible on all pages, including Vimium C Options?

Yes, it happens everywhere; including the Vimium C options page.

**Comment by gdh1995** [comment]
Confirmed. It's a bug of compilation process. I'll fix it in hours and publish a new version (maybe wait a while for #250)

**Comment by gdh1995** [comment]
Hello, v1.87.1 has bee released on Firefox Add-ons and you may take a try.

**Comment by YorickPeterse** [comment]
I upgraded to 1.87.1 and it works. Thanks a lot!
