### ISSUE TITLE
是否可以获取chrome内置页面翻译的操作？

### ISSUE THREAD

**Issue by zz5678** [gdh1995/vimium-c#252]
![image](https://user-images.githubusercontent.com/67672527/100376454-83b01400-304a-11eb-8056-c4bfc46beffa.png)

Google 一直不肯给出快捷键或者其他方式操作这个 chrome 内置功能，很笨拙而且经常出问题，不过偶然测试，发现可能是内置 js ，并可能被 vimium 获取，不知是否可以取出

**Comment by gdh1995** [comment]
“并可能被 vimium 获取”这个是从何得知的？这是一个“翻译”组件私有的弹出网页啊，按说vimium不能在这个弹出框里执行js。

印象中扩展程序的接口里应该没有接口操作它，我去看看文档确认一下。

**Comment by zz5678** [comment]
![image](https://user-images.githubusercontent.com/67672527/100513909-9b52de00-31ab-11eb-8697-cc0bc5e1aa38.png)
又看了几遍，可能是和这个混了。

BTW，支持反垄断Google！！ 净搞私有，要加个 deepl 的翻译接口都没戏
