### ISSUE TITLE
suggestion: mention case-sensitive in search-engine manual

### ISSUE THREAD

**Issue by saleo** [gdh1995/vimium-c#253]

**Comment by gdh1995** [comment]
By default, Vomnibar does case-insensitive search if all characters of input text is lower-case, while case-sesitive search if any character is upper-case. This behavior is the same with Vimium.

If you always want to use case-insensitive search, you may add an option of "icase" to `Vomnibar.activate*` in custom key mappings. For example:
```
map o Vomnibar.activate icase
```

**Comment by saleo** [comment]
great, thanks
