### ISSUE TITLE
Where have "gi" gone?

### ISSUE THREAD

**Issue by afilp** [gdh1995/vimium-c#254]
I missing the "gi" option to focus on the 1st input of the page. Is it now implemented with different keystrokes?

Thanks!

**Comment by gdh1995** [comment]
What's your browser and system? On my computer `gi` works.

**Comment by afilp** [comment]
Chrome Version 86.0.4240.198 (Official Build) (64-bit) and Windows 10, but I see that this is not an option in `vimium-c` help either:

![image](https://user-images.githubusercontent.com/7850073/100454624-f1e5ec80-30c5-11eb-9430-5d0132da3653.png)

Shouldn't I see a `g i` option there? Do I have an old version maybe or something?

**Comment by gdh1995** [comment]
Yes, `g` will replace all `g***`.

**Comment by afilp** [comment]
Thanks, so how can I go to 1st input now? 

I have a vimium-c version that opens vomnibar when clicking `g`. What should I do next?

Thanks!

**Comment by gdh1995** [comment]
You may map another key sequence to the command of `focusInput`, in "Custom key mappings" on Vimium C Options page.

And the syntax looks like: `map keySequences focusInput`

**Comment by afilp** [comment]
Thanks! 

Do you plan to add a dedicated key (or sequence) on this feature? (so that users do not have to do this themselves, if they manage to find how to do so)

**Comment by gdh1995** [comment]
Sorry, could you explain what do you want again?

`g` will always replace all `g***`, so if you add `map g .....` to custom key mappings, then it's up to you to choose another key for `focusInput` - Vimium C can not guess what key would be suitable to replace the initial `gi`.

**Comment by gdh1995** [comment]
BTW, the initial is `gi: focusInput; o: Vomnibar`.

**Comment by gdh1995** [comment]
I'm closing this issue because it lacks responses and maybe has been solved. If you still have any questions, fell free to reopen it.
