### ISSUE TITLE
标记功能只能在当前网页生效吗？

### ISSUE THREAD

**Issue by ugirc** [gdh1995/vimium-c#255]
我在README.md中看到了这句描述
> 按 “M+字母” 创建标记，在别的网页就可以按 “`+字母” 切换到（或者打开）这个标记的网页

是否支持当在网页A作了个标记，当我在网页B按下这个标记时，立刻跳转到网页A？

**Comment by gdh1995** [comment]
标记有两种有效范围：当前域名内、全局。

这块基础用法和Vimium是一样的：
```
ma, mA  set local mark "a" (global mark "A")
`a, `A  jump to local mark "a" (global mark "A")
``      jump back to the position before the previous jump
          -- that is, before the previous gg, G, n, N, / or `a
```

https://github.com/philc/vimium/wiki/Tips-and-Tricks#swapping-global-and-local-marks

**Comment by ugirc** [comment]
谢谢，很棒的功能！

**Comment by ugirc** [comment]
> 标记有两种有效范围：当前域名内、全局。
> 
> 这块基础用法和Vimium是一样的：
> 
> ```
> ma, mA  set local mark "a" (global mark "A")
> `a, `A  jump to local mark "a" (global mark "A")
> ``      jump back to the position before the previous jump
>           -- that is, before the previous gg, G, n, N, / or `a
> ```
> 
> https://github.com/philc/vimium/wiki/Tips-and-Tricks#swapping-global-and-local-marks

我可以下vimium一样修改全局和局部的大小写吗？如果可以要用什么命令
map X Marks.activateCreateMode swap
map Y Marks.activateGotoMode swap

![图片](https://user-images.githubusercontent.com/46078304/100743929-f38e1800-3417-11eb-927e-4eee8314778a.png)

**Comment by gdh1995** [comment]
哦goto模式直接用 `Marks.activate` 这个名字吧。

之前没注意，下次更新我再把activateGotoMode加回来

**Comment by ugirc** [comment]
> 哦goto模式直接用 `Marks.activate` 这个名字吧。
> 
> 之前没注意，下次更新我再把activateGotoMode加回来

![图片](https://user-images.githubusercontent.com/46078304/100746270-7664a200-341b-11eb-942c-f3483e25ac52.png)

我试了但是好像并没有效果，小写字母还是局部的
