### ISSUE TITLE
Simmulation of browser hotkeys

### ISSUE THREAD

**Issue by ViOrise** [gdh1995/vimium-c#256]
Can we simulate browser hotkeys by using vimium? Some keys, such C-b in browser are difficult to comfort use.

**Comment by gdh1995** [comment]
Vimum C can open `chrome://***` URLs, but there's no API to click browser buttons or trigger any browser shortcuts.

**Comment by gdh1995** [comment]
You may use system-level key mapping tools, like AutoHotKey on Windows and Karabiner on macOS.
