### ISSUE TITLE
Link kept focus after opening link in a background tab

### ISSUE THREAD

**Issue by casprwang** [gdh1995/vimium-c#257]
Hi there, thanks for this great work.

One small nick pick: after opening a link in a background tab, the cursor is still acting like it is focused on the link.

![2020-12-03 12 50 56](https://user-images.githubusercontent.com/19645990/101087111-a3719b80-3566-11eb-98f0-8db8e813517b.gif)

IMHO, the hovering behavior looks unnecessary, especially when a link comes with floating windows.

If this is not a feature, maybe dispatch a following 'unhover' event?

**Comment by gdh1995** [comment]
Will an <kbd>Escape</kbd> be enough to make the card hide?

If not, you can add an option of `autoUnhover` to `LinkHints` commands: for example, `map f LinkHints.activate autoUnhover`.

**Comment by casprwang** [comment]
<kbd>Esc</kbd>didn't work(see subtitle in GIF), but the option works like a charm. Thanks!
