### ISSUE TITLE
Incorrect number of page search results with diacritic letters

### ISSUE THREAD

**Issue by maxigaz** [gdh1995/vimium-c#260]
When there are diacritic and non-diacritic variants of the same letter on a page (for example, “e” and “é”) and I search for something that includes such a letter, Vimium C v1.87.2 under Firefox v83.0 only partially tells the difference between these variants.

For instance, when I go to [this page](https://hu.wikisource.org/wiki/A_magyar_helyes%C3%ADr%C3%A1s_szab%C3%A1lyai/A_tulajdonnevek_%C3%ADr%C3%A1sa) and search for `tér`, Vimium C says 25 matches are found. If I search for `ter`, Vimium C displays 28 as the number of matches. However, pressing the keys `n` or `N` steps through matches of both `tér` and `ter`, which means the actual number should be 53.

If I use a regular expression by typing in `/tér\r` and `/ter\r`, in both cases Vimium C tells occurances of “tér” and “ter” apart, and the displayed number is also correct.

**Comment by gdh1995** [comment]
This is because `n` makes your browser do search, while the `25` / `23` is got using Vimium C's JavaScript:
* both Chrome and Firefox will do some letter tricks to let `e` match both an `é` and a plain `e`
* but in JavaScript there's no easy way (that I currently know) to do it

Maybe I can add a step of replacing non-English letters to English ones before counting.

BTW, on my Win 10 + Firefox 83.0, `/ter\r` can not match `tér`, and the `n` command also skips it.

**Comment by maxigaz** [comment]
> BTW, on my Win 10 + Firefox 83.0, /ter\r can not match tér, and the n command also skips it.

Yes, that's what I meant.

**Comment by gdh1995** [comment]
Hello, v1.88.0 has been released, and if you add `normalize` to mappings of `enterFindMode***`, then FindMode will try to treating some non-English letters as English ones. It will affect both page text and your query.

For example: `map / enterFindMode postOnEsc normalize`.

**Comment by maxigaz** [comment]
I’ve just tried this new version. When I use the setting `map / enterFindMode postOnEsc normalize`, the displayed number of results is consistent.

However, I can’t use queries like `/tér\r` to specifically search for “tér” or words with diacritic letters in them anymore. At first, this query will show the message “No matches” and nothing will be highlighted, and then pressing `n` will cycle through matches for `/ter` and `/tér` (without using a regular expression).

**Comment by gdh1995** [comment]
Well, it's indeed a bug.

Here's a working around: wait for about 6 seconds before typing a next character, so that it won't use a normalized version in its text cache.

A better working around is to map another key to `enterFindMode` without "normalize"

**Comment by gdh1995** [comment]
Hello, v1.88.1 has been released on Firefox Add-ons, and the regexp mode should work now.

**Comment by maxigaz** [comment]
I can confirm it works. Thank you very much for your work!
