### ISSUE TITLE
create new tab不能定位到新tab的问题

### ISSUE THREAD

**Issue by Ryziii** [gdh1995/vimium-c#261]
在Chrome内核版的Edge中出现的问题，使用create new tab回打开新标签但是无法定位到新建的标签。

在自定义快捷键中 `map T Vomnibar.activateInNewTab`,
按`T`输入文本会在新建标签页使用默认搜索输入文本，但是无法定位到新建标签页.
我使用此map在Chrome中使用会定位到新tab

原版vimium在Edge中使用也有此bug

**Comment by gdh1995** [comment]
是说没有自动切换到新标签页吗？这两个命令都始终出现这个问题，还是，偶尔出现？



---原始邮件---
发件人: "Ryziii"<notifications@github.com&gt;
发送时间: 2020年12月17日(周四) 凌晨1:47
收件人: "gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [gdh1995/vimium-c] create new tab不能定位到新tab的问题 (#261)




 
在Chrome内核版的Edge中出现的问题，使用create new tab回打开新标签但是无法定位到新建的标签。
 
在自定义快捷键中 map T Vomnibar.activateInNewTab,
 按T输入文本会在新建标签页使用默认搜索输入文本，但是无法定位到新建标签页.
 我使用此map在Chrome中使用会定位到新tab
 
原版vimium在Edge中使用也有此bug

**Comment by Ryziii** [comment]
是的。**Edge无法**自动切换到新标签，但是Chrome可以自动切换到新标签。
搞了两张图更直观的说明问题。

Edge如下：
https://i.imgur.com/O6MELoE.gif

Chrome如下：
https://i.imgur.com/oPaVdrw.gif

> 图片太大了只能用链接展示了

**Comment by gdh1995** [comment]
测试一下：
1. 设置 `map T Vomnibar.activateInNewTab newtab`
2. 按`T`，输入`g test`（需要`g`是一个自定义搜索引擎的关键词），然后连续按 3 次空格键来触发 Vomnibar 打开搜索结果
3. 看看在哪边打开

**Comment by Ryziii** [comment]
我的Edge版本是87.0.664.60，未做任何flag改动。
最新进展：今天此bug无法复现了...非常抱歉

另外问一下 `map T Vomnibar.activateInNewTab`后使用 `T` 与原版vimium的逻辑不同，`T` 后就会有十个历史输入，这个可以关吗。

vimium：
![image](https://user-images.githubusercontent.com/20976649/102462034-4278b600-4084-11eb-8157-85e92632af19.png)
![image](https://user-images.githubusercontent.com/20976649/102462440-be72fe00-4084-11eb-9e44-8dc54c3bb1cd.png)

vimium-c：
![image](https://user-images.githubusercontent.com/20976649/102462426-ba46e080-4084-11eb-943f-e2904c9518cc.png)

**Comment by gdh1995** [comment]
可以自定义css来隐藏：

``` css
/*#omni*/
.no-query#list { height: 0 !important }
```

不过这10个不是普通的“历史记录”，而是优先显示“可以恢复的”最近关闭的标签页，从这儿按回车恢复的标签页会保留一部分输入框内容、前进后退历史等信息。

**Comment by Ryziii** [comment]
了解了，是最近关闭的十个tab。因为我使用Vomnibar.activateInNewTab的频率极高，从vimium转到vimium-c后感到从按下 `T` 到唤出tab速度变慢很多，所以想有可能是这”最近关闭的十个tab“的问题。
感谢大大耐心解答。

**Comment by gdh1995** [comment]
呃速度差距这么明显吗？不过自定义css只是隐藏，实际上还是会向浏览器查最近关闭的tabs并渲染。

我回头查查为什么慢吧，没法加速的话就只能再加一个选项来真的把这一步跳过去。

目前Vomnibar有几种不同的加载速度：
1. 最慢的是浏览器启动后，在所有页面上都没用过Vomnibar或者omnibox的`v`关键词，第一次使用Vomnibar相关功能
2. 速度稍慢的是 在某一个页面上第一次按`T`显示Vomnibar
3. 最快的是在某个曾经显示过Vomnibar的页面上再按 `T`

这是因为要加载的东西不一样。方便的话请问你感觉上，实际使用中上述哪几个比 Vimium 的 Vomnibar 慢？

**Comment by Ryziii** [comment]
1. 没测
2. vimium与vimium-c一样都会有点慢
3. vimium明显秒开的感觉，vimium-c会慢一点点，给我的感觉就有一点点卡的感觉

上述是我纯主观的的使用体验，没有截屏逐帧去读秒对比速度。
如果对速度的影响是查“最近关闭tab”并渲染这个功能带来的那能出一个选项关闭最好了。
