### ISSUE TITLE
F键进入select框是，再次按F会失效

### ISSUE THREAD

**Issue by SmallTeddy** [gdh1995/vimium-c#262]
如题，有时F进入select框时，再次按F不显示提示，看下这个能否解决

**Comment by gdh1995** [comment]
没法解决。点击 `<select>` 后Vimium C进入文字输入模式，设计上就是这样；按<kbd>esc</kbd>会回到普通模式并且取消select元素的焦点。

原因是，这个状态下如果想按 F 会有歧义。因为下拉列表本身是支持用键盘选择条目的，比如假如是 foo、bar两个，那按 f 就选择 foo，按 b 选择 bar，所以Vimium C选择了放弃自己的快捷键模式，而是进文字输入模式，来保留 select 的完整功能。

另外，本来`F`应该让它弹出下拉列表的， 但浏览器（从几年前就）限制了没法用扩展来显示`<select>`的下拉列表，只能靠用户真的去按空格键或者鼠标点击。

**Comment by SmallTeddy** [comment]
谢谢你的回复   我了解了   十分感谢   这依旧是我google使用过的最好的插件  甚至超越油猴
