### ISSUE TITLE
feature request: Vomnibar active in new window

### ISSUE THREAD

**Issue by casprwang** [gdh1995/vimium-c#263]
Something like `Vomnibar.activateInNewWindow`. Also, It would be awesome to have a macro for opening a Vomnibar selection in a new window(`cmd/ctrl+shift+enter`?)

Many thanks!

**Comment by gdh1995** [comment]
Accepted. I'll add it but recently I have little rest time - maybe it won't arrive until the further v1.88, in about one month.

**Comment by casprwang** [comment]
Thank you! And of course, please take care of yourself first.

**Comment by gdh1995** [comment]
Hello, v1.88.0 has been released, and if you add `clickLike="chrome"` to mappings of `Vomnibar.activate***`, then `Ctrl/Alt/Shift` will work like Chrome itself deals with your click. So <kbd>Shift+Enter</kbd> will open in a new window.

**Comment by casprwang** [comment]
hmm, it seems `map o LinkHints.activate clickLike="chrome"` opens a new tab for me, not a window. 

```
map t Vomnibar.activateInNewTab
map h previousTab
map l nextTab
map gq removeTab
map Q restoreTab
unmap W
map W moveTabToNewWindow
map gj closeDownloadBar
map f LinkHints.activate autoUnhover
map o LinkHints.activate clickLike="chrome"
```

**Comment by gdh1995** [comment]
Try this: hold on Shift and select a hint marker.


because chrome use shift+click to open on a new window.



---Original---

**Comment by casprwang** [comment]
no luck... there a gif with keys presses 

![2021-01-04 10 34 07](https://user-images.githubusercontent.com/19645990/103567451-b4b90b00-4e78-11eb-957b-02d31418d6f0.gif)

**Comment by gdh1995** [comment]
Well. My last comment has a typo, and it should be `map o Vomnibar.activate clickLike="chrome"`.

`LinkHints` currently doesn't support switch to new-window mode by Ctrl/Shift/Alt, but you can use a special mapping with `newtab="window"` option to make hint markers do so.

**Comment by casprwang** [comment]
Ah, I see. It works now 👍
