### ISSUE TITLE
goToRoot功能失效了。

### ISSUE THREAD

**Issue by Git0503** [gdh1995/vimium-c#266]
goToRoot功能失效了。

**Comment by gdh1995** [comment]
v1.78.2 吗？测试了chrome 87下正常

**Comment by Git0503** [comment]
1.87.2，也是Chrome




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月28日(星期一) 晚上11:52
收件人:&nbsp;"gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送:&nbsp;"0620"<745458417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gdh1995/vimium-c] goToRoot功能失效了。 (#266)





 
v1.78.2 吗？测试了chrome 87下正常

**Comment by Git0503** [comment]
1.87.2，也是Chrome


从上个版本开始就有这个问题了，不知道因为什么


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月28日(星期一) 晚上11:52
收件人:&nbsp;"gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送:&nbsp;"0620"<745458417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gdh1995/vimium-c] goToRoot功能失效了。 (#266)





 
v1.78.2 吗？测试了chrome 87下正常

**Comment by gdh1995** [comment]
你是不是别的按键和goToRoot的快捷键冲突了，比如map了`g`，会导致所有默认的`g`开头的快捷键都被忽略，包括`gU`

**Comment by Git0503** [comment]
下面是我的自定义快捷键，应该没冲突的吧

有冲突不是都有提示的吗

unmapall

map&nbsp;,&nbsp;closeTabsOnLeft

map&nbsp;.&nbsp;closeTabsOnRight

map&nbsp;j&nbsp;LinkHints.activateModeToHover

map&nbsp;k&nbsp;previousTab

map&nbsp;l&nbsp;nextTab

map&nbsp;z&nbsp;Vomnibar.activateInNewTab

map&nbsp;r&nbsp;reloadTab

map&nbsp;d&nbsp;autoOpen

map&nbsp;c&nbsp;autoCopy

map&nbsp;h&nbsp;restoreGivenTab

map&nbsp;w&nbsp;closeOtherTabs

map&nbsp;q&nbsp;LinkHints.activateModeToDownloadImage

&nbsp;

map&nbsp;v&nbsp;visitPreviousTab

map&nbsp;a&nbsp;LinkHints.activateModeToOpenInNewTab

map&nbsp;n&nbsp;LinkHints.activateModeToOpenInNewForegroundTab

map&nbsp;b&nbsp;Vomnibar.activateBookmarksInNewTab

map&nbsp;f&nbsp;LinkHints.activate

map&nbsp;o&nbsp;Vomnibar.activate

map&nbsp;x&nbsp;removeTab

map&nbsp;u&nbsp;LinkHints.activateModeToCopyLinkUrl&nbsp;#复制链接

map&nbsp;t&nbsp;openCopiedUrlInCurrentTab&nbsp;#在当前标签页打开复制的链接

map&nbsp;et&nbsp;LinkHints.activateModeToOpenVomnibar&nbsp;#编辑链接文字

map&nbsp;eu&nbsp;Vomnibar.activateUrl&nbsp;#编辑链接

map&nbsp;if&nbsp;performFind

&nbsp;

map&nbsp;yq&nbsp;firstTab

map&nbsp;yh&nbsp;lastTab

map&nbsp;yw&nbsp;moveTabToIncognito

map&nbsp;yb&nbsp;Vomnibar.activateBookmarks&nbsp;#搜索收藏夹并在当前标签页打开

map&nbsp;yl&nbsp;Vomnibar.activateHistory&nbsp;#搜索历史记录并在当前标签页打开

map&nbsp;yy&nbsp;copyCurrentUrl

map&nbsp;yt&nbsp;LinkHints.activateModeToCopyLinkText

map&nbsp;yr&nbsp;restoreTab&nbsp;#恢复最近关闭网页

map&nbsp;yp&nbsp;goUp&nbsp;#当前网站的上一层

map&nbsp;ys&nbsp;goToRoot

&nbsp;

map&nbsp;gs&nbsp;searchInAnother&nbsp;keyword="google"

map&nbsp;gh&nbsp;goBack&nbsp;#后退

map&nbsp;gq&nbsp;goForward&nbsp;#前进

map&nbsp;gn&nbsp;goNext&nbsp;#下一页

map&nbsp;gp&nbsp;goPrevious&nbsp;#上一页

map&nbsp;gc&nbsp;scrollToBottom

map&nbsp;gd&nbsp;scrollToTop

map&nbsp;gv&nbsp;debugBackground

&nbsp;

map&nbsp;yi&nbsp;openUrl&nbsp;url=

map&nbsp;yd&nbsp;openUrl&nbsp;url

map&nbsp;yf&nbsp;openUrl&nbsp;url=

map&nbsp;yj&nbsp;openUrl&nbsp;url=

map&nbsp;in&nbsp;openUrl&nbsp;url=

map&nbsp;ma&nbsp;openUrl&nbsp;url

map&nbsp;sh&nbsp;openUrl&nbsp;url

map&nbsp;mu&nbsp;openUrl&nbsp;url

map&nbsp;ed&nbsp;openUrl&nbsp;url

map&nbsp;ym&nbsp;openUrl&nbsp;url

map&nbsp;yo&nbsp;openUrl&nbsp;url

map&nbsp;pa&nbsp;openUrl&nbsp;url

map&nbsp;go&nbsp;openUrl&nbsp;urlrd%"





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月28日(星期一) 晚上11:56
收件人:&nbsp;"gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送:&nbsp;"0620"<745458417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gdh1995/vimium-c] goToRoot功能失效了。 (#266)





 
你是不是别的按键和goToRoot的快捷键冲突了，比如map了g，会导致所有默认的g开头的快捷键都被忽略，包括gU

**Comment by gdh1995** [comment]
自定义快捷键之间冲突会提示，如果和默认快捷键冲突了，直接丢弃默认快捷键

**Comment by Git0503** [comment]
那我这是什么原因呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 凌晨0:12
收件人:&nbsp;"gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送:&nbsp;"0620"<745458417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gdh1995/vimium-c] goToRoot功能失效了。 (#266)





 
自定义快捷键之间冲突会提示，如果和默认快捷键冲突了，直接丢弃默认快捷键

**Comment by gdh1995** [comment]
我用你这套试了试没问题啊，在当前网页（https://github.com/gdh1995/vimium-c/issues/266）上按`ys`能跳到GitHub首页。

你的“处理剪贴板文字”设置项填了什么

**Comment by Git0503** [comment]
p@^https://item.m.jd.com/product/(\d+).html\b@https://item.jd.com/$1.html@


这不是我设置的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 凌晨0:15
收件人:&nbsp;"gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送:&nbsp;"0620"<745458417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gdh1995/vimium-c] goToRoot功能失效了。 (#266)





 
我用你这套试了试没问题啊，在当前网页（https://github.com/gdh1995/vimium-c/issues/266）上按`ys`能跳到GitHub首页。
 
你的“处理剪贴板文字”设置项填了什么

**Comment by gdh1995** [comment]
你在哪个网页没法触发你的 ys 快捷键？当时是在文本框里吗？

**Comment by Git0503** [comment]
在QQ浏览器上可以，在Chrome上就是不行，ChromeAPP模式和无痕模式也都不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 凌晨0:15
收件人:&nbsp;"gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送:&nbsp;"0620"<745458417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gdh1995/vimium-c] goToRoot功能失效了。 (#266)





 
我用你这套试了试没问题啊，在当前网页（https://github.com/gdh1995/vimium-c/issues/266）上按`ys`能跳到GitHub首页。
 
你的“处理剪贴板文字”设置项填了什么

**Comment by Git0503** [comment]
哪个都不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 凌晨0:19
收件人:&nbsp;"gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送:&nbsp;"0620"<745458417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gdh1995/vimium-c] goToRoot功能失效了。 (#266)





 
你在哪个网页没法触发你的 ys 快捷键？当时是在文本框里吗？

**Comment by gdh1995** [comment]
所有网页吗？把其它扩展程序都禁用掉，然后打开（或刷新）file:///C:/xxxxx 某个文件夹，再按 ys 试试

**Comment by gdh1995** [comment]
如果你的Vimium C配置里没有敏感信息的话，可以用Vimium C设置页面右下角的“导出配置”按钮得到一个json，传上来，这样我就能在我的测试浏览器里完全复现你的配置了。

**Comment by Git0503** [comment]
有可能是插件的原因，Chrome很奇怪，同样的插件在QQ浏览器正常，在Chrome总是不断出问题，另外全部关闭插件再一个个地打开很麻烦诶，所以我不太想测试，有没有好用的插件管理工具推荐，因为不是全部打开，有些插件暂时用不到，现有的插件又只能全部打开或全部关闭




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 下午4:16
收件人:&nbsp;"gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送:&nbsp;"0620"<745458417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gdh1995/vimium-c] goToRoot功能失效了。 (#266)





 
如果你的Vimium C配置里没有敏感信息的话，可以用Vimium C设置页面右下角的“导出配置”按钮得到一个json，传上来，这样我就能在我的测试浏览器里完全复现你的配置了。

**Comment by gdh1995** [comment]
呃那部分测试的办法是，在 Vimium C 设置页面里 按 ys，看右下角显示不显示“An extension has no upper-level pages”。如果有的话，至少 goToRoot 命令已经正常触发了，顶多是后续计算root URL的时候出问题了。

我用的扩展程序不多，没试过这类插件管理工具。你可以先用 Snipaste 对着扩展管理页面截图，贴到屏幕上来记住哪些插件打开着，回头恢复起来就能对照着弄了。

**Comment by Git0503** [comment]
在设置页面试了，没有触发，其他命令是可以正常触发的，只有这个goToRoot 命令没有




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 下午4:34
收件人:&nbsp;"gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送:&nbsp;"0620"<745458417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gdh1995/vimium-c] goToRoot功能失效了。 (#266)





 
呃那部分测试的办法是，在 Vimium C 设置页面里 按 ys，看右下角显示不显示“An extension has no upper-level pages”。如果有的话，至少 goToRoot 命令已经正常触发了，顶多是后续计算root URL的时候出问题了。
 
我用的扩展程序不多，没试过这类插件管理工具。你可以先用 Snipaste 对着扩展管理页面截图，贴到屏幕上来记住哪些插件打开着，回头恢复起来就能对照着弄了。

**Comment by gdh1995** [comment]
网站例外规则 里设置了 `y` 吗？

在浏览器里调试 Vimium C 的方法如下图：
![image](https://user-images.githubusercontent.com/5547703/103271905-71811700-49f6-11eb-94ea-ad7202dab0fd.png)

先打开 `chrome://extensions/`，启用右上角的“开发者模式”，找到 Vimium C 点击“背景页”，然后在弹出的窗口里点击”Console“，就能看有没有什么报错信息了（上图里的那两条信息是刚安装Vimium C时一般都会有的提示，不属于报错）。

在 Vimium C 设置页面 上调试的方法是，在该页面上按 Ctrl+Shift+I ，然后一般会在右侧弹一个面板出来，也是找到并点击”Console“，看下边有没有什么报错。

> 同样的插件在QQ浏览器正常

qq浏览器里你是怎么安装的Vimium C？从它自带的腾讯扩展商店的话，可能版本会比Chrome版旧，因为这个是腾讯每隔一段时间去Chrome扩展商店抓取的，不是我主动发布的。

在 Vimium C 设置页面左下角可以看到版本号。

**Comment by Git0503** [comment]
你发的图片我这里看不了，


其他带y的命令都正常，所以应该不是这个原因，QQ浏览器上也是从Chrome商店安装









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 下午4:59
收件人:&nbsp;"gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送:&nbsp;"0620"<745458417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gdh1995/vimium-c] goToRoot功能失效了。 (#266)





 
网站例外规则 里设置了 y 吗？
 
在浏览器里调试 Vimium C 的方法如下图：
 
 
先打开 chrome://extensions/，启用右上角的“开发者模式”，找到 Vimium C 点击“背景页”，然后在弹出的窗口里点击”Console“，就能看有没有什么报错信息了（上图里的那两条信息是刚安装Vimium C时一般都会有的提示，不属于报错）。
 
在 Vimium C 设置页面 上调试的方法是，在该页面上按 Ctrl+Shift+I ，然后一般会在右侧弹一个面板出来，也是找到并点击”Console“，看下边有没有什么报错。
  
同样的插件在QQ浏览器正常
  
qq浏览器里你是怎么安装的Vimium C？从它自带的腾讯扩展商店的话，可能版本会比Chrome版旧，因为这个是腾讯每隔一段时间去Chrome扩展商店抓取的，不是我主动发布的。
 
在 Vimium C 设置页面左下角可以看到版本号。

**Comment by gdh1995** [comment]
调试看看吧。

调试步骤：先打开 chrome://extensions/，启用右上角的“开发者模式”，找到 Vimium C 点击“背景页”，然后在弹出的窗口里点击”Console“，就能看有没有什么报错信息了。

在 Vimium C 设置页面 上调试的方法是，在该页面上按 Ctrl+Shift+I ，然后一般会在右侧弹一个面板出来，也是找到并点击”Console“，看下边有没有什么报错。

**Comment by Git0503** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 晚上7:05
收件人:&nbsp;"gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送:&nbsp;"0620"<745458417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gdh1995/vimium-c] goToRoot功能失效了。 (#266)





 
调试看看吧。
 
调试步骤：先打开 chrome://extensions/，启用右上角的“开发者模式”，找到 Vimium C 点击“背景页”，然后在弹出的窗口里点击”Console“，就能看有没有什么报错信息了。
 
在 Vimium C 设置页面 上调试的方法是，在该页面上按 Ctrl+Shift+I ，然后一般会在右侧弹一个面板出来，也是找到并点击”Console“，看下边有没有什么报错。

**Comment by gdh1995** [comment]
呃9分钟前这个，你回复的内容是？我只能看到引用的旧邮件的部分。

**Comment by Git0503** [comment]
你不是叫我调试看有没有提示嘛，console里一片空白




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 晚上8:12
收件人:&nbsp;"gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送:&nbsp;"0620"<745458417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gdh1995/vimium-c] goToRoot功能失效了。 (#266)





 
呃9分钟前这个，你回复的内容是？我只能看到引用的旧邮件的部分。

**Comment by gdh1995** [comment]
设置页面的console也是空白的吗？

你的键盘布局是中文或者英文吗？感觉像是 s 这个键没被认出来。

试试单独把 `s` 映射到某个命令，然后保存设置后按 `s` 看看能不能触发它。

另外可以测试：打开 http://gitee.gdh1995.cn/vimium-c/keyboard-test.html ，依次按 y 和 s，看页面上会记录什么；然后随便按几次ctrl，再单独按 s ，看记录什么

**Comment by Git0503** [comment]
这是设置里的console，能看到图片吗





这是按键测试，按键正常





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 晚上8:19
收件人:&nbsp;"gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送:&nbsp;"0620"<745458417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gdh1995/vimium-c] goToRoot功能失效了。 (#266)





 
设置页面的console也是空白的吗？
 
你的键盘布局是中文或者英文吗？感觉像是 s 这个键没被认出来。
 
试试单独把 s 映射到某个命令，然后保存设置后按 s 看看能不能触发它。
 
另外可以测试：打开 http://gitee.gdh1995.cn/vimium-c/keyboard-test.html ，依次按 y 和 s，看页面上会记录什么；然后随便按几次ctrl，再单独按 s ，看记录什么

**Comment by gdh1995** [comment]
看不到图片。方便把你的Vimium C配置文件导出成json吗，放个百度网盘或者什么网页上我去复制？

**Comment by Git0503** [comment]
json：https://ws28.cn/f/4cat1ykljbg


测试的截图：https://note.youdao.com/web/#/file/recent/note/WEB75b715a09db2f35e5b5d07ac575fef74/







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 晚上8:32
收件人:&nbsp;"gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送:&nbsp;"0620"<745458417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gdh1995/vimium-c] goToRoot功能失效了。 (#266)





 
看不到图片。方便把你的Vimium C配置文件导出成json吗，放个百度网盘或者什么网页上我去复制？

**Comment by gdh1995** [comment]
截图这个网址我没权限看不了，你可以把它分享出来，我才能看。我的有道账号也是 “ gdh1995 ”

**Comment by gdh1995** [comment]
复现出来了，谢谢！辛苦了

**Comment by Git0503** [comment]
我明明已经分享了，可能是有道变了


改用幕布：https://share.mubu.com/doc/6wWnIkIZWS




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 晚上9:09
收件人:&nbsp;"gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送:&nbsp;"0620"<745458417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gdh1995/vimium-c] goToRoot功能失效了。 (#266)





 
截图这个网址我没权限看不了，你可以把它分享出来，我才能看。我的有道账号也是 “ gdh1995 ”

**Comment by gdh1995** [comment]
确实是一个bug，在获取当前网页URL的时候，Vimium C 错误地以为自己可能在其它浏览器上，但是存放浏览器类型的地方已经被优化（精简）掉了，它找不到这个信息。

这个问题有绕过的办法：随便编个网址添加到“网站例外规则“的”“网址匹配规则”里，然后选中”监听网址中锚（hash）的变化“，保存，然后 `ys` 就会走别的路获取URL，就不会出错了。

前阵子代码里刚修复还没发布到新版本，我没注意到 v1.87.2 也有这个问题，还以为是我最近加新功能刚改出来的呢。

（我有道笔记用的不熟不确定，大概是上一个链接是你自己看的时候的链接，大概是分享的内容有专门的分享链接。）

**Comment by Git0503** [comment]
好了，谢谢。


有道云那个是我的问题，我先复制了分享链接，后来又复制页面的链接，才出现了这个问题，分享链接确实是不一样的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 晚上9:21
收件人:&nbsp;"gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送:&nbsp;"0620"<745458417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gdh1995/vimium-c] goToRoot功能失效了。 (#266)





 
确实是一个bug，在获取当前网页URL的时候，Vimium C 错误地以为自己可能在其它浏览器上，但是存放浏览器类型的地方已经被优化（精简）掉了，它找不到这个信息。
 
这个问题有绕过的办法：随便编个网址添加到“网站例外规则“的”“网址匹配规则”里，然后选中”监听网址中锚（hash）的变化“，保存，然后 ys 就会走别的路获取URL，就不会出错了。
 
前阵子代码里刚修复还没发布到新版本，我没注意到 v1.87.2 也有这个问题，还以为是我最近加新功能刚改出来的呢。
 
（我有道笔记用的不熟不确定，大概是上一个链接是你自己看的时候的链接，大概是分享的内容有专门的分享链接。）

**Comment by Git0503** [comment]
还有一个问题：removeTab命令用了一次之后，再想连续用就不起作用了，要点一下网页才行


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gdh1995/vimium-c"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 晚上9:21
收件人:&nbsp;"gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送:&nbsp;"0620"<745458417@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gdh1995/vimium-c] goToRoot功能失效了。 (#266)





 
确实是一个bug，在获取当前网页URL的时候，Vimium C 错误地以为自己可能在其它浏览器上，但是存放浏览器类型的地方已经被优化（精简）掉了，它找不到这个信息。
 
这个问题有绕过的办法：随便编个网址添加到“网站例外规则“的”“网址匹配规则”里，然后选中”监听网址中锚（hash）的变化“，保存，然后 ys 就会走别的路获取URL，就不会出错了。
 
前阵子代码里刚修复还没发布到新版本，我没注意到 v1.87.2 也有这个问题，还以为是我最近加新功能刚改出来的呢。
 
（我有道笔记用的不熟不确定，大概是上一个链接是你自己看的时候的链接，大概是分享的内容有专门的分享链接。）

**Comment by gdh1995** [comment]
那是焦点焦点不在网页上了，这时候没什么办法可以单键触发Vimium C的命令。

打开 `chrome://extensions/shortcuts`，里边可以设置（只浏览器内的）全局生效的快捷键，但是必须带上Alt、Ctrl中的至少一个键作为辅助。

比如设置“自定义快捷键 1”成 Alt+X，然后去Vimium C设置页面，添加自定义快捷键：
```
shortcut userCustomized1 command="removeTab"
```
就能稳定触发removeTab了。

====

不过，我个人习惯是，给“切换到左、右标签页”设置快捷键，遇到操作不了的情况，就切换到别的网页，然后用 reloadGivenTab、removeRightTab 来刷新或者关闭旁边的标签页。

**Comment by gdh1995** [comment]
v1.88.0 已经在 Firefox、Chrome 商店里发布，可以改回旧版例外规则，再试试了。微软Edge的扩展商店版还在等审核。
