### ISSUE TITLE
[Feature Request] use downloads.setShelfEnabled to close the Downloads Shelf

### ISSUE THREAD

**Issue by ivanddm** [gdh1995/vimium-c#267]
Hi there,

I just wanted to suggest an additional mapping that I really wish I had (and that Surfingkeys has as well).

One is to be able to **close the Downloads shelf in Chrome**. I always have to reach the mouse to close that annoying shelf. This is the shelf I'm talking about:

![image](https://user-images.githubusercontent.com/20104703/103224605-07ef0300-4939-11eb-939f-7c619e0c4725.png)

And an additional mapping related to this would be to **show the latest downloaded file in Finder** (Mac) or Explorer (Windows) AND close the shelf as well, all in one command.

Thanks in advance,

**Comment by gdh1995** [comment]
> close the Downloads shelf

Use the command `Close the bottom download bar elegantly` (`closeDownloadBar`).

![image](https://user-images.githubusercontent.com/5547703/103226359-e0af2a80-4966-11eb-8385-65d9b042c56d.png)

>  show the latest downloaded file in Finder

Extensions can not do so, because browsers don't provide such APIs.

**Comment by ivanddm** [comment]
This is really great, thanks a lot for that. I was not aware of that command already being available. I'm closing this then.

**Comment by ivanddm** [comment]
Hi again,

I have been trying this feature and although it does close the download bar, somehow the chrome window flashes (as if it closes the window and opens it back again), and many times it changes the window position on the screen. Would it be possible to make this feature less intrusive?

Thanks!

**Comment by gdh1995** [comment]
As said in https://github.com/gdh1995/vimium-c/issues/118#issuecomment-581191376:
> As far as I've found, It has been the safest way to do this.
> Um, there are some other extensions which can do so without flashing. But all of them require a a permission to control your download history, And some of them will even remove all the download history on a new file beginning to download

**Comment by ivanddm** [comment]
Sure, I understand. Perhaps you can take a look at Surfignkeys if you got the time, an extension similar to yours that has this option as well.

Thanks again!

**Comment by gdh1995** [comment]
Oh it require two new permissions (compared with Vimium C): `downloads` and `downloads.shelf` to use `chrome.downloads.setShelfEnabled`.

Vimium C won't add such permissions directly. On the contrary, I'm considering about moving some existing ones into "optional permissions", which are disabled on fresh installation and need a user to click a button to enable - this is a more clean solution.

This moving requires months, since I has no much rest time. I'll add these new permissions when I finish it.

**Comment by gdh1995** [comment]
Hello. Vimium C v1.89.1 has been released on Firefox Add-ons, MS Edge Add-ons and Chrome Web Store. So you may take a try.

Vimium C Options has a new option named "optional permissions" and you need to manually choose the related permission items and click save.

cc. to @OnceThenEver .
