### ISSUE TITLE
download images/videos binding not working in firefox

### ISSUE THREAD

**Issue by elig0n** [gdh1995/vimium-c#269]
I have bound `LinkHints.activateModeToDownloadImage` but whenever i select a hint it only shows a message but does not download anything as far as I can tell via the download manager. I'm using Firefox 84.0.1

**Comment by gdh1995** [comment]
Um, Firefox doesn't accept the signal of "downloading something" which was sent by Vimium C.

I'll add an option named `raw` to `LinkHints.activateModeToOpenImage`, and with it Vimium C will open the image URL in a new tab directly, so that you can use Ctrl+S on the tab.

**Comment by gdh1995** [comment]
Hello, Vimium C v1.88.0 has been released, and if you add an option `keyword=""` to the mapping of `LinkHints.activateModeToOpenImage`, then Vimium C will open a plain tab for an image, and then Ctrl+S will work.

For example: `map Fi LinkHints.activateModeToOpenImage keyword=`

**Comment by elig0n** [comment]
Will this work for videos too ?

**Comment by gdh1995** [comment]
Well, the inner logic is very simple so it's only suitable for public .mp4 files, but if a video requires logging-in, or has been split into multiple files, then I'm afraid it won't work.
