### ISSUE TITLE
open hint in new window

### ISSUE THREAD

**Issue by elig0n** [gdh1995/vimium-c#270]
I was looking for it but funny enough I didn't find such option among the many options

**Comment by gdh1995** [comment]
Just need to add `newtab="window"` when mapping a key sequence to `LinkHints.activate`.

**Comment by elig0n** [comment]
Thanks. Is there documentation for all those options somewhere ? I couldn't see newtab= in the help screen

**Comment by gdh1995** [comment]
Um, sadly, no documentation, but only code...

Options of some in-page commands are defined in `CmdOptions`:

https://github.com/gdh1995/vimium-c/blob/6e68dca5ca9e6f6d40be060707e88c3d6ca535d1/typings/messages.d.ts#L266-L276

Options of other commands are defined in `BgCmdOptions`:

https://github.com/gdh1995/vimium-c/blob/6e68dca5ca9e6f6d40be060707e88c3d6ca535d1/background/typed_commands.d.ts#L1-L11

As for their detailed meanings, you'll have to read the code (or search in old issues).
