### ISSUE TITLE
发现vimium c在youtube用户页面内，不支持新窗口打开网页

### ISSUE THREAD

**Issue by lyjhyjyes** [gdh1995/vimium-c#272]
https://www.youtube.com/channel/UCgjNUSBhxvFqIbgtLGxmlVA
经测试，chrome83多个版本的vimium c，设置了map Fr LinkHints.activateModeToOpenInNewForegroundTab 在新标签页中打开链接 (LinkHints.activateModeToOpenInNewForegroundTab)
youtube其他页面能用Fr打开新网页，而进入了用户页面，第一次Fr，然后选择连接，失败，必须要第二次Fr选择链接打开，十分麻烦
请问如何解决呢

**Comment by gdh1995** [comment]
“用户页面”指什么？你给的这个链接是一个频道的主页。

具体点哪一个会有问题？给点截图吧。如果所有按钮都有这个问题，也找一个始终能复现问题的按钮，截图我看看

**Comment by lyjhyjyes** [comment]
> “用户页面”指什么？你给的这个链接是一个频道的主页。
> 
> 具体点哪一个会有问题？给点截图吧。如果所有按钮都有这个问题，也找一个始终能复现问题的按钮，截图我看看

您好，今天更新1.88版本，已解决点击问题
![Uploading 000.png…]()

**Comment by gdh1995** [comment]
它自己好了？但我还不知道问题在哪，没针对这个issue改过什么。

**Comment by lyjhyjyes** [comment]
对呀，好奇怪。忽然就能在用户页内新标签页打开视频链接 发送自 Windows 10 版邮件应用 发件人: Dahan Gong发送时间: 2021年1月4日 15:30收件人: gdh1995/vimium-c抄送: lyjhyjyes; Author主题: Re: [gdh1995/vimium-c] 发现vimium c在youtube用户页面内，不支持新窗口打开网页 (#272) 它自己好了？但我还不知道问题在哪，没针对这个issue改过什么。—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by lyjhyjyes** [comment]
> 它自己好了？但我还不知道问题在哪，没针对这个issue改过什么。
您好，chrome上vimium c 1.88.0版本，youtube首页和用户页面，在新页面打开链接，又不能一次打开链接，必须第二次Fr操作才能新页面打开链接，不知为何呢。不习惯使用GitHub传图，如果没看到图片我再传一次
![00](https://user-images.githubusercontent.com/57164542/104185172-92625700-544f-11eb-900a-98ea5aa1d44c.png)

**Comment by gdh1995** [comment]
关闭其他所有扩展，然后刷新youtube网页，再试试呢？
