### ISSUE TITLE
Suggestion: mark tabs that play audio on vomnibar

### ISSUE THREAD

**Issue by elig0n** [gdh1995/vimium-c#273]
I would rather not install another add-on just to locate tabs that play music on Firefox
so maybe showing a sound symbol on the vomnibar for open tabs can help with that 
and perhaps with an option to filter such tabs via keyword (for example `audio:`)
would be useful.

**Comment by gdh1995** [comment]
Hello. Vimium C v1.89.0 has been released on Firefox Add-ons, and being verifying by Chrome Web Store and MS Edge Add-ons. So you may take a try.

Now audible tabs will get an extra label of `♬` (unmuted) and `♪` (muted):
![image](https://user-images.githubusercontent.com/5547703/113605485-4ce1ae80-9679-11eb-9bb6-292bd023568b.png)

And now valid tags to filter in tabs are: `:audio` (aka `:audible`), `:unmuted`, `:muted`, `discarded`, `:incognito` and `:pinned`. You just need to type a prefix of tags to do filtering.
