### ISSUE TITLE
find one matched word,'enter' will focus the nearby hyperlink instead of the word

### ISSUE THREAD

**Issue by saleo** [gdh1995/vimium-c#275]
eg1: 

in Vimium-c's readme page, '/consensus' and 'enter', the focus moved to the "The Constitution of the People's Republic of China " nearby

eg2:
in the page: [Robotics simulator \- Wikipedia](https://en.wikipedia.org/wiki/Robotics_simulator),  '/tenaciy' and 'enter', focus moved to hyperlink nearby as shown in the below image:

![image](https://user-images.githubusercontent.com/2926834/103603589-e9e15e00-4f49-11eb-8b8c-f35e4940f114.png)

**Comment by gdh1995** [comment]
Hello, v1.88.2 has been published, and you may take a try.

**Comment by saleo** [comment]
thanks, nice work!
