### ISSUE TITLE
how to highlight all find results ?

### ISSUE THREAD

**Issue by elig0n** [gdh1995/vimium-c#277]
When using `/` to search only one result is shown at a time requiring hitting `n` or `N` to find the number of occurrences. Is there a way to highlight all found matches a-la VIM's `:set hlsearch` ?

**Comment by gdh1995** [comment]
`FindMode`: use `<c-s-j>` / `<c-s-k>` to show rects for current visible matches, imported in commit e089a3bee0f2e0211e6c0055a4fb695d9f6de797

**Comment by elig0n** [comment]
I have 1.88.1 on Firefox and c-s-j opens the Browser Console and c-s-k does nothing.

**Comment by gdh1995** [comment]
You need to enter FindMode first.

**Comment by elig0n** [comment]
May I suggest that this should work in normal mode ?
If one wishes to see rectangles not in the current viewport he has to exit the focus of the findmode text box but even then the rectangles move inaccordingly when scrolling the page

**Comment by sky31even** [comment]
![image](https://user-images.githubusercontent.com/49628447/177930467-ec1222d1-9f92-4b6f-b425-7ef6ac0818f4.png)

I think we could make it a paremeter for find mode such as "HighlightAll", if true it will automatically highlight all matches results and use different shades to show the current focus, like the find mode of chrome as above. And everything keeps the same if it's false.

**Comment by sky31even** [comment]
btw, actually the chrome find mode is awesome now except for it doesn't work simutenously with vimium C since it captures all the focus

**Comment by gdh1995** [comment]
@elig0n Sorry I forgot your last comment. Currently (in v1.98.3) Vimium C's `performFind`, `performBackwardsFind` and `performAnotherFind` supports `highlight=true`. For example:
```
map N performFind query="words-to-find" highlight
# or use your last query in FindMode HUD
map n performFind last highlight
```

These 2 commands will search in a current viewport and highlight found words. Though there's an issue in up to v1.98.3 that it stops when finding a match in an editable box. I'll try fixing it in a future version.

As for that rects should move when a page scrolls, I'll change the current logic.

@sky31even The yellow background color can only be added by browsers, and web-extensions can not simulate it, so Vimium C uses **a bounding boxes** to mark visible matches, and only the "current" match can have a orange background color.

**Comment by gdh1995** [comment]
@sky31even Yes it's the mostly recommended way to do a search - it runs fast and its results are accurate. While Vimium C has such useful features: find history, multiple-line query text (you may insert a "new line" character by `Shift+Enter`) and regexp search.

**Comment by sky31even** [comment]
> @elig0n Sorry I forgot your last comment. Currently (in v1.98.3) Vimium C's `performFind`, `performBackwardsFind` and `performAnotherFind` supports `highlight=true`. For example:
> 
> ```
> map N performFind query="words-to-find" highlight
> # or use your last query in FindMode HUD
> map n performFind last highlight
> ```
> 
> These 2 commands will search in a current viewport and highlight found words. Though there's an issue in up to v1.98.3 that it stops when finding a match in an editable box. I'll try fixing it in a future version.
> 
> As for that rects should move when a page scrolls, I'll change the current logic.
> 
> @sky31even The yellow background color can only be added by browsers, and web-extensions can not simulate it, so Vimium C uses **bounding boxes** to mark visible matches, and only the "current" match can have a orange background color.

this really fits for my demand, only the rects move with page scrolling left ~~ looking forward the new version lol.... thank you for the work!!

**Comment by sisrfeng** [comment]
I like the "find history" feature of vimium-c, but I often need to press `n` for several times to make sure that I have read all the match. It would be great if thing like this would appeared :  2/10,  (index of the current match/total match)

**Comment by gdh1995** [comment]
Hello, in v1.99.3 `enterFindMode` supports `highlight=true`, too, and `highlight=true` will make it show nearby 20+20 matches; you may also setup `highlight=30|40|...` to show more nearby matches.

@sky31even "The rects move when a page scrolls" means this feature work as intended. I thinks moving should be useful and avoid confusing rects.

@sisrfeng The count is not accurate and it's not easy to keep a current index correct, so I think it‘s better to show only total matches.

**Comment by sisrfeng** [comment]
What about using chrome's own search bar, but use `/` instead of <C-f>,  `n` instead of `<CR>` , `N` instead of shift+ <CR> ?

**Comment by gdh1995** [comment]
Unfortunately Vimium C, as a web extension, can not operate Chrome's native find bar.

**Comment by sisrfeng** [comment]
> Unfortunately the extension API doesn't let us provide custom shortcuts for browser search/search next. :(
https://github.com/crittermike/shortkeys/issues/193#issuecomment-568561243

Now I consider using `ctrl F` in chrome, but `/` in vim. (弃疗了)

**Comment by Propfend** [comment]
I am using:
```
map n performFind highlight
```
Mine only gets highlighted for a moment after i press `n`.
> `FindMode: use <c-s-j> / <c-s-k>`
>

Does not work for me.

**Comment by Propfend** [comment]
Plus, it would be nice if Vimium-C could show the Link positions of the page on the website scrollbar column, the same way Chromium or Firefox searching feature do.
