### ISSUE TITLE
Local files can't be opened from the Vomnibar

### ISSUE THREAD

**Issue by maxigaz** [gdh1995/vimium-c#278]
Using Vimium C v1.88.1 in Firefox 84 under Linux, I can’t find a way to open any local files (such as .txt and .html ones) using only the Vomnibar.

The issue is twofold:

1. When I copy and paste the full path to the file into the Vomnibar (e.g. `/home/maxigaz/Documents/test.html`) and press Enter, it’s interpreted as a query to the default search engine. (On the other hand, if I paste the same path Firefox’s own URL bar, it’s recognized correctly as a local file.)
2. If the same file has been opened at least once in Firefox and I type parts of the file’s name into the Vomnibar, it appears in the list as a history item (prefixed with `file://…`). However, nothing happens when I select it and press Enter.

By the way, the Vomnibar is brought up with `o` in both cases. (I checked if the cause might be a custom command like `map o Vomnibar.activate engines=15`, but the problem remained even after unmapping this.)

**Comment by gdh1995** [comment]
it's a limit of Firefox, but not Vimium C.


There're many URLs that Vimium C can not open actively.



---Original---

**Comment by gdh1995** [comment]
"a limit" means it's a designed feature of Firefox - to limit what extensions can do



---Original---

**Comment by maxigaz** [comment]
Oh, OK. Thank you for the explanation!

**Comment by NightMachinary** [comment]
@gdh1995 Is there a patched version of Firefox (or any browser that vimium supports, really) without this limit? I want to have vim keybindings when viewing PDF files, and none of the other options are as good as a browser plus vimium.
