### ISSUE TITLE
exit full screen first instead of close Vomnibar

### ISSUE THREAD

**Issue by Monirzadeh** [gdh1995/vimium-c#280]
1. open a YouTube video and make that full screen
2. open Vomnibar
3. press `Esc`
4. it exit from full screen first instead of close Vomnibar

expected behavior
1. open a YouTube video and make that full screen
2. open Vomnibar
3. press `Esc`
4. close Vomnibar
5. press `Esc` again
6. exit from full screen

**Comment by gdh1995** [comment]
This is a feature of Chrome, and there's nothing Vimium C can do to bypass it.

See https://github.com/philc/vimium/issues/3435#issuecomment-556843536 and https://github.com/philc/vimium/issues/2963#issuecomment-612779675 for similar questions in the original Vimium:

> <kbd>Escape</kbd> and <kbd>Ctrl+[</kbd> is always hooked by a browser, so you may add this to key mappings on Vimium Options:
> 
> ```
> mapKey <c-i> <c-[>
> ```
> 
> And then use <kbd>Ctrl+I</kbd> to exit insert mode. Other composed keys usually work, too, if only they're not forced to be hooked by your browser.
