### ISSUE TITLE
"v" shortcut is added to "Search engines added by extensions", impossible to disable

### ISSUE THREAD

**Issue by Roman-** [gdh1995/vimium-c#281]
When I type "v" in my Chrome omnibar, it triggers Vimium C search engine. My "v" shortcut was previously binded with a different search engine that I use.
The "v" shortcut appaers in the list of "search engines" in my Google Chrome settings (see first screenshot). There doesn't seem to be an option in the extention settings to disable it or change the keyword. The only option to disable it is disabling the extention itself.
![Omni](https://sun9-26.userapi.com/impf/ssBHBgiSb3Dk6on_k1zfCGk5J5hNGKcaAVnSdw/YBAye0cIMGk.jpg?size=481x204&quality=96&proxy=1&sign=2860ff7c6c5a72ff79c9f6804f867af0&type=album)

![Search engines settings](https://sun9-14.userapi.com/impf/TIvueiDB_k7AqGebllY3Z6aNSc8h01mn9nlQKQ/NNrcDVpl5no.jpg?size=697x443&quality=96&proxy=1&sign=ac0c7a868d74650d9b93b0ce5f8337af&type=album)

Chrome  Version 88.0.4324.96 (Official Build) (64-bit)

**Comment by gdh1995** [comment]
I know this but it can not be fixed. This is a limit of browsers, and they only allow each web extension to declare up to one keyword in its manifest file, but don't provide any API to change, add or remove the keyword dynamically.

**Comment by Roman-** [comment]
There's also a related behaviour with that omnibar, a very strange one, and I don't know if that's related to Vimium C or the browser itself.
When I open a new tab and start typing a search query or the website, it enables that "Vimium C" (like on the first screenshot) without even waiting me to press the Spacebar or Enter! Furthermore, when it happens, I can not remove that thing by pressing "Backspace". With other keys that are search-engine shortcuts, pressing Backspace returns omnibar in normal mode with that key being typed as first symbol of the search query. Please check if that's the case on Chrome Version 88.0.4324.96.

Considering "cantfix", is there an option to disable the search-engine (regardless the shortcut key) completely without disabling the extention?

**Comment by gdh1995** [comment]
> open a new tab and start typing a search query or the website, ...  I can not remove that thing by pressing "Backspace"

It's very strange. By default when the browser's address bar gets focused, it should have no words, and it will enter Vimium C mode only when you type "v" and a space. Have you used any software to remap keyboard or add system-level shortcuts?

> Considering "cantfix", is there an option to disable the search-engine (regardless the shortcut key) completely without disabling the extention?

No, there's no way to do so on the published Vimium C. The only way is you download the extenision files or compile a version of Vimium C on your computer, and modify its `manifest.json` to delete it, and then load the folder as an extension in debug mode (https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package).

**Comment by Roman-** [comment]
> It's very strange. By default when the browser's address bar gets focused, it should have no words, and it will enter Vimium C mode only when you type "v" and a space. Have you used any software to remap keyboard or add system-level shortcuts?

Ok I've found the reason for it. Seems to be a Chrome error when you have another search engine binded to "v" key before installing/enabling the vimium (which adds its own "v" shortcut on top). To reproduce:
1) Disable Vimium C
2) Go to "search engines", add "v" shortcut for some engine
3) Enable Vimium C.
