### ISSUE TITLE
pdf如何平滑滚动，而不是翻页

### ISSUE THREAD

**Issue by NietzscheX** [gdh1995/vimium-c#282]
PDF Viewer for Vimium C
在大于100%，比如150%的情况下，
默认大小是100%，pdf的一页刚好占一个屏幕，
可是在放大模式下（因为字太小了需要放大），一页需要多个屏幕才能展示完毕，但是此时按J往下翻的时候，属于pdf的一页的但是尚未展示、尚未阅读的部分会被直接略过，pdf翻到下一页了。

请问有没有一种流畅的滚动方式，而不是直接一页一页的翻？

**Comment by NietzscheX** [comment]
补充一下信息：
我是使用了saladict，然后再saladict上右键-->在pdf阅读器中打开，
直接使用是可以平滑翻页的。

但是直接使用无法享受实时翻译的效果，所以这个问题应该是和saladict协作的问题？

**Comment by gdh1995** [comment]
你装了pdf viewer for vimium c?没装的话，平时应该也没法用vimium c快捷键平滑滚动吧。


它是一个独立于浏览器内置PDF阅读器的一个专门看pdf的扩展，我给他添加了vimium c的支持；，而沙拉查词自己也内置了一个专门看PDF的页面，所以你打开PDF的时候，具体用哪个打开的就很关键了。


我回头看看能不能搞兼容，感觉不好搞



---原始邮件---
发件人: "NietzscheX"<notifications@github.com&gt;
发送时间: 2021年2月3日(周三) 中午11:45
收件人: "gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [gdh1995/vimium-c] pdf如何平滑滚动，而不是翻页 (#282)




 
补充一下信息：
 我是使用了saladict，然后再saladict上右键--&gt;在pdf阅读器中打开，
 直接使用是可以平滑翻页的。
 
但是直接使用无法享受实时翻译的效果，所以这个问题应该是和saladict协作的问题？

**Comment by gdh1995** [comment]
啊，这个是专门处理了插件兼容性，一开始是平滑滚动的，后来有人提我就改成了让j、k执行这个PDF阅读器自己的翻页功能。
回头我去加个开关，让你可以选择不使用阅读器的翻译方案，而是沿用vimium c的



---原始邮件---
发件人: "NietzscheX"<notifications@github.com&gt;
发送时间: 2021年2月3日(周三) 中午11:31
收件人: "gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [gdh1995/vimium-c] pdf如何平滑滚动，而不是翻页 (#282)




 
PDF Viewer for Vimium C
 在大于100%，比如150%的情况下，
 默认大小是100%，pdf的一页刚好占一个屏幕，
 可是在放大模式下（因为字太小了需要放大），一页需要多个屏幕才能展示完毕，但是此时按J往下翻的时候，属于pdf的一页的但是尚未展示、尚未阅读的部分会被直接略过，pdf翻到下一页了。
 
请问有没有一种流畅的滚动方式，而不是直接一页一页的翻？

**Comment by NietzscheX** [comment]
谢谢大佬这么快就回复我

嗯我是安装了pdf viewer for vimium c的
如果读中文文档没有任何问题，用pdf viewer for vimium c看pdf了 因为太习惯vim模式上下了翻页了，完美。
但是读英文文档的时候，遇到很多不认识的单词，希望能翻译，在pdf viewer for vimium c里面无法直接鼠标划词翻译。

而saladict可以打开pdf（基于pdf.js项目），也能划词翻译，但是他的翻页效果就是我所提的，只能一页一页的翻，不支持连续滚动。

我看你这个pdf viewer for vimium c也是基于pdf.js项目。

也就是说：
pdf viewer for vimium c 能完美支持pdf的翻页，但是没有翻译。
saladict完美翻译，但是翻页支持得差。

我就想想问问有没有一个更好的办法解决：
要是pdf viewer for vimium c里面可以直接划词翻译 那就完美了。

**Comment by gdh1995** [comment]
看了看这俩不好兼容。pdf viewer for vimium c 不能调用saladict的脚步来添加查词按钮。建议你用独立窗口查词模式、需要查词时选择文字、复制，然后按快捷键触发查词。

快捷键在 `chrome://extensions/shortcuts` 下的“在独立窗口中搜索剪贴板内容”里配置。

**Comment by NietzscheX** [comment]
> 看了看这俩不好兼容。pdf viewer for vimium c 不能调用saladict的脚步来添加查词按钮。建议你用独立窗口查词模式、需要查词时选择文字、复制，然后按快捷键触发查词。
> 
> 快捷键在 `chrome://extensions/shortcuts` 下的“在独立窗口中搜索剪贴板内容”里配置。

好的好的，谢谢。
