### ISSUE TITLE
Feature Request Zoom Reset

### ISSUE THREAD

**Issue by evanricard** [gdh1995/vimium-c#286]
Hi gdh,

I noticed an old feature request for zoom in / zoom out; I'm wondering if you would have time in the new year and you could add a command for zoom reset. Thanks!

-Evan

**Comment by gdh1995** [comment]
map ... toggleZoom count=1000


for a count larger than four, it will mean an absolute zoom factor, and:
* if larger than 1000, then reset
* if larger than 100, then apply count / 100
* if larger than 10,then apply count / 10



---Original---

**Comment by evanricard** [comment]
Ah man thanks that's easy! I knew you must have had this baked in somewhere, cheers :P ƪ(˘⌣˘)ʃ
