### ISSUE TITLE
nextHint and previousHint

### ISSUE THREAD

**Issue by evanricard** [gdh1995/vimium-c#288]
Hi again @gdh1995, 

Regarding LinkHints.activateModeWithQueue are there nextHint and previousHint type behaviors or some way to navigate between linkHint elements?

Regardless, thank you!

**Comment by evanricard** [comment]
Also, what is the usage of `removeTab` keepWindow="mayClose" goto="current" as in is this viable syntax?

**Comment by gdh1995** [comment]
If you has enabled the `Use the link's name and characters for link-hint filtering` option in Vimium C Options page (aka. the filter-hint mode), then `<tab>` and `<s-tab>` can be used to navigate among elements. The "currently active" element will have gray text, and one `<enter>` or 3 `<space>` keys will activate it.

<hr>

`removeTab` has such options:
``` typescript
type RemoveTabOptions = {
  limited?: boolean // decide what a very large count will close (the one side of tabs, or the whole window)
  highlighted?: boolean | "no-current" // decide whether to follow the Tab.highlighted status or not
  goto?: "left" | "right" | "previous" // decode an active tab after closing some tabs
  mayClose?: boolean // if false or undefined, then won't close "the last one window", to keep your browser running
  keepWindow?: "always" // if "always", then won't close any window - create a new tab before closing all current tabs
}
```

**Comment by evanricard** [comment]
@gdh1995, ah thank you interestingly enough on Vivaldi it seems that it changed the linkhints to numerics instead of alphabetical representation. Am I able to just removeTab on the current tab? I will check the wiki on that. Thank you again

**Comment by gdh1995** [comment]
> changed the linkhints to numerics

Yes it worked as designed.



> just removeTab on the current tab

If you want to remove a current tab, then `removeTab` with no mapping options is enough, like `map x removeTab`.

**Comment by evanricard** [comment]
alright thank you for sharing unfortunately my map ``map <a-c> removeTab`` is not working - probably a Vivaldi thing - but my ``map C removeTab`` is working; alt-c is **not** mapped elsewhere nor is it a mnemonic chord to the menu bar as far as I can tell. I have other alt modifier + alpha chararcter mappings already within Vimium-C or among other extensions so thus it confused me causing me to open this ticket. 

Regardless, thank you for your help!

**Comment by gdh1995** [comment]
Are you using macOS ? If so, please try enabling (or partly enabling) the `Ignore keyboard layout` option in "advanced options" section on Vimium C Options page.

#### Reason

The macOS system will map `Alt+***` to some infrequent characters, which makes Vimium C get wrong key name.

Test for this system-level mapping:
* open https://gdh1995.cn/vimium-c/keyboard-test.html
* click Vimium C's icon and "save options" to make Vimium C disabled on the page
* reload the page, and enable "Prevent all keyboard events"
* then press Alt+C to see what it will log.

**Comment by evanricard** [comment]
Thanks again @gdh1995, no I am not on MacOS. 
![image](https://user-images.githubusercontent.com/30779615/108853260-80c6b000-75b4-11eb-92a5-ae14ea876ed4.png)
Logs the keys as it should it looks like!

**Comment by gdh1995** [comment]
Closed because I have no idea about what happened about `<a-c>` on your computer.

If you find any new clues and reproducible way on other computers, fell free to reopen this issue.
