### ISSUE TITLE
自定义搜索时 不输入关键词显示的链接无法显示

### ISSUE THREAD

**Issue by ugirc** [gdh1995/vimium-c#289]
我之前输入关键词bz然后直接回车是可以显示blank后面的链接，如https://www.bilibili.com/account/history的，现在在chrome上为什么不行了？麻烦有空大佬帮我看看？

![image](https://user-images.githubusercontent.com/46078304/108374591-158b7f80-723c-11eb-9d89-1b62a051b630.png)

我的配置代码
```
bz | bili|bilibili|bz|Bili: https://search.bilibili.com/all?keyword=%s
blank=https://www.bilibili.com/account/history 哔哩哔哩

y| youtube | yt: https://www.youtube.com/results?search_query=%s
blank=https://www.youtube.com/ youtube
```

**Comment by gdh1995** [comment]
blank前边不要有换行



---原始邮件---
发件人: "AnishHui"<notifications@github.com&gt;
发送时间: 2021年2月18日(周四) 晚上10:53
收件人: "gdh1995/vimium-c"<vimium-c@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [gdh1995/vimium-c] 自定义搜索时 不输入关键词显示的链接无法显示 (#289)




 
我之前输入关键词bz然后直接回车是可以显示blank后面的链接，如https://www.bilibili.com/account/history的，现在在chrome上为什么不行了？麻烦有空大佬帮我看看？
 

 
我的配置代码
 bz | bili|bilibili|bz|Bili:&nbsp;https://search.bilibili.com/all?keyword=%s blank=https://www.bilibili.com/account/history&nbsp;哔哩哔哩 y|&nbsp;youtube&nbsp;|&nbsp;yt:&nbsp;https://www.youtube.com/results?search_query=%s blank=https://www.youtube.com/&nbsp;youtube

**Comment by ugirc** [comment]
> blank前边不要有换行

谢谢！
