### ISSUE TITLE
how change size of omnibar

### ISSUE THREAD

**Issue by Monirzadeh** [gdh1995/vimium-c#290]
hi 
i need to change size omnibar and margin around that so how can i change that 
there is this bellow code but i can't change that with css
```
.Omnibar{left:calc(10vw - 12px);top:64px;width:calc(80vw + 24px)}
```
i need to change size of omnibar to size of screen without any marrgin

**Comment by gdh1995** [comment]
During my tests, `left`/`width` of `.Omnibar` did work, so what's the CSS style code your tried?

If you want to remove margin and border radius, then you also need to set CSS for the Vomnibar iframe. See https://github.com/gdh1995/vimium-c/wiki/Style-the-UI-of-Vimium-C-using-Custom-CSS#basic-structure for more syntax info.

**Comment by Monirzadeh** [comment]
i talk about this margin(an invisible box around vomnibar) that i can't remove that
![screanshot-2021-02-22-15-23-59-438639710](https://user-images.githubusercontent.com/25131576/108705189-3b59a280-7522-11eb-8144-abefef0a590b.png)

**Comment by gdh1995** [comment]
If you mean the left/top/right margin, then its code is in:

https://github.com/gdh1995/vimium-c/blob/2f6b5c590eae1720dbf7a96ef8e590128f6633a4/front/vomnibar.html#L8-L9

And customized styles belonging to `/* #omni */` section will override them.

**Comment by Monirzadeh** [comment]
thanks
