### ISSUE TITLE
Searching For the Copied Text in a Custom Search Engine 

### ISSUE THREAD

**Issue by jetrosut** [gdh1995/vimium-c#293]
1. Go to a webpage.
2. Hit '/' and search for a phrase.
3. Press 'enter', followed by 'y' to yank.
4. Hit 'o' to open up the Omnibar.
5. Enter the letter mapped to the search engine in question.
6.  Do 'Control + V' to paste the copied phrase.
7. Hit 'Enter'.

I thought a shortcut could be implemented for the steps from 4 to 7. Like how you select buffers with " in vim for example, you could do "mp which would result in searching using the engine mapped to m.

**Comment by gdh1995** [comment]
`Vomnibar.activateUrl`: use selected text or tab URL as query

**Comment by jetrosut** [comment]
That requires a new mapping to each search engine but still works, thanks.
