### ISSUE TITLE
Mapping a function with "N-th" to a key

### ISSUE THREAD

**Issue by jetrosut** [gdh1995/vimium-c#295]
By default, '2g0' will take you to the second tab. Though, I'd very much rather doing 2g instead, as 0 is pressed with the little finger due to its location on a regular qwerty keyboard and adds a superfluous step. Adding 'map c firstTab' to the Vimium-c options does not work, it instead takes you to the first tab no matter what.

I believe [168](https://github.com/gdh1995/vimium-c/issues/168) would not solve this issue as fake numbers are not what's needed.

**Comment by gdh1995** [comment]
With `map c firstTab`, then <kbd>2</kbd><kbd>c</kbd> will go to the 2nd tab (indexed from left).

**Comment by jetrosut** [comment]
@gdh1995 I wish there was a way to delete the issue. I thought I tested it and it didn't work but I am guessing it was either a tab that Vimium didn't work on or I had disabled the extension and reenabled it without refreshing the page later on. I am terribly sorry.

**Comment by gdh1995** [comment]
Ah. It's not needed to delete the issue - just fell free to file issues here.
