### ISSUE TITLE
希望增加方向键的设置

### ISSUE THREAD

**Issue by ChloeKurumi** [gdh1995/vimium-c#297]
我想把wsad改成方向键的↑↓←→，上下虽然可以设置滚动，但有些网站的←→是用来翻页的快捷键，希望能支持

**Comment by gdh1995** [comment]
在 Vimium C 设置页面，添加下述代码到“自定义快捷键”：
```
# 左右键翻页
map <left> goPrevious
map <right> goNext
```
或者
```
# 左右键滚动
map <left> scrollLeft
map <right> scrollRight
```

上下滚动的快捷键设置是：
```
map <up> scrollUp
map <down> scrollDown
```
当然也可以不 map 这两个键，直接触发浏览器内置的滚动

**Comment by ChloeKurumi** [comment]
> 在 Vimium C 设置页面，添加下述代码到“自定义快捷键”：
> 
> ```
> # 左右键翻页
> map <left> goPrevious
> map <right> goNext
> ```
> 
> 或者
> 
> ```
> # 左右键滚动
> map <left> scrollLeft
> map <right> scrollRight
> ```
> 
> 上下滚动的快捷键设置是：
> 
> ```
> map <up> scrollUp
> map <down> scrollDown
> ```
> 
> 当然也可以不 map 这两个键，直接触发浏览器内置的滚动

看视频的时候，←→是后退和前进，怎么设置成a键后退，d键前进？？

**Comment by gdh1995** [comment]
目前Vimium C的命令做不到；单独加的话感觉没啥必要性，也不通用（可能换个网站就模拟不了方向键了），太折腾了。
