### ISSUE TITLE
Can the spacebar key <space> be mapped?

### ISSUE THREAD

**Issue by Kristoffer-PBS** [gdh1995/vimium-c#298]
In my neovim config i have this mapping to toggle between the last visited buffer, which i
find really useful!
```vim
nnoremap <leader><leader> <c-^> 
```
where I have mapped `<leader>` to spacebar.

Can i create a similar keybinging with `<space><space>` to toggle between the last visited tab?

**Comment by gdh1995** [comment]
`map <space><space> visitPreviousTab` should work.

**Comment by Kristoffer-PBS** [comment]
It does!
Thank you very much
