### ISSUE TITLE
添加多国语言支持

### ISSUE THREAD

**Issue by liushilive** [gdh1995/vimium-c#30]
希望 Vimium C Help 页面支持多国语言。

记不住快捷键，经常需要查看帮助，希望可以添加中文帮助提示。

谢谢！

**Comment by gdh1995** [comment]
早就在 #13 的“long term tasks”里了……

至于开发计划，已经安排上了，打算高考结束前弄出来。

**Comment by gdh1995** [comment]
补充：目前支持自定义每个命令的显示的帮助文本，在map ...的时候可以指定`map E goNext $desc=<span>下一页</span>`这种写法。具体参考https://github.com/gdh1995/vimium-c/issues/27#issuecomment-460973139 ，允许的tags列表参见https://github.com/gdh1995/vimium-c/blob/master/background/help_dialog.ts#L124

**Comment by gdh1995** [comment]
您好，Vimum C 1.77.0（已发布）与今后的新版本都将最大程度地支持中文界面。
