### ISSUE TITLE
[BUG][macOS] When zooming via pinching the fingers, the vomnibar is also zoomed

### ISSUE THREAD

**Issue by NightMachinary** [gdh1995/vimium-c#300]
When I zoom Chrome by pinching, the vomnibar is also zoomed:
![image](https://user-images.githubusercontent.com/36224762/109835567-8d07d880-7c58-11eb-884a-f99b7142c7ff.png)

This doesn't happen if I use `CMD+-` and `CMD+=`, this problem does not occur.

**Comment by gdh1995** [comment]
it's not a bug. browsers have special logic for pinch-zoom and all page content will be zoomed.







---Original---
