### ISSUE TITLE
chrome 有些网页不运行，360浏览器却可以。

### ISSUE THREAD

**Issue by snsnsjsn** [gdh1995/vimium-c#301]
![image](https://user-images.githubusercontent.com/11435527/110207025-2682f480-7ebc-11eb-8281-2e008ef04acd.png)
http://cms.dlszywz.cn/user_index.php?is_frame=2&t=********

上面360可以使用
chrome却用不了

**Comment by gdh1995** [comment]
啊抱歉，我没账号访问不了这个网址。这个网站是用了某种网站模板搭建的吧？请问具体是哪个模板，我去自己搭建了再试试。

另外需要知道Chrome版本、你的操作系统名字和版本、具体怎么用不了（所有快捷键都不行，还是按 <kbd>f</kbd> 没响应，还是弹不出 Vomnibar）。同时请问你怎么跑在 360浏览器上的？也是从 Chrome应用商店 里安装的吗？

盲猜的话，或许是 Vimium C 出bug了，或者是因为Chrome 最近一年收紧了一些跨域检查而导致 LinkHints 功能受限。

**Comment by snsnsjsn** [comment]
模板网站 你可以访问我的 https://eyun点it  注册一个账户看看，就可以进入后台测试f键

操作环境 ，win10最新， chrome最新，f没响应， 都是从 chrome商店安装的。

你试试看看

**Comment by gdh1995** [comment]
呃，我这 f 能工作：
![image](https://user-images.githubusercontent.com/5547703/110248590-e5b6d880-7fac-11eb-8be5-46c4cd85c03c.png)

我是Win10，Edge 最新、Chrome最新（89）都行。

====

请在 chrome://extensions/ 上把所有其他扩展都禁用，只保留Vimium C启用着，然后刷新这个网页测试一下 f
* 一种可能性是，这个页面把焦点移动到某个隐藏的输入框或选择框了，造成 Vimium C 不响应 f 键。

请在这个页面上测试像“切换标签页”之类的“不涉及 网页内容 或 Vimium C”的快捷键，如果能用，则说明可能只是 LinkHints 的问题。

**Comment by snsnsjsn** [comment]
可以了，估计是其他插件导致的
