### ISSUE TITLE
After jump to mark, jump back to previous Tab

### ISSUE THREAD

**Issue by OBorce** [gdh1995/vimium-c#302]
Is it possible after jumping to a global mark, to go back to the previous tab? something like vim's CTRL+o

**Comment by gdh1995** [comment]
There's a command named `previousTab`, and by default ` gT`, `J` and `<a-c>` are mapped to it.

**Comment by OBorce** [comment]
That `previousTab` is the tab on the left of the current one, I mean previous as in the one we just jumped from. 
Example I have 10 tabs, I am currently on Tab 6, and have set a global mark on Tab 1 with `mM`.
Now I jump to the mark with `M i.e. Tab 1.
I would like to return (jump back) to where I was Tab 6.

**Comment by michielappelman** [comment]
I think `visitPreviousTab` would work in your case. By default mapped to `^`.

**Comment by gdh1995** [comment]
Oh sorry I misspelled the name. Yes the correct one is "visitPreviousTab".
