### ISSUE TITLE
Bind minus sign "-" to an action

### ISSUE THREAD

**Issue by slittica** [gdh1995/vimium-c#303]
Just moved from vimium-ff and I am currently missing the option to bind the minus character. In my keyboard layout (abnt2) the default key to jump to the previous tab `^` requires pressing shift. `-` is the most convenient option for me.

I see the message that binding `-` and numbers are not supported. Why is that and is there any way to circumvent this (e.g. by disabling another feature that I might not need)?

Thanks!

**Comment by gdh1995** [comment]
It's because Vimium C supports "negative count prefix" - for example `-3x` will close a current tab and 2 left (but not right) tabs - and it always treats <kbd>-</kbd> as a sign prefix of command count.

You may bypass this logic using `mapkey`:
```
mapkey - <neg>
map <neg> previousTab
```

**Comment by slittica** [comment]
Works perfectly, thank you!
