### ISSUE TITLE
Restore a closed tab in incognito mode

### ISSUE THREAD

**Issue by slittica** [gdh1995/vimium-c#305]
Is there a way to ignore this check and perform the action regardless?

Thanks

https://github.com/gdh1995/vimium-c/blob/873dd91c5fc47788af37dc002982ef875d74248a/background/all_commands.ts#L463-L465

**Comment by gdh1995** [comment]
Browsers also don't record closed incognito tabs, so the answer is no.

Therefore, if in an incognito window and `count > 1`, then `restoreTab` will restore "2 closed tabs which were in a normal window".

**Comment by slittica** [comment]
It works on Firefox. Not sure if I have enabled some setting that allows this, but it’s not an extension and I have been reopening closed tabs in incognito for as long as I can remember. Plain Ctrl-shift-T works for me and so does Vimium-ff.

**Comment by gdh1995** [comment]
Um, what is Vanilla Firefox? On standard Firefox 86, incognito tabs won't be added into the list of closed sessions, and I download Firefox from https://ftp.mozilla.org/pub/firefox/releases/ .

Anyway, I'll add an option to allow users to skip this check.

**Comment by slittica** [comment]
By vanilla I meant default configs, no addons, no synced settings. Just plain fresh-after-install and up-to-date Firefox. 

I just tried it in Windows Sandbox:

![record](https://user-images.githubusercontent.com/79228063/112023731-477d5380-8b12-11eb-812b-1c700ba0c683.gif)

I'm reopening tabs by hitting `ctrl-shift-t`. Thanks for looking into it, though!

**Comment by gdh1995** [comment]
I'll add a new option of `incognito="force"` to `restoreTab` in a next version. As a work around, you may use `restoreGivenTab` to restore a tab (it ignores incognito status).

**Comment by gdh1995** [comment]
Hello. Vimium C v1.89.0 has been released on Firefox Add-ons, and being verifying by Chrome Web Store and MS Edge Add-ons. So you may take a try.

**Comment by slittica** [comment]
Awesome! Just got to try it and it works perfectly. It wasn't clear at first where I should set this option, but I figured it should be set in a custom key mapping. So here it is in case anyone else was wondering:

`map X restoreTab incognito="force"`

**Comment by npn225** [comment]
Thank you, @gdh1995! 

Your update resolved this issue for me!

And thank you, @pandoxer!  

That mapping was what got it working for me!
