### ISSUE TITLE
Toggleable vomnibar (suggestion)

### ISSUE THREAD

**Issue by Shorono** [gdh1995/vimium-c#309]
A command like "Vomnibar.toggle" that would have one hotkey that would open the vomnibar if pressed once and close it again if pressed again. Kinda like how the command palette acts in sublime text.

**Comment by gdh1995** [comment]
There's a working-around for it: use `mapkey`. For example, if
```
mapkey <c-g:o> <esc>
map <c-g> Vomnibar.activate
```
, then <kbd>Ctrl+G</kbd> will toggle Vomnibar.
