### ISSUE TITLE
vomnibar became huge after git cloning and compiling the latest version

### ISSUE THREAD

**Issue by wis** [gdh1995/vimium-c#31]
maybe caused from a css commited a day ago
https://github.com/gdh1995/vimium-c/blame/a5b3395a256d91a513ea6c4fa6a82f3dfcf9f47a/front/vomnibar.html#L12-L23
the commit message is ["iframe vomnibar: use rem to adjust zoom level on Firefox"](https://github.com/gdh1995/vimium-c/commit/a97b8559816475815eda4402a36595bdfba0fd53), I currently use Chromium
![2019-05-01_05:27:21_3840x2160 f](https://user-images.githubusercontent.com/9993663/57003832-1d46e380-6bd2-11e9-8cd0-1436b83dd05b.png)

**Comment by gdh1995** [comment]
Yes, I also found this bug yesterday. Fixing.

It's because the commit works well on my laptop (Chrome 74 x64, Win 10), so I commit it, but the size gets totally wrong on my PC ...

**Comment by gdh1995** [comment]
In fact, this is the first issue I have met that same versions of Chrome work differently on a same version of Win 10 (v1809, b17763.437) but different computer hardwares . I've tested Chrome 35, 61, 74 and so on but they just do the same on a same computer while differently on different computers.

**Comment by wis** [comment]
I'm so glad I switched today from vimium to vimium C! 
it's really underappreciated, too bad first mover advantage is a thing, I wish more people give it a shot like I (finally) did. :smiley:

**Comment by gdh1995** [comment]
Thanks.

A big problem is Vimium C has (almost) no documents... I'll write them this year.

**Comment by gdh1995** [comment]
The reason of difference is found - my laptop is English and PC is Chinese. If I switch Chrome's language to Chinese, it also breaks on my laptop.
