### ISSUE TITLE
Changing the icon color depending on working status of Vimium-C.

### ISSUE THREAD

**Issue by ipimko** [gdh1995/vimium-c#311]
**Vimium** changes the icon color (from blue to gray) on pages where **Vimium** doesn't work, but **Vimium-C** doesn't.
Toggling the 'Show extension icon dynamically on the top right' option does nothing.
Tested on chrome, chromium, firefox on linux and chrome, edge on Windows.

Very handy feature, can you do this in Vimium-C?

Thank you in advance.

**Comment by gdh1995** [comment]
Vimium C only shows gray/partially-gray icons for those tabs which run it and match its configured exclusion rules. As for those like `about:blank` and `chrome://...`, Vimium C can never work on them, and I usually think it's very easy to tell such privileged tabs from normal web sites. Therefore it's somehow unnecessary for me to take a look at Vimium C icon when on such tabs.

If you found Vimium C showed wrong icon on a website matching any exclusion rule, then it may mean a bug. Please let me know the version of your Vimium C and tested browser, and I'll try to fix it.
