### ISSUE TITLE
Grouped Tabs Are Removed After closeDownloadbar

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#313]
After closed the downloadbar, the grouped tabs were all removed from groups.
![截图1](https://user-images.githubusercontent.com/66708845/112857944-f823be00-90e3-11eb-95a6-a39c7df9f3df.png)

**Comment by gdh1995** [comment]
Um, this will be fixed when https://github.com/gdh1995/vimium-c/issues/267#issuecomment-755250242 is sloved.

**Comment by OnceThenEver** [comment]
Fine
