### ISSUE TITLE
pdf_problem

### ISSUE THREAD

**Issue by salihtangel** [gdh1995/vimium-c#315]
When we open a pdf in explorer the default vim spec. are not working.
Can you do for it also pdf.

**Comment by gdh1995** [comment]
https://chrome.google.com/webstore/detail/pdf-viewer-for-vimium-c/nacjakoppgmdcpemlfnfegmlhipddanj will work with Vimium C.

**Comment by salihtangel** [comment]
> 
> 
> https://chrome.google.com/webstore/detail/pdf-viewer-for-vimium-c/nacjakoppgmdcpemlfnfegmlhipddanj will work with Vimium C.

does it have similar thing in firefox?

**Comment by gdh1995** [comment]
Um, not released on Firefox add-ons yet.
