### ISSUE TITLE
System remaps not working on vomibar 

### ISSUE THREAD

**Issue by sunnyrahul25** [gdh1995/vimium-c#316]
I have system remaps in 
~/.Xmodmap that remap caps +  hjkl  as arrows keys.

~/.Xmodmap
! remove Caps Lock 
clear Lock 
! add Mode_switch, Escape is caps lock 
keycode 66 = Mode_switch  Mode_switch 
keycode 45 = k K Up 
keycode 43 = h H Left 
keycode 44 = j J Down 
keycode 46 = l L Right 
keycode 46 = l L Right 

They do work on most of applications on my system.
However, with Vomnibar  they dont work . Although arrow keys(up,down,left,right) work on the Vomnibar.
Below is the screenshot of keyboard test tool, with my  remaps.
![vimiumkey](https://user-images.githubusercontent.com/8398157/113316622-d8bca900-930e-11eb-99c1-c9f349ccceb8.jpg)
I would appreciate, if someone could help me with this problem.

**Comment by gdh1995** [comment]
what will a real arrowup/down show on the test page?



---Original---
From: "Sunny ***@***.***&gt;
Date: Thu, Apr 1, 2021 23:26 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] System remaps not working on vomibar  (#316)




 
I have system remaps in
 ~/.Xmodmap that remap caps +  hjkl  as arrows keys.
 
~/.Xmodmap
 ! remove Caps Lock
 clear Lock
 ! add Mode_switch, Escape is caps lock
 keycode 66 = Mode_switch  Mode_switch
 keycode 45 = k K Up
 keycode 43 = h H Left
 keycode 44 = j J Down
 keycode 46 = l L Right
 keycode 46 = l L Right
 
They do work on most of applications on my system.
 However, with Vomnibar  they dont work . Although arrow keys(up,down,left,right) work on the Vomnibar.
 Below is the screenshot of keyboard test tool, with my  remaps.
 
 I would appreciate, if someone could help me with this problem.

**Comment by sunnyrahul25** [comment]
In the above log, 
key event no : 1,2,3,4 are for  real arrow keys. 
key event no : 6,7,10,11 are for remaps (caps +  jk)

**Comment by gdh1995** [comment]
Hello. Vimium C v1.89.0 has been released on Firefox Add-ons, and being verifying by Chrome Web Store and MS Edge Add-ons. So you may take a try.

**Comment by sunnyrahul25** [comment]
System remaps are working now, Thank you for the quick fix. I'll close the issue.
