### ISSUE TITLE
Unexpected permissions

### ISSUE THREAD

**Issue by forestmonster** [gdh1995/vimium-c#32]
@gdh1995, I saw in https://github.com/philc/vimium/issues/3307 you recommended your plugin, but I was surprised when I saw [this unexpected part of the vimium-c permissions](https://user-images.githubusercontent.com/39405/57094127-9d4d7600-6cc4-11e9-8218-039769dc5fb5.png). Can you explain those? I don't see that in your [privacy policy](https://github.com/gdh1995/vimium-c/blob/master/PRIVACY-POLICY.md).

**Comment by gdh1995** [comment]
It's used to "globally" disable image loading / JavaScript execution / ... on what websites you want, and commands "toggleCS", "enableCSTemp", "clearCS" need it.

For example, I disable image loading on most websites, and if I need some pages to have images for a while, I'll use `toggleCS` to re-enable the image loading. And all the settings will be reset on the next startup of Chrome. As for the `enableCSTemp`, it will re-open current page in incognito mode and enable image loading, so pages in normal mode are not affected.

The related permission name is  "contentSettings", and documents are https://developer.chrome.com/extensions/contentSettings . It can not allow Vimium C to send HTTP requests to websites.
