### ISSUE TITLE
"mapKey o <f6>" not working to have "o" trigger F6 key (focus on address bar)

### ISSUE THREAD

**Issue by chausies** [gdh1995/vimium-c#320]
In Firefox, pressing F6 puts the focus on the address bar, which is my preference over vimium's address list that pressing "o" gives you.

However, when I enter the custom key mapping "mapKey o <f6>", pressing "o" does nothing, and doesn't bring focus to the address bar.

Can this be fixed...? Alternatively, triggering "ctrl+L" would work just as well (same functionality as F6).

(Incredible work on this extension, by the way!)

**Comment by gdh1995** [comment]
maybe you misunderstood it - `mapkey` can not affect your browser, while it only works during Vimium C handles keyboard events.

No browsers have provided any API to hook a key as another. If you do want such a feature, please use system-level softwares like AutoHotKey.

Usage of mapKey
* simple layout translation: https://github.com/philc/vimium/wiki/Tips-and-Tricks#key-mapping
* map to different keys in different modes: https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout#mapkey-directive

**Comment by chausies** [comment]
Thanks. But is there any way to make the "o" key just bring focus to the address bar? Before Firefox Quantum, vimFX used to have that feature if I remember correctly.

**Comment by gdh1995** [comment]
no api to do so in the new web-extension platform.



---Original---
From: "Ajay Shanker ***@***.***&gt;
Date: Mon, Apr 5, 2021 20:43 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] "mapKey o <f6&gt;" not working to have "o" trigger F6 key (focus on address bar) (#320)




 
Thanks. But is there any way to make the "o" key just bring focus to the address bar? Before Firefox Quantum, vimFX used to have that feature if I remember correctly.

**Comment by chausies** [comment]
That's really unfortunate. But thanks for the responses! Keep up the great work.
