### ISSUE TITLE
All pages show "Vimium-c is not running on this page"

### ISSUE THREAD

**Issue by IzakMarais** [gdh1995/vimium-c#321]
I now get the following message on all web pages (and cannot use any Vimium-C functionality). 

>Vimium C is not running on this page
>
>Your browser does not run web extensions like Vimium / Vimium C on certain pages, usually for security reasons.
>
>Unless your browser's developers change their policy, then unfortunately it is not possible to make Vimium / Vimium C
(or any other web extension, for that matter) work on this page.
>
>Configure more on the options page. Version1.89.0.

Browser: Firefox 78.9.0esr (64-bit)

I suspect the Vimium-C upgrade to 1.89.0 triggered this.

**Comment by gdh1995** [comment]
Hello, v1.89.1 has been released on Firefox Add-ons to fix this issue, so you may take a try.

**Comment by IzakMarais** [comment]
Thanks.
