### ISSUE TITLE
can't export the config

### ISSUE THREAD

**Issue by gemini4545** [gdh1995/vimium-c#322]
version: 1.89.1
Firefox version: 87.0 (64 bit)
phenomenon: no response after clicking the "export config", but the 'import config" is OK, and the the " export config" on Edge is also OK.

**Comment by gdh1995** [comment]
Working around: open the Developer Tools and type `window.CurFFVer_ = 87`, and then `export` should work.

**Comment by gemini4545** [comment]
Sorry, you mean which Developer Tools?

**Comment by gemini4545** [comment]
> 
> 
> Working around: open the Developer Tools and type `window.CurFFVer_ = 87`, and then `export` should work.

Sorry, you mean which Developer Tools?

**Comment by gdh1995** [comment]
Um sorry I made a mistake and got a wrong name. The real working around is `window.g = 87`:

![image](https://user-images.githubusercontent.com/5547703/113818333-3424e600-97aa-11eb-98d2-48f96d7e3744.png)

**Comment by aemonge** [comment]
This doesn't work for me, the console won't recognized your suggestion:

![Untitled](https://user-images.githubusercontent.com/1322348/114689538-16113580-9d16-11eb-9131-86bbacc2a497.jpg)

**Comment by gdh1995** [comment]
window.g = 89



---Original---
From: "Andres ***@***.***&gt;
Date: Wed, Apr 14, 2021 17:39 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] can't export the config (#322)




 
This doesn't work for me, the console won't recognized your suggestion:

**Comment by aemonge** [comment]
Awesome !!!

I've miss read it q=
