### ISSUE TITLE
虎扑以及某些网站的视频无法用快捷键打开 必须使用鼠标点击

### ISSUE THREAD

**Issue by Stephen2252Ro** [gdh1995/vimium-c#323]
虎扑以及某些网站的视频无法用快捷键以及空格键播放，必须使用鼠标点击播放
![image](https://user-images.githubusercontent.com/64295584/114031183-1644a780-98b6-11eb-977b-e1448787a740.png)

**Comment by OnceThenEver** [comment]
So does twitter.

**Comment by JimMoen** [comment]
出现问题的版本，v1.89.0
_**在之前的版本中**_，在Bilibili的播放器页面，即便鼠标没有移动到播放器上让控制条出现，也可以识别诸如暂停，全屏等的按钮。之前版本的效果类似现在在youtube页面上的样子。但目前的1.89.0不能做到。（之前版本的crx不知道到哪里可以下载，release里面没有，故没有切换版本截图。但我之前经常使用）

- **Bilibili播放控制条不出现时无法识别按钮。**
![image](https://user-images.githubusercontent.com/32241529/116420934-009d1f00-a871-11eb-877e-487ed5a6f0ef.png)

- **Bilibili控制条出现之后可以识别。**
![image](https://user-images.githubusercontent.com/32241529/116421213-37733500-a871-11eb-95a7-267d4a8dfc35.png)

- **Youtube上不论播放控制条是否出现都可以识别到按钮。之前版本的Vimium C在Bilibili也是这样的。**
![image](https://user-images.githubusercontent.com/32241529/116421011-101c6800-a871-11eb-886d-49b58471cec5.png)
![image](https://user-images.githubusercontent.com/32241529/116421596-92a52780-a871-11eb-8f39-0f8b292b5c2d.png)

**Comment by gdh1995** [comment]
旧crx我也没了，后台只能看到最新crx，我有几个版本没存crx了。
你同时用firefox吗？它支持选择下载旧版插件。我过会也用chrome试试。也不一定是新版插件造成的，可能是B站改了……



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月28日(周三) 晚上10:43
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.******@***.***&gt;;
主题: Re: [gdh1995/vimium-c] 虎扑以及某些网站的视频无法用快捷键打开 必须使用鼠标点击 (#323)




 
出现问题的版本，v1.89.0
 在之前的版本中，在Bilibili的播放器页面，即便鼠标没有移动到播放器上让控制条出现，也可以识别诸如暂停，全屏等的按钮。之前版本的效果类似现在在youtube页面上的样子。但目前的1.89.0不能做到。（之前版本的crx不知道到哪里可以下载，release里面没有，故没有切换版本截图。但我之前经常使用）
  
 
Bilibili播放控制条不出现时无法识别按钮。
 
 

 
Bilibili控制条出现之后可以识别。
 
 

 
Youtube上不论播放控制条是否出现都可以识别到按钮。之前版本的Vimium C在Bilibili也是这样的。

**Comment by gdh1995** [comment]
确定了是B站改了自己的页面设计造成点不了。目前没有办法让 LinkHints 给隐藏时候的它们显示提示。

`LinkHints.click` 正在加强，下版本可以添加参数来强行选这类按钮。

**Comment by gdh1995** [comment]
做过类似功能，支持强行修改classname，也就是先 f 选择整行并修改class来显示出来按钮，再f选择要点的按钮。


用activatemodeToHover, 参数是:
toggle?: {
&nbsp; &nbsp; &nbsp; [selector: string]: string;
&nbsp; &nbsp; };



比如 toggle={".btn1":"btn-active","4#link-a":"larger\u0020red"} 表示：
* 在当前元素的祖先元素里匹配 ".btn1"，如果找到了，则切换其"btn-active"类名，并结束
* 找到当前元素第5层祖先，然后在其子树里找"#link-a"，找到后切换larger、red这两个类名，并结束


如果把4换成-1，比如"-1#foo"，则表示在当前提示元素的子树里找 "#foo"。


匹配顺序通常会是toggle对象的各属性的字面顺序，但不作保证；找到后就修改样式并结束遍历；可以同时修改多个样式。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月30日(周五) 晚上10:39
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.******@***.***&gt;;
主题: Re: [gdh1995/vimium-c] 虎扑以及某些网站的视频无法用快捷键打开 必须使用鼠标点击 (#323)




 
最好能让对应的按钮图标同时浮现出来；
 之前的状态是有 Hints，但不知道点的是什么，只能凭借对B站 UI 的熟悉程度来猜

**Comment by OnceThenEver** [comment]
@gdh1995 邮件回复里有转义失败的字符，看起来好乱

**Comment by gdh1995** [comment]
做过类似功能，支持强行修改classname，也就是先 f 选择整行并修改class来显示出来按钮，再f选择要点的按钮。

用activatemodeToHover, 参数是:
```
toggle?: {
      [selector: string]: string;
    };
```

比如 `toggle={".btn1":"btn-active","4#link-a":"larger\u0020red"}` 表示：
* 在当前元素的祖先元素里匹配 ".btn1"，如果找到了，则切换其"btn-active"类名，并结束
* 找到当前元素第5层祖先，然后在其子树里找"#link-a"，找到后切换larger、red这两个类名，并结束

如果把4换成-1，比如"-1#foo"，则表示在当前提示元素的子树里找 "#foo"。

匹配顺序通常会是toggle对象的各属性的字面顺序，但不作保证；找到后就修改样式并结束遍历；可以同时修改多个样式。
