### ISSUE TITLE
Fn + {down} triggers weird behavior

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#326]
![屏幕截图(257)](https://user-images.githubusercontent.com/66708845/114279838-2a7cd600-9a69-11eb-9715-e32c532efec3.png)
I was editing the _Shortcuts Customization_ field and tried to use `Fn ↓` to get to the end, but then the whole page scrolled down so that I can't see the things above.

**Comment by gdh1995** [comment]
`Fn` is not a "real" key, but just translate a key to another, according to hardware (and maybe system software) configurations.

So the key Vimium C got was not `Fn + ArrowDown`, and I guess it was `pagedown`. You may test what your browser sends to Vimium C by pressing keys on https://gdh1995.cn/vimium-c/keyboard-test.html .

**Comment by OnceThenEver** [comment]
I found `Ctrl+Fn+ArrowRight` is what I want.
Thanks for your enlightment.

**Comment by OnceThenEver** [comment]
k
