### ISSUE TITLE
about LinkHints.activateModeToHover

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#328]
![屏幕截图(258)](https://user-images.githubusercontent.com/66708845/114506369-46989700-9c64-11eb-8d28-0a2663ad1fd6.png)
![屏幕截图(259)](https://user-images.githubusercontent.com/66708845/114506373-48625a80-9c64-11eb-99ff-f71c1f84c44b.png)
I want to preview two Wikipreviews consecutively.

After the first `LinkHints.activateModeToHover`, continue the second one immediately, but the second preview didn't show, as though the virtual cursor hadn't left the first yet.

**Comment by gdh1995** [comment]
Give an example URL ?

**Comment by OnceThenEver** [comment]
@gdh1995
Is there any progress?

**Comment by gdh1995** [comment]
Not yet. I was fixing other found issues and adding some of my expected features. Fortunately they seems finished and I'm going to start this task in this Wednesday (or May).

**Comment by gdh1995** [comment]
Hello, you may try this version: [vimium_c-1.89.1-firefox-6db5c78.zip](https://github.com/gdh1995/vimium-c/files/6384809/vimium_c-1.89.1-firefox-6db5c78.zip), or [vimium_c-1.89.1-chrome-6db5c78.zip](https://github.com/gdh1995/vimium-c/files/6384810/vimium_c-1.89.1-chrome-6db5c78.zip) . How to try: https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package

**Comment by OnceThenEver** [comment]
One trivial issue:
After entering _chrome://extensions_-like pages, the focus is on the input field, then I use `Esc` to defocus, but the scroll commands don't work, and I have to use `Tab` several times to get to the right focus.

**Comment by gdh1995** [comment]
&nbsp;Do you have enabled the chrome-urls flag to let vimium c run on such pages?



---Original---
From: ***@***.***&gt;
Date: Wed, Apr 28, 2021 23:36 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] about LinkHints.activateModeToHover (#328)




 
One trivial issue:
 After entering chrome://extensions-like pages, the focus is on the input field, then I use Esc to defocus, but the scroll commands don't work, and I have to use Tab several times to get to the right focus.

**Comment by OnceThenEver** [comment]
Yeah, after several `Tab` finally did the scroll commands work, and before that did the Vomnibar show up.

**Comment by gdh1995** [comment]
1. By default, Vimium C won't grab back focus when it gets injected into `chrome://*` and `chrome-extension://.../*`.
2. You may use `f` to select a dark-red marker, which usually means it's a scrollable area (or a cross-origin iframe), and then scrolling commands should work using it.

**Comment by OnceThenEver** [comment]
I found it.
By the way, under which condition will HUD present?

**Comment by gdh1995** [comment]
&nbsp;It usually shows，unless your page （or iframe） is very small



---Original---
From: ***@***.***&gt;
Date: Fri, Apr 30, 2021 21:04 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] about LinkHints.activateModeToHover (#328)




 
I found it.
 By the way, under which condition will HUD present?

**Comment by OnceThenEver** [comment]
Usually? I seldom see _: scroll_-like things. There are only numbers mostly.

**Comment by gdh1995** [comment]
what did you mean when you said "HUD"?


In Vimium and Vimium C, it means the small tip block at the bottom-right corner, and when a viewport is too small (in width) to show the whole HUD, LinkHints will not show its status. Other commands show HUD if only needed, while not considering about viewport width.



---Original---
From: ***@***.***&gt;
Date: Fri, Apr 30, 2021 22:43 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] about LinkHints.activateModeToHover (#328)




 
Usually? I seldom see : scroll-like things. There are only numbers mostly.

**Comment by OnceThenEver** [comment]
Ah, sorry for the misunderstanding.
But is there any term dedicated to _: Scroll_-likes?

**Comment by OnceThenEver** [comment]
And just now, I found `LinkHints.activateModeToHover` doesn't show the link title.

**Comment by gdh1995** [comment]
I call it "box hint" (framr box or scrollable box).



---Original---
From: ***@***.***&gt;
Date: Fri, Apr 30, 2021 23:47 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] about LinkHints.activateModeToHover (#328)




 
Ah, sorry for the misunderstanding.
 But is there any term dedicated to : Scroll-likes?

**Comment by gdh1995** [comment]
Do you mean no text even when the option "use link name" is enabled?



---Original---
From: ***@***.***&gt;
Date: Sat, May 1, 2021 00:00 AM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] about LinkHints.activateModeToHover (#328)




 
And just now, I found LinkHints.activateModeToHover doesn't show the link title.

**Comment by OnceThenEver** [comment]
Is that a parameter? My code is:
`map b LinkHints.activateModeToHover`

**Comment by OnceThenEver** [comment]
![屏幕截图(11)](https://user-images.githubusercontent.com/66708845/116728933-21a07400-aa19-11eb-9f06-0d7087ad193b.png)

**Comment by gdh1995** [comment]
The tip of `[title]` is a built-in feature of browsers and there's no web-extension API to trigger it from JavaScript.
