### ISSUE TITLE
针对特定网页优化

### ISSUE THREAD

**Issue by colorsakura** [gdh1995/vimium-c#329]
有些网页有很多地方完全不会去点击，但是也有快捷键，就会导致按键提示局部填满。

**Comment by OnceThenEver** [comment]
举个例子？

“完全不会去点击”  这句话挺主观的

![屏幕截图(2)](https://user-images.githubusercontent.com/66708845/115134490-17f33580-a043-11eb-9b9f-65c610e926a6.png)
![截图2](https://user-images.githubusercontent.com/66708845/115134488-16c20880-a043-11eb-8b82-37bda1cf0ed7.png)

要是嫌多，可以输入一些单词开头的几个字母来筛选

**Comment by gdh1995** [comment]
Commands like `LinkHints.*` supports some options to use CSS selectors to filter out / add special page elements.

`LinkHints` 系列命令支持一些参数来筛选、添加要提示的元素，不过需要懂些 CSS 知识。

* `clickable` will mark matched elements as clickable / `clickable` 可以把相应元素标记成“可点击的”
* `match` will limit `LinkHints` to only show hints for specific elements / `match` 可以限制 `LinkHints` 只对特定元素显示提示
* `exclude` will exclude some elements from the list of found elements / `exclude` 最后生效，可以排除一些不想要的元素

For example, `map f LinkHints.activateMode clickable=".link,.button" exclude=".link-container"` will add `<i class="link"/>` and exclude `<div class="link link-container">...</div>` .

And the way to trigger different commands on different websites is in https://github.com/gdh1995/vimium-c/wiki/Map-a-key-to-different-commands-on-different-websites .

**Comment by colorsakura** [comment]
![image](https://user-images.githubusercontent.com/32534829/115137623-bb4f4500-a059-11eb-8ef0-f2174dd26450.png)
比如这样，一个地方有多个快捷按键。

**Comment by gdh1995** [comment]
上边这个一般是写网页代码的时候比较随心所欲，把鼠标点击的功能做出来就不管了，但没梳理键盘操作的情况，导致理论上两个框都能“点”，Vimium C没法排除外边那个框。

底下这个还多一个问题，是有的时候为了性能做了些优化，导致外边的框也”变得可以点“（SC、SM这俩，以及SC下边的），其实是有标准做法可以把它们标记成”自身不该被点“的，但是国内网站经常没人标，国外大网站有时候标的也不够细。

总之活用 `exclude` 吧，可以筛选掉任意元素，而且在所有 `LinkHints` 命令下都生效，理论上也不怎么影响LinkHints的启动速度。

**Comment by OnceThenEver** [comment]
> 底下这个还多一个问题，是有的时候为了性能做了些优化，导致外边的框也”变得可以点“（SC、SM这俩，以及SC下边的），其实是有标准做法可以把它们标记成”自身不该被点“的，但是国内网站经常没人标，国外大网站有时候标的也不够细。

是不是说 Vimium-C 判断一个元素能不能点击，是根据HTML源码里这个元素是否被标记成“不可被点击”？

**Comment by gdh1995** [comment]
主要是html，还有一些js代码控制的状态



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月18日(周日) 晚上7:02
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.******@***.***&gt;;
主题: Re: [gdh1995/vimium-c] 针对特定网页优化 (#329)




  
底下这个还多一个问题，是有的时候为了性能做了些优化，导致外边的框也”变得可以点“（SC、SM这俩，以及SC下边的），其实是有标准做法可以把它们标记成”自身不该被点“的，但是国内网站经常没人标，国外大网站有时候标的也不够细。
  
是不是说 Vimium-C 判断一个元素能不能点击，是根据HTML源码里这个元素是否被标记成“不可被点击”？
