### ISSUE TITLE
Clickable elements in  Canvas LMS's speedgrader

### ISSUE THREAD

**Issue by gdh1995** [gdh1995/vimium-c#33]
As said in https://github.com/philc/vimium/issues/3307#issuecomment-489230299, @smk291 you found Vimium C can not hint most elements on a special page, so I open this issue.

Basically, I think it's because the page has a big '<iframe>' and then wraps most content in it, while Vimium C has not implemented the feature of hinting links across all frames in a tab.

To find the real reason, could you provide the exact URL of the web page you mentioned?

**Comment by smk291** [comment]
The URL isn't public, so I can't share it. The problem does appear to be iframe related.

**Comment by gdh1995** [comment]
Okay, then it's indeed an issue caused by Vimium C giving up the feature of hitns across frames. I'll think about it again.

**Comment by gdh1995** [comment]
Just a note: Vimium has added back a similar feature of show hints in multiple iframes in the same time, and also supports FilteredHint now. The only limitation is that it requires iframes are in a same origin.
