### ISSUE TITLE
Open link in new tab breaks on amazon

### ISSUE THREAD

**Issue by ayroblu** [gdh1995/vimium-c#330]
Hi, I was searching: https://www.amazon.co.uk/s?k=cherry+rubber+o+ring+40A+thick&i=computers&ref=nb_sb_noss
And the `LinkHints.activateModeToOpenInNewTab` shortcut wasn't working for me. Specifically I opened the console and saw:
![image](https://user-images.githubusercontent.com/4915682/115231318-51907300-a10d-11eb-9204-248cae05ff22.png)
Other shortcuts like `LinkHints.activateMode action="focus"` and `LinkHints.activateModeToOpenIncognito` continue to work as expected

**Comment by gdh1995** [comment]
Strange. When I test on it, all LinkHints break down with such an exception ...

**Comment by gdh1995** [comment]
Um I forgot to update here. To work around this bug, you may turn off the advanced `Detect whether links are completely covered or not` option on Vimium C Options page.

**Comment by gdh1995** [comment]
Hello, v1.90.2 should have fixed this issue.
