### ISSUE TITLE
LinkHints.activateModeToOpenImage and private windows.

### ISSUE THREAD

**Issue by politicus** [gdh1995/vimium-c#331]
I just installed Vimium-C (Brave Browser v89.1.21.77) and found that when I activate LinkHints.activateModeToOpenImage from a private window the image is opened in a new tab but in a non private window.

If technically possible, would love to have the image opened in a new tab next to the tab in a private window I activated LinkHints.activateModeToOpenImage or at least have a "notification" (I am referring to the little rectangle that appears sometimes at the bottom of the window) that the image has been opened.

**Comment by gdh1995** [comment]
Why do you want a HUD message on a web page tab? Did the new image tab fail in making the non-incognito window foreground and active?

Vimium C opens its `pages/show.html` and insert a target image on the page, so the image URL won't occur in your history. And when opening images from incognito windows, Vimium C will tell your browser "not cache the image in local computer", to keep the effect of "incognito windows".

The cost of such a design is: 1) Some web servers don't allow such a method to load their images, and then Vimium C Display page can only show a tip of "broken"; 2) It seems that browsers won't use in-memory cache of target images, so it will download the image again.

If you don't want to use this mode, then you may use `keyword=""` to make Vimium C open a tab of an image URL in the same incognito window: for example, `map Fi LinkHints.activateModeToOpenImage keyword=""` .

**Comment by politicus** [comment]
Thanks you for your detailed answer!

Added `keyword` and it is working perfectly now. 

A little bit more about the context of my question. I like to use browser's windows as “session". Once I am done with one "task" I close all the tabs of the window. So when I am working in a private window I prefer that the links I open  in a new tab open in the same window I am in.

**Comment by gdh1995** [comment]
Where Vimium C opens an image tab if `keyword=""`?

**Comment by politicus** [comment]
In the same private window.

**Comment by gdh1995** [comment]
Do you mean common URLs will be opened in normal windows even when the current is a n incognito window?


What opens URLs? the openUrl command or Vomnibar?



---Original---
From: "Francois Albert ***@***.***&gt;
Date: Sun, May 2, 2021 20:59 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] LinkHints.activateModeToOpenImage and private windows. (#331)




 
Thanks you for your detailed answer!
 
Added keyword and it is working perfectly now.
 
A little bit more about the context of my question. I like to use browser's windows as “session". Once I am done with one "task" I close all the tabs of the window. So when I am working in a private window I prefer that the links I open  in a new tab open in the same window I am in.

**Comment by politicus** [comment]
I mean, when in private window, url of a picture will be opened in a new tab in the private window I am in.

Urls are opened with the LinkHints.activateModeToOpenImage command.

**Comment by gdh1995** [comment]
&nbsp;Sorry, I still can't get what did you mean.


&nbsp;Could you provide:
1. what's your key mapping rule related to this problem?
2.&nbsp; On what website (URL) did you test?&nbsp; What keys did you press?
3.&nbsp; (If you want to open a new tab containing an image)&nbsp; Where would the image tab be opened by Vimium C, when a current tab is private (incognito)?
4.&nbsp; Where do you want to put this tab? (Why did you say,&nbsp; you wanted to open in a private window and it did open in a same private window -&nbsp; This was what I got from your comments, but then I cann't get what's wrong with it).



---Original---
From: "Francois Albert ***@***.***&gt;
Date: Mon, May 3, 2021 04:05 AM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] LinkHints.activateModeToOpenImage and private windows. (#331)




 
In the same private window.

**Comment by gdh1995** [comment]
Added: if your `activateModeToOpenImage` mapping has `keyword=""`, then it should open image tabs in a current window, even when the current is private.

If you want similar actions when there's no `keyword=""`, then this can only be implemented in a very far future version of Vimium C and after it is migrated to the web extension manifest V3.

**Comment by gdh1995** [comment]
> A little bit more about the context of my question. I like to use browser's windows as “session". Once I am done with one "task" I close all the tabs of the window. So when I am working in a private window I prefer that the links I open in a new tab open in the same window I am in.

Oh sorry I misunderstood what you said. I once thought you were asking a related question, so I hadn't got what you want - since `keyword=""` would have solved it.

Today I think there's no problem left about the first comment of this issue. Am I right? If not, feel free to reopen this.
