### ISSUE TITLE
Question: Possible to download image from cache?

### ISSUE THREAD

**Issue by Frederick888** [gdh1995/vimium-c#332]
Some websites doesn't allow loading images directly via their links, e.g. https://www.pixiv.net.

In such web pages, `LinkHints.activateModeToDownloadImage` `LinkHints.activateModeToDownloadLink` don't work while `Save Image As...` in Firefox context menu can still save the image. In fact, `Save Image As...` works even when there's no Internet connection, as long as the image has been loaded (not sure if it takes cache control headers into consideration though).

I'm wondering if it's possible to do this via Vimium C?

**Comment by gdh1995** [comment]
Are you using Vimium C v1.89.1 ?  Go to Vimium C Options page, check the optional permission item named "`Let browser download files`", and then click "Save Options" and confirm you allow it. Then Vimium C will use Firefox's standard process to download an image.

**Comment by gdh1995** [comment]
If Vimium C has owned the optional permission, but it still fails in downloading from cache, then it seems that there's no way to do so.

If it can download from cache, but fails in downloading images from some websites, then it may be because of lacking of the `Referer` header, and I'll add such an HTTP header in a next release of Vimium C (refer: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download#:~:text=Referer%20header).

**Comment by Frederick888** [comment]
Wow, thanks for your quick response.

But unfortunately it still doesn't download the images from Pixiv after enabling the option.

I think 'Firefox's standard process' is probably:

1. Request the HTTP headers
2. Check cache and cache control headers
3. If cache is not present or has expired: proceed with the HTTP request for a fresh copy
4. If cache is still valid: extract data from cache directly

It seems that 'Save Image As...' does its trick to skip 1-3 which allows downloading even without network. It works as if Firefox were in offline mode. Not sure if there's a browser extension API for this... :(

By the way, in web pages where Vimium C can normally download images, after enabling File -> Work Offline, it stops working while 'Save Image As...' is still functional.

**Comment by gdh1995** [comment]
Does Vimium C's `downloadImage` work on Pixiv in a default online mode of Firefox ? On my MS Edge 89, it opens image URL in a current tab, instead of triggering download action...

**Comment by Frederick888** [comment]
I'm using Firefox 89 and Vimium C 1.89.1 under Linux, and `activateModeToDownloadImage` always opens images in a new tab not only on Pixiv but also all other websites I've tested.

`activateModeToDownloadLink` downloads images directly.

**Comment by gdh1995** [comment]
Hello, please test this version: [vimium-c-1.89.1-firefox-debug-56b4cda9.zip](https://github.com/gdh1995/vimium-c/files/6352619/vimium-c-1.89.1-firefox-debug-56b4cda9.zip) (how to test: https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package ).

It should support downloading images on Pixiv on Firefox, though on Chrome it still opens image URL in a current tab.

**Comment by gdh1995** [comment]
As for reusing cached data, unfortunately I can not find any browser API to do this.

**Comment by Frederick888** [comment]
Yup I can confirm Vimium C can download images on Pixiv now. Thank you!

Regarding the cache thing, if there's no API for this, please feel free to close this ticket :)
