### ISSUE TITLE
Opening a bookmarklet and mapping to another key sequence

### ISSUE THREAD

**Issue by srikat** [gdh1995/vimium-c#333]
Hi,

Two questions.

I am wondering if it is possible to set up a key say `p` to trigger a bookmarklet that opens a Pinboard popup (the first one [here](https://pinboard.in/howto/))

Also, I would like to know if it is possible to map a key press to a key combo. Ex.: `i` to Cmd + Opt + C (for inspecting elements on the page).

Thanks in advance.

**Comment by gdh1995** [comment]
There's no command to trigger a bookmark item, but Vimium C's `openUrl` command supports an option of `url`, and its value can be `"javascript:..."`:
```
map <a-b> openUrl url="javascript:alert(123)"
```

Note: option values should not include space characters - considering that it is a JSON, then you may write something like `url="javascript:\u0020alert(123)"` if you do need spaces.

====

There's neither web-extension API to change how your browser handles keyboard events and shortcuts, nor API to open the "Developer Tools" window. So the answer is "impossible" to do so.

**Comment by srikat** [comment]
For anyone else interested in this, here's what I am using:

```
map p openUrl url="javascript:if(document.getSelection){s=document.getSelection();}else{s='';};document.location='https://pinboard.in/add?next=same&url='+encodeURIComponent(location.href)+'&description='+encodeURIComponent(s)+'&title='+encodeURIComponent(document.title)"
```

I couldn't get the `popup` bookmarklet code working w/o browser prompting to accept popups. So had to use the `same page` one.

Ref.: https://pinboard.in/howto/
