### ISSUE TITLE
goPrevious and goNext should only search for the links in screen

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#334]
In many situations, the webpage includes several links to go to the previous or the next, but currently `goPrevious` and `goNext` will match the very first link containing the keyword from a range of the whole page.

I think it's appropriate to have the range being the screen, like `LinkHints.activate`.

**Comment by gdh1995** [comment]
Patterns of `goNext` supports CSS selectors which start with `"."`, `"#"` or `"["`. For example, it can be `.btn-prev,#prev,prev,previous`.

The command also supports an option named `patterns` to override the default pattern options:
```
// for a special website
map <v-gp1> goNext isNext=false patterns=".btn-prev,#prev-btn"
map <v-gn1> goNext isNext=true patterns=".btn-next,#next"
```

**Comment by gdh1995** [comment]
And since v1.87.0, * `goNext`: support substituting a tab URL and jumping to it
  * need to convert the index number of URL into `${index[/[min]:[max]:[step]]}` first
  * the default key of substituting is `n`, and `goNext` now supports `sed`
  * the later parts are optional, and the shortest format is `${curIndex}`
  * `goNext` will use a new URL of `index + step`, or find an element as a fallback if a tab URL is not converted
  * if `absolute`, then use command count as the new index
  * now can skip checking the `rel` attribute by `noRel`

For example, for GitHub issues and pull requests, here's a way to go to next/previous items:
```
# in the below rules, step=2, which means 334 will be followed by 336/332
map <f6> goNext sed="n;(issues|pull)/(\\d+);$1/$${$2/::2};" isNext=false
map <f7> goNext sed="n;(issues|pull)/(\\d+);$1/$${$2/::2};" isNext
```

**Comment by OnceThenEver** [comment]
I'd like to make my situation more explicit.

![截图1](https://user-images.githubusercontent.com/66708845/116044858-fda10380-a6a3-11eb-87f8-e5ddfcea99da.png)

The red circle is what I want.

![截图2](https://user-images.githubusercontent.com/66708845/116045090-422c9f00-a6a4-11eb-95f7-2433866bbf17.png)

After `goPrevious` the page jumped back into the top and matched my abnormal id, which is just a coincidence.

**Comment by gdh1995** [comment]
```
env tieba host=":https://tieba.baidu.com/"
map ]] runKey expect={"tieba":"<v-tiebanext>"} keys="<v-gonext>"
map <v-gonext> goNext
map <v-tiebanext> goNext exclude=".u_username_wrap,#com_userbar,#user_info,[target=_blank],body"
```

goPrevious 类似

**Comment by gdh1995** [comment]
等下个版本里，`<v-tiebanext>` 就可以写成 `<v-tieba_next>`、`expect`可以是`expect="tieba:<v-tieba_next>,site2=<v-site2_next>"`了，不需要套大括号和引号套，读起来会省事不少。

**Comment by OnceThenEver** [comment]
I have considered my problem again, and now I think my situation is too singular, whereby the current behavior of searching for the whole page has its own advantage in that when reading the content in the middle, one don't have to jump to the bottom to go previous or go next.&nbsp;
I'll pick your opinion. Thank you!

---Original---
From: "Dahan ***@***.***&gt;
Date: Mon, Apr 26, 2021 16:59 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] goPrevious and goNext should only search for the links in screen (#334)




 env tieba host=":https://tieba.baidu.com/" map ]] runKey expect={"tieba":"<v-tiebanext&gt;"} keys="<v-gonext&gt;" map <v-gonext&gt; goNext map&nbsp;<v-tiebanext&gt;&nbsp;goNext exclude=".u_username_wrap,#com_userbar,#user_info,[target=_blank],body"  
goPrevious 类似
