### ISSUE TITLE
Is it possible to map a key to another extension's commands?

### ISSUE THREAD

**Issue by NightMachinary** [gdh1995/vimium-c#336]
Is it possible to map commands from another extension?
![image](https://user-images.githubusercontent.com/36224762/116224774-4a4d1300-a766-11eb-88e2-dd72d495aba0.png)

E.g., I like to map this extension's `Find or create` to `o`.

**Comment by gdh1995** [comment]
Usually it requires the target extension is able to accept external messages from other extensions.

Vimium C has a command named `sendToExtension`, and its usage is like:
```
map <f6> sendToExtension id="hfjbmagddngcpeloejdejnfgbamkjaeg" raw data={"key":"value"}
```

**Comment by gdh1995** [comment]
According to its Firefox version (https://addons.mozilla.org/en-US/firefox/addon/workona/) , it does accept external messages and has abundant actions to respond on those messages.

You can search `ExtensionMessage.FAV_ICON_URL` in its `background.js` and read code to find what message you need.
