### ISSUE TITLE
能否添加一个“将网页翻译成中文”的快捷键

### ISSUE THREAD

**Issue by Stephen2252Ro** [gdh1995/vimium-c#337]
![image](https://user-images.githubusercontent.com/64295584/116444226-7ca65f80-a88f-11eb-9e73-06f1c4d06efb.png)

**Comment by gdh1995** [comment]
There's no browser API for web extensions to call this native function. you may install some extensions, like SalaDict, and configuring a few shortcuts on `chrome://extensions/shortcuts` to trigger their commands.

**Comment by Joker-jiajiahui** [comment]
> Web 扩展没有浏览器 API 来调用此本机函数。你可以安装一些扩展，比如 SalaDict，并配置一些快捷方式`chrome://extensions/shortcuts`来触发它们的命令。
> 
> 或者您可以使用系统级键盘工具，如 AutoHotKey ( http://ahkcn.github.io/docs/Hotkeys.htm ) 来触发 Chrome 的菜单项。
> 
> 这个功能不开放，没法控制，建议转换成第三方扩展，像 saladict ( [#247 (comment)](https://github.com/gdh1995/vimium-c/issues/247#issuecomment-749481669) )、edgetranslate ( #383 ) 。
> 
> 或者使用 AutoHotKey ( http://ahkcn.github.io/docs/Hotkeys.htm ) 做系统级别的快捷键，触发浏览器内部设置快捷键。



> Web 扩展没有浏览器 API 来调用这个本机函数。你可以安装一些扩展，比如 SalaDict，并配置一些快捷方式`chrome://extensions/shortcuts`来触摸它们的命令。
> 
> 或者您可以使用系统级键盘工具，如 AutoHotKey ( http://ahkcn.github.io/docs/Hotkeys.htm ) 来触发 Chrome 的菜单项。
> 
> 这个功能不开放，没法控制，建议转成第三方扩展，像 saladict ( [#247 (comment)](https://github.com/gdh1995/vimium-c/issues/247#issuecomment-749481669) )、edgetranslate ( #383 ) 。
> 
> 或者使用 AutoHotKey ( http://ahkcn.github.io/docs/Hotkeys.htm ) 做系统级别的快捷键，触摸浏览器内部设置快捷键。

autohotkey的具体方法您实现了吗，或者能否提供下具体的思路

**Comment by gdh1995** [comment]
AHK 的话，就是在特定快捷键下模拟鼠标点击就行了啊，比如鼠标移动到左上角，模拟右键，等一会模拟向下移动xx像素，然后模拟左键点击。具体怎么操作需要你再优化，比如某网站上左上角不合适的话，也可以不移动鼠标直接模拟右键，触发快捷键之前人工挪动鼠标到空白位置就行了

更省事的办法是，安装 SalaDict 扩展程序，然后配置全局快捷键，不过这样走的就不是浏览器内置的翻译器了，效果可能有点区别：
![image](https://user-images.githubusercontent.com/5547703/208288993-48161061-9324-4476-8c88-9a869bad0f91.png)
