### ISSUE TITLE
Help with excluded URL pattern

### ISSUE THREAD

**Issue by srikat** [gdh1995/vimium-c#338]
Hello,

I currently have the following pattern added in the excluded URLs list where I do not want Vimium C to work:

```
^https?\:\/\/.*\?ct_builder=true.*
```

However, it does not seem to work.

Some sample desired matching URLs:

```
https://example.com/?ct_template=page&ct_builder=true&ct_inner=true

https://example.com/?ct_template=main&ct_builder=true

https://example.com/sample-page/?ct_builder=true&ct_inner=true
```

Any ideas?

**Comment by gdh1995** [comment]
The first 2 URLs only have `&ct_builder=true`. The 3rd one should work.

BTW, `^https?\:\/\/.*\?ct_builder=true` is enough, because the tail `.*` is useless.

**Comment by gdh1995** [comment]
And, a faster regexp is `^$|[?&]ct_builder=true`

**Comment by srikat** [comment]
Thank you, it works.
