### ISSUE TITLE
Feature request: link hints on text matching regexp

### ISSUE THREAD

**Issue by cyberhuman** [gdh1995/vimium-c#339]
I have the following custom search engine in the configuration:
```
u|uid|uuid|id: https://site.com/uid/%s UID
```
And a keymap to activate it:
```
# activate link hints to the uid page
map gf LinkHints.activateModeToSearchLinkText keyword="uid"
```
But sometimes, the text I want to search for is not a link so I have to use the mouse to select it first and a binding with `autoOpen` to search for the selected text.
It would be nice if it was possible to activate the hints mode for arbitrary text matching a regexp on the page. For example if I know UIDs are integers I would do:
```
map gF LinkHints.activateModeToSearchText regexp="\d+" keyword="uid"
```

**Comment by gdh1995** [comment]
You may use the `match` option to use CSS selectors to select what elements to show hint for.

**Comment by gdh1995** [comment]
For example, if you want to search a User ID in `<div class="user-id">...</div>`, then you may write:
```
# 37 means "activateModeToSearchLinkText"
map gf LinkHints.click direct="element" mode=37 keyword="uid" match=".user-id"
```

And then LinkHints should auto find the element and then search its inner text.

**Comment by cyberhuman** [comment]
Thanks @gdh1995! I tried your suggestiion and it almost works. The issue I have is that the matching elements have some free-hand text containing the uid, not only the uid (that's why I mentioned "text matching regexp" in the title). So I tried to use the `re=` feature of custom search engines but I can't make it work:
```
u|uid|uuid|id: https://site.com/uid/$s{$1} re="uid:\+(\d+)" UID
```
Do you have any clues if it's possible to do?

**Comment by gdh1995** [comment]
`re=` is designed to parsing queries, but normal searching won't use it - only the `searchAs` command and Vomnibar will use it.

What you need is text substitution:
* open Vimium C Options page, and find `Substitution for clipboard text` in advanced options
* add a line like `u@uid:\+?(\d+)@@i,matched` to execute substitution
  * `u` is its context (types); `i` means to ignore cases
  * the regexp is `/uid:\+?(\d+)/i`
  * `,matched` means to throw away parts which are not matched by the regexp
* add a new option to the mapping of `gf`: `sedKeys="u"` . And then LinkHints will trigger the substitution rule.

**Comment by gdh1995** [comment]
I'm very happy to see existing features can mostly meet this need. And here're some improvements in a next released version:
* for LinkHints, string values of `mode` can represent all modes, and then you may write `mode="search"`
* I'll add a `textFilter` option to `LinkHints`, to only show hints for those whose text matches a regexp:
  * `textFilter` may be something like `/uid=/`
  * Note: this will affect LinkHints's initing speed, while `match=<css-selectors>` will (usually) speed up LinkHints

**Comment by cyberhuman** [comment]
Hi! I tried this suggestion above and it opens URL moz-extension://5f63a04b-2019-4cc8-a3f3-b9a9401216cf/<uid> which does not exist. I also tried to capture the search engine's URL in the regexp (even with `^https://mysiite\.com/` so it certainly starts from the beginning) and substitute it, but it opens moz-extension://5f63a04b-2019-4cc8-a3f3-b9a9401216cf/https://mysite.com/<uid>.
So I see two problems here:
- with `,matched` the search engine's URL will be removed;
- moz-extension://.../ is always prepended to the result.

**Comment by gdh1995** [comment]
um, could you provide your whole substitution rule?


maybe I do need to change its logic.



---Original---
From: "Raman ***@***.***&gt;
Date: Sun, May 16, 2021 11:04 AM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Feature request: link hints on text matching regexp (#339)




 
Hi! I tried this suggestion above and it opens URL moz-extension://5f63a04b-2019-4cc8-a3f3-b9a9401216cf/ which does not exist. I also tried to capture the search engine's URL in the regexp (even with ^https://mysiite\.com/ so it certainly starts from the beginning) and substitute it, but it opens moz-extension://5f63a04b-2019-4cc8-a3f3-b9a9401216cf/https://mysite.com/.
 So I see two problems here:
  
with ,matched the search engine's URL will be removed; 

moz-extension://.../ is always prepended to the result.

**Comment by cyberhuman** [comment]
> um, could you provide your whole substitution rule?
```
u@user\+id\+?(\d+)@@i,matched
```
The original URL looks like `https://mysite.com/user+id+12345+some+other+text`.
After the substitution the URL is `moz-extension://5f63a04b-2019-4cc8-a3f3-b9a9401216cf/12345`.

**Comment by gdh1995** [comment]
Well, it's a logic issue when handling substitution rules: Vimium C currently applies `keyword` to create a URL before doing substitution, so it converts a normal to `12345`, and then your browser treats as a part of URL relative to Vimium C's origin.

As a working around, you may change the substitution rule to:
```
u@user\+id\+?(\d+)@$1@i
```

The `$1` is a syntax of RegExp in JavaScript, and it will refer the `(\d+)` part. When no `,matched`, a result string will also include non-matched parts, so normal `https://mysite.com/` will be kept.

====

I'll swap the two steps in a next version.

**Comment by cyberhuman** [comment]
Hey, I already tried the $1 syntax before and it's inserted after the extension URL.

**Comment by gdh1995** [comment]
what's your related key mapping, search engine rule, and substitution rule, when you use $1 ?


an ideal process is:
key mapping should apply keyword=u, and then u converts text to http://mysite.../... , and finanlly substitute it to correct its query part.



---Original---
From: "Raman ***@***.***&gt;
Date: Mon, May 17, 2021 06:47 AM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Feature request: link hints on text matching regexp (#339)




 
Hey, I already tried the $1 syntax before and it's inserted after the extension URL.

**Comment by cyberhuman** [comment]
I tried to reproduce the issue with the `matched` and it's gone. I'm sorry for the fuss.
The final substitution rule that works for me is:
```
u@(^https://mysite\.com/).*\buser\+id\+(\d+).*@$1$2@i
```
Notice that I have to remove the text around the user ID part, and also make sure not to remove the search engine URL, otherwise the browser falls back to this moz-extension://... thing.

**Comment by cyberhuman** [comment]
By the way, I consider this solution a kind of workaround. For example, if one element has two UID it's only possible to open the first of them this way. I was thinking how it could work is to use the text search feature and show the link hints beside each highlighted text (is that even possible with the browser's API?)

That being said, I really appreciate your efforts put into the development and support of this extension. Keep up a good work! 👍🏻

**Comment by gdh1995** [comment]
It's too technically complicated to use the Find API to match a N-th link, and I think it will prevent users from figuring out what will be found easily.

If an element with two `#text` of UIDs has children nodes, then you may use `match` to select its children, instead of the outer element itself.

**Comment by cyberhuman** [comment]
> It's too technically complicated to use the Find API to match a N-th link, and I think it will prevent users from figuring out what will be found easily.

Okay :-(

> If an element with two `#text` of UIDs has children nodes, then you may use `match` to select its children, instead of the outer element itself.

Unfortunately there is only one `<p>` with all the text inside.

**Comment by gdh1995** [comment]
&nbsp;You may use another substitution rule to extract the second uid



---Original---
From: "Raman ***@***.***&gt;
Date: Mon, May 17, 2021 12:07 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Feature request: link hints on text matching regexp (#339)




  
It's too technically complicated to use the Find API to match a N-th link, and I think it will prevent users from figuring out what will be found easily.
  
Okay :-(
  
If an element with two #text of UIDs has children nodes, then you may use match to select its children, instead of the outer element itself.
  
Unfortunately there is only one <p&gt; with all the text inside.

**Comment by cyberhuman** [comment]
> You may use another substitution rule to extract the second uid

Yes thanks 😄  But at that point, it becomes too many workarounds and another binding to remember, which is hard because it's seldom used. So I would just use mouse to select the interesting part 🤷🏻‍♂️

**Comment by gdh1995** [comment]
Hello. Since v1.90.0, Vimium C's performFind supports count, `restart` and `query`, so there's another way to search N-th item:
```
map <f6> performFind query="\\ruid:\\+\\d+" restart $then="<v-uid>"
map <v-uid> autoOpen sedKeys="u" keyword="uid" reuse="new-bg"
```

Then, `3<f6>` will: search for `uid:+........` by 3 times, from a current caret position, and then when found, it calls `autoOpen` to extract the number from selected text and opens `uid` search engine in a new background (inactive) tab.

`restart` is used to support continuous actions, like `2<f6>3<f6>5<f6>`.
