### ISSUE TITLE
[Feature Request] add a way to disable (per site or globally) LinkHints activating for things with .onclick handler

### ISSUE THREAD

**Issue by tobez** [gdh1995/vimium-c#34]
Normally, having .onclick covered by link hints is a good thing.
However, in some instances it becomes incredibly annoying.
Please compare attached screenshot, one for Vimium C, one for stock Vimium, to see what I mean. (The site on the screenshots is stories.duolingo.com, if that helps).

Vimium C:  
<img width="945" alt="Vimium C" src="https://user-images.githubusercontent.com/63679/57192325-82326e80-6f2f-11e9-8e19-29c3c1087050.png">

Stock Vimium:  
<img width="948" alt="Stock vimium" src="https://user-images.githubusercontent.com/63679/57192324-82326e80-6f2f-11e9-8a69-45e5b6453571.png">

Thanks!

**Comment by gdh1995** [comment]
Is it a translation website? Then I think the words are indeed clickable, and https://cn.bing.com/dict also make words clickable.

If you agree that only a few pages need the feature to be disabled, you may use `<Shift-F2>` to toggle this feature.

**Comment by tobez** [comment]
It is a language learning site, so close enough.  The individual words and expressions are not really clickable in a meaningful way (the translation is shown on mouse hover).

That said, I did not know about <Shift-F2>, and that works perfectly for my needs.  Is it documented somewhere?

Thanks.

**Comment by gdh1995** [comment]
Sorry but currently Vimium C has few documents and most small features can only be got from its source code.

In fact, when LinkHint is activated:
* `<f1>` works as `<backspace>`
* `<f2>` and `<c-f2>` (also `<m-f2>` on Mac) are to toggle the option `Search shadow DOMs in "url" / "image" mode by default` on a current page
* `<a-f2>` is to toggle `dialog mode` of LinkHints
  * in this mode, hint markers are ensured to be topest - no page elements can cover them
  * but there's a fullscreen backdrop in this mode and real mouse click will be ineffective
* `<s-f2>` is to toggle whether to list those with click listeners
* `<a-s-f2>` and `<c-s-f2>` is to redo a search for elements with nonnull ".onclick" property
  * some pages use not `<div onclick="..."></div>` but `$("div")[0].onclick = function() {...}`
  * Vimium C will auto find all such cases which is assigned on page loading
  * if some `onclick` assignment occurs when a page is loaded, this shortcut may help

**Comment by tobez** [comment]
Thank you for the explanation.

I think that this issue can be safely closed, since <s-f2> does the trick.

\Anton.
