### ISSUE TITLE
a sound operation on the variants of LinkHints.activate

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#340]
Currently, `LinkHints.activate`'s several variants, including:
- LinkHints.activateModeWithQueue,
- LinkHints.activateModeToOpenInNewForegroundTab,
- LinkHints.activateModeToOpenInNewTab,

have their own unique distinguishing characteristics, and those characteristics can blend into new compound commands through the combination of `Ctrl` `Shift` or `Alt`. But in facing some webs' own inclinations, like whether open pages in new tabs or not, the above commands have inconsistent behavior with their HUDs on different pages. For example, there's no command indeed that can open a new page in the current tab if the web would open it in the new tab, but the HUD of `LinkHints.activate` says it can.

So I combed through the behaviors about opening pages and clicking, concluding the table below:

Trigger JS / Open Page | In the New/Current Tab | To New Foreground Tab | With Queue | Trigger (inclination dependent)
----------------------|----------------|-------------|-----|---------
Open Page | New | √ | √ | Ctrl + Alt
Open Page | New | √ |    | Ctrl
Open Page | New |  | √ | Alt
Open Page | New | | | Default / Shift
Open Page | Current  | | | Default / ×
Trigger JS* | Current | | | Default
Trigger JS | Current | | √ |Alt

\* Actually, this behavior is the same as the 4th and the 5th, namely clicking once.

I suggest a new parameter of `LinkHints.activate` to identify the users' inclination about whether to open a page in the new or current tab, `Ctrl` to toggle between _whether to new foreground tab or not_, `Shift` to toggle between _the users' inclination and the opposite_, and `Alt` to stay unchanged.

**Comment by gdh1995** [comment]
&nbsp;There's no way to detect whether a website will open a new tab or not. And more importantly,&nbsp; a web page itself can also dynamically decide whether to open a tab, in its javascript code.


&nbsp;The head-up-display is only a indicator about how Vimium C sends click events to webpages, but not a promise for the final result.



---Original---
From: ***@***.***&gt;
Date: Wed, May 5, 2021 18:42 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] a sound operation on the variants of LinkHints.activate (#340)




 
Currently, LinkHints.activate's several variants, including:
 1. LinkHints.activateModeWithQueue,
 2. LinkHints.activateModeToOpenInNewForegroundTab,
 3. LinkHints.activateModeToOpenInNewTab,
 have their own unique distinguishing characteristics, and those characteristics can mix into new compound commands through the combination of Ctrl Shift or Alt. But in facing some webs' own inclinations, like whether open pages in new tabs or not, the above commands have inconsistent behavior with their HUDs on different pages. For example, there's no command indeed that can open a new page in the current tab if the web would open it in the new tab, but the HUD of LinkHints.activate says it can.
 
So I combed through the behaviors about opening pages and clicking, concluding the table below:
 
Trigger JS / Open Page | In the New/Current Tab | To New Foreground Tab | With Queue | Trigger (inclination dependent)
 Open Page                               New                                        √                                √                             Ctrl + Alt
 Open Page                               New                                        √                                                                    Ctrl
 Open Page                               New                                                                           √                                  Alt
 Open Page                               New                                                                                                       Default / Shift
 Open Page                             Current                                                                                                       Default / ×
 Trigger JS*                              Current                                                                                                          Default
 Trigger JS                                Current                                                                        √                                  Alt
 * Actually, this behavior is the same as the 4th, the 2nd, and the 5th, namely clicking once.
 
I suggest a new parameter of LinkHints.activate to identify the users' inclination about whether open a page in the new or current tab, Ctrl to whether to new foreground tab or not, Shift to users' inclination with the opposition, and Alt to stay unchanged.

**Comment by OnceThenEver** [comment]
No, you don't have to detect that. I mean you can neglect webs' inclination and unify the behavior on different pages.

**Comment by gdh1995** [comment]
&nbsp;I cannot force those web page "buttons which want to open a new table" to open in a current table.&nbsp; Although for normal links, we are indeed able to open new tabs because we can read the href attribute.
&nbsp;If you do want to open in new tabs,&nbsp; You may use `newtab="force"`.
&nbsp; As for your other expectation, there's no method -&nbsp; Please remember,&nbsp; a web page can use JavaScript to do whatever it want, including changing how to open anchors, click buttons or even click a div.



---Original---
From: ***@***.***&gt;
Date: Wed, May 5, 2021 18:59 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] a sound operation on the variants of LinkHints.activate (#340)




 
No, you don't have to detect that. I mean you can neglect webs' inclination and unify the behavior on different pages.

**Comment by gdh1995** [comment]
Um using the same logic, it seems possible to
&nbsp;force vimium c to open a URL in a current tab -&nbsp;of course it can only be executed on an anchor.&nbsp; I may add an option to do so.
If you want a mode which overrides logic on anchors and still follow ctrl / shift / alt keys,&nbsp; Then there's indeed no such an option.
&nbsp;But I'm still doubting whether this option is useful for any other user.



---Original---
From: ***@***.***&gt;
Date: Wed, May 5, 2021 18:59 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] a sound operation on the variants of LinkHints.activate (#340)




 
No, you don't have to detect that. I mean you can neglect webs' inclination and unify the behavior on different pages.

**Comment by OnceThenEver** [comment]
> Please remember, a web page can use JavaScript to do whatever it want

Although I separate the behaviors into Trigger JS and Open Page, I recognize that they are not exhaustive. You may see the former as any clicking event other than Open Page, as far as Vimium-C can simulate.

> I cannot force those web page "buttons which want to open a new table" to open in a current table.
> it seems possible to force vimium c to open a URL in a current tab

I think to some extent forcing Vimium-C to open a URL in a current tab and forcing the webpage to do so are just different descriptions of one thing, because they have identical results.

> I may add an option to do so.

That's the key, which fixes up the drawback where the cross in the table lies.

**Comment by gdh1995** [comment]
not a same thing. if you force Vimium C to open an anchor in a current page, then it won't dispatch any "click" event to web pages.



---Original---
From: ***@***.***&gt;
Date: Wed, May 5, 2021 22:38 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] a sound operation on the variants of LinkHints.activate (#340)




  
Please remember, a web page can use JavaScript to do whatever it want
  
Although I separate the behaviors into Trigger JS and Open Page, I recognize that they are not exhaustive. You may see the former as any clicking event other than Open Page, as far as Vimium-C can simulate.
  
I cannot force those web page "buttons which want to open a new table" to open in a current table.
 it seems possible to force vimium c to open a URL in a current tab
  
I think to some extent forcing Vimium-C to open a URL in a current tab and forcing the webpage to do so are just different descriptions of one thing, because they have identical results.
  
I may add an option to do so.
  
That's the key, which fixes up the drawback where the cross in the table lies.

**Comment by OnceThenEver** [comment]
What's "dispatch"?
Is that replacing the URL-1 with URL-2 by immediately click it after URL-1?

**Comment by gdh1995** [comment]
"click an element" means dispatching "click" event (and some other events) to the page, with "target=the element".&nbsp; Usually a page will do some actions on the click event.
Before a click event, there are mousedown and mouseup events on the same target. if a page doesn't receive any click event, it may do nothing, bcause most pages won't deal with mousedown specially.



---Original---
From: ***@***.***&gt;
Date: Thu, May 6, 2021 01:33 AM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] a sound operation on the variants of LinkHints.activate (#340)




 
What's "dispatch"?
 Is that replacing the URL-1 with URL-2 by immediately click it after URL-1?

**Comment by OnceThenEver** [comment]
Thanks to your explanation, I understand that the behavior of the web is exclusively up to its designer.
And if you are going to only accept adding to force Vimium-C to open URL in the current tab, that would still be good.

**Comment by gdh1995** [comment]
Hello. v1.90.0+ has support `newtab="force-mode"`, and if with it, `LinkHints` will only open link in a new tab when HUD shows it's in newtab mode, and if the tip is "in current page", it will open link in a current tab (without dispatching any `click` event on `<a>`).

For any non-anchor element, `newtab` won't change how Linkhints simulates clicking.

**Comment by xfdj** [comment]
> For example, there's no command indeed that can open a new page in the current tab if the web would open it in the new tab, but the HUD of `LinkHints.activate` says it can.

@OnceThenEver Try `map f LinkHints.activate mode="open-link" reuse="current"`, it works for me. It is better than `map f LinkHints.activate newtab="force-current"`.
