### ISSUE TITLE
Cannot set dark mode as default style

### ISSUE THREAD

**Issue by mangkoran** [gdh1995/vimium-c#341]
I already followed the direction in [this comment](https://github.com/gdh1995/vimium-c/issues/27#issuecomment-475856879) but dark mode still not applied to vomnibar and others. `gn` worked but it resets back to light theme after restarting firefox.
![image](https://user-images.githubusercontent.com/57625126/117316686-61ed6f80-aebb-11eb-9178-a9985a01afdb.png)
After restarting firefox:
![image](https://user-images.githubusercontent.com/57625126/117317394-125b7380-aebc-11eb-9586-d8e7429fb5a3.png)

**Comment by gdh1995** [comment]
You can modify the "Vomnibar Options" option on Vimium C Options page, and add ` dark ` to its `styles` field. Note that `styles` should be a string of a list of words split by space characters.

(This comment is also for https://github.com/gdh1995/vimium-c/issues/179#issuecomment-833434864).

**Comment by mangkoran** [comment]
At first I am confused as there is no "Vomnibar Options", but turns out it's called " Vomnibar Serttings".

Thankyou! I will close this.
