### ISSUE TITLE
Exit insert mode with custom keybind

### ISSUE THREAD

**Issue by vlashada** [gdh1995/vimium-c#342]
Hi!

Is there any way to exit insert mode other than pressing esc? I would love to press "e" in insert mode, for instance

**Comment by gdh1995** [comment]
If you mean the auto-entered insert mode when an input box is focused, then `mapkey <e:i> <esc>` should work, and the meaning of `:i` can be got from https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout .

If you're using the `enterInsertMode` command, then currently Vimium C supports an option named `key` , and the usage is `map xxx enterInsertMode key="<a-c>"` .

And, as said in https://github.com/gdh1995/vimium-c/issues/325#issuecomment-817279359 , `key` requires a "long" key sequence, which will be changed in the next released version of Vimium C (the new rule is only to exclude `0-9`, `A-Z` and `a-z`) .

**Comment by vlashada** [comment]
Wow, thank you! I tried variants of escaping insert mode, but never thought of just mapping it to escape. Thank you for this super nice extension!!

**Comment by OnceThenEver** [comment]
`map ' openUrl url="vimium://status\u0020toggle\u0020^\u0020'"`
