### ISSUE TITLE
Browser window shifts to another screen

### ISSUE THREAD

**Issue by CinematicCow** [gdh1995/vimium-c#343]
Hi, whenever I use vim-c to full-screen a video on YouTube and then exit the full-screen, it automatically shifts the entire browser window to my other monitor on the left.

Browser Used : Mozilla Firefox for Ubuntu canonical - 1.0
Browser Version:  88.0(64-bit)
Operating System : POP OS
Operating System Version : 20.10 x86_64

**Comment by gdh1995** [comment]
Does this happen on Chromium + PopOS, or on other systems?

**Comment by CinematicCow** [comment]
I am closing this, as it seems the problem was with Firefox itself, reinstalled it and now it works fine.
