### ISSUE TITLE
macOS中的command键是否支持？

### ISSUE THREAD

**Issue by skystary** [gdh1995/vimium-c#344]
command键在自定义快捷键中要怎么写？还是说根本不支持？用m表示似乎没有用，<m-b>这种写法能别识别，但是并没有执行meta+b。我原本是想实现打开一个隐私窗口，但是并没有这个命令，vimium文档里写支持的createTab incognito，vimium-c也并不支持，花了5、6个小时阅读所有的英文内容，只找到了Vomnibar.activate incognito。

顺便说一下，vimium-c功能很强大，但是在设置中的很多内容缺乏介绍。比如为命令设置新的快捷键举的例子shortcut createTab position="end"，就完全不知道是干嘛的，下面的扩展阅读链接点进去也根本没提到这些用法。还有命令列表里的参数也都不知道要怎么使用。

**Comment by skystary** [comment]
又继续研究了几个小时，看到有介绍vimium的文章介绍<m-b>这种写法，意识到可能是一个bug，补充说明下我用的是 Firefox Nightly 90，macOS 11.3.1。
另外又发现一点不知道是bug，还是功能限制如此。如果另外一个扩展的快捷键是<a-c>，用mapKey c <a-c>并不能触发，似乎mapKey只能映射vimium-c自带的命令？

**Comment by gdh1995** [comment]
麻烦把你完整的创建窗口的那行配置贴出来，我看一下。
目前没有写每个命令的详细参数文档，主要还是我懒和忙的问题，这个，目前建议阅读源码分析一下，至少这个在源码里面，已经把每个命令的可以有的配置项，集中在两个地方列出来了。 Vwiki里面有一个所有命令的列表，那个页面上给了两个链接来指向这些参数列表所在的源文件。


&nbsp; Shortcut 是用来配置全局快捷键的，全局快捷键就是那种可以全局生效，但是它只能配置，几个到几十个，而且，只能是单个的键，不能是一串键


napkey，确实只能在插件内部生效，这个是浏览器限制做不到全局。想全局配置的话，你只能说用系统设置或者至少是在浏览器外独立运行的的软件，和浏览器平级的那种。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月12日(周三) 晚上11:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [gdh1995/vimium-c] macOS中的command键是否支持？ (#344)




 
command键在自定义快捷键中要怎么写？还是说根本不支持？用m表示似乎没有用，这种写法能别识别，但是并没有执行meta+b。我原本是想实现打开一个隐私窗口，但是并没有这个命令，vimium文档里写支持的createTab incognito，vimium-c也并不支持，花了5、6个小时阅读所有的英文内容，只找到了Vomnibar.activate incognito。
 
顺便说一下，vimium-c功能很强大，但是在设置中的很多内容缺乏介绍。比如为命令设置新的快捷键举的例子shortcut createTab position="end"，就完全不知道是干嘛的，下面的扩展阅读链接点进去也根本没提到这些用法。还有命令列表里的参数也都不知道要怎么使用。

**Comment by gdh1995** [comment]
呃 incognito 在createTab还真是不支持，我查查。

**Comment by gdh1995** [comment]
当前版本里可以换用 openUrl 命令，它也支持 incognito ，但仍然有限制，不会用隐私模式打开`chrome://newtab`，下一版本会修复此问题。也就是说，`map t openUrl incognito url="https://www.baidu.com"` 是可以的。

meta键的话，应该是 类似 `<m-t>` 的写法， 如果不生效，可能是被系统、浏览器拦截了。请打开 https://gdh1995.cn/vimium-c/keyboard-test.html 测一下 Meta+T 看会记录什么

**Comment by skystary** [comment]
谢谢，我不知道自己有没有能力看懂源码，不过有时间我先学习下。原来浏览器不能接收扩展发出的按键事件，看另一篇文档也提到扩展不能监听浏览器的夜间模式状态，只能定时查询。这种限制还是挺麻烦的，实现不了也没办法。但是同样也解释了mapKey t <m-t>不起效的原因，因为不能传递按键，扩展本身又没有<m->组合的按键。我试了下map <m-t> 到一个命令是有效的。

然后我把<m-t>和incognito组合在一起测试发现了一个新的bug，就是如果是map t或map <a-t>或map <c-t>都可以，但是map <m-t> openUrl incognito url="https://www.baidu.com"，既不会打开百度的网页，也不会在无痕窗口打开，只会打开一个普通的空白标签页。不论是Chrome和Firefox都一样有这个问题。

PS：希望下一版能修复Firefox配置导出的问题，我看别人也提了。顺便问下Firefox导出的配置能直接导入Chrome吗？如果不能浏览器的账号同步会同步vimium-c的配置文件吗？

**Comment by gdh1995** [comment]
看起来url、incognito都没生效，而且其他按键触发时可以，那么就是`map <m-t>`这个命令整个没生效，`<m-t>`被浏览器拦截了没发给Vimium C。

Firefox配置导出已经修了，只是还没发版。

能直接导入Chrome，绝大多数地方都兼容，甚至“自定义快捷键”里支持`$if={“browser”:1}`来根据浏览器类型决定是否生效，1表示chrome，2是firefox

按说Firefox下配置文件同步会正常起作用，但是去年吧有用户反馈不起作用。我自己就一台机子、没启用Vimium C的配置同步，不方便测试。你可以先试试，如果不同步的话就去看看控制台日志，有问题就贴上来吧，谢谢。

**Comment by skystary** [comment]
也不是按了没反应，打开了一个普通空白标签页，似乎是把参数都给忽略了。好奇于是去试了下省略url参数，结果 `map <c-t> openUrl incognito` 在Firefox里生效了，Chrome里只打开了普通标签，没办法打开无痕标签，但是 `about:newtab` 是两个浏览器都有效的。

**Comment by gdh1995** [comment]
`<c-t>`还是`<m-t>`？

空白的话，说明大概率是浏览器打开的，而不是Vimium C打开的。你在Chrome里注释掉 `map <c-t>`，保存后试试 `c-t`，应该还会打开空白页面。

测试命令参数的时候，建议别映射到组合键，直接 `map t openUrl .........` 然后按字母 T 更稳妥。

**Comment by skystary** [comment]
另外想问一个问题，有一个 `autoOpen` 命令似乎和 `openCopiedUrlInNewTab` 命令有类似的效果，只是更强大。实现上是先查询有没有选中的内容，如果没有就执行 `openCopiedUrlInNewTab` 一样的操作吗？还是说实现上会有区别，比如一个是会自动转换文字网址，一个遇到没有协议头的网址，比如`www.baidu.com`或`baidu.com`会作为搜索关键词？

**Comment by gdh1995** [comment]
浏览器自身快捷键里，有的优先级很高，但有的低可以被覆盖，具体试了才知道，印象中创建标签、关闭窗口的优先级都很高。

**Comment by gdh1995** [comment]
记不清……只是有个方向，然后临时去源码找找。

**Comment by gdh1995** [comment]
`autoOpen` 确实是先找选中文字，找不到的话就和 openCopiedUrlInNewTab 走的一样了。

* 如果是页面上的选中文字，就把它转网址，没https://没关系，看起来像网址就行；
* 如果是剪贴板文字，会尝试更多转换，比如去除两端引号、识别百度网盘分享链接的那种模板等
  * 还会纠正网址，比如 `0.0.0.0` 转成 `127.0.0.1`
  * 如果遇到 `vimium://` 的网址，就执行对应命令。参考 https://github.com/gdh1995/vimium-c/wiki/Vimium-inner-URLs

网址纠正可以自由配置，“处理剪贴板文字”这个配置也可以用于处理别的来源的文字，比如 “p”前缀的规则在 autoOpen 处理页面上的选中文字时也会用上。另外很多命令都支持 `sed` 选项，来自定义用哪个前缀。

**Comment by skystary** [comment]
“百度网盘分享链接的那种模板”是指能自动填充访问码？可以少装一个油猴脚本了吗？

后面的什么 “p”前缀的规则 `sed` 选项，我完全没理解。。。这里的自由匹配是指在 `autoOpen` 等命令后面增加参数使用吗？如果是，现在也没有文档介绍参数的使用。

**Comment by gdh1995** [comment]
不是，而是在openCopiedUrlInNewTab里自动找到里边的网址打开，不用手动删掉前后缀。

sed 还没文档，基础写法上类似 linux下 sed 命令，然后我改了前缀的用法，比如 `s/1/2/g` 表示在粘贴或复制的时候把文字里的 “1”都换成 “2”

其中“s”我称为动作前缀，换成“c”的话就是只用在复制的时候、“p”对应粘贴。规则里的前缀只能是英文字母，最长是6个字母。"s" 始终等价于同时写 ”c“ 和 ”p“。

* 如果一个规则是 `cpr/1/2/g`，则有 3 种条件下都会执行它，分别是”c“、”p“或”r“
* 对于`map xxx autoOpen sedKeys="rst" ...`，则会按照声明的顺序依次执行前缀含有“r”、“s“ 或 “t” 字母的替换规则

规则的主体部分就是非常像 sed 命令的正则替换写法了，
* `s/1/2/g` 中，“/”是分隔字符，标点符号或者超出ASCII范围的字符都行，比如换成冒号、叹号。
* 末尾的 “g” 是正则标志位，可以用 JS 支持的标志
* 正则标志位后，如果跟着 “,”、并接着“decode”之类的关键词，则表示额外操作，比如解码网址（%xx）等


具体看 `background/clipboard.ts#substitute_`

**Comment by skystary** [comment]
看了N遍以后我大概看懂了点，意思是说前缀可以是任意字母，但是scp是保留的，代表了动作？这里动作前缀有什么特殊性吗？难道在特定命令里不同的动作不被支持？比如 `autoOpen` 只支持 ”p“，写 `map xxx autoOpen sedKeys="ct" c/1/2/g` 不会被执行？

**Comment by gdh1995** [comment]
autoopen默认用 p，写sedkeys的话就只用sedkeys指定的字母



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月13日(周四) 晚上9:35
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.******@***.***&gt;;
主题: Re: [gdh1995/vimium-c] macOS中的command键是否支持？ (#344)




 
看了N遍以后我大概看懂了点，意思是说前缀可以是任意字母，但是scp是保留的，代表了动作？这里动作前缀有什么特殊性吗？难道在特定命令里不同的动作不被支持？比如 autoOpen 只支持 ”p“，写 map xxx autoOpen sedKeys="ct" c/1/2/g 不会被执行？

**Comment by skystary** [comment]
就是可以省略 `sedKeys` 直接写 `map xxx autoOpen p/1/2/g url="https://www.baidu.com"` ？那么多参数使用上有什么顺序吗？比如 `sedKeys` 一定要写在替换规则前面，url写在最后？那么其他的比如 `incognito` 写在什么位置有要求吗？

我一直在想这替换对普通用户有什么用，这应该是 vimium 对选中文字和剪贴板文字的内部处理方法吧？还有种功能就是我安装的“链接地址洗白白”油猴脚本，清洗各种网址后缀，获取原始地址。再后来又想到其实一些网址通过替换关键字，很容易获得文件的下载地址，也许这对普通用户还是挺有用的。以前还能批量替换http地址为https地址，不过现在是没什么用了。其他不知道还有哪些用途？

**Comment by gdh1995** [comment]
map命令的时候可以带参数，参数不讲究顺序；部分命令的参数可以叫 sedKeys ，sedKeys参数的值是几个英文字母；具体规则在高级设置里的“替换”那个配置项里写：

![image](https://user-images.githubusercontent.com/5547703/118226184-12113880-b4b9-11eb-8b9a-dfa76a0fcf64.png)


确实有写法可以直接在map的时候写替换规则，但不是你这么写，而是换成“sed”这个参数，比如`sed="s/1/2/g"`. 这时候规则始终生效，而不管前缀字母是什么（但还是要写上前缀字母）。

**Comment by gdh1995** [comment]
map命令的时候可以带参数，参数不讲究顺序；部分命令的参数可以叫 sedKeys ，sedKeys参数的值是几个英文字母；具体规则在高级设置里的“替换”那个配置项里写：

![image](https://user-images.githubusercontent.com/5547703/118227065-7f719900-b4ba-11eb-885f-26ff1b28749a.png)

确实有写法可以直接在map的时候写替换规则，但不是你这么写，而是换成“sed”这个参数，比如`sed="s/1/2/g"`. 这时候规则始终生效，而不管前缀字母是什么（但还是要写上前缀字母）。


你看这张图里是我配置的一些，确实主要是清洗知乎里的外链、京东手机分享链接之类的，也可以修正 `goUp`命令的 计算结果、在 `goNext` 里直接计算下一页的网址；从网页上复制出去的时候也能自动转换网址，比如把内网转外网。

**Comment by skystary** [comment]
原来如此，你不说都没注意到还有“处理剪贴板文字”这个选项
