### ISSUE TITLE
Custom clipboard substitution for different actions

### ISSUE THREAD

**Issue by cyberhuman** [gdh1995/vimium-c#346]
A bit related to #339, I can do:
```
map gf LinkHints.activateModeToSearchLinkText keyword="uid" match=".user-id" sedKeys="uid"

uid: https://site.com/uid/%s UID

uid@(^https://mysite\.com/).*\buser\+id\+(\d+).*@$1$2@i
```
and the substitution works. But when I try to use the same approach for copying:
```
map yf LinkHints.activateModeToCopyLinkText match=".user-id" sedKeys="uid"

uid@\buser\sid\s(\d+).*@@i,matched
```
the substitution is not invoked. Is this expected?

**Comment by gdh1995** [comment]
For substitution rules, `uid` means 3 conntext: `u`, `i` and `d`, so ``sedKeys="u"` and `u@user\+id\+(\d+).*@$1@i` should be enough.

**Comment by gdh1995** [comment]
`activateModeToCopyLinkText` should have applied `sedKeys`, and then it should copy the number characters. What did it copy in fact during your tests?

**Comment by cyberhuman** [comment]
> `activateModeToCopyLinkText` should have applied `sedKeys`, and then it should copy the number characters. What did it copy in fact during your tests?

Nothing is substituted. I'll check with one character like you suggested.
BTW this is an issue of this method: if substitution fails, the original string is used, but I'd like the whole operation to fail instead (maybe with a notification).

**Comment by cyberhuman** [comment]
Ok. I made the changes like you suggested and then figured out there was a bug in the substitution rule (I forgot to escape a plain-text `@` inside). It now works, sorry for the hassle!

**Comment by cyberhuman** [comment]
> For substitution rules, `uid` means 3 conntext: `u`, `i` and `d`, so ``sedKeys="u"`and`u@user+id+(\d+).*@$1@i` should be enough.

BTW in addition to the substitution failure issue above, I think the rules aren't documented well enough. The help text in the settings says:
> The prefix character may be c|p|s|i|g…; "c" means copying, "p" for pasting and "s" for both.

Are the characters that are mentioned applied automatically to all those operations? Can we use only the remaining characters from a-z for custom rules? Are uppercase and lowercase the same for this purpose?

**Comment by gdh1995** [comment]
Yes, it lacks documents ...

The substitution keys are case-insensitive.

Some commands have their default key characters, and the list of default keys seems growing by time (when I add new features). So if you use a used character in the rules, then it may be used in another mapped command (even when no `sedKeys` argument in its key mapping).

I also find this seems too bad and unstable, but I haven't found a sounding idea to define a range of characters free to use. Currently Vimium C converts such English letters into a 32-bit number (`1 << s[0] | 1 << s[1] | ...`), so it requires reworking before supporting other non-letter characters.

**Comment by gdh1995** [comment]
Since v1.90.0, the keys of substitution can be non-ASCII letters, like α, β and γ. And such names won't be taken up by Vimium C.
