### ISSUE TITLE
Set omnibar to only search in open tabs?

### ISSUE THREAD

**Issue by cocoonkid** [gdh1995/vimium-c#348]
Set omnibar to only search in open tabs?

**Comment by gdh1995** [comment]
You may use `map T Vomnibar.activateTabSelection`

**Comment by cocoonkid** [comment]
Apology for my ignorance and thank you for your  swift reply. Where can set this?  or is it a simple keyboardmapping?  because that conflicts with newtab. I couldn't find a spot to put that.

**Comment by gdh1995** [comment]
1. Open Vimium C's "Options" page (open `chrome://extensions/`, click "Vimium C" and then you can found an "Options" link/button)
2. Find the "Custom key mappings" option field and add `map T Vomnibar.activateTabSelection` to it
3. Click the "Save Options" button at the bottom of the page.
4. Then when CapsLock status is off, <kbd>Shift+T</kbd> should open `Vomnibar` and list opened tabs

`T` in the above `map ...` can be replaced by any other key sequence. The default mapping for `T` is indeed `createTab`, and if you write `map T ...`, it will auto override the default mapping.

**Comment by cocoonkid** [comment]
Thanks , so I understood i correctly. Thanks for taking the time to explain in details.

I was able to overwrite the default o now.

Best of luck in your endeavours!

**Comment by gdh1995** [comment]
BTW, here's a Wiki about "How to switch what to search in when keep Vomnibar showing" in Section 3 of https://github.com/gdh1995/vimium-c/wiki/How-to-...-on-Vomnibar .
