### ISSUE TITLE
Copy open tabs URLs to clipboard / Open all the URLs from clipboard in new tabs 

### ISSUE THREAD

**Issue by tinywrkb** [gdh1995/vimium-c#349]
This request for two different commands:  
* Copy the URLs of all the open tabs in the current window to the clipboard with EOL/CR-LF after each URL.
* Open all URLs from the clipboard as new tabs in the current window. Each URL is separated by EOL/CR-LF.

This is one of the reasons why I'm still going back to the unmaintained cVim/vb4c.

**Comment by gdh1995** [comment]
> Copy

There's a command named `copyWindowInfo`. Here's an example to copy URLs of tabs:
```
# format is used to stringify a browser.tabs.Tab instance
map <f6> copyWindowInfo format="${url}" join="\n"
```

# open all URLs

Accepted. I'll add it.

**Comment by tinywrkb** [comment]
> map <f6> copyWindowInfo format="${url}" join="\n"

Nice! I guess I should have looked at the CmdOptions/BgCmdOptions. Thanks!

**Comment by gdh1995** [comment]
Hello, now `openCopiedUrlInNewTab` and `autoOpen` support an option of `copied=urls|any-urls`. `urls` means Vimium C will detect whether text in clipboard includes some lines of URLs, and if true open tabs for them, else open or search it as a single line of text. `any-urls` means to always open as lines of URLs, when some of lines are not URL, convert them using the `keyword` option.

**Comment by tinywrkb** [comment]
Thanks! It's working here pretty well with Edge 91 and Vimium-C 1.90.1.

A related issue that I noticed is that `openCopiedUrlInCurrentTab` merges a multi-line clipboard text to a single URL. 
I think that the wanted behavior for `openCopiedUrlInCurrentTab` is to read the clipboard up to the first newline character or maybe to iterate over the lines up to the first line that contains a proper URL.

**Comment by gdh1995** [comment]
It's because I think "current" means one URL and one tab. You may use the "Auto substitution of various text" option to extract URLs in ways you like. https://github.com/gdh1995/vimium-c/issues/339 has an example about how to modify page/clipboard text.

**Comment by gdh1995** [comment]
BTW, v1.90.0 and v1.91.1 has some bugs. V1.90.2 has been uploaded and is waiting for reviewing by MS Edge store.

**Comment by tinywrkb** [comment]
> You may use the "Auto substitution of various text" option to extract URLs in ways you like. #339 has an example about how to modify page/clipboard text.

Doesn't it also affect the `openCopiedUrlInNewTab` command?  
I added `p@^(https://.*)\n.*@$1@` and while it fixed `openCopiedUrlInCurrentTab`, it breaks `openCopiedUrlInNewTab copied="urls"`.

> BTW, v1.90.0 and v1.91.1 has some bugs. V1.90.2 has been uploaded and is waiting for reviewing by MS Edge store.

Thanks for the heads-up, I actually hit the `goBack` issue and saw the multiple bug reports, and the suggested workaround works fine for me.

**Comment by gdh1995** [comment]
You may use another substitution key (https://github.com/gdh1995/vimium-c/issues/346) by `map ...  sedKeys="α"` and `α@...@$1@`

**Comment by tinywrkb** [comment]
Thanks! It's working perfectly.  
You should really need to mention the `sedKeys` in the `Auto substitution
of various text` section on the settings page.

> The prefix character may be... and it can be set to a custom value by mapped command with `sedKeys`.

Also, consider documenting this use case of handling multiple tabs clipboard text somewhere in the wiki. Basically, it's this mapping

```
map ya copyWindowInfo format="${url}" join="\n"
map p openCopiedUrlInCurrentTab sedKeys="α"
map P openCopiedUrlInNewTab copied="urls"
```
and the following substitutions
```
α@^(https://.*)\n.*@$1@
α@^(http://.*)\n.*@$1@
```

Thanks again.
