### ISSUE TITLE
Disable pattern

### ISSUE THREAD

**Issue by mimooh** [gdh1995/vimium-c#35]
In Vimium I could use *apainter* to disable vim keys. Here I need to provide the full  http://localhost/aamks/apainter/index.php URL?

**Comment by gdh1995** [comment]
Sorry but `localhost` means the website you're visiting is sent from a process on your local machine, so I can not visit it. Then, what's your real meaning of `use apainter to disable vim keys`?

If you means `map apainter enterInsertMode` in Vimium's key mappings, then Vimium C also support the `enterInsertMode` command, and it also support another way to disable itself totally, please refer https://github.com/philc/vimium/issues/3272#issuecomment-475296695 for more explanations.

**Comment by mimooh** [comment]
I want to disable vimium for any site containing word "apainter". Say this site: https://student.szach.in/aamks/apainter/index.php.

I get:
Vimium C keeps to be: enabled
after I type apainter or *apainter* into Patterns-input-field.

BTW, I'd like to have an empty new tab after pressing t. I setup Vimium C new tab to 
     pages/blank.html
The content of the page is blank, but address bar contains text chrome-extension://hfjbmagddngcpeloejdejnfgbamkjaeg/pages/blank.html which is problematic when I want to paste into address bar. Can I have the address bar blank?

**Comment by gdh1995** [comment]
You need to input `^$|apainter` in the `Patterns`.

It's because Vimium C has two formats of exclusion patterns:
* if a pattern starts with a "`:`" character, then it's treated as a string and Vimium C only executes prefix matching using it.
* if a pattern starts with a "`^`" character, then it's treated as a regular expression and Vimium C executes regexp matching using it.

This feature is designed for performance worries about too many exclusion rules.

**Comment by mimooh** [comment]
Works, thanks!

-- 
Karol Kreński

**Comment by gdh1995** [comment]
Just a tip: if you feel this issue is solved, you may close it.

**Comment by mimooh** [comment]
Thanks, it works.

**Comment by f1h0** [comment]
@gdh1995 
post here with a question

sites to be excluded.
```
https://www.site.com/p/[^CW].*/
```
such a construction gives errors and vim does not want to work

**Comment by gdh1995** [comment]
@f1h0 You may try a more accurate regexp:
```
^https://www\.site\.com/p/[^CW]
```

* the prefix of `^` character will ensure Vimium C executes regexp matching, but not string-prefix matching
* usually `.*$` and `.*/` is not as useful as a user expect

**Comment by f1h0** [comment]
> @f1h0 You may try a more accurate regexp:
> 
> ```
> ^https://www\.site\.com/p/[^CW]
> ```
> 
> * the prefix of `^` character will ensure Vimium C executes regexp matching, but not string-prefix matching
> * usually `.*$` and `.*/` is not as useful as a user expect

**error** 
![image](https://user-images.githubusercontent.com/1436880/224556196-2d577236-1ef9-497d-b4b9-1d3a2326c47b.png)

**Comment by gdh1995** [comment]
The red color means the regexp doesn't match a current URL.

You should write a real regexp including a real domain (hostname), but not the sample word of `www.site.com`.
