### ISSUE TITLE
changing default setting

### ISSUE THREAD

**Issue by Shahin-rmz** [gdh1995/vimium-c#352]
Hello, 
thanks for good repo.
how can we change default setting?
I want to setting be more like tmux and w3m, in terminal browser which I use pretty much for searching and writing the code. now because I use Jupyter Lab I need to use browser, and hopefully found Vimium-c.

**Comment by gdh1995** [comment]
Um, why did you close this?

To change its key mappings, you may open its options page, and edit "custom key mappings". The basic usages are just like [Vimium](https://github.com/philc/vimium)'s, and can be found in https://github.com/philc/vimium#keyboard-bindings and https://github.com/philc/vimium/wiki.

**Comment by Shahin-rmz** [comment]
Thanks for the quick response.
The reason that I've closed the issue, was that I was able to make the basic needed changes with the documentation of vimium.
Thanks anyways.
