### ISSUE TITLE
go-back function does not work in chrome Version 91.0.4472.77 

### ISSUE THREAD

**Issue by zzx41375004** [gdh1995/vimium-c#354]
如题，后退功能在chrome更新后似乎无法使用了

**Comment by gdh1995** [comment]
duplicated of #353



---Original---
From: ***@***.***&gt;
Date: Wed, May 26, 2021 12:25 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] go-back function does not work in chrome Version 91.0.4472.77  (#354)




 
如题，后面功能在chrome更新后似乎无法使用了

**Comment by zzx41375004** [comment]
thanks

**Comment by gdh1995** [comment]
v1.90.1 should have fixed it.

Some other bug are fixed in v1.90.2 .
