### ISSUE TITLE
Idea thread about Vimium C's security

### ISSUE THREAD

**Issue by 205g0** [gdh1995/vimium-c#357]
There was a post on HN about browser extensions and their security just yesterday[1] and since Vimium C is one of the best, if not the best vim extension and at the same time it needs a lot permissions just because of its nature, I thought it's good to have some information, discussion or whatever around this topic. Both related to Firefox and Chrome.

That Vimium C's code is open source and available on GH is a good start! In the HN thread was a guy who gets buying offers for his extension all the time and he documents those inquiries.[2] Maybe this would be a another great od step in the right direction.

I am looking forward to your ideas and I hope this thread is in the interest of the maintainer @gdh1995 as well! Dahan, please let us know if you would like to handle this topic in a different way and thanks again for your amazing work, we owe you something (next idea: maybe we should sponsor you 😃).

Edit: Just have seen the sponsor button haha, next idea, I would go one step further, Dahan. I would offer a premium subscriptions next to some one-off sponsorings and tbh, I would pay for it.

[1] https://news.ycombinator.com/item?id=27326268
[2] https://github.com/extesy/hoverzoom/discussions/670

**Comment by gdh1995** [comment]
Vimium C has a document about requested permissions: https://github.com/gdh1995/vimium-c/blob/master/PRIVACY-POLICY.md .

I make Vimium C out of interest and to satisfy my needs. I'm not interested in selling this extension to any companies, especially when I can not tell good companies from cheaters .

**Comment by gdh1995** [comment]
Firstly I'm very glad that you like Vimium C. Thanks for your appreciation.

There's only one published version for Vimium C - no "Pro" versions - although its packages published on Edge / Firefox / Chrome stores are different, they're usually compiled from a same version of source code and their behaviors are as same as possible.

Both of my PayPal account and Vimium C's OpenCollective account accept donations, although I haven't got idea about how to transfer money from OpenCollective to my PayPal ^_^
