### ISSUE TITLE
close firefox on x press, when its the last tab

### ISSUE THREAD

**Issue by MasterPiceControlled** [gdh1995/vimium-c#358]
Hi, could there be an option to close firefox when hitting x on the last (and only) tab?

Right now x is closing the tab, keeping firefox open (with an "empty url tab").
Can there be an option to instead just close firefox entirely (with no remaining "empty url tab")?

(like in https://github.com/philc/vimium)

- thanks

**Comment by gdh1995** [comment]
You need to add an option of "mayClose" to the mapping:
map x removeTab mayClose



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 1, 2021 02:53 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] close firefox on x press, when its the last tab (#358)




 
Hi, could there be an option to close firefox when hitting x on the last (and only) tab?
 
Right now x is closing the tab, keeping firefox open (with an "empty url tab").
 Can there be an option to instead just close firefox entirely (with no remaining "empty url tab")?
 
(like in https://github.com/philc/vimium)
  
thanks

**Comment by MasterPiceControlled** [comment]
ahh, I see, thank you very much
