### ISSUE TITLE
Hints Get Cut Off

### ISSUE THREAD

**Issue by syeare** [gdh1995/vimium-c#36]
For some reason, the hints get cut out when highlighting. I'm using the newest version of vimium on ungoogled-chromium 70. [Here's](https://i.imgtc.com/8VOKweG.png) an example (look closely at "Privacy and Cookie Policy" and "Subscribe with RSS").

**Comment by gdh1995** [comment]
What's your setting for Vimium C's "Characters used for link hints" option?

**Comment by gdh1995** [comment]
I tried some character sequences and found that `qwe asd zxc rty gh vbn` will generate the same snapshot, so please remove the space characters in it (aka, set it `qweasdzxcrtyghvbn`).

**Comment by gdh1995** [comment]
Latest Vimium C has supported auto-removing space characters from linkHint characters, so you just need to edit it on Vimium C options page and save it.
