### ISSUE TITLE
Feature request: close tabs with a specific domain

### ISSUE THREAD

**Issue by foodornt** [gdh1995/vimium-c#362]
How do I close tabs with a specific domain like `*youtube.com*` and `*twitter.com*`?

**Comment by gdh1995** [comment]
um,&nbsp; It seems currently there's no method to do so.
As a working around, you may use sortTabs and then press number + x to trigger removeTab.



---Original---
From: ***@***.***&gt;
Date: Sat, Jun 5, 2021 05:07 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] Q: How do I close tabs with a specific domain? (#362)




 
How do I close tabs with a specific domain like *youtube.com* and *twitter.com*?

**Comment by gdh1995** [comment]
Um, `sortTabs` only sorts tabs by recency.

I'll add this feature then. Maybe in months.

**Comment by foodornt** [comment]
oh no problem

can I somehow use `closeOtherTabs` and the filter thingy together to accomplish this functionality?

**Comment by gdh1995** [comment]
not in a current version...



---Original---
From: ***@***.***&gt;
Date: Sat, Jun 5, 2021 19:31 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Q: How do I close tabs with a specific domain? (#362)




 
oh no problem
 
can I somehow use closeOtherTabs and the filter thingy together to accomplish this functionality?

**Comment by gdh1995** [comment]
Hello, v1.92 has been published on Firefox and Chrome stores, and you may take a try.

You may write `map xxx closeOtherTabs filter="host"` to close such tabs:
* in a same current window
* whose URLs have a same host as the current tab's
* is not the current active tab

And if you write `map xxx closeOtherTabs filter="host" $then="removeTab" $else="removeTab"`, then it will also call `removeTab`, so all tabs which are in a current host will be closed.

You may also replace `$then=removeTab` with other commands / mapped keys, to call a command with arbitrary options you want. Wiki: https://github.com/gdh1995/vimium-c/wiki/Auto-run-a-tree-of-commands#run-a-key-after-a-command

**Comment by foodornt** [comment]
```
map <a-y> closeOtherTabs filter="youtube" $then="removeTab" $else="removeTab"
```
Closes all tabs, even non youtube tabs
even if I removed $else it still closes them

**Comment by gdh1995** [comment]
Um, what browser are you using? MS Edge? Or which version is your Vimium C in?

**Comment by gdh1995** [comment]
Sorry I've got what's wrong - `host` is a value word, but not a placeholder. Please change the mapping into:
```
map <a-y> closeOtherTabs filter="host" $then="removeTab" $else="removeTab"
```
to close "tabs which has a same hostname with the current tab and in a current window";

Or you may write
```
map <a-y> closeOtherTabs filter="host=www.youtube.com" $then="removeTab" $else="removeTab"
```

**Comment by foodornt** [comment]
YAY works now thank you
