### ISSUE TITLE
Search input loses focus

### ISSUE THREAD

**Issue by moosotc** [gdh1995/vimium-c#363]
For instance when pressing '/' on `https://github.com/gdh1995/vimium-c/issues/`
and starting to search for a string beginning with 'm' the input field loses focus. The issue
seems to depend on what, how, where search was done.
[vimium-options.json.txt](https://github.com/gdh1995/vimium-c/files/6602466/vimium-options.json.txt)

**Comment by gdh1995** [comment]
are you using Vimium or Vimium C?
what's your browser name, its version and system name?



---Original---
From: ***@***.***&gt;
Date: Sat, Jun 5, 2021 19:22 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] Search input loses focus (#363)




 
For instance when pressing '/' on https://github.com/gdh1995/vimium-c/issues/
 and starting to search for a string beginning with 'm' the input field loses focus. The issue
 seems to depend on what, how, where search was done.
 vimium-options.json.txt

**Comment by moosotc** [comment]
Dahan Gong ***@***.***> writes:

> are you using Vimium or Vimium C?
> what's your browser name, its version and system name?
>

vimium.. Looks as if i have barked up the wrong tree, sorry.

FWIW

- firefox -V
Mozilla Firefox 89.0

- uname -a
Linux archlinux 5.12.8-arch1-1 #1 SMP PREEMPT Fri, 28 May 2021 15:10:20 +0000 x86_64 GNU/Linux

**Comment by gdh1995** [comment]
it's a bug of Vimium, and I've filed a pull request to fix it, but it's not merged yet.



---Original---
From: ***@***.***&gt;
Date: Sat, Jun 5, 2021 19:31 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Search input loses focus (#363)




 Dahan Gong ***@***.***&gt; writes:
 
 &gt; are you using Vimium or Vimium C?
 &gt; what's your browser name, its version and system name?
 &gt;
 
 vimium.. Looks as if i have barked up the wrong tree, sorry.
 
 FWIW
 
 - firefox -V
 Mozilla Firefox 89.0
 
 - uname -a
 Linux archlinux 5.12.8-arch1-1 #1 SMP PREEMPT Fri, 28 May 2021 15:10:20 +0000 x86_64 GNU/Linux
