### ISSUE TITLE
is it possible to change find focus behavior?

### ISSUE THREAD

**Issue by MushiTheMoshi** [gdh1995/vimium-c#364]
Hi there,

   First of all, it's awesome the work you've done here , really appreciated. Is it possible to change the focus behavior so that the focus does not change until I hit enter ? since it would be nice sometimes when following tutorials or documents to copy commands  by looking for the occurrence. 

Thanks in advance,

Julio

**Comment by gdh1995** [comment]
Sorry. You said "does not change", but I can't get&nbsp; what and how currently changes when you use the FindMode bar.



---Original---
From: "Julio ***@***.***&gt;
Date: Sun, Jun 6, 2021 11:00 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] is it possible to change find focus behavior? (#364)




 
Hi there,
 
First of all, it's awesome the work you've done here , really appreciated. Is it possible to change the focus behavior so that the focus does not change until I hit enter ? since it would be nice sometimes when following tutorials or documents to copy commands  by looking for the occurrence.
 
Thanks in advance,
 
Julio

**Comment by MushiTheMoshi** [comment]
Hey, thanks. Well the focus moves to the first occurrence before you complete the word. I think that's the normal behaviour on chrome. Is it possible ?

**Comment by gdh1995** [comment]
are you using "Vimium" or "Vimium C"?
There's a very similar bug of Vimium, and I've filed a pull request to fix it, but it's not merged yet.




---Original---
From: "Julio ***@***.***&gt;
Date: Sun, Jun 6, 2021 11:40 AM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] is it possible to change find focus behavior? (#364)




 
Hey, thanks. Well the focus moves to the first occurrence before you complete the word. I think that's the normal behaviour on chrome. Is it possible ?

**Comment by MushiTheMoshi** [comment]
vimium c ...

**Comment by gdh1995** [comment]
oh sorry.
Then what's your system and chrome version?



---Original---
From: "Julio ***@***.***&gt;
Date: Sun, Jun 6, 2021 12:21 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] is it possible to change find focus behavior? (#364)




 
vimium c ...

**Comment by gdh1995** [comment]
> the focus moves to the first occurrence before you complete the word

Do you mean the caret moves and then prevents you from typing remaining letters in the bar of FindMode?

**Comment by MushiTheMoshi** [comment]
I'm sorry let me explain again. Is not a bug, is not a bad behaviour, is the actual behaviour of the browser search. I'm using Linux / Brave. When I'm in insert mode at the time I'm typing the search is simultaneously executed, so if I type "na" is colouring already the word "na" and it changes the document location where first "na" occurrence is,  then I complete "name" an it moves the focus in the document to "name" first occurrence, I would like to change that behaviour so that only changes the document position when I complete the word "name".

**Comment by gdh1995** [comment]
Well, then I need to add a command option to support this feature.

**Comment by MushiTheMoshi** [comment]
no I think, it'd be nice a caret/visual improved wiki entry, as I'm doing it as (v - c, c - v ) as per vimium wiki and sometimes the cursor is too far from the current document position making the copy selection a bit complicated. I think I can use the current caret, to be honest I think is not really necessary and is a very particular case. Thank you so much for your prompt responses and the kind help. Regards

**Comment by gdh1995** [comment]
Um, maybe I misunderstand what you said in the last comment, but it seems you don't expect "not running find until an Enter key" any more?
