### ISSUE TITLE
[Q] How do I map `CMD+SHIFT+LEFT` to `Move tab to the left`?

### ISSUE THREAD

**Issue by NightMachinary** [gdh1995/vimium-c#368]
How do I map `CMD+SHIFT+LEFT` to `Move tab to the left`? 

I think it should be possible with
![image](https://user-images.githubusercontent.com/36224762/121546615-acb15880-ca20-11eb-8b2a-b378defebd91.png)

But I can't find the docs for these custom shortcuts.

Unrelated: `<a-p>` (which I assume is `option+p` on macOS) for pinning a tab doesn't work for me.

**Comment by gdh1995** [comment]
Add `shortcut userCustomized1 command="moveTabLeft"` to the key mapping textbox.

**Comment by NightMachinary** [comment]
@gdh1995 BTW, can we have more of these custom shortcuts? 2 aren't enough.

**Comment by gdh1995** [comment]
Please open Vimium C Options page, find `Ignore keyboard layout` and partly check it.

If "partly checked" doesn't work, you may try:
* make it fully checked
* use `mapKey` to translate keys. see
  * https://github.com/gdh1995/vimium-c/wiki/Map-the-keys-composed-with-Option
  * https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout#an-example-for-cyrillic-layout-russian-and-ukrainian

**Comment by NightMachinary** [comment]
@gdh1995 Umm, I think you replied to the wrong thread :-? 

PS: Thanks, that worked like a charm.

**Comment by gdh1995** [comment]
See the 2nd comment of this issue - I've added a snapshot to address the useful help text on Vimium C Options page.

There's a helper extension to provide 32 shortcuts in the link of `More`.

**Comment by gdh1995** [comment]
> @gdh1995 Umm, I think you replied to the wrong thread :-?
> 
> PS: Thanks, that worked like a charm.

Which comment did you mean? The one saying `Ignore keyboard layout`?

BTW, the option of `Ignore keyboard layout` should have been partly checked on macOS by default, if your Vimium C was installed recently - I once changed its initial value on macOS for new installation, but not modify configuration of old users.

**Comment by NightMachinary** [comment]
Oh, right. It was for `a-p`, and it did work! Thanks again.

**Comment by gdh1995** [comment]
> @gdh1995 BTW, can we have more of these custom shortcuts? 2 aren't enough.

If you don't need the 6 pre-defined shortcuts, you may also override them by mappings like:
```
shortcut createTab command="goNext"
```

Both `createTab` and `userCustomized1` are shortcut names, and can be found in https://github.com/gdh1995/vimium-c/blob/master/manifest.json#L37
