### ISSUE TITLE
Edge 上扩展更新后，旧网页上快捷键没反应

### ISSUE THREAD

**Issue by ABackerNINI** [gdh1995/vimium-c#369]
没有禁用VimC的情况下对有些tab没反应,同时另外一些tab正常.没反应的tab按刷新按钮后该tab恢复正常.

猜测可能是EDGE的tab休眠引起的,没仔细测试.不过这个休眠功能很早就出了,之前没问题,可能是1.90.2的问题.

Vimium C 1.90.2，MS Edge 91，Windows。

![QQ截图20210610235528](https://user-images.githubusercontent.com/12003373/121557513-615e7080-ca47-11eb-84e3-224a74994972.png)

**Comment by gdh1995** [comment]
一般是按了 Alt 键，键盘焦点跑到 右上角菜单按钮 了

**Comment by ABackerNINI** [comment]
不是,焦点在页面内

**Comment by ABackerNINI** [comment]
我先测试一下是不是休眠引起的

**Comment by gdh1995** [comment]
还有可能是：
* 键盘焦点在一个可以输入文字的地方，自动屏蔽了不带F1-F12的快捷键；按Escape可以通知页面取消文本框的焦点
* 按 i 触发了 enterInsertMode 命令，进了暂停状态，默认配置下右下角会有提示说暂停了
* 键盘焦点在一个很小的，甚至隐藏了的 空白 iframe 里，这种特殊iframe 上 Vimium C 有可能不生效（一般是浏览器不让）
* 等会补充

**Comment by ABackerNINI** [comment]
试了按esc后也没反应,网页应该没什么特殊的,B站和斗鱼,之前一直正常的

**Comment by gdh1995** [comment]
现在就有这么的页面？按 F12 ，点“控制台”，截屏看看

**Comment by ABackerNINI** [comment]
![Uploading QQ截图20210611001326.png…]()

**Comment by gdh1995** [comment]
其它页面上 Vimium C 还能用吗？你有没有手动去 edge://extensions/ 禁用过 Vimium C ？

**Comment by ABackerNINI** [comment]
之前遇到过一次没太在意,刚才是发现有3个tab不能用,另外两个可以用,刷新后可以用,同一网址新的tab可以用
没有禁用

**Comment by gdh1995** [comment]
这个可能是 Chrome 今年要推的一个“省电”扩展程序接口版本造成的，但按说现在还没上，可能是Edge太激进了，就把 Vimium C 后台杀了。然后前端脚本找不到后台，就自杀了（`has been destroyed`那几行）。

这个功能其实挺恶心的，本来 Vimium C 常驻就是为了省 CPU，现在过段时间就要 重新加载一遍，一大堆东西要重新算，浪费 CPU，Vomnibar 的延迟又要变高很多。而且有些临时状态本来只存内存里，很安全，现在要落盘了不然对应功能没法做……

**Comment by gdh1995** [comment]
你用过那种省电，或者管理其它扩展程序的扩展吗？比如一键禁止/启用其它扩展的

**Comment by gdh1995** [comment]
看下截图里的那个红色背景的“53”，能不能点一下再截图传上来。点一下会展开具体报错的堆栈，因为它看起来像是别的扩展程序也被 Edge 杀了，所以我想看看具体是哪个。

**Comment by ABackerNINI** [comment]
好像不是休眠导致的,我调成5分钟测了两次休眠之后没有问题

应该是没装那种扩展,这些应该不影响吧
Dark Reader
OneTab
Stylebot
Tampermonkey

**Comment by gdh1995** [comment]
这些扩展看起来没影响。

但这种“智能休眠”还是有嫌疑，因为5分钟只是个“最小时间”，它可能觉得扩展程序相对重要，不该在5分钟就停，多等会才停。

另外，你系统内存充足不？会不会是内存不够了……

**Comment by ABackerNINI** [comment]
![QQ截图20210611002623](https://user-images.githubusercontent.com/12003373/121562166-c61bca00-ca4b-11eb-9d19-824bef0df2ae.png)
![QQ截图20210611002557](https://user-images.githubusercontent.com/12003373/121562185-cae07e00-ca4b-11eb-9a6c-330aa3db61ec.png)
![QQ截图20210611002654](https://user-images.githubusercontent.com/12003373/121562202-cddb6e80-ca4b-11eb-904e-c9079332f39a.png)

**Comment by ABackerNINI** [comment]
内存够,还有7g

**Comment by ABackerNINI** [comment]
另外有个可能是edge本身的问题,之前遇到过两次,就是突然不能访问任何网站,都打不开,只能重启edge才行

**Comment by gdh1995** [comment]
呃图里没显示堆栈，大概是被Edge丢掉了，因为报错是很早报的，那时候还没开F12，Edge就没记录。

不太好查了。下次你碰到新的不工作的标签后，按 Shift+Esc 打开“浏览器任务管理器”，看看有没有“扩展：Vimium C……”这一行吧。

目前能做的就是，遇到类似情况后去 `edge://extensions/` 点“重新加载”，这样不用每个页面都刷新一次

**Comment by gdh1995** [comment]
> 另外有个可能是edge本身的问题,之前遇到过两次,就是突然不能访问任何网站,都打不开,只能重启edge才行

听起来像是和机子上代理程序的兼容性问题

**Comment by ABackerNINI** [comment]
没有开代理

下次遇到我再反馈

**Comment by ABackerNINI** [comment]
![QQ截图20210611003747](https://user-images.githubusercontent.com/12003373/121563730-4858be00-ca4d-11eb-81ce-42e40fe6ee9f.png)
![QQ截图20210611003723](https://user-images.githubusercontent.com/12003373/121563751-4d1d7200-ca4d-11eb-9edb-2200475c48a6.png)
看看这个有帮助吗

**Comment by gdh1995** [comment]
啊没有。这一行是我故意打出来的，嵌入网页的代码发现 Vimium C 后台进程没了，做个记号表示不是因为别的原因而停止响应快捷键的。

现在主要是不知道：为什么后台没了；或者是不是后台还在但是连不上

**Comment by gdh1995** [comment]
哦对了，你那俩不工作的标签还在吗？做个测试？

**Comment by ABackerNINI** [comment]
还在

**Comment by gdh1995** [comment]
打开 `edge://extensions/`，点左下角的“开发人员模式”，然后点开 Vimium C 详情，点击蓝色的“背景页”，在新窗口里点“控制台”，看看之前有没有输出什么。

然后输入 `Date.now()` 回车、`performance.now()` 回车，看看两条命令输出什么

![image](https://user-images.githubusercontent.com/5547703/121565136-c5d0fe00-ca4e-11eb-9e32-8e21f789f2a5.png)

![Uploading image.png…]()

**Comment by ABackerNINI** [comment]
![QQ截图20210611005257](https://user-images.githubusercontent.com/12003373/121565905-85be4b00-ca4f-11eb-947c-187a5aa2f97d.png)

**Comment by gdh1995** [comment]
应该是 Edge 在捣鬼：
1. Vimium C 后台进程 在昨晚 23:20:48 启动
2. 第一幅图（很多行`has been destroyed`的那个）的网页上，Vimium C 前端脚本在 23:21:00 发现连不上后台，自动退出
3. 第二幅图的网页上，Vimium C 前端脚本在 23:44:45 发现连不上后台，自动退出

按说后台进程启动只需要一两秒，再卡几倍，按10秒算，还算能解释第一幅图，但第二幅图里都启动 24 分钟了，还连不上，极大概率是 Vimium C 后台被 Edge 冻结了。

还有个可能性，是你机子的时间不准……假如这两个网页上 Vimium C 前端很早就自动退出了，然后你系统时间自动校正，往过去拨了几个小时，之后 Vimium C 再启动的时候就显得是启动得比退出要早。
这个可能性很小，你可以去出错的这两个页面上，按 F12，输入 `performance.now()` 和 `Date.now()` 看看数字，我来减一下确认看看

**Comment by ABackerNINI** [comment]
![QQ截图20210611010809](https://user-images.githubusercontent.com/12003373/121568080-dd5db600-ca51-11eb-8f0a-66c27134eadb.png)
![QQ截图20210611010848](https://user-images.githubusercontent.com/12003373/121568087-e058a680-ca51-11eb-9f56-3543fb9953a3.png)

系统时间的话,我想起来,应该是昨晚23点多唤醒的电脑,之前在睡眠

后台是每个tab一个后台还是共用一个

**Comment by ABackerNINI** [comment]
呃,不会是插件更新导致后台被关了吧?

电脑睡眠时edge没关,没反应的tab打开的.

**Comment by gdh1995** [comment]
第一个是 18:54:14 启动的，第二个是 15:18:56 的。后台是所有标签页共用的。

那看起来是这么的：
* 睡眠，一段时间后，后台进程被停了
* 唤醒后，切换到某页面时，会检查后台在不在，发现没了（实质是被重启了），前端脚本就自杀

重启的后台是没法在前端识别的，要修的话，可以改成后台重启时强制重新初始化前端脚本，但具体细节我还要再想想。

**Comment by gdh1995** [comment]
啊有道理，确实是插件更新了

**Comment by ABackerNINI** [comment]
那我再测试一下看看

前端可以改成不自杀吗? 如果发现后台没了, 每隔几秒重新检查一下

**Comment by gdh1995** [comment]
之前是v1.90.0，v1.90.2我前几天上传到Edge Store，然后昨晚上 19:05 附近刚通过的。

但针对扩展更新，我是做了自动重新加载前端脚本的。正常流程是，扩展更新了，那些网页的旧脚本连不上旧后台于是自杀，新扩展后台告诉浏览器重新加载“网页上的扩展脚本”，然后就能恢复对快捷键的处理了。

不确定为啥没自动加载好，可能也与睡眠有关……

=====

如果真是部分原因是扩展更新，那你没法测试，除非我发新版、等好几天审核通过，才能再复现那个场景。

如果接下来这几天你又遇到了同样的扩展不工作的问题，而 Vimium C 还是 v1.90.2，那就不是更新的问题。

现在前端已经每过几秒重新检查了，问题在于，“更新”会造成新旧两个版本不互通，旧前端无论如何也连不上新后台，只能自杀。

如果是 Edge 因为系统睡眠而停了后台，那重启后可能同一版本的前端还能连，但是无限循环地每隔几秒就检查也不好，显得浪费cpu，而且在更新之类的情况下循环检查没意义。

**Comment by ABackerNINI** [comment]
我也这样有点"洁癖",比较注重性能,hhhhha

先看看还会不会遇到同样的问题吧,我这边留意一下,有问题再反馈.

感谢耐心地回复^_^

**Comment by ABackerNINI** [comment]
呃,我好像测试出来了,禁用VimC扩展再开启,之前打开的tab就没反应了

之前应该是更新导致的类似的扩展重启过程

**Comment by ABackerNINI** [comment]
![QQ截图20210611015703](https://user-images.githubusercontent.com/12003373/121573966-637cfb00-ca58-11eb-9fde-d5b07d2f31bd.png)

**Comment by ABackerNINI** [comment]
试了下Vimium C 1.90.2，Firefox 89，Linux。重启扩展后已打开的tab能正确重新加载扩展,没问题.应该是edge或者chrome上版本的问题

**Comment by gdh1995** [comment]
Firefox 机制特殊，它自己做了“重新加载前端”的活。但它也有问题，比如手动禁用Vimium C时，正显示着的linkhints/vomnibar没法自动隐藏。

我也基本上确定了是版本更新造成后台重启的问题，其它表现都一样，只是重启后没自动重载前端的原因我还要再想想。

**Comment by ABackerNINI** [comment]
OK, 找到问题就好办了

**Comment by ABackerNINI** [comment]
刚更新了1.92.4,测试了一下应该没问题

更新之前的两个网页更新后:
![QQ截图20210831112203](https://user-images.githubusercontent.com/12003373/131436974-6c6560d6-985d-4119-b33e-75f08cb5e2eb.png)
![QQ截图20210831112553](https://user-images.githubusercontent.com/12003373/131437020-e9f0a841-e467-492a-b3b8-e0d84a510ff8.png)

1630379752364

更新时间:
![QQ截图20210831112217](https://user-images.githubusercontent.com/12003373/131437056-dc1d539a-3ee7-40d2-a4a9-05fd4f2edd88.png)

你看看如果没问题的话我就测试下手动重启插件后是否正常.

**Comment by ABackerNINI** [comment]
好像有一点小问题,不过不太确定是否是插件更新导致的

旧页面: 投币那里没有显示快捷键
![QQ截图20210831113551](https://user-images.githubusercontent.com/12003373/131437748-6c208883-9520-41f2-beb3-5561eb859c75.png)
![QQ截图20210831114333](https://user-images.githubusercontent.com/12003373/131438690-b93a8fd7-dd93-4b52-b81c-9c88422782ce.png)

复制地址重新打开的页面:
![QQ截图20210831113609](https://user-images.githubusercontent.com/12003373/131437763-6ee9dafa-fce1-41fd-bd61-208406eb0a00.png)
![QQ截图20210831114349](https://user-images.githubusercontent.com/12003373/131438706-5c0a44f9-2a9e-4804-9cf2-02dba50ff372.png)

**Comment by gdh1995** [comment]
快捷键能用就好。至于有的元素缺提示，这个是因为新版本扩展是“在页面加载完成后”才加载的，为了不影响页面脚本正确运行主动关掉了一部分功能，也确实是刷新就好了。

**Comment by ABackerNINI** [comment]
OK, 不过刚测试了下发现手动重启插件还是不能正常使用,需要刷新页面

**Comment by gdh1995** [comment]
你的“手动重启”说的是禁用再启用，还是点“重新加载”？“不能正常使用”是说大部分快捷键都不能用，还是只是说部分元素没提示?

====

谢谢测试了。我台式机的测试出问题了，我在笔记本上禁用了同步过来的vimium c商店版扩展，只保留开发版，结果台式机上扩展也被禁用了，就没法测自动升级后的效果。

看起来正常了。之前那次可能是有个地方启动慢了、没获取到“程序升级了”的信息造成的。

**Comment by ABackerNINI** [comment]
禁用后再重启

都不能使用

**Comment by gdh1995** [comment]
禁用+“启用”和“重新加载”效果不一样，启用的话旧网页上不能用的现象是正常的；重新加载会触发“升级到相同版本”的流程，Vimium C 就会主动重新在各个网页上加载，就能用了

**Comment by ABackerNINI** [comment]
好, 这个也没什么影响,^_^
