### ISSUE TITLE
[Firefox] Popup dialog is unusable when in a very small size

### ISSUE THREAD

**Issue by HueLiu** [gdh1995/vimium-c#371]
**Describe the bug**
When I pin Vimium C to overflow menu, I couldn't click the button to save changes.

**To Reproduce**
1. Right-click on the Vimium C icon and select `Pin to Overflow Menu`
2. Expand Overflow Menu, Right-click on the Vimium C icon
3. The button `save chances` is missing and could not be clicked.

It will help a lot if here includes a screenshot when applicable.
![image](https://user-images.githubusercontent.com/19755727/121996791-d3361180-cddb-11eb-8a40-56ad68912e9b.png)

![image](https://user-images.githubusercontent.com/19755727/121996861-f496fd80-cddb-11eb-8f40-8d05ed535431.png)

**Browser, OS and Vimium C version**
![image](https://user-images.githubusercontent.com/19755727/121996944-16908000-cddc-11eb-84f4-929f30523359.png)

**Comment by gdh1995** [comment]
Um, you may use Ctrl+Enter to save

**Comment by gdh1995** [comment]
Hello, Vimium C v1.92.0 has been released on Firefox Add-Ons, and you may take a try.

**Comment by HueLiu** [comment]
Thank you very much for the development, I have tested the latest version and there is no problem.
