### ISSUE TITLE
vimium-c no response after trigger windows terminal quake mode

### ISSUE THREAD

**Issue by roachsinai** [gdh1995/vimium-c#373]
**Describe the bug**

在结合Windows Terminal Preview和Edge时，会有 Vimium-c 无反应的情况。

**To Reproduce**
1. Windows应用商店下载 windows terminal preview
2. 在 Edge 中打开一个网页，然后按下windows键和反引号键（这个时windows terminal 下拉模式的默认触发键）
3. 然后再次按下windows键和反引号键收回windows terminal

此时在网页上按下`f`后， Vimium-c 无反应。但是Ctrl+C或者Ctrl+W可以打开或者关闭标签页。

**Browser, OS and Vimium C version**

+ Edge: Microsoft Edge | 91.0.864.53&nbsp;(官方内部版本)&nbsp;(64 位)
+ Vimium C version: 1.90.2

Windows Terminal 相关issue：https://github.com/microsoft/terminal/issues/10450

**Comment by gdh1995** [comment]
如果有反应的时候用鼠标点一下网页内容的空白处，然后有访问



---Original---
From: ***@***.***&gt;
Date: Fri, Jun 18, 2021 13:37 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] vimium-c no response after trigger windows terminal quake mode (#373)




 
Describe the bug
 
在结合Windows Terminal Preview和Edge时，会有 Vimium-c 无反应的情况。
 
To Reproduce
 Steps to reproduce the behavior:
  
Windows应用商店下载 windows terminal preview 

在 Edge 中打开一个网页，然后按下windows键和反引号键（这个时windows terminal 下拉模式的默认触发键） 

然后再次按下windows键和反引号键收回windows terminal 
 
此时在网页上按下f后， Vimium-c 无反应。但是Ctrl+C或者Ctrl+W可以打开或者关闭标签页。
 
Browser, OS and Vimium C version
  
Edge: Microsoft Edge | 91.0.864.53&nbsp;(官方内部版本)&nbsp;(64 位) 

Vimium C version: 1.90.2 
 
Windows Terminal 相关issue：microsoft/terminal#10450

**Comment by gdh1995** [comment]
然后，f 这种快捷键能工作吗？



---Original---
From: ***@***.***&gt;
Date: Fri, Jun 18, 2021 13:37 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] vimium-c no response after trigger windows terminal quake mode (#373)




 
Describe the bug
 
在结合Windows Terminal Preview和Edge时，会有 Vimium-c 无反应的情况。
 
To Reproduce
 Steps to reproduce the behavior:
  
Windows应用商店下载 windows terminal preview 

在 Edge 中打开一个网页，然后按下windows键和反引号键（这个时windows terminal 下拉模式的默认触发键） 

然后再次按下windows键和反引号键收回windows terminal 
 
此时在网页上按下f后， Vimium-c 无反应。但是Ctrl+C或者Ctrl+W可以打开或者关闭标签页。
 
Browser, OS and Vimium C version
  
Edge: Microsoft Edge | 91.0.864.53&nbsp;(官方内部版本)&nbsp;(64 位) 

Vimium C version: 1.90.2 
 
Windows Terminal 相关issue：microsoft/terminal#10450

**Comment by roachsinai** [comment]
> 如果有反应的时候用鼠标点一下网页内容的空白处，然后有访问
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Fri, Jun 18, 2021 13:37 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [gdh1995/vimium-c] vimium-c no response after trigger windows terminal quake mode (#373) Describe the bug 在结合Windows Terminal Preview和Edge时，会有 Vimium-c 无反应的情况。 To Reproduce Steps to reproduce the behavior: Windows应用商店下载 windows terminal preview 在 Edge 中打开一个网页，然后按下windows键和反引号键（这个时windows terminal 下拉模式的默认触发键） 然后再次按下windows键和反引号键收回windows terminal 此时在网页上按下f后， Vimium-c 无反应。但是Ctrl+C或者Ctrl+W可以打开或者关闭标签页。 Browser, OS and Vimium C version Edge: Microsoft Edge | 91.0.864.53&nbsp;(官方内部版本)&nbsp;(64 位) Vimium C version: 1.90.2 Windows Terminal 相关issue：microsoft/terminal#10450 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

在网页空白处点击之后，`f`就可用了。

**Comment by gdh1995** [comment]
那就是浏览器的“键盘焦点”跑到窗口框架上去了。你可以按几次tab，或者点一下。

目前扩展程序没法挪焦点，没法修。

**Comment by roachsinai** [comment]
那这个浏览器方面可以解决么？

**Comment by gdh1995** [comment]
我猜他们不会管的，这个问题太小了，无非是不那么方便——按一次鼠标或者几次tab就行。

可以去edge反馈里试试。

**Comment by roachsinai** [comment]
嗯嗯，好的。感谢回复。

**Comment by gdh1995** [comment]
bugs.chromium基本上不管这种小事，有些明显逻辑错了但没有可见影响的bug都没人想动，影响扩展而不影响大网站的问题也没多高优先级。

**Comment by roachsinai** [comment]
嗯嗯，好的。反馈我应该时找Edge，毕竟windows terminal也是微软的产品，😀

**Comment by roachsinai** [comment]
刚才发现焦点在右上角。

![image](https://user-images.githubusercontent.com/9500049/122524010-3c22c100-d04a-11eb-80b2-d20412011743.png)

**Comment by gdh1995** [comment]
按左alt键也能把键盘焦点移动到右上角菜单按钮，我还没发现好办法移动回去。用鼠标或触摸板点吧



---Original---
From: ***@***.***&gt;
Date: Fri, Jun 18, 2021 15:31 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] vimium-c no response after trigger windows terminal quake mode (#373)




 
刚才发现焦点在右上角。

**Comment by roachsinai** [comment]
感觉可以用 autohotkey 来实现。
