### ISSUE TITLE
shift-delete fails to work

### ISSUE THREAD

**Issue by gqqnbig** [gdh1995/vimium-c#374]
**Describe the bug**

In vomnibar, shift-delete used to close tabs. However, it fails to work nowadays.

If I press shift-delete on current tab, vimium-c says "The current tab should be kept.". If I press shift-delete on other tabs, nothing happens. The target tab remains open.

**Browser, OS and Vimium C version**

Windows 10
Chrome 91.0.4472.106
Vimium C 1.90.2

**Comment by gdh1995** [comment]
Thanks. Confirmed and it will be fixed in a next release.

**Comment by sunnyrahul25** [comment]
It would be nice if it could be mapped to vim friendly keybinding or custom keybinding? I don't whether it is possible in the current implementation but I don't  see any command related in the show available command maps.

**Comment by gdh1995** [comment]
Such keys can be mapped "in `omni` mode" - `mapKey <c-d:o> <s-delete>` works on Vomnibar. The "mode" concept used in `mapKey` can be seen in https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout#pre-mode-mapkey .

**Comment by gqqnbig** [comment]
I confirm the issue has been fixed in release 1.92.1
