### ISSUE TITLE
hints are also mapped after mapKey configuration in other keyboard layout

### ISSUE THREAD

**Issue by Akuseru1** [gdh1995/vimium-c#376]
**Describe the bug**
I'm using firefox and have the colemak layout on my keyboard, so i set the following configuration:
```
# colemak layout
mapKey n j
mapKey N J
mapKey e k
mapKey E K
mapKey i l
mapKey I L
mapKey k n
mapKey K N
mapKey l i
mapKey L I
mapKey j e
mapKey J E
```
the keys work as expected, when i press f to open a link the hints appear, but the hints that appear do not match with the keys that i press.

for example, if i press a the letter `l` then the link with the hint `i` will open, which is not what is expected.

**To Reproduce**
1. go to any url , for example: https://www.google.com/search?q=vimium
2. press f
3. press l,k,e or any other mapping and see if the correct link opens

**Browser, OS and Vimium C version**

Firefox: 89.0
OS: GNU/Linux, Solus OS
Vimium C 1.90.2, Firefox 89,

**Comment by gdh1995** [comment]
If you mean "`mapKey` affects LinkHints", then it's not a bug but a feature - `mapKey` usually works "anywhere inside Vimium C", except that in normal mode it's applied after testing exclusion passKeys.

If you don't want this behavior, you can rewrite how LinkHints maps keys by rules like `mapKey <n:l> n`. Please see https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout for detailed usages.

In a next (future) version of Vimium C, it will support `mapKey <f:n> f`, which only affects normal mode.

**Comment by gdh1995** [comment]
Hello, Vimium C v1.92.0 has been released on Firefox Add-Ons, and you may try `mapKey <f:n> f` on it.
