### ISSUE TITLE
[Feature] 点击空白

### ISSUE THREAD

**Issue by Higurashi-kagome** [gdh1995/vimium-c#377]
很好用，非常感谢！

注意到使用 f 开启链接提示之后，只会提示所有可点击的链接，我遇到的问题是，有时没有任何链接是我所想要点击的，而仅仅是希望通过点击背景等空白处来退出焦点，所以是否能在 f 命令触发后添加一个**点击页面空白处**的按键选项？

**Comment by gdh1995** [comment]
退出文本框焦点按下 `<esc>`，强制 blur 不是文本框的元素的话，长按 `<esc>`，一般都能成功blur

**Comment by Higurashi-kagome** [comment]
对于弹窗之类的元素，按 `<esc>` （包括长按）似乎并不能够达到目的：

<details>
<summary>Details</summary>

![demo](https://user-images.githubusercontent.com/51501079/123534659-2fd8eb00-d751-11eb-87fe-62c832d290db.gif)

</details>

**Comment by gdh1995** [comment]
看起来是弹窗自己没做好焦点控制。

主要问题是“空白”没法很好地定义出来，“四周”有可能有侧边栏、菜单、漂浮广告、浮层按钮、置顶提示之类的一堆东西，而且扩展程序是没法像人一样“找出一块只有一种颜色的地方”的。直接点 `<body>` 也不一定有用，很可能事件绑定到了 `<div id="app">` 之类的子元素上。

在有的网站上，你按 f 然后随便点个别的，比如一般是左上角会有个绑定到整个页面的提示按钮，可以退出对话框。只是，看起来你这个截图的网站不好这么做。

建议是，使用 `map Fe openUrl url="javascript:document.querySelect('.cls1#id2').click()"` 这种方式直接指定 JS，就能用来取消了，或者 `map Fe LinkHints.click direct="element" match=".cls1#id2,[data-close]"` 来让 LinkHints 对它模拟点击。

**Comment by Higurashi-kagome** [comment]
好的，该方法基本能够解决我所遇到的问题。谢谢！
