### ISSUE TITLE
与 youtube 冲突，建议可以自定义 f 键

### ISSUE THREAD

**Issue by zz5678** [gdh1995/vimium-c#378]
youtube 页面上，f 键是作为 “视频全屏” 的 乒乓键存在的，和 vimium 直接冲突

**Comment by gdh1995** [comment]
https://github.com/philc/vimium#custom-key-mappings

**Comment by zz5678** [comment]
OK ！这样设置后，解决了这个问题，把 f 键功能换到了 e 上
```
unmap f
map e LinkHints.activate
```
