### ISSUE TITLE
How to unmap key -

### ISSUE THREAD

**Issue by GiancarloAparicio** [gdh1995/vimium-c#380]
**Describe the bug**
I am currently using the Video Speed ​​Manager extension, the problem is that vimium-c blocks the use of the '-' key

**To Reproduce**
1. Install Video Speed ​​Manager extension, https://chrome.google.com/webstore/detail/video-speed-manager/fkopaaikpmfhpmoobnmklgmcgmhgfkcd
2. Use the - + keys, the '-' key does not work

Look for and apparently the - + keys, they are not mapped and but it only blocks the use of the - key

**Comment by gdh1995** [comment]
You may use the `passNextKey` command to skip any next key once, use a key mapping like `mapKey - <fake1>` to let Vimium C treat it as another key, or use exclusion rules to mark that `-` should always be ignored on some websites.
