### ISSUE TITLE
Bugs on chrome://

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#381]

**Comment by OnceThenEver** [comment]
Even when the focus is on the input field, Vimium-c still works like otherwise.

**Comment by OnceThenEver** [comment]
And if I'm going to hit `f`, _LinkHints_ will take effect.

**Comment by gdh1995** [comment]
Um, on which page? I tested a fresh profile of Chrome 91, Win10 and it seems `chrome://newtab` is OKay, while history and bookmark pages have such an issue. So it seems that this only occurs on only pages using Material Design. Am I right?

**Comment by OnceThenEver** [comment]
My condition is the same as yours except that I use macOS, and I don't know what the Material Design is.

**Comment by OnceThenEver** [comment]
I Googled this term and I guess `chrome://settings/` also uses Material Design, and it also exposes this problem too.

**Comment by gdh1995** [comment]
Well, I find a very naive bug: Vimium C v1.90.2 will inject new content script if only the URL changes.

And Material Design uses Shadow DOM to render UI components, which triggers another long-term issue: Vimium C content doesn't learn focused input inside shadow DOMs on Vimium C loading.

Anyway, I'll fix it in a next version.

**Comment by gdh1995** [comment]
Hello, v1.92 has been published on Firefox and Chrome stores, and you may take a try.

**Comment by OnceThenEver** [comment]
Verified.
And a new issue: some elements at the sidebar of the bookmark page have no linkhints.
![截屏2021-08-17 19 31 13](https://user-images.githubusercontent.com/66708845/129718591-9b0c824b-fe36-4104-9de0-89d506d47035.png)

**Comment by gdh1995** [comment]
```
env cBm host=":chrome://bookmarks/"
map f runKey expect=[["cBm","<v-f>",{"clickable":"[role=treeitem]"}]] keys="<v-f>"
map <v-f> LinkHints.activate
```

**Comment by OnceThenEver** [comment]
Thank you for your kind help!
