### ISSUE TITLE
pdf 页面翻译

### ISSUE THREAD

**Issue by bommbo** [gdh1995/vimium-c#383]
求问：关于pdf页面单词选中翻译，如何做快捷键翻译？
原谅我来厚颜无耻地求教了。在网页端使用贵插件和edgetranslate配合使用，使用体验非常赞，两边都是很多快捷键。但是pdf中就比较尴尬，选择好内容后，那边无法使用快捷键，求问个解决办法。感谢感谢
https://github.com/EdgeTranslate/EdgeTranslate/issues/218

**Comment by gdh1995** [comment]
pdf 你是用了 PDF Viewer for Vimium C 吗？

这个插件我没用过，还没来得及看。我之前见过用沙拉查词的，它内置了一份PDF阅读器的页面，修改沙拉查词后可以做到在沙拉查词的页面里跑 Vimium C 快捷键，类似于 https://github.com/gdh1995/vimium-c/issues/318

修改别的插件来支持 Vimium C 的办法参见 https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions

**Comment by bommbo** [comment]
> pdf 你是用了 PDF Viewer for Vimium C 吗？
> 
> 这个插件我没用过，还没来得及看。我之前见过用沙拉查词的，它内置了一份PDF阅读器的页面，修改沙拉查词后可以做到在沙拉查词的页面里跑 Vimium C 快捷键，类似于 #318
> 
> 修改别的插件来支持 Vimium C 的办法参见 https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions

是的，我用的pdf viewer for vimium c,这个插件帮助我很好的选择单词，但是没办法快捷键进行翻译，而且edgetranslate应该也是对内置pdf进行了修改，它们支持了dark模式。修改他的插件，在 PDF Viewer for Vimium C 中可行吗？能支持快捷键和黑暗模式吗？我先看看沙拉查词的那个，感谢您看看，我觉得至少  PDF Viewer for Vimium C 可以像他们一样加上黑暗模式。

**Comment by gdh1995** [comment]
一个扩展不能修改其它扩展，之前我说的“修改”都是需要手动操作的。另外改 edgetranslate 的 pdf页面的话，就和 pdf viewer for vimium c 无关了。

PDF Viewer for Vimium C 和原版的PDF Viewer用的代码完全一样（只是版本落后点），我只加了对Vimium C 的支持。我不打算给它本身加功能。

其实理想状态是，把PDF阅读器做成普通网页，这样各个扩展就都能在同一个网页上跑了，但是普通网页权限不够很多东西不方便，也不能彻底离线用。

你可以先找找有没有这类工具网页，凑合用……或者你把这个PDF 阅读器的html、js等文件提取出来直接当作本地文件来打开，

**Comment by bommbo** [comment]
> 一个扩展不能修改其它扩展，之前我说的“修改”都是需要手动操作的。另外改 edgetranslate 的 pdf页面的话，就和 pdf viewer for vimium c 无关了。
> 
> PDF Viewer for Vimium C 和原版的PDF Viewer用的代码完全一样（只是版本落后点），我只加了对Vimium C 的支持。我不打算给它本身加功能。
> 
> 其实理想状态是，把PDF阅读器做成普通网页，这样各个扩展就都能在同一个网页上跑了，但是普通网页权限不够很多东西不方便，也不能彻底离线用。
> 
> 你可以先找找有没有这类工具网页，凑合用……或者你把这个PDF 阅读器的html、js等文件提取出来直接当作本地文件来打开，

测试良好，非常感谢！！！！成功实现最好用的pdf阅读器，有vim 模式，黑暗模式，还能选定翻译。

**Comment by gdh1995** [comment]
https://github.com/EdgeTranslate/EdgeTranslate/pull/225 已合并，这个问题先关闭了。
