### ISSUE TITLE
r does not work for some sites after switching tabs

### ISSUE THREAD

**Issue by falolaf** [gdh1995/vimium-c#384]
**Describe the bug**
When switching to a tab for some sites, `r` does not reload the page in that particular tab. There might be other commands that also does not work but I have not encountered any.

**To Reproduce**
1. Open https://opensource.com/ in two different tabs
2. Swtich from one of the tabs to the other
3. Use `r` to reload the page
4. Nothing happens

If e.g. `j, k` or `gF` is used after tab switch then `r` will work.

**Browser, OS and Vimium C version**

Vimium C: 1.90.2
OS: Windows 10 OS Version 1909 (Build 18363.1621)
Firefox: 89.0.2
Chrome: 91.0.4472.124

**Comment by gdh1995** [comment]
By default `r` is mapped to `reload`, and then it only reload `"a current frame"`. So I think in step 3 your keyboard focus were in an invisible / too small iframe.

To always reload a tab (aka. its top frame), you may use `<a-r>` which means `reloadTab`, and you can also map other keys as you like.

**Comment by falolaf** [comment]
But why is the focus changed by switching tab?
It indeed looks like the last "Subscribe to our weekly newsletter" on the page is focused after I switch from and to the tab. I.e. this one:
![bild](https://user-images.githubusercontent.com/9840223/124465766-14e02980-dd96-11eb-8734-3673bd8a666b.png)
That one is reloaded with `r`.

**Comment by gdh1995** [comment]
Well, I'm not sure. I can not 100% reproduce that the focus was in the iframe by default when today I tested it.

**Comment by falolaf** [comment]
Here it happens all the time. Both in FF and Chrome. And also Edge Chromium.
It also happens on pages that unfortunately are behind company firewall so I can't share them. In FF neither `j` nor `k` works for at least one of those pages. I have to use e.g. `gF` first. 
I am quite sure that this behavior is rather new as I can't remember that it has bugged me this much in the past.

I have remaped `r` to `reloadTab` in FF as that is what I mostly want anyhow.

**Comment by falolaf** [comment]
I have tested different version of Vimium C back to 1.86.2 and it seems the same also happens in those. I was most likely wrong in my assumption that it started recently. Perhaps I have changed my WoW which makes this more noticible for me.

**Comment by gdh1995** [comment]
V1.90.2 has some bugs in `runKey`, `$then` and `$else`, but I guess you haven't used these new features.

Here're compiled from the latest code in my developing project: [vimium_c-1.90.2-firefox-c81a225-mod.zip](https://github.com/gdh1995/vimium-c/files/6767714/vimium_c-1.90.2-firefox-c81a225-mod.zip) and [vimium_c-1.90.2-chrome-c81a225-mod.zip](https://github.com/gdh1995/vimium-c/files/6767716/vimium_c-1.90.2-chrome-c81a225-mod.zip) . And you may test them by following steps in https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package .

**Comment by falolaf** [comment]
Thank you for your efforts @gdh1995!
I have tested the one for Firefox but the same behavior is still there.
And, I have not used any of the features that you mention.

**Comment by gdh1995** [comment]
Um, days ago (Aug. 26) I published v1.92.4, but I didn't make any changes about iframes and keyboard focus in it (compared with v1.92.2). It's somehow strange.

Let's continue watching whether it will happen again or not.

**Comment by falolaf** [comment]
Yes, strange indeed. I still have not been able to reproduce it with my current setup. Though, in a new profile I tested out 1.90 and could reproduce it to some extent.

**Comment by gdh1995** [comment]
Hello, here're some old versions of Vimium C, and if you have enough rest, could you test them on your Firefox ? (I've fixed bugs about settings importing in such versions manualy)

[vimium-c-1.92.1-firefox.zip](https://github.com/gdh1995/vimium-c/files/7091391/vimium-c-1.92.1-firefox.zip)
[vimium-c-1.92.2-firefox.zip](https://github.com/gdh1995/vimium-c/files/7091387/vimium-c-1.92.2-firefox.zip)
[vimium-c-1.92.3-firefox.zip](https://github.com/gdh1995/vimium-c/files/7091389/vimium-c-1.92.3-firefox.zip)

Zip file usage: https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package

**Comment by falolaf** [comment]
Sorry for late reply!

I have not had any time to test those I have to admit. Though, I have been able to trigger the issue on at least one page. Unfortunately it is a company page behind a firewall so I can't share it.
And, I actually have to click with the mouse on the page for any Vimium shortcuts to work.
And, the same behaviour in Chrome.

**Comment by gdh1995** [comment]
What about a long-pressed `Escape` key when this occurs? It should blur any blur-able element.

**Comment by falolaf** [comment]
> 
> 
> What about a long-pressed `Escape` key when this occurs? It should blur any blur-able element.

Nothing happens, as far as I can see.
In Chrome it is possible to Tab twice and then the "first element" on the page is activated and then keyboard shortcuts work. The same does not happen in FF though.

**Comment by gdh1995** [comment]
Sorry I'm a little confused.

> have to click with the mouse on the page for any Vimium shortcuts to work

Did commands like `mainFrame` work yet? If not, then it seems you're in a special iframe where Vimium C can not run its scripts, which is usually caused by browser limitation.

If `mainFrame` worked, did `j` and `k` work before any mouse click? Did `f` work?

====

I think the most possible cause is you're in a special iframe. You may try `map <f7> mainFrame $then="f" $else="f"` to use `F7` to  go to a main frame and activate `LinkHints`.

**Comment by falolaf** [comment]
Hello @gdh1995!

I am also confused... :-)

No Vimium C shortcuts seem to work. Maping `F7` does not work either. Text selection in both FF and Edge Chromium is "activated" instead. 
Here are two sites that show this behaviour:
https://sn.se/nyheter
https://kkuriren.se/nyheter

I can also add that mail.google.com shows the same behaviour, with gmails own shortcuts, in case "Chat" is disabled. Vimium C is disabled on this site.

**Comment by gdh1995** [comment]
Is there an area which you clicked / focused using `Tab` keys and then could not use Vimium C any more?

If you saw an exactly same behavior on GMail, then it may be a problem due to limitation of your browser (see https://github.com/philc/vimium/issues/3353#issuecomment-505564921 ).

I didn't find same statuses on the two websites you provided with GMail. Could you provide a detailed URL and the snapshot of screen area where you once clicked?

**Comment by falolaf** [comment]
On https://sn.se/nyheter, using `Tab` and enter what can be seen in the below picture, then Vimium C does not work any longer:
![bild](https://user-images.githubusercontent.com/9840223/132445000-089da068-d2dc-44cf-846d-88eaf9636b29.png)
And it seems that part is in focus after switching tabs.

This is reproducible in Chrome, Edge Chromium and FF for me.

**Comment by gdh1995** [comment]
OKay. It seems the `iframe` uses an ugly way of `document.write` to show some content, just like https://github.com/philc/vimium/issues/2404 .

There's no "effective and cheap" way to detect this, but Vimium C has provided some ways to re-enable itself manually.

And you may read https://github.com/gdh1995/vimium-c/wiki/Enable-or-Disable-all-frames-by-a-shortcut to see how to re-enable Vimium.

Here's a conclusion of the wiki page:

### Method 1

1. Click Vimium C's icon at the top-right corner of browser window, and you'll see its popup dialog
2. click "Disable once" at the bottom-left corner
3. click the icon to open the popup dialog again
4. click "Enable" or "Reset"
5. use any way (like mouse click) to switch keyboard focus to the page itself
6. then Vimium C's key mappings will work on the page section

### Method 2

A more convenient way is:
* open `chrome://extensions/shortcuts` and assign a shortcut to Vimium C's "`Custom shortcut 1`"
* open Vimium C Options, and add a key mapping of `shortcut userCustomized1 command="openUrl" url="vimium://status/enable"`

Then, when you find Vimium C doesn't work, press the shortcut to re-enable it.

**Comment by falolaf** [comment]
Again, thank you for your efforts @gdh1995!

I have done some quick tests and both methods seems to work. I will give it some more time and see if it works in the long run.
