### ISSUE TITLE
Remove tabs to the left ? 

### ISSUE THREAD

**Issue by elig0n** [gdh1995/vimium-c#387]
**Describe the bug**
There is `removeRightTab` command but is there a way to remove tabs to the left of current tab?

**Browser, OS and Vimium C version**
Vimium-C 1.90.02

**Comment by gdh1995** [comment]
press "-" and number keys before mapped keys, to remove a tab in the left.
or you can "map xxx removeRightTab $count=-1" to add a scale factor of "-1" pressed keys, and then "3xxx" will work as "removeRightTab with count=-3"



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 9, 2021 01:05 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] Remove tabs to the left ?  (#387)




 
Describe the bug
 There is removeRightTab command but is there a way to remove tabs to the left of current tab?
 
Browser, OS and Vimium C version
 Vimium-C 1.90.02

**Comment by elig0n** [comment]
Thanks

**Comment by elig0n** [comment]
Do you think you can add a shortcut action for specifying numerical-prefixes ? I have `-` bound to zoom out so having an alternative shortcut like `Alt-u -3` to specify negative numbers could be useful (similar to emacs C-u).

**Comment by gdh1995** [comment]
You may use `mapKey` to make another work as `-`: for example, `mapKey <a--> -` means `Alt+minus` work as `-`.
