### ISSUE TITLE
how to disable map for simple insert mode

### ISSUE THREAD

**Issue by GiancarloAparicio** [gdh1995/vimium-c#388]
**Describe the bug**
I have mapped the combinations

```vim
map <c-b> Vomnibar.activateBookmarksInNewTab
map <c-b:i> Vomnibar.activateBookmarksInNewTab
```

I just want to disable <c-b: i>, in exclude keys use:
```
<c-b:i>
```
But when saving it gets messy and does not deactivate the combinations
![image](https://user-images.githubusercontent.com/61440825/124975497-b31cfb00-dff3-11eb-8c41-23b3659b12d9.png)

**Comment by gdh1995** [comment]
Exclusion rules doesn't care about current modes.
You should use the "runKey" command to do different work on different sites / active elements. In Vimium C's wiki there's a document about its usages.
But v1.90.2 has a bug reverting checks on the "expect" argument of "runKey"...



---Original---
From: "Erick Giancarlo Ramos ***@***.***&gt;
Date: Fri, Jul 9, 2021 02:56 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] how to disable map for simple insert mode (#388)




 
Describe the bug
 I have mapped the combinations
 map&nbsp;<c-b&gt;&nbsp;Vomnibar.activateBookmarksInNewTab map&nbsp;<c-b:i&gt;&nbsp;Vomnibar.activateBookmarksInNewTab
 
I just want to disable <c-b: i&gt;, in exclude keys use:
 <c-b:i&gt;  
But when saving it gets messy and does not deactivate the combinations

**Comment by gdh1995** [comment]
the bug and working around of runKey can be found jn https://github.com/gdh1995/vimium-c/issues/366#issuecomment-856125015

**Comment by GiancarloAparicio** [comment]
@gdh1995 Configure this, but the passNextKey command forces you to have to run the shortcut <c-b> 2 times to get it to work in notion.

```vim
env notion host="^(?!https://www\\.notion\\.so/)"

map <c-b:i> runKey expect={"notion":"<v-notion>"} keys="<v-not-notion>"

map <v-notion> passNextKey
map <v-not-notion> Vomnibar.activateBookmarksInNewTab
```
There is a way to avoid this behavior?

**Comment by gdh1995** [comment]
Um, no. Up to now there's no way to pass special keys according to DOM status (except URL patterns in exclusions).

Then I suggest that you may add `<c-b>` on `*.notion.so` as an exclusion rule, and when you want to use Vomnibar, press `<esc>` to blur inputs firstly.

**Comment by gdh1995** [comment]
BTW, in the snapshot of the first comment, `^https?://\.*notion\\.so` seems not what you want. Vimium C will guess "what a pattern should be" if it doesn't start with `^` or `:`, and appearently it failed and made a wrong regexp.

You can write a valid regexp starting with `^` to tell Vimium C not guess anything.

**Comment by GiancarloAparicio** [comment]
True, I had not realized that the regex was wrong, it should be something like that
 ^ https?: \ / \ / www \ .notion \ .so \ /?. *
after trying a short time, the shortcuts in notion, it is not so bad to have to press 2 times.
Thanks for the help

**Comment by gdh1995** [comment]
Hello, v1.92 has been published on Firefox and Chrome stores, and you may take a try.

The bug about `expect` has been fixed, so you may need to update your `env notion ...`.
