### ISSUE TITLE
The hint doesn't apply to some of the clickable elements.

### ISSUE THREAD

**Issue by ghostflyby** [gdh1995/vimium-c#389]
### Chinese edition
快捷键对某些可点击元素无效。
如 https://sspai.com/ 的顶部导航栏。

### English edition
The hint doesn't apply to some of the clickable elements.
For example, the top navigation bar of https://sspai.com/ .

**Comment by ghostflyby** [comment]
It seems that it happens randomly, now the hint works just fine.

**Perhaps this issuse should be closed.**

**Comment by gdh1995** [comment]
Vimium C 收集“可点击元素”的逻辑里，有些情况是有延迟的：页面加载时收集但推迟汇总，等“加载完成”或者“1秒后”后再分批汇总；加载后新增的可点击元素上报延迟是666毫秒；分批大小是512个，两批延迟是36毫秒。

以上是 Chrome / MS Edge 版的逻辑，如果用 Firefox 的话基本上没有这个延迟。
