### ISSUE TITLE
passNextKey have bug at Video Web

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#390]
from macOS 11.4 in Chrome:
When the browser is not fullscreen, press `i` to trigger `passNextKey` and press `f` to make the video fullscreen, then Vimium-C will have broken.

**Comment by gdh1995** [comment]
What Vimium C will do if you exit fullscreen and then press `f`?

What pages (using `f` to enter fullscreen) are you visiting? Youtube?

**Comment by OnceThenEver** [comment]
> What Vimium C will do if you exit fullscreen and then press f?
Return to the fullscreen video

> What pages (using f to enter fullscreen) are you visiting? Youtube?
Not only YouTube but also BiliBili

By the way, `i`: `passNextKey`—>`f`: video fullscreen —> switch to either the left or right tab —> return back to the video tab
then will the Vimium-C resurrect on the video tab.

**Comment by OnceThenEver** [comment]
@gdh1995 Hello?

**Comment by gdh1995** [comment]
Um sorry I forgot this.

Now I think your `i` worked as `enterInsertMode`, but not `passNextKey`. And when a page gets inactive, its global insert mode will auto exit, which explains it resurrects after tab switching.

**Comment by OnceThenEver** [comment]
I'm sure that my `i` maps `passNextKey`, checking `showHelp`.
After trying mapping `I` to `enterInsertMode` and repeat the process above, however, Vimium-C didn't resurrect: Insert Mode didn't automatically exit.

**Comment by gdh1995** [comment]
Oh yes `enterInsertMode` won't auto exit.

**Comment by gdh1995** [comment]
When `i`, `f` and exit full screen using your mouse, is HUD showing, and what will the HUD (at the bottom right) show if you press some (non-mapped) letter keys?

**Comment by OnceThenEver** [comment]
HUD shows "临时禁止所有快捷键", in spite of pressing any non-mapped key.

**Comment by gdh1995** [comment]
&nbsp;Will it disappear if you press keys many times?&nbsp; If so then how many times?



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 23, 2021 21:58 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] passNextKey have bug at Video Web (#390)




 
HUD shows "临时禁止所有快捷键", in spite of pressing any non-mapped key.

**Comment by OnceThenEver** [comment]
It won't.

**Comment by gdh1995** [comment]
When you find `Vimium-C will have broken`, will HUD show at the bottom right of current frame?

I tested Chrome 91 x64, Win10, and Vimium C v1.90.2 with a fresh profile (only with `map i passNextKey`), but didn't reproduce it.

**Comment by OnceThenEver** [comment]
I use MacOS, you may have another try.

**Comment by gdh1995** [comment]
Please test this developing version: 
[vimium_c-1.90.2-chrome-dc5e026-mod.zip](https://github.com/gdh1995/vimium-c/files/6871974/vimium_c-1.90.2-chrome-dc5e026-mod.zip)

I didn't find any obvious bug related with this issue, so I just added some logic about fault tolerance.

This is a very very unstable version, so please uninstall it (and re-install the web-store version again) when you finish tests.

**Comment by OnceThenEver** [comment]
This developing version doesn't work.
Have you reproduced the issue?

**Comment by gdh1995** [comment]
No, currently I have no macOS... My last macOS had been sold out in this March.

Well I'll take a try to borrow one from classmates.

**Comment by OnceThenEver** [comment]
Fine, we have time a lot.
But no another forgetting, please.

**Comment by gdh1995** [comment]
Note for myself:
* on macOS, both Chrome and Firefox eats `keyup` events on composed keys
  * e.g. in <kbd>Ctrl+Meta+Shift+F</kbd>, `F` will be eaten and then no `keyup` events for it
* Chrome will also eat a plain `F` if it makes Chrome switching fullscreen mode; but Firefox not
  * C92, FF 90; <kbd>F</kbd> on `<video>` of www.bilibili.com

**Comment by gdh1995** [comment]
Hello, please try this version: [vimium_c-1.90.2-chrome-8b007d2.zip](https://github.com/gdh1995/vimium-c/files/6950554/vimium_c-1.90.2-chrome-8b007d2.zip)

Usage: https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package .

**Comment by gdh1995** [comment]
Hello, v1.92 has been published on Firefox and Chrome stores, and you may take a try.

**Comment by OnceThenEver** [comment]
Verified.
And a new issue: `i`->`f`->`f`, then the following `Esc` quits fullscreen, but I think canceling _LinkHints.activate_ is more appropriate.

**Comment by gdh1995** [comment]
In fullscreen mode, `Esc` will always quit fullscreen on Chrome, which can not be changed by Vimium C as far as I know.

**Comment by OnceThenEver** [comment]
All right, it's a trivial issue after all. Thank You!
