### ISSUE TITLE
[Question] How to sort history results by date?

### ISSUE THREAD

**Issue by GiancarloAparicio** [gdh1995/vimium-c#391]
**Describe the bug**
How you can sort the history results by date, similar to the browser search engine.
![image](https://user-images.githubusercontent.com/61440825/125175480-1775c100-e192-11eb-9a85-da90e5c777a8.png)
![image](https://user-images.githubusercontent.com/61440825/125175507-455b0580-e192-11eb-9208-9bdb0f4f3d97.png)

**Comment by gdh1995** [comment]
Up to now there's only one limited way: use the prefix of a full URL as your query. This means:
* if you search `https://github.com/`, then Vimium C will sort all matched history items (whose URLs start with your query) by visiting time
* if you search `github.com`, then Vimium C will sort matched items by time score and word-similarity score, which may give a higher score to a shorter URL than a longer.
