### ISSUE TITLE
Moving tabs around is slow/laggy/freezes with the default bindings in firefox

### ISSUE THREAD

**Issue by M-e-r-c-u-r-y** [gdh1995/vimium-c#392]
**Describe the bug**
When moving tabs left and right with `<` and `>` key bindings, there is a lag/freeze between each hop, have to let go shift key and try after a second sometimes.

I remapped it as follows and the lag is not there.

```
map <c->> moveTabRight
map <c-<> moveTabLeft
unmap >>
unmap <<
```

**Note**: The bug is there in Vimium FF as well, maybe a common fix could be found and merged into both repos?

**To Reproduce**
1. Have multiple tabs in a window(5 to 10) to test.
2. Try without proposed bindings and with bindings to feel the difference.

**Browser, OS and Vimium C version**

Firefox version: 89.0.2
OS version: Win 10
Vimium C version: 1.90.2

**Comment by gdh1995** [comment]
Um, in fact `<<` means two `<` keys. How did you test it (did you press one `<` and a second `<` when you thought it's "delayed")?

**Comment by M-e-r-c-u-r-y** [comment]
> 
> 
> Um, in fact `<<` means two `<` keys. How did you test it (did you press one `<` and a second `<` when you thought it's "delayed")?

Ah I see my bad, yea, I waited a bit and tried the second press, we can close this then as it's working as expected.
