### ISSUE TITLE
map <a-c-s-left> closeTabsOnLeft, the custom command does not take effect?

### ISSUE THREAD

**Issue by tuihou123321** [gdh1995/vimium-c#394]
ctrl+shift+alt+arrow left key, the expression in emacs should be: <a-c-s-left>, is it okay to write this way? ?

But setting shortcut commands in vimium does not take effect, why? ?

The custom code is as follows

```
map <a-c-s-left> closeTabsOnLeft

```

**Comment by gdh1995** [comment]
`map <a-c-s-left> closeTabsOnLeft` works on my Chrome 91 x64 and Win 10. Are you using Firefox on Linux?

**Comment by tuihou123321** [comment]
> `map <a-c-s-left> closeTabsOnLeft` works on my Chrome 91 x64 and Win 10. Are you using Firefox on Linux?

Restarting chrome is useless. After restarting the computer, it finally took effect. 
It has been resolved, thank you

------

The system information is as follows: 
chrome version 91.0.4472.124 (official version) (64-bit) 
system: window10
