### ISSUE TITLE
关于“Select an element and hover”/ “simulated mouseenter”在某些网页上失效的情况

### ISSUE THREAD

**Issue by JasonWongnn** [gdh1995/vimium-c#396]
尊敬的作者您好，和您反馈一下当前状况。
“Select an element and hover”在某些网页上可以正常响应（比如淘宝首页），可以顺利的模拟出鼠标悬停的效果；
但在某些网页上就失效了（比如知乎，若正常的使用鼠标悬停在回答编辑时间，可查看具体发表时间，但插件无法顺利实现该模拟效果）。
您的插件提供了相当大的助力，几乎可说是Vimium插件的plus版本，非常感谢您的开发，若可以改进这一小小的鼠标悬停缺憾肯定会是百尺竿头。

Win10 21H1，火狐91.0b8，插件版本1.90.2

**Comment by gdh1995** [comment]
嗯，虽然没测，但是这个基本上可以确定是唉，浏览器限制没法做。
这个模拟旋停只是触发js事件，让页面自己决定要做什么，但是有的悬停效果是纯css写的，没有考虑过js手动触发悬停的效果，那仅靠浏览器扩展是没法实现同样效果



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月30日(周五) 上午9:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [gdh1995/vimium-c] 关于“Select an element and hover”/ “simulated mouseenter”在某些网页上失效的情况 (#396)




 
尊敬的作者您好，和您反馈一下当前状况。
 “Select an element and hover”在某些网页上可以正常响应（比如淘宝首页），可以顺利的模拟出鼠标悬停的效果；
 但在某些网页上就失效了（比如知乎，若正常的使用鼠标悬停在回答编辑时间，可查看具体发表时间，但插件无法顺利实现该模拟效果）。
 您的插件提供了相当大的助力，几乎可说是Vimium插件的plus版本，非常感谢您的开发，若可以改进这一小小的鼠标悬停缺憾肯定会是百尺竿头。
 
Win10 21H1，火狐91.0b8，插件版本1.90.2

**Comment by gdh1995** [comment]
另外1.90.2应该是，有中文界面吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月30日(周五) 上午9:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [gdh1995/vimium-c] 关于“Select an element and hover”/ “simulated mouseenter”在某些网页上失效的情况 (#396)




 
尊敬的作者您好，和您反馈一下当前状况。
 “Select an element and hover”在某些网页上可以正常响应（比如淘宝首页），可以顺利的模拟出鼠标悬停的效果；
 但在某些网页上就失效了（比如知乎，若正常的使用鼠标悬停在回答编辑时间，可查看具体发表时间，但插件无法顺利实现该模拟效果）。
 您的插件提供了相当大的助力，几乎可说是Vimium插件的plus版本，非常感谢您的开发，若可以改进这一小小的鼠标悬停缺憾肯定会是百尺竿头。
 
Win10 21H1，火狐91.0b8，插件版本1.90.2

**Comment by JasonWongnn** [comment]
尊敬的作者，抱歉我不懂js css等语言（github都不太会用o(ini)o），您说的意思我理解了，可能就是“目前我做这些已经是基线啦，有的网页它就是模拟不出来你就自己看着办吧”的意思吧。

在火狐的插件页面是有中文版本的介绍，根据打开插件的区域不同可选择英文或中文的插件介绍。
具体插件的设置界面的话，我没找到中文的界面，但是个人认为和大部分插件设置有足够的共通之处，已经足够好用了。

发件人: Dahan Gong ***@***.***>
发送时间: 2021年7月30日 10:06
收件人: gdh1995/vimium-c ***@***.***>
抄送: JasonWongnn ***@***.***>; Author ***@***.***>
主题: Re: [gdh1995/vimium-c] 关于“Select an element and hover”/ “simulated mouseenter”在某些网页上失效的情况 (#396)

另外1.90.2应该是，有中文界面吧



---原始邮件---
发件人: ***@***.***&gt<mailto:***@***.***&gt>;
发送时间: 2021年7月30日(周五) 上午9:56
收件人: ***@***.***&gt<mailto:***@***.***&gt>;;
抄送: ***@***.***&gt<mailto:***@***.***&gt>;;
主题: [gdh1995/vimium-c] 关于“Select an element and hover”/ “simulated mouseenter”在某些网页上失效的情况 (#396)





尊敬的作者您好，和您反馈一下当前状况。
“Select an element and hover”在某些网页上可以正常响应（比如淘宝首页），可以顺利的模拟出鼠标悬停的效果；
但在某些网页上就失效了（比如知乎，若正常的使用鼠标悬停在回答编辑时间，可查看具体发表时间，但插件无法顺利实现该模拟效果）。
您的插件提供了相当大的助力，几乎可说是Vimium插件的plus版本，非常感谢您的开发，若可以改进这一小小的鼠标悬停缺憾肯定会是百尺竿头。

Win10 21H1，火狐91.0b8，插件版本1.90.2

―
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

―

**Comment by JasonWongnn** [comment]
尊敬的作者，抱歉我不懂js css等语言（github都不太会用o(╥﹏╥)o），您说的意思我理解了，可能就是“目前我做这些已经是基线啦，有的网页它就是模拟不出来你就自己看着办吧”的意思吧。

在火狐的插件页面是有中文版本的介绍，根据打开插件的区域不同可选择英文或中文的插件介绍。
具体插件的设置界面的话，我没找到中文的界面，但是个人认为和大部分插件设置有足够的共通之处，已经足够好用了。


> 
> 另外1.90.2应该是，有中文界面吧
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年7月30日(周五) 上午9:56 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [gdh1995/vimium-c] 关于“Select an element and hover”/ “simulated mouseenter”在某些网页上失效的情况 (#396) 尊敬的作者您好，和您反馈一下当前状况。 “Select an element and hover”在某些网页上可以正常响应（比如淘宝首页），可以顺利的模拟出鼠标悬停的效果； 但在某些网页上就失效了（比如知乎，若正常的使用鼠标悬停在回答编辑时间，可查看具体发表时间，但插件无法顺利实现该模拟效果）。 您的插件提供了相当大的助力，几乎可说是Vimium插件的plus版本，非常感谢您的开发，若可以改进这一小小的鼠标悬停缺憾肯定会是百尺竿头。 Win10 21H1，火狐91.0b8，插件版本1.90.2 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by gdh1995** [comment]
不用这么客气😀

确实是没法模拟。

Vimium C 有全套中文界面，只是之前有一阵子 firefox 版本写错了，没正确显示中文，但最近一版印象中修复了这个，所以，是不是你把你的 Firefox 自身界面修改成了不是中文？

**Comment by JasonWongnn** [comment]
我明白了，可能是因为我用的Firefox developer edition（没有中文）。感谢您的解答。

**Comment by gdh1995** [comment]
可以手动安装语言包：

![image](https://user-images.githubusercontent.com/5547703/127614493-9ee3007c-0cfe-498e-9800-d180f9c9c0dd.png)
