### ISSUE TITLE
能不能添加一个 edge浏览器的自动翻译全页面的快捷键，

### ISSUE THREAD

**Issue by Stephen2252Ro** [gdh1995/vimium-c#397]
**Describe the bug**
Include a clear bug description
首先能不能添加一个edge浏览器的自动翻译全页面的快捷键，以及自动恢复原文的快捷键。另外有些页面浏览器会弹出是否要翻译全文的提示，能不能给这个提示的两个选项添加一下快捷键，
![image](https://user-images.githubusercontent.com/64295584/128147396-199334ae-507f-40b6-9a4b-73e6e99bfea2.png)

**To Reproduce**
1. Go to URL "..."
2. Click on "..."

It will help a lot if here includes a screenshot when applicable.

**Browser, OS and Vimium C version**

If you're using MS Edge, Chrome, or other Chromium-based browsers,
include the browser and OS version found at `chrome://version`.
Also include the Vimium C version found at `chrome://extensions`.

If you're using Firefox, report the Firefox and OS version found at `about:support`.
Also include the Vimium C version found at `about:addons`.

**Comment by gdh1995** [comment]
这个功能不开放，没法控制，建议换成第三方扩展，像 saladict (https://github.com/gdh1995/vimium-c/issues/247#issuecomment-749481669)、edgetranslate (https://github.com/gdh1995/vimium-c/issues/383) 。

Duplicated as #337 .
