### ISSUE TITLE
shift will make focusInput fail to switch to the last field when there are 2 or more of it

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#398]
macOS 11.5 Chrome 92:

https://user-images.githubusercontent.com/66708845/128190373-aec5d69f-22c8-4906-add5-bcfda17e0412.mov

**Comment by gdh1995** [comment]
What keys did you press in the video? `gi` and then `Shift`? or `gi` and `Shift+Tab` ?

**Comment by OnceThenEver** [comment]
`gi`->`Shift`

**Comment by gdh1995** [comment]
Have you enabled the option named `Allow mapping right-hand (or left-hand) modifier keys` (aka `映射键盘右侧（或左侧）的修饰键`) ?

**Comment by OnceThenEver** [comment]
Yes

**Comment by OnceThenEver** [comment]
Yes

**Comment by gdh1995** [comment]
It seems in such a situation `Shift` should never be treated as `<s-modifier>`. I'll update `focusInput` then.

**Comment by OnceThenEver** [comment]
Thank You

**Comment by gdh1995** [comment]
Hello, v1.92 has been published on Firefox and Chrome stores, and you may take a try.

**Comment by OnceThenEver** [comment]
Verified, thanks
