### ISSUE TITLE
LinkHints.activateModeToDownloadImage

### ISSUE THREAD

**Issue by BioBox** [gdh1995/vimium-c#399]
The title says it all. _`LinkHints.activateModeToOpenImage`_ is an awesome feature, but is there any way to just copy the URL of the image instead of opening it in my tab? Or at least have it open in a new tab so that it doesn't overwrite what I already have?

**Comment by gdh1995** [comment]
Um, the `OpenImage` command should open a new tab by default. How did you map keys and options to it ?

Up to now, there's no command name / command option to copy image URLs, but you may copy in opened image tabs:
* `map xxx Vomnibar.activateUrl` and then on Vimium C Display page, Vomnibar will show an image URL (with a prefix).

**Comment by BioBox** [comment]
Sorry for the late reply. I have it mapped as `map zi LinkHints.activateModeToDownloadImage` and it always opens it in the current tab. I tried disabling my "New Tab Redirect" extension but the behavior still persists.

**Comment by gdh1995** [comment]
Um, please try this: `map zi LinkHints.activateModeToDownloadImage download="force"`.

To use `download="force"`, firstly you need to give Vimium C the "downloads" permission on Vimium C Options page:

![image](https://user-images.githubusercontent.com/5547703/129680355-3ad99ef8-a447-46df-b037-ab65efe3fc18.png)

**Comment by BioBox** [comment]
It simply downloads the image without any hassle. Although I would still prefer to copy the address, this works well enough for me. Thank you!

**Comment by gdh1995** [comment]
Well, in fact `download="force"` may fail on Chrome and in some edge cases, and in some of such cases removing it may make downloading succeed ...

As for copying URL, this need is too rare, so I still recommend `LinkHints.activateOpenImage` and then trigger `Vomnibar.activateEditUrl` .

**Comment by BioBox** [comment]
Ah, okay that works too. When you said `OpenImage` I though you were talking about `activateModeToDownloadImage`. Using `activateOpenImage` and then copying the auto-selected text from the omnibar-edit does the trick. It just takes a few extra steps.

**Comment by gdh1995** [comment]
Um, to copy URL of `<img>` elements, there's a tricky way I once forgot.
```
map Fa LinkHints.activateCopyLinkUrl match="img,video,audio" access="dataset.canonicalSrc,dataset.src,src"
```

This means to only show hints for `img` elements but not background images, and then find its `src` attribute and copy as a URL.
