### ISSUE TITLE
Suggestion: Could the dark mode be...less dark?

### ISSUE THREAD

**Issue by bobf32** [gdh1995/vimium-c#403]
Not a bug, just a suggestion. The vomnibar in dark mode shows mostly with a black background, and a dark grey border. 

I would prefer the black background to be less dark, more of a dark grey. It would be nice if this setting were configurable. Perhaps add a new option where user could enter the desired background colour code?

**Comment by gdh1995** [comment]
You may write custom CSS on Vimium C Options. Please refer to https://github.com/gdh1995/vimium-c/wiki/Style-the-UI-of-Vimium-C-using-Custom-CSS .

**Comment by bobf32** [comment]
Great, thank you.
