### ISSUE TITLE
Error on Vimium-C startup and on Vomnibar.activate

### ISSUE THREAD

**Issue by KrutNA** [gdh1995/vimium-c#406]
### Startup

**Steps to reproduce:**
On Vimium-C startup (for example after disable and enable extension):

**Error:**
![image](https://user-images.githubusercontent.com/31564815/129735478-21fd6e5d-47d3-42f7-ad2c-aa4c1ef9d2eb.png)

### Vomnibar

**Steps to repoduce**
Open any url, like YT, GH, etc.
Trying to open Vomnibar with key (`Vomnibar.activate`). (Same behaviour on `activate` and `activateOpenInNewTab`)
And vomnibar doesn't appear. Also it looks like it takes keys, but nothing happens. I couldn't use `LinkHints.activate` key or any other keys. After pressing <kbd>Esc</kbd> key everything starts working.

**Error** 
![image](https://user-images.githubusercontent.com/31564815/129736231-02002f12-48be-415a-8dfd-fcd4d9b06e36.png)

### Browser, OS and Vimium C version:

Browser: Google Chrome: 92.0.4515.107 (Official Build) (64-bit)

OS: Linux 5.13.6-arch1-1

Vimium-C: 1.92.1, Chrome 92, Linux.

I'm using native Google Chrome dark theme (chrome://flags). Bugs appeared not a long time ago. Everything was working fine before.

**Comment by gdh1995** [comment]
Please reset Locale Encoding to GBK or set it any other string not starting with utf, and reload Vimium C to see whether Vomnibar works or not.

![image](https://user-images.githubusercontent.com/5547703/129750171-4500c436-d6aa-4e6a-b837-e9985526f113.png)


Then this is a bug imported since v1.92.0 - I once reworked too many files and left some typos there.

**Comment by KrutNA** [comment]
@gdh1995 But could you fix it as fast as possible, cause utf-8 is one of the most used encodings.

**Comment by gdh1995** [comment]
It should not affect anything. Vimium C always decode URLs using `utf-8`, and the option is only a fallback when utf8-decoding fails.

**Comment by gdh1995** [comment]
Hello, now v1.92.4 is available on Firefox Add-ons and Chrome Web Store. And you may take a try.

**Comment by KrutNA** [comment]
> Hello, now v1.92.4 is available on Firefox Add-ons and Chrome Web Store. And you may take a try.

Vomnibar with utf-8 encoding works fine now, but I got an error directly after Vimium C update from 1.92.3. Idk, I couldn't reproduce it but I got a screenshot of errors.

![image](https://user-images.githubusercontent.com/31564815/131300102-2c1e964e-5d06-42c1-b313-42bd12cc1d99.png)

**Comment by gdh1995** [comment]
You may remove the unpacked version of Vimium C, and re-install the version published in Web Store.

**Comment by gdh1995** [comment]
The first 2 permission warnings can be ignored, because they works as designed - when Chrome flag `#extensions-on-chrome-urls` is enabled, they will be valid.
