### ISSUE TITLE
Error export options

### ISSUE THREAD

**Issue by raingart** [gdh1995/vimium-c#407]
`options_ext.js:1 Uncaught (in promise) TypeError: e.M.Ho is not a function`

![Screenshot_5](https://user-images.githubusercontent.com/13064767/129737315-ceaf72eb-7a55-487a-9ad4-a96cf522d93d.png)

**Comment by raingart** [comment]
btw
I use the following commands in those extensions that do not have the ability to export/import:

export:
`chrome.storage.local.get(null, a => console.log(JSON.stringify(a)));`
import:
`chrome.storage.local.set(obj_data_exported);`

or
export:
`copy(localStorage);`

import:
`Object.keys(data).forEach(function (k) {
  localStorage.setItem(k, data[k]);
});`

but in your case it will not work because, as I understand it, a custom JSON template is used.
I have never seen anything like this before. In principle, nothing prevents you from updating an already previously exported file

**Comment by gdh1995** [comment]
Priorities are: `storage.sync > localStorage > storage.local`. And if `Synchronize settings with your current account for this browser` option is not checked, then `storage.sync` won't be in use.

**Comment by gdh1995** [comment]
If you has turned off syncing, then `localStorage.setItem` should always work - but you need to reload Vimium C manually, since there can not be listeners on its changes.

If settings are synced, then you may use `storage.sync.get(i => copy(i))` and `storage.sync.set(i)` .

**Comment by gdh1995** [comment]
Could you open Developer Tools on Vimium C's background process? When exporting failed, it should log an error in `background/browsing_data_manager.js` and I'd like to see where the error was thrown. A screen snapshot of a formatted file may help a lot.

**Comment by raingart** [comment]
down work (dont copy) `chrome.storage.sync.get(i => copy(i))` 

need use:
`chrome.storage.sync.get(i => console.log(JSON.stringify(i)))` > manual copy

**Comment by raingart** [comment]
Can you take a look through [anydesk ](https://anydesk.com/en) remotely? I'm too lazy to understand. But I can give you access

**Comment by gdh1995** [comment]
Oh Thank you. You may mail your code to gdh1995@qq.com .

**Comment by raingart** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/13064767/129746533-c2aebd87-0e67-4d67-b04d-992399fa5010.png)
![Screenshot_6](https://user-images.githubusercontent.com/13064767/129746541-accbf2ef-fc8c-4284-a4d0-e373448dcdc4.png)

**Comment by gdh1995** [comment]
The snapshot is not Vimium C's. ID of Vimium C on Chrome Web Store is hfjbmagddngcpeloejdejnfgbamkjaeg .

**Comment by gdh1995** [comment]
Please reset `Locale Encoding` to `GBK` or set it any other string not starting with `utf`, and reload Vimium C to see whether exporting works or not.

BTW, this bug has a same root cause with #406 (Vomnibar broke).

**Comment by raingart** [comment]
Is there a localization problem?
![Screenshot_8](https://user-images.githubusercontent.com/13064767/129750085-1d5b3088-046e-4813-93ff-19cda7584dba.png)

**Comment by gdh1995** [comment]
No.

This is a logic bug imported since v1.92.0 - I once reworked too many files and left some typos there. I forgot to initialize a variable when it's `utf*` .

**Comment by raingart** [comment]
Question: page navigation patterns have case sensitive? (I created a lot of issues here and there, and write here)

"previous" ==? "Previous"
I looked at the code but did not see normalization

A jak to funguje s unicode? And languages ​​with reversed spelling. For example Farsi or Hebrew?
"Předchozí" ==? "předchozí"

**Comment by gdh1995** [comment]
> dont work (dont copy) `chrome.storage.sync.get(i => copy(i))`

Oh it's because `copy` is a console function - not accessible in lambda functions.

**Comment by raingart** [comment]
lambda functions its [Arrow Function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions)?

**Comment by gdh1995** [comment]
Yes `goNext` converts patterns using `String.toLowerCase()`. As for unicode, I don't know ...

If a word (split by `,`) starts with a character in `.#[`, then it's used as a CSS selector, so you may write CSS selectors (case-sensitive) to work on non-English pages.

**Comment by gdh1995** [comment]
> lambda functions its

Indeed. `i => copy(i)` does not work on console. And your `manual copy` is right.

**Comment by raingart** [comment]
Thanks!
then I'll close the issues?

**Comment by gdh1995** [comment]
Feel free to close or reopen issues.
