### ISSUE TITLE
hide closing UI in popup when scrolling

### ISSUE THREAD

**Issue by raingart** [gdh1995/vimium-c#408]
in [Show available commands.](chrome-extension://hfjbmagddngcpeloejdejnfgbamkjaeg/pages/options.html#commands) better css fixed the button close.

![Screenshot_2](https://user-images.githubusercontent.com/13064767/129739017-64186e2c-1add-4032-ab49-e5277df87543.png)
![Screenshot_1](https://user-images.githubusercontent.com/13064767/129739020-02e6e12b-d27c-470a-a83d-a84470748d2c.png)

**Comment by gdh1995** [comment]
Um, you can press <kbd>Esc</kbd> to hide it...

**Comment by raingart** [comment]
add to title "Close (Esc)"

**Comment by gdh1995** [comment]
I think it's not necessary - when you get familiar with Vimium C, you may notice all of its UI can exit by `<esc>` and `<c-[>` - so do Vomnibar, LinkHints, Marks, VisualMode and Find HUD.
