### ISSUE TITLE
undocumented mapping command

### ISSUE THREAD

**Issue by raingart** [gdh1995/vimium-c#409]
if use keyMappings:
`map t newTab`

ist working, but in [manual](chrome-extension://hfjbmagddngcpeloejdejnfgbamkjaeg/pages/options.html#commands) described what to use `Create new tabs (createTab)`
like: 
`map t createTab`

this is not a mistake, it is simply not described. Perhaps it is worth listing the commands synonyms

**Comment by gdh1995** [comment]
`newTab` is an alias to `createTab` (to help those who don't want to remember what names are normalized), while the help dialog only shows normalized names.

The normalization process is in:
https://github.com/gdh1995/vimium-c/blob/8d4c0705a77d8f1add8b69a300f3665470cfadd1/background/help_dialog.ts#L120-L151
