### ISSUE TITLE
How to re-map <Esc>ape key sequence from Visual mode back to Normal mode?

### ISSUE THREAD

**Issue by andrewwxy** [gdh1995/vimium-c#41]
Issue:
  Tried and failed to re-map Escape sequence FROM Visual Mode TO Normal Mode.

Where:
  chrome-extension://hfjbmagddngcpeloejdejnfgbamkjaeg/pages/options.html#!newTabUrl

What FAILed:
  map jk < esc> [padded space inserted for preview mode only]
  map jk < Esc> 
  map jk isEscape_

  PASS R
  FAIL map jk Esc
  https://github.com/gdh1995/vimium-c/blob/d2ba7c9b96756491b30694961df871c9b555a8b5/content/mode_visual.ts
        Switch back to plain find mode by the "<kbd>\R</kbd>" escape sequence.

Where Else?
  https://github.com/gdh1995/vimium-c/search?q=%3cesc%3e&unscoped_q=%3cesc%3e
  https://github.com/gdh1995/vimium-c/search?q=escape+sequence&unscoped_q=escape+sequence

  https://github.com/gdh1995/vimium-c/blob/af9d99344eed0147be8859a21f41162f678843b0/pages/options.html
        Switch back to plain find mode by the "<kbd>\R</kbd>" escape sequence.
  https://github.com/gdh1995/vimium-c/blob/d2ba7c9b96756491b30694961df871c9b555a8b5/content/mode_visual.ts
      if (VKeyboard.isEscape_(event)) {
      a.currentCount_ || a.currentSeconds_ ? a.resetKeys_() : a.deactivate_(1);
  https://github.com/gdh1995/vimium-c/blob/98d8ef80ae2fbe62be923887d08f95d3e7c5f381/types/vimium_c.d.ts
    declare const enum VKeyCodes {
    None = 0,
    backspace = 8, tab = 9, enter = 13, shiftKey = 16, ctrlKey = 17, altKey = 18, esc = 27,
        

Greatly appreciated.

**Comment by gdh1995** [comment]
Currently you can not. I've added to to the TO-DO list in the next week, and there may be it in Vimium C v1.75.2 / v1.75.3.

**Comment by andrewwxy** [comment]
OIC, no worries, I'll keep watch then.
FYI, its a most excellent emulation of Vim.

**Comment by gdh1995** [comment]
Now, since Vimium C v1.75.2, `mapKey` supports any source key and any target key, including `<esc>` and `<c-[>`, so `mapKey <f1> <esc>` will work.

Note: the `key` above means a character and some control keys, but not two or more key chars, so `mapKey jk <esc>` will only cause an error report.

**Comment by andrewwxy** [comment]
非常好🙏 @gdh1995
So, 
mapKey <esc> jk

will also work?

**Comment by gdh1995** [comment]
No, `j` and `k` are two keys, so it's an invalid mapping. A correct mapping should look like `mapKey <srcKey> <targetKey>` - there're 3 space-splitted parts: `"mapKey"`, a source key and the targetKey.

A key is either a single visible (printable) character, or a long string wrapped by `<` and `>`, if the string in `<` and `>` is longer than one character.

The detailed usage is just like https://github.com/philc/vimium#custom-key-mappings

Although Vimium C is able to auto correct some mistaken spelling, here're some formats which are different with Vimium:
* if you need to use `Ctrl/Alt/Meta`+`Shift`+`Non-printable-character`, add `s-` to it. For example, `<c-s-f6>` is correct.
* if the main part is a printable character and its lower case and UPPER case are different, then:
  * if Ctrl/Alt/Meta has been pressed, use `s-` and the lower case of the main part, like `<c-s-f>`
  * if only ShiftKey has been pressed, use its UPPER case only (when the Caps Lock is off)

BTW, if you want to type `<esc>` on GitHub issues, you need to type ``` `<esc>` ``` (wrap `<esc>` with two [grave accent](https://www.google.com.hk/search?ie=utf-8&q=%60)).

**Comment by glyh** [comment]
Is it possible to map a same key to both open visual mode and close visual mode? Thanks!

**Comment by gdh1995** [comment]
You may map a key to `<esc>` only in a mode:
```
map v enterVisualMode
mapKey <v:v> <esc>
```

See https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout#per-mode-mapkey
