### ISSUE TITLE
Website icons and import settings bug

### ISSUE THREAD

**Issue by GiancarloAparicio** [gdh1995/vimium-c#410]
**Describe the bug**

* Website icons don't appear in searches
* The functionality and import does not work

**To Reproduce**
After updating vimium-c, i realized that the Website icons did not appear 

Before they looked like this:
![11111111](https://user-images.githubusercontent.com/61440825/129818320-3b1de4b2-a894-4d09-b040-be5a883bc46a.png)

thinking that maybe it was a matter of my configuration, I exported my configuration and removed vimium-c, however the Website icons did not appear anyway.

![test](https://user-images.githubusercontent.com/61440825/129818256-119acef9-b940-4b75-8758-5e23e8b3135f.png)

When I try to import my data again, it doesn't work either, it just doesn't load anything.

1. Import a configuration file

**Browser, OS and Vimium C version:**

Chrome: 92.0.4515
Vimium:  1.92.1 
SO: Linux

**Comment by pickalexrener** [comment]
same as well
![Quicker_20210818_090739](https://user-images.githubusercontent.com/51726771/129820441-3c7f073e-3459-4a47-aab8-41ad17369756.png)

**Comment by gdh1995** [comment]
> import

As said in https://github.com/gdh1995/vimium-c/issues/407#issuecomment-900366306, please reset `Local Encoding` to `GBK` or set it any other string not starting with `utf`, and retry.

**Comment by BioBox** [comment]
I never changed the local encoding and it still doesn't work for me (gbk is the default).
Tried uninstalling and reinstalling and still no dice.

My info according to Vimium-C:
Vimium C 1.92.1, Chrome 92, Linux.

**Comment by gdh1995** [comment]
@BioBox Sorry there's indeed a bug affecting setting syncing and importing, if you have enabled syncing. Please try the method in https://github.com/gdh1995/vimium-c/issues/413#issuecomment-903154318 :

> Sorry it's a bug when enabling syncing.
> 
> Please run in Developer Tools (press `F12` and go to `Console` panel):
``` javascript
localStorage.vimSync = "false";
```
> 
> And then reload Vimium C.
> 
> **Added:** this code will disable syncing. You may modify your backup file by: add `"vimSync": false,` as a line to the JSON object, and then importing the file should work.

**Comment by BioBox** [comment]
Okay, thanks. I look forward to when this is fixed.

**Comment by gdh1995** [comment]
Sorry I've found another bug affecting importing. I'll publish v1.92.4 to fix it (in days).

There's an ugly working around for it:
1. switch your browser language into Chinese and restart your browser
2. import settings on Vimium C Options
3. then switch browser language back

**Comment by gdh1995** [comment]
Hello, now v1.92.4 is available on Firefox Add-ons and Chrome Web Store. And you may take a try.
