### ISSUE TITLE
Discord webpage doesnt see servers at clickable links

### ISSUE THREAD

**Issue by BurnyCoder** [gdh1995/vimium-c#412]
Each server on the right is clickable to go to that server, but pressing f doesnt give them keybinds, it gives keybinds only to channels in the current server, it would be nice if you could go to different servers using keybinds too.
[https://i.imgur.com/brkHrsQ.png](https://i.imgur.com/brkHrsQ.png)

**Comment by gdh1995** [comment]
Try add this to your key mappings on Vimium C Options:
```
unmap f
env discord host="https://discord.com/"
map f runKey expect="discord:<v-discord_f>" keys="<v-f>"
map <v-f> LinkHints.activate
map <v-discord_f> LinkHints.activate clickable="[class^=member-]"
```

I've also added a wiki: https://github.com/gdh1995/vimium-c/wiki/Add-or-remove-hints .
