### ISSUE TITLE
visitPreviousTab feature request 

### ISSUE THREAD

**Issue by tirphana** [gdh1995/vimium-c#416]
**What command or commands**

visitPreviousTab

**How should a feature do**

When a user has done such steps:

1. Open three new tabs, regardless the URL
2. Discard the one that was opened last using "Auto Tab Discard" or any other similar addon
3. The focus jumps to the tab that was opened second, now execute Vimium's `visitPreviousTab` command

then Vimium C should do:

1. Jump to the tab that was opened first, and is still active. But, by default it jumps to (and refreshes) the third one, which is indeed the one previously used. However, during regular usage I find that discarding a tab is in a sense almost equivalent to closing it, and it would be much better if discarded tabs would be treated as such by this command, instead of refreshing them.

**Browser and OS**

- Browser name: Firefox 89.0.2, Vimium 1.92.4
- OS name: Arch Linux

**Comment by gdh1995** [comment]
Hello, Vimium C v1.95.0 has been released on Firefox Add-Ons for weeks, and then this should work now:
```
map xxx visitPreviousTab filter="discarded=false"
```

**Comment by tirphana** [comment]
Unfortunately, it doesn't seem to be fixed, I'm still returned to the previously discarded tab.

Using Vimum C v1.96.2

**Comment by gdh1995** [comment]
Sorry there's a bug in v1.96.2 about this. To work around it, you may use `... filter="discarded=true"` in v1.96.2, but when this bug gets fixed, you will need to use `discarded=false` again.

**Comment by tirphana** [comment]
>you may use ... filter="discarded=true" in v1.96.2

Already tried that myself, it still does the same thing regardless.

>when this bug gets fixed, you will need to use discarded=false again

Guess I'll just wait for it then. 👍

**Comment by gdh1995** [comment]
> it still does the same thing regardless

Sounds like you were using a wrong key mapping. What's your real key mapping for `visitPreviousTab`? Please paste it here. Thanks.

**Comment by tirphana** [comment]
map <c-#> visitPreviousTab filter="discarded=true"

**Comment by gdh1995** [comment]
Oh I found another small issue making `discarded=true` not work. They will be fixed in a new version of Vimium C.

**Comment by gdh1995** [comment]
Oh, `map <c-#> visitPreviousTab filter="discarded=only"` should "succeed" in filtering out discarded tabs in v1.96.2 .

**Comment by gdh1995** [comment]
Hello, you may take a try with Vimium C v1.96.3 on Firefox Add-Ons, which has fixed some bugs about `filter`.

**Comment by tirphana** [comment]
Yaaay, it works now, thank you for implementing this! :+1:
