### ISSUE TITLE
[bug] Settings json import not working on v1.92.0~v1.92.3

### ISSUE THREAD

**Issue by tommyalatalo** [gdh1995/vimium-c#418]
**Describe the bug**

When exporting the settings json file on one computer (Firefox) and then importing it on another (Brave or Iridium), the settings are not loaded into the options, and the "Save" button is not enabled.

**To Reproduce**

1. Change some settings on the options page on Firefox
2. Export the settings as a json file using the `Export Settings` button
3. Load the settings json file in the Iridium or Brave browser, vimium c settings, using the `Import Settings` button
4. Observe that no settings were imported 

**Browser, OS and Vimium C versions**

```
- Browser name: Firefox
- Browser version: 91.0.2
- Vimium C version: 1.92.4
- OS name and version: EndeavourOS (Arch Linux)
```
```
- Browser name: Iridium
- Browser version: Version 2021.06 (Iridium Build) (64-bit)
- Vimium C version: 1.92.4
- OS name and version: EndeavourOS (Arch Linux)
```
```
- Browser name: Brave
- Browser version: Version 1.28.106 Chromium: 92.0.4515.159 (Official Build) (64-bit)- Vimium C version: 1.92.4
- OS name and version: EndeavourOS (Arch Linux)
```
Iridium version details:
```
Iridium	2021.06 (Iridium Build) (64-bit)
Revision	4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS	Linux
JavaScript	V8 9.1.269.36
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
Command Line	/usr/lib64/chromium/chromium --password-store=detect --enable-threaded-compositing --ui-disable-partial-swap --flag-switches-begin --flag-switches-end
Executable Path	/usr/lib/chromium/chromium
Profile Path	/home/tommy/.config/iridium/Default
```
Brave version details:
```
Brave	1.28.106 Chromium: 92.0.4515.159 (Official Build) (64-bit)
Revision	0185b8a19c88c5dfd3e6c0da6686d799e9bc3b52-refs/branch-heads/4515@{#2052}
OS	Linux
JavaScript	V8 9.2.230.29
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
Command Line	/usr/lib/brave-bin/brave --enable-crashpad --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=PasswordImport,ReducedReferrerGranularity,WebUIDarkMode,PrefetchPrivacyChanges,DnsOverHttps,LegacyTLSEnforced,AutoupgradeMixedContent,SafetyTip --disable-features=AutofillServerCommunication,FledgeInterestGroups,FlocIdComputedEventLogging,HandwritingRecognitionWebPlatformApiFinch,HandwritingRecognitionWebPlatformApi,IdleDetection,InterestCohortFeaturePolicy,DirectSockets,TrustTokens,SignedExchangeSubresourcePrefetch,LiveCaption,FledgeInterestGroupAPI,AutofillEnableAccountWalletStorage,InterestCohortAPIOriginTrial,FirstPartySets,FederatedLearningOfCohorts,PrivacySandboxSettings,NetworkTimeServiceQuerying,SubresourceWebBundles,SignedExchangePrefetchCacheForNavigations,EnableProfilePickerOnStartup,TextFragmentAnchor,NotificationTriggers,WebOTP,EnablePasswordsAccountStorage,LangClientHintHeader --flag-switches-begin --flag-switches-end
Executable Path	/usr/lib/brave-bin/brave
Profile Path	/home/tommy/.config/BraveSoftware/Brave-Browser/Default
```

**Comment by gdh1995** [comment]
Hello, now v1.92.4 is available on Firefox Add-ons and Chrome Web Store. And you may take a try.

**Comment by tommyalatalo** [comment]
I just updated on Iridium, and it works nicely.

One other small question, when I imported this other host I see that the interpretation of dark mode is no the same (i.e. the styles I set for `.D>.LH` were not applied on the new host), is there a way to force dark mode for the general css, like we can do for the vomnibar with `"styles": "dark"`?

**Comment by gdh1995** [comment]
> the styles I set for `.D>.LH` were not applied on the new host

Sorry I didn't understand this. What's "a new host"?

If you have clicked the "Save Options" button, then "Custom CSS for Vimium C UI" should work on all normal websites.

`.D` means it's only applied when your browser is in dark mode (not a dark theme simulated by extensions like "Dark Reader"). So it should either take effect on all tabs, or is ignored on all tabs.

So, what did you mean by "force dark mode for the general css"? If you want to apply `.D` even your browser is not in dark mode, then currently there's no way in Vimium C to do so, but you may just remove `.D>` prefix to get your custom CSS always take effect.

**Comment by tommyalatalo** [comment]
> > the styles I set for `.D>.LH` were not applied on the new host
> 
> Sorry I didn't understand this. What's "a new host"?
> 
> If you have clicked the "Save Options" button, then "Custom CSS for Vimium C UI" should work on all normal websites.
> 
> `.D` means it's only applied when your browser is in dark mode (not a dark theme simulated by extensions like "Dark Reader"). So it should either take effect on all tabs, or is ignored on all tabs.
> 
> So, what did you mean by "force dark mode for the general css"? If you want to apply `.D` even your browser is not in dark mode, then currently there's no way in Vimium C to do so, but you may just remove `.D>` prefix to make your custom CSS always take effect.

**Comment by Shahin-rmz** [comment]
Hi
I have a vimium settings as json data.
just want to import the settings to Vimium C and get the error that this is not the Vimium C config Format.
Any idea how to import it?
Thanks

**Comment by gdh1995** [comment]
@Shahin-rmz Hello, Vimium C doesn't use the format of Vimium settings file - in fact, Vimium C implemented settings exporting and importing earlier than Vimium (2015 vs. 2017). So please migrate your configuration manually.

Most options can be imported by copying text on Vimium Options and pasting it onto corresponding text boxes on Vimium C Options. The page will convert syntax if necessary.
