### ISSUE TITLE
Support custom key mapping for Chrome's native search tab

### ISSUE THREAD

**Issue by ryan-efendy** [gdh1995/vimium-c#419]
As a user I'd like to be able to map [toggle Chrome's native tab search](https://support.google.com/chrome/answer/10490587?hl=en) to a custom key. Can we add this to the list of available commands?

![image](https://user-images.githubusercontent.com/12979345/131171943-daecb506-c8a5-471a-8b8a-ef134fd81f37.png)

**Comment by gdh1995** [comment]
Sorry but I think there's no API in Chrome's extension platform to do so.
