### ISSUE TITLE
make new tab empty

### ISSUE THREAD

**Issue by mimooh** [gdh1995/vimium-c#42]
I love this plugin! But I need to remove chrome-extension://hfjbmagddngcpeloejdejnfgbamkjaeg/pages/blank.html from the address bar for every new tab. Can I have really empty new tab?

**Comment by gdh1995** [comment]
No, if you only use the version in Chrome WebStore.

If you can compile Vimium C's source code, then it's easy to do so: just modify `OverrideNewTab` in types/build/index.d.ts to `0`, and then run `gulp dist`.

**Comment by mimooh** [comment]
OK, thank you

**Comment by rdewolff** [comment]
Why do we need to recompile to do this ?
I dont like the fact that when I create a new tab, I don't have the scope in the address bar. Any workaround for this @gdh1995 ??

**Comment by gdh1995** [comment]
@rdewolff  On the latest version of Vimium C, the option "Focus web page when creating a new tab" may help you. But the behavior of overriding default NewTab URL can not be changed dynamically.

**Comment by rdewolff** [comment]
Wouhou, that works great. Thanks a lot for your immediate answer!
