### ISSUE TITLE
Bookmarks deletion support in Vomnibar

### ISSUE THREAD

**Issue by 2b** [gdh1995/vimium-c#421]
Is there any way to remove bookmarks in Vomnibar in Chromium-based browsers? For now, when you press Shift+Del on a bookmark in Vomnibar, Vimium displays "This item cannot be deleted".

Thank you.

**Comment by gdh1995** [comment]
Vimium C doesn't provide any way to delete a bookmark, to keep this extension reliable and avoid accidental mistaken operation. So, please use other professional extensions to manage your bookmarks.
