### ISSUE TITLE
Feature Request: Hop to any visible text

### ISSUE THREAD

**Issue by matheusfillipe** [gdh1995/vimium-c#422]
**What command or commands**

A new command to help on selecting text.

**How should a feature do**

The goal is not have to use a mouse to select text. The visual mode works perfectly the issue is getting the cursor to the point you want to select from.
The carrot mode or searching for what you see and then going through the matches until you are where you want to start a selection is too slow and using a mouse would be a sin.
Inspired on https://github.com/phaazon/hop.nvim I think it would be the best to maybe have f on visual or carrot mode to act like hop (or easy motion) accepting one character as input and generating hints for the matching text of the webpage for what is currently visible. 

1. The user opens a webpage
2. Presses v for visual mode
3. f for generating hings on selectable text.
4. Then he types one character and hints for it are generated.
5. He writes them and the cursor is placed on the desired position.

Then he can continue with the visual mode commands. 

**Browser and OS**

- Browser name: Firefox
- OS name: Linux

**Comment by gdh1995** [comment]
Um, you may try the current `LinkHints.activateSelect` command.

**Comment by matheusfillipe** [comment]
Hah! Sorry for bothering about this, that command is already quite good enough or this!
