### ISSUE TITLE
Inject Vimium C into Chrome's Reader Mode

### ISSUE THREAD

**Issue by ryan-efendy** [gdh1995/vimium-c#423]
As a user I'd like to be able to use Vimium C keyboard shortcut in Chrome's Reader Mode

![image](https://user-images.githubusercontent.com/12979345/131764826-a8c909d8-c699-4e76-a0d6-ef5b1eea4fc6.png)

![image](https://user-images.githubusercontent.com/12979345/131764830-d913e6a3-fd56-47e1-ba06-358765d7bcbf.png)

**Comment by gdh1995** [comment]
Um, up to now Chrome doesn't provide any way to run Vimium C on such reader-mode tabs. But you may still use "browser-level shortcuts" on `chrome://extensions/shortcuts` to trigger commands of Vimium C.

Vimium C has 8 shortcut placeholders, and if it's not enough for you, you may use another extension like https://chrome.google.com/webstore/detail/shortcut-forwarding-tool/clnalilglegcjmlgenoppklmfppddien to add 30 items.
