### ISSUE TITLE
Gmail: Can't press escape to close labels menu

### ISSUE THREAD

**Issue by ayroblu** [gdh1995/vimium-c#425]
**Describe the bug**

Can't press escape to close Gmail menu. I tried to use the passthru function, but this did not work either. I disabled `<esc>` specifically in the options and then it works. Vimium has the same issue, but using the passthru function does work on Vimium

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to gmail
2. Select an email (checkbox)
3. Open the "Labels" menu
4. Press Escape key

![image](https://user-images.githubusercontent.com/4915682/131929421-54294044-6389-4fe3-82f2-b89ca5d07d6d.png)

**Browser, OS and Vimium C versions**

- Browser name: Chrome
- Browser version: 92.0.4515.131
- Vimium C version: 1.92.4
- OS name and version: MacOS Big Sur 11.4

**Comment by ayroblu** [comment]
Discovered this. It's a sufficient workaround for me. Can close if not relevant!

```
map ' openUrl url="vimium://status\u0020toggle\u0020^\u0020'"
```

**Comment by gdh1995** [comment]
GMail will close the menu on `<esc>` only when the label input bar is focused, so you need to trigger `passNextKey` when the input is focused. Then you may refer the `map some keys which contains F1 ~ F12` section on https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box .

Here's an example:
```
mapKey <c-]> <v-f1>
map <v-f1> passNextKey
```

And then `<c-]` will always work as `passNextKey`, even when an input or textbox is focused.

**Comment by gdh1995** [comment]
Or there's a new command named `dispatchEvent` and it can simulate `Escape` key events:
```
mapKey <c-]> <v-f1>
map <v-f1> runKey keys="<v-esc>+-<v-esc>"
map <v-esc> dispatchEvent type="keydown" code="Escape" key="Escape" keyCode=27
```

**Comment by ayroblu** [comment]
This works thanks!

**Comment by ayroblu** [comment]
Oh I swore this was working before. But now again, when I am insert mode, and then try to use this it doesn't work.
I think from reading the wiki, if you're in insert mode, then nothing works? I can't activate the passNextKey function and so it can't send through it?

**Comment by gdh1995** [comment]
What's your "insert mode"? The one from `enterInsertMode`? Or the one by `vimium://status toggle`?

In the Wiki page are some tips:
> Vimium C will keep such keys, whose main key is `F1~F12`, usable even **in a default insert mode**
> * of course **not** in the insert mode entered by the command `enterInsertMode`

If you want so, please use another tip in the same Wiki page:
> configure global shortcuts on `chrome://extensions/shortcuts`

**Comment by gdh1995** [comment]
Um, and a 3rd rule is "long keys starting with `v-` always work in a plain insert mode since v1.92.0", so if your plain insert mode refuses such a way, then I guess you replaced `<v-f1>` with another key name not starting with `<v-`. Am I right?

**Comment by ayroblu** [comment]
Version: 1.92.4

Custom key mappings with only:
```
mapKey <c-]> <v-f1>
map <v-f1> passNextKey
```

Pressing <c-]> only works in normal mode not insert mode `enterInsertMode`
So no remapping

This works sufficiently well for me, so I'll use the status toggle
```
map ' openUrl url="vimium://status\u0020toggle\u0020^\u0020'"
```

**Comment by gdh1995** [comment]
Um, yes `enterInsertMode` means to ignore all key mappings (`map` and `mapKey`) except keys to exit the mode itself (`<esc>` and `<c-[>`).

**Comment by gdh1995** [comment]
The only way to trigger commands in a "global insert mode" entered by `enterInsertMode` is to use "browser shortcuts" - see https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box#shortcuts for detailed usages.
