### ISSUE TITLE
`LinkHints.activateOpenInNewForegroundTab` not working

### ISSUE THREAD

**Issue by hacker-DOM** [gdh1995/vimium-c#430]
Hi! I have (among others):

```
map T LinkHints.activateOpenInNewForegroundTab
```

In Vimium, it works correctly. In Vimium C, it does not. I get the "Open link in new active tab", then when I click the keyboard combination, the link is highlighted, but no tabs are opened. I am on:
- Vimium C - 1.92.4
- Brave - Version 1.29.79 Chromium: 93.0.4577.63 (Official Build) (x86_64)
- MacOS - 11.5.2

**Comment by hacker-DOM** [comment]
Weird; it's working now, I don't think I did anything 👍

**Comment by gdh1995** [comment]
Um, do you mean it failed and then worked on a same link or button?

If no tabs are opened, then there're usually some possible reasons:
* a page runs JavaScript code to block mouse clicks and then does not "opening a link in a new tab" but any other thing it wants
* on the page Vimium C runs into a bug and fails in simulating mouse click events

If you found Vimium C's `LinkHints.activateOpenInNewForegroundTab` always fails to open a new tab, but your "click by a real mouse" does work, then it might be a bug of Vimium C. Please let me know if so.
