### ISSUE TITLE
自定义数字键打开标签的旧版语法不再兼容了

### ISSUE THREAD

**Issue by adangran** [gdh1995/vimium-c#431]
**What command or commands**
我原先在配置中添加这两行  

```
mapkey 2 <v-2>  
map <v-2> createTab url="https://www.zhihu.com/"  
```

这样按2 就能打开知乎，在输入框内按2正常输入2

但更新到1.92.4 不管是不是在输入框内按2都是直接打开知乎，无法输入2

请问，应该怎么设置才能恢复按数字键打开标签的功能

**How should a feature do**

When a user has done such steps:

then Vimium C should do:

**Browser and OS**

- Browser name: edge 
- OS name: windows 10

**Comment by gdh1995** [comment]
呃抱歉这个是加新特性造成了不同版本的配置不兼容，现在“`<v-***>`”始终会触发快捷键，而不管是不是在输入框里。

对于你这个需求，在 v1.92 以后版本上，请改成：
```
mapkey <2:n> <v-2>
map <v-2> createTab url="https://www.zhihu.com/"
```

**Comment by adangran** [comment]
升级到1.98.2后这个语法又失效了

**Comment by gdh1995** [comment]
这是个新bug，见 https://github.com/gdh1995/vimium-c/issues/656 。等下一版会修复。
