### ISSUE TITLE
page turning ineffective in some dialog with scroll bar

### ISSUE THREAD

**Issue by hellorayza** [gdh1995/vimium-c#432]
**Describe the bug**
也许是我没有正确使用，在知乎的评论对话框中，几个翻页按键(u,d, hjkl)失效。

**Browser, OS and Vimium C versions**

- Browser name: edge
- Browser version: 93.0.961.44
- Vimium C version: 1.92.4
- OS name and version: windows11 professional 22000.184

**Comment by gdh1995** [comment]
输入文字的时候默认就是让大部分快捷键失效的，除了带有 F1~F12 的键。需要在输入框里触发 Vimium C 命令的话，可以参考 https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box 里的办法。

**Comment by hellorayza** [comment]
抱歉我没说清，是知乎评论的弹出框中，翻页键只能让弹出框后面的网页翻页

**Comment by gdh1995** [comment]
呃这个是因为没能自动发现对话框是“可滚动对象”，这时候按 `f` 找到对话框左上角，会有个暗红色字体的提示标签，选中它后就能滚动对话框了。

**Comment by hellorayza** [comment]
哈哈可以了，谢谢这么棒的插件

**Comment by hellorayza** [comment]
> 输入文字的时候默认就是让大部分快捷键失效的，除了带有 F1~F12 的键。需要在输入框里触发 Vimium C 命令的话，可以参考 [gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box](https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box) 里的办法。

在输入框中输入的时候也会有一些快捷键监听吗？最近我在windows电脑浏览器上遇到一些输入法的问题：在输入框使用双拼输入的时候经常会遇到吞字现象(候选汉字直接消失，拼音进入到输入框)，此时我在其他软件中输入相同的键位就不会出现吞字现象，回到浏览器在刚才的输入框中依然可以复现。我不确定是哪里出了问题。

**Comment by gdh1995** [comment]
在浏览器扩展管理页面里，彻底关掉/重新开开 Vimium C 试试？不确定是浏览器问题、还是 Vimium C 执行了什么。每次开关 Vimium C 后要重新刷新测试的标签页。

输入框里监听F1~F12 和 `<***:i>` 映射，前提都是用 map、mapkey 指令映射过。对于 ime 事件也是默认忽略的，按说中文环境不会出现这个问题。

倒是有个报告，在 FindMode 的右下角输入框里输入韩文，会造成类似的丢词+候选上屏的问题。你是在哪些输入框里遇到了？Vomnibar 里会遇到吗？

**Comment by hellorayza** [comment]
感谢帮助。
吞字现象我只在浏览器的输入框中遇到过，比如edge地址栏，搜索框、一些网站评论框。
我使用Vomnibar 频率较低，我后面会继续观察的。

**Comment by gdh1995** [comment]
能确认 edge 地址栏里也出现过？那就不是 Vimium C 的问题了，因为它管不到这儿。

一般来说是输入法和浏览器的兼容性问题，这类问题也算常见吧。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月9日(星期三) 上午10:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [gdh1995/vimium-c] page turning ineffective in some dialog with scroll bar (#432)





 
感谢帮助。
 吞字现象我只在浏览器的输入框中遇到过，比如edge地址栏，搜索框、一些网站评论框。
 我使用Vomnibar 频率较低，我后面会继续观察的。
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hellorayza** [comment]
我知道了是别的插件(Grammarly)的原因

**Comment by gdh1995** [comment]
Grammarly 也不该影响地址栏吧？
