### ISSUE TITLE
No LinkHints on headlines of SalaDict's Wiki Section

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#433]
![截屏2021-09-13 04 19 02](https://user-images.githubusercontent.com/66708845/133001830-d3d37b8b-29e9-4f54-96e8-ac92f74d0671.png)

**Comment by gdh1995** [comment]
Um, a quick fix is:
```
map f LinkHints.activate clickable=".section-heading"
```

Related wiki: https://github.com/gdh1995/vimium-c/wiki/Add-or-remove-hints
