### ISSUE TITLE
按 F 后淘宝首页搜索栏可以夺取输入焦点

### ISSUE THREAD

**Issue by alayamanas** [gdh1995/vimium-c#436]
进一步地，观察到taobao.com首页加载完毕较慢，在其加载完毕前按下f键，随后某时刻网页加载完毕搜索栏便夺取了输入焦点

**Comment by gdh1995** [comment]
阻止焦点是面向“新加载网页”的，所以如果你按了某个键，那这个网页就不“新”了，淘宝就能获取焦点。

回头我给 f 加一个拦截焦点的功能吧。

**Comment by gdh1995** [comment]
Hello. Vimium C v1.94.0 has also been available on MS Edge Add-ons.
