### ISSUE TITLE
LinkHints.activate should take effect on pull down list

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#439]
Like the one besides “导入配置“ at Vimium-C setting page.

**Comment by gdh1995** [comment]
It's a limitation of your browser. Please see https://github.com/philc/vimium/issues/2257#issuecomment-249346014 for more info.

LinkHints will "`focus`" it and then you may use `<Space>` to show its list, and `ArrowDown` and `ArrowUp` to switch among items.

**Comment by OnceThenEver** [comment]
> LinkHints will "`focus`" it and then you may use `<Space>` to show its list, and `ArrowDown` and `ArrowUp` to switch among items.

Following your instruction, I discovered a strange and trivial bug:
Under below settings, what you described didn't happen:
```
map f runKey expect={"Sala":"<v-sala>","cBm":"<v-cbm>"} keys="<v-f>"
map <v-f> LinkHints.activate
```
But the default settings do.

**Comment by OnceThenEver** [comment]
Acknowledged
