### ISSUE TITLE
Tab switching using `T` often doesn't work

### ISSUE THREAD

**Issue by clawoflight** [gdh1995/vimium-c#44]
I have no idea how to debug this and I haven't found a consistent pattern yet.

The vomnibar always opens and filters properly, but when I select a tab, it often doesn't take me there. It may have something to do with which page I want to switch from or to, but I'm not sure yet.

What I have noticed is that the other tab still appears to be loaded:
If I re-open the browser and switch to a youtube tab, it the tab and video will load and start to play, but the selected tab remains the one I was on before.

This is really irritating, partly because it doesn't make any sense and partly because the fuzzy tab selection is one of the main use-cases for me.

*NOTE*: I cannot reproduce this with Vimium, so I guess it was introduced in here, but that's all I know :/

**Comment by gdh1995** [comment]
What browser and version are you using? Is your Vimium C latest (v1.75 or later)? BTW, when you confirm to switch to another tab, are you pressing "Enter" or "Ctrl+Enter"?

**Comment by gdh1995** [comment]
Confirmed. Thanks.

It seems to happen randomly. I'll try to find why and fix it.

**Comment by clawoflight** [comment]
Using Brave, also tried Chromium.
And I am confirming using "Enter". Is there a difference between the 2?

Thanks for looking into it!

**Comment by gdh1995** [comment]
Is this problem only occuring since Vimium C's v1.75 ? Or also before v1.74.9?

There should be no difference between Enter and Ctrl/Shift+Enter in "tab selection" mode of Vomnibar. I once worried some logic error about it, but after some tests I think it's not the reason of this problem.

**Comment by clawoflight** [comment]
I only just discovered Vimium C, I used Qutebrowser as primary browser for a while and wanted to try out Brave. So I can't help bisect the version.

**Comment by gdh1995** [comment]
I've published Vimium C v1.75.4, which should solve this issue. If there's still any problem, please let me know. Thank you again!

**Comment by clawoflight** [comment]
I think the problem is finally gone, thank you :)
