### ISSUE TITLE
如何复制图片地址？

### ISSUE THREAD

**Issue by Wooolfboy** [gdh1995/vimium-c#446]
文档中有打开图片跟下载图片这两功能，但没有复制图片地址，我也试着用' LinkHints.activateCopyLinkUrl match="img" '，能识别图片但提示“没有发现地址”，我想应该是因为图片地址是存放在src属性中的原因。
是否能添加这个功能，或者可以给个比较简单的实现方式吗？

**Comment by gdh1995** [comment]
Duplicate of https://github.com/gdh1995/vimium-c/issues/399#issuecomment-927788170 .

In v1.92.4 a working around is
```
map Fa LinkHints.activateCopyLinkUrl match="img,video,audio" access="dataset.canonicalSrc,dataset.src,src"
```

**Comment by Wooolfboy** [comment]
可以复制，哈哈。
是我没仔细看issues，重复了，不好意思🙏

**Comment by gdh1995** [comment]
没，这个方法是我刚想起来的，我给那个问题之前回答的是“不行”……正在测另一个方法，应该比这个`match=img`要好写，等会更新。

**Comment by Wooolfboy** [comment]
感谢感谢，其实我感觉这个已经挺简洁的了，哈哈

**Comment by gdh1995** [comment]
这个兼容性不好，不支持背景图，也没用上一些识别“更清晰图”的特殊规则。 https://github.com/gdh1995/vimium-c/issues/399#issuecomment-927788170 更新了

**Comment by Wooolfboy** [comment]
再次感谢，用上了，确实能识别到背景图了🙏
