### ISSUE TITLE
Feature request: multiple <url-pattern>s per keyword in custom search engines.

### ISSUE THREAD

**Issue by PiperSuave** [gdh1995/vimium-c#448]
Hello,
I have an enhancement request for custom search engines: allow more than one < url-pattern> per keyword.  The use case for this is opening multiple websites with the same search input at one time.

Perhaps this could be accomplished by updating the current BNF from this:
< keywords > ":" < url-pattern> ["blank="< url-for-blank-query>] [ [parsing-prefix] "re="< parsing-regexp>] <...display-name>

To something similar to this:
< keywords> ":"  < url-pattern>    **< OPTIONAL-PART>***   <…display-name>
**< OPTIONAL-PART>** =  ["blank="<  url-for-blank-query>] [ [parsing-prefix] "re="<parsing-regexp>]  |  ["blank="< url-for-blank-query>] [ [parsing-prefix] "re="< parsing-regexp>] **“,”**

Basically, a comma separated list of URL patterns instead of just a singular URL pattern.

This would allow for custom search engines such as these:

_maps: https://www.google.com/maps?q=$s, https://www.bing.com/maps?q=$s, https://duckduckgo.com/?q=$s&ia=web&iaxm=about  All the maps_

A vomnibar entry of “maps London” would open three tabs (google, bing, duckduckgo) with the respective maps being displayed in each.

or:

_searchall: https://www.bing.com/search?q=$s blank=https://cn.bing.com/  ,``\``
               https://www.google.com/search?ie=utf-8&q=$s ``\``
               www.google.com re=/^(?:\.[a-z]{2,4})?\/search\b.*?[#&?]q=([^#&]*)/i ``\``
               blank=https://www.google.com ``\``
               bing and google search_

A vomnibar entry of “searchall volcano” would open two tabs (bing, google) with search results for volcano being displayed in each.

Finally, thanks for maintaining and extending this fantastic extension!

Best regards.

**Comment by gdh1995** [comment]
Looks convincing. Thanks for your advice.

**Comment by gdh1995** [comment]
Hello. Recently I think this is not as useful as I once though, since the only lacking feature is "to open multiple URLs by a search". So I added `vimium://urls` to do so, and you may try it on Vimium C v1.95 (today published on Firefox Add-Ons, but not on Chrome Web Store yet).

Example: `m: vimium://urls/b|g:$S Bing and Google`

Doc: https://github.com/gdh1995/vimium-c/wiki/Vimium-inner-URLs#function-urls

**Comment by PiperSuave** [comment]
Excellent!  I tested it under Firefox and it performs exactly as I had hoped it would.  Thanks very much for adding it into Vimium-C so quickly.
Best regards.

**Comment by zim0369** [comment]
GREAT!!
