### ISSUE TITLE
Scrolling before content has loaded will go too far

### ISSUE THREAD

**Issue by meluskyc** [gdh1995/vimium-c#45]
Using `scrollPageDown` before a page has fully loaded will scroll too far. 

![Vimium C Scroll Bug](https://media.giphy.com/media/XbJVRnWv6W2fZeqMJH/giphy.gif)

Hopefully this is possible to fix. Vimium does not have this issue currently.

**Comment by gdh1995** [comment]
Confirm. Thanks, and the solution is in development.

**Comment by gdh1995** [comment]
Vimium C v1.75.7 has been published on Chrome Web Store, and you may have a try.

**Comment by meluskyc** [comment]
Fixed. Thank you!
