### ISSUE TITLE
LinkHints.activate not working on Firefox 93 when some other extensions are enabled

### ISSUE THREAD

**Issue by rasfincher** [gdh1995/vimium-c#456]
**Describe the bug**

LinkHints.activate not working on Firefox 93.0 on MacOS Monterey

**To Reproduce**

Try to open LinkHints.activate (either using f or mapped to another key). No hints appear. As far as I can all other functionality appears to be working. 

**Browser, OS and Vimium C versions**

- Browser name: Firefox
- Browser version: 93.0
- Vimium C version: 1.93.0
- OS name and version: MacOS Monterey

**Comment by gdh1995** [comment]
Sorry but could you provide the names you tried turning off? Maybe I can fix the crashes in a few weeks.
