### ISSUE TITLE
联想官网的下载菜单不支持

### ISSUE THREAD

**Issue by dunkeng** [gdh1995/vimium-c#46]
https://pcsupport.lenovo.com/us/zh/products/laptops-and-netbooks/thinkpad-edge-laptops/thinkpad-e485-type-20ku/downloads

不好意思哈，从VIMIUM那边回复完了才想起应该来这边提个问题单。
额外请问两个问题，你会一直维护这个工具吗？并且同步VIMIUM那边的更新？

**Comment by gdh1995** [comment]
联想这个页面写的太随意了，没有任何提示来表示那几个下拉框是可以点击的，纯粹靠JavaSrript全局监听鼠标移动的事件来修改页面样式显示“下拉”部分的内容。没什么好办法来发现这类东西。

几年内会一直维护；大部分更新已经同步过来了，除了两三个功能我不想要或者没条件/没能力测试的之外。

**Comment by gdh1995** [comment]
没有问题的话可以close这个issue不？

**Comment by dunkeng** [comment]
都关了吧，反正这基本是你的个人项目啊
