### ISSUE TITLE
Customizing the opening fashion of Vomnibar

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#463]
To be aligned with `LinkHints` family

**Comment by gdh1995** [comment]
A duplicate of #429.

**Comment by OnceThenEver** [comment]
But   ⌃⇧⏎   still jump to tab when opening the history tab, is that what you intended?

**Comment by gdh1995** [comment]
In the master version of code, `<a-c-s-enter>` will open normal items in a new background tab. I'll fix its behavior on "recently closed session items"

**Comment by OnceThenEver** [comment]
By checking `master/i18n/params.json`, I found that `LinkHints.activateOpenVomnibar` doesn't support `clickLike`, but it also triggers vomnibar.

**Comment by OnceThenEver** [comment]
And the perfect solution for this issue:
1. Use `Vomnibar.activate*` commands that **don't** end with `InNewTab`, with parameter `clickLike` added.
2. Use commands like `mapKey <enter:o> <c-s-enter>` to reorder the original mappings, which are given in the first picture in this issue.

**Comment by gdh1995** [comment]
I'll add `then: string | dict` to `LinkHints.activateSelect` and `LinkHints.activateOpenVomnibar`, to specify whatever options you need when VisualMode / Vomnibar gets activated.

**Comment by OnceThenEver** [comment]
That would be great.

**Comment by gdh1995** [comment]
Hello, Vimium C v1.96.1 has been released on Firefox Add-Ons, and you may take a try. Chrome / Edge versions may still need a few days.

**Comment by OnceThenEver** [comment]
Issue solved for Chrome 1.96.0
