### ISSUE TITLE
所有新标签页都是vimiumc的设置页面

### ISSUE THREAD

**Issue by dunkeng** [gdh1995/vimium-c#47]
我找不到解决办法，浏览器是百分浏览器，最新版

**Comment by gdh1995** [comment]
修改Vimium C设置页面的New Tab URL一栏

**Comment by dunkeng** [comment]
> 修改Vimium C设置页面的New Tab URL一栏
> 
> > all newly created tabs are Vimium C's Options pages
> > I can not find a solution. The browser is the latest version of Cent Browser.
> 
> Modify the "New Tab URL" on Vimium C Options page to what URL you want.

关不完美，我取得的地址是：
chrome://newtab/
修改后，URL会自动刷新为原来的，新页面是原来的简化版本，不好看，但功能存在
如图：
![1](https://user-images.githubusercontent.com/22165870/59170628-1b2d5880-8b72-11e9-9d0c-ae4d25753da6.png)
![4](https://user-images.githubusercontent.com/22165870/59170629-1bc5ef00-8b72-11e9-806f-a60c62b218fa.png)
![3](https://user-images.githubusercontent.com/22165870/59170630-1bc5ef00-8b72-11e9-9afa-b5a36ee3f85f.png)
![2](https://user-images.githubusercontent.com/22165870/59170631-1bc5ef00-8b72-11e9-83df-19550338831f.png)

**Comment by gdh1995** [comment]
从应用商店安装的Vimium C的话，没有直接修的办法。间接的办法是：

1, 从https://github.com/gdh1995/vimium-c/releases下载Vimium C的安装包，比如vimium-c_1.75.6_chrome.crx
2. 解压到一个空文件夹中，修改manifest.json，删除其中`"newtab": "pages/newtab.html"`这一行
3. 从百分浏览器里打开chrome://extensions/，勾选右上角“开发者模式”，加载存放Vimium C的文件夹
4. 就能基本正常地用了

或者你有能力从源码编译的话，下载源码后把types/build/index.d.ts的`MayOverrideNewTab`为`0`，然后执行`npm install && npm run chrome`，会编译到dist文件夹中。

不过chrome://newtab和chrome-search://local-ntp/local-ntp.html都是浏览器内置页面，Vimium C不能在这些页面上运行。

**Comment by dunkeng** [comment]
最好用上了gdh1995全家桶了，安逸了“微度新标签页修改版”

**Comment by gdh1995** [comment]
哈，谢谢。

之前也有反馈newtab的问题，也考虑过直接去掉，或者另外发布一个不绑定newtab的版本。但Vimium C目前用户就一两千人吧，感觉再两个版本分流的话，用户量看起来就更少得可怜了。。。直接去掉的话我自己又很需要这个功能。

今天有了个新主意来把这个绑定newtab的功能独立出去，我这个月内实现看看效果吧，方便的话也许可以拆成Vimium C + New Tab Replacer for Vimium C。

**Comment by dunkeng** [comment]
按你自己的节奏来就可以了，这些东西首先要自己用的爽，用的顺手，才会投入更多力气去做的更实用。不必要太过关注客户需求的，毕竟你还不是商业软件。我现在也是想从百分迁移到EDGE去，刚好可以多试试其他的工具，虽然集成度肯定没有百分好

**Comment by gdh1995** [comment]
Edge对写扩展程序用的WebExtension API支持的不很全，Vimium C目前可以从源码编译出支持它的版本（代码会多很多不必要的trick），但要改types/build/index.d.ts 。

新的测试版Edge (https://www.microsoftedgeinsider.com/)倒是Chromium内核的，能直接完美加载Vimium C。

**Comment by whwnow** [comment]
我也发现这个问题了，`ctrl + t` 打开的是设置页面。我之前的新页面是被其他插件接管的，这个就没法接受了。从Vimium那边转过来是因为在那边提了个搜索的需求，被这边实现了，效率还挺高。希望能解决一下新标签这部分，不明白为什么把新标签强制成设置页面，这是什么逻辑？

**Comment by gdh1995** [comment]
1. 接管是为了阻止浏览器创建新标签页后把焦点放到浏览器地址栏，影响vimium c快捷键。
2. 这个“阻止”功能在最新几版里可以关闭，在选项页面“advanced options”里的focus ****里。
3. 可以修改指向其它新标签页的，刚安装的话，Ctrl+T打开的页面有一行淡黄色背景的就是，修改它就行。修改方式在它右侧的“How to ...”里有介绍

**Comment by whwnow** [comment]
好的，期待新版本更新。
