### ISSUE TITLE
Best way to learn Vimium-C?

### ISSUE THREAD

**Issue by random-un** [gdh1995/vimium-c#470]
I very recently moved to Vimium-C from Vimium, and I'm extremely impressed by how much additional functionality is available on this variant. I made the switch because I really like the [LinkHints.activateModeToSelect](https://github.com/gdh1995/vimium-c/issues/3#issuecomment-695320311) command, but now realize there's so much more.

One challenge: many of the additional commands, modifiers, and concepts are unfamiliar or unknown to me, and I'm not sure of the best way to discover and learn about them. In the example of `LinkHints.activateModeToSelect`, I happened to notice the `caret=true` option was available thanks to a comment in the issue thread, but could have easily missed this detail.

I've done some quick searches in the wiki and issues -- are those the recommended resources? More broadly, do you have a suggestion on best ways to become a Vimium-C power user?

Thank you!

**Comment by sisrfeng** [comment]
I spend more than 15 minutes to find how to use regex in search. After some trials, I find `/\rYOUR_STRING` works.

I search this using google: `"search"  "regex" site:github.com/gdh1995/vimium-c`
![image](https://user-images.githubusercontent.com/53520949/152647839-f0e524a7-f9c0-48cc-9a8e-7565fd975763.png)

I think this repo is not quite well documented. (I can not find how to use regex in `vimium`  too )
Would you mind giving some advice for searching something in this repo?

**Comment by gdh1995** [comment]
Um,
* this project does lack documents
* as for `Vimium`, it has a simple explanation: https://github.com/philc/vimium/wiki/Find-Mode#case-sensitivity-and-regexps
