### ISSUE TITLE
Suggestion: It would be nice to add another command do the same as captureTab but save it to clipboard

### ISSUE THREAD

**Issue by miguel550** [gdh1995/vimium-c#473]
`captureTabToClipboard`

**How should a feature do**
This should do the same as `captureTab` but instead of saving the image into a file it would save it to clipboard. Must of the time I only need the image to be in my clipboard to send it to another application.

**Browser and OS**

- Browser name:  Chrome 95.0.4638.54 (Official Build) (x86_64)
- OS name: macOS Version 10.15.7 (Build 19H1217)
- Vimium-C version: 1.94.0

**Comment by gdh1995** [comment]
Hello, Vimium C v1.96.1 has been released on Firefox Add-Ons, and you may take a try.

The usage is ``` map xxx captureTab copy ```, which only works on Firefox.

**Comment by gdh1995** [comment]
Hello, now Vimium C v1.99.0 is able to copy captured image as PNG image into system clipboard (the old versions copy it as an HTML section, which is not compatible with some software), and it works on Chrome, too.
