### ISSUE TITLE
visitPreviousTab switch between tabs in different windows?

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#476]
Unlike `visitPreviousTab acrossWindows`, which it more suitably named `visitPreviousWindow`, I hope the tab stack to stock tabs from different windows, so I can either switch to the tab in the same window or to the tab in different window.

**Comment by gdh1995** [comment]
So, do you want `map xxx visitPreviousTab acrossWindows onlyActive`?

**Comment by OnceThenEver** [comment]
By test, `onlyActive` doesn't change `acrossWindows`'s behavior.

**Comment by gdh1995** [comment]
`onlyActive` is used when you give a count like 2 / 3 / ...

**Comment by OnceThenEver** [comment]
Assume the following situations:
- Initially in Window1's Tab1, now switch to Window1's Tab2
- Initially in Window1's Tab1, now switch to Window2's Tab1

In both cases, I want to return to Window1's Tab1 with a single keystroke.

**Comment by gdh1995** [comment]
Could we use Chinese to describe this issue? 能用中文说吗？

最好假设同一个场景，你这个两步都是1/1，是两个问题吧？

**Comment by gdh1995** [comment]
What about only adding `acrossWindows` and removing `onlyActive` ?

**Comment by OnceThenEver** [comment]
As the first comment said, it doesn't work too.

**Comment by gdh1995** [comment]
Sorry I didn't understand what do you really want. Any detailed description?

**Comment by OnceThenEver** [comment]
![截屏2021-11-02 17 10 25](https://user-images.githubusercontent.com/66708845/139818191-2dd964f5-b680-44cf-842e-0fc029950a5e.png)

**Comment by OnceThenEver** [comment]
First stack: without `acrossWindows`
Second stack: with `across Windows`
Third stack: my expectation, i.e. mixing 1st and 2nd stack up
![截屏2021-11-02 17 33 36](https://user-images.githubusercontent.com/66708845/139821691-98e766e2-d457-4746-82a4-22e1f3a26dd2.png)

**Comment by gdh1995** [comment]
With `map xxx visitPreviousTab acrossWindows`, `3xxx` should be able to go from `W1 T1` to `W1 T2`.

**Comment by OnceThenEver** [comment]
Ah, I just figured out the true problem:
I switched too fast that Chrome didn't push the midway tabs into stack. What a farce.

**Comment by gdh1995** [comment]
Um, it's a feature of Vimium C (just like what the original [Vimium](https://github.com/philc/vimium) does), that if a tab is activated and then inactivated in less than 666 ms, then it won't be added into the recency stack.
