### ISSUE TITLE
When focus in input field, <a-p>-like commands broke

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#477]
So `map <a-p> autoOpen` can't search field's text.

**Comment by gdh1995** [comment]
Please see https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box

**Comment by OnceThenEver** [comment]
But this mapping works just in last version.

**Comment by gdh1995** [comment]
What's your platform when "it works", os, browser and Vimium C version?

**Comment by OnceThenEver** [comment]
I use Chrome in macOS 12, and mac's default character of ⌥p is "π".
`map <a-p:i> autoOpen` works, but I have to additionally define `map <a-p> autoOpen` to search clipboard.
Does it relates to this [bug](url:https://github.com/gdh1995/vimium-c/issues/325?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDE3OTIxMDI4OTM6NjY3MDg4NDU%3D#issuecomment-954472931)?

**Comment by gdh1995** [comment]
Not related. Both Normal mode and Insert mode support Ctrl/Alt well.

`<a-p>` is treated as a plain key, so Insert mode won't consume it. In fact, the mode should only consume keys with `F1 ~ F12` or ending with `:i>`.

**Comment by OnceThenEver** [comment]
I'll get used to the change.

**Comment by gdh1995** [comment]
Um this logic has kept for almost a year, and before it a plain Insert mode would refuse all keys not with `F1 ~ F12`. So I'm not sure why you found that `<a-p>` worked in Insert mode.

**Comment by OnceThenEver** [comment]
`map <a-p> autoOpen` have always been my shortcut to search some fraction of texts in the input box.
After all, chars of ⌥(_letter_) are rarely used in mac.
