### ISSUE TITLE
Make vimiumC work while the page is loading.

### ISSUE THREAD

**Issue by zim0369** [gdh1995/vimium-c#478]
vimiumC just like vimium doesn't work while the page is loading. If it works then navigation would be pretty faster. 

I have a high speed connection but some websites that are badly written take time to load.

**Comment by gdh1995** [comment]
Please try https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box#shortcuts .

**Comment by zim0369** [comment]
It worked like a charm!

Thank you so much!

**Comment by mortezadadgar** [comment]
> Please try https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box#shortcuts .

can this be done for firefox as well?

**Comment by gdh1995** [comment]
@mortezadadgar  Global shortcuts are on "Manage Shortcuts" in "Tools Menu" of `about:addons` :

![image](https://user-images.githubusercontent.com/5547703/142810528-66b8305f-e2dc-4b1d-92a5-2cff01e1acc1.png)
