### ISSUE TITLE
Provide a list of available commands in options tab.

### ISSUE THREAD

**Issue by zim0369** [gdh1995/vimium-c#479]
when trying to create new mappings I'm unable to figure out what the commands are. I have to search the web and still fail to find the command I need. Why not create a link in the options page that redirects to a list of all available commands?

I AM NOT REFERRING TO THE COMMANDS THAT ARE ALREADY AVAILABLE. I WANT TO SEE A LIST OF MAPPINGS THAT I CAN CREATE. 

Right now I want to map { and } to do J and K.

**Comment by gdh1995** [comment]
If press `?` on Vimium C Options, then you can see a whole list of all available commands (and bound keys for some of them).
* on other pages, `?` will only show a list of all mapped commands.
* the default available mappings are: https://github.com/gdh1995/vimium-c/blob/master/background/key_mappings.ts#L498-L524

Here's a list of command names: https://github.com/gdh1995/vimium-c/wiki/List-of-all-commands (without description, though).

If you wonder what's the syntax of custom key mappings, here're:
* `mapKey`: https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout
* `env` and `runKey expect`: https://github.com/gdh1995/vimium-c/wiki/Map-a-key-to-different-commands-on-different-websites
* `run` key trees and `$then` / `$else`: https://github.com/gdh1995/vimium-c/wiki/Auto-run-a-tree-of-commands
