### ISSUE TITLE
How to add color or change background color on match after  the search with / ??

### ISSUE THREAD

**Issue by Goku-San** [gdh1995/vimium-c#481]
Hello, just wanted to say nice extension.

Like the question states... This is similar to #271 

The problem:
I use firefox with dark mode on. When I search for a word with ``/`` and hit <kbd>Enter</kbd> the **background color** is ``#ff9632`` and remains the same after every next <kbd>n</kbd> key press,
while the letters are unreadable because the **color** is ``#ffffff``.
Also the **color** sometimes changes to **green** on first <kbd>Enter</kbd> hit.

What I tried
```
/* #find */ 
::selection { color: #000000 !important; }

/* #find:host */ 
::selection {color: #000000 !important; }

/* :host */ 
::selection {color: #000000 !important; }

/* #ui */ 
::selection {color: #000000 !important; }
```
Even tried to hard code it in the extension, but firefox disabled it afterwards, so I had to reinstall.

Can you hard code color white so ``:selection`` or is there a way for me to achieve that through settings ??

**EDIT** Current Firefox version 94.0

**Comment by gdh1995** [comment]
This should work:

``` css
/* #find:host */
::selection {color: #000000 !important; }
```

During my tests, it works on Vimium C Options page, MS Edge 95 and Win 10. Whenever you change selection color or background color, you need to change the query on Find HUD to tell your browser to redraw the selection area.

**Comment by gdh1995** [comment]
Um, there's a small issue about live preview for `#find:host` section - if there's no such a section, and you add it and want to see effects, then you need to exit FindMode and re-enter it.

**Comment by Goku-San** [comment]
> you need to change the query on Find HUD to tell your browser to redraw the selection area.

How do I do this ??

After first match I press <kbd>Esc</kbd> and again <kbd>n</kbd> nothing is changed. Same colors...

**Comment by gdh1995** [comment]
Um, up to now `#find:host` is not used by `performFind`, but only `enterFindMode`.

**Comment by gdh1995** [comment]
Then I'll fix it.

**Comment by Goku-San** [comment]
When I open **shadow-root** the first line is 
```html
<style type="text/css">::selection { background: #ff9632 !important; }</style>
```
The **color** is never added , and I can't find the color that I have added... Now I am trying to some how change the colors to see if it reflects in the UI somehow.
It would be nice if you could add some class to it or something so it can be targeted easily.

**Comment by gdh1995** [comment]
If you have: entered `FindMode` and searched for some words, and the words have matched at least once, then you'll see `#find:host` string (along with some pre-defined rules) as the last child element of the shadow root. If you can't find the new node, then maybe there's another bug.

I think there should be another section, maybe named `#find:selection` to support adding rules into the first `<style>`.

**Comment by gdh1995** [comment]
``` html
<div>
  <!-- shadow root -->
  <style type="text/css">::selection { background: #ff9632 !important; }</style>
  <style type="text/css">html, body, * { user-select: auto; } ::selection { color: red !important }</style></div>
```

**Comment by Goku-San** [comment]
Nope I don't have that. Tried in google-chrome (current version 95.0.4638.69 ) as well same thing.

Just to be clear after every change I restart the browser to be on the safe side.

**Comment by gdh1995** [comment]
What's your "custom CSS" (the whole text)? What're your Vimium C version and OS name?

**Comment by Goku-San** [comment]
Custom Css
```css
/* #find:host */
::selection { color: #000000 !important; }
```
**Vimium C 1.94.0, Firefox 94, Linux.**

OS Manjaro XFCE

**Comment by Goku-San** [comment]
This is the workflow
press <kbd>/</kbd> search for the word, the first match is background: orange, color: black
press <kbd>Enter</kbd> the search box closes the matched word changes background: orange, color: white
press <kbd>n</kbd>  go to next match background: orange, color: white

**Comment by gdh1995** [comment]
Um, here's my test on Windows 10. I'll test on Ubuntu 20.04 in a while.

![image](https://user-images.githubusercontent.com/5547703/140549846-058cfe30-dbae-4315-981e-e76dad0cdc45.png)

**Comment by gdh1995** [comment]
Oh. Please not press `enter` -  `FindMode` should be kept active in order to apply `#find:host` styles.

**Comment by Goku-San** [comment]
How do I traverse then and keep the styles ?

**Comment by gdh1995** [comment]
What do you mean by "keep" and "the styles"? If you want to edit the first `<style>`, then you need to wait for a future version of Vimium C.

**Comment by Goku-San** [comment]
Am If I don't press <kbd>Enter</kbd> how will I traverse to the next match ?

> What do you mean by "keep" and "the styles"?

I mean I would like to traverse to next match while **background is orange and color is black**.

**Comment by gdh1995** [comment]
When Find HUD is focused, you may use `<c-j>` and `<c-k>` to go to a next / previous match.

**Comment by Goku-San** [comment]
> you may use ``<c-j>`` and ``<c-k>`` to go to a next / previous match.

Thanks, this works. But its easier with <kbd>n</kbd> and <kbd>N</kbd>

> If you want to edit the first <style>, then you need to wait for a future version of Vimium C.

I really hope you implement this. I look forward to the next version. 

Thanks for Your time. 
 Wish You all the best.
Cheers...

**Comment by gdh1995** [comment]
Hello, on Firefox Add-Ons Vimium C v1.95.0 has been released, and then you may use `#find:selection` to change the colors.

**Comment by Goku-San** [comment]
Thanks... it works great...

Cheers...
