### ISSUE TITLE
map space-space to pause/play yt videos.

### ISSUE THREAD

**Issue by zim0369** [gdh1995/vimium-c#483]
I have mapped all of the commands that started with shift to start with space. 

`so space-f -> open link in new tab`, etc.

This is much more convenient for me but it creates a small problem. I can't use space to pause videos on yt, rather have to go into insert mode press k and esc.

I tried using:
`map <space><space> enterInsertMode <space> reset` but combining commands doesn't seem to be supported.

**Comment by zim0369** [comment]
```
map { moveTabLeft
map } moveTabRight

map ( previousTab
map ) nextTab

map <space>l goForward
map <space>h goBack

map <space>f restoreTab
map <space>g scrollToBottom
map <space>f moveTabToNextWindow
map <space>p openCopiedUrlInNewTab
map <space>o Vomnibar.activateInNewTab
map <space>f LinkHints.activateOpenInNewTab

unmap <<
unmap >>
```
These are all my mappings in a non-broken state.

**Comment by gdh1995** [comment]
If you want to use `<space>` to exit `Insert Mode`, then you may write:
```
map <space><space> enterInsertMode key="<space>"
```

**Comment by zim0369** [comment]
I'm sorry for bad explanation but I want to be able to pause the video in normal mode by pressing space key twice since I've lost the ability to pause it as I've almost turned the space key into a leader key. 

Is there a way in which I can send space key to youtube?
`map <space><space> key="<space>"` doesn't work.

**Comment by gdh1995** [comment]
The basic syntax of `map` can be seen in https://github.com/philc/vimium#custom-key-mappings , and what Vimium C adds are new commands and much more command options.

For this issue, you should use `dispatchEvent`:
```
map <v-de> dispatchEvent
run <space><space> #key=%20%2C32%2CSpace+(de)-de
# the line of "run" can be replaced by
map <space><space> runKey keys="+(de)-de" o.key="\u0020,32,Space"
```

**Comment by zim0369** [comment]
That worked perfectly but it seems way harder to understand.

**Comment by gdh1995** [comment]
Usages of `run` (an alias of `map *** runKey`) re in https://github.com/gdh1995/vimium-c/wiki/Auto-run-a-tree-of-commands. 

`dispatchEvent` supports `key="Key,keyCode[,Code]"` in which a default `Code` is its `Key` value. And `-de` will be converted into "running `dispatchEvent` by `-1` times", and then `dispatchEvent` will auto dispatch a keyup event. So `(de)-de` means a pair of `keydown & keyup` events.

**Comment by Bellavene** [comment]
> map <v-de> dispatchEvent
> run <space><space> #key=%20%2C32%2CSpace+(de)-de
> # the line of "run" can be replaced by
> map <space><space> runKey keys="+(de)-de" o.key="\u0020,32,Space"

Doesn't work. I get only the second key press, the ordinary space key doesn't trigger. Like, the key code is not correct.

**Comment by gdh1995** [comment]
@Bellavene I just tested Youtube and it does work now.

The 4th line is another version of the 2nd line, and it should be removed when you add the block into your key mappings.

The mapping itself is just to simulate a "`Space`" key on a page, while the `<space><space>` can be replaced by any other key if you like. So I'm not sure what you meant by `the ordinary space`.

The `keyCode` of `Space` is `32` on my Chrome 98 for Windows.

If you want to pass a real `Space` key, instead of simulating one, you may use the command `passNextKey`:
```
map xxx passNextKey
```

Then `xxx<space>` will pass a real space to page, even when `<space>` has been mapped inside Vimium C. The command will auto exit after passing keys for `count` times, so `2xxx<space><space>` will pass two `<space>` keys.

**Comment by gdh1995** [comment]
@Bellavene Um, I did more tests, and it seems you have to click the video panel before pressing `<space><space>`. It's a matter about where the keyboard focus is.

If a page was playing AD, I could use `<space><space>` to pause it directly, but after I clicked the `Skip AD` button and the video started, `<space><space>` would fail.

When I used `LinkHints` to click the video area, `<space><space>` worked again.

Here's a easy way to fix this issue: you just need to tell `dispatchEvent` to prefer `<video>` elements:
```
map <v-de> dispatchEvent
run <space><space> #key=%20%2C32%2CSpace&match=video+(de)-de
```

**Comment by Bellavene** [comment]
Still, something doesn't work quite right.
I want to trigger on first press LinkHints.activate, one the second press – regular space key.

**Comment by gdh1995** [comment]
Um, you can not do so by only using plain `map` rules. In Vimium C's key mappings, a key sequence should never be a prefix of another key sequence. In what you want, Vimium C can not decide whether to activate LinkHints or wait a second `<space>`.

But there is a "near" way: enter `LinkHints` and then trigger commands when LinkHints is showing:
```
map <space> LinkHints.activate
mapKey <s-space:l> <f666>
run <s-space> LinkHints.unhoverLast#r&u=false+(space1)-space1
map <v-space1> dispatchEvent key="\u0020,32,Space" \
  direct="sel,f,h,a,a,em" match="div"
```

Then a first `<space>` shows LinkHints, and a following `Shift+Space` will exit LinkHints (if it's showing) and simulate a `Space` (keydown+keyup) event.

**Comment by Bellavene** [comment]
Thank you! Last one works!
