### ISSUE TITLE
input for custom search engines without query strings should not be URL encoded

### ISSUE THREAD

**Issue by wis** [gdh1995/vimium-c#49]
how to reproduce:
1. add this to list of custom search engines in your vimium c options: `ghu: https://github.com/%s GitHub @user/org`
2. go to https://github.com/gdh1995/vimium-c
3. type ghu gdh1995/vimium-c in the vomnibar and press return

what should happen: go to
`https://github.com/`**gdh1995/vimium-c** (input that replaces `%s` is not URL encoded)
not 
`https://github.com/`gdh1995 **%2F** vimium-c  (URL encoded)

how to fix:
if the custom search engine url has the `%s` after a the query string of the url, it should be url encoded, if it does not have a query string/s it should not.
for example:
if the custom search engine url was:
`https://github.com/user?u=%s` %s should be url encoded
but for custom search engine urls that don't have a qwery string, like:
`https://github.com/%s` %s should _not_ be url encoded.

vimium c version I'm using: 1.74

**Comment by gdh1995** [comment]
Please use `$S` or `%S` (the UPPER CASE of `S` character) to replace the `%s`.

**Comment by wis** [comment]
seems to work, thanks
by the way, is it documented here or in the options page?

**Comment by gdh1995** [comment]
![image](https://user-images.githubusercontent.com/5547703/59575366-cba8d880-90ed-11e9-84f7-93893d9f86fa.png)

Advanced syntax details are on https://github.com/gdh1995/vimium-c/wiki/Search-engine-rules#url-pattern .
