### ISSUE TITLE
【New Function】Search current page's all links' URL

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#491]

**Comment by gdh1995** [comment]
You may enable `Use the link's name and characters for link-hint filtering` (aka `使用链接和按钮的文字来在提示模式列出的对象中筛选`): https://github.com/gdh1995/vimium-c/wiki/Using-Link-Hints#filtered-hints

**Comment by gdh1995** [comment]
Or use mappings like `map Ff LinkHints.activate useFilter` and `map Fg LinkHints.activate useFilter=false` to enable different modes by keys.

**Comment by OnceThenEver** [comment]
What about searching URLs?

**Comment by gdh1995** [comment]
No such a feature.

**Comment by OnceThenEver** [comment]
Please consider it.

**Comment by gdh1995** [comment]
No, I won't implement it, because:
1. in most websites most URLs are not visible on pages
2. most URLs contain too little information to filter easily.

**Comment by OnceThenEver** [comment]
Alright
