### ISSUE TITLE
能否增加一个设置项，在进入全屏看视频的时候自动暂停vimium-c

### ISSUE THREAD

**Issue by KKFantasy** [gdh1995/vimium-c#493]
我同时在使用这个脚本[网页播放器增强脚本](https://github.com/xxxily/h5player)，在看视频的时候vimium-c会和视频控制快捷键冲突，但是除了常用的视频网站可以排除之外，有时也会在一些类似知乎之类的非视频网站看视频，每次都需要手动禁用有点不太方便。

**Comment by gdh1995** [comment]
要是你是用 `LinkHints` 去点击网页里的全屏按钮的话，可以做到全屏时自动进入 `InsertMode`:
```
env fs fullscreen=true
map f LinkHints.activate $then="<v-on_fs>"
map <v-on_fs> runKey expect="fs:enterInsertMode" keys="blank"
```

然后按一次 `Esc` 退出全屏、按第二次 `Esc` 退出 `InsertMode`。

自动按全屏状态修改 Vimium C 状态的功能不好做，暂时没想到特别完美的办法，我估计今年内不会做这个。

**Comment by KKFantasy** [comment]
https://github.com/xxxily/h5player/blob/11d72ecb97f2e093252cf103f0739e97d799fe0e/src/libs/FullScreen/index.js#L111
https://developer.mozilla.org/zh-CN/docs/Web/API/Element/requestFullScreen
谢谢，不过试了下好像不行，看起来脚本好像是通过上边这个api来全屏的。

**Comment by gdh1995** [comment]
我是想问，你是怎么触发“进入全屏”这个命令的？用鼠标点某个按钮，还是用 Vimium C 的 LinkHints 命令去模拟点击某个按钮，还是用键盘按回车？

如果是第二种“用 Vimium C 的 LinkHints 命令去模拟点击”的话，就可以用上边三行命令，否则的话目前没办法、需要另外设计新功能。

**Comment by KKFantasy** [comment]
好吧，是

**Comment by gdh1995** [comment]
这样吧，添加
```
run <enter> #key=Enter%2C13+(dispatchEvent)(-dispatchEvent)+enterInsertMode#hideHUD&key
```

这样敲一次回车，Vimium C 会向页面发送一次回车，并且进入暂停模式；进入暂停模式后按 Escape 可以退出暂停。

有个小问题是，如果处于全屏状态，按 Escape 会先退出全屏，再按一次才会退出暂停。

也可以这么写：
```
run <enter> #key=Enter%2C13+(dispatchEvent)(-dispatchEvent)+enterInsertMode#hideHUD&key=<enter>
```

这样按 Escape 不能退出暂停，只会退出全屏；按第二次回车才可以退出暂停了。

**Comment by KKFantasy** [comment]
测试正常，非常感谢

**Comment by gdh1995** [comment]
既然凑合能用，就不打算添加`根据页面的“当前焦点元素”变化时执行指定操作`这个功能的了
