### ISSUE TITLE
Visually select and/or yank paragraph

### ISSUE THREAD

**Issue by mjfneto** [gdh1995/vimium-c#494]
# `vap` and/or `yp`

When a user has done such steps:

1. Enter visual mode
2. Press `a` ("around"), followed by `p` ("current paragraph")

OR

1. Enter visual or caret mode (either through Find or mouse click)
2. Hit `y` ("yank"), followed by `p` ("current paragraph")

## Notes

This is a vim [feature](https://vimhelp.org/motion.txt.html#ap).

**Comment by gdh1995** [comment]
Vimium C and Vimium use `{` and `}` to extend selection by "paragraph", but the browser support of `paragraph` is not as good as I once expected.

So you may use `(o)y` to select a whole `sentence` and then yank.

**Comment by gdh1995** [comment]
Update: I find a way to select a paragraph on Chrome, and then I'll implement `ap` in a next version of Vimium C.

Old: 
> Vimium C and Vimium use `{` and `}` to extend selection by a step of "paragraph", but not `paragraphBoundary`.

**Comment by gdh1995** [comment]
As for `yp`, it won't be added, since `y` has been assigned to the "copyAndExit" command.

**Comment by gdh1995** [comment]
Hello, Vimium C v1.96.1 has been released on Firefox Add-Ons, and you may take a try. Chrome / Edge versions may still need a few days.

It adds support of `ap`.

**Comment by mjfneto** [comment]
Nice! I will.

**Comment by gdh1995** [comment]
Does it work now?

**Comment by mjfneto** [comment]
I don't think so. I enter Visual Mode `v`, right? Then I press `a` followed by `p`? It isn't selecting the paragraph the cursor is in.

**Comment by gdh1995** [comment]
After `v`, was there a HUD of `Visual Mode` at the bottom right corner? I can use `v` and `ap` on this page:
* select `Then I press ...`
* press `v` and see a HUD of `Visual Mode`
* press `a` and `p` (keyboard layout is English, and no Input Method Editor) to select the line

**Comment by mjfneto** [comment]
- I click somewhere in a paragraph to select
- I press `v` (a HUD of `Visual Mode` appears)
- then I press `a`, followed by `p`
- But the it isn't selecting the paragraph

I'm using Firefox now.

**Comment by mjfneto** [comment]
It seems to be working on Edge though. I've just tested it on a Wikipedia page and it selected the paragraph just right 😉

**Comment by gdh1995** [comment]
As said in https://developer.mozilla.org/en-US/docs/Web/API/Selection/modify, Firefox doesn't support `paragraph` or `paragraphboundary`, so Vimium C broke in your tests.

I'll update code to use `line` as a fallback.

**Comment by gdh1995** [comment]
hello, v1.98.0 has been released, and you may take a try. Now it will use `line` as a fallback on Firefox

But this version has a known bug that keys like  `ae`/`aw` don't work, which will be fixed in a next version.

**Comment by gdh1995** [comment]
Hello, v1.99.0 has been available on Firefox (Chrome and Edge versions are waiting for review), and on Firefox `ae` and `aw` should work to some degree.
