### ISSUE TITLE
Modal editing inside vomnibar.

### ISSUE THREAD

**Issue by zim0369** [gdh1995/vimium-c#499]
There is a plugin for neovim called telescope which has vim built-in also in it's search bar and getting into normal mode to navigate through the list with j and k. It'd be cool to have this feature and also more ergonomic.

It doesn't have to be a fully-fledged vi emulator tho.

**Comment by gdh1995** [comment]
* `Ctrl+J/K` to go to a next/previous suggestion item
* like a default Bash shell, use `Alt+B/F` to move caret left/right by a word, and use `Alt+D` to delete a word.
* `Shift+ArrowDown` and `Shift+ArrorUp` to pageDown / pageUp.

**Comment by zim0369** [comment]
> * `Ctrl+J/K` to go to a next/previous suggestion item
> * like a default Bash shell, use `Alt+B/F` to move caret left/right by a word, and use `Alt+D` to delete a word.
> * `Shift+ArrowDown` and `Shift+ArrorUp` to pageDown / pageUp.

Wow! I thought that'd conflict with the browsers default shortcuts but it works great!! thank you!
