### ISSUE TITLE
Enable jump to page in PDF Viewer for Vimium C

### ISSUE THREAD

**Issue by hacker-DOM** [gdh1995/vimium-c#500]
Hi again! it would be great if there was some easy way to jump to page X in PDF Viewer for Vimium C. Here's an example:

- Esc
- 3 pressed twice
- g

Jumps to page 33. That would be 🙏🙏

**Comment by gdh1995** [comment]
Hello, Vimium C v1.96.1 has been released on Firefox Add-Ons, and you may use `openUrl url="javascript:"` on PDF Viewer for Vimium C. For example,
```
map gg runKey expect="pdf:ggp" keys="gg0"
map <v-gg0> scrollToTop
map <v-ggp> openUrl mask \
  url="javascript:let%20a=PDFViewerApplication;a.page=Math.max(1,Math.min(a.page+$c,a.pagesCount))"
```

`$c` in this means command count。

**Comment by hacker-DOM** [comment]
Hi, I was wondering

- Does the PDF extension have documentation? I would be interested to see its functionalities :-)
- Can the PDF extension perform jump-back
- I tried copy-pasting the above code into my keybindings, but I get "No environment has been defined" :-(

**Comment by gdh1995** [comment]
1. The extension is forked and modified from https://github.com/mozilla/pdf.js . I just added Vimium C injection into it.
2. You may use `Marks.activate` to remember a position and then jump back.
3. Sorry the list was incomplete. You also need a `env` named `pdf`, like:
```
env pdf host=:chrome-extension://nacjakoppgmdcpemlfnfegmlhipddanj/
```
