### ISSUE TITLE
Changes to "Keys" under "Excluded URLs and keys" not possible to save in Firefox

### ISSUE THREAD

**Issue by falolaf** [gdh1995/vimium-c#502]
Changes to "Keys" under "Excluded URLs and keys" not possible to save in Firefox. I.e., "No Changes" button does not change to "Save Changes" and `<c-enter>` does not do anything.

1. Do changes to "Keys" for an entry under "Excluded URLs and keys"
2. Not possible to save

A workaround is to do changes to "Keys", then do changes to "Patterns". Now it is possible to save all the changes. Though, changes done to "Keys" are saved but not sorted.

- Browser name: Firefox
- Browser version:  94.0.1
- Vimium C version: 1.95.0
- OS name and version: Windows_NT 10.0 18363

**Comment by gdh1995** [comment]
Confirmed

**Comment by gdh1995** [comment]
Hello, Vimium C v1.96.0 has been released on Firefox Add-Ons, and you may try it again.

**Comment by falolaf** [comment]
Yes, this seems to work now! Thank you!
