### ISSUE TITLE
dark mode is too dark

### ISSUE THREAD

**Issue by nobodyatandnothing** [gdh1995/vimium-c#506]
**What command or commands**

styles="dark"
gn

**How should a feature do**

lower contrast is easier on the eyes

**Comment by gdh1995** [comment]
You may write CSS code to change UI elements of Vimium C: https://github.com/gdh1995/vimium-c/wiki/Style-the-UI-of-Vimium-C-using-Custom-CSS

**Comment by zim0369** [comment]
> **What command or commands**
> 
> styles="dark" gn
> 
> **How should a feature do**
> 
> lower contrast is easier on the eyes

https://github.com/zim0369/vimiumC.css
