### ISSUE TITLE
Repeat last command

### ISSUE THREAD

**Issue by mjfneto** [gdh1995/vimium-c#510]
Add a repeat last command feature.

The other day I was going through the contents of a carousel element contents and realized that I had to press `f`, followed by the respective linkHint in order to move to the next item in the list. Considering the need to not repeat ourselves, is there a repeat last command feature? 

In Vim editor, the `.` ([dot](https://stackoverflow.com/questions/7325052/why-the-dot-command-is-so-useful-in-vim)) repeats the last editing action. If there's no overwrite, maybe this could work as a keybinding.

**Comment by gdh1995** [comment]
```
map . LinkHints.click direct="clicked"
```

Then Vimium C will click the last-clicked element, if it's still visible.

And, ``` map . LinkHints.click direct="clicked" directOptions={"search":"doc"} ``` will "scroll into and click" a given element even when it's out of view.

`LinkHints.click direct="clicked"` requires you use `LinkHints.activate*` to click an element first. `LinkHints.activate* autoUnhover=true` will make Vmium C forget what's clicked, so the option should not be used before `LinkHints.click direct="clicked"`.

**Comment by mjfneto** [comment]
It sort of works. I have to use `LinkHints.active*` twice for `map . LinkHints.click direct="clicked"` to work. Do you what might be causing this?

**Comment by gdh1995** [comment]
On what website and what buttons? Any snapshot?

**Comment by mjfneto** [comment]
Does it take a little while to load at first? Because this only seems to happen when I have just opened a page. After a few seconds, it works just fine, both on Edge and Firefox.

**Comment by gdh1995** [comment]
@mjfneto  What command do you mean? If you mean `f`, then it does; if you mean `LinkHints.click`, then it's `direct="clicked"` which requires you have pressed `f` and selected an element before.

**Comment by mjfneto** [comment]
I mean the `LinkHints.click` command. The sequence I'm trying is this:

- page loads
- press `f`
- type LinkHint (it works; in the case of the carousel, the next item is shown)
- press `.` (if the previous steps are done to fast, sometimes, specially in Firefox, the message "No matching targets found" pops up after a first try. However, if done a second time, pressing `.` works as expected).

**Comment by gdh1995** [comment]
On what pages did you find the tip of `No matching targets`?

**Comment by mjfneto** [comment]
For instance, on this [page](https://www.w3schools.com/howto/howto_js_slideshow.asp), using Firefox.

**Comment by gdh1995** [comment]
&nbsp;Then what link did you click?



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 30, 2021 20:01 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Repeat last command (Issue #510)




 
For instance, on this page, using Firefox.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gdh1995** [comment]
Um, I think I find a bug of Firefox. Let me take a try to work around it.

**Comment by gdh1995** [comment]
Hello, Vimium C v1.96.0 has been released on Firefox Add-Ons, and you may try it again.
