### ISSUE TITLE
增强体验，拥有滚动的div 的键位提示放在滚动条的中间

### ISSUE THREAD

**Issue by q962** [gdh1995/vimium-c#511]
v1.94.0

我观察到，可以选择具有滚动的div，但是键位却是在左上角
问题
- 不容易区分键位指代的是什么
- 容易被左上角的按钮键位提示遮挡

目的
可以将放到键位放置在滚动条上，中间位置是一个不错的位置。还可以用颜色区分它

**Comment by gdh1995** [comment]
已经用深红色了。可以按 Space 来切换提示之间的遮盖顺序。

**Comment by q962** [comment]
1.95.0 更新的吗？

**Comment by gdh1995** [comment]
一直可以用深红色区分滚动类型、Space切换顺序啊

**Comment by q962** [comment]
![image](https://user-images.githubusercontent.com/15686075/143666733-8761ed8e-9c5e-42d3-902a-7a6e36f2d567.png)

**Comment by gdh1995** [comment]
反复按Space可以看到底下的提示字符

**Comment by q962** [comment]
没有颜色，Space 切换会使用了

**Comment by gdh1995** [comment]
没有的话说明这个“可滚动元素”也是可点击的，“可点击”比“可滚动”要优先，就没标红。

**Comment by q962** [comment]
好吧，那如果我想让提示符在滚动条上，我该改那个文件？

**Comment by gdh1995** [comment]
呃`content/hint_filter.ts#createHint`

**Comment by gdh1995** [comment]
可以用 `LinkHints.activateHover` ，只模拟切换焦点不模拟点击。这样，选择你想滚动的区域内部的某个元素后，就可以滚动相应区域了

**Comment by gdh1995** [comment]
就不用找左上角

**Comment by q962** [comment]
体验了下，也还行
