### ISSUE TITLE
Restore closed tab in background

### ISSUE THREAD

**Issue by omre86** [gdh1995/vimium-c#512]
Hello, is there a way to restoreTab to restore it in background, thank you

**Comment by gdh1995** [comment]
There's a trick which is not so good:
```
map z restoreTab $then="visitPreviousTab"
```

It will go to a previously visited tab when the restored tab gets "loaded", so you may have to wait for a while before Vimium C jumps back.

I'll add an option of `active=false` to `restoreTab` to restore in background directly, in a future version.

**Comment by omre86** [comment]
Thank you for you response, this feature will be good

**Comment by gdh1995** [comment]
Hello, Vimium C v1.96.0 has been released on Firefox Add-Ons, and you may add `active=false` then.

**Comment by omre86** [comment]
It works great now, thank you !!
