### ISSUE TITLE
[Feature] Deep Navigation Mode

### ISSUE THREAD

**Issue by blasterpistol** [gdh1995/vimium-c#519]
**How should a feature do**

Hello, sometimes links are nested too deeply (submenus, subpages, some other complex UIs), so it's annoying to constantly press `f DE` `f SH` `f H` `f J`. Maybe there is some kind of navigation mode that constantly highlights links until you exit that mode?

Something like this
`f (start deep navigation)` `DE` `SH` `H` `J` `f/q (stop deep navigation)`

**Comment by gdh1995** [comment]
By default, `Alt+F` is mapped to `LinkHints.activateWithQueue` mode, and you may also enter "queued" mode of `LinkHints` when you have pressed `f`, just by pressing `Alt`.

**Comment by blasterpistol** [comment]
Thanks, it works fine with submenus, but lacks consistent behavior for links that reload the page (open them in background tabs).

**Comment by blasterpistol** [comment]
`Alt+F` also not works as expected, for example
on github.com:

`Alt+F` then `SD`
![image](https://user-images.githubusercontent.com/4533828/145712863-d7326656-cc21-4e85-b6fa-03af29128b12.png)

That gives me no LH on menu items:
![image](https://user-images.githubusercontent.com/4533828/145712888-6dafd183-b5a1-4219-8b10-531533b14ebf.png)

But it works if I repeat this, I think the menu is loading asynchronously, so a little delay or DOM mutation observer might be helpful.

**Comment by gdh1995** [comment]
You can press `Tab` to refresh hints without changing LinkHints' mode; if a link still has no hint after a `Tab`, then you may try `F2` to tell Vimium C to collect "more clickable" elements.

F2 is only for Chrome-like browsers, and it will collect all elements which is directly under document and has a non-null `onclick` property but not an `[onclick]` attribute.

**Comment by gdh1995** [comment]
A mutation observer is not so helpful, since a page may "always" update its DOM in a small interval.

In queue mode `LinkHints` will auto refresh hints after it clicks a link, in about 250ms and when the old link is moved out or disappears.

**Comment by gdh1995** [comment]
When a page is reloaded Vimium C won't do anything to restart LinkHints, unless you write your customized key mappings using `$then` (https://github.com/gdh1995/vimium-c/wiki/Auto-run-a-tree-of-commands#run-a-key-after-a-command).

It's because it's almost impossible to recognize when is "suitable" to restart LinkHints.
