### ISSUE TITLE
after selecting iframe, vimium c creates listeners only for the contents of the iframe

### ISSUE THREAD

**Issue by smk291** [gdh1995/vimium-c#52]
I wrote a comment about this on the extension's page on the chrome store.  To repeat what I wrote there:

To replicate: 

1. Go to a page that uses iframes 
2. Press "f" 
3. Type the key combination, whose font is reddish, that focuses on the iframe. 
4. Press "f" again. 
5. The only links/buttons that vimium c recognizes and creates listeners for are now those in the iframe. The rest of the page is ignored.

I just discovered that merely clicking inside the iframe has the same effect.

**Comment by gdh1995** [comment]
Yes, this does exist. It's because Vimium C doesn't support the feature of LinkHints across iframes (up to v1.75.7).

Maybe I'll add part support of the feature in hte next several months.

**Comment by gdh1995** [comment]
Hello, Vimium c v1.79.1 has been released on Chrome Web Store and Firefox Add-ons, and you may have a try then.

It adds support for **LinkHints across same-origin frames**, and the **Filtered Hint** mode.
