### ISSUE TITLE
[Question] Custom selectors for clickable

### ISSUE THREAD

**Issue by AndreiD049** [gdh1995/vimium-c#520]
Hello, is there any way to add custom selectors to the clickable elements.
Scenario: We have an internal application with clickable table rows, but the rows are not highlighted when pressing `f`.
Is there any way to add `tr` element for a certain site? or maybe for all of them?

**Comment by AndreiD049** [comment]
Figured it out:
`map f LinkHints.activate clickable="tr"`

Is there ane documentation of the syntax of the `map` and other such settings?

**Comment by gdh1995** [comment]
See https://github.com/gdh1995/vimium-c/wiki/Add-or-remove-hints .

As for mappings, basic usages can be seen in https://github.com/philc/vimium . Some advanced usages are in:
- https://github.com/gdh1995/vimium-c/wiki/Map-the-keys-composed-with-Option
- https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout
- https://github.com/gdh1995/vimium-c/wiki/Map-a-key-to-different-commands-on-different-websites
- https://github.com/gdh1995/vimium-c/wiki/Auto-run-a-tree-of-commands
  - like https://github.com/gdh1995/vimium-c/wiki/Auto-run-a-tree-of-commands#run-a-key-after-a-command
