### ISSUE TITLE
Add preferences entry to toolbar context menu

### ISSUE THREAD

**Issue by kauesena** [gdh1995/vimium-c#521]
**What command or commands**

Open Vimium-c preferences. 

**How should a feature do**

When a user has done such steps:

1. Clicked with the right button the toolbar Vimium-c icon,

then Vimium C should do:

2. Open tab with add-on preferences. 

**Browser and OS**

- Browser name: Firefox
- OS name: Arch LInux

**Comment by gdh1995** [comment]
There's no browser API to do so.

If you left-click the icon, it will open a dialog and you may click the link of "Options" on the dialog to open Vimium C Options.

**Comment by kauesena** [comment]
Really? I've just checked and I get only: manage extension; remove extension; report extension; pin to overflow menu; remove from toolbar; menu bar; bookmarks toolbar; customize toolbar. I can get to Vimium-c preferences if I click manage extension and then give a couple more clicks.

**Comment by gdh1995** [comment]
You can **left click** the icon to see the Vimium C Popup dialog.

**Comment by kauesena** [comment]
Oh! _Left_-click. I did not read it correctly. I see it now. Thanks. I've just seen you can get to options from the help panel invoked by `?` too. I'll probably stick to this method. It is a pitry though that we cannot get to a addons options via the context menu of its icon.

**Comment by gdh1995** [comment]
But there's no API to do so. You may see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction to get what an extension can do about its icon.
