### ISSUE TITLE
Dark Mode Setting Independent of System Theme

### ISSUE THREAD

**Issue by Myrdden** [gdh1995/vimium-c#524]
Hello, as mentioned in #365, Firefox with `resistFingerprinting` set to `true` spoofs `systemUsesDarkTheme`, which in turn means the implemented dark mode doesn't work. So my question: Why does the dark mode setting *need* to be dependent only on the value of `systemUsesDarkTheme`? Would it be possible to simply embed an option or selector or modify the existing one such that one can manually select `Light | Dark | Use System Theme`, and thus free the option of being tied to that profile value?

**Comment by gdh1995** [comment]
Um, it's just because I haven't spent time to add this. Please wait for a next version of Vimium C.

**Comment by Myrdden** [comment]
No worries, thank you!

**Comment by technodrome** [comment]
+1. This definitely needs to be configurable. Spent ages now trying to find out why I get glaring white UI in newest Vivaldi.

**Comment by gdh1995** [comment]
Please try Vimium C v1.96.3, and you may click the checkbox of `darkMode` / `reduceMotion` for many times to switch among `disabled`, `following-the-global`, `always-enabled`.

**Comment by technodrome** [comment]
> Please try Vimium C v1.96.3, and you may click the checkbox of `darkMode` / `reduceMotion` for many times to switch among `disabled`, `following-the-global`, `always-enabled`.

Thanks, works! But no chance one would find that without your advice. Can you add some documentation in the sidebar or turn it into a proper dropdown? UX is quite bad otherwise.

**Comment by gdh1995** [comment]
Hello, Vimium C v1.96.4 for Chrome / Edge and v1.96.6 for Firefox have been published, and the help text has been updated.
