### ISSUE TITLE
Self build dist error: Unrecognized manifest key 'browser_specific_settings'.

### ISSUE THREAD

**Issue by tjx666** [gdh1995/vimium-c#525]
**Describe the bug**

![image](https://user-images.githubusercontent.com/41773861/147386486-439ac23d-721e-4c74-87ec-db68c4a6b89c.png)

**To Reproduce**

![image](https://user-images.githubusercontent.com/41773861/147386500-851e0987-aaab-4223-931e-257a611b4934.png)

![image](https://user-images.githubusercontent.com/41773861/147386507-439a59ce-a972-4d19-8711-bcbdd13d76e5.png)

![image](https://user-images.githubusercontent.com/41773861/147386796-320dc724-46fa-47a6-8354-63251256f461.png)

1. upgrade `terser` and `typescript`
2. modify .vscode `settings.json` to show some hidden files
3. `npm install`
4. change build target to `ES2021`, browser type for dist to `chrome`, min chrome version for dist to `96`
4. `node './scripts/tsc'`
5. `gulp dist`

**Browser, OS and Vimium C versions**

- Browser name: Chrome
- Browser version: 96.0.4664.110
- Vimium C commit hash: 2de2f2caef178d1a32f21e8aa91f44c18e24f020 
- OS name and version: MacOS 12.1

**Comment by gdh1995** [comment]
&nbsp;It's a warning and you may ignore it.



---Original---
From: ***@***.***&gt;
Date: Sat, Dec 25, 2021 22:02 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] Self build dist error: Unrecognized manifest key'browser_specific_settings'. (Issue #525)




 
Describe the bug
 

 
To Reproduce
 

 

 

  
upgrade terser and typescript 

modify .vscode settings.json to show some hidden files 

npm install 

node './scripts/tsc' 

gulp dist 
 
Browser, OS and Vimium C versions
  
Browser name: Chrome 

Browser version: 96.0.4664.110 

Vimium C commit hash: 2de2f2c 

OS name and version: MacOS 12.1 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gdh1995** [comment]
or, run "npm run chrome" to get a chrome-only version



---Original---
From: ***@***.***&gt;
Date: Sat, Dec 25, 2021 22:02 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] Self build dist error: Unrecognized manifest key'browser_specific_settings'. (Issue #525)




 
Describe the bug
 

 
To Reproduce
 

 

 

  
upgrade terser and typescript 

modify .vscode settings.json to show some hidden files 

npm install 

node './scripts/tsc' 

gulp dist 
 
Browser, OS and Vimium C versions
  
Browser name: Chrome 

Browser version: 96.0.4664.110 

Vimium C commit hash: 2de2f2c 

OS name and version: MacOS 12.1 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
