### ISSUE TITLE
Switching input source introduces unexpected bug in Chrome 96 at macOS 12.1

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#526]
The incomplete (if there're any others) list includes:
```
map ' openUrl url="vimium://status\u0020toggle-next\u0020^\u0020'"
map , goPrevious
map . goNext
map ; visitPreviousTab acrossWindows
```
Nothing happened when stroking keys, even the HUD didn't show.
And after a while it will restore; causes are unclear.

**Comment by gdh1995** [comment]
Browser name and version? What had you done before you found this.

**Comment by OnceThenEver** [comment]
Chrome 96 on macOS 12.1
I didn't do anything, as far as I can recall. The last event is the release of 1.96.1, the 2nd is that of 1.96.0

**Comment by gdh1995** [comment]
When will it happen that "Nothing happened when stroking keys"? For example, did you trigger any command and then notice this issue?

What did you mean by `after a while it will restore`? So now do such keys work well?

**Comment by OnceThenEver** [comment]
Of course I have to touch the keyboard to notice the issue. It just does nothing, like I didn't touch the keyboard.
It brokes down intermittently; maybe I triggered something subtle but I have no idea what's that.

**Comment by OnceThenEver** [comment]
Problem founded: In Chinese input source, `;``,``.``:` differ with those in English input source.

**Comment by gdh1995** [comment]
You can test what key info Vimium C receives on https://gdh1995.cn/vimium-c/keyboard-test.html . Please check what it records when "the keyboard focus is in an input box", and when not.

**Comment by OnceThenEver** [comment]
Bug about input source must be introduced recently since I've been using Vimium-C for almost a year without this problem.

**Comment by gdh1995** [comment]
Maybe Chrome 96 should be blamed. In fact, Chrome for Linux has a keyboard layout bug in versions from 92 to 94.

**Comment by OnceThenEver** [comment]
I'll temporally take the workaround adding Chinese character mappings.

**Comment by gdh1995** [comment]
It should not. This issue looks like a bug of Chrome, because `event.key` had never included IME-interpreted characters.

Could you do me a favor and put your test results in Chinese IME on https://gdh1995.cn/vimium-c/keyboard-test.html ?

**Comment by OnceThenEver** [comment]
https://user-images.githubusercontent.com/66708845/147462763-8ea36729-0e67-4655-9815-0905706ad044.mov

**Comment by gdh1995** [comment]
Seems a bug of Chrome 96. Google often adds some "features" into their browser which no normal people can image, and without any notification to developers - I can not find related items on https://chromestatus.com/features#milestone%3D96 .

**Comment by OnceThenEver** [comment]
Do what we can do. Neither partially checking nor unchecking will facilitate those users: they have to set overlapping and repeating mappings, or frequently switch between input sources. Complete check if want no bother.

**Comment by gdh1995** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1275011 reports a same issue on Chrome 98 (dev version).

Maybe I do need some actions to work around it. But I haven't got any idea.

**Comment by gdh1995** [comment]
What's the name of your `Chinese input source` on macOS 12.1 ?

**Comment by OnceThenEver** [comment]
System's default simplified Chinese



---Original---
From: "Dahan ***@***.***&gt;
Date: Tue, Dec 28, 2021 00:30 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Switching input source introduces unexpected bug in Chrome 96 at macOS 12.1 (Issue #526)




 
What's the name of your Chinese input source on macOS 12.1 ?

**Comment by gdh1995** [comment]
Thanks. I've reported in https://bugs.chromium.org/p/chromium/issues/detail?id=1282945 .

**Comment by gdh1995** [comment]
Hello Vimium C v1.99.0 has been available on Chrome, and please test this new option:
![image](https://user-images.githubusercontent.com/5547703/184065908-55294092-ab4f-46af-a50b-830e23d63ba1.png)

If you enable `Ignore keyboard layout if a key is not located in 7-bit ASCII` completely (it should have been partially selected), then Vimium C should support `.`, `,`, `;` even in a Chinese input source now.

**Comment by OnceThenEver** [comment]
This issue is solved. Thanks for your work.
