### ISSUE TITLE
Open link in new tab on specific page does not work in FF since 1.96.0

### ISSUE THREAD

**Issue by falolaf** [gdh1995/vimium-c#527]
Some links on the following page will not open correctly in new tab:
https://www.öob.se/jul/nyar/fyrverkerier

I.e., selecting link after `F` opens a new tab but the URL is truncated. 

1. Go to URL https://www.öob.se/jul/nyar/fyrverkerier
2. Type `F`
3. Select a link from any of the thumbnails
4. New tab is opened but URL is truncated to https://www.ob

The same Vimium C version in MS Edge Chromium works.
Vimium C version 1.95.0 works in Firefox.
Ctrl+click opens a new tab with correct URL in Firefox.

- Browser name:  Firefox
- Browser version: 95.0.2
- Vimium C version:  1.96.0/.1
- OS name and version: Windows_NT 10.0 18363

**Comment by gdh1995** [comment]
Oh it's a bug of Vimium C in v1.96.

To work around it, you may add `sed=false` when mapping keys, like:
```
map F LinkHints.activateOpenInNewTab sed=false
```

**Comment by falolaf** [comment]
> ```
> map F LinkHints.activateOpenInNewTab sed=false
> ```
I tested this and it does not work for me. URL is still truncated.

**Comment by gdh1995** [comment]
Sorry. `map F LinkHints.activateOpenInNewTab testUrl=false` should help in v1.96.2 .

**Comment by gdh1995** [comment]
Hello, you may take a try with Vimium C v1.96.3 on Firefox Add-Ons.

**Comment by falolaf** [comment]
v1.96,3 works fine! Thank you!

**Comment by gdh1995** [comment]
Hello, v1.97.0 has fixed some related bugs, and then you may remove `testUrl=false` and retry those links.

**Comment by falolaf** [comment]
It might take some time to verify this for me as my employer blocks almost all extensions/addons in all available browsers.
