### ISSUE TITLE
May I have choices about whether vomnibar's zoom scale is independent of that of page's?

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#528]

**Comment by gdh1995** [comment]
No, browsers haven't provide suitable API to get an absolute screen DPI ignoring zooming.

Chrome has `getScreens` (https://web.dev/multi-screen-window-placement/), but it needs a user to click "I agree xxxxxx" **on every website** calling this, so this is useless for extensions.
