### ISSUE TITLE
Bug of `switchFocus select="end"` immediately following `switchFocus select="all"`

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#529]
Chrome 96
macOS 12.1

Reproduce:
1. `map gu switchFocus select="all"` to select all texts in the field
2. ⎋ to blur
3. `map go switchFocus select="end"` to refocus the field, expecting cursor at the end

Then the bug is: all texts remain selected.

**Comment by gdh1995** [comment]
Well, it's a feature:
1. `select` is designed to only take effect when "a target input has no selection before"
2. there's no reliable way to learn "whether it has a selection or not"
3. but a approximate way is: by default Chrome makes a new input select its end
4. so Vimium C only uses `select=...` when it finds an input selects its end
5. so `select="end"` was ignored

The step 3 is not correct on Firefox - it seems Firefox prefers that an input selects all of its text.

Maybe I should update this logic.

**Comment by OnceThenEver** [comment]
> there's no reliable way to learn "whether it has a selection or not"

I noticed that when in Visual Mode, when some character is selected, the HUD is different from that of when there's no character selected, which means that Vimium-C can detect "whether it has a selection or not" out of input field; but it can't inside the input field, right?

**Comment by gdh1995** [comment]
A "new line" character is not related with "has a selection or not". They are two different things.

**Comment by OnceThenEver** [comment]
⏎ means to copy the selected by stroking `Enter`

**Comment by gdh1995** [comment]
Then, no. The "selection" word means "a range selection or a caret".

**Comment by gdh1995** [comment]
I've decided to update the logic to apply `select=...` and update selection if only "an old selection" of a target element is at the begin, at the end, or selecting the whole.

**Comment by OnceThenEver** [comment]
Why not when in the midway?

**Comment by OnceThenEver** [comment]
Why not when at the midway position?

**Comment by gdh1995** [comment]
Such a case means a user has used the input, and the range selection or caret may contain some info, so it should be kept.


There's also a way to force it to move caret - you may use 'focusInput $then=...' to execute another command, like running a JS URL.



---Original---
From: ***@***.***&gt;
Date: Wed, Dec 29, 2021 21:38 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Bug of `switchFocus select="end"` immediately following `switchFocus select="all"` (Issue #529)




 
Why not when at the midway position?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by OnceThenEver** [comment]
The user may define `map xxx switchFocus` without parameters to restore the last position of caret.

If you commit that way, then this inconsistent and counterintuitive behavior would make users confused until they find some documentation recording it; after all, `$then=` is not on help dialog; even yes, `$then=` increase the learning overhead.

**Comment by gdh1995** [comment]
now switchfocus restores (aka does't change) position by default.


i mean, only if you want to reset selection whatever it currently is, then you will need $then



---Original---
From: ***@***.***&gt;
Date: Wed, Dec 29, 2021 22:13 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Bug of `switchFocus select="end"` immediately following `switchFocus select="all"` (Issue #529)




 
The user may define map xxx switchFocus without parameters to restore the last position of caret.
 
If you commit that way, then this inconsistent and counterintuitive behavior would make users confused until they find some documentation recording it; after all, $then= is not on help dialog; even yes, $then= increase the learning overhead.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by OnceThenEver** [comment]
My solution is simple: let `select=...` parameter be independent of the perious state. Then with portfolio
```
map a switchFocus
map b switchFocus select="end"
map c switchFocus select="start"
map d switchFocus select="all"
```
the required functionalities are satisfied. As for "keeping potential information of caret's position", what about another parameter, toggling the independence?

**Comment by gdh1995** [comment]
I think most users won't want to give up useful info by default, and it's easy enough to move caret from middle to end. Then I won't change this parameter again.

**Comment by OnceThenEver** [comment]
Now that you insist, please tell me the detailed mappings using `$then=` to move caret or select all text coercively.

**Comment by gdh1995** [comment]
```
map <f1> switchFocus \
  $then="openUrl##url=javascript:(()=>{var%20a=document.activeElement,l=a.value.length;a.setSelectionRange(l,l)})()"
```

**Comment by OnceThenEver** [comment]
And this is for select all:
```
map <f1> switchFocus \
  $then="openUrl##url=javascript:(()=>{var%20a=document.activeElement;a.setSelectionRange(0,a.value.length)})()"
```

**Comment by gdh1995** [comment]
To select all, this also works:
```
map <f1> switchFocus \
  $then="openUrl##url=javascript:(()=>{var%20a=document.activeElement;a.select()})()"
```

**Comment by OnceThenEver** [comment]
Compact further:
```
map gg switchFocus $then="openUrl##url=javascript:{document.activeElement.select()}"
map go switchFocus \
  $then="openUrl##url=javascript:{var%20a=document.activeElement,l=a.value.length;a.setSelectionRange(l,l)}"
```
