### ISSUE TITLE
New tab question

### ISSUE THREAD

**Issue by ww7** [gdh1995/vimium-c#53]
Is a possible to disable to handle **newtab** only with compiling himself?
Prefer to use blank page with focus on a empty address-bar in Firefox.
If I set `about:blank` extension, text `about:blank` mixed with input.

For trick with "Focus web page when creating a new tab", Firefox `about:newtab` is not accepted.
about:**newtab** is a blacklisted? :)

**Comment by ww7** [comment]
Meanwhile with vimium-c I found `O` more handy than new tab

**Comment by gdh1995** [comment]
Sorry but I can't get what's your question.

Currently, if you don't expect Vimium C to take over the NewTab settings, you may:
* download Vimium C's .xpi file and unzip it
* edit the "manifest.json" file, delete the line of `"newtab": "pages/newtab.html"` and save
* open `about:debugging` and then load the manifest.json as a new web extension on Firefox.

**Comment by ww7** [comment]
Thank you.
Would be good to see this Tip in the Wiki
I'm just inform: about:newtab - not accepted in Options

**Comment by gdh1995** [comment]
Oh. the `about:newtab` is a "standard" URL which means a common new tab page, but with the current released Vimium C, this URL will be taken over by Vimium C and redirected to another configurable URL (the "New tab URL" option of Vimium C). And as a result, if Vimium C's "New tab URL" was also `about:newtab`, there would be a dead loop, so this is refused on the Vimium C Options page.

**Comment by gdh1995** [comment]
The current version of Vimium C, v1.76.1, will **cause you fail to use Vimium C to open Firefox's default new tab page** - although you are still able to see the page by typing `about:home` on the address bar, Vimium C is not allowed by Firefox to open this page yet. So Vimium C Options page also refuses a value like `about:home`.

Comment: The "default new tab" mentioned above looks like this:
![image](https://user-images.githubusercontent.com/5547703/61185773-a4fba480-a68f-11e9-94d5-8195f3475d0c.png)

**Comment by ww7** [comment]
> Sorry but I can't get what's your question.
> 
> Currently, if you don't expect Vimium C to take over the NewTab settings, you may:
> 
>     * download Vimium C's .xpi file and unzip it
> 
>     * edit the "manifest.json" file, delete the line of `"newtab": "pages/newtab.html"` and save
> 
>     * open `about:debugging` and then load the manifest.json as a new web extension on Firefox.

for persistent tweaked addon i'm need to make xpi and load  with disable signature in dev version of Firefox?

**Comment by gdh1995** [comment]
Well, as said in eariler issues, I'll give up the current feature of overriding browser's new tab, when Vimium C arrives at a new version (maybe v1.77). And then new tab will not be affected.

**Comment by gdh1995** [comment]
Vimium C v1.77.0 has been on Chrome Web Store and Firefox Add-ons, and it won't manage the New Tab settings any more.

So closed.
