### ISSUE TITLE
How to reference the original <space> given `map <space> scrollDown`

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#531]

**Comment by gdh1995** [comment]
Use `passNextKey`: https://github.com/philc/vimium/wiki/Tips-and-Tricks#using-the-escape-key-in-inputs .

BTW, here should be `map`, but not `mapKey`.

**Comment by OnceThenEver** [comment]
I mean:
```
map <space> scrollDown
mapKey <c-space> originalSapce
```

**Comment by gdh1995** [comment]
`mapKey` is only a task inside Vimium C, while it can not affect your browser or web pages.

**Comment by OnceThenEver** [comment]
Didn't get your idea.
Because of the first mapping, `mapKey <c-space> space` is actually `mapKey <c-space> scrollDown`; I want original space's function that scroll down one page be transferred to `<c-space>`.

**Comment by gdh1995** [comment]
Then I still fail in understanding what's you need.

Any detailed steps?

**Comment by OnceThenEver** [comment]
I've found `scrollFullPageDown` just now.
Apology for my carelessness!

**Comment by gdh1995** [comment]
Um, by default `<space>` is not a shortcut in Vimium C, but one of your browser.
