### ISSUE TITLE
进一步扩展yy的功能.

### ISSUE THREAD

**Issue by hahagood** [gdh1995/vimium-c#532]
**What command or commands**
需要对yy的功能进一步地扩展.

**How should a feature do**
在微信转发一个链接的时候,希望复制的格式是
url
description
而要复制一个链接到org-mode的时候,又希望是
[[url][description]]

When a user has done such steps:
以前在用surfingkeys的时候,是可以自己添加代码去修改,增加部分功能的.最近几天surfingkeys不灵了. 

then Vimium C should do:
希望能进一步扩展yy的功能.或者开放添加代码的功能.

**Browser and OS**

- Browser name: Chromium
- OS name: Archlinux

**Comment by gdh1995** [comment]
Will be added as a new usage of `LinkHints.activateCopyLinkText` in a future version.

**Comment by gdh1995** [comment]
Hello, Vimium C v1.96.3 has been available. You may write key mappings like:
```
# the `.foo` is a CSS selector to find a child element, and can be empty to use the hinted element
map xxx LinkHints.activateCopyLinkText access=".foo:[[${href}][${innerText||textContent}]]"

# these are also valid formats:
map yyy LinkHints.activateCopyLinkText access=":${href}\n${innerText||textContent}"
map zzz LinkHints.activateCopyLinkText access="${innerText||textContent}"
map ccc LinkHints.activateCopyLinkText access="innerText"
```
