### ISSUE TITLE
Feature request: reload page without # part of URL

### ISSUE THREAD

**Issue by EJamesW** [gdh1995/vimium-c#537]
Great package, thanks!

I'm a former user of Surfingkeys, and one little feature which that add-on had, but that appears to be missing with vimium-c (and vimium), is the command to reload the page without the # part of the URL.

It's the command that's bound to `g#` in Surfingkeys.

Would it be possible to add this command?

**Comment by gdh1995** [comment]
You may:
1. add this to "Custom key mappings"
```
map g# openUrl url="$S" url_mask sedKeys="0" reuse="current"
```
2. add this to `Auto substitution of various text`
```
0/#.*//
```

And then, `openUrl` will:
1. access a current tab's URL and replace `$S` with it
2. run `text substitution` on the URL by a key of `0`, and then text matching `new RegExp("#.*")` will be replaced with `""`
3. open the result in a current tab

**Comment by EJamesW** [comment]
This works perfectly. Much appreciated, thank you!
