### ISSUE TITLE
Support icons on previous patterns and next patterns

### ISSUE THREAD

**Issue by tamwile** [gdh1995/vimium-c#538]
**What command or commands**

It would be nice if Previous patterns and Next patterns could handle icons, and not only text.
For example, i found some websites using font-awesome for the [pagination](https://fontawesome.com/v4.7/icon/chevron-right).
afaik, it is impossible to add an icon to the Next patterns list.

**How should a feature do**

Allow to add css class to the Previous patterns and Next patterns.
With the example above, we should be able to add fa-chevron-right, and fa-chevron-left

**Infos**

Firefox 95.0.2
Linux

**Comment by gdh1995** [comment]
The 2 patterns has supported CSS selectors, if only a word starts with `.`, `#` or `[` .
