### ISSUE TITLE
enable/disable the vimium-c in a tab

### ISSUE THREAD

**Issue by logicalbhanu** [gdh1995/vimium-c#539]
how can i disable/enable vimium-c in a tab, i have look for some of the comment posted by on one of the issue at 'vimium' github page, but that only disables it for me and to enable it again i have to click it manually.

I am using Brave browser Version 1.34.80 Chromium: 97.0.4692.71 (Official Build)(64-bit)

**Comment by gdh1995** [comment]
https://github.com/gdh1995/vimium-c/wiki/Enable-or-Disable-all-frames-by-a-shortcut
