### ISSUE TITLE
"searchAs" and "searchInAnother" syntax

### ISSUE THREAD

**Issue by ww7** [gdh1995/vimium-c#54]
For me not work 
I'm tried  with `map S searchInAnother keyword="s"`
where `s: http://searx.be/?q=%s`
Answer `no search engine found`
Also with `keyword="wiki"`
Same with `map s searchAs`

**Comment by gdh1995** [comment]
What's the URL of your test page? Vimium C can only recognize query words on pages which match at least one configured search engine, while it seems that it is not familiar with your test page.

**Comment by ww7** [comment]
Got it. Thanks
Why it's limited for search engines results?

**Comment by gdh1995** [comment]
Vimium C can not know all patterns of search result URLs, and hand-written parsing may cause unexpected errors, so I decided just to let users specify what they want.

**Comment by gdh1995** [comment]
So closed?

**Comment by ww7** [comment]
Great, thanks

**Comment by elig0n** [comment]
why does it not take selected words from any page but search engine results page ?

**Comment by gdh1995** [comment]
@elig0n Vimium C just provides a way to recognize words from a tab's URL, since there's no reliable solution to extract words from all existing websites.

**Comment by elig0n** [comment]
@gdh1995 Sorry i do not understand. Selection is recognized for copy so what is the problem sending it to the default search engine?

**Comment by gdh1995** [comment]
Um, I can not get what you want. Maybe you can try `autoOpen`, and it will use selected words (those whose background color is blue) and search it (if the selected is a URL, then open it). `autoOpen` has an option named `keyword` to specify which search engine to use.

If I'm still misunderstanding your question, could you file a new issue and describe it in detail?

**Comment by elig0n** [comment]
uh so what is searchAs and searchInAnother used for ?

**Comment by gdh1995** [comment]
* `searchAs`: search "user's selected white-blue text or copied text" in a search engine which is recognized from a current tab
  *  for example, if copy "bar" on Word / Excel and trigger it on a Google search result page, then search "bar" with Google
* `searchInAnother`: recognized search words from a current tab and use another predefined search engine to search it
  *  for example, switch from Google to MS Bing.
  * the destination search engine is defined in the "keyword" option of key mapping rule
* while `autoOpen`: search "user's selected white-blue text or copied text" in a predefined search engine
  * the destination search engine is defined in the "keyword" option of key mapping rule

**Comment by OnceThenEver** [comment]
> * while `autoOpen`: search "user's selected white-blue text or copied text" in a predefined search engine
>   
>   * the destination search engine is defined in the "keyword" option of key mapping rule

According to your instruction, I wrote `map B autoOpen keyword="https://www.bing.com/search?q=$s"`.

But when I select "AndroidSDK", the new tab's URL is `https://www.google.com/search?q=AndroidSDK`, whereas my default search engine is Google.

What's the problem?

**Comment by gdh1995** [comment]
`keyword` should be a name of one custom search engine.

**Comment by OnceThenEver** [comment]
Got it, thank you.

**Comment by sky31even** [comment]
got it ~~ autoOpen allows keyword input too ~~
