### ISSUE TITLE
提2个issue，向指定函数传递选中的链接 以及 恢复标签页的Vomnibar

### ISSUE THREAD

**Issue by Wooolfboy** [gdh1995/vimium-c#540]
**What command or commands**
1.如何选中的链接或者图片后，把链接标题当成参数传递给指定的函数?
2.是否能实现恢复已关闭的标签页的Vomnibar?

**How should a feature do**
1.我想把图片下载到指定目录，如果有title的话则把title作为文件名，函数已经构造完毕，只要传递参数进去就能下载（我很想实现这个功能，如果没有打算添加的话我自己需要怎么实现？是否能在LinkHints中添加自定义方法？）
2.在不清楚关闭了几个标签页想恢复其中的某一个，这时候把已关闭的标签页做成Vomnibar会很有用（历史列表在这个情况下并不太好使，一个是失去了前进后退历史，另一个是需要重新加载页面）

**Browser and OS**
Firefox95 ，Manjaro

**Comment by gdh1995** [comment]
1. You may make `LinkHints` trigger `dispatchEvent`, like:
```
# key mappings
map f LinkHints.activateHover $then="<v-notify>"
map <v-notify> dispatchEvent class="custom" type="vimium:notify"
```

and a test page can be:
``` html
<html>
  <div>
    <a id="test" href="#">say hello when LinkHints selects this</a>
  </div>
  <script>
    document.addEventListener("vimium:notify", (ev) => {
      alert("hello")
      // or do whatever you want
    })
  </script>
</html>
```

2. When you trigger `Vomnibar.activate`, it will be in `omni` mode, and list all recently-closed tabs when no queries. You may select an item to recover the tab, or press <kbd>PageDown</kbd> or <kbd>Shift+ArrowDown</kbd> to see earlier closed tabs.

**Comment by gdh1995** [comment]
1. Or you may save your JS code into a browser bookmark or a line in key mappings
```
# key mappings
map f LinkHints.activateHover $then="<v-run_bm>"
map <v-run_bm> openBookmark title="vimium:downloadImage"

map g LinkHints.activateHover $then="<v-run_js>"
map <v-run_js> openUrl url="javascript:let%20a=1;alert(a)"
```

2. closed tabs have a mark:
![image](https://user-images.githubusercontent.com/5547703/149870665-ce67fa91-baf2-4fff-abcf-5ba9c27dde27.png)

**Comment by gdh1995** [comment]
BTW, now `LinkHints.activateDownloadImage` will also try using`<img>.title`, though it won't auto append an extension name like `.png`.

**Comment by Wooolfboy** [comment]
完美！我是在暴力猴中的脚本构造的函数，所以采用的是第一种，目前用下来完美运行。
第二个issue原来默认的Vomnibar就带有恢复标签页，居然一直都被我忽略掉了，惭愧惭愧。
全部解决，赞！
