### ISSUE TITLE
Unclickable hints on Google

### ISSUE THREAD

**Issue by tripfish** [gdh1995/vimium-c#541]
I'm getting link hints in the second line (title) of a search result that doesn't open the page when I call the link hint. It just shows a frame around the search result for a short time when I call the hint.

1. Go to google.com
2. search something
3. press f (for LinkHints.activate)
4. call a link hint in second line (R)

![image](https://user-images.githubusercontent.com/13979325/149993638-e5bc959f-13fa-442a-9bd9-0798932db8b3.png)

![image](https://user-images.githubusercontent.com/13979325/149994596-320c0c34-11a0-4392-817d-ff4d6a4054a7.png)

- Browser name: Google Chrome
- Browser version: 97.0.4692.71 (Offizieller Build) (64-Bit) (cohort: Stable)
- Vimium C version: 1.96.3
- OS name and version: Windows 10 64 Bit

**Comment by random-un** [comment]
Came here to report the same thing. This behavior started recently.

Operation system: Chrome OS 97.0.4692.91
Vimium C version: 1.96.3

![image](https://user-images.githubusercontent.com/35006176/150437248-5ef91e3b-dc2b-4264-a93e-cce29ca225b9.png)

**Comment by taozhang-tt** [comment]
have the same problem, any solution?

**Comment by gdh1995** [comment]
Hello, Vimium C v1.96.4 for Chrome / Edge, and v1.96.6 for Firefox have been published, and you may take a try.

**Comment by tripfish** [comment]
Works perfectly on Chrome and Firefox. Thank you very much!

**Comment by random-un** [comment]
Wanted to report that I'm still having some issues here:

- Some hints for certain Google search results remain un-clickable. See an example in this screenshot 
![image](https://user-images.githubusercontent.com/35006176/154631569-f4fdc5a9-483b-42b3-9c5c-519341ff8f53.png)
- For me the _Copy a link URL to the clipboard_ action (LinkHints.activateCopyLinkUrl) rarely works on Google.com search results pages. I 
![image](https://user-images.githubusercontent.com/35006176/154631727-246243f6-3c64-4f22-84a5-af318ed36e17.png)


Thanks for your continued work on this excellent extension.

**Comment by gdh1995** [comment]
@random-un As for the 2nd point, have you tried `Q` and `W` on the snapshot? I think it will copy some URLs "successfully".

What will it copy on your browser? I tried once and got `https://www.google.com/aclk?sa=l&ai=DChcSEwjN4MWe******`. If you also get this please let me know.

**Comment by random-un** [comment]
Apologies for the delay. For me triggering LinkHints.activateCopyLinkUrl on Google search results pages brings up hints, but does not allow me to select any hints. When I hit `W` in the screenshot above the links remain visible and nothing gets copied to the clipboard. 

This is similar to the previous unexpected behavior for opening links -- it was not possible to activate the `W` hint, but if there was a hint below it for `Test.com: Home` then that link _would_ be possible to activate.

**Comment by gdh1995** [comment]
Oh it means a crash of Vimium C. I once met it but yesterday I could not reproduce it again. I'll do more test when I have rest time.

**Comment by ni554n** [comment]
@gdh1995 This is still an issue on the latest version even after applying the snippet from previous reply.
I just switched from Vimium. It doesn't show the non functioning hint on the URL.

**Comment by gdh1995** [comment]
@ni554n  Sorry but Google often modify there webpages, and it even shows somehow different pages for different users, so I can not reproduce your issue in a reliable way.

Could you try to add `map xxx LinkHints.activate clickable="a>h3"` ?

**Comment by stivens13** [comment]
Hi all!

Still having the issue of inactive link hints on Google search. The solution below and similar doesn't work for some reason. Do I understand correctly that this remap makes `f` to use altered link hint and no additional keys need to be pressed?

> env g host=":https://www.google.com/search?"
> 
> run f <v-f> expect="g:<v-gf>"
> map <v-f> LinkHints.activate
> map <v-gf> LinkHints.activate clickable="a>h3"
> 
> run F <v-F> expect="g:<v-gF>"
> map <v-F> LinkHints.activateOpenInNewTab
> map <v-gF> LinkHints.activateOpenInNewTab clickable="a>h3"

**Comment by gdh1995** [comment]
@stivens13 Yes both `f` and `F` will behave differently based on what a current website is.

Please check the URL of your Google search result pages. `host` of `env` should be "`:`" + `prefix of the URL` .
