### ISSUE TITLE
hide specific type  of linkhint

### ISSUE THREAD

**Issue by sisrfeng** [gdh1995/vimium-c#544]
Thanks for your nice work!
This area in google is annoying, I can not find a method to disable it. 
![image](https://user-images.githubusercontent.com/53520949/150722014-f6a0f315-4ada-45f1-88d1-b7ff422c6304.png)

![image](https://user-images.githubusercontent.com/53520949/150721969-1682cb9a-56fe-4db7-b60d-87e27104215d.png)

Can vimium-c hide the linkhint of this menu ? 
![image](https://user-images.githubusercontent.com/53520949/150721930-9ab77166-9333-4723-8d4c-0c29e33edf0e.png)

**Comment by gdh1995** [comment]
Please see https://github.com/gdh1995/vimium-c/wiki/Add-or-remove-hints

**Comment by sisrfeng** [comment]
有没有大佬知道具体怎么搞啊?  不懂css啊

**Comment by gdh1995** [comment]
呃Google的页面压缩得太厉害，确实难了点。你可以这么写：
```
map f LinkHints.activate exclude="[aria-label=\"About\u0020this\u0020Result\"]"
```

效果是把”标签“带”About this Result“的都舍弃掉。

**Comment by gdh1995** [comment]
`.link` and `.button` are only simple examples and can be removed.
