### ISSUE TITLE
Vomnibar blacklist not working as expected

### ISSUE THREAD

**Issue by LanHikari22** [gdh1995/vimium-c#546]
**Describe the bug**
I have some bookmarks I title with "+ar" or "archived" and would like to be able to filter them since I use bookmarking a lot. I added these two patterns to "Block list of words for Vomnibar" setting. However when I launch the vomnibar with "b" or "o" I still see them as valid entries. What I did is I added the pattern to the name of the bookmark in firefox.

**To Reproduce**

1. Bookmark any website. Ex: www.google.com, and title the bookmark "archived abc - Google"
2. Bookmark another link. Ex: https://www.google.com/imghp, and title the bookmark "abc - Google Images"
3. Include "archived" as a black-listed pattern in vimium-c option "Block list of words for Vomnibar"
4. Launch the bookmark search with "b" or vomnibar with "o" and search the pattern "abc"

Expected result: "archived abc - Google" would not show up in the results, or at the very least, would be deprioritized in sorting. 

**Suggestion**
It would be great to filter words dynamically in the vomnibar with some pattern. Like typing "-archived" to filter out that word from the search query, or "!archived" or "!!archived". I would find this more useful than blacklisting because sometimes I may want to see results I choose to filter out this way. The dash syntax is inspired by rofi for filtering out windows like "-fox" if I don't want to see firefox windows in the search results.
Please also let me know if you guys are open for a PR for a feature like this.

**Browser, OS and Vimium C versions**

- Browser name: Firefox
- Browser version: 95.0.2 (64-bit)
- Vimium C version: 1.96.4
- OS name and version: Manjaro Linux

**Comment by gdh1995** [comment]
1. Confirmed.

2. PRs are always welcomed. I suggest that it can be a new keyword in the `Vomnibar settings`'s `actions` field.

**Comment by gdh1995** [comment]
Hello, Vimium C v1.96.6 for Firefox has been published, and you may take a try.

**Comment by LanHikari22** [comment]
Thank you! It works as expected now. I can see that if I explicitly write one of the blocked terms, it would show the results for them too, which is nice!
