### ISSUE TITLE
The "H" key doesn't work: doesn't switch to previous page 

### ISSUE THREAD

**Issue by haosmos** [gdh1995/vimium-c#547]
**Describe the bug**

The "H" key doesn't work: doesn't switch to the previous page. I have specified in the settings in the "Custom key  
mappings": "map H goBack $count=-1" but that does not solve the problem. 

**To Reproduce**

**Browser, OS and Vimium C versions**

- Browser name: Microsoft edge 
- Browser version: 97.0.1072.76 
- Vimium C version: 1.96.3
- OS name and version: Windows 11, build: 22000.434

**Comment by gdh1995** [comment]
An upper-case "H" usually means Shift+H if only the CapsLock key is off. Have you tried Shift+H ?


And, the "$count=1" is not needed.



---Original---
From: ***@***.***&gt;
Date: Mon, Jan 31, 2022 19:13 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] The "H" key doesn't work: doesn't switch toprevious page  (Issue #547)




 
Describe the bug
 
The "H" key doesn't work: doesn't switch to the previous page. I have specified in the settings in the "Custom key
 mappings": "map H goBack $count=-1" but that does not solve the problem.
 
To Reproduce
 
Steps to reproduce the behavior:
 
Browser, OS and Vimium C versions
  
Browser name: Microsoft edge 

Browser version: 97.0.1072.76 

Vimium C version: 1.96.3 

OS name and version: Windows 11, build: 22000.434 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by haosmos** [comment]
> An upper-case "H" usually means Shift+H if only the CapsLock key is off. Have you tried Shift+H ? And, the "$count=1" is not needed.
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Jan 31, 2022 19:13 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [gdh1995/vimium-c] The "H" key doesn't work: doesn't switch toprevious page (Issue #547) Describe the bug The "H" key doesn't work: doesn't switch to the previous page. I have specified in the settings in the "Custom key mappings": "map H goBack $count=-1" but that does not solve the problem. To Reproduce Steps to reproduce the behavior: Browser, OS and Vimium C versions Browser name: Microsoft edge Browser version: 97.0.1072.76 Vimium C version: 1.96.3 OS name and version: Windows 11, build: 22000.434 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

Oh, I found the reason: the reason is that I use [PowerToys](https://github.com/microsoft/PowerToys), which allows me to reassign the keys of the keyboard — I applied the following key reassignment: "h + shift = backspace". 

Now I disabled PowerToys and shift + H returns to the previous page in the browser. 

I think I found a solution: I reassigned the key in vimium-c settings from H to O and it seems to work. 

Thanks for your great extension! 👍🙌
