### ISSUE TITLE
Not working correctly with Vivaldi 5.1

### ISSUE THREAD

**Issue by cjk** [gdh1995/vimium-c#553]
**Describe the bug**

After upgrading to Vivaldi 5.1 most Vimium-commands stopped working for me.

Some errors are displayed in the extensions error-log:

![image](https://user-images.githubusercontent.com/57523/153385997-ae1936ec-cf56-4eea-ac2a-80ecb1b909b4.png)

**To Reproduce**

1. Upgrade to Vivaldi 5.1
2. Go to any site, like https://reddit.com
3. Try to open new tab / show Vomnibar or close tab using Vimium keyboard-shortcut

**Browser, OS and Vimium C versions**

- Browser name: Vivaldi
- Browser version: 5.1.2567.39 (Stable channel) stable (64-bit)
- Vimium C version: 1.96.6
- OS name and version: Linux 5.16.8-arch1-1 SMP PREEMPT Tue, 08 Feb 2022 21:21:08 +0000 x86_64 GNU/Linux

**Comment by gdh1995** [comment]
Um, the image is not an error, and you may ignore the `invalid scheme` warnings.

I can not reproduce this issue on Vivaldi 4.1.2567.39 for Win10 with a fresh profile. So, up to now,
1. does `chrome-extension://hfjbmagddngcpeloejdejnfgbamkjaeg/pages/options.html` work on your Vivaldi?
2. please test these steps to get the potential log messages:
- 1. Open `chrome://extensions/?id=hfjbmagddngcpeloejdejnfgbamkjaeg`
- 2. turn on the `developer mode` switch at the top right corner
- 3. and then click a link of "`background page`" in the "Inspect views" section.
- 4. then your browser will popup a debugging window and then the "`Console`" panel has log information.
3. if there's no error message, please press `<f12>` on a website tab like https://reddit.com and then see its `Console` panel

**Comment by cjk** [comment]
Thanks for the info, I followed your steps and there is the this error-message shown in the console:

```
Error in event handler: TypeError: Error in invocation of sessions.getRecentlyClosed(optional sessions.Filter filter, function callback): Error at parameter 'filter': Error at property 'maxResults': Value must be at most 25.
    at Object.p [as ai] (<URL>)
    at Object._u (<URL>)
    at Object.af (<URL>)
    at Object._u (<URL>)
    at Object.e.y._u (<URL>)
    at Array.y (<URL>)
    at i (<URL>)
```

Now we just need to find out where this value of "maxResults" is set :thinking:

**Comment by gdh1995** [comment]
Is there any error if press `<f12>` on a website tab like https://reddit.com/ and then see its `Console` panel?

The error is caused by an inner issue of Vivaldi, which may break `Vomnibar`, but not other commands of Vimium C.

**Comment by cjk** [comment]
After some more experimenting, it looks like there are two behaviors contributing here:
1. The above error in `sessions.getRecentlyClosed` prevents any vomnibar-related functionality
2. After initially visiting (some?) pages by clicking a link, after the page loaded, Vimium-C is totally unresponsive and no keyboard-action triggers anything. However, reloading the page manually resolves this and Vimium-C starts working, except for the Vomnibar, of course

@gdh1995  If I understand you correctly, the first problem is caused by Vivaldi and we have a wait for a fix from them?
I don't know, perhaps the second issue will also disappear once Vivaldi fixed the first :man_shrugging: 

Thanks for looking into this so far. Perhaps the best option for me may be to downgrade to Vivaldi 5.0 for now. Because without the Vomnibar, browsing is no fun to me :grinning:

**Comment by gdh1995** [comment]
1. Vimium C will work around it in a next version
2. When you found "unresponsive", was the keyboard focus on the web page yet? I mean, it might be on not a page but your browser window, so JS code could not get any key
3. If a page has focus but Vimium C still fails, please open the Developer Tools and put errors on `Console` here. Thanks.

You may add this to key mappings to disable the session feature of Vomnibar:
```
map o Vomnibar.activate noSessions
```

**Comment by gdh1995** [comment]
Hello, Vimium C v1.97.0 should have fixed this, and you may remove `noSessions` and take a try.

V1.97.0 has a bug affecting order of Vomnibar suggestions, and I'll fix it in a next version.

**Comment by cjk** [comment]
Thanks @gdh1995 , I just tested and the Vomnibar is back for me, even without the `noSessions` parameter.

Great work! :+1:

**Comment by gdh1995** [comment]
Oh sorry but I forgot to check problems about other commands. Do Vimium C's other commands (other than Vomnibar) work on your Vivaldi now? If not, log messages and website URLs might help.

**Comment by cjk** [comment]
@gdh1995 thanks for asking. I haven't noticed any other regressions, though I'm only using a fraction of Vimium C's functionality (mostly searching, tab- and page-navigation).
So I think we're fine here. If I stumble upon anything odd, I'll open another issue.

Thanks again for your great support!

**Comment by cjk** [comment]
In newer versions of Vivaldi, a similar problem surfaced now:

![image](https://github.com/gdh1995/vimium-c/assets/57523/5715857b-6266-4ef7-b651-2edc455d59cb)

Perhaps it's related to / similar to fix like the error above.

**Comment by gdh1995** [comment]
The two warnings means two special features which can work only if your browser has enabled the `#extensions-on-chrome-urls` flag.

When the flag is disabled by default, the 2 warnings are shown, and there seems no way to avoid this behavior on Chromium-based browsers. You may just ignore them.
