### ISSUE TITLE
[FEATURE REQUEST] Edit mode

### ISSUE THREAD

**Issue by grappas** [gdh1995/vimium-c#555]
**What command or commands**

Choose text box with "f" or "gi", leave text box with "bd" or "q"

**How should a feature do**

When a user has done such steps:

Choose text box with "f" or "gi" leave text box with "bd" or "q"

then Vimium C should do:

When editing a text box to use vim shortcuts to edit a text box with all modes available (normal, insert, visual, etc.). When text box is focused all shortcuts works only for that text box. Text box can only be left if "bd" or "q" is stroked.

Yea, I know there is a firenvim extension, but it's not working for all text boxes. 

Having such extension and not having possibility to edit like in vim is felt like little bit handicapped - if you know what I mean ;). 

**Browser and OS**

- Browser name: Firefox 97
- OS name: Windows 10

**Comment by gdh1995** [comment]
Sorry but I don't want EditMode. A whole "VIM-like edit mode" is too big to added it into Vimium C.

Vimium C's original project, Vimium (https://github.com/philc/vimium), once had the `enterEditMode`, but the command had too may issues and was hard to maintain, so in https://github.com/philc/vimium/pull/1961, Vimium removed it completely.

Here're some advices:
1. If you want a full-featured VIM-like edit mode, then https://github.com/philc/vimium/pull/1961#issuecomment-178566159 recommends https://chrome.google.com/webstore/detail/wasavi/dgogifpkoilgiofhhhodbodcfgomelhe .
2. if you just want to trigger some commands of Vimium C when in an input, please see https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box
- 1. for example, if you want to replace selected text or modify selection, you may use `editText` as said in https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box#edit-text-using-edittext
3. if you want to run a very complicated action, you may add long JS code as a bookmark, and use `map xxx openBookmark title="v:cmd1"` to  run it
- 1. you may use Vimium C's commands to build a command tree - see https://github.com/gdh1995/vimium-c/wiki/Auto-run-a-tree-of-commands
