### ISSUE TITLE
[Feature Request] Searching Chrome Windows' Name

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#556]
![Screen Shot 2022-02-21 at 22 02](https://user-images.githubusercontent.com/66708845/154970008-a4c8f78c-3121-4d9d-acdd-ec78dda735c7.png)

Just as important as searching tabs.

**Comment by gdh1995** [comment]
Sadly, there's no extension APIs to access this name: https://developer.chrome.com/docs/extensions/reference/windows/#type-Window
