### ISSUE TITLE
`ArrowDown` and `ArrowUp` simulation doesn't work

### ISSUE THREAD

**Issue by alexluigit** [gdh1995/vimium-c#557]
**Describe the bug**

**To Reproduce**

Use the config from https://github.com/gdh1995/vimium-c/wiki/Auto-run-a-tree-of-commands
```
map <v-de> dispatchEvent

# simulate `ArrowDown` and `ArrowUp` by `Ctrl+J` and `Ctrl+K`
env s element="select"
env t element="textarea"
run <c-j:i> #key=ArrowDown%2C40+de-de,#key=ArrowUp%2C38+de-de \
  expect="t:editText#run=auto%2ccount%2cline;s:scrollSelect"
run <c-k:i> -<c-j:i>
```
Press C-j/k, the hud says "the 'de-de' has not been mapped".

**Browser, OS and Vimium C versions**

- Browser name: Brave
- Browser version: 1.35.103
- Vimium C version: 1.96.6
- OS name and version: Arch Linux

**Comment by gdh1995** [comment]
Oh it's a bug in v1.96.xxx . I'll fix it soon.

**Comment by gdh1995** [comment]
Here's a working around: replace line of `run <c-j:i>` with
```
run <c-j:i> #key=ArrowDown%2C40+de+-de,#key=ArrowUp%2C38+de+-de \
  expect="t:editText#run=auto%2ccount%2cline;s:scrollSelect"
```

The difference is to add `+` before `-de`, so that Vimium C can learn "-de" is a second command.

**Comment by alexluigit** [comment]
Thanks! It works.
