### ISSUE TITLE
Cannot iterate twitter images in Firefox

### ISSUE THREAD

**Issue by leodream** [gdh1995/vimium-c#559]
**Describe the bug**

Cannot select the next/previous images with [[/]] when viewing a tweet that has multiple images in Firefox

**To Reproduce**

1. Open a tweet with multiple images. (e.g. https://twitter.com/firefox/status/1461436801093193738)
2. Click on one image. There are "→" and "←" shown at the edge of the images.
3. With Firefox, [[ and ]] do not work. With Chrome, it can change to next and previous images. 

**Browser, OS and Vimium C versions**

- Browser name: Firefox
- Browser version:  97.0.1
- Vimium C version: 1.96.6
- OS name and version: openSUSE Tumbleweed  Linux 5.16.10-1

**Comment by gdh1995** [comment]
Does your Firefox has a same configuation for the preferred page language with your Chrome?

Twitter doesn't provide enough clues to let Vimium C know the arrow icons mean "next/previous" (for web-extension code, there's no way to check whether an icon "looks like arrow" or not).

The only useful point is `title` of the 2 icons. So during my tests, on twitter in English `goNext` works, but it fails when the page is in Chinese.

**Comment by leodream** [comment]
Thanks for the response.

Confirmed that 

- the preferred language is set to English in both browser setting and the twitter account setting
- tried with incognito/private mode (without login to twitter), same behavior

> Twitter doesn't provide enough clues to let Vimium C know the arrow icons mean "next/previous" (for web-extension code, there's no way to check whether an icon "looks like arrow" or not).

Indeed, I was surprised when I first noticed [[]] worked in that page using Chrome.

> The only useful point is title of the 2 icons. So during my tests, on twitter in English goNext works, but it fails when the page is in Chinese.

I cannot find any goNext from the F12 console of that page, and still cannot get [[]] work after adding goNext to the "Next Patterns" configuration in Firefox.

**Comment by gdh1995** [comment]
Um, the `goNext` above means the Vimium C command.

The `[title]` is here, and I wonder what it is on your Chrome and Firefox:
![image](https://user-images.githubusercontent.com/5547703/155712750-36956660-54fb-49b3-9a92-1d0ffee14551.png)

**Comment by leodream** [comment]
Both shows "**Previous slide**". 
chrome:
![chrome](https://user-images.githubusercontent.com/2774809/155734152-7f3b45ea-ddfe-46a2-85c2-76707623bd71.png)

firefox:
![firefox](https://user-images.githubusercontent.com/2774809/155734174-e3d4159e-5f79-4f1f-98c9-0228b169ec27.png)

Also checked with newly installed Firefox on Windows, same result -- looks like it has nothing to do with platform and other addons.

**Comment by gdh1995** [comment]
Okay, I'll take a try in days.

**Comment by gdh1995** [comment]
Hello Vimium C v1.97.0 has been published on Firefox Add-ons, and you may take a try.

**Comment by leodream** [comment]
The issue persists on Vimium C [1.97.0] Firefox 98, Linux.

**Comment by gdh1995** [comment]
hello, v1.98.0 has been released, and you may take a try.

**Comment by gdh1995** [comment]
Hello, Vimium C v1.98.2 for Firefox has been published, and you may take a try.

**Comment by leodream** [comment]
Both Chrome and Firefox cannot go to the next image with "]]" with 1.98.2

**Comment by gdh1995** [comment]
Hello, I added some new logic in Vimium C v1.99.0 to solve twitter images support, and up to now the version has been available on Firefox Add-Ons, so you may take a try on Firefox.

**Comment by leodream** [comment]
Works perfectly. Thank you.
