### ISSUE TITLE
FR: Save Settings in a dotfile (`.vimiumcrc`)

### ISSUE THREAD

**Issue by chrisgrieser** [gdh1995/vimium-c#563]
It's more of a question, but I couldn't find it in the wiki or by browsing the files from the extension:

Are current settings stored somewhere in the system? I'd like to sync them manually by adding them to my dotfile github repo, but can't do so since I can't find their location.

**Comment by gdh1995** [comment]
It's saved through APIs from your browser, so there's no obvious text files to store settings. You may export settings manually.

**Comment by chrisgrieser** [comment]
well, in that case I'd like to change this question into a Feature Request to save the settings as a dot file :)

**Comment by gdh1995** [comment]
It's impossible to do so. Browsers have never provide APIs to silently read / write a files without opening a `Select File` dialog.
