### ISSUE TITLE
autoOpen key mapping doesn’t work when using vimium://urls.

### ISSUE THREAD

**Issue by PiperSuave** [gdh1995/vimium-c#564]
**Describe the bug**

autoOpen key mapping doesn’t work when using vimium://urls.

**To Reproduce**

Assume the following “Custom search engines” : 

A: https://www.google.com/search?q=$S    Google Search
B: https://www.bing.com/search?q=$S        Bing Search
C: https://search.brave.com/search?q=$S  Brave Search
TEST: [vimium://urls/A|B|C:$S](vimium://urls/A%7CB%7CC:$S)     ALL SEARCH

And the following “Custom key mappings” :

map ,A autoOpen keyword="A"        copy
map ,B autoOpen keyword="B"       copy
map ,C autoOpen keyword="C"       copy
map ,T autoOpen keyword="TEST" copy

Using custom search engines A, B, C in the Vomnibar works as expected (e.g. “A tornado” opens a tab with a google search for tornados).  Likewise, “TEST tornado” opens three tabs with google, bing, and brave searches for tornado.  

Also as expected if the word “tornado” is highlighted on a web page and “_,A_” is typed, then a new tab is opened with a Google search for tornado in it.  The same with “_,B_” with Bing and “,_C_” for Brave.  However, when “_,T_” is typed the following message is displayed: 

 _url     : vimium://urls/A|B|C:tornado_

rather than the expected three tabs with the search results in them.

**Browser, OS and Vimium C versions**

Browser(s): Firefox 97.0.1, Brave 1.35.104
Vimium C version 1.96.6
MacOS 12.2.1

Firefox and Brave have identical configuration files.

Thanks for your continuing work on Vimium C!

Best regards.

**Comment by gdh1995** [comment]
Hello Vimium C v1.97.0 has been published on Firefox Add-ons, and you may take a try.

**Comment by PiperSuave** [comment]
Just tested your update and it works great.  Thanks!  

Best regards.
