### ISSUE TITLE
is it possible to show tabs in fullscrean mode

### ISSUE THREAD

**Issue by Monirzadeh** [gdh1995/vimium-c#565]
is it possible to vimium-c show tabs on top similar to [this](https://chrome.google.com/webstore/detail/fullscreen-tab-bar/hlackdnjlfblchoenkpcbbophehmeijb?hl=en). it is better work for me to see tabs always on top and i can build a complete full screen workflow.
that extension has a lot of bug and not develop any more.
i am not sure is it out of scope or not. maybe it can be as another extension that design to work with vimium-c like newtab extension

**Comment by gdh1995** [comment]
The extension you mentioned looks too simple and has a bad performance when there're many running tabs.


Vimium C has no such a bar, but it supports a command named "Vomnibar.activateTabs",
which means Vomnibar will show all recently-visited tabs, and you may search for titles and URLs in them.


Vomnibar also supports:
* press PageDown and PageUp keys (or Shift+ArrowDown and Shift+ArrowUp) to show other pages of suggestions
* if you use `map xxx Vomnibar.activateTabs currentWindow`, then it only shows tabs in a current window




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "gdh1995/vimium-c"                                                                                    ***@***.***&gt;;
Date:&nbsp;Sat, Mar 5, 2022 05:22 AM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;[gdh1995/vimium-c] is it possible to sho tabs in fullscrean mode (Issue #565)





 
is it possible to vimium-c show tabs on top similar to this. it is better work for me to see tabs always on top and i can build a complete full screen workflow.
 that extension has a lot of bug and not develop any more.
 i am not sure is it out of scope or not. maybe it can be as another extension that design to work with vimium-c like newtab extension
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Monirzadeh** [comment]
i am aware of that but some time have have a bar on top or show them when i use next tab previous can be helpful

**Comment by gdh1995** [comment]
Sorry it seems this feature is not related to Vimium C's main purpose (use keyboard to trigger browser behaviors), so Vimium C won't add this feature. Besides, I have no much rest time to implement a new high-performance extension of "tab bar".

**Comment by Monirzadeh** [comment]
thank you i understand.
