### ISSUE TITLE
How to select to a symbol?

### ISSUE THREAD

**Issue by seriiserii825** [gdh1995/vimium-c#567]
Hi, thanks a lot for you chrome extension. 
I can't understand how to select in visual mode to symbol. 

I press / and search for a word. 
After i can press "ap" and select all paragraph. 
But i want to search a word, after press "l" and want to select till first "l", and press ";" to select to another symbol l. 

Exists a way to do this? 

And before you extension i used SurfingKeys. 

And it work in another way. 
When i press v, i can go to the each start of word or paragraph. 

I press v in surfingkeys 
https://i.imgur.com/Bg51gwo.png
After i press a letter from screen i can make selection to specific symbol

Thanks in advance.

**Comment by gdh1995** [comment]
In Find Mode, You may:
* press Ctrl+J/K to move selection to a next / previous match of your query word.
* press Ctrl+Shift+J/K to see (some near) matches of your query.
- browsers don't provide enough APIs to expose all matches to developers, so Vimium C can just "try to" collect matches


If you want to select a word without typing its part, you may map a key to `LinkHints.activateSelect`,
and this command will show hints for all visible "text slices".


I think one-hint-per-text-slice is enough, while one-hint-per-word is too&nbsp;messy




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "gdh1995/vimium-c"                                                                                    ***@***.***&gt;;
Date:&nbsp;Sat, Mar 5, 2022 05:09 PM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;[gdh1995/vimium-c] How to select to a symbol? (Issue #567)





 
Hi, thanks a lot for you chrome extension.
 I can't understand how to select in visual mode to symbol.
 
I press / and search for a word.
 After i can press "ap" and select all paragraph.
 But i want to search a word, after press "l" and want to select till first "l", and press ";" to select to another symbol l.
 
Exists a way to do this?
 
And before you extension i used SurfingKeys.
 
And it work in another way.
 When i press v, i can go to the each start of word or paragraph.
 
I press v in surfingkeys
 https://i.imgur.com/Bg51gwo.png
 
I press v in vimiumc
 Just one selection
 https://i.imgur.com/QMuG0JV.png
 
Thanks in advance.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by seriiserii825** [comment]
Thanks for response.
yv - LinkHints.activateSelect
