### ISSUE TITLE
After restoring a tab in the new window, no focus in the main frame

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#568]
macOS 12.2.1   |   Chrome 99

Reproduction Steps:
1. Close the only tab in a window
2. Trigger `restoreTab` to restore it
3. The closed tab reopen in a new window, but none of Vimium-C's commands could be triggered, including `mainFrame`, till I use the pointer to click blank space to reclaim the focus

**Comment by gdh1995** [comment]
How did you trigger `restoreTab` when the only tab has been closed?


Do you mean you had 2 windows, and a first window with only&nbsp;one tab was closed,
so you trigger the command on a web page in a second window?




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "gdh1995/vimium-c"                                                                                    ***@***.***&gt;;
Date:&nbsp;Sat, Mar 5, 2022 05:48 PM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;[gdh1995/vimium-c] After restoring a tab in the new window, no focus in the main frame (Issue #568)





 
macOS 12.2.1   |   Chrome 99
 
Reproduction Steps:
  
Close the only tab in a window
 
Trigger restoreTab to restore it
 
The closed tab reopen in a new window, but none of Vimium-C's commands could be triggered, including mainFrame, till I use the pointer to click blank space to reclaim the focus
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gdh1995** [comment]
OKay, reproduced on Edge 98, Win10.




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "gdh1995/vimium-c"                                                                                    ***@***.***&gt;;
Date:&nbsp;Sat, Mar 5, 2022 05:48 PM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;[gdh1995/vimium-c] After restoring a tab in the new window, no focus in the main frame (Issue #568)





 
macOS 12.2.1   |   Chrome 99
 
Reproduction Steps:
  
Close the only tab in a window
 
Trigger restoreTab to restore it
 
The closed tab reopen in a new window, but none of Vimium-C's commands could be triggered, including mainFrame, till I use the pointer to click blank space to reclaim the focus
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by OnceThenEver** [comment]
> Do you mean you had 2 windows, and a first window with only one tab was closed, so you trigger the command on a web page in a second window?

That's it.

**Comment by gdh1995** [comment]
I have no much rest time recently. Maybe it's a bug, but it can also be "a feature" of Chrome. I'm not sure yet.

**Comment by gdh1995** [comment]
![image](https://user-images.githubusercontent.com/5547703/158504087-a0488126-fb18-411a-a5e4-831212363a1e.png)

This native menu item causes this issue, too. I'm not sure whether an extension can work it around or not.

**Comment by OnceThenEver** [comment]
If the reopened tab is in the blacklist of Vimium-C, then the default action of _space,_ scrolling one page, has no effect too. So it's Chrome's feature (or bug).

**Comment by gdh1995** [comment]
Hello, I noticed you forked Vimium C, then you may fetch the latest commit a1de8e3e and build it by yourself. I've made a try to bypass this issue on Chrome.

**Comment by gdh1995** [comment]
Hello, Vimium C v1.98.3 has been published, and you may take a try. It should have solved this issue, by doing some extra actions when a window gets restored.

**Comment by OnceThenEver** [comment]
Verified.
