### ISSUE TITLE
Problems with going to some page with russian layout

### ISSUE THREAD

**Issue by HappyCthulhu** [gdh1995/vimium-c#569]
**Describe the bug**

I recorded video of this bug: https://youtu.be/qgj71W-hoGA

Hi, im using english and russian keyboard layouts. 
In past days, when i switched from en to ru layout, i pressed "А" (same key as english "F"), Vimium showed me, what keys i should press. For example: Vimium show me "EF", i pressed "УА" (same keys on russian layout) and get to page, that i was needed. Now i cant reproduced it, Vimium cant catch that shortcuts. 

I saw this issue: https://github.com/philc/vimium/issues/953
And add this to my Vimium C profile: https://github.com/philc/vimium/wiki/Key-Mappings#russian-language-keyboards

And russian layout working if concerns Vimium functions like showHelp, scrollDown, etc. But when it comes to function, thas allows me to go through pages using Vimium-generated shortcuts, it crashes.  

I understand, that this bug is hard to explain. Let me now if u cant understand my bug report.

**To Reproduce**

- switch from en to ru layout
- press "f"
- try to go on some page

**Browser, OS and Vimium C versions**

- Browser name: Google Chrome
- Browser version: Version 97.0.4692.99 (Official Build) (64-bit)
- Vimium C version: Version 1.96.6. 
- OS name and version: Ubuntu 20.04, Windows 10

**Comment by gdh1995** [comment]
Sorry for my delay of this response. Do you mean you can not press "`УА`"  to trigger a hint mark of `EF` when Vimium C is in `LinkHints` mode?

Then you may need `mapKey`. As indicated by https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout#an-example-for-cyrillic-layout-russian-and-ukrainian , `mapKey A B` will make Vimium C treat a keyboard press of `A` as `B`.

Vimium C has some special improvements about `mapKey`: https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout#mapkey-directive . So you may limit the scope of a `mapKey` rule only inside `LinkHints` by writing `mapKey <У:l> E`.

If you don't use pre-mode `mapKey`, then you may need to rewrite your current key mappings - with `mapKey У E` existing, `map У showHelp` won't work, but `map E showHelp` will allow `У` to show a help dialog.

**Comment by HappyCthulhu** [comment]
thanks, that link helped me!
https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout#mapkey-directive

**Comment by HappyCthulhu** [comment]
thanks, that link helped me!
https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout#mapkey-directive
