### ISSUE TITLE
autoOpen does not work on selected text at Microsoft Edge 99.0.1150.39 

### ISSUE THREAD

**Issue by leviathan-n** [gdh1995/vimium-c#570]
**Describe the bug**
select some text then input the mapping keys of autoOpen, and nothing happend,  but on chrome 99.0.4844.51 and firefox 98.0, after doing same action, it will open a google search web with selected text as query.

**To Reproduce**

**Browser, OS and Vimium C versions**

- Browser name: microsoft edge
- Browser version: 99.0.1150.39
- Vimium C version: Vimium C [1.96.6](https://github.com/gdh1995/vimium-c/blob/master/RELEASE-NOTES.md#1966)
- OS name and version: windows 10 and windows 11

**Comment by gdh1995** [comment]
Can not reproduce this on a fresh profile of Edge. Please test these:
1. If the text you mentioned was in an "input box", please try select normal text and then trigger mapped keys
2. If you're using a non-English keyboard layout, or the key mapped to `autoOpen` is "long", please try an English letter
- 1. for example, `map b autoOpen` and then try to press the <kbd>B</kbd> key
3. Disable all other extensions on `edge://extensions`, refresh tabs and then retry
4. Go to `edge://settings/appearance`, disable `Show mini menu when selecting text`, and then retry.

**Comment by leviathan-n** [comment]
>

**Comment by leviathan-n** [comment]
> Can not reproduce this on a fresh profile of Edge. Please test these:
> 
>     1. If the text you mentioned was in an "input box", please try select normal text and then trigger mapped keys
> 
>     2. If you're using a non-English keyboard layout, or the key mapped to `autoOpen` is "long", please try an English letter
> 
> 
>     * 1. for example, `map b autoOpen` and then try to press the B key
> 
> 
>     3. Disable all other extensions on `edge://extensions`, refresh tabs and then retry
> 
>     4. Go to `edge://settings/appearance`, disable `Show mini menu when selecting text`, and then retry.

mini menu is the answer, thx a lot

**Comment by gdh1995** [comment]
Then, when `Show mini menu when selecting text` is enabled, you need to press <kbd>Esc</kbd> before triggering any Vimium C mappings, when you select some text using a mouse.
