### ISSUE TITLE
Return unpinned tab to its original position

### ISSUE THREAD

**Issue by elig0n** [gdh1995/vimium-c#574]
When pinning a tab it goes to the top in the list of tabs.
Unpinning it back still keeps it at its place.
It could be nice if it could return to its previous index location (especially getting it back to its tree position when using TreeStyleTab and similar addons)

**Comment by gdh1995** [comment]
Chrome doesn't remember an "original" position for a pinned tab, so this is hard to implement.

And, it's "impossible" to define "original positions" - given 5 tabs: A, B, C, D, E, and pin `D`, what's the "original position":
1. if move `C` after `E`
2. if move `C` right and create a new tab before `E`
3. if switch `B`  and `E`, pin `C`, create a new tab after `E`, and then unpin `C`
4. ...

So, I won't try to implement such an idea.

You may use `map xxx sortTabs sort="host,recency"` in Vimium C to sort all tabs.
