### ISSUE TITLE
Vomnibar do not list bookmarks from folders except "Bookmark's Toolbar"

### ISSUE THREAD

**Issue by mizzunet** [gdh1995/vimium-c#577]
**Describe the bug**

I have few bookmarks in "Bookmarks toolbar" and some in "Other bookmarks". 
But items in the later one, do not show on Vomnibar when typing it's name or url or anything

**To Reproduce**

1. Bookmart one site as Toolbar
2. Bookmark another one as in Other
3. Open Vomnibar
4. Type the url/title of each of these bookmarks
5. See that Bookmark in "Other" does not show up

**Browser, OS and Vimium C versions**

- Browser name: Firefox
- Browser version: 98
- Vimium C version: 1.96.6
- OS name and version: Artix

**Comment by mizzunet** [comment]
I'm sorry, I was wrong

**Comment by gdh1995** [comment]
Um, would you mind talking about what mistakes caused you thought Vomnibar failed?

**Comment by mizzunet** [comment]
> Um, would you mind talking about what mistakes caused you thought Vomnibar failed?

The site I bookmarked wasn't bookmarked for some reason. So, it didn't show up in Vomnibar. I checked bookmark only after is Issue is made.

**Comment by mizzunet** [comment]
@gdh1995 BTW, why can't I use Vimium's custom CSS themes for this extension? How can I make compatible?
https://github.com/ysjn/vimium-simply-dark/blob/master/vimium-simply-dark.css
https://github.com/dracula/vimium/blob/master/vimium-dracula.css

**Comment by gdh1995** [comment]
Vimium C uses shorter names for its UI elements, so you need to replace CSS selectors in those examples. https://github.com/gdh1995/vimium-c/wiki/Style-the-UI-of-Vimium-C-using-custom-CSS#finding-element-classes-and-ids

![image](https://user-images.githubusercontent.com/5547703/158951057-e6819071-6543-44fe-a9c0-32fb56e2acf8.png)

**Comment by mizzunet** [comment]
Cool, thanks (:
