### ISSUE TITLE
Search includes "+"

### ISSUE THREAD

**Issue by mizzunet** [gdh1995/vimium-c#578]
**Describe the bug**

I have `bk: https://1lib.in/s/%s Books` as a search engine. But when I search by Vomnibar, the spaces becomes +'s on the site
![image](https://user-images.githubusercontent.com/10193999/158936381-423e45f9-470d-4051-bf72-aca127c11b0c.png)
![image](https://user-images.githubusercontent.com/10193999/158936439-b5004692-9e56-42fe-bda3-c0c33480000c.png)

But if I search from the site from itself, the URL looks like this
![image](https://user-images.githubusercontent.com/10193999/158936415-4a5685fe-7fd0-44fc-8d88-7405c9076587.png)

**To Reproduce**

1. Make this as a search engine
2. Search in it

**Browser, OS and Vimium C versions**

- Browser name: Firefox
- Browser version: 98
- Vimium C version: 1.96.6
- OS name and version: Artix

**Comment by gdh1995** [comment]
`bk: https://1lib.in/s/${s:%20} Books` will help.

**Comment by mizzunet** [comment]
Thanks
