### ISSUE TITLE
Actions on multiple selected tabs

### ISSUE THREAD

**Issue by balta2ar** [gdh1995/vimium-c#58]
It looks like Vimium-C does not support tab selection. Relativetly recently (probably this year), both Firefox and Chromium were added a feature where you can select multiple tabs with Shift and do an operation on all tabs at once, for example you can select many tabs and close or reload them at once. When I select many tabs and press `x` to close, or `r` to reload, only the current tab is closed or reloaded. I guess it could be nice to be consistent with the browser behaviour and execute shortcut on all selected tabs.

**Comment by gdh1995** [comment]
Yes, it doesn not consider about the selected status. But it's mainly because it support "count prefix" to achieve almost the same functionality. For example, if press "`5x`" (press down <kbd>5</kbd>, release the key, and then press <kbd>x</kbd>), Vimium C will close 5 tabs, a current tab and 4 tabs at its right, and for "`-5x`", the closed will be the current one and 4 at its left.

Besides, it's too inconvenient if a user have to "select" some tabs using a mouse and then press keyboard keys to trigger shortcuts.

**Comment by balta2ar** [comment]
Count prefix is a great feature, but supporting multiple selected tabs is more about being aligned with the browser native functionaliy, providing smooth user experience. Yesterday it was my first time that I pressed <kbd>x</kbd> and I was surprised that <kbd> didn't work as I expected. I may be the first user who noticed that, maybe others will find it out as well over time.

> too inconvenient if a user have to "select" some tabs using a mouse and then press keyboard keys to trigger shortcuts

Sorry, that's my primary workflow and I have never thought it was inconvenient before you said so :) One downside with "count prefix" that I noticed is that you don't see the tabs you're about to close. In Firefox tabs do not shrink as in Chrome. The tab width stays constant and instead you get to see only a portion of the tabs, but you can scroll them horizontally using mouse wheel. That's what I do. I activate my first tab, then I scroll lots of tabs to the right/left, and while I do that, I see the favicons and part of the titles of the tabs, so I see what's in my selection. Then I press Shift and click on some tab, finishing it with Ctrl-W to close the groups of tens of tabs at once. For me, it's very convenient, visual and interactive.

The point of this issue is to bring the inconsistency that I have noticed to your attention. Personally, I'm fine with the current behaviour as long as I can press Ctrl-W or Ctrl-R, but I thought you might wanted to adjust Vimium-C to match native behavior. So this is purely informational, a "nice to have" feature, but if your vision is different, I can understand, feel free to close the issue. I highly appreciate your time and your effort you've put into this plugin in any scenario.

**Comment by gdh1995** [comment]
Looks reasonable.

Although there've been some discussions about it like https://github.com/philc/vimium/issues/3283 , now I agree with you that it should be "consistent" with browsers.

But, to be honest, it will be a very hard task if to support noncontinuous selected tabs in all commands of Vimium C. So I prefer to add it only for "`removeTab`". This feature may be ready on version 1.77.* (one ~ two months).

I also suggests you try the Vomnibar in tab mode (e.g. `map T Vomnibar.activateTabSelection currentWindow`), and then you can: select a tab and press <kbd>Shift+Enter</kbd> to remove it, and then select another tab to remove.

**Comment by balta2ar** [comment]
> removeTab command should ignore other selected tabs if the count prefix is not 1

Yeah, it's not clear how to interpret "count prefix" when mutiple tabs are selected. I guess one of the options is to show an error to the user saying "Can't work with mutiple tabs and count prefix". Or maybe just ignore the action.

> I also suggests you try the Vomnibar in tab mode

You probably meant `Shift-Delete`, not `Shift-Enter`?

I've tried and as far as I understand, it's not exactly the same: the workflow here is that I 1. select a tab 2. press `Shift-Delete` for each tab. 3. Do 1 & 2 repeatably. With the method above, I could just select tabs and press `ctrl-w` once. I couldn't find a way to select mutiple tabs in Tab mode and then press `Shift-Delete` once, please correct me if I missed anything. This doesn't disparage Tab mode in anyway though -- one of the reasons that I switched to Vimium-C is that it supports closing tabs with `Shift-Delete` shortcut (awesome feature, thank you!).

**Comment by gdh1995** [comment]
Um, yes what I meant is "`Shift-Delete`", sorry for the typo.

The last weekend I was too tired to update Vimium C, so I may write and release a new version in this week.

**Comment by gdh1995** [comment]
Hello, I've made a test version and you may take a try:
* 
[vimium_c-1.76.3-chrome.zip](https://github.com/gdh1995/vimium-c/files/3461471/vimium_c-1.76.3-chrome.zip)
[vimium_c-1.76.3-fx.zip](https://github.com/gdh1995/vimium-c/files/3461472/vimium_c-1.76.3-fx.zip)
* you need to map `removeTab` like this in order to close those highlighted:
  * `map x removeTab highlighted` will close all highlighted including the current one
  * `map x removeTab highlighted="no-current"` will always skip a current tab

**Comment by gdh1995** [comment]
Version 1.76.4 has been released.

**Comment by dvkndn** [comment]
@gdh1995 is there a way to "close other tabs" (keep current tab)?

**Comment by gdh1995** [comment]
@dvkndn There's an advanced command named "closeOtherTabs":
* by default, it closes all other tabs
* if giving `filter="url"`, then it will only close tabs which have a same URL with the current tab.

**Comment by dvkndn** [comment]
Thank you!
