### ISSUE TITLE
Blank new tab for not to be focused on address bar

### ISSUE THREAD

**Issue by mizzunet** [gdh1995/vimium-c#580]
**What command or commands**

Tridactyl has a similar feature that provides New Tab, so the cursor not focused on address bar. So, keybinding would work.
![image](https://user-images.githubusercontent.com/10193999/158961591-a42646f5-aab6-4c2a-b867-b3c6ef390363.png)
![image](https://user-images.githubusercontent.com/10193999/158961606-88481038-edb7-4265-b21c-7d58b658d230.png)

Would you be able to make this for Vimium C?

Thanks

**Comment by gdh1995** [comment]
It's in a plugin of Vimium C: `NewTab Adapter` in https://github.com/gdh1995/vimium-c-helpers/tree/master/newtab

**Comment by gdh1995** [comment]
Vimium C once integrated this feature of overriding native NewTab page, but this feature can not be disabled dynamically, so quite a few users dislike it. Then I split it into a new extension.

A simpler way is to avoid Ctrl+T / click the `+` button on tab bar, but always use keys of Vimium C to create tabs. You may map a key like `Alt+T` to `create new tab` following https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box#global-shortcuts

**Comment by mizzunet** [comment]
Got it

**Comment by mizzunet** [comment]
I see that `newtab.html` prefers dark mode.
`style media="(prefers-color-scheme: dark)">body{background:#000}</style>`

But it is white
![image](https://user-images.githubusercontent.com/10193999/158963427-caca63df-2b67-4172-aadc-24cba21b0b47.png)

**Comment by gdh1995** [comment]
You may write your own `newtab.html` and make `New tab URL` on Vimium C Options point it.

The `(prefers-color-scheme: dark)` is a condition (do something if dark) but not a request of enabling dark mode.

If you want to force a dark page, you may use `<meta name="color-scheme" content="dark">` just like https://github.com/gdh1995/vimium-c-helpers/pull/18/files
