### ISSUE TITLE
[Feature request] LinkHints cycle across results in the whole page

### ISSUE THREAD

**Issue by damscal** [gdh1995/vimium-c#581]
Hello Dahan, thank you for your great work. I'm writing as a follow-up of https://github.com/philc/vimium/issues/2420#issuecomment-1072005449

The method you implemented is very interesting for specific use cases.

As a more general solution, it would be great if it was possible to cycle across the filtered results of LinkHints (i.e. using tab key) through the whole page, scrolling into view when necessary.

Best wishes,
dam

**Comment by gdh1995** [comment]
Um, I'm not interested in "showing a part of hints of whole page and providing a way to scroll and see next parts", but in Vimium C there're indeed some tricks to "scroll and see hints".

In Vimium C's `LinkHints`, you may use arrow keys and PageDown/PageUp to scroll pages, and then press `Tab` to re-init LinkHints. `Tab` is used to re-init LinkHints when:
- 1. there're no typed characters as the matching prefix
- 2. and the option of `Use the link's name and characters for link-hint filtering` is disabled

You may use `LinkHints.click` to cycle across matched elements, by:
```
# "hover" to avoid click actions
# `offset:cur` means to select elements "near a current focused / active element"
# `index:0` means to select a next element nearby, and `index:-1` means a previous element
map g LinkHints.click action="hover" \
  direct="element" match="input" \
  directOptions={"search":"doc","offset":"cur","index":0,}
```
