### ISSUE TITLE
[Feature request] LinkHints with variable CSS selector

### ISSUE THREAD

**Issue by damscal** [gdh1995/vimium-c#582]
**What command or commands**

LinkHints

**How should a feature do**

Users activate LinkHints. Then they press a key combination (e.g. Alt+S). This key combination acts as a switcher. Now if the users type a CSS selector (e.g. "div.button") LinkHints selects all links that match this CSS selector. If the users press the switcher again, they can further normally filter the results typing links text.

Example:

if user types:
`fContri<a-s>span.Label<a-s>butor`

then Vimium C should:

select all links matching the text `Contributor` and the CSS selector `span.Label`.

Thank you for the great work
Best wishes
dam

**Comment by gdh1995** [comment]
What do you want to do after LinkHints shows hints for matched elements? Just to see them?

**Comment by damscal** [comment]
> What do you want to do after LinkHints shows hints for matched elements? Just to see them?

Sorry for not specifying earlier,
I was thinking possibly:
- cycle through them with tab (forward) and shift+tab (backward)
- click the focussed one with Enter
- OR exiting the command with Esc

**Comment by gdh1995** [comment]
But css selectors can not be guessed easily, so I think this feature is too hard to use - you should prepare such selectors and save them into key mappings:
map xxx LinkHints.activate match=".btn"


see the first wiki page for documents of match/exclude/clickable parameters.



---Original---
From: ***@***.***&gt;
Date: Sat, Mar 19, 2022 02:13 AM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] [Feature request] LinkHints with variable CSS selector (Issue #582)




  
What do you want to do after LinkHints shows hints for matched elements? Just to see them?
  
Sorry for not specifying earlier,
 I was thinking possibly:
  
cycle through them with tab (forward) and shift+tab (backward) 

click the focussed one with Enter 

OR exiting the command with Esc 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by damscal** [comment]
Thank you,
yes I had looked into the solution you explained
Of course this would be an advanced use case, yet it shouldn't be difficult to remember a few simple CSS selectors such as "a" or "button", correct?
I imagine the feature would be very powerful in allowing more advanced filtering without having to manage a long list of custom mappings. Also, even with a long and complicated list, the possibilities would be rigid and limited, while with this new approach they would be flexible and endless, more coherent with Vim philosophy :)

Best wishes
dam

**Comment by gdh1995** [comment]
If your selectors are simple, then you can add them into key mappings. For example, such mappings will also help.
```
map Fa LinkHints.activate match="a"
map Fbtn LinkHints.activate match=".btn,button"
map Fin LinkHints.activate match="input,textarea"
```

You just need to press an extra `Esc` and `F`, but this way doesn't need any `Backspace` keys.

**Comment by groutoutlook** [comment]
> If your selectors are simple, then you can add them into key mappings. For example, such mappings will also help.
> 
> ```
> map Fa LinkHints.activate match="a"
> map Fbtn LinkHints.activate match=".btn,button"
> map Fin LinkHints.activate match="input,textarea"
> ```
> 
> You just need to press an extra `Esc` and `F`, but this way doesn't need any `Backspace` keys.
> 
> As a result, I don't think this feature does worth, considering that it requires quite a few big changes and a complete set of behavior design.

This helps me a lot, should also be paraphrased as linkHints match with certain string on elements as well.
