### ISSUE TITLE
[Feature request] Retain the current search terms when using LinkHints.activateWithQueue

### ISSUE THREAD

**Issue by damscal** [gdh1995/vimium-c#584]
**What command or commands**

`LinkHints.activateWithQueue`, with the options `Use the link's name and characters for link-hint filtering` and `Require "Enter" when filtering hints` enabled

**How should a feature do**

When a user has done such steps:

1. init LinkHints.activateWithQueue
2. input search terms, for example `my keyword`
3. tab through filtered results
4. press `Enter`

then Vimium C should do:

1. show hints for all clickable elements
2. filter the hints, showing only those related to `my keyword`
3. highlight the focussed hint
4. click the highlighted element and open it in a new tab
5. **go back to (3.) instead of going back to (1.)**

This would basically save the user from having to type `my keyword` again. It would be useful for example when the users need to click multiple similar buttons, or if  they need to click the same button several times.

Best wishes,
dam

**Comment by gdh1995** [comment]
Sounds useful.

**Comment by gdh1995** [comment]
hello, v1.98.0 has been released, and you may take a try.

`map xxx LinkHints.activate retainInput`
