### ISSUE TITLE
Labels to move between visible tabs with `f`

### ISSUE THREAD

**Issue by kauesena** [gdh1995/vimium-c#585]
It would be nice if pressing `f` assigned labels also for the visible tabs in the tab bar so that we could press the key sequences of one of those labels and open the respective tab.  

**Browser and OS**
- Browser name: Firefox 98.0.1
- OS name: Arch Linux

**Comment by gdh1995** [comment]
`LinkHints` is only designed for web page content. You may trigger the `Vomnibar.activateTabSelection` command to see tabs.
