### ISSUE TITLE
Not working at chrome pages

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#588]
macOS 12, Chrome 99, Vimium-C 1.97.0

![Screen Shot 2022-03-28 at 09 12](https://user-images.githubusercontent.com/66708845/160310405-5d1fc8b8-8e88-4550-b955-edb049d39aa7.png)
The original options disappeared, and Vimium-C doesn't work at `chrome://` pages even I toggled on the required flag.

**Comment by gdh1995** [comment]
Sorry it's a bug of building scripts. Will fix it in a following version.

**Comment by gdh1995** [comment]
hello, v1.98.0 has been released, and you may take a try.

**Comment by OnceThenEver** [comment]
Issue fixed.
