### ISSUE TITLE
How to right click for Google Drive interface and make a webpage receive ESC keys 

### ISSUE THREAD

**Issue by gilbh** [gdh1995/vimium-c#589]
Hi,

It would be nice to get the right click menu in Google Drive:
![image](https://user-images.githubusercontent.com/39532610/160313208-b1c59e84-aea8-44c9-b229-aad1053cc16b.png)

Or is there such a feature already?

This plugin is brilliant! Keep up the good work!

Thanks
Gil

**Comment by gdh1995** [comment]
I'll add this feature to `map xxx LinkHints.activate button="right"`

**Comment by gdh1995** [comment]
hello, v1.98.0 has been released, and you may take a try.
```
# will show a popup menu at an element's center
map xxx LinkHints.activate button="right" xy="0.5,0.5"
```

**Comment by gilbh** [comment]
Thanks. I will try.

**Comment by gdh1995** [comment]
Any new inconvenience?

**Comment by gilbh** [comment]
Yes, this works great!! Fantastic.

Unrelated: on gmail, if I have the "Labels" list open in `Insert mode` and I press `<Esc>`, the list will stay hanging and I cannot close it with keyboard. (The `<Esc>` switches to `Normal mode` but it would be great to close the list as well).

Thanks again for all the good work.

**Comment by gdh1995** [comment]
There're some different ways:

A naive but easy to use way is: add `.bqf` into `Compatibility of Escape` on Vimium C Options. But this may fail when GMail updates its source code and the classname changes in the future.

The second way is `passNextKey`. With `map <f2> passNextKey`, you may use `<f2>` to trigger `passNextKey` (even when) in insert mode, and then a following `<esc>` will be ignored by Vimium C and make GMail hide the menu. `passNextKey` has a counter, and when command count is 1, it will only pass one (composed) key.

Another way is to simulate `Escape` keyboard events:
```
map <v-de> dispatchEvent
run <c-]:i> #key=Escape%2C27+(de)-de
```

Then in insert mode `Ctrl+]` will make Vimium C dispatch a simulated `Escape` event, and GMail does hide the label panel on the key.

====

BTW. the above ways assume the "label list" is such a panel:
![image](https://user-images.githubusercontent.com/5547703/169110924-da46c6b3-2122-47e5-96ba-ff90d3e99818.png)

**Comment by gilbh** [comment]
Sorry for taking so long to reply. (Please consider re-opening).

I tried 
```
map <f2> passNextKey
```

-- and indeed I see the 
![image](https://user-images.githubusercontent.com/39532610/176741256-6db1eb4c-32d7-4322-b2fd-b831a374ae01.png)
label, but then, when I click `Esc`, it does not close the panel ... maybe I am doing something wrong?

The third method of `c-]` does not work for me. Nothing happens when I click it ... 

Thanks.

**Comment by gilbh** [comment]
Well, returning the focus to the input box fixed the issue. But it means I need to "manually" move the mouse back to the input box every time ... I get it that it is a difficult scenario, you might not have any other option if the focus is lost ....

**Comment by gdh1995** [comment]
The input box becomes focused immediately when the label panel shows, so why you need to `return focus to it`?

If you worry about a first `<esc>` blurs it, then you may try
> adding `, .bqf` or `, [ignoreesc=true]` into `Compatibility of Escape` (note it's a list of single selectors joined with `,`)

This means when Vimium C finds an `<esc>` it will always pass it to a page firstly, and then wait a small while before blurring it anyway.

**Comment by gdh1995** [comment]
There're some ways to re-focus a recently focused element:
* `focusInput` will show hints for all visible input boxes and auto select a recently focused element
* when nothing is focused, `switchFocus` and `simBackspace` will re-focus a visible and recently focused element
  * if a a recently focused element is not visible, these commands will try to make it scroll into view (but not focus it)

And if you remove `:i` from `<c-]:i>` and use a key mapping like:
```
map <v-de> dispatchEvent
run <c-]> #key=Escape%2C27&match=[ignoreesc=true]+(de)-de
```

Then `Ctrl+]` will still simulate a `ESC` key even if nothing is focused, and it will:
1. try to find an element matching `[ignoreesc=true]`
2. auto use a recently clicked or focused element.
3. so, during my test it can make the list hide

**Comment by gilbh** [comment]
Thanks for the detailed answer!

Adding `, [ignoreesc=true]` did the trick, and I will try to see if this usage works well in other contexts. For now, it's great!!

Sorry for the basic question:
When you mention commands like `focusInput`, `switchFocus`, and `simBackspace` -- how do I activate them? I tried `:` while in `normal` but that did not work.

I am just trying to learn more about your project and how it works.

Thanks again!

**Comment by gdh1995** [comment]
`[ignoreesc]` is only for GMail and even limited on GMail's label list box. If you want so on other websites, you may need to add other appropriate CSS selectors.

Those commands can be mapped by yourself, through adding rules in `Custom key mappings` on Vimium C Options. And there're some key mappings enabled by default:
```
map gi focusInput
map <f1> simBackspace
map <f2> switchFocus
map <s-f1> switchFocus
```

**Comment by gilbh** [comment]
Great. Really helpful. I am not 100% sure, but I think it might also work on Google Drive. 

Thanks a lot for the help.
