### ISSUE TITLE
Clear (or delete) whole line in Vomnibar shortcut

### ISSUE THREAD

**Issue by ww7** [gdh1995/vimium-c#59]
On Win `ctrl+backspace` and on Mac `cmd+backspace` will delete all chars from cursor to line start.
Is a possible to have this in Vimium-C ?

**Comment by gdh1995** [comment]
In my test, all of Chrome, Notepad, CMD on Windows 10 x64 use "Ctrl+Backspace" to delete a word (from cursor to its left word boundary), and Vomnibar too.

**Comment by ww7** [comment]
Sorry.
Not work on Firefox on Mac.
But works on Chrome on Mac and Firefox on Windows.

**Comment by gdh1995** [comment]
What's the shortcut you said "not work with Firefox on Mac"? Is it `Ctrl+Backspace` for deleting a word, or for deleting a line?

**Comment by ww7** [comment]
On the Mac in text fields we have next shortcuts
`Opt(Alt)+Backspace` — delete a word
`Cmd(not a Ctrl)+Backspace` — delete a line

On the Chrome (mac) in Vomnibar `Opt+Backspace` and `Cmd+Backspace` delete a word
On the Firefox (mac) this shortcuts not work

**Comment by gdh1995** [comment]
I have no Mac, so the code can only be tested on Windows, and behavior on Mac is from my guesses... This is why the shortcuts behavior wiredly on Mac. I'll try to borrow one and fix them.

**Comment by gdh1995** [comment]
Hello, I've made a test version and you may take a try:
* [vimium_c-1.76.3-chrome.zip](https://github.com/gdh1995/vimium-c/files/3459363/vimium_c-1.76.3-chrome.zip) [vimium_c-1.76.3-fx.zip](https://github.com/gdh1995/vimium-c/files/3459364/vimium_c-1.76.3-fx.zip)
* on Firefox, the feature of deleting a word is not JS-acccessible
  * so on Firefox & Windows, I map `Alt+Backspace` to delete a whole line of Vomnibar input
  * and on Firefox & Mac, the `Ctrl+Backspace` has to do nothing.
* If you get any idea about such shortcuts or find any other key is lacking, please do me a favor and share it here.

**Comment by ww7** [comment]
Sorry for late response, test version works on Firefox, thanks!

**Comment by gdh1995** [comment]
Version 1.76.4 has been released.
