### ISSUE TITLE
Switching between modes using key shortcuts

### ISSUE THREAD

**Issue by gilbh** [gdh1995/vimium-c#590]
Is it possible to switch, say, from `Visual` to `Insert` by clicking `i` (or something else), without needing to go first through `Normal` with `Esc`?

**Comment by gdh1995** [comment]
Currently not, but there're some tricks which may help:

Firstly, `<c-[>` works almost the same as `<esc>` inside Vimium C, so you may press `Ctrl+[` and then `i` to exit VisualMode and enter InsertMode.

Secondly, there's a way to press a same key twice to do so:
```
# `:v` only works in VisualMode; `:n` only in NormalMode
mapKey <c-]:v> <esc>
mapKey <c-]:n> <v-i>
map <v-i> enterInsertMode
```

Detailed usages of `mapKey`: https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout#pre-mode-mapkey

**Comment by gdh1995** [comment]
BTW, I don't think this case is so useful that I should add a new feature for it.

**Comment by gilbh** [comment]
> Currently not, but there're some tricks which may help:
> 
> Firstly, `<c-[>` works almost the same as `<esc>` inside Vimium C, so you may press `Ctrl+[` and then `i` to exit VisualMode and enter InsertMode.
> 
> Secondly, there's a way to press a same key twice to do so:
> 
> ```
> # `:v` only works in VisualMode; `:n` only in NormalMode
> mapKey <c-]:v> <esc>
> mapKey <c-]:n> <v-i>
> map <v-i> enterInsertMode
> ```
> 
> Detailed usages of `mapKey`: https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout#per-mode-mapkey

Incredible! I will start implementing this right away.

**Comment by gilbh** [comment]
> BTW, I don't think this case is so useful that I should add a new feature for it.

Of course not. It already exists. Thanks!!

**Comment by gilbh** [comment]
Thank you. I will look into this.

**Comment by gdh1995** [comment]
hello, v1.98.0 has been released, and you may take a try.

When a key is mapped to `<v-***>` in Find / Visual / Vomnibar mode, then Vimium C will execute it at once.

I have also remembered there's a command of `reset` which will exit all modes (except a plain insert mode) and go back to normal mode.

So **in a future v1.98.1** this issue can by solved by:
```
map <c-a-f> <v-enter_find>
run <v-enter_find> reset+enterFindMode
```

**Comment by gilbh** [comment]
Thanks a lot!

**Comment by gdh1995** [comment]
Hello, Vimium C v1.98.3 has been published on Firefox, MS Edge and Google Chrome stores, and you may take a try.
