### ISSUE TITLE
功能请求：域名提取

### ISSUE THREAD

**Issue by leicancun** [gdh1995/vimium-c#591]
**What command or commands**

域名提取

**How should a feature do**

例如按下`alt`+`y` 从 `https://github.com/gdh1995/vimium-c` 页面中提取域名出域名 `github.com`

**Browser and OS**

- Browser name:  chrome
- OS name: win

**Comment by gdh1995** [comment]
提取后呢？打开新标签还是复制？还是填到在Vomnibar里供编辑？

**Comment by gdh1995** [comment]
https://github.com/gdh1995/vimium-c/wiki/Substitute-URLs-and-text-during-commands 理论上能从网址里抽取任意关键词，配好规则就行

**Comment by leicancun** [comment]
> 提取后呢？打开新标签还是复制？还是填到在Vomnibar里供编辑？

复制到剪贴板就好了

**Comment by gdh1995** [comment]
类似于 https://github.com/gdh1995/vimium-c/issues/537 的办法：
1. 添加自定义快捷键
```
map xxx copyCurrentUrl sedKeys="0"
```
2. 添加“文字自动替换”规则
```
0@^[^:]+://([^/]*)/@$1@,matched
```

**Comment by leicancun** [comment]
> 类似于 #537 的办法：
> 
> 1. 添加自定义快捷键
> 
> ```
> map xxx copyCurrentUrl sedKeys="0"
> ```
> 
> 2. 添加“文字自动替换”规则 （帮助： https://github.com/gdh1995/vimium-c/wiki/Substitute-URLs-and-text-during-commands ）
> 
> ```
> 0@^[^:]+://([^/]*)/@$1@,matched
> ```

非常感谢，这完美的解决了我的问题！

**Comment by gdh1995** [comment]
v1.98.0 后支持了
```
map xxx copyCurrentUrl type="host"
```

**Comment by leicancun** [comment]
> v1.98.0 后支持了
> 
> ```
> map xxx copyCurrentUrl type="host"
> ```

感谢大佬！这非常棒！👍😁
