### ISSUE TITLE
How to show hints for more links in Slack

### ISSUE THREAD

**Issue by hacker-DOM** [gdh1995/vimium-c#593]
**Describe the bug**

In https://app.slack.com, when clicking the keyboard shortcut for "Open a link in the current tab":

<img width="63" alt="Screenshot 2022-03-29 at 9 33 35 PM" src="https://user-images.githubusercontent.com/18601956/160693223-47b938bc-0f2e-4161-bcb8-6475ed0409c8.png">

Only a link to the currently opened channel is showed; other channels lack links

**Browser, OS and Vimium C versions**

- Browser name: Vivaldi
- Browser version: 5.1.2567.66 (Stable channel) (arm64) 
- Vimium C version: 1.97.0
- OS name and version: MacOS 12.3

**Comment by gdh1995** [comment]
The page does not follow the well-accepted suggestions of Accessible Rich Internet Applications (ARIA), but Vimium C does, so LinkHints ignores most of its buttons and menuitems.

Please try this key mapping rule:
```
map f LinkHints.activate clickable="[aria-hidden]"
```

`clickable="[aria-hidden]"` is to make matched items not "hidden" any more. And detailed usages like the `clickable` parameter can be seen in https://github.com/gdh1995/vimium-c/wiki/Add-or-remove-hints .

**Comment by hacker-DOM** [comment]
`Tab` works great, `aria-hidden` seems to highlight quite a lot of links. Thx!
