### ISSUE TITLE
How can i change shortcut for listing records?

### ISSUE THREAD

**Issue by HappyCthulhu** [gdh1995/vimium-c#595]
Vimium has shorcuts: Alt+n/p for listing records in search line (history, tabs, bookmarks, etc) down/up. 
How can i change shortcut it to Ctrl+n/p?

**Comment by gdh1995** [comment]
By default `Ctrl+N` and `Ctrl+P` have been mapped to next/prev suggestion line, but your browser may treat such composed keys as built-in shortcuts and then block them, which will prevent Vimium C from recognizing such keys.

For example, on MS Edge 99 x64 for Win10, Vomnibar can receive `Ctrl+P`, but `Ctrl+N` always triggers a "Print" dialog of the browser.

If you want to map other keys to `Alt+N` / `Alt+P`, you may use `mapKey` in `Custom Key Mappings`. For example:
```
# Ctrl+Comma
mapKey <c-,:o> <a-j>
```

See https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout#per-mode-mapkey .
