### ISSUE TITLE
Execute shell command and pass yanked URL

### ISSUE THREAD

**Issue by mizzunet** [gdh1995/vimium-c#596]
I have `ya` key to copy current page's URL.
And a script, `playwithmpv`,
```
#!/bin/bash
URL="$@"
mpv $URL
```
Can I execute this script with sending the copied URL by the key `yap`?

**Comment by gdh1995** [comment]
No. Web-extensions like Vimium C can not call executable files or scripts on your computer. It can only do some things inside your browser.

You may:
1. create a servicec process to watch system clipboard changes, and call mpv on some conditions
2. or, create a HTTP server process, and make Vimium C send a request with the URL to it, and the the server can do everything you want


### watch clipboard changes

For the 1st trick, you may add this to `Custom key mappings` on Vimium C Options:
```
# `type="frame"` means a current iframe; or you may use `type="tab"` to copy a URL on the address bar
map xxx copyCurrentUrl type="frame" sedKeys="1"
```

and add this to `Auto substitution of various text`:
```
1@^@web+mybash://mpv/@
```

Then Vimium C will copy text like `web+mybash://mpv/file:///C:/` to your system clipboard.

### HTTP server

Vimium C has no command to create a HTTP request, but you may run any JS code:
1. create a bookmark, with title="v:run-mpv" url="javascript:..."
  1. the `javascript:...` should create a `XHR`/`fetch` to `http://localhost:<port>/...`
  2. if you want to bypass some HTTPS security limits, you may create an iframe and build a POST request inside it
2. add to `Custom key mappings`
```
# run js on a current iframe
map xxx openBookmark title="v:run-mpv"
# run js on a top frame
map xxx openBookmark title="v:run-mpv" reuse="current"
```

**Comment by mizzunet** [comment]
Thank you very much. I'll see the first option.

Currently, I set keybinding in Sway config to run the following, 
```
FOCUS=$(swaymsg -t get_tree | jq -r '..|try select(.focused == true)' | jq ."app_id")
MPV_ARGS="--speed=2.5"
TIME="0.8"

if [[ $FOCUS == '"firefox"' ]]; then
    wtype yy
    sleep $TIME
    URL=$(wl-paste)
    shopt -s nocasematch extglob
    notify-send -u low 'Video will play with mpv' -t 3000
    mpv $MPV_ARGS $URL 
else
    notify-send -u low 'Firefox is not focused' -t 3000
fi
```
