### ISSUE TITLE
[Question] 模拟点击的实现

### ISSUE THREAD

**Issue by Higurashi-kagome** [gdh1995/vimium-c#598]
您好。最近我尝试使用 JS/Jquery 模拟点击[微信读书](https://weread.qq.com/)阅读页底部的下一章按钮（为了写一个浏览器扩展）：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/161391300-5f5f2533-b0da-41b8-b1e6-d405bee97a69.png)

</details>

发现 JS/Jquery 的 click() 函数都没能触发翻页。注意到 Vimium-c 有着很强的模拟点击能力（F 加其他按键实现跳转），相信可在这里找到解决方案，所以简单地看了一下 [run_keys.ts](https://github.com/gdh1995/vimium-c/blob/master/background/run_keys.ts) 和 [key_handler.ts](https://github.com/gdh1995/vimium-c/blob/master/content/key_handler.ts)，意识到就我现在的水平而言，一时半会儿是读不懂的。所以到这里来请教，希望能够找到模拟点击该按钮的方法，或许您能够提供一点思路，或者是帮助限定源码范围，以帮助我加快源码的阅读。

非常感谢。

**Comment by Higurashi-kagome** [comment]
问题已经解决。概括来说，要模拟点击，可以用 MouseEvent 逐个测试以下事件：

```
"mousedown",
"mouseup",
"click",
"mouseover",
"mouseenter",
"mouseout",
"mouseleave",
"mousemove",
```

模拟点击的相关功能位于 [async_dispatcher.ts#L116](https://github.com/gdh1995/vimium-c/blob/833905a7a1193db598ab769edea46349fd87ceb5/content/async_dispatcher.ts#L116)。谢谢。

**Comment by gdh1995** [comment]
是那个文件的 click_ 函数。

顺序不太对，应该是 over, enter, down, up, click；out/leave是鼠标移出去的时候产生的，Vimium C 默认不会自动追加，而是在click后，用户按 `Esc` 的时候再模拟这俩。move 的话，绝大多数情况都不咋需要专门发它。

确实需要特定内容，主要是鼠标点击了哪个按钮、鼠标在哪儿位置。

Vimium C 追求稳定性，所以模拟得还不彻底。彻底的话，需要在每个事件之间等一个 setTimeout(..., 0)，来保证旧事件的promises都完成了，而 Vimium C 是用了 1-2 次 await 来模拟这个等待，极端情况下会漏；还需要覆盖 isTrusted属性，改成 true 。

**Comment by Higurashi-kagome** [comment]
所以顺序是：

```
"mouseover",
"mouseenter",
"mousedown",
"mouseup",
"click",
"mouseout",
"mouseleave",
("mousemove")
```

好像是 click_ 函数调用了 mouse_ 函数，最终生效的应该是 mouse_。

在测试的时候，也试着看了看 [vimium](https://github.com/philc/vimium)，发现它的点击能力没有 Vimium C 强大，比如这里所说的翻页按钮，它无法模拟点击（点击无法正确跳转），不过说来，它的代码风格似乎更加易懂，大概与我不了解 TS 也有些关系。再次感谢。

**Comment by gdh1995** [comment]
啊 Vimium C 写的确实过于复杂了，写的时候考虑了各种情况，又加了很多提高运行时速度的trick，就只能让开发的 ts 代码越写越长。

像 enter/leave，一般库不需要，但我确实遇到了网页检测了enter事件，才加的它。事实上真实的 enter 会有很多个，Vimium C 图快只模拟一个，仍然有可能因为不够真实而失败。

鼠标坐标也是，有的网页检测坐标后显示动画或者移动内容，Vimium C 不模拟它的话甚至会导致网页错乱掉。

你要是熟悉前端开发的话，可以下载 Vimium C 源码，`npm ci` 后执行
```
# chrome/新edge, 98+, windows
export BUILD_BTypes=1 BUILD_MinCVer=98 BUILD_OS=4
gulp local2
```
来编译出来一份 js 版，除去了不符合设定条件的代码，大概能清晰一些。

**Comment by Higurashi-kagome** [comment]
好的，需要学习的时候再试试。不过一定程度功能强大上才真正重要的，熟悉前端的读者看代码应该还是比较顺利。
