### ISSUE TITLE
How do I change the CSS of the hints? 

### ISSUE THREAD

**Issue by basseX** [gdh1995/vimium-c#599]
I am unable to change the CSS of the hints. The only thing working is changing the color of the text, but I would like to make changes to the background of the hints as well.

**Comment by gdh1995** [comment]
The default styl uses a `linear-gradient` filter as `background`, so if you want to replace it with a pure color, then you need something like `background: yellow`.

The latest CSS is in https://github.com/gdh1995/vimium-c/blob/master/front/vimium-c.css , and you may use browsers' Developer Tools (by `Ctrl+Shift+I` or `F12`) to see their effects:
![image](https://user-images.githubusercontent.com/5547703/162187547-9187d735-589c-4b3e-a716-2b7b3cf97e31.png)

**Comment by basseX** [comment]
Hi, thank you for enlightening me, though I'm not sure I understand. I would like to change the style of the hints showed when pressing F, to achieve something like this [this](https://gist.github.com/nerdius/63d99e826a63689d6182130bae299eb0).


![image](https://user-images.githubusercontent.com/58905488/162370023-78caa52f-c266-4580-bdc1-632cedd57945.png)

**Comment by gdh1995** [comment]
So do you know basic knowledge about CSS? Here're are some tutorials:
1. https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics
2. https://developer.mozilla.org/en-US/docs/Learn/CSS

Vimium C uses different classnames from Vimium, so the CSS selectors in your gist link need to be replaced with something like `.D>.LH` (I notice that your Vimium C is in dark mode).

**Comment by basseX** [comment]
Thank you very much, this was exactly what I was looking for.
