### ISSUE TITLE
cant login, after inject into hypothesis 

### ISSUE THREAD

**Issue by yymm120** [gdh1995/vimium-c#603]
1. According to [wiki-inject-into-other-extensions](https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions), I rewrote the html file and manifest file of hypothesis , and then import the plugin into chrome.
2. vimium C works fine in hypothesis, but hypothesis cannot log in.
3. Hypothesis must be logged in before it can be used, I wonder if I overwrote part of the file, causing it to fail to log in.

**Comment by gdh1995** [comment]
If you revert those changes about Vimium C on your copy of `hypothesis`, will the unpacked extension work on your Chrome?

I haven't done tests. Usually there're 2 possible reasons:
1. If your extension is downloaded from https://github.com/hypothesis/browser-extension and compiled by yourself, then it may lack some secret tokens
- 1. please install its official version and then copy it
2. If it's copied from Chrome's `User Data` folder, then deleting `key` field in `manifest.json` caused its ID changed.
- 1. I guess extensions may use their extension IDs as a basic indicator to control account syncing
- 2. Then please try: adding the original `key` field back, reload the unpacked extension and retry
- 3. the line should be something like `"key": "MIIBIjANBgkq...................",`

**Comment by gdh1995** [comment]
Any progress about this problem?

**Comment by gdh1995** [comment]
Um, I do a test and find that the `key` field should not be removed, so that your unpacked `hypothesis` has a same extension ID with the official version, and then it should allow you to login.

Here's my modified version: [hypothesis-1.1069.0.0_0-with-vimium_c.zip](https://github.com/gdh1995/vimium-c/files/9022682/hypothesis-1.1069.0.0_0-with-vimium_c.zip)
