### ISSUE TITLE
How to map key to open Vimium settings?

### ISSUE THREAD

**Issue by mizzunet** [gdh1995/vimium-c#604]
Currently, I mapped `;e`, as
```
map ;e openUrl url="moz-extension://8a60ac56-72f7-4eaf-b0aa-727c82e71ffe/pages/options.html"
```
But it's not a better solution, as UUID is variable. Is there a comamnd for this?

**Comment by gdh1995** [comment]
```map ;e openUrl url="vimium://options"``` should work - https://github.com/gdh1995/vimium-c/wiki/Vimium-inner-URLs

**Comment by mizzunet** [comment]
Cool. Thanks :)
