### ISSUE TITLE
How to select the current word in caret mode 

### ISSUE THREAD

**Issue by ahmedeidandq** [gdh1995/vimium-c#606]
First of all I want to thank you for this great plugin, I can't imagine my day without vimium-c .

I want to remap a key to be able to select the current word in caret mode ( even if cursor in the middle of the word) instead of moving the cursor manually to the beginning of the word, then enter the visual mode automatically .
Like {viw} in vim

I think it is possible, but i can't figure out how to achieve it .

Thanks

**Comment by gdh1995** [comment]
As said in https://github.com/gdh1995/vimium-c/issues/605#issuecomment-1101039849 , there was `aw` to select a current word, but v1.98.0 seems to have bugs about this. Please wait for a newer version.

**Comment by ahmedeidand** [comment]
Great!!
One more question .. Would I be able to do that ( select the current word ) from the "caret mode" directly without entering visual mode ? 
I think it will be amazing

**Comment by gdh1995** [comment]
Vimium C v1.99.0 has been published and its `as` and `aw` should work now.

"Caret mode" is designed to keep selection one-character wide, and it's very easy to switch between VisualMode and CaretMode (by `c` and `v`), so I don't think there's a need to handle commands like `aw` and `as` specially in Caret Mode.

**Comment by gdh1995** [comment]
Updated: I want to rethink whether to do this. Sorry for disturbing messages.

**Comment by gdh1995** [comment]
Hello, now in v1.99.96 `aw` and `as` in caret mode should also select a word, to make copying easier.

**Comment by ahmedeidandq** [comment]
THANK YOU SOO MUCH 🙏🙏🙏🙏
