### ISSUE TITLE
Search completion

### ISSUE THREAD

**Issue by ww7** [gdh1995/vimium-c#61]
As for me search completion (Google) not work. 
If I understand correctly, Vomnibar should return suggestion with e.g. "g" key from Google
I try to use URL for suggestions `https://www.google.com/complete/search?client=chrome&q=%s` and it's not work

**Comment by gdh1995** [comment]
Vimium C doesn't support it, and has no plan to do so.

I've applied very strict CSP on Vimium C's manifest so its pages have no permissions to request any HTTP(s)/FTP websites.

**Comment by gdh1995** [comment]
Maybe I'' design another plugin extension to implement online suggestions - in this year or later?

**Comment by gdh1995** [comment]
Closed because in recent months I have no time to implement another extension.
