### ISSUE TITLE
Open Vomnibar with pre-inputs

### ISSUE THREAD

**Issue by amosbird** [gdh1995/vimium-c#610]
Currently we can type `bi ` to choose a specific search engine to use in Vomnibar, however it's not obvious how to generate a keymap with such default behavior.

I tried `map s Vomnibar.activateInNewTab engines=8 $then="bi "`, which still gives me an empty input bar.

**Comment by gdh1995** [comment]
```map b Vomnibar.activateInNewTab keyword="bing"```

**Comment by amosbird** [comment]
Great!
