### ISSUE TITLE
使用 yy 复制网址，其中的unicode字符被百分号编码了

### ISSUE THREAD

**Issue by K-gihu** [gdh1995/vimium-c#613]
**Describe the bug**

用 yy 复制带中文的网址 https://git-scm.com/book/zh/v2/服务器上的-Git-在服务器上搭建-Git 希望得到中文结果，但是结果是其中的unicode使用百分号表示了：https://git-scm.com/book/zh/v2/%E6%9C%8D%E5%8A%A1%E5%99%A8%E4%B8%8A%E7%9A%84-Git-%E5%9C%A8%E6%9C%8D%E5%8A%A1%E5%99%A8%E4%B8%8A%E6%90%AD%E5%BB%BA-Git

**Browser, OS and Vimium C versions**
```
- Browser name: firefox
- Browser version: 99.0.1
- Vimium C version: 1.98.0
- OS name and version: Linux 5.17.3-arch1-1 #1 SMP PREEMPT Thu, 14 Apr 2022 01:18:36 +0000
```

**Comment by gdh1995** [comment]
嗯是这样，目前可以加`decoded`参数。下一版会让`decoded`默认就是开启的。
```
map yy copyCurrentUrl decoded
```

**Comment by gdh1995** [comment]
Hello, Vimium C v1.98.2 for Firefox has been published, and you may take a try. In this version `decoded` is default to `true` and you may delete it from your key mappings.

**Comment by K-gihu** [comment]
已更新到v1.98.3，工作正常。
