### ISSUE TITLE
Can vomnibar shows row number by default? 

### ISSUE THREAD

**Issue by playdougher** [gdh1995/vimium-c#614]
**What command or commands**

To quickly access items with 'alt + num', I need to open the vomnibar and press alt and wait for 1 second to show the number, then press 'alt + num'. If the number is shown by default, I can save the 1 second

**How should a feature do**

show vomnibar row number by default

**Browser and OS**

- Browser name: firefox 
- OS name: windows10

Name 	Firefox
Version 	95.0.1
Build ID 	20211215221728
Vimium C [1.98.0]

**Comment by gdh1995** [comment]
Add this to `Custom CSS for Vimium C UI`:
```
/*#omni*/
.alt .item::after{background:rgba(255,255,255,0.8);border-radius:21px;color:#333;
content:attr(data-alt-index);font-size:24px;
height:39px;line-height:39px;position:absolute;left:calc(50% - 20px);text-align:center;top:2px;width:39px}
```

And add a keyword of `alt` into the `styles` field of `Vomnibar settings`, just like:
![image](https://user-images.githubusercontent.com/5547703/164959313-5f473c6e-7e5d-4460-aa64-0e7feb256768.png)

**Comment by playdougher** [comment]
> Add this to `Custom CSS for Vimium C UI`:
> 
> ```
> /*#omni*/
> .alt .item::after{background:rgba(255,255,255,0.8);border-radius:21px;color:#333;
> content:attr(data-alt-index);font-size:24px;
> height:39px;line-height:39px;position:absolute;left:calc(50% - 20px);text-align:center;top:2px;width:39px}
> ```
> 
> And add a keyword of `alt` into the `styles` field of `Vomnibar settings`, just like: ![image](https://user-images.githubusercontent.com/5547703/164959313-5f473c6e-7e5d-4460-aa64-0e7feb256768.png)

it works great!
![p1](https://user-images.githubusercontent.com/26463515/164959984-2d93d84b-7e69-4a4d-a6ff-217dca7ee938.png)
