### ISSUE TITLE
mac os unicode 键盘 option修饰键某些情况不起作用

### ISSUE THREAD

**Issue by 10ve** [gdh1995/vimium-c#615]
**Describe the bug**
mac os unicode 键盘 option+t 不起作用

**To Reproduce**

1. 设置->键盘->输入法-> unicode 16进制输入
2. 打开chrome option+t 没反应(但是option+f/a起作用)
3. vimium 配置中*忽略键盘布局*勾选和未勾选都尝试过

**Vimium 配置**
```
{
	"name": "Vimium C",
	"@time": "2022/4/24 11:20:59",
	"time": 1650770459532,
	"environment": {
		"extension": "1.98.0",
		"platform": "mac",
		"chrome": "100"
	},
	"allBrowserUrls": true,
	"autoReduceMotion": 2,
	"ignoreKeyboardLayout": 2,
	"keyMappings": [
		"#!no-check",
		"mapkey e j",
		"mapkey n h",
		"mapkey i l",
		"mapkey u k",
		"mapkey k i",
		"mapkey h e",
		"mapkey l n",
		"mapkey j u",
		"mapkey I L",
		"mapkey N H",
		"mapkey <n:l> n",
		"mapkey <e:l> n",
		"mapkey <i:l> n",
		"mapkey <o:l> n",
		"mapkey <h:l> h",
		"mapkey <j:l> j",
		"mapkey <k:l> k",
		"mapkey <l:l> l"
	],
	"vimSync": true,
	"vomnibarPage": "chrome-extension://cglpcedifkgalfdklahhcchnjepcckfn/vomnibar.html"
}
```
**keyboard-test测试结果**

<img width="706" alt="截屏2022-04-24 11 24 03" src="https://user-images.githubusercontent.com/11514850/164955046-56930790-bc2b-4a98-ad22-dbcc870d2849.png">

**Browser, OS and Vimium C versions**

- Browser name: chrome
- Browser version: 100.0.4896.127 (正式版本) (x86_64) 
- Vimium C version: 1.98.0
- OS name and version: Macos Monterey 12.3.1

**Comment by gdh1995** [comment]
Please open https://gdh1995.cn/vimium-c/keyboard-test.html , disable Vimium C (on the page) and then test Option+T .

Usually some keys are always blocked and handled by your browser and even system, in which case there's nothing to do for a web-extension like Vimium C.

**Comment by gdh1995** [comment]
Um, sorry I didn't notice that bottom image in the issue body.

**Comment by gdh1995** [comment]
Oh I see. I'll try to fix it in a next version.

**Comment by 10ve** [comment]
谢谢回复,相同情况的还有`<a-p><a-m>`

还有一个可能是unicode hex input输入法的问题:
vomnibar option+数字键不起作用

<img width="744" alt="截屏2022-04-24 15 19 25" src="https://user-images.githubusercontent.com/11514850/164964908-71684b67-05fd-4e1a-a05f-e14ad024095e.png">

> To type a unicode character in Unicode "Input Source" mode, hold Option ⌥ and type the 4-digit unicode:
Option ⌥ + 2120 = ℠
Option ⌥ + 2325 = ⌥

**Comment by gdh1995** [comment]
嗯复现了。这俩是同一个原因造成的

**Comment by gdh1995** [comment]
Option+数字键是这样的：
1. 在windows、linux下，alt+0-9 会点击对应行
2. 在 macOS 下，考虑到系统输入法已经把 Alt+字母/数字 用来输入特殊字母了，就（只给 Alt+0-9）换了快捷键
3. 具体来说，macOS 下需要按 Meta+0-9 或者 Alt+Meta+0-9、又或者 Alt+Ctrl+0-9 才能点击对应行
4. 其中 Meta(Command) + 0-9 算是和 Alfred 保持一致，既然它都用了，那应该没有什么大问题。
