### ISSUE TITLE
`f` (`LinkHints.activate`) blocked by Firefox popup blocker if `a` link has `target="_blank"`

### ISSUE THREAD

**Issue by hesyifei** [gdh1995/vimium-c#616]
**Describe the bug**

`f` (`LinkHints.activate`) is blocked by Firefox popup blocker if the `a` element has `target="_blank"`.

**To Reproduce**

1. Make sure "Block pop-up windows" is enabled in Firefox settings and the site you are visiting is not in the exception list.
![2022-04-25_09-01-36-Settings — Mozilla Firefox](https://user-images.githubusercontent.com/4939421/165128038-04f03583-9700-4175-bc26-66beade04588.png)

2. Visit a page with `<a href="..." target="_blank">...</a>`. For example, https://www.rapidtables.com/web/html/link/html-link-new-window.html.

3. Press `f` to enter `LinkHints.activate` and select that link.

4. Firefox says "Firefox prevented this site from opening a pop-up window".

![2022-04-25_08-57-15-HTML link in a new window — Mozilla Firefox](https://user-images.githubusercontent.com/4939421/165128401-a548360c-c726-4f13-a338-eec601adb9b0.png)

Expected behavior: the page should be opened in a new tab (as if a mouse clicked it) without being blocked. I have also tried the latest version of Vimium (1.67.1) which does not seem to have this problem.

Potentially related: https://github.com/gdh1995/vimium-c/issues/26#issuecomment-1106049071

**Browser, OS and Vimium C versions**

- Browser name: Firefox
- Browser version: 99.0.1
- Vimium C version: 1.98.0
- OS name and version: Windows 11 21H2

**Comment by gdh1995** [comment]
Thanks for this report. It seems Firefox is changing its popup-blocking policy (for many times). I need more time to test and find a solution.

Before version 96 (and 91esr.6+), Firefox would block Vimium C's simulated click events, so Vimium C has a special feature to bypass it. But Firefox 96 removed the blocking and then I've disabled the feature on latest versions of Firefox.

If v99 does add the blocking policy back, then maybe the special feature needs to come back, too.

To work around this bug, please try such a mapping when you known that you want to open a link in a new tab:
```
map F LinkHints.activate newtab="force-mode"
```

**Comment by gdh1995** [comment]
Oh sorry. What my last comment mentioned is another bug, while it seems this bug is caused by a different point of popup block.

**Comment by gdh1995** [comment]
Hello, I've made some tests, and you may try this developing version:
[vimium_c-1.98.0-firefox-2996ed3.zip](https://github.com/gdh1995/vimium-c/files/8585290/vimium_c-1.98.0-firefox-2996ed3.zip)

Here's how to use a Zip file: https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package

**Comment by hesyifei** [comment]
> Hello, I've made some tests, and you may try this developing version: [vimium_c-1.98.0-firefox-2996ed3.zip](https://github.com/gdh1995/vimium-c/files/8585290/vimium_c-1.98.0-firefox-2996ed3.zip)
> 
> Here's how to use a Zip file: https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package

I tested it and it seems to solve the problem! Thanks!

**Comment by gdh1995** [comment]
Hello, Vimium C v1.98.2 for Firefox has been published, and you may take a try.

**Comment by hesyifei** [comment]
Thanks! It worked!
