### ISSUE TITLE
simulateBackspace does not work in extension input boxes when used through a shortcut

### ISSUE THREAD

**Issue by chanicpanic** [gdh1995/vimium-c#619]
**Describe the bug**

When a shortcut is mapped to the `simulateBackspace` command, backspaces are not simulated in the extension's input boxes (i.e. the Vomnibar or the find mode input box). However, backspaces are correctly simulated in focused input boxes on webpages.

**To Reproduce**

1. Create the key mapping `shortcut userCustomized1 command="simulateBackspace"` and save the settings.
2. Open `chrome://extensions/shortcuts`.
3. In the Vimium C section, bind `Custom shortcut 1` to `Ctrl + H`.
4. Open a webpage.
5. Press `o` to bring up the Vomnibar and start typing.
6. Press `Ctrl + H`.

Result: No backspace is simulated, and Vimium C presents a `Nothing was focused` message.
Expected: A backspace is simulated.

**Browser, OS and Vimium C versions**

- Browser name: Brave
- Browser version: 1.37.116 (Chromium: 100.0.4896.127)
- Vimium C version: 1.98.0
- OS name and version: Linux 5.17

**Comment by gdh1995** [comment]
Vimium C won't execute some of its commands on Find HUD and Vomnibar, which is on purpose.
1. the 2 pages should be simple and run quick
2. Find HUD is so small that it can not contain any complex UI
3. the cost of passing messages between a normal web page and Vomnibar is too expensive, and there's no way to passing messages synchronously

If you do want to use another key as `Backspace` on Vomnibar, here's another way:
1. remove Ctrl+H on `chrome://extensions/shortcuts`
2. add these mappings into `Custom Key Mappings` on Vimium C Options
```
# by default, <f1> on Vomnibar means to `do delete`
mapKey <c-h:v> <f1>
map <c-h:i> simulateBackspace
```

**Comment by chanicpanic** [comment]
Thank you, I was not aware of the per-mode mappings.

I removed the Ctrl+H shortcut, and now I have `map <c-h:i> simulateBackspace` which handles text boxes and `mapKey <c-h:f> <f1>` for the Find HUD.

However, I have tried `map <c-h:o> simulateBackspace` and `mapKey <c-h:o> <f1>` for the Vomnibar, but neither seem to be working. Any suggestions?

**Comment by gdh1995** [comment]
Oh I made a mistake in my last comment - Vomnibar's modeId is not `v` but `o`.

I tested `mapKey <c-h:o> <f1>` on Vomnibar and it worked on Chrome 100, Win 10. Would you mind try `<c-h:o>` again?

Or if you don't use `<f1>` to do other things, you may write `mapKey <c-h> <f1>` directly.

**Comment by chanicpanic** [comment]
Ok, I have made some discoveries. It seems like the Vomnibar is ignoring keyboard layout in this case even with `Ignore keyboard layout` disabled.

I am using a dvorak layout, and if I have `mapKey <c-h:o> <f1>` and press `<c-h>` in the Vomnibar, it does not work. However, a backspace is simulated when pressing `<c-d>` because dvorak `d` is QWERTY `h`. So, using `mapKey <c-j:o> <f1>` makes `<c-h>` backspace in the Vomnibar because QWERTY `j` is dvorak `h`.

Thus, to achieve the same physical key combo for backspace across all inputs I have:

```
mapKey <c-h:i> <f1>
mapKey <c-h:f> <f1>
mapKey <c-j:o> <f1>
```

**Comment by gdh1995** [comment]
Um, it's because I once thought Vomnibar should do so, in order to make shortcuts out-of-the-box on non-English keyboard layouts.

I need a new method to support English-but-not-QWERTY layouts better.

**Comment by gdh1995** [comment]
Hello, in v1.98.3 Vomnibar should obey the state of `Ignore keyboard layout` when a key is in `A-Z, 0-9 and English punctuation marks` (aka. ASCII characters); while if a keyboard events reports a non-ASCII character (like those in Russian and Greek), then Vomnibar will still ignore keyboard layout anyway.

**Comment by chanicpanic** [comment]
Great, `mapKey <c-h:o> <f1>` is working as I had originally expected. Thank you!
