### ISSUE TITLE
Wrong focus with multiple chrome windows

### ISSUE THREAD

**Issue by kovasap** [gdh1995/vimium-c#62]
I have two chrome windows open on one of my monitors.  When I have focus on one of them, put focus on something on another monitor, then return to the second of the chrome windows, vimium C will think that I am focusing the first.  This means that when I do "previousTab" or "nextTab", the chrome window that is NOT focused will have its tab's cycled.  Chrome shortcuts that are not vimium c related will still act on the focused monitor (e.g. ctrl-f to search).  I'm using xmonad as my desktop environment if that's relevant.

Anyone have an issue like this?

**Comment by gdh1995** [comment]
Seems a bug, I'll fix it this weekend.

**Comment by gdh1995** [comment]
Sorry but could you provide your system platform (Win/Mac/Arch/Ubuntu/CentOS/..., x32/x64), system version and current Chrome version?

**Comment by kovasap** [comment]
Ubuntu, latest chrome

**Comment by gdh1995** [comment]
Sorry but I can not reproduce it.

Here's my test environment today (2019/08/30):
* install Ubuntu 18.04 x86-64 and nvidia GPU driver
* install Google Chrome and Vimium C
  * add `map c previousTab`, and bind `<a-c>` to "previous tab" on `chrome://extensions/shortcuts`
* install xmonad, and logout & login to switch to xmonad
* create two Chrome window on my laptop's monitor, and a gnome terminal window on an external LCD monitor (connected to laptop's HDMI port)

* test1: switch focus by moving mouse
  * both `c` and `<a-c>` work well
* test2: switch focus by pressing `<a-w>` and `<a-e>` (Alt is the default "mod" key)
  * both `c` and `<a-c>` work well

So could you provide more information?

**Comment by kovasap** [comment]
I think this problem has resolved itself; I haven't noticed it for a while now.  Perhaps the issue was with something other than vimium_c.  Sorry for the hassle and thanks so much for the repro attempt!

**Comment by gdh1995** [comment]
Well, it's acceptable from me if this issue doesn't occur. This issue is the first use case I can not solve prefectly in this repo - as you see I've given up this issue for months. I have to admit that, there're always some key-points in a real world which I can not get and then fail to find a solution. .

Anyway, thanks for your patience in this extension and please let me know if you get any new issues about it.

And, happy new year!

**Comment by kovasap** [comment]
No problem.  I'm overall extremely satisfied with the extension - thank you so much for creating and maintaining it!  I hope you have a happy new year as well!
