### ISSUE TITLE
Is it possible to disable Vimium for all sites except a few enumerated ones?

### ISSUE THREAD

**Issue by kings2u** [gdh1995/vimium-c#622]
The title says it all. I use SurfingKeys for the most part, but Vimium works on a few particular sites much better than SurfingKeys.

Thanks for any help!

**Comment by kings2u** [comment]
I was able to accomplish this by using regex to match all but one window title, e.g.,:

`^https?://[^g][^o][^o][^g][^l][^e]`

**Comment by gdh1995** [comment]
A better regexp may be `^https?://(?!google)`
