### ISSUE TITLE
怎么控制hint显示的位置(比如放链接左边,让它不挡住链接)? 还有能设置hint背景透明度吗?(这样即使挡住了下面也能看到下面的文字)

### ISSUE THREAD

**Issue by iamqiz** [gdh1995/vimium-c#623]
谢谢大佬😊

**Comment by gdh1995** [comment]
思路就是去配置页面写 CSS 改样式，CSS 选择器可以是 `.LH` 、`.HM` 等。按 F12 配合浏览器的 DevTools 就知道了哪些选择器是哪些了。

![image](https://user-images.githubusercontent.com/5547703/166217379-7998e3a2-e925-40d6-9373-41fa08c3e25d.png)

但我自己用多了的感受是，左上角+完全不透明 是个非常“稳定”的方式，优点有：
1. 和链接的（矩形）位置左上角对齐，容易知道是哪个链接
2. 完全不透明，保证了可读性，在有背景图案的页面上也能看清

临时让提示块变透明的快捷键可以这么写：

1. 自定义快捷键
```
mapKey <c-f:l> <s-f0_transparent>
```
2. 自定义界面样式
``` css
.HM-f0_transparent { opacity: 0.4; }
```

然后在 LinkHints 模式下，按 `Ctrl+F` 就能临时切换透明度。

**Comment by gdh1995** [comment]
靠左这个比较复杂。因为没法预知提示块有多宽，现在是设置左上角位置，让它自动往右扩展，所以想“右上角对齐链接左上角”的话很难搞。

**Comment by iamqiz** [comment]
@gdh1995 谢谢大佬如此详细地解答!🤞 
我遇到了点问题,我用chrome最新版f12然后ctrl+shift+C却选取不到hints,而且在elements里也找不到hints对应的span元素,这是为啥?
另外我试了大佬的修改透明度的代码.可以用,我现在尝试将黄色背景完全透明化,然后文字改成半透明黄色(也就是黄色荧光),等我遇到问题再来请教大佬哈 😁

**Comment by gdh1995** [comment]
Vimium C 界面的根元素是`<html>`的最后一个子节点，和 `<body>`同级，具体的界面元素都在它的 ShadowDOM 树里。

为了在LinkHints开着的时候仍然不影响鼠标点页面，hints 设置了`pointer-events: none;`样式，而浏览器的c-s-c默认会跳过这种元素。手动找就行了

**Comment by iamqiz** [comment]
@gdh1995 谢谢大佬,找到了!😘

**Comment by gdh1995** [comment]
哦赞







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月2日(周一) 晚上9:54
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.******@***.***&gt;;
主题: Re: [gdh1995/vimium-c] 怎么控制hint显示的位置(比如放链接左边,让它不挡住链接)? 还有能设置hint背景透明度吗?(这样即使挡住了下面也能看到下面的文字) (Issue #623)




 
@gdh1995 大佬,喜报! 我搜到个css:  transform: translateX(-100%)   然后应用到LH上:  .LH { transform: translateX(-100%) }
 居然可以右对齐了🤣

**Comment by iamqiz** [comment]
@gdh1995  请教大佬,请问 mapKey <c-f:l> <s-f0_transparent> 这里面c-f后的:l 是什么意思? 还有后面的 s-前缀代表什么?'😊

**Comment by gdh1995** [comment]
`<c-f:l>` 里的 `:l` 表示只在 LinkHints 内部生效，这个是 Vimium C 比 Vimium 多出来的一种特性，文档见 https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout#per-mode-mapkey

`<s-f0****>` 是 LinkHints 的一种特殊用法，`s-`表示按下Shift。LinkHints 识别到 `Shift` 加“一个以`f0`开始的键”后，就会切换 “`HM-` + 键名“ 这个 CSS 的 classname，这样就能自定义快捷键来切换任意classname，配合自定义界面UI能临时切换任意想要的样式。

**Comment by iamqiz** [comment]
@gdh1995  感谢大佬!Per-mode mapKey 这个功能真不错! 利用这个我把可视模式下的方向键映射到hjkl了,这下可以用方向键移动光标啦!🤣 代码如下,供其他人参考
```
mapKey <left:v> h
mapKey <right:v> l
mapKey <up:v> k
mapKey <down:v> j
```

第二个问题,能修改HM css,那有没有能修改LH css的按键映射? 我用`<s-f0****>`去临时修改background颜色, 但它不影响div.HM元素里面的LH元素, 比如
`.HM-f0_transparent { opacity: 0.5; background:none;}`  background不会影响LH元素(opacity会影响LH)

**Comment by gdh1995** [comment]
&nbsp;Css支持级联选择器，你再搜一下教程？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月3日(周二) 中午12:34
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.******@***.***&gt;;
主题: Re: [gdh1995/vimium-c] 怎么控制hint显示的位置(比如放链接左边,让它不挡住链接)? 还有能设置hint背景透明度吗?(这样即使挡住了下面也能看到下面的文字) (Issue #623)




 
@gdh1995  感谢大佬!Per-mode mapKey 这个功能真不错! 利用这个我把可视模式下的方向键映射到hjkl了,这下可以用方向键移动光标啦!🤣 代码如下,供其他人参考
 mapKey&nbsp;<left:v&gt;&nbsp;h mapKey&nbsp;<right:v&gt;&nbsp;l mapKey&nbsp;<up:v&gt;&nbsp;k mapKey&nbsp;<down:v&gt;&nbsp;j  
第二个问题,能修改HM css,那有没有能修改LH css的按键映射? 我用<s-f0****&gt;去临时修改background颜色, 但它不影响div.HM元素里面的LH元素, 比如
 .HM-f0_transparent { opacity: 0.5; background:none;}  background不会影响LH元素(opacity会影响LH)

**Comment by iamqiz** [comment]
@gdh1995  谢谢大佬,我改成`.HM-f0_transparent>.LH` 后可以了 😊
