### ISSUE TITLE
请教如何设置来禁用按键的数字前缀?,比如忽略3j中的3,而一律使用1j 

### ISSUE THREAD

**Issue by iamqiz** [gdh1995/vimium-c#624]
我有个标注插件,它的快捷键是数字或字母(没法定义组合键),因此我想使用1/2/3/4来作为它的快捷键,但是会被vimium c捕获,导致数字键对那么插件不生效
谢谢大佬😊

**Comment by gdh1995** [comment]
设置网站例外规则：
![image](https://user-images.githubusercontent.com/5547703/166663149-6bbc0f69-fef7-43a8-a660-6cb0f20439f6.png)

或者用 `mapKey 0 <fake1>` 这种，把0-9全改成物理上不存在的键。注意不能是 `<v-fake1>`，所有 `<v-***>` 都会被视为快捷键。

**Comment by iamqiz** [comment]
@gdh1995 **谢谢大佬,成功了**! 我一开始用的是unmap 1 会报错😂

**Comment by iamqiz** [comment]
@gdh1995  大佬,顺便再问个问题, map f runKey 的expect 选项内容很长, 怎么才能分多行书写呢?  我尝试python方式,结尾加 \ 不行

**Comment by gdh1995** [comment]
这种斜杠应该是可以的：
```
map f runKey expect="a:b,\
c:d,\
e:f"
```

你怎么写的？

**Comment by iamqiz** [comment]
@gdh1995 大佬,我又试了一下可以了, 之前试的时候一保存,就自动把expect里的双引号改写成\"形式, 同时[ ] 形式的expect 变成了
"[  ]" 这样字符串形式的了 ,这是我现在的配置(两个环境,分行写):
```
env wolai host="https://www.wolai.com/*"
env baidu host="https://baijiahao.baidu.com/*"

map f runKey expect=[["wolai","<v-f1>",{"match":"div._35PMP,div._18wH_,div._14df9,div.node-container,span.RbYBQ","exclude":"span.tree-arrow-icon"}],\
["baidu","<v-f1>",{"clickable":"span.send"}]] keys="<v-f1>"
map <v-f1> LinkHints.activate
```

**Comment by gdh1995** [comment]
v1.98.0 不支持在参数值里用 ```\``` 换行，我看看怎么改。

你这个情况，可以把 match/exclude 拆到 `v-f1` 里

**Comment by gdh1995** [comment]
哦那是因为空格在`keys`前边是必须的，Vimium C 只用空格来区分`expect`和`keys`这种参数，而不是看括号对的匹配情况。

不加空格的话是尝试把 `[["wolai....` 到 `span.send"}]keys="<v-f1>"`识别成 expect 的值了（具体为什么我要再想想），在纠正格式时还出现了别的错。

下一版会修掉，另外会支持字符串内换行：
```
map f runKey expect="a:b,\
c:d,\
e:f"
```

**Comment by iamqiz** [comment]
> 

@gdh1995  哈哈,我忘了前后两个是2个选项,不是一个选项 🤣

**Comment by gdh1995** [comment]
第 1.98.3 版本修掉 `\\\r` 的问题，并且支持字符串内换行了。

还支持了 `unmap 2` 这种写法，比 `mapKey 2 <fake1>` 更合适，能同时允许 `12t` 来创建 12 个新标签页。

在定义 `unmap 2` 后还能写 `map 2 xxx`，而之前会被视为错误忽略掉。
