### ISSUE TITLE
请问如何调整 Vomnibar.activateTabs 中 tab 的显示顺序

### ISSUE THREAD

**Issue by MasouShizuka** [gdh1995/vimium-c#625]
Vomnibar 搜索 tab 时每一个条目的最后有 `#+数字`，其实就是浏览器中标签页的显示的顺序。
请问如何让 `Vomnibar.activateTabs` 的显示条目顺序和浏览器中标签页的显示的顺序相同，即从 `#1` - `#n`。

此外，最好能让初始位置在当前的 tab 的位置。
比如，当前处于 `#2` 的标签页，即第2个标签页，则 `Vomnibar.activateTabs` 初始选择的条目为 `#2`。

**Comment by gdh1995** [comment]
```
map xxx Vomnibar.activateTabSelection currentWindow tree="from-start"
```

设计上不应该自动选中当前标签，因为它不会是要切换过去的那个，而且默认选中的不是第1个的话会额外代码复杂度。

**Comment by MasouShizuka** [comment]
确实有一定道理。

但我经常有这样的一种情况，在某个网页上用命令 `LinkHints.activateWithQueue` 连续打开多个内容，那么这些标签页会堆积在当前的标签页后面，而且通常会比较多。
我可以通过 `Vomnibar.activateTab` 按顺序查看当前标签页后面的刚打开的标签页标题，并往后选择想先查看的标签页。

所以，若不是自动选中当前标签页的话，就得先在 Vomnibar 列表中翻页，并定位到当前标签页的位置。

**Comment by MasouShizuka** [comment]
或许可以让标签页以循环队列的方式组织起来，那么只要让当前的标签页作为队列头即可了

**Comment by gdh1995** [comment]
现状就是循环的，按 PageDown/PageUp，或者 Shift+ArrowDown/ArrowUp 翻页。

试试 `tree=true`:
```
map xxx Vomnibar.activateTabSelection currentWindow tree
```

会找当前标签的父标签页作为队头，找不到就往前数4个，让当前标签页“居中”，于是搜“+4”就是当前页做队头了。

**Comment by gdh1995** [comment]
不过，标签的序号有点问题，回头我调整一下。

**Comment by gdh1995** [comment]
第 1.98.3 版本里标签序号问题已修复。
