### ISSUE TITLE
add e and E comamands

### ISSUE THREAD

**Issue by palandovalex** [gdh1995/vimium-c#630]
in standart shortcuts list theare "ge" and "gE" commands, for using explore

but, 'e' and 'E' simbols are not used

so, maybe it's worth replacing the commands  "ge" and "gE"  to  'e' and 'E'

**Comment by gdh1995** [comment]
Um, I don't want to add such frequently-used keys into the default list of key mappings, to avoid impact on operating habits of old user.

You may add your own key mappings in the `Custom key mappings` textbox on Vimium C Options page. Please see:
- https://github.com/philc/vimium/#custom-key-mappings
