### ISSUE TITLE
Fa复制当前网址URL怎么处理得到最简短的网址?

### ISSUE THREAD

**Issue by midanmo** [gdh1995/vimium-c#631]
![Snipaste_2022-05-14_17-25-04](https://user-images.githubusercontent.com/105541490/168419825-e6c753a6-f21e-4540-a624-e9c20eb1828d.png)
https://www.hao123.com/?src=from_pc_logon
比如Fa或FE复制得到上面的链接 , vimium-c有什么方法能快速的把前面的https://与com后面的/都删除掉 . 
我想用百度site:最简短的网址 关键字 , 进行某网站相关搜索 .

**Comment by midanmo** [comment]
![Snipaste_2022-05-14_17-32-46](https://user-images.githubusercontent.com/105541490/168420093-d5a33f9f-7e71-4b4d-895b-8216a4fbc9df.png)
类似这个的搜索 . 本人纯纯小白 . 希望大神帮帮忙 .

**Comment by midanmo** [comment]
![Snipaste_2022-05-14_17-38-23](https://user-images.githubusercontent.com/105541490/168420280-2e0b52d3-fae5-4ad3-8926-178da5538f01.png)
![Snipaste_2022-05-14_17-38-39](https://user-images.githubusercontent.com/105541490/168420282-2911ba37-660b-41d3-a8a7-718e9a0fade4.png)

**有什么好的方法能一步到位吗?**

**Comment by gdh1995** [comment]
等我晚上想想啊。

**Comment by gdh1995** [comment]
在 Vimium C 设置页面的 `文字自动替换` 里写`u@^[^:]+://([^/]*)/@site:$1 @,matched` 。

目前 1.98.0 版里，让 `Vomnibar` 这么截取字符串时，会去掉尾部空格，也不支持 `u` 以外的动作前缀，下一版会修掉这两个问题。

**Comment by midanmo** [comment]
@gdh1995 有没有更详细的文字自动替换的案例说明？[https://github.com/gdh1995/vimium-c/wiki/Substitute-URLs-and-text-during-commands](url)：Substitute URLs and text during commands，这个网页看不懂。或者有没有简化SED语法的帮助说明？sed没用过，不知道怎么编替换命令。



下面是我用CopyQ简化网址
![Snipaste_2022-05-19_15-09-54](https://user-images.githubusercontent.com/105541490/169232365-e8ba8dfb-06e2-483a-b9c4-6399a72a7264.png)



![Snipaste_2022-05-19_15-15-59](https://user-images.githubusercontent.com/105541490/169232927-2c9380d9-12f8-4976-aded-d88efa86c5af.png)

**Comment by midanmo** [comment]
map ga LinkHints.activateCopyLinkUrl sed="s@http.?://www\\.@site:@g"
前面https://www. 或 http://www. 我是这样代换的

**Comment by gdh1995** [comment]
Vimium C 的替换规则 远没有 `sed` 程序那么复杂，而且是我魔改了的。格式就是：
```
前缀（也就是1~6个名字） 分隔符 用于匹配的正则表达式 分隔符 替换结果 分隔符 正则表达式属性 [ "," 若干额外命令 ]
```

在 `u@^[^:]+://([^/]*)/@site:$1 @,matched` 里，名字是`u`，分隔符是`@`。正则是`^[^:]+://([^/]*)/`，效果是匹配到 `xxx://xx.xxx.xxx.xxx/xxx` 这种网址，并把 `://` 后边、右边那个`/` 前边 的东西捕捉下来，然后替换掉 `site:$1 ` 里的 `$1`。后边`matched`表示丢弃没匹配上的部分（也就是网址的路径等后边）。

至于你写的 copyLinkUrl，可以这么：
```
map Fa LinkHints.activateCopyLinkUrl sed="s@^https?://(?:www\\.)?([^/]*)/@site:$1\u0020@,matched"
```

**Comment by midanmo** [comment]
@gdh1995 

map gs copyCurrentUrl type="url" sed="s@^https?://(?:www\\.)?([^/]*)/@site:$1\u0020@,matched"
第二步：o打开多功能搜索窗百度搜索
第三步：粘贴+关键字


 基本解决问题

**Comment by gdh1995** [comment]
第 1.98.3 版本里，支持了：
```
map FE LinkHints.activateOpenVomnibar url sed="s@^https?://(?:www\\.)?([^/]*)/@site:$1\\u0020@,matched"
```

这样选择链接后，自动对网址做替换再填入 Vomnibar 里。
