### ISSUE TITLE
'50%' from Vim to Vimium C

### ISSUE THREAD

**Issue by Kurttana78** [gdh1995/vimium-c#632]
I am kindly asking to implement a new shortcut to jump to the 50% mark of the scroll bar. Button e would be my suggestion.

**Comment by gdh1995** [comment]
Um, no perfect way in a current version. I'll add it in a next version of Vimium C.

**Comment by gdh1995** [comment]
Hello, v1.98.3 has been published, and you may try such a mapping:
```
map xxx scrollToTop view="max" dir=0.5 offset=1
```

It will show the middle part of a scrollable target.
