### ISSUE TITLE
How to change the size of the hint marker?

### ISSUE THREAD

**Issue by woshichuanqilz** [gdh1995/vimium-c#634]
![image](https://user-images.githubusercontent.com/11295355/168949962-ae57c308-fd85-4884-a029-fbbf8857d414.png)

I do some search but can't  find the answer. 

I can't locate the element on the dev tool, so I don't know how to write the css code

**Comment by palandovalex** [comment]
This element are added to '#shadow-root'. Inside this - theare element whith selector:
 div.H.RM.D
an inside this div:
span.LH

LH - is class for styling this elements

**Comment by palandovalex** [comment]
If you need to cusom style for marks:

open options of plugin, then find 'Vomnibar settings'.
theare you can change style of element

**Comment by palandovalex** [comment]
In Vimium-C options find:

Custom CSS
for Vimium C UI

and you whill have a happyness!

**Comment by gdh1995** [comment]
You may write your CSS on Vimium C Options page - see https://github.com/gdh1995/vimium-c/wiki/Style-the-UI-of-Vimium-C-using-Custom-CSS .

The related CSS selector is `.LH` .
