### ISSUE TITLE
Vimium-c does not mark one clicable item

### ISSUE THREAD

**Issue by palandovalex** [gdh1995/vimium-c#635]
**Describe the bug**

Vimium-c does not mark one clicable item

**To Reproduce**

1. use Firefox
2 go to https://habr.com/ru/all/
3 if you logged in - logout.
4. use 'f' key

if is how it should be ewerywere
![on-yandex](https://user-images.githubusercontent.com/75374436/168982633-45a9eda3-9c2b-4a7f-9d38-6c75951a5383.png)

it is how it on firefox:

![on-firefox](https://user-images.githubusercontent.com/75374436/168982841-e0281006-173c-4b8b-8043-319005690cb0.png)
 firefox:

**Browser, OS and Vimium C versions**

- Browser name: Firefox
- Browser version: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0
- Vimium C version: Version 1.98.0.
- OS name and version: Linux 5.14.0-1036-oem #40-Ubuntu SMP Mon May 9 09:15:08 UTC 2022

**Comment by gdh1995** [comment]
Um it's a known typo bug on Vimium C v1.98.0 for Firefox, and has been fixed in the latest developing code. Please wait for a next version.

**Comment by gdh1995** [comment]
Hello, Vimium C v1.98.2 for Firefox has been published, and you may take a try.
