### ISSUE TITLE
request scroll Search history or favorites to loop down all addresses

### ISSUE THREAD

**Issue by snsnsjsn** [gdh1995/vimium-c#637]
hi
 when I type B to pop up the favorite bar

and type the keyword to match the result

but the window could just list the first 10 items

and others will hide and could not scroll down to find 

so pls add the scroll features for the history or favorite  bar.

thanks for your great work

**Comment by gdh1995** [comment]
You may use `Shift+ArrowDown` / `PageDown` and `Shift+ArrorUp` / `PageUp` to switch to another page of results.
