### ISSUE TITLE
chrome video player volume adjust key especially: youtube

### ISSUE THREAD

**Issue by 11100010** [gdh1995/vimium-c#639]
on the default mode of chrome, if player is not be focused, up/down arrow will scroll up/down the page instead increase/decrease video volume.
is there any method to map a key to adjust the volume of player or mute the sound in vimium c? or "focusing player" key?

I'm noob in programming and english, so maybe my wording is weird, hope you can understand what i describe.
Thank you so much for your awesome extension.

**Comment by 11100010** [comment]
And I love this command "Move tab to next window (use last, position, right=true)(moveTabToNextWindow)"
Could you add another command that move tab to "previous window" in the next update?

**Comment by gdh1995** [comment]
Yes you may add a key mapping to "focus a video player", by writing this in the textbox `Custom key mappings` on Vimium C Options page:
```
map <f6> LinkHints.click action="focus" match="video"
```

And the above `<f6>` may be replaced with other keys, like `a`, `A` (Shift+A), `<c-a>` (Ctrl+A), `<s-f6>` (Shift+F6) and `<c-s-a>` (Ctrl+Shift+A).

====

The command of `move tab to a next window` (as well as most other commands) supports "`prefix count`“.

For example, by default the key mapped to `moveTabToNextWindow` is `W`, so `-W` (a minus and W) will move a current tab to a previous window. And if you want a single key to do so, you may write:
```
map <a-w> moveTabToNextWindow count=-1
```

`moveTabToNextWindow` can also move more than one tabs by a single command. For example,
```
map W moveTabToNextWindow tabs
```

means `2W` moves a current tab and its right one to a next window, and `-3W` moves a current tab and its 2 left tabs to a next window. In a current version v1.98.0 of Vimium C, when `tabs` is true, there's no way to move tabs to a "previous" window, so I'll add a new parameter of `nextWindow=-1` to support it, in a next version of Vimium C.
