### ISSUE TITLE
LinkHints.activateSelect  caret 的选定内容

### ISSUE THREAD

**Issue by bommbo** [gdh1995/vimium-c#642]
每次选中的位置都偏靠后一点

**Comment by gdh1995** [comment]
能截图解释一下吗？

我试了一下可能能找到你说的是什么了，`activateSelect`默认选中第一个词语，然后`caret`会改成选中第一个字。结果选中的“词语”是2个字以上的时候，caret会跳到结尾往右选择1个字。效果就成了跳过一个词语。

我回头改改。
