### ISSUE TITLE
github网页

### ISSUE THREAD

**Issue by bommbo** [gdh1995/vimium-c#644]
按下o键应该是打开一个搜索框，但是在github页面打开的时候有些奇怪，它的搜索框有一圈白边，其他的网页没有。
桌面环境 gnome+popos,不知道跟这个有没有关系。
![Screenshot from 2022-06-01 12-16-08](https://user-images.githubusercontent.com/61496351/171326501-6aa8792c-9356-4bb4-9b5b-183e4587330a.png)

**Comment by gdh1995** [comment]
1. 能否给个更大范围的截图？你的GitHub是进入了深色模式的吧？
2. 什么浏览器？Firefox，Chromium还是各种定制版
3. 怎么进的深色模式，是系统有深浅选项（gnome好像最新版才有），还是浏览器开了“强制深色”（比如改了 `chrome://flags` 下的各种配置），还是在GitHub的 https://github.com/settings/appearance 里设置的始终深色？
4. 试试关掉其他所有扩展、刷新网页再看呢？
5. 有没有改过Vimium C的`自定义界面样式`这个配置？

**Comment by bommbo** [comment]
![Screenshot from 2022-06-01 15-08-45](https://user-images.githubusercontent.com/61496351/171347644-226c379e-ead3-4609-afb0-12efe2e5fc56.png)

**Comment by gdh1995** [comment]
你屏幕的分辨率和缩放比例是多少？这个滚动条不该出来的，它出来就表示 Vimium C 的搜索框尺寸算错了。

Chromium 版本是多少？改过 `chrome://flags` 下的特性吗？

**Comment by bommbo** [comment]
那是因为点了那个手机模式啦，chrome://flags 下的是默认的
![Screenshot from 2022-06-01 18-03-30](https://user-images.githubusercontent.com/61496351/171379961-0805eb7e-3563-4342-a273-7a3d2da46a54.png)

**Comment by bommbo** [comment]
> 那是因为点了那个手机模式啦，chrome://flags 下的是默认的 ![Screenshot from 2022-06-01 18-03-30](https://user-images.githubusercontent.com/61496351/171379961-0805eb7e-3563-4342-a273-7a3d2da46a54.png)
版本是这个

![Screenshot from 2022-06-01 18-07-41](https://user-images.githubusercontent.com/61496351/171380647-7f9062e0-ab96-4d0f-87b9-d0bc3433d53e.png)

**Comment by gdh1995** [comment]
确认了，Chrome 102 修改了一些东西导致背景色和设计的不一样了。能修复，等 Vimium C 更新吧。
