### ISSUE TITLE
在使用稀土掘金插件的主页或谷歌网上应用店无法使用插件命令

### ISSUE THREAD

**Issue by Nauxscript** [gdh1995/vimium-c#645]
[稀土掘金插件](https://chrome.google.com/webstore/detail/%E7%A8%80%E5%9C%9F%E6%8E%98%E9%87%91/lecdifefmmfjnjjinhaennhdlmcaeeeb) 使用这个插件后打开新标签页默认是掘金做的一个主页，此时无法用vimium-c

测试了一下，如果是浏览器的默认新标签页设置的地址，都是无法使用的

想问一下有没有解决方法

感谢！

**Comment by gdh1995** [comment]
* 在插件页面上运行的办法参考 https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions 
* 在默认新标签页的话，如果你用的是 Google Chrome，而不是Firefox或者别的厂家的定制版Chromium，那么可以：
  * 打开 `chrome://flags`，找到 `#extensions-on-chrome-urls`，改成 `Enabled`
  * 重启浏览器
  * 然后打开 Vimium C 设置 页面，找到 `在 Chrome 原生的新标签页上运行`，勾选上，保存
  * 新创建一个默认标签页，应该能用 Vimium C 了
* 在网上应用店的话，这个是浏览器内部禁掉了，没办法改

**Comment by Nauxscript** [comment]
好的，十分感谢！

顺便问一嘴，如何进行双击操作，看指南里有个 alt + f，试了一下不行，而且会一直有在标记链接的模式

**Comment by gdh1995** [comment]
呃哪儿写的 alt+f ？我可能要改改。

双击没有默认绑定的快捷键，需要手动 map：
```
map <a-f> LinkHints.activate dblclick
```
