### ISSUE TITLE
can not restore closed tab

### ISSUE THREAD

**Issue by axrdiv** [gdh1995/vimium-c#646]
**Describe the bug**

I can't restore a closed tab by tapping \<s-x\>.

**To Reproduce**

**Browser, OS and Vimium C versions**

- Browser name: Chrome 
- Browser version: 102.0.5005.61
- Vimium C version: 1.98.1
- OS name and version: MacOS

**Comment by 11100010** [comment]
can't believe it. me too bro.
Suddenly it happened. Initially I thought maybe I have messed up something.
And I try it on my second laptop, the result was it had the exact issue.

what a mystery!

**Comment by 11100010** [comment]
the default shortcut on mac shift+command+t still works well.

**Comment by gomico** [comment]
Same here, Shift+x doesn't work anymore

browser: Vivaldi 5.3.2679.38 
OS: Windows 10 Version 21H2 (Build 19044.1706)
vimium c 1.98.1

**Comment by ZhangHaizhao** [comment]
use z？？？

**Comment by gdh1995** [comment]
Confirmed. Very sorry. I beg I can find a working around before a new version passes checks of Chrome web store.

**Comment by gdh1995** [comment]
Update: sorry for the bug. Unfortunately there's no working around. Please use `Vomnibar.activate` with an empty query to show recent tabs and restore them when needed. Those suggestions with a mark of `↶` are closed tabs:

![image](https://user-images.githubusercontent.com/5547703/172463637-14f8497b-e3d4-4cf1-8a33-5a7baaede25e.png)


#### Inner details

Vimium C v1.98.1 for Chrome has a bug during its building process which causes uncertain functions fail silently and there's no working around. I'll release a new version to fix it soon.

While the versions for New MS Edge and Firefox use different building steps and parameters, so they seem not affected.

**Comment by 11100010** [comment]
Hooorayyyy, It worked again now guys.
I wonder is there a way to stop chrome extensions automatically updating themselves. :P

**Comment by gdh1995** [comment]
Hello. v1.98.2 for Chrome has been released, and this should have been solved by it.
