### ISSUE TITLE
X is not ok/ X恢复页面失效

### ISSUE THREAD

**Issue by HBSpy** [gdh1995/vimium-c#649]
**Describe the bug**

x is ok
X is not

**To Reproduce**

**Browser, OS and Vimium C versions**

- Browser name: Chrome
- Browser version: 版本 102.0.5005.61（正式版本） (arm64)
- Vimium C version: 1.98.1
- OS name and version:  macOS

**Comment by gdh1995** [comment]
Confirmed. Thanks for your report.

A duplicate of #646 .

**Comment by gitman486** [comment]
+1

**Comment by gdh1995** [comment]
Here's a new unstable version to fix `X (restoreTab)` failing and another bug about scrolling too long: [vimium_c-1.98.1-chrome-ebe5e49-mod.zip](https://github.com/gdh1995/vimium-c/files/8868669/vimium_c-1.98.1-chrome-ebe5e49-mod.zip) . And the usage of Zip packages is https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package .

请测试 最新开发版 [vimium_c-1.98.1-chrome-ebe5e49-mod.zip](https://github.com/gdh1995/vimium-c/files/8868669/vimium_c-1.98.1-chrome-ebe5e49-mod.zip) 。

zip 使用方法可参考 https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package ：

解压这个 zip 文件到一个空白文件夹
手动在地址栏输入 chrome://extensions/ 打开浏览器扩展设置页面
禁用从扩展商店安装的 Vimium C
勾上“开发者模式”的选择框，然后加载这个文件夹

**Comment by HBSpy** [comment]
It works!
等个stable
