### ISSUE TITLE
Unable to go to a mark after creating a mark

### ISSUE THREAD

**Issue by znadre** [gdh1995/vimium-c#650]
**Describe the bug**

Unable to go to a mark using ` after creating a mark.

**To Reproduce**

**Browser, OS and Vimium C versions**

- Browser name: Chrome
- Browser version: 102.0.5005.63
- Vimium C version: 1.98.1
- OS name and version: Windows 11

**Comment by gdh1995** [comment]
Confirmed. Thanks for this report.

**Comment by znadre** [comment]
Fixed after 1.98.2. Thanks!
