### ISSUE TITLE
增加键盘快捷方式支持除字母以外的按键的特性

### ISSUE THREAD

**Issue by linkpom** [gdh1995/vimium-c#653]
**增加键盘快捷方式支持除字母以外的按键的特性**
(经常使用ctrl + shift + [ 和 ctrl + shift + ], 在vimium-c中无法设置)

**Comment by ChloeKurumi** [comment]
可以设置啊？不是都写了嘛？
map <c-s-[> xxx
尖括号里的c、s、a指的就是ctrl、shift、alt

**Comment by gdh1995** [comment]
请试试 `map <c-{> createTab`，对于这种按住Shift会`产生完全不同字符`的键，需要去掉 `s-`，而是使用上档字符来表示按住了shift 。

英文字母的话才是 `<c-s-f>` 这种写法。

**Comment by linkpom** [comment]
了解了, 在edge的扩展页面的确可以配置成功, 在edge的键盘扩展页面配置时会显示"键入一个字母"
