### ISSUE TITLE
在链接上鼠标右键点击出现浏览器菜单的功能有对应热键吗？

### ISSUE THREAD

**Issue by lededev** [gdh1995/vimium-c#654]
热键**f**和**F**是模拟鼠标左键点击链接。
而我需要鼠标右键点击链接的弹出浏览器菜单功能，请问有热键吗？
或者直接复制选定链接地址到裁剪板的功能也行。

**Comment by lededev** [comment]
复制选定链接的方法找到了，热键**yf**就可以支持。
当然，由于我只用左手使用vimium-c，右手还是要把持鼠标，于是又自己映射了一个热键cf，可以用了。`map cf LinkHints.activateCopyLinkUrl`
我的按键方案里左手的s d对应j k，S D对应J K，v V对应H L
不过还是希望能支持在选定链接上鼠标右键点击弹出浏览器菜单的功能，因为那个菜单里可选择的功能不少，而且可定制增加。

**Comment by gdh1995** [comment]
内置的浏览器菜单的话，浏览器不提供接口，做不来弹出不了
