### ISSUE TITLE
Can't copy highlights text in Vomnibar

### ISSUE THREAD

**Issue by polt515** [gdh1995/vimium-c#655]
Describe the bug

When you highlight text in Vomnibar it will copy the full URL instead of what's highlighted when you use the command Ctrl C

To Reproduce

- Browser name: Firefox
- Browser version: 101.0
- Vimium C version: 1.98.2
- OS name and version: Windows 11

**Comment by gdh1995** [comment]
Accepted. A new feature in v1.98.2 causes it and should be improved.

**Comment by gdh1995** [comment]
Hello v1.98.3 has been published and you may take a try.
