### ISSUE TITLE
Num keys bindings broken 

### ISSUE THREAD

**Issue by ahmedeidandq** [gdh1995/vimium-c#656]
Before the last release I was able to use: 
```
mapkey <0:n> <v-nexttabcommand>
mapkey <9:n> <v-previoustabcommand>

map <v-nexttabcommand> nextTab
map <v-previoustabcommand> previousTab
```

to bind 0 and 9 key to change tabs, But now I can't . 
Is there a new way to do same thing ?

**Comment by gdh1995** [comment]
Hello v1.98.3 has been published and you may take a try.
