### ISSUE TITLE
mapKey 的i模式设置在微软拼音模式中无效

### ISSUE THREAD

**Issue by yxysm** [gdh1995/vimium-c#657]
设置: 
```
map <s-f8> LinkHints.activateWithQueue 
mapKey <;:i> <s-f8>
map ; LinkHints.activateWithQueue 
```

目的: 
无论在focus或blur下, 按;都会触发hints.

重现: 
input box focus状态: 英文模式(无论中英键盘)下按;或直接s-f8完全ok, 中文模式按;则直接输入;进box.

疑问: 
不清楚是我哪里设置不对还是有哪些限制,  mapKey i模式似乎只对英文模式有效. blur状态时,中英文模式都ok.
"Ignore keyboard layout" 选项勾上去勾都试过,没变化.

**Browser and OS**
- Browser name:  CentBrowser Version 4.3.9.24
- OS name: Windows 10 1809
- Vimium-C: 1.98.2

BTW, 扩展做的非常棒!

**Comment by gdh1995** [comment]
焦点在文本框里的时候，中文输入的候选框是屏蔽不了的，强行拦截特别容易造成状态错乱，所以这时候vimium c不会拦截它，只会忽略输入的字符。需要的话可以带上ctrl/alt，或者用 f1-f12，来避免触发输入法的候选框。

**Comment by gdh1995** [comment]
没有聚焦到文本框的时候，输入法的真正状态就是英文模式，所以字母键会生效。

强行拦截候选框的其中一种常见问题，就是焦点不在文本框里、但输入法仍然处在中文模式，按字母键触发候选框但没地方可以去真的输入。这个问题我前几年遇到过不少，就不敢再拦截候选框的打字事件了。

**Comment by yxysm** [comment]
哇, 回复好快👍, 多谢解释! 明白了. 带上ctrl/alt或f1-f12试过都没问题. 其实就是想用最方便的键快速调出hints, 但中文下字符直接就弹上去了. 平时基本都是中文模式(包括英文单词,因为可以提示), 所以才请教的.

**Comment by yxysm** [comment]
是不是和输入法做的比较死有关, 比如像;这样字符,它不候选而是直接进box,如果候选的话, Vimium-C是否也可实现该字符设置的功能?

**Comment by yxysm** [comment]
Sorry, 我上条表述有误, 应该是, 像;这样字符,并未触发候选框,Vimium-C是否可实现这类字符设置的功能?

**Comment by gdh1995** [comment]
目前判断进候选框的办法不够精确，分号这种也会被归类到“输入法管理的模式”里。想精确判断的话，会涉及一些别的地方，要同时考虑多处条件，我感觉这样没法保证判断的正确性和浏览器兼容性，不打算修改判断方式。

**Comment by yxysm** [comment]
嗯, 了解, 很多情况并非想当然的样子, 背后可能涉及多且复杂的因素, 这只是我的一个小疑问, 谢谢您及时,详细和清晰的解答.
