### ISSUE TITLE
[Feature idea] Combining gaze tracking with Vimium C

### ISSUE THREAD

**Issue by imranq** [gdh1995/vimium-c#658]
Thank you for writing Vimium C, it is a game changer for my browsing speed and has helped me avoid wrist strain by eliminating my touchpad and mouse use completely!

Here is an idea I've been thinking about: Is it possible to combine gaze tracking using the device camera to determine the user's gaze and have shortcuts in vimium that perform actions related to the gaze position on screen. 

This would be useful for selecting/editing text and all sorts of applications as effectively we are using the motion of our eyes as the mouse itself. This would help users with disabilities and limited motor movements

---
**Here is an example:**
I focus on a piece of text with my eye. I press a shortcut and vimium brings my mouse to the exact position my eyes were looking at on the screen. Possibly this position is represented as M{n}: {x}{y} where 
* n = the monitor I am looking at, 
* x = x-coordinate of my mouse position, 
* y = y-coordinate of mouse position

Finally I can use another shortcut to select text using the mouse position as the initial caret. 

---
Here is an example of gazetracking software: https://github.com/antoinelame/GazeTracking

Apologies if this idea is too random/off-topic, but I thought it would be interesting to share. Thank you!f

**Comment by gdh1995** [comment]
Sorry but the feature of gaze tracking is not suitable to implement in Vimium C:
1. it requires to access your camera, but only frontend webpages can "request" it
- Vimium C should be simple and its accessed privacy should be as little as possible
2. it's a heavy task costing much CPU (or even GPU? I'm not sure)
- 1. if a browser extension want to track eyes, it would cost more CPU (and time) than a native software

However, if this feature is implemented in another extension (with or without native applications), then you may:
1. when press `xxx`, let Vimium C send a request to it, using `map xxx sendToExtension ...options`
- 1. its usage is in my comments on https://github.com/gdh1995/vimium-c/issues/573
3. it should get `n/x/y` from its tracking worker, and then move caret to text under the position
4. it asks Vimium C to run another command like `enterVisualMode`

**Comment by imranq** [comment]
Thank you for the quick response! I did not realize we can combine vimium c with another extension. That's great!

**Comment by imranq** [comment]
I also wanted to mention here that the key combination `yv` is a good replacement for selecting text from a static page via caret
