### ISSUE TITLE
新标签页默认网址配置失效

### ISSUE THREAD

**Issue by winlans** [gdh1995/vimium-c#659]
**Describe the bug**
上一个版本的时候， 这个功能还是正常的，但是现在默认打开的是浏览器的。

**To Reproduce**
![image](https://user-images.githubusercontent.com/16457089/173483464-28717df8-7423-4371-a4f3-eb0a96a334ee.png)
如图，设置之后， 使用快捷键 `t` 打开的是浏览器的新标签页

**Browser, OS and Vimium C versions**

- Browser name:  Microsoft Edge
- Browser version:  102
- Vimium C version:  1.98.0]
- OS name and version: Windows

**Comment by gdh1995** [comment]
v1.97.0 有这个问题，但 v1.98.0 修了，请修改这个配置项、保存、再改回去保存试试。

如果还不行，大概是 t 被别的扩展用掉了，可以试试 `map xxx createTab` 然后看 `xxx` 会打开什么

**Comment by winlans** [comment]
> v1.97.0 有这个问题，但 v1.98.0 修了，请修改这个配置项、保存、再改回去保存试试。
> 
> 如果还不行，大概是 t 被别的扩展用掉了，可以试试 `map xxx createTab` 然后看 `xxx` 会打开什么

已经好了，多谢
