### ISSUE TITLE
Vomnibar search field unfocused on Youtube etc

### ISSUE THREAD

**Issue by ww7** [gdh1995/vimium-c#66]
Issued with Firefox on mac, `Don't let pages steal the focus in loading` is checked
On the Youtube, Youtube Music, Gmail etc is Vomnibar search is unfocused, need to click with a mouse in Vomnibar or click in text field on page

**Comment by gdh1995** [comment]
Then Chrome or Windows has no such an issue? Weird. I'll have a try this evening.

**Comment by gdh1995** [comment]
Please try this zip:
[vimium_c-1.76.6-dist.zip](https://github.com/gdh1995/vimium-c/files/3529480/vimium_c-1.76.6-dist.zip) (It's built from commit 825aa98b72ce6d3bb45868cf74ce071ca98b3c9a).

I reproduced this issue but it was not always there, so the recent commits are only for tests. Thanks for your feedback.

**Comment by gdh1995** [comment]
Closed because v1.76.7 has been released on Firefox Add-Ons.
