### ISSUE TITLE
o is not work well,it work the same as O

### ISSUE THREAD

**Issue by gitman486** [gdh1995/vimium-c#660]
**Describe the bug**
o is not open on the same tab
不是在同一个标签打开，而是在 新标签

**Comment by gdh1995** [comment]
你搜索了什么、选择的是哪类搜索结果，来个截图？按的是回车吗，还是按下了 Ctrl 键？操作系统、输入法、键盘布局都是什么？

**Comment by gitman486** [comment]
win10 自带微软输入法 联想笔记本thinkpad14键盘是没有小键盘的那种
直接按的o，随便点击一个历史记录都是在新窗口打开
![image](https://user-images.githubusercontent.com/64391947/173888071-8db0eaec-174c-4ea7-8a12-2fa0bc79ad38.png)
![image](https://user-images.githubusercontent.com/64391947/173888079-d672e486-2178-44c0-a124-f832b5453f57.png)

然后开启大写，也是在新窗口打开

**Comment by gdh1995** [comment]
没搜索词的时候，你点的这个不单纯是历史记录，而是“最近关闭的标签页”，所以点击实际上是恢复了关掉的标签而不是重新打开它。它们和单纯历史记录的区别是
![image](https://user-images.githubusercontent.com/5547703/173888493-9f5c6963-bdb0-41ea-8729-f10f0113e34e.png)

**Comment by gitman486** [comment]
已解决，确实如你所说。
