### ISSUE TITLE
自定义数字键打开标签的旧版语法不再兼容了

### ISSUE THREAD

**Issue by adangran** [gdh1995/vimium-c#664]
旧版使用数字键快速打开网站，语法如下：
```
mapkey <1:n> <v-1>
map <v-1> createTab url="https://www.zhihu.com/"
```

但现在用1.98.2版本，这个设置没反应了，怎么回事？

_Vimium C [1.98.2](https://github.com/gdh1995/vimium-c/blob/master/RELEASE-NOTES.md#1982)，Microsoft Edge 101，Windows_

**Comment by gdh1995** [comment]
这是个1.98.2的bug，最新代码已修复，过两天发新版本就该好了。

**Comment by gdh1995** [comment]
第 1.98.3 版已发布，请尝试。
