### ISSUE TITLE
[Feature] Support searching bookmarks' folder name/希望能支持对收藏夹的文件夹名进行搜索

### ISSUE THREAD

**Issue by zzeitt** [gdh1995/vimium-c#665]
**Command <kbd>B</kbd>**

Add a feature to `bookmark-searching` function.

**How should a feature do**

When a user has done such steps:
0. Having some bookmarks saved in different folders like this.

    .
    ├── search/
    │   ├── baidu.com
    │   └── google.com
    └── video/
        ├── bilibili.com
        └── youtube.com

2. Press button <kbd>B</kbd> (Currently mapping to the `bookmark-searching` function.)
3. Enter some text indicating the bookmark's folder name, e.g. 'video'.

then Vimium C should do:

2. Display the items inside the folder `video`.
3. (Optional) Highlight the targeted folder name in the sub-field of search result.
![vimiumc_bookmark_search drawio](https://user-images.githubusercontent.com/30381410/174443199-d33e1e48-0ece-43d5-8819-a8d17a15ff72.png)

**Browser and OS**

- Browser name: 102.0.1245.44 (正式版本) (64 位)
- OS name: Windows 10 Version 21H2 (Build 19044.1766)

**Comment by gdh1995** [comment]
某个搜索词以 “`/`” 开头的话就能按 路径 搜索了。

**Comment by zzeitt** [comment]
Thanks for the reply! It works!

> BTW, I am eager to see the 'fuzzy search' feature (#169) on Vomnibar as well.


感谢您的回复，非常棒的插件！
> (小声bb）要是能支持“模糊搜索”就更好啦有(｡･∀･)ﾉﾞ

**Comment by gdh1995** [comment]
模糊搜索有人提过，主要是担心速度变慢、好些优化措施似乎和模糊冲突了我又懒得改。近期都不一定写。

**Comment by zzeitt** [comment]
嗯嗯，确实专注于Vimium本来的功能就挺好的～
