### ISSUE TITLE
question: automatic LinkHints

### ISSUE THREAD

**Issue by gilbh** [gdh1995/vimium-c#666]
Is it possible to have the `f` function (I think it is called LinkHints) re-appear after I click a specific letter/link? I am not sure if that would be helpful if the link take to another page, but when staying in the same page, having the option for such a "sticky" mode of LinkHints is invaluable for continuing to open sub-menus etc.

Thanks for all your great work!

**Comment by gdh1995** [comment]
There has been a command named `LinkHints.activateWithQueue` (`<a-f>`).

**Comment by gilbh** [comment]
Fantastic, but I think there are drop-down menus for which the `LinkHints` does not work (even when I am using `<a-f>`. The website I encounter this is behind a user/pw (it's my bank), so I can't share the URL, but here's the screenshot:

**Comment by gdh1995** [comment]
If the menu shows after LinkHints re-inits itself, you may press `Tab` to make Linkhints reinit again and then it should show hints for new elements.

If some elements are still not hinted, please see https://github.com/gdh1995/vimium-c/wiki/Add-or-remove-hints to configure parameters of LinkHints.

**Comment by gilbh** [comment]
`Tab` did it. Great!!

**Comment by gilbh** [comment]
A related question: is there a "persistent" LinkHints mode? That is, that LinkHints is always on when entering a new page? I think to would be cool!

**Comment by gdh1995** [comment]
No there's no plan to make LinkHints always show - it's impossible to auto select a suitable time point to show LinkHints, because page content may change frequently.

**Comment by gilbh** [comment]
Thanks. I did not think of this problem, but I think that even a one second delay from entering the page until LinkHints come up would be tolerable (even if things change in the page after, which is rare). In my mind at least, this is a major added value, because it really pivots the browsing experience into `vimium-c`. Thank you for your consideration.

**Comment by neta540** [comment]
Is there an option to let hjkl scrolling work while hints are shown, and redraw the hints on each scroll?

**Comment by gdh1995** [comment]
@neta540 Well, not available up to now, unless you can tolerate latency of 50ms between hint markers disappearing and showing again, no holding-on-to-scroll-longer, and the lose of LinkHints mode and options info:
```
mapKey <j:l> <v-lh_j>
run <v-lh_j> scrollDown+reset+LinkHints.activate
```

Maybe I'll add this feature in a future version, but I haven't decided yet.

**Comment by Yarden-zamir** [comment]
Here to ask about the presistant LinkHints mode plans

**Comment by gdh1995** [comment]
A future version will auto detect more clickable targets and then make the `Tab` key on a second LinkHints not so necessary as now.

While `persistant LinkHints mode` is not in a plan yet.

**Comment by Yarden-zamir** [comment]
Who do we need to bribe to get PLM support then?
For people who want to use the keyboard esclusivley this extension is bliss, but the overhead of having to "opt in" every page load is high and I would rather flip a switch that makes sure I need to "opt out" instead.

**Comment by gdh1995** [comment]
OKay now I accept this idea, but I have no much time in recent months, so I may add this feature in, um, maybe 2024.
