### ISSUE TITLE
feature request: auto scroll

### ISSUE THREAD

**Issue by 11100010** [gdh1995/vimium-c#667]
Instead installing another extension, is there any way to get autoscroll feature in Vimium C ?

I see the word "auto" in the command listing here:

<c-e> d	Scroll down (use keepHover=true|false|auto|never)(scrollDown)
<c-y> e	Scroll up (use keepHover=true|false|auto|never)(scrollUp)

Is it possible?

**Comment by 11100010** [comment]
it's awesome but not really functions as well as what i'd like it to. Anyway, thanks you so much.

**Comment by gdh1995** [comment]
Then what did you mean by `auto scroll`?
