### ISSUE TITLE
Source a list of advanced key mappings

### ISSUE THREAD

**Issue by aaron-a-f** [gdh1995/vimium-c#672]
Firstly, @gdh1995 thank you so much for your work on Vimium-C. It's truly incredible! 

It's such a powerful tool and I feel it could be even more accessible and useful to individuals if the advanced features were more apparent or easily implementable. Would it be possible to have a section in the documentation where you request that users send in useful key mappings that they use? Popular websites such as Google, GitHub, YouTube for example can be made much more keyboard-friendly using things like CSS link-hints. I feel like having a community-driven section for this might be valuable.

Thanks again

**Comment by gdh1995** [comment]
Yes a publicly edited document may help. But there was once a malicious and new GitHub account who put harmful information into the Vimium C Wiki, while GitHub doesn't send Wiki modification events to me so I hadn't noticed it until weeks later. This is why I turned off its editing permission of the public.

Maybe we can open some pages in GitHub Discussions to do so, and then I can add links to them into Wiki.

**Comment by aaron-a-f** [comment]
Could they be stored in a markdown file under the docs folder, with you as
the sole CODEOWNER? That way they'd still need your approval

**Comment by gdh1995** [comment]
Do you mean files in the `docs/` of this repo? Um, I prefer puting them on Wiki pages or other web pages. Users may follow steps in https://stackoverflow.com/a/11481887/5789722 to create their Wiki commits and notify me to merge them.
