### ISSUE TITLE
ap and as in visual mode doesn't work in firefox

### ISSUE THREAD

**Issue by polt515** [gdh1995/vimium-c#673]
Describe the bug

as and ap in visual mode doesnt works as intended

To Reproduce

    Browser name: Firefox
    Browser version:  	102.0
    Vimium C version: 1.98.3
    OS name and version: Windows 11

**Comment by gdh1995** [comment]
What do you mean by `as intended`? Firefox doesn't expose the concept of sentences and paragraphs, so `ap` and `as` can only work like `selecting a current line`.

**Comment by gdh1995** [comment]
Um `as` seems to usually select a wrong start position. I'll try fixing it soon.

**Comment by polt515** [comment]
oh, I didn't know that Firefox doesn't recognize paragraphs and sentences, so I understand now why  **ap** doesn't work. 

Thanks

**Comment by gdh1995** [comment]
Hello, v1.99.0 has been available on Firefox (Chrome and Edge versions are waiting for review), and on Firefox `as` should work.

**Comment by random-un** [comment]
Hello! I did not know that `ap` and `as` were supported shortcuts in visual mode. I'm not finding these two in [this](https://vim.rtorr.com/) cheat sheet -- am I looking in the wrong place? Is there a good spot for all supported visual mode shortcuts?

Thanks for the great extension!

**Comment by gdh1995** [comment]
Um it's not from VIM, while I made the 2 keys using the `a` prefix in `aw` and `ae`, `p` for `paragraph` and `s` for `sentence`.

A full list of all default key bindings in VisualMode is:
https://github.com/gdh1995/vimium-c/blob/52163718d65a7f71d5a8d830a6e032de2f476e1a/background/key_mappings.ts#L789-L815
