### ISSUE TITLE
是否能够让vimium-c在本地html上面工作?

### ISSUE THREAD

**Issue by yymm120** [gdh1995/vimium-c#675]
现在我有一个离线html: `C:\Users\Administrator\Desktop\wiki.html`, 但是vimium-c在这个页面上失效.
于是我在这个html的head后面增加`<script type="text/javascript" src="chrome-extension://hfjbmagddngcpeloejdejnfgbamkjaeg/lib/injector.js"></script>`, 没有任何效果.

**Comment by gdh1995** [comment]
请打开浏览器扩展管理页面，找到vimium-c点开详情，看“允许访问文件网址”是否已勾选，没有的话就勾上


不行的话，方便把wiki.html和配套js、css等文件打包发上来吗？





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月2日(周六) 下午3:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [gdh1995/vimium-c] 是否能够让vimium-c在本地html上面工作? (Issue #675)




 
现在我有一个离线html: C:\Users\Administrator\Desktop\wiki.html, 但是vimium-c在这个页面上失效.
 于是我在这个html的head后面增加<script type="text/javascript" src="chrome-extension://hfjbmagddngcpeloejdejnfgbamkjaeg/lib/injector.js"&gt;</script&gt;, 没有任何效果.

**Comment by yymm120** [comment]
勾选了"允许访问文件网址"后生效了, 谢谢了

**Comment by ShelpAm** [comment]
找不到名为"允许访问文件网址"的选项！
