### ISSUE TITLE
按下大写F跳转问题

### ISSUE THREAD

**Issue by l049i2019** [gdh1995/vimium-c#679]
遇到的问题：
    浏览论坛的时候，按下大写F通过标记的字母选中了某个主题在后台打开。如果这个页面里面还有其他我感兴趣的帖子，我又得重新按下F标记链接进行跳转。有没有可能按下F输入字母后台打开网页后，标记链接的字母不消失？不然同一个页面我打开一个链接就要按一次F，很麻烦

**Comment by gdh1995** [comment]
There has been a command named LinkHints.activateWithQueue (<a-f>). And you may press Alt in LinkHints mode to toggle queue mode.

A duplicate of #666 .
