### ISSUE TITLE
Spoilers do not open on 4pda.to

### ISSUE THREAD

**Issue by Butek1** [gdh1995/vimium-c#680]
**LinkHints.activate**

**How should a feature do**
Must open spoiler

When a user has done such steps:

Spoilers do not open on this site    https://4pda.to/forum/index.php?showtopic=1032195#topicoptions
 show bug   https://youtu.be/jJHJ5Ow-Ft4

**Browser and OS**

- Browser name:  Vivaldi  5.3.2679.70 (Stable channel) (64 bit) 
- OS name: Windows 10 Version 1909 (Build 18363.657)
- Vimium version  1.98.3

**Comment by Butek1** [comment]
> **LinkHints.activate**
> 
> **How should a feature do** Must open spoiler
> 
> When a user has done such steps:
> 
> Spoilers do not open on this site https://4pda.to/forum/index.php?showtopic=1032195#topicoptions
> show bug   https://youtu.be/jJHJ5Ow-Ft4
> **Browser and OS**
> 
> * Browser name:  Vivaldi  5.3.2679.70 (Stable channel) (64 bit)
> * OS name: Windows 10 Version 1909 (Build 18363.657)

**Comment by Butek1** [comment]
> **LinkHints.activate**
> 
> **How should a feature do** Must open spoiler
> 
> When a user has done such steps:
> 
> Spoilers do not open on this site https://4pda.to/forum/index.php?showtopic=1032195#topicoptions
> 
> **Browser and OS**
> 
> * Browser name:  Vivaldi  5.3.2679.70 (Stable channel) (64 bit)
> * OS name: Windows 10 Version 1909 (Build 18363.657)
> Vimium version  1.98.3

**Comment by Butek1** [comment]
> > **LinkHints.activate**
> > **How should a feature do** Must open spoiler
> > When a user has done such steps:
> > Spoilers do not open on this site https://4pda.to/forum/index.php?showtopic=1032195#topicoptions
> > **Browser and OS**
> > 
> > * Browser name:  Vivaldi  5.3.2679.70 (Stable channel) (64 bit)
> > * OS name: Windows 10 Version 1909 (Build 18363.657)
> > * Vimium version  1.98.3

**Comment by gdh1995** [comment]
Um it's because the page doesn't report those items as "clickable". Please try such a key mapping:
```
map f LinkHints.activate clickable=".block-title"
```

And then Vimium C should find those really clickable items and work well.

Related wiki: https://github.com/gdh1995/vimium-c/wiki/Add-or-remove-hints

**Comment by heissonly** [comment]
it is still not working on twitter videos. Do I need to make different settings for twitter videos to open ? 

Try this https://twitter.com/ufcfooty/status/1550977267978887170?s=20&t=HAJe1GwH428O0YF0ePZWAw

**Comment by gdh1995** [comment]
What do you want to do on the twitter webpage? The above `clickable=".block-title"` is only used for `https://4pda.to/`, so if you find somewhere else exists non-recognized clickable elements, you may add more CSS selectors to the `clickable="..."` parameter.

**Comment by heissonly** [comment]
It doesn't work as intended. I tied your solution but didn't work as well. I would like to start video. But if I click "AWD" in this screenshoot it doesn't start the video. [Screen Shot 2022-07-26 at 15 44 41](https://user-images.githubusercontent.com/10747792/181021152-541e81ad-b58a-482a-8817-6f50fff1773a.png)

**Comment by gdh1995** [comment]
Well it's because twitter adds some extra transparent "mask" element covering the video, and then Vimium C's option `Detect whether links are completely covered or not` filters out the real video element.

### details

According to my further test, the `QD` in your snapshot means this `div` element:
![image](https://user-images.githubusercontent.com/5547703/181023977-70409839-01a8-4505-8576-d846095308b9.png)

### solution

Unfortunately, twitter has disabled standard way to play/pause its video (the "pause" button is drawn by itself, but not your browser), so a current version of Vimium C won't play/pause it. I'll change logic in a next version.

As a working around, you may use JS url to toggle status of "any video":
```
map Fw openUrl url="javascript:var\u0020a=document.querySelector('video');a.paused?a.play():a.pause()"
```

I tested it on twitter and it seems to work. Though it may fail if a webpage has more than one video element.

**Comment by heissonly** [comment]
Thanks for your fast response, but sound still didn't come up in this case .

 However, I solved the problem by disabling twitter "auto play when it is on wifi" feature. So now normal mode "LinkHints.activate" works perfect to start the video and to stop the video your solution works only.

But for the future reales it would be good to change to logic as you mentioned.

**Comment by Butek1** [comment]
> What do you want to do on the twitter webpage? The above `clickable=".block-title"` is only used for `https://4pda.to/`, so if you find somewhere else exists non-recognized clickable elements, you may add more CSS selectors to the `clickable="..."` parameter.



> What do you want to do on the twitter webpage? The above `clickable=".block-title"` is only used for `https://4pda.to/`, so if you find somewhere else exists non-recognized clickable elements, you may add more CSS selectors to the `clickable="..."` parameter.



> What do you want to do on the twitter webpage? The above `clickable=".block-title"` is only used for `https://4pda.to/`, so if you find somewhere else exists non-recognized clickable elements, you may add more CSS selectors to the `clickable="..."` parameter.

How to add more then one emement
It dont work          clickable=".element" ".element2"
how right ?
