### ISSUE TITLE
Is there a reason to put this(sadjklewcmpgh) character in vimium default "Characters used for link hints" section ? 

### ISSUE THREAD

**Issue by heissonly** [gdh1995/vimium-c#681]
I am asking about this since I want to personalize if there is a logic behind this I'll let it leave as it is.

**Comment by gdh1995** [comment]
The string is indeed from Vimum, and I just removed `f` from it.

I searched in Vimium's commit history, and it seems there's no special reason for every character. A basic intent is to make it longer and easier for fingers to type (in a QWERTY keyboard layout).

Of course you may change it as you like. For example, I use `dsavewrqcxz` to let my left hand type most keys needed by LinkHints.
