### ISSUE TITLE
How to trigger keys like `<a-f>` on macOS? 

### ISSUE THREAD

**Issue by heissonly** [gdh1995/vimium-c#684]
It doesnt work 'a' key in mac. (e.g <a-f>) Is it a functional key like cmd or control I think it is meta key in mac. But It doesn't work for me. Can someone explain which key is <a-f> in mac ?

**Comment by gdh1995** [comment]
Sorry I'm not sure why it currently doesn't work. Please wait for some days and I'll try to test it.

**Comment by gdh1995** [comment]
Have you partially-checked (aka. partially-enabled) `Ignore keyboard layout` on Vimium C Options?

**Comment by heissonly** [comment]
it doesn't work properly even in the case of selection "Ignore keyboard layout" as far as I see.

**Comment by gdh1995** [comment]
Oh, `a-` (alt) on macOS means the `Option` key, but not `Meta`; while `m-` is for `Meta`.

**Comment by heissonly** [comment]
Yes,now it is working when i tried again with the option of "Ignore keyboard layout fully". Since my keyboard is not US qwerty.
