### ISSUE TITLE
Feature Request: Jump to marked positions across different tabs and possibly different windows

### ISSUE THREAD

**Issue by morphykuffour** [gdh1995/vimium-c#685]
I was wondering if this functionality is already implemented. I want to be able to set marks in tabs and quickly jump to them. I want kind of a global tag system where the tags can be viewed in UI and be jumped to.  The current implementation works only currently focused tab which is great for reading long articles and documentation.

**Comment by gdh1995** [comment]
Vimium C support most usages in Vimium, so as said in https://github.com/philc/vimium#keyboard-bindings:

> ### Using marks:
> ```
> ma, mA  set local mark "a" (global mark "A")
> `a, `A  jump to local mark "a" (global mark "A")
> ``      jump back to the position before the previous jump
>           -- that is, before the previous gg, G, n, N, / or `a
> ```

And as said in https://github.com/philc/vimium/wiki/Tips-and-Tricks#swapping-global-and-local-marks:

> ### Swapping global and local marks
> In Vim, upper-case letters are global marks, whereas lower-case letters are local marks.
> 
> In a browser, global marks are arguably more useful than local marks. Therefore, Vimium allows you to swap these two:
> ```
> map X Marks.activateCreateMode swap
> map Y Marks.activateGotoMode swap
> ```
> 
> With these mappings, lower-case letters are taken to be global marks, and vice versa.

**Comment by morphykuffour** [comment]
Thank you for all the info
