### ISSUE TITLE
How to create global custom shortcut from extension setting in chrome. 

### ISSUE THREAD

**Issue by heissonly** [gdh1995/vimium-c#686]
I would like to go last recent tab but if I set this from vims setting it is not always working for in some pages. (e.g new tab or extension tab(chrome-extension://))   

There are some setting here. For custom setting what can I do
![Screen Shot 2022-07-28 at 13 49 49](https://user-images.githubusercontent.com/10747792/181498084-8dcc3153-9c51-45b3-84c4-dd650d7c4ebb.png)
?

**Comment by gdh1995** [comment]
See https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box#global-shortcuts :
> add something like `shortcut userCustomized1 command="goBack"` into "Custom key mappings" on Vimium C Options page

**Comment by heissonly** [comment]
Thank you this extension is very helpfull.

But sometimes it doesn't see my setting.It is probably about this part. Can you please explain how to  add id ?



> Please note that, if you have modified some options of Vimium C, you may need to add its extension id (clnalilglegcjmlgenoppklmfppddien) to Vimium C's "Allow list of other extension IDs" settings.

**Comment by gdh1995** [comment]
What do you mean? The section about `Allow list of other extension IDs` is about injection, but not global shortcuts.
