### ISSUE TITLE
无痕窗口打开问题

### ISSUE THREAD

**Issue by leicancun** [gdh1995/vimium-c#688]
大佬，请问一下该如何将复制的 url 直接在无痕窗口打开？
目前我是这样做的，例如复制了 https://github.com/gdh1995/vimium-c 之后通过按 “|” 打开链接，之后按 ”u“ 在无痕窗口中打开当前网页，能不能复制了url 之后直接按某一个键达到这个效果？

**Comment by gdh1995** [comment]
```map xxx openCopiedUrlInNewTab incognito```

**Comment by leicancun** [comment]
> `map xxx openCopiedUrlInNewTab incognito`

感谢大佬帮助，问题已解决😊
