### ISSUE TITLE
Is there any way to disable it on every single website forever until you re-enable it?

### ISSUE THREAD

**Issue by yoyeet961** [gdh1995/vimium-c#689]
Is there any way to disable it on every single website forever until you re-enable it manually using like the extension options page?
If not, can you add it?

**Comment by gdh1995** [comment]
You may configure this option:
![image](https://user-images.githubusercontent.com/5547703/182507099-decf3332-125e-4fa4-af96-2b464d29b83f.png)

If `Keys` is empty, Vimium C will be disabled totally on matched pages. And you may press the Vimium C icon at the top-right corner and click `Enable for once` to re-enable it.

![image](https://user-images.githubusercontent.com/5547703/182507323-859230c9-5cfc-4237-a1e3-d90cb6ec0f10.png)

There're also some advanced tricks to toggle pass keys within a single key: https://github.com/gdh1995/vimium-c/wiki/Enable-or-Disable-all-frames-by-a-shortcut#how-to-toggle-pass-keys
