### ISSUE TITLE
ALT+c  & ALT+v ?? a problem automatically change's tab

### ISSUE THREAD

**Issue by omaru-ok** [gdh1995/vimium-c#690]
**ALT+c & ALT+v**

i just want to know why it interfare with my browsere keybinds  yes my  browser -opera-gx-   has  own keybinds and made  alt+c and alt+v to go back and forward . but vimium-c is interfering with this as tab swichi

**i just want to disabled that keybinds in vimimum**

im just a new user or vim newbie

then Vimium C should do: get me a way to disable alt+c and alt+v key to be disabled

**Browser and OS**

- Opera GX  - (chromium )
- OS name: window 11

**Comment by gdh1995** [comment]
Vimium C has some default key mappings, and you may write rules to map new keys and unmap some rules. Please try adding this to `Custom key mappings` on Vimium C Options ( chrome-extension://hfjbmagddngcpeloejdejnfgbamkjaeg/pages/options.html ):
```
unmap <a-c>
unmap <a-v>
```

And then click `Save Options` at the bottom.

E.g.:
![image](https://user-images.githubusercontent.com/5547703/182508208-5d115fa7-028c-4304-8f30-ec4aa65e306e.png)

**Comment by omaru-ok** [comment]
oh thx 🤩
