### ISSUE TITLE
mapKey not working correctly

### ISSUE THREAD

**Issue by Balrrach** [gdh1995/vimium-c#691]
**Describe the bug**

Trying to map `J` to `<c-s-p>` doesn't work at all.  
Trying to map `/` to anything ends up mapping it to `<c-f>`(which is the first map I intended to use and that one actually works).

**To Reproduce**
Put the following in `Custom key mappings`:
```
map n scrollDown
map e scrollUp
map h scrollLeft
map i scrollRight

map N previousTab
map E nextTab
map I goForward

unmap m

map L LinkHints.activateOpenIncognito

mapKey / <c-s-p>
mapKey J <c-s-p>
```

**Browser, OS and Vimium C versions**

- Browser name: Firefox 
- Browser version: 103.0 (64-bit)
- Vimium C version: 1.98.3.
- OS name and version: Manjaro Linux 5.10.133

**Comment by gdh1995** [comment]
`mapKey` only takes effects inside Vimium C, and it can not affect what your browser or website pages do.

**Comment by gdh1995** [comment]
> Trying to map `/` to anything ends up mapping it to `<c-f>`(which is the first map I intended to use and that one actually works).

I don't know what you wanted. In your example there's no `<c-f>` mapped, so `/` would not be consumed by Vimium C, and maybe Firefox itself consumed those `/` keys.
