### ISSUE TITLE
javascript schema bookmark doesn't work

### ISSUE THREAD

**Issue by tjx666** [gdh1995/vimium-c#697]
**Describe the bug**

I have a bookmark which link is:

```javascript
javascript: !(function () {
    let package;
    if (location.href.includes('git')) {
        package = document.title.split(/(GitHubs-s)*([^:]*)/)[2].split('/')[1];
    } else if (location.href.includes('npm')) {
        package = document.title.split(' ')[0];
    }
    const url = `https://npmgraph.js.org/?q=${package ?? ''}`;
    window.open(url);
})();
```

Click the bookmark will work, but vimium not.

https://user-images.githubusercontent.com/41773861/184210555-5bf667fa-ae0e-4b6f-b0a0-0078beb69380.mov

**To Reproduce**

1. create a bookmark whick link is above code.
2. open bookmark omni box with shortcut `b`
3. select the created bookmark
4. vimium will do nothing

**Browser and Vimium version**

chrome: 104.0.5112.79
vimium: 1.99.0

**Comment by gdh1995** [comment]
Please open Developer Tools and show errors on `Console` panel. And, what's your version of Vimium C? It should not be1.67.

**Comment by tjx666** [comment]
It's strange that works now.
