### ISSUE TITLE
按下/进入搜索模式，页面停止响应。

### ISSUE THREAD

**Issue by bushnerd** [gdh1995/vimium-c#698]
**Describe the bug**
按下/进入搜索模式，页面停止响应。

**To Reproduce**

1.进入任意URL
2.按下/，试图进入搜索模式
3.页面停止响应。
4.右下角出现如图提示
![image](https://user-images.githubusercontent.com/28666253/184302117-12cb383d-dfe1-423c-a16d-bad7f736d08f.png)
![image](https://user-images.githubusercontent.com/28666253/184302239-b51ae61f-1ac1-4b84-96e0-a458a0f24426.png)

**Browser, OS and Vimium C versions**

- Browser name: Google Chrome
- Browser version: 104.0.5112.81 (正式版本) （64 位） 
- Vimium C version: 1.99.0
- OS name and version: Windows 10 Version 1909 (Build 18363.1440)

**Comment by gdh1995** [comment]
能确定"`/`"绑定到了 `enterFindMode` 吗？如果确定，请把别的扩展程序都临时禁用，只保留 Vimium C，再试试。

**Comment by gdh1995** [comment]
比如就像是 https://github.com/gdh1995/vimium-c/issues/457#issuecomment-945313426 说的，Katalon Recorder 会导致类似的卡死问题，而且 https://github.com/katalon-studio/katalon-recorder/issues/105 一直没人修。

**Comment by bushnerd** [comment]
> 比如就像是 [#457 (comment)](https://github.com/gdh1995/vimium-c/issues/457#issuecomment-945313426) 说的，Katalon Recorder 会导致类似的卡死问题，而且 [katalon-studio/katalon-recorder#105](https://github.com/katalon-studio/katalon-recorder/issues/105) 一直没人修。

非常感谢，谢谢这么及时的回复，确认就是此问题。

**Comment by bushnerd** [comment]
与这个重复。https://github.com/gdh1995/vimium-c/issues/457#issuecomment-945313426
