### ISSUE TITLE
[Request] contributing to documentation (English)

### ISSUE THREAD

**Issue by Acumane** [gdh1995/vimium-c#699]
Hey @gdh1995, I'd like to help improve the English documentation on your project's wiki!

Since GitHub wikis are effectively their own repositories (which can only be cloned—thereby preventing pull requests from being made), I suggest you add a `/docs/` directory here so that myself and others can fork and contribute changes formally.

Contributions would then need to be applied to the wiki either manually (copy/paste) or automatically through GitHub Actions like [Bi-directional Wiki Sync](https://github.com/marketplace/actions/bi-directional-wiki-sync-action) or [one of these](https://github.com/marketplace?type=actions&query=wiki).

**Comment by gdh1995** [comment]
Um, I prefer to using Wiki but not `/docs/` to do so.

You may clone the Wiki repo, edit and commit, push to a repo of yours and then I can merge your commits manually on my local wiki repo and push the merged commits to this Wiki.

Or if you like, you may fork Vimium C, add a `/docs`, and file PRs, although I may merge and then move those files to the Wiki repo.

**Comment by gdh1995** [comment]
Oh first of all, thank you for your enthusiasm.

**Comment by Acumane** [comment]
I'd prefer the fork & PR approach since I plan on contributing code once I'm less busy.

> Or if you like, you may fork Vimium C, add a `/docs`, and file PRs, although I may merge and then move those files to the Wiki repo.

To clarify, that is what I was suggesting. Just know that if you use [this GitHub action](https://github.com/marketplace/actions/bi-directional-wiki-sync-action), `/docs` would merge with your wiki (and vice versa) automatically. That would be the most robust solution, especially if others wish to contribute in the future.
If you insist on merging them *manually*, then deleting `/docs` after is okay.

> thank you for your enthusiasm
I run highly customized vim-like keybinds, so it was my pleasure to find that your improvements have already left Vimium in the dust 👍

**Comment by gdh1995** [comment]
> `/docs` would merge with your wiki (and vice versa) automatically

Sounds interesting. Sorry I didn't take a look at the 2 links in your first comment. Then I'll use it and update my building scripts to auto ignore `docs/` .
