### ISSUE TITLE
Non-english keys don't work

### ISSUE THREAD

**Issue by moskalenco-a** [gdh1995/vimium-c#700]
**Describe the bug**
After update, non-english keys don't work. It worked on my OS and browser before update.
**To Reproduce**
Open any site. Press **а**(same key) instead of **f**. It doesn't work with ukrainian keys too.
If I press **f** all works. If I press **j** it moves down. But if I press **о**(same key as **j**) it doesn't move.

**Browser, OS and Vimium C versions**

- Browser name: Firefox
- Browser version: 103.0.1
- Vimium C version: 1.99
- OS name and version: Fedora 35

**Comment by gdh1995** [comment]
I'm not sure what you meant by "**a** (same key)", sorry. But v1.99.0 does contain some logic changes about key event recognition, so please open Vimium C Options, disable (aka. uncheck) the "Ignore keyboard layout if a key is not located in 7-bit ASCII" option, save it and then retry.

Or, do you have any `mapKey` rules? The new option of `Ignore keyboard layout if a key is not located in 7-bit ASCII` is to make new users not need `mapKey` any more, so it should not affect English letter keys - what details did you mean by that "**`o`** is a same key as **`j`**" ?

**Comment by moskalenco-a** [comment]
Checked "Always ignore keyboard layout" and now it works. Thanks you. And sorry for stupid question.

**Comment by gdh1995** [comment]
Hello, as reported in #703, this is a bug in v1.99.0 which may break old configuration. Fortunately modifying the new keyboard layout settings will fix it.

I'll file a new version to fix it.

**Comment by moskalenco-a** [comment]
Yes, it's really bug, because with old configuration all worked(so new version broke configuration and it's not normal), but it's very good that other languages are supported and it's easy to change settings. I change Chrome with Vimium to Firefox with Vimium C only because of support of other languages. Thank you for so cool extension!

**Comment by gdh1995** [comment]
Um, Vimium also can ignore or follow keyboard layouts, so what's the meaning of `other languages are supported` ?

**Comment by moskalenco-a** [comment]
I mean, that if I switch to language with non-latin letters it works. For example in similar extension for Chrome, I can press "f", and it will work with any language, but if I press "dk" for example it will not work if language is Ukrainian or Russian. That's why I switched to your extension :) Sorry if my English is too bad.

**Comment by gdh1995** [comment]
It's a little strange for me, because as far as I can remember, Vimium should have supported this usage, and here's the option:
![image](https://user-images.githubusercontent.com/5547703/184910230-a1b93c84-bb70-4998-895b-820c55d440b9.png)

During my test on Vimium v1.67.1 and Chrome 104, Win11, if I enabled the option and click `Save Options`, then Vimium showed `LinkHints` on the `f` key, even in a Russian keyboard layout, and its LinkHints also treats following keys as English letters.

**Comment by moskalenco-a** [comment]
Hm, maybe they have already fixed it. I have been using Firefox and your Vimium C for 2-3 months... Don't use Chrome and that extension since.

**Comment by gdh1995** [comment]
I'm not sure what was wrong. But in fact Vimium v1.67 on my Win11 also works well, and it was released on 2021/07, so it's strange that it didn't work 3 months ago.

**Comment by moskalenco-a** [comment]
I didn't remember when I switched to Vimium C with Firefox. 2-3 months is approximately... Maybe that was in the end of May or maybe in May...

**Comment by moskalenco-a** [comment]
Installed that Vimium extension in Chrome. Looks like they really fixed it. Keyboard layout is ignored even for links(when i press something like ab).
