### ISSUE TITLE
Firefox's PDF.js - injecting vimiumc - browser is not defined

### ISSUE THREAD

**Issue by porterdcarnegie** [gdh1995/vimium-c#707]
Trying to get Vimiumc to load on Firefox's built-in PDF viewer.
Edited Firefox's source file _toolkit/components/pdfjs/content/web/viewer.html_ to have vimiumc's injector.js.  The Inspector complains `Uncaught ReferenceError: browser is not defined` in inspector.js, why is _browser_ out of scope and any ideas on how to make vimiumc load?

**Comment by gdh1995** [comment]
It's because Vimium C can only run in a "web-extension" environment, but the built-in component is not an extension.

You may compile https://github.com/gdh1995/pdf.js to get an "extension" version of PDF Viewer, and my version of PDF Viewer on Chrome Web Store is just from it. But I'm not sure whether it needs any extra modification or not to run on Firefox.

**Comment by MahdiNazemi** [comment]
@porterdcarnegie, were you able to build an extension for Firefox from the source Dahan shared?
I'm interested in having PDF Viewer for Vimium-C on Firefox and would like to know if it works without any modifications.

**Comment by MahdiNazemi** [comment]
@gdh1995, would you please share more detailed instructions on how to build an extension from the source? I have compiled the code for production using `gulp generic`, but I'm unsure what to do next.

**Comment by gdh1995** [comment]
Um an old document is in https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions .

The trick to inject Vimium C's scripts into another extension's page is being removed by Chrome, and the deadline is 2023/01 . If that day arrives, a version of PDF Viewer for Vimium C may have to rely on some special versions of Vimium C, while today it can inject all versions of Vimium C in recent years .

**Comment by MahdiNazemi** [comment]
Will the PDF Viewer continue to work when Chrome no longer supports Manifest V2 in June 2023?

**Comment by gdh1995** [comment]
One version of it will bind to a special version of Vimium C - in MV2 versions are not limited.
