### ISSUE TITLE
Is there a way to start automatically in insert mode?

### ISSUE THREAD

**Issue by davidc360** [gdh1995/vimium-c#708]
For some websites, i find that i use insert mode more than vim mode. For example Youtube, i would press J, K, L to play the video and F to full screen, and now have to press i before that. Of course I can black list youtube, but then sometimes i also use Vimium to navigate links. Is there a workaround for my use case?

**Comment by gdh1995** [comment]
As said in https://github.com/gdh1995/vimium-c/wiki/Enable-or-Disable-all-frames-by-a-shortcut#how-to-toggle-pass-keys , you may only allow a single key for some URLs, and map the key to execute `vimium://status/toggle/...`

**Comment by gdh1995** [comment]
For example, this will make `<a-w>` toggle Vimium C's status between `(enabled)` and `^ <a-w>`:
![image](https://user-images.githubusercontent.com/5547703/194247583-9322960f-2655-4c8b-85e3-02bad46a6970.png)
