### ISSUE TITLE
Using global Marks easily

### ISSUE THREAD

**Issue by ww7** [gdh1995/vimium-c#71]
I don't realize how often peoples use Marks, as for me it's cool feature, especially a global marks.
But global marks not easy to use because Shift. 
I suggest to implement additional separate mappings (`create` and `go to`) for global marks.
Or option to disable local marks and use global only.

**Comment by gdh1995** [comment]
There's an option `swap` which is used to revert the check for <kbd>Shift</kbd> status.

For example, `map M Marks.activateCreateMode swap` makes `M` + `any letter` create a global mark by default, and then when Shift is pressed, it creates local marks.

**Comment by gdh1995** [comment]
Sorry I don't understand this sentence yet. Could you explain it again (in point 1,2,3...) ?

**Comment by ww7** [comment]
Nevermind, I'm meat if exist function to `go back` (to previous tab with scroll position) after using global mark.

**Comment by gdh1995** [comment]
Um, global marks have been designed to do so:

1. firstly, find or create a tab with a recorded URL
2. switch to it
3. tell it to scroll to a recorded position

But if a page is loading slowly, Vimium C won't ensure it must receive and execute the "scroll" command .

The original extension Vimium does ensure this, but I think the cost for this is too expensive.

**Comment by ww7** [comment]
Shame on me, answer for my question is a Ctrl+Tab

**Comment by gdh1995** [comment]
If you want "jump to a global mark" and then "jump back to the last tab", then currently there's a similar command named "visitPreviousTab" to do so.
