### ISSUE TITLE
How to add a mapping like Vomnibar.activateEditTitle

### ISSUE THREAD

**Issue by OnceThenEver** [gdh1995/vimium-c#712]
Logical equivalently
`map a Vomnibar.activate $then="openUrl##url=javascript:document.activeElement.value=document.title"`

Unfortunately, this mapping doesn't work, though it seems logical and I don't know what's the problem. I ran Vomnibar.activate and execute that js code in the console of Chrome on macOS 12.5, and everything was fine.

**Comment by gdh1995** [comment]
It's because `openUrl` always executes JS code on a current web page frame, but not Vomnibar frame.

To refer a tab's URL / title in another command, you may use `map xxx openUrl url="vimium://run/..."`, like this:
```
map t openUrl url_mask=false title_mask="$s" \
  url="vimium://run/Vomnibar.activate##url=$s"
```

**Comment by OnceThenEver** [comment]
Thanks for your detailed explanation.
Would you provide `Vomnibar.activateEditTitle`, as `Vomnibar.activateEditUrl`'s counterpart, just for convenience?

**Comment by gdh1995** [comment]
No, because it seems not widely needed. In the past 5~7 years you're the only one who want it.

**Comment by OnceThenEver** [comment]
My pleasure😂

**Comment by gdh1995** [comment]
Hello, the mapping needs an update to replace `$s` with `$S`:
```
map t openUrl url_mask=false title_mask="$S" \
  url="vimium://run/Vomnibar.activate##url=$S"
```
