### ISSUE TITLE
behance 中首页浏览快速多次按 d 向下翻页后会出现 f 键识别失败，只能识别部分，中间的作品无法识别。

### ISSUE THREAD

**Issue by xiahibb** [gdh1995/vimium-c#715]
**Describe the bug**

**To Reproduce**

**Browser, OS and Vimium C versions**

- Browser name: 
- Browser version: 
- Vimium C version: 
- OS name and version:

**Comment by gdh1995** [comment]
能截图看看吗？

**Comment by xiahibb** [comment]
最新的谷歌游览器，Windows系统

**Comment by xiahibb** [comment]
![Uploading uTools_1661756367643.png…]()

**Comment by gdh1995** [comment]
你点太快了，图还没上传完

**Comment by xiahibb** [comment]
<img width="1730" alt="uTools_1661756367643" src="https://user-images.githubusercontent.com/40662921/187142261-8d0073e5-65e9-439e-99bf-632c04eebeff.png">

**Comment by xiahibb** [comment]
感谢作者大大

**Comment by gdh1995** [comment]
滚动条滚了很多页？看起来是滚动20页以上，Vimium C 为了避免太卡而主动跳过了一些页面元素，结果在这个网页上跳错了。

遇到这种情况下，在LinkHints模式里按 `Tab` 键，会关掉这个自动跳过特性并重新找可点击元素，试试吧。这个特性在LinkHints彻底退出后会自动重开，可以用 `LinkHints.activateWithQueue` 来让连续的 LinkHints 都不跳过元素。

**Comment by xiahibb** [comment]
<img width="771" alt="uTools_1661759467662" src="https://user-images.githubusercontent.com/40662921/187151654-82303056-2219-49b1-bf16-e369fd83b57e.png">
不知道是否是这个操作方法，因为不懂代码，很难读懂操作方法。这个网站，设计师用得特多，很重要的一个网站，平面我们会大量的去看里面的作品来提高自己的设计审美。

**Comment by gdh1995** [comment]
点“显示所有命令”就可以看默认的快捷键，比如`LinkHints.activateWithQueue` 默认快捷键是 `Alt+F`。当然你这么写也行，效果是 `f` 后LinkHints也会自动保持，直到按`ESC`才会退出。

`Tab` 键能用吗？我大概想了个办法去修复找不到的问题，不过最近忙，下一版本可能要一两个月才会发。

**Comment by xiahibb** [comment]
按 f 后再退 tab 后，再按 f 键，我试了，没有什么变化，还是识别不出来。而添加了 LinkHints.activateWithQueue 这个后，会让Vimium C 在用其它网页是有点不太方便，目前我试了很多方法，看来只能是按 r 让游览器重新加载一下这个页面让后会让 f 这个功能重新识别成功，不过会等上一会，有点太影响体验，不过也只有这个方法比较能解决问题了。感谢您呀，本来您也没有用这个来赚钱，不敢多求。

**Comment by gdh1995** [comment]
不退出，在LinkHints模式下直接 tab

**Comment by xiahibb** [comment]
刚刚才发现，按 r 后重新加载的页面不是我正在浏览的位置。也试了按 tab ，目前来看像我这样的普通用户暂时没法解决这个问题，只能期待您的更新了，要是有什么快速点按三个 f 可以重新别识一下的功能就好了，哈哈哈

**Comment by gdh1995** [comment]
r重载后位置变化是这类网页的通病吧，瀑布流页面刷新后不会重新加载之前看过的那么多东西，只会加载足够第一屏显示的数量，所以位置就变了。

设计上，在 LinkHints 模式下，按 Tab 时，只要“处在字母匹配模式 + 还没有输入过字母前缀来筛选提示块”，就会重新刷新 LinkHints 的提示标签，而且会关掉一些有副作用的优化功能。

你感觉的 Tab 没效果，可以具体说说吗？

**Comment by xiahibb** [comment]
感谢，先按Alt加f，会出现在新标签页打开页页面的提示，然后接着按下 Tab 确实解决了单纯按 f 无法识别的问题，可这样操作后，会去到一个新的页面，会以单独的方式来完全打开去浏览一个作品集的内容。这种解决办法，没有解决普通 f 出现的问题，主要是这两方面的原因：1.这种方式与原网页的点击后以叠加的方式展示作品集的方式交互方式不同，就是会影响看作品集的速度。2.在这个模式下再按 esc 退出后，再按 f 还是没有解决普通 f 下的识加问题。所以感觉按 Tab 没效果，哈哈哈

**Comment by gdh1995** [comment]
既然tab生效了，那在普通的`f`触发的LinkHints里 tab 也该生效，就不用alt+f 了。

LinkHints模式下，按ctrl/shift/alt 会切换“是否在新标签页打开”、“是否连续点击”这些状态， 右下角会提示当前状态，你可以多切几次熟悉熟悉。

也可以重新配置 alt+f 来默认在当前页面连续点击：
```
map <a-f> LinkHints.activate mode="cur-queue"
```

**Comment by xiahibb** [comment]
好的，又学到了新技能，普通 f 触发 LinkHints 里 tab 也生效了，tab与按 ctrl/shift/alt 会切换“是否在新标签页打开”、“是否连续点击”这些状态，这个功能很好用，解决了behance 中首页浏览快速多次按 d 向下翻页后会出现 f 键识别失败，只能识别部分，中间的作品无法识别。很棒，很开心，感谢
