### ISSUE TITLE
使用goNext /goPrevious对纯数字的链接不起作用，提示没有找到下一页对应的按钮和链接

### ISSUE THREAD

**Issue by yxkongfu** [gdh1995/vimium-c#716]
请教对于没有高级选项“上一页”“下一页”里边的关键词的纯数字链接应该如何处理，自己在里边加了1,2,3或者page=1,page=2这样的也不行

**Comment by gdh1995** [comment]
懂CSS的话可以在里边写CSS选择器，以`.`, `#`, `:`开头的词都会被视为CSS选择器。

goNext 也支持根据网址直接算下一页网址的功能，但是需要手动指定怎么算，配置方法挺复杂的。

可以的话你给网址上来我看看怎么写。

**Comment by yxkongfu** [comment]
http://zh.bookszlibb74ugqojhzhg2a63w5i2atv5bqarulgczawnbmsb6s6qead.onion/s/%E5%81%A5%E5%BA%B7?page=1

**Comment by gdh1995** [comment]
添加这一行到`文字自动替换`：
```
n@\?page=(\d+)\b@?page=${$1,:}@
```

![image](https://user-images.githubusercontent.com/5547703/188158031-928b7d4d-0633-4409-b621-83470d4fd75d.png)

**Comment by yxkongfu** [comment]
加上了，依然没有效果，还是提示找不到下一页

**Comment by gdh1995** [comment]
试试 `n@(?<=\?|&)page=(\d+)@page=${$1,:}@` 呢？

**Comment by gdh1995** [comment]
这个办法的重点是写一个正则表达式（`(?<=\?|&)page=(\d+)`）把 url 里的页码抓出来，然后替换成`${...}`的样式，这样 `goNext` 就知道怎么改造 url 了。
