### ISSUE TITLE
怎么离线安装，不能访问商店

### ISSUE THREAD

**Issue by 107295472** [gdh1995/vimium-c#718]
怎么离线安装

**Comment by gdh1995** [comment]
可以根据readme自己编译、当成调试模式加载，或者百度搜搜帮助下载crx的网站。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月1日(周四) 下午5:13
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [gdh1995/vimium-c] 怎么离线安装，不能访问商店 (Issue #718)




 
怎么离线安装

**Comment by gdh1995** [comment]
另外就是可以用微软的 Edge 浏览器，它支持导入 Chrome 的历史记录、收藏夹、密码之类的，扩展商店也容易访问，我这两年平时用的就是 Edge。

自己编译的话，可参考 https://github.com/gdh1995/vimium-c#building 、 https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package .
