### ISSUE TITLE
repeat last hint

### ISSUE THREAD

**Issue by elig0n** [gdh1995/vimium-c#723]
Some AJAX/JS webpages use a clickable link/button to scroll/change page content without reloading the page. Using hints to click them (i.e. f + 2/3 hint characters) repeatedly can be tiresome and slow, then it would then be better to have a repeat last hint action and a key bound for it (i.e. semicolon or comma, similar to vim's). The same last selected hint would be then clicked.

Also a second bound-key could be used for clicking the last to the last used link hint, for cases where previous/forward buttons exist this way it is possible to "set" those keys in succession and have both opposite actions easy bindings.

**Comment by gdh1995** [comment]
To click a last element, you may use `LinkHints.click`:
```
map xxx LinkHints.click direct="clicked"
```

If you want more hints, you may specify CSS selectors to click a first one in matched elements:
```
# this will find the first `a` or `.btn` element and click it
map xxx LinkHints.click direct="element" match="a,.btn"
```
