### ISSUE TITLE
在元素设计比较密集的网页，我无法通过红色字体识别通过哪些按键来聚焦到可以滚动的元素中

### ISSUE THREAD

**Issue by conglinyizhi** [gdh1995/vimium-c#725]
**How should a feature do**

When a user has done such steps:

1. Go to URL "[https://open.feishu.cn/document/ukTMukTMukTM/uITNz4iM1MjLyUzM]"
2. Press a key "f"

在我这里，他看起来就像这样：
![图片](https://user-images.githubusercontent.com/42381347/190883183-21a2423a-11bb-4ccd-bcd2-652ef0f7e5af.png)
“应用权限概述”左侧的本应用于聚焦红色字体被挡住，这对于挡住他的黑色字体似乎更重要一些

then Vimium C should do:

**Browser and OS**

Windows_NT 10.0 19043
Firefox  91.13.0esr
Vimium C 1.99.3

**Comment by gdh1995** [comment]
按空格可以切换提示块之间的前后顺序，这样就能看到红色字母了。
1. 一般来说点击（比如这儿切换到侧边列表里的某一项）是高频需求，滚动是低频，所以不用刻意把红色块挪到前边
2. 判断先后顺序本身比较复杂，花时间，而 linkhints 启动应当在尽量正确的前提下，能快一点是一点
3. 有的网站的滚动元素本身也是可以点击的，这时候设计上不会标红，所以还是建议用 `LinkHints.activateHover` 命令选择可滚动区域，可避免触发单击效果

**Comment by conglinyizhi** [comment]
好的，感谢您的回复











丛林意志

---原始邮件---
发件人: "Dahan ***@***.***&gt;
发送时间: 2022年9月18日(周日) 下午3:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gdh1995/vimium-c] 在元素设计比较密集的网页，我无法通过红色字体识别通过哪些按键来聚焦到可以滚动的元素中 (Issue #725)




 
按空格可以切换提示块之间的前后顺序，这样就能看到红色字母了。
  
一般来说点击（比如这儿切换到侧边列表里的某一项）是高频需求，滚动是低频，所以不用刻意把红色块挪到前边 

判断先后顺序本身比较复杂，花时间，而 linkhints 启动应当在尽量正确的前提下，能快一点是一点 

有的网站的滚动元素本身也是可以点击的，这时候设计上不会标红，所以还是建议用 LinkHints.activateHover 命令选择可滚动区域，可避免触发单击效果
