### ISSUE TITLE
Vomnibar and Dark Reader

### ISSUE THREAD

**Issue by Dim-Tim-1963** [gdh1995/vimium-c#726]
When I open the Vomnibar (and the Help popup), it follows the site theme set by Dark Reader addon, though everywhere in Vimium settings I forced dark mode. I may change the Vomnibar theme manually, but it remembers it until restart only.

(What I want: Vomnibar is always dark)

My browser: Waterfox, G5.0b2, Vimium C: 1.99.3, Dark Reader: 4.9.57.

Most likely it's a Dark Reader issue, but no harm to ask. :)

**Comment by gdh1995** [comment]
So, you have partially enabled "dark mode" on Vimium C Options, and your Dark Reader is configured to make pages dark, but Vomnibar gets white then?

**Comment by Dim-Tim-1963** [comment]
Some cites I exclude from dark mode, they remain as is, and on those ones Vomnibar starts light.

**Comment by gdh1995** [comment]
Could you give some screen snapshots? I wonder:
1. your Vimium C configuration on ` Auto switch between light and dark mode`
2. your Dark Reader configuration on a website where such an issue happens
3. the result UI of the website's page and Vomnibar on it

**Comment by Dim-Tim-1963** [comment]
![v1](https://user-images.githubusercontent.com/42923977/190894035-dc34f542-8a20-431d-9833-299e0cf8d9ae.jpg)
![v2](https://user-images.githubusercontent.com/42923977/190894039-222dd5cf-b5cd-4cf0-b63a-7190bb821f59.jpg)

BUT:

![v3](https://user-images.githubusercontent.com/42923977/190894045-34d1a8f9-1ad6-4b3e-bf98-d0991c9dc5ae.jpg)
![v4](https://user-images.githubusercontent.com/42923977/190894053-90bdec2c-760e-4eb6-a1b9-ef2c873cf118.jpg)

![v5](https://user-images.githubusercontent.com/42923977/190894059-d652def6-aa1f-4975-bebd-094c992e60e4.jpg)

**Comment by gdh1995** [comment]
Sorry I forgot what you said. What configuration did you change before and after `BUT:`?

**Comment by gdh1995** [comment]
Well, it's because `Filter` and `Filter+` take effects "globally", and in these modes `Dark Reader` adds an "`invert"` filter to web pages, so Vimium C's dark Vomnibar are inverted and looks light.

There seems no way to work around it. I once found some tricks on Chrome to keep Vomnibar dark in such modes, but it turns out that the trick doesn't work on Firefox-based browsers.

**Comment by gdh1995** [comment]
It's almost impossible for extensions to do anything to sovle it on Firefox. The only chance is that the Firefox team think their code is a bug and change the behavior to match what Chrome does.

**Comment by gdh1995** [comment]
Um, I get a new idea: I can add a new mode of Vomnibar - if it notices any `Filter` / `Filter+` during starting then not enable Vimium C's dark mode, but just keep the default light colors. And then Dark Reader's `Filter` should make Vomnibar dark, though a little differently.

**Comment by gdh1995** [comment]
Hello, v1.99.8 for Firefox has been published, and it won't set itself dark if it knows a tab is in `Filter` / `Filter+` mode, so that when `Auto switch between light and dark mode` is enabled, Vomnibar can be dark when Dark Reader manages color themes.

**Comment by Dim-Tim-1963** [comment]
Great!  Thanks, Dahan.
