### ISSUE TITLE
提取title的问题

### ISSUE THREAD

**Issue by LarryKHite** [gdh1995/vimium-c#728]
比如我想提取Title为 “Vimium使用 -  Github” 的页面，但只需要 “Vimium使用” 部分，该如何设置 filter

我现在用的是 map xx copyWindowInfo type="tab" format="${title}"

非常感谢

**Comment by gdh1995** [comment]
```
map xx copyWindowInfo type="tab" format="${title}" sed="s/\u0020-\u0020.*$//g"
```

就是把"` - `"当作分隔符，丢掉它和后边所有

**Comment by LarryKHite** [comment]
> ```
> map xx copyWindowInfo type="tab" format="${title}" sed="s/\u0020-\u0020.*$//g"
> ```
> 
> 就是把"`-`"当作分隔符，丢掉它和后边所有

还想请教下，如果我想同时匹配 “-” 和 “|” 该如何写呢？非常感谢 :)

**Comment by gdh1995** [comment]
`sed=` 后边的`\u0020-\u0020.*$`这部分区域，填入符合JS标准的正则表达式就行：
```
map xx copyWindowInfo type="tab" format="${title}" sed="s/\u0020[-|]\u0020.*$//g"
```
