### ISSUE TITLE
LinkHints.unhoverLast doesn't work in this situation

### ISSUE THREAD

**Issue by zyf0330** [gdh1995/vimium-c#729]
**Describe the bug**

An a element has two event listener `onmouseenter` and `onmouseover`, they produces two different effects. But vimium-c `LinkHints.unhoverLast` just cancels `onmouseenter` effect but not `onmouseover` effect.

**To Reproduce**

This is a paid website, so maybe I cannot produce.

**Browser, OS and Vimium C versions**

- Browser name: Chrome
- Browser version: Version 105.0.5195.125 (Official Build) (64-bit)
- Vimium C version:  Vimium C 1.99.3, Google Chrome 105, Linux.
- OS name and version: Ubuntu 22.04

**Extra infos**
If I execute below code, both two effects are canceled.
```
var event = new MouseEvent('mouseleave', 
       {view: window, bubbles: true, cancelable: true});

  var cancelled = !aElement.dispatchEvent(event);

```

**Comment by gdh1995** [comment]
Vimium C dispatches `mouseout (bubbles: true, cancelable: true)` and then `mouseleave (bubbles: false, cancelable: false)` in order, and this order has been used by Chrome for years and is still correct on Chrome 106. So there're such potential reasons of this issue:
1. the website binds `mouseleave` listeners in a child element, but LinkHints in Vimium C trends to select a parent element, and then the listener was not triggered
2. maybe the website's effects can not work well if `mouseout` and `mouseleave` are simulated by Vimium C in a same "macro task".

Vimium C's another command, named `dispatchEvent`, can be used to work around this compatibility issue:
```
map <v-dem> dispatchEvent direct="clicked" class="mouse"
run xxx dem#type=mouseout+dem#type=mouseleave#bubbles=false&cancelable=false
```

**Comment by gdh1995** [comment]
> Vimium C's another command, named `dispatchEvent`, can be used to work around this compatibility issue:

Oh the correct mapping is:
```
map <v-dem> dispatchEvent direct="clicked" class="mouse"
run xxx dem#type=mouseout+dem#type=mouseleave&bubbles=false&cancelable=false
```

**Comment by zyf0330** [comment]
Thank you.
Is there doc about `dispatchEvent`? I don't understand what `direct` and `class` options mean.

**Comment by gdh1995** [comment]
Um, basically:
1. the command is to create a simulated "event" object and "dispatch" it using browser's `dispatchEvent` API (https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent);
2. `class` means the "class type" of an event instance to be "dispatched", like `keyboard` for `KeyboardEvent` and `mouse` for `MouseEvent`;
3. `type` is just the `type` member of a JS Event instance
4. other common properties are passed to the `MouseEvent` constructor as `options` (https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/MouseEvent)

There's no document but only source code:

- entry point of `dispatchEvent`: https://github.com/gdh1995/vimium-c/blob/68b4f58c092c806d79fb4461bd29c11aa5beb461/background/all_commands.ts#L188
- `class`: https://github.com/gdh1995/vimium-c/blob/68b4f58c092c806d79fb4461bd29c11aa5beb461/background/all_commands.ts#L193
- `direct`: https://github.com/gdh1995/vimium-c/blob/68b4f58c092c806d79fb4461bd29c11aa5beb461/content/link_hints.ts#L548

**Comment by zyf0330** [comment]
This is worked for me.
```
map <v-dem> dispatchEvent direct="clicked" class="mouse"
run Q dem#type=mouseout+dem#type=mouseleave&bubbles=true&cancelable=true
```

**Comment by gdh1995** [comment]
So does your test page require `bubbles=true`? But `mouseleave` should not have a `bubbles` of `true`, as far as I've tested on recent versions of Chrome and Firefox on Win11.

**Comment by zyf0330** [comment]
Sorry, I just try and pick first successful expression.
After some tries, I find `run Q dem#type=mouseout+dem#type=mouseleave&cancelable=false` just works which remove `bubbles=false`

**Comment by gdh1995** [comment]
Hello, v1.99.90 has been released on Chrome Web Store, and its `LinkHints.unhoverLast` (also also `dispatchEvent`) supports a parameter of `bubbles=true`:
```
map xxx LinkHints.unhoverLast bubbles
```

And you may take a try.
