### ISSUE TITLE
how to open all bookmarks in a folder?

### ISSUE THREAD

**Issue by 11100010** [gdh1995/vimium-c#730]
is there any command to open all bookmarks in a specific folder using the vomnibar?
or could I mapping a key to use javascript doing this function?

**Comment by 11100010** [comment]
another question: anybody knows how to use this command:

Add tabs into a bookmark folder (use folder:string)(addBookmark)

after pressing the mapped key, it promts: "Need "folder" to refer a bookmark folder" , and then nothing happens.

**Comment by 11100010** [comment]
could i use this command:

open a bookmark (use title, path)(openBookmark)

to open all bookmarks in a specific folder? if yes, then how, thanks so much for helping me figure it out

**Comment by gdh1995** [comment]
Oh currently `openBookmark` can not do so. You may use `openUrl` with `urls: string[]`:
```
map xxx openUrl urls=["http://a.com", "http://b.org"]
```

**Comment by 11100010** [comment]
nice, although it still need some extra work, but it works fine. thank you so much

**Comment by 11100010** [comment]
nice, although it still needs some extra work, but it works fine. thank you so much

**Comment by 11100010** [comment]
Looks like the command: _Open a bookmark (folder) (use title, path)(openBookmark)_
has been fixed?

I still don't understand how to map the command correctly, only got the respond:
"Invalid bookmark path" or "Invalid bookmark title"

I've tried both the folder name and the id (e.g. chrome://bookmarks/?id=356 )
But it didn't work.
Could you mind to explain to me?
Thank you!

**Comment by 11100010** [comment]
Looks like the command: Open a bookmark (folder) (use title, path)(openBookmark)
has been fixed?

I still don't understand how to map the command correctly, only got the respond:
"Invalid bookmark path" or "Invalid bookmark title"

I've tried both the folder name and the id (e.g. chrome://bookmarks/?id=356 )
But it didn't work.
Could you mind to explain to me?
Thank you!

**Comment by gdh1995** [comment]
Do you want to open a folder?

Then you may try:
```
map xxx openBookmark id=356
```

The `title` is its name, and `path` should be something like `/folder1/folder2/title`, just like what `Vomnibar` shows for the bookmark node (when a query word starts with `/`).
