### ISSUE TITLE
select tabs in vomnibar and delete them

### ISSUE THREAD

**Issue by playdougher** [gdh1995/vimium-c#732]
I checked vimium-c wiki and issues but can't find selection on vomnibar

Is it possible to select multiple tabs with mouse or shortcuts? Use <s-delete> to close tab has some delay, so I want to select more tabs then close them together

For example, use shotcuts to select tabs:
open the vominibar of recent opened tabs -> type string to search tabs -> alt-j to move down to a tab, press alt-v to select one tab, or press alt-shift-v then alt-j/k to select multiple adjacent tabs and  alt-shift-v to end selection -> press shift-backspace to delete tabs 

**Browser and OS**

- Browser name: Firefox 100.0.2 20220519220738
- OS name: win10 enterprise 20H2

**Comment by gdh1995** [comment]
Um, I think this need is too rare to add as a new command. Currently there's a trick using `vimium://run` to remove some types of tabs:
1. `removeTab` supports a parameter named `filter`, and the parameter can include complex conditions
2. so you may type a search engine name and `filter` value on Vomnibar, and then press Enter to run the command

For example, with ```rt: vimium://run/closeOtherTabs##filter=$S Remove Tabs```, a query of `rt host=www.google.com` on Vomnibar will remove all tabs in `www.google.com` (but not those in `scholar.google.com`:
![image](https://user-images.githubusercontent.com/5547703/194312868-a8c0cd1f-beec-4bc3-abe2-01cc3b80bb1b.png)

The `filter` parameter is a list of `flag=value` joined using `&` or `+`, and it supports `title` (if partially match), `url` (in the format of exclusion patterns), `host` (exactly match), `active=true|false`, `new=true|false`, `discarded=true|false`, `hidden=true|false`, `incognito=true|false`, `pinned=true|false`, `muted=true|false`, `audible=true|false` and so on, and those boolean flags support `xxx=same`, which means to have a same state with a current tab. So `filter=muted=true&url=:https://www.youtube.com/` means to close all muted youtube tabs.

**Comment by playdougher** [comment]
I try to filter with title, find it can only remove tabs on current window and I can't know how many and which tabs are removed, anyway, this need is rare, I can use <s-delete> to delete tabs one by one, thanks your reply!

**Comment by gdh1995** [comment]
> it can only remove tabs on current window

Um yes both `closeOtherTabs` and `removeTab` only take care about tabs in a current window.

You may use `joinTabs filter=title=...` to move all matched tabs in other windows to a current window, and then remove them:
```
rt: vimium://run/joinTabs#filter=title=$s+closeOtherTabs##filter=$S Remote all tabs
```

**Comment by gdh1995** [comment]
Um, The above mapping of `title=$s` had a bug and I just fixed it.

**Comment by Adamkaram** [comment]
it doesn't work yet
jt: vimium://run/joinTabs#filter=title=$s
still telling me that no tabs matched the filter parameter

**Comment by Adamkaram** [comment]
jt: vimium://run/joinTabs#filter=title=$s 
doesn't work yet i don't why

**Comment by gdh1995** [comment]
Um, what was your query word？


The search engine has included 'title=',&nbsp; So your query should not add it again.



---Original---
From: ***@***.***&gt;
Date: Mon, Oct 17, 2022 16:49 PM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] select tabs in vomnibar and delete them (Issue#732)




 
jt: vimium://run/joinTabs#filter=title=$s
 doesn't work yet i don't why

**Comment by Adamkaram** [comment]
i will try it now and give a report 
also what about these two commands
if i need automatically to join all youtube tabs in a new window with something like this
jt: vimium://run/joinTabs#filter=host=:https://www.youtube.com/ newWindow
and should i add active=true condition if was active in youtube tabs ?

**Comment by Adamkaram** [comment]
> Um, what was your query word？ The search engine has included 'title=',&nbsp; So your query should not add it again.
 
 more explain please!

**Comment by Adamkaram** [comment]
> Um, what was your query word？ The search engine has included 'title=',&nbsp; So your query should not add it again.
it's working now , so after i should add it again what form should my query looks like ?
jt: vimium://run/joinTabs#filter=$s  is that right with no need to add title condition?

**Comment by Adamkaram** [comment]
> Um, what was your query word？ The search engine has included 'title=',&nbsp; So your query should not add it again.


it's working now , so after i should add it again what form should my query looks like ?
jt: vimium://run/joinTabs#filter=$s is that right with no need to add title condition?

**Comment by Adamkaram** [comment]
> Um, what was your query word？ The search engine has included 'title=',&nbsp; So your query should not add it again.


it's working now, so after I should add it again what form should my query looks like?
jt: vimium://run/joinTabs#filter=$s is that right with no need to add title condition?

I tried after searching and  I came up with 
jt: vimium://run/moveTabToNewWindow+joinTabs#filter=host=$s

but it has a flow :
it will move the active tab with tabs belonging to the host I specified  but it work just fine 
is there any way just to move tabs with specified tabs?

**Comment by gdh1995** [comment]
So what do you want? Move some tabs (not including a current tab) to a new window?

**Comment by Adamkaram** [comment]
> So what do you want? Move some tabs (not including a current tab) to a new window?

umm ,i'm just doing experiments to improve ux or make ur extension more flexible 
but anyway yes that what i want

**Comment by gdh1995** [comment]
Um it's because `moveTabToNewWindow` only move `N tabs in a current window` by default, so without given count it will only move a current tab, or nothing if `filter=...` doesn't match the current one.

Then you may try:
```
map <v-mv> moveTabToNewWindow count=1000 focused=false
```
and
```
jt: vimium://run/<v-mv>#filter=host=$s Move tabs by host
```

**Comment by gdh1995** [comment]
Hello, the `jt` search engine needs an update to replace `$s` with `${s:%20}`:

```
jt: vimium://run/<v-mv>#filter=host=${s:%20} Move tabs by host
```

**Comment by gdh1995** [comment]
Hello, I find I just forgot to mention the simplest way - `Shift+Delete` on Vomnibar.

When Vomnibar is showing tabs, you may filter tabs by their titles and URLs, and even their statuses using `:`-prefixed words like `:muted`, `:audible` and `:pinned` (see more in https://github.com/gdh1995/vimium-c/issues/671#issuecomment-1229367594).

And then, you may press arrow keys to select a tab and then press `Shift+Delete` to remove it. Vomnibar will auto update its suggestion list to show left tabs, so you may remove one by one if only needed.

**Comment by gdh1995** [comment]
@Adamkaram Sorry the old solution of `map <v-mv> moveTabToNewWindow count=1000 focused=false` has a disadvantage: the count is so large that Vimium C will treat it as a mark to "select this tab and all tabs at the right", but not "select all tabs in a current window" as I once thought.

A fix to it is to use `map <v-mv> moveTabToNewWindow count=1000 focused=false limited=false` (aka. to append ` limited=false`).

And, Vimium C v1.99.5 is being published, and it will treat `limited` as `false` if it doesn't exist while `filter` exists. So you may also just wait for it and then the above trick will work better.
