### ISSUE TITLE
change the look of Hud

### ISSUE THREAD

**Issue by Aneeqasif** [gdh1995/vimium-c#733]
i want to change the colors of this:
![image](https://user-images.githubusercontent.com/78728701/192102227-c9e79010-8163-4fa8-b9a8-28c6ac3f572f.png)
 how can i do that

**Browser and OS**

- Browser name:  firefox
- OS name: manjaro

**Comment by Fuann-Kinoko** [comment]
you can modify the css in settings
[wiki](https://github.com/gdh1995/vimium-c/wiki/Style-the-UI-of-Vimium-C-using-Custom-CSS)

**Comment by gdh1995** [comment]
Yes, BTW the dialog in your snapshot is named "Vomnibar", while "HUD" is this one:
![image](https://user-images.githubusercontent.com/5547703/194539835-4f78219a-0dec-4cb4-9ffe-2ca8b6880936.png)

**Comment by Aneeqasif** [comment]
got it thanks
