### ISSUE TITLE
Can you remap Esc to ii?

### ISSUE THREAD

**Issue by breezemight** [gdh1995/vimium-c#735]
Is this possible to remap ESC in vimium C or can we remap at all?

**Comment by gdh1995** [comment]
You may use `mapKey` to make another "`(composed) key`" work like as `<esc>`. For example:
```
mapKey <c-q> <esc>
```

But Vimium C doesn't support `ii` to do so, because this will prevent you from typing the `i` character when you're writing in a normal text box.

**Comment by gdh1995** [comment]
If you just want to use other key sequences to exit insert mode, then you may see https://github.com/gdh1995/vimium-c/issues/721#issuecomment-1284915528 and https://github.com/gdh1995/vimium-c/issues/721#issuecomment-1284914232 :

> If you want to trigger key sequences in a "plain" insert mode (not from `enterInsertMode`, but entered when an input box is focused), then this is just enough:
> ```
> mapKey <c:i> <v-c>
> map <v-c>d dispatchEvent esc
> ```
