### ISSUE TITLE
`feature-request` any possibility for vomnibar search suggestions ?

### ISSUE THREAD

**Issue by pc00per** [gdh1995/vimium-c#736]
Any possibility in your roadmap featuring search auto suggestions (from google, ddg, etc) directly from vomnibar ?
Is there a possibility to incorporate search APIs into extensions ?

**Comment by gdh1995** [comment]
As I've answered in #61, I won't add such a feature into Vimium C, so that it can keep search words secret and invisible for outsides, in order to protect user privacy.

**Comment by pc00per** [comment]
Welp, by default, even firefox & chromium have search suggestions enabled. So there's no point of protecting user's privacy when the browsers themselves break privacy.
Google's already a sponsor of firefox for their default search engine. And it already comes with search suggestions enabled. 
And you already know about chromium right.
So protecting privacy would be the least usable argument in this case.

**Comment by gdh1995** [comment]
Um some users don't worry about their browsers like Chrome and Firefox, but they do not trust (non-popular) web extensions.

**Comment by Gr-Nobel** [comment]
May be an ability to turn on and off this feature for more privacy-oriented persons.

**Comment by gdh1995** [comment]
Maybe I'll add a syntax to customized completion URL, um, but in a few years.

**Comment by ym496** [comment]
Any updates on this?

**Comment by gdh1995** [comment]
Um, not yet; neither in recent 6 months, sorry.
