### ISSUE TITLE
Not working properly on some sites when using the Brave Browser

### ISSUE THREAD

**Issue by sharimot** [gdh1995/vimium-c#737]
**Describe the bug**

I'm using Vimium C on the Brave browser. On some sites, when I open a link in a new tab, Vimium C is not working on the newly opened page. When I reload the page, Vimium C starts to work properly.

This bug appears on these sites:
- https://bloomberg.com/
- https://wired.com/
- https://bbc.com/
- https://cnn.com/
- https://economist.com/
- and many more

This bug seems to have been introduced a few weeks ago. I've been using Vimium C on Brave for long but I've never encountered a bug like this.

Vimium (the original extension) is working correctly in the same situation. 

This bug doesn't happen on Chrome.

**To Reproduce**

1. Go to one of the above-mentioned sites.
2. Right-click a link and open it in a new tab.
3. Go to the new tab.
4. Vimium C is not working.
5. Reload the page.
6. Vimium C is working.

**Browser, OS and Vimium C versions**

- Browser name: Brave
- Browser version: v1.43.93
- Vimium C version: 1.99.3
- OS name and version: macOS Monterey 12.2.1

**Comment by gdh1995** [comment]
Um, sorry for such a late response. I expect some more information about this report:
1. Does this issue always happen on such sites if only you create new tabs?
- 1. will Vimium C work at once without refreshing pages during some tests?
- 2. or does it happen very rare?
2. If you can reproduce the issue easily, could you help me to test some different versions of Vimium C?
- 1. firstly, please **export and backup your Vimium C configuration** by click `Export Settings` on Vimium C Options
- 2. here're two different versions: [vimium-c-5f62e61-chrome.zip](https://github.com/gdh1995/vimium-c/files/10049357/vimium-c-5f62e61-chrome.zip) (old) and [vimium-c-f89f1b8-chrome.zip](https://github.com/gdh1995/vimium-c/files/10049358/vimium-c-f89f1b8-chrome.zip) (new)
- 3. you may load them following steps in https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package
- 4. with each version loaded, please test how Vimium C behave on those websites
- 5. don't forget to re-install a latest Vimium C from web store.

**Comment by gdh1995** [comment]
Today I could not reproduce this issue on Brave v1.43.93 for Windows x64 and Vimium C v1.99.3 / v1.99.8.

1. Could you provide some log messages on the `Console` panel of `Developer Tools` (opened by `⌘ + Option + i`)?
2. What will it be, if you disable all other extensions on your Brave browser, reload all tabs and then redo tests?

**Comment by sharimot** [comment]
Thank you so much for your kind and detailed reply!

After reinstalling Vimium C, the bug magically went away.

I'm sorry for bothering you.

Thank you anyway.

It might be a good idea to encourage bug reporters to reinstall the extension before submitting issues.

**Comment by gdh1995** [comment]
Um did your Vimium C's configuration change acrossing re-installing?

**Comment by sharimot** [comment]
No, I just imported the settings that I exported from the previously installed version.

**Comment by sharimot** [comment]
I probably discovered the true cause of the bug.

As can be seen on [this comment](https://github.com/gdh1995/vimium-c/issues/646#issuecomment-1150864580), I installed the original Vimium bug before I discovered the bug.

Yesterday, I uninstalled the original Vimium along with Vimium C and then reinstalled Vimium C only.

The issue was resolved.

But today, I reinstalled Vimium and encountered the bug.

After I disabled Vimium, the bug disappeared.

I assumed that the reinstallation of Vimium C was what allowed me to solve the bug, but it turned out that the uninstallation of **Vimium** was probably the real reason I was able to solve this bug.

Sorry for my mistake.

**Comment by gdh1995** [comment]
A bit strange, because Vimium C should work with Vimium - there's only one conflict that, if Vimium handles keyboard events earlier than Vimium C, then some key mappings of Vimium C won't work, but if you do meet this Vimium's key mappings will do something and you should have noticed it.
