### ISSUE TITLE
When enable link namd and url filtering, english characters used for lint doesn't work

### ISSUE THREAD

**Issue by zyf0330** [gdh1995/vimium-c#738]
**Describe the bug**
When enable link namd and url filtering, english characters used for lint doesn't work. Wrong link hint is activated.

**To Reproduce**

1. enable `Use the link's name and characters for link-hint filtering`
2. set `Characters used for link hints` to `qwerasdfg`
3. use `f` and enter link hint

**Browser, OS and Vimium C versions**

- Browser name: Chrome
- Browser version: Version 105.0.5195.125 (Official Build) (64-bit)
- Vimium C version: 1.99.3
- OS name and version: Ubuntu 22.04

**Comment by zyf0330** [comment]
Yes, you are right.
If unchecked `Use the link's name and characters for link-hint filtering`, I can use both lower and upper case to filter hint names, if checked, I can just use upper case to filter.

But I didn't see it in the doc.

Thank you. I can use just numbers.

**Comment by gdh1995** [comment]
Um yes Vimium C has quite few documents and there're tons of parameters not explained.
