### ISSUE TITLE
`feature-request:` link name filtering without numeric hints

### ISSUE THREAD

**Issue by pc00per** [gdh1995/vimium-c#739]
**`Miscellaneous : Use the link's name and characters for link-hint filtering`**
Under this option, give us the ability to remove [numeric hints](https://user-images.githubusercontent.com/83843264/192688084-9170662b-533e-4907-8bd0-75d498870089.png) & directly utilize [blue hint boxes](https://user-images.githubusercontent.com/83843264/192688137-7085ebc6-ef14-4634-a58f-547e9faaa55d.png) after it's selection. Would look much cleaner. You can show **link name mode** status below (similar to visual mode as an acknowledgement).

**`TL;DR`**: Don't use **link hints** for **link name mode** at all. Just hint them with **blue boxes** after user typed them.

**`Solution:`**
Use **directional selection** if multiple links exist with same name. After typing link name, give us selective navigation between them using either `arrow keys` (or) `j k` in general.

**`Reason:`**
- Link name filtering with numbers on them look are unappealing & unintuitive. 
- Another reason is [numeric links](https://user-images.githubusercontent.com/83843264/192688185-7451d808-29d7-474d-be16-fa475fd0166f.png) exist. And it's link name is always a different number, which is very unusual. My above approach is both visually appealing, as well as functionally better at the same time.

**Comment by gdh1995** [comment]
But if remove hint ID totally, then it can be much harder to select a hint among many links and buttons with a same text title.

If you do want to hide hint ID, you may change CSS for hint markers at this place:
![image](https://user-images.githubusercontent.com/5547703/194532786-9444e1bd-9924-4650-a05d-ea31c403bcfb.png)

For example, you may make hint markers translucent or have no background:
![image](https://user-images.githubusercontent.com/5547703/194533869-14138609-2312-4bbe-8d54-bf08a4d75202.png)

BTW, if `Use the link's name` is enabled, then <kbd>Tab</kbd> key will switch "the current selected hint" among all visible hints, so you may press Tab and Shift+Tab to select a hint.

**Comment by gdh1995** [comment]
And to work with number text, you may fill `Characters used for link hints` with some rare characters, like `!@#$%^&*()`.

![image](https://user-images.githubusercontent.com/5547703/194534393-b1f3350b-0690-4bbf-8cc5-7075309f93be.png)

**Comment by pc00per** [comment]
Tq for your suggestion. But this still doesn't fix my 2nd reasoning.
> Another reason is [numeric links](https://user-images.githubusercontent.com/83843264/192688185-7451d808-29d7-474d-be16-fa475fd0166f.png) exist. And it's link name is always a different number, which is very unusual. My above approach is both visually appealing, as well as functionally better at the same time.

**Comment by gdh1995** [comment]
When you use `!@#$%^&*()`, "link number" will be `!` (1), `@` (2), ..., `!#` (13) and so on, and number characters in "link text" will be treated in the same way LinkHints treats letter characters.

Because 1) Vimium C always assigns a unique number to every hint, 2) and hint numbers are arranged from 1 to the count of all hints, then up to now Vimium C only assign a same "link number" to an numeric-text element if its number doesn't exceed the count.
