### ISSUE TITLE
Help shortcut (?) doesn't work on CH-DE keyboard

### ISSUE THREAD

**Issue by blankster** [gdh1995/vimium-c#74]
First of all, thanks a lot for your extension! You made my life a lot better, especially as your extension works with habitica.com :)

As I'm still in the learning process, I need the help-overlay very often (shortcut "?"). This shortcut doesn't work (**it does in the original vimium extension**), on CH-DE keyboard layouts (https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/KB_Swiss.svg/1920px-KB_Swiss.svg.png) shift needs to be pressed to input a "?".

_I think that's a bug and there are quite a lot keyboard layouts which are needing a modifier key like shift to input a "?"._

My setup:
- Win 10 x64
- Latest Chrome
- Latest extension version
- Keyboard layout: CH-DE (Swiss German)

Please let me know if I can provide more information to help you to help me/us. And thanks again!

**Comment by gdh1995** [comment]
You may:
* disable the advanced option "ignore keyboard layout"
* or try pressing Shift and this button:

![image](https://user-images.githubusercontent.com/5547703/65371875-d51c8080-dc9a-11e9-9894-fa84d1778fa2.png)

**Comment by blankster** [comment]
Thanks a lot for your ultra-fast reply 👍 👍 👍 

Both approaches worked, I decided to deactivate "ignore keyboard layout" as this problem occurs also with other problems (like find "/").

**Comment by gdh1995** [comment]
Thanks for this issue. It is indeed a mistake that I once made "ignore keyboard kayout" enabled by default on Vimium C v1.77 . I've decided to switch back to the old behavior ("disabled" by default), and it may be arrived in v1.78.

**Comment by blankster** [comment]
Thanks for caring 👍 
Offtopic: I've also edited https://habitica.fandom.com/wiki/Accessibility and added a link to your Chrome extension - it's the only one I've tested which works together correctly with [Habtica](https://habitica.com).
