### ISSUE TITLE
建议命令列表的关闭按钮始终显示或者点击窗口外部区域自动关闭

### ISSUE THREAD

**Issue by iamqiz** [gdh1995/vimium-c#740]
命令列表的关闭按钮如下
在滚动条滚动底部时,关闭按钮就点击不到了, 这时候得按esc才能关掉
建议命令列表的关闭按钮始终显示或者点击窗口外部区域自动关闭该窗口
thanks !🥰

![Snipaste_2022-09-30_22-28-33](https://user-images.githubusercontent.com/48077521/193292330-f4425d80-9cfa-4ebf-97d8-2cfeaf7599fa.png)

往下稍微滚动
![Snipaste_2022-09-30_22-27-54](https://user-images.githubusercontent.com/48077521/193292145-6fb18102-caf8-40e5-9824-c2e7bc1b5bf4.png)

**Comment by gdh1995** [comment]
感觉必要性不大。目前已经有参数可以让点击帮助对话框外边时自动关闭帮助对话框：
```
map ? showHelp exitOnClick
```
![image](https://user-images.githubusercontent.com/5547703/194905467-0218e68c-2cc9-468e-976b-89e95570345c.png)

**Comment by iamqiz** [comment]
我试了,用?打开的帮助 可以点击外面区域进行关闭
但如果是通过点击下图链接打开的帮助,无法通过点击外部区域关闭
![Snipaste_2022-10-11_02-23-25](https://user-images.githubusercontent.com/48077521/194930132-e763aead-877a-4010-ad39-44166d316fc1.png)

**Comment by gdh1995** [comment]
呃这个就不重要了吧，又不经常用它。我回头看看，好改的话我就改

**Comment by iamqiz** [comment]
好的,感谢大佬😄

**Comment by gdh1995** [comment]
最新版应该自动沿用"`?`"的参数了，你试试

**Comment by iamqiz** [comment]
@gdh1995  可以了! 大佬真给力! 听我说谢谢你，因为有你，温暖了四季~😁
