### ISSUE TITLE
closeTabsOnLeft command does not work properly

### ISSUE THREAD

**Issue by fievell** [gdh1995/vimium-c#741]
When closeTabsOnLeft was set as default($count=0), it works correctly and close all the tabs on left. But when '$count' was set beyond 0( I've tried 1 and 2), the closeTabsOnLeft command close the tabs on right

**Comment by gdh1995** [comment]
Um, it works as designed. Usually you only need `count=***`, while `$count` has been used by some commands to represent "direction" - `closeTabsOnLeft` is the same as `closeTabsOnRight $count=-1e6` (`1e6` is a trick meaning all tabs at one side). So:
- `closeTabsOnRight $count=1` means to close 1 tab at right
- `closeTabsOnRight $count=-2` means to close up to 2 tabs at left
