### ISSUE TITLE
How to add more than one element ?

### ISSUE THREAD

**Issue by Butek1** [gdh1995/vimium-c#742]
It dont work
clickable=''.element1" ".element2"

**Comment by gdh1995** [comment]
Well, it's `clickable=".ele1,.ele2"` - the value of `clickable` should be a correct CSS selector (https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors) and will be passed to `querySelectorAll` (https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll).
