### ISSUE TITLE
F1 stopped working

### ISSUE THREAD

**Issue by Judykator** [gdh1995/vimium-c#745]
After installing the extension, the keyboard shortcut - F1 - assigned to another within Firefox stopped working

**Comment by gdh1995** [comment]
`F1` will be consumed by Vimium C by default, and you may unmap it by modifying Vimium C Options:
```
unmap <f1>
```

And then click `Save Options`:

![image](https://user-images.githubusercontent.com/5547703/194765400-9d9eabea-2fac-4580-9c31-527a96bced80.png)
