### ISSUE TITLE
vimium dont work if i run a file on localhost

### ISSUE THREAD

**Issue by Butek1** [gdh1995/vimium-c#747]
**if I run index.html on my PC then Vimium dont work in this index.html**

**How should a feature do**

When a user has done such steps:

https://www.youtube.com/watch?v=t7_1jxUIPbk

then Vimium C should do:

**Browser and OS**

- Vivaldi	5.4.2753.51 (Stable channel) (Готово обновление 5.5.2805.32) (64 бита) 
- Version	6a886b3dacf7a1a5a6d68e6e55f92bc0abaf2aa3
- ОС	Windows 10 Version 1909 (Build 18363.657)
- JavaScript	V8 10.4.132.24
- Vimium version  1.99.3

**Comment by bommbo** [comment]
you can try qutebrowser.

**Comment by gdh1995** [comment]
Usually it's a limitation of your browser and you may enable it manually:
- Chrome: 
![image](https://user-images.githubusercontent.com/5547703/194798784-7cb3f8eb-e74d-49f6-9292-cea00dc52869.png)
- Vivaldi:
![image](https://user-images.githubusercontent.com/5547703/194799105-e615e60a-8cc2-434a-b22a-8e6dd67672ac.png)
