### ISSUE TITLE
How do I turn off vimium c for certain websites?

### ISSUE THREAD

**Issue by rew1nter** [gdh1995/vimium-c#748]
I don't want to run it on `youtube.com` for example. How can make vimium c not start there?

**Comment by bommbo** [comment]
May be you can try this extension [extensions-manager](https://chrome.google.com/webstore/detail/extension-manager/gjldcdngmdknpinoemndlidpcabkggco)

**Comment by gdh1995** [comment]
Vimium has a built-in feature to do so: when you're on a youtube.com tab, click the Vimium C icon at the top-right corner, and then click `Save Options` on Vimium C's popup dialog, then it will be fully disabled on youtube:
![image](https://user-images.githubusercontent.com/5547703/194798475-046dd142-513b-4d4a-9833-01e225dce8fb.png)

You may also make Vimium C partially disabled using the popup dialog.

It works the same to modify exclusion rules on Vimium C Options:
![image](https://user-images.githubusercontent.com/5547703/194798651-cf204088-59cb-44f0-8433-bc3fe085c9eb.png)
