### ISSUE TITLE
Alt + [Num] not working

### ISSUE THREAD

**Issue by worldpe** [gdh1995/vimium-c#749]

**Comment by gdh1995** [comment]
Do you mean "`Alt+Num` to go to N-th tab didn't work after you installed Vimium" ?

If so, then it's a known compatiblity issue on Firefox - see https://github.com/philc/vimium/issues/4129#issuecomment-1271386217:
> I think this issue is because you've enabled `privacy.resistFingerprinting` in `about:config` on Firefox, while the flag make Firefox never report status of `Alt` keys to Vimium. As a result, Vimium only received number key events and thought you were typing "prefix count numbers" for a following Vimium command, and then blocked them.
> This can not be fixed, because `privacy.resistFingerprinting` is designed to do so by the Firefox maintainer team.
>
> You may disable the flag of `privacy.resistFingerprinting`. Or you can add `1234567890` as exclusion passkey on Vimium Options, but this way means you can never use count prefix for Vimium commands any more:

![image](https://user-images.githubusercontent.com/5547703/194528803-52f29fa6-a81d-4af1-a451-de12a4f75d96.png)

**Comment by gdh1995** [comment]
And, if you use only `123456789` as exclusion keys, then you may press `0` to notify Vimium C you want to type a count prefix, and `02j` will mean `scroll down by twice the distance`.
