### ISSUE TITLE
[Chrome] Import Settings broken

### ISSUE THREAD

**Issue by wallace11** [gdh1995/vimium-c#75]
Steps to reproduce (Chrome):
1. [Machine A] Export settings
2. [Machine B] Import settings from external file
3. [Machine B] Settings are recognized - hitting "OK" does nothing

Ironically enough, when [Machine B] is Firefox, it works.

**Comment by gdh1995** [comment]
Confirmed. Thanks.

As said in https://github.com/gdh1995/vimium-c/issues/27#issuecomment-533863177, this bug has been fixed but is still waiting for a new release.

**Comment by gdh1995** [comment]
Fixed by v1.78.0 for Chrome.
