### ISSUE TITLE
support for `chrome-extension://**`

### ISSUE THREAD

**Issue by pc00per** [gdh1995/vimium-c#752]
**What command or commands**
Similarly on how `chrome://**` support included, is it possible the same for `chrome-extension://**`? Caz I wanna use it on other extension pages too.

**How should a feature do**
Give us an option to run vimium-c on chrome-extension:// pages too (preferably below chrome:// settings). Whether to enable it bydefault is your choice btw.

**Browser and OS**
- Browser name: Chromium
- OS name: ArchLinux (btw)

**Comment by gdh1995** [comment]
It requires modifications on other target extensions: see https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions .

**Comment by pc00per** [comment]
> It requires modifications on other target extensions: see https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions .

So this would require code modification of other extensions ?

**Comment by gdh1995** [comment]
yes



---Original---
From: ***@***.***&gt;
Date: Fri, Oct 14, 2022 11:11 AM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] support for `chrome-extension://**` (Issue#752)




  
It requires modifications on other target extensions: see https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions .
  
So this would require code modification of other extensions ?
