### ISSUE TITLE
Feature request for PDF Viewer for Vimium C in edge

### ISSUE THREAD

**Issue by Wongboo** [gdh1995/vimium-c#755]
Feature request for PDF Viewer for Vimium C in edge, PDF Viewer for Vimium C does work in edge, but it'll triger pdf viewer in chrome with some modification, which is far different from pdf viewer in edge in UI and functionality. Or add it as an openable option

**Browser and OS**

- Browser name: MS Edge

In edge
<img width="1308" alt="截屏2022-10-17 09 45 48" src="https://user-images.githubusercontent.com/44860323/196072061-93c08cff-5a8f-4ea4-a9c2-bb64a792f685.png">
In extension
<img width="1308" alt="截屏2022-10-17 09 46 50" src="https://user-images.githubusercontent.com/44860323/196072137-ff10ad07-5eb2-4ec0-8b54-4ed405dbe809.png">

**Comment by gdh1995** [comment]
It's impossible to run non-bulitin extensions on Chromium's built-in PDF viewer page, so `PDF Viewer for Vimium C` has to hook access to PDF files and show its own JS-based viewer.

**Comment by Wongboo** [comment]
Alright, I understand, so it is not the pdf viewer in chromium but a new pdf viewer provided by extension, maybe pdf.js?

Another question: is it possible for pdf viewer provided by extension change dark and light theme according to browser's setting? Might be an upstream feature request.

**Comment by gdh1995** [comment]
Yes it uses `pdf.js`. Light and Dark themes have been supported by PDF.js:
![image](https://user-images.githubusercontent.com/5547703/196390853-269c262e-ff76-4ce4-9b2e-bcb3c9b78ffc.png)

**Comment by Wongboo** [comment]
thx for explanation!
