### ISSUE TITLE
Send arbitrary text to website

### ISSUE THREAD

**Issue by hacker-DOM** [gdh1995/vimium-c#756]
Hi again!

I'd like to ask if it is possible to send_text to a website?

I have `t` bound to an important command, yet `t` on github.com opens fuzzy search which is also a really cool feature! :D Would it be possible to do something like:

mapSendText T t

I'm using `send_text` for the verb bc Kitty does so too :-) https://sw.kovidgoyal.net/kitty/actions/#action-send_text

**Comment by hacker-DOM** [comment]
Ah, just found https://github.com/philc/vimium/wiki/Tips-and-Tricks#using-the-escape-key-in-inputs

It does solve my immediate problem, but the feature request still holds for other uses cases! :)

**Comment by gdh1995** [comment]
There's a command named `dispatchEvent` for this, and you may see some usages in https://github.com/gdh1995/vimium-c/issues/560#issuecomment-1051557063 .

Basically, this should work:
```
map <v-de_t> dispatchEvent key="t-84"
run T de_t-de_t
```

**Comment by FranklinYu** [comment]
Dahan, I tried this:

```VimL
map <v-de_k> dispatchEvent key="k-75"
run K de_k-de_k
```

But it actually registers <kbd>k</kbd> instead of <kbd>Shift</kbd> <kbd>k</kbd>. The page doesn’t react on <kbd>Shift</kbd> <kbd>k</kbd>. If I replace it with `run k` then it registers <kbd>Shift</kbd> <kbd>k</kbd>. Capital case and small case seem to be switched. Is this a bug?

**Comment by gdh1995** [comment]
@FranklinYu What did you mean by the word of `register`?

The `k-75` means a lower-case letter of `k`, while `run K` means the upper-case one. So if your CapsLock is on, a single `k` key will trigger `run K`; if it's off, then `<Shift>` + `k` will mean `run K`.

**Comment by FranklinYu** [comment]
By “register” I meant “to register a binding between the key and the command”. So I want Vimium-C to pass through the lower-case `k`, but `run k` doesn’t do that. When I was debugging my set-up, I found that `run k` actually passed through the upper-case k (i.e. `K`).

**Comment by gdh1995** [comment]
What do you mean by `pass through`?

`k` (lower-case) is just the letter K key; while if you write `run K`, then Vimium C won't act on the key, unless:
1. CapsLock is on
2. or you're also holding on `Shift` key.
