### ISSUE TITLE
Scrolling is got lagging when you have video or image element.

### ISSUE THREAD

**Issue by Monirzadeh** [gdh1995/vimium-c#757]
**Describe the bug**

if you Scrolling site after a while it start lagging if you get to video or image element

1. open a website with lots of image or video (twitter or any other website)
2. start scrolling with `j` or `k`
after a while, scrolling is not smooth anymore

Sidenote: if you use arrow key, it is less lagging, but if you use Scroll wheel on mouse it is not lagging at all.
I am not sure how exactly, But I think somehow Scroll wheel mechanism is different from normal scrolling (that currently use). So we can't see this annoying lag when we scroll page with mouse scroll.
Is there any way `j' and 'k' simulate specific mouse wheel scrolling instead of current mechanism?

**Browser, OS and Vimium C versions**

- Browser name: brave
-  Version 106.0.5249.65
- Vimium C version: 1.99.3
- OS name and version: arch linux

**Comment by gdh1995** [comment]
Yes Vimium C's scrolling is implemented independently and different from browsers' native scrolling logic.

When a browser runs smooth scrolling, it knows `I'm scrolling` and then it doesn't send some types of mouse events and delay loading resources for a while. But Chrome and Firefox doesn't expose APIs to web extensions, so when Vimium C tells a page to scroll, the browser will still run all heavy work just as when there's no scrolling.

This can not be fixed, unless those browsers add such an API.

**Comment by Monirzadeh** [comment]
> APIs to web extensions

I do a little investigation and find extensions that get wheel events. [This](https://chrome.google.com/webstore/detail/mouse-gesture-events/ogjdgjefnddnjhkibmblgiofbjdgnahc/related) extension, for example.
I can find this[ document](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API#browser_compatibility) too.
If I am not wrong, viminium-c create an invisible mask over web content. So, can we use that and implement something like [this](https://www.sitepoint.com/html5-javascript-mouse-wheel/)?

**Comment by gdh1995** [comment]
Um, when Vimium C finds it scrolls too slow, it will try creating a mask to hide mouse events for "some" webpage JS event listeners.

An extra mask will usually make further scrolling faster, but if you find it fails, then you may disable this mask by such a mapping:
```
map j scrollDown keepHover
map k scrollDown keepHover
# map xxx scroll*** keepHover
```

**Comment by gdh1995** [comment]
`PointerLock` is not related.

The keypoints of a browser's native scrolling are:
1. not compute `:hover` state changes until scrolling ends: https://chromestatus.com/feature/6058736774807552
2. scrolling tasks have much higher priority than JS `onscroll` listeners and `requestAnimationFrame` callbacks

However the 2 points (especially the 2nd) are not controllable by JS code including web extensions.
