### ISSUE TITLE
请问有办法在Vomnibar.activateTabs中以是否查看过作为filter吗

### ISSUE THREAD

**Issue by Fuann-Kinoko** [gdh1995/vimium-c#758]
我用鼠标中键打开了很多页面，但是没有查看这些页面
似乎这些页面在Vomnibar.activateTabs中是以星号着重标注的

![](https://p.sda1.dev/7/cc9f762b14769572686a061d845a7d41/image.png)

请问有办法让vomnibar只显示这些打开了但未查看过的页面吗？

**Comment by gdh1995** [comment]
Not now, but you may use `map T Vomnibar.activateTabs preferTabs` to give such tabs high priorities.

**Comment by Fuann-Kinoko** [comment]
谢谢！看起来`Vomnibar.activateTabs preferTabs="new"`对我来说已经足够了
