### ISSUE TITLE
问题及建议

### ISSUE THREAD

**Issue by Solar-Lancelo** [gdh1995/vimium-c#76]
问题:
1. 关闭右侧标签页, 一次只能关闭一个而非右侧全部
2. 在火狐浏览器上全局快捷键是否可用, 关于配置全局快捷键的说明很难找到
3. Vimium中一些命令在 vimium-c 的 Show available commands 没有, 例如看小说时进入上一章/下一章的快捷键

建议:
1. 对于那些没有map快捷键的命令希望在Show available commands 里面可以直接看到, 而不是去查wiki, 这样添加新的快捷键时太麻烦了

**Comment by gdh1995** [comment]
1. 支持“数字”+“命令快捷键”模式，比如“9x”会关闭9个标签页，如果右边没有9个则往左边找，而如果整个窗口的标签页少于9/2=4.5个，那么只会关闭当前和右侧的标签页，所以可以这么写:

```
map Xc closeTabsOnRight
map XC closeTabsOnRight count=9999
```

然后按<kbd>9999Xc</kbd>或者<kbd>XC</kbd>就可以关闭右侧所有。

2. 全局快捷键可用，难找是因为Firefox的页面设计比较坑。Vimium C设置页面提示了`参见 about:addons 上“工具”按钮的“管理扩展快捷键”`（最新版有中文界面了），意思是点击这儿：

![image](https://user-images.githubusercontent.com/5547703/65847406-00c2f900-e374-11e9-9bfd-a62d08eb48a5.png)

3. 帮助对话框右下角有个”显示高级命令“的按钮，点一下就有了。

4. 当且仅当在Vimium C的选项页面上时，Show available commands 里会显示所有命令，包括所有没有映射过的。

**Comment by pkpkoko** [comment]
浏览器: Firefox 68.1.0esr (64-bit)

1. 只能显示map过的快捷键
![1](https://user-images.githubusercontent.com/52375886/65936411-135e3080-e44f-11e9-9902-461aa3fbe074.PNG)

2. 调出搜索框时, 建议鼠标点击空白处可以移除那个搜索框, 或者通过该命令加参数实现
3. 只能在Vomnibar.activate使用自定义的搜索引擎, Vomnibar.activateBookmarksInNewTab调出的搜索框就不能使用自定义的搜索引擎, 不知道能不能整合进去, 其他几个搜索框没有试
4. 关闭右侧标签页,主流浏览器的都是关闭右侧所有标签页, 对于新用户来说, 心理上也会是这么认为的,  用户再去百度的话增加了不少时间成本, 很影响体验的, 可以考虑不加参数的这条命令默认关闭右侧所有标签页
5. 最关键的在[Show available commands]里没有closeTabsOnRight这条命令, 这不就很尴尬了吗
![2](https://user-images.githubusercontent.com/52375886/65936522-79e34e80-e44f-11e9-8124-d31b41f660b7.PNG)
6. 全局键在新标签页,扩展管理页面...
- removeTab  可用
- goForward        Vomnibar.activate  不可用

```
shortcut userCustomized1 command="goForward"
shortcut userCustomized2 command="Vomnibar.activate"
```

**Comment by pkpkoko** [comment]
7. 火狐设置全局键后, 请问该要怎么清除掉
8. 有没有**完整的**命令参数的**文档**, 比如removeTab 后浏览器focus左边的标签页,

**Comment by gdh1995** [comment]
1. 问题确认存在，下一版修复
2. 还在考虑加不加
3. 支持使用“:o”前缀，可以从history、bookm等模式切换回到omni（混合）模式，例如：
  * 输入“:o b abc”可以在任意模式的Vomnibar里保证用“b”这个搜索引擎搜索“abc”
4. 会修改这个命令的中文说明
  * 比如这个命令的英文说明里，tab会改成单数
5. 属于问题1造成的
6. 技术上做不到在新标签页和扩展管理等（about:***这一系列）页面上显示Vomnibar，goForward的话在Firefox下不能用在这类页面上，只有在Chrome 72+上是全局可用的。
  * 可以考虑自己定制一个“新标签页”扩展，然后在里边主动加载Vimium C的lib/injector.js，就能用Vimium C的快捷键了。
  * 参考 #24 、https://github.com/gdh1995/vimium-c-helpers/blob/master/newtab/newtab.js#L7-L11

**Comment by gdh1995** [comment]
4. 我又看了看，似乎是我最初就对这个命令理解错了，我再想想怎么改
7. 不知道，我刚试了试没法删，这个只好怪Firefox了。可以先改成某个不会按的组合键
8.  没有，我精力有限，更愿意写新功能……

**Comment by Lancelo-L** [comment]
可能你的序号表错了..
![Screenshot_2019-10-02 Build software better, together](https://user-images.githubusercontent.com/52375886/66051573-b010f300-e561-11e9-8f77-7871759fbb5a.png)

**Comment by gdh1995** [comment]
哦那个是GitHub自动调整了markdown的标号。。。

4. closeTabsOnRight我决定改回默认“关闭所有”了，也就是说和Chrome和Vimium的默认用语一样
  1. 但是支持`map Xv closeTabsOnRight count=1`来回到旧的用法

**Comment by gdh1995** [comment]
补充：removeTab命令支持参数 goto=""/"left"/"right"/"previous" ，也就是 浏览器默认值、左、右、最近访问的前一个标签页。比如：`map x removeTab goto="left"`.

**Comment by gdh1995** [comment]
关闭搜索框的话，把鼠标移动到搜索框的文本输入框最右侧，会看到两个按钮，点那个❌就能关闭了。我再想想怎么加空白区域自动关闭。

**Comment by gdh1995** [comment]
v1.78.1 已经发布了。

1. 应该修复了

2. 现在showHelp和Vomnibar.*支持参数“exitOnClick”，比如 `map o Vomnibar.activate exitOnClick`，然后就能点击页面其它区域退出Vomnibar了。具体来说是点击 “当前页面（frame）上 不是由Vimium C显示 的内容”，会隐藏相应对象。

4. 现在closeTabsOnRight和closeTabsOnLeft默认都关闭一侧的所有标签，指定参数`$count=1`可以回到旧版行为，即关闭一侧指定数量的标签页

7. 根据我对Firefox 69的快捷键设置页面的分析结果，它没考虑需要解除绑定的快捷键的情况，也就是说，删不了。
  - 1. 我试了试删除Vimium C再加回来，不行
  - 2. 所以目前只能说是没办法
  - 3. 我一会去Firefox的反馈网站找找

**Comment by Lancelo-L** [comment]
好厉害
