### ISSUE TITLE
`n` must be pressed twice in Find

### ISSUE THREAD

**Issue by hacker-DOM** [gdh1995/vimium-c#760]
Is it just me or does find in page require you to press n twice to go to the second match? In Vim:

`/foo<CR>` go to first match

`n` go to second match

In Vimium:

`/foo<CR>` go to & higlight first match

`n` First match is not highlighted anymore

`n` Go to second match

Vimium 1.99.3, vivaldi 5.5.2805.38 (Stable channel) (x86_64) 

Thanks for Vimium C!

**Comment by gdh1995** [comment]
Um reproduced. As a working around, you may use `Ctrl-J` and `Ctrl+Shift+J`/`Ctrl+K` in `FindMode` to select other matches.

**Comment by gdh1995** [comment]
Hello, v1.99.90 has been released on Chrome Web Store, and you may take a try.
