### ISSUE TITLE
Enter caret mode without invoking visual mode ?

### ISSUE THREAD

**Issue by pc00per** [gdh1995/vimium-c#761]
`v -> c` to enter caret mode, is somewhat buggy. Because in some cases, I can't even enter into visual mode, erroring **Create a selection before entering Visual mode**.
Problem is, I can't do selections without caret mode. And it's only invoked inside visual mode (simple `c` doesn't work too).
I can use `/`. But the downside of `/` finder is, whenever I start typing a word on the current screen, the page jumps all over the place (finding other similar words on that page).
How to fix this chicken & egg thing ?

**Comment by gdh1995** [comment]
Um not possible yet, because I haven't found a way good enough to find "first visible text to select".

I'll take a try in recent months.

BTW, if you just want a key to replace `vc`, then you may write:
```
map c enterVisualMode mode="caret"
```

**Comment by pc00per** [comment]
Welp, I do need visual mode too, since I use it more primarily than caret. But the error is very random between `Create a selection before entering Visual mode` & `No usable selection, entering caret mode`. If the later warning occurs, it's easy to manage. But the former error is what bugs me.

**Comment by gdh1995** [comment]
The 1st tip means Vimium C can not find a "large enough" text paragraph.

**Comment by pc00per** [comment]
I think `Cannot find text paragraph here` is the correct tip, instead of `Create a selection before entering Visual mode`. Because you're literally asking user to select text where there's nothing on the page.
