### ISSUE TITLE
How to override Vomnibar opacity CSS

### ISSUE THREAD

**Issue by casprwang** [gdh1995/vimium-c#762]
**Describe the bug**

Can't override Vomnibar opacity CSS
**To Reproduce**

1. put following CSS in options and save
```
#bar { opacity: .8!important; }
#list { opacity: .8!important; }
#toolbar{opacity:.8!important;}
body { opacity: .8!important; }
```

2. activate Vomnibar

3. Vomnibar is not transparent when actively focused

**Browser, OS and Vimium C versions**

- Browser name: Chrome
- Browser version:  Version 106.0.5249.119 (Official Build) (arm64)
- Vimium C version: 1.99.3
- OS name and version: MacOS

**Comment by gdh1995** [comment]
You may need to add a prefix of `/* #omni */` - see https://github.com/gdh1995/vimium-c/wiki/Style-the-UI-of-Vimium-C-using-Custom-CSS#basic-structure

**Comment by casprwang** [comment]
It worked. I didn't know the special comments was needed 😀. Thanks!
