### ISSUE TITLE
Feature request: Vomnibar.activateInNewWindow

### ISSUE THREAD

**Issue by casprwang** [gdh1995/vimium-c#763]
**What command or commands**

similar request: https://github.com/philc/vimium/issues/4116

I understand that user can select search result with `shift` key to open in new window, but in many occasions user may want to have a short handed triggerer like `Vomnibar.activateInNewTab`, so that a single `enter` would just opens the result in a preferred tab/window. 

**How should a feature do**

When a user has done such steps:

```
map W Vomnibar.activateInNewWindow autoSelect newtab="force"
```

1. Press W
2. hit enter on first item

then Vimium C should do:

3. opens a new window with search result

**Browser and OS**

- Browser name: Chrome
- OS name:  MacOS

**Comment by gdh1995** [comment]
See https://github.com/philc/vimium/issues/4138#issuecomment-1272735979 :

> `LinkHints` supports a parameter of `newtab="window"`, most commands to open URLs support `reuse="new-wnd"` and there's a trick to make Vomnibar always open URL in new window. So a basic key mapping to do so is:
> ```
> map f LinkHints.activate newtab="window"
> # map xxx LinkHints.activateXXXXXX newtab="window"
> 
> map o Vomnibar.activateInNewTab clickLike
> mapKey <enter:o> <s-enter>
> 
> run <v-nw> $s#reuse="new-wnd" mask
> run t nw createTab
> run p nw openCopiedUrlInNewTab
> # run xxx nw openXXXXX
> ```

**Comment by gdh1995** [comment]
Also in https://github.com/gdh1995/vimium-c/issues/263#issuecomment-753814870 

> Hello, v1.88.0 has been released, and if you add `clickLike="chrome"` to mappings of `Vomnibar.activate***`, then `Ctrl/Alt/Shift` will work like Chrome itself deals with your click. So <kbd>Shift+Enter</kbd> will open in a new window.
> 
> (updated) For example: `map o Vomnibar.activate clickLike="chrome"`

**Comment by casprwang** [comment]
amazing! thanks again for the quick response. It could take a while for me to find those work arounds...

**Comment by casprwang** [comment]
actually I think the workaround might not be exactly the same as the feature requested.

The feature request is to have an additional `Vomnibar.activateInNewWindow` function/command, so that when user trigger `Vomnibar.activateInNewTab` and hit `enter` on results, a new tab will open, and `Vomnibar.activateInNewTab` will open a new window. 

the configurations would be something like:
```
map X Vomnibar.activateInNewTab autoSelect
map Y Vomnibar.activateInNewWindow autoSelect

// hit X and enter will open in new tab
// hit Y and enter will open in new window
```

For the first comment workaround. 


> See [philc/vimium#4138 (comment)](https://github.com/philc/vimium/issues/4138#issuecomment-1272735979) :
> 
> > `LinkHints` supports a parameter of `newtab="window"`, most commands to open URLs support `reuse="new-wnd"` and there's a trick to make Vomnibar always open URL in new window. So a basic key mapping to do so is:
> > ```
> > map f LinkHints.activate newtab="window"
> > # map xxx LinkHints.activateXXXXXX newtab="window"
> > 
> > map o Vomnibar.activateInNewTab clickLike
> > mapKey <enter:o> <s-enter>
> > 
> > run <v-nw> $s#reuse="new-wnd" mask
> > run t nw createTab
> > run p nw openCopiedUrlInNewTab
> > # run xxx nw openXXXXX
> > ```


If we do `mapKey <enter:o> <s-enter>` I believe `Vomnibar.activateInNewTab` will always open a new window when user hit `enter`. We can't have two different function to open tab versus window. As I tried the following:

```
map X Vomnibar.activateInNewTab clickLike
map Y Vomnibar.activateInNewTab clickLike
mapKey <enter:o> <s-enter>
// hit both X and Y then enter will open in new window
```

For the second comment 

> Also in [#263 (comment)](https://github.com/gdh1995/vimium-c/issues/263#issuecomment-753814870)
> 
> > Hello, v1.88.0 has been released, and if you add `clickLike="chrome"` to mappings of `Vomnibar.activate***`, then `Ctrl/Alt/Shift` will work like Chrome itself deals with your click. So Shift+Enter will open in a new window.
> > (updated) For example: `map o Vomnibar.activate clickLike="chrome"`

This is the workaround I'm currently using, but as I mentioned from the original issue detail, sometimes user know whether to open in window or tab before hand. It would be great if we can start with a functional triggerer to open in windows/tabs, versus hitting `enter`/`s-enter`/`c-enter` at the end.

Hope that makes sense...

**Comment by gdh1995** [comment]
Well, there's a new way to do so:
```
map o Vomnibar.activateInNewTab itemKeyword="ow"
```
and
```
ow: vimium://run/openUrl#reuse=new-wnd&url=$s
```

![image](https://user-images.githubusercontent.com/5547703/197378986-9d05ce1e-2c3a-44f3-9299-337eb53eac19.png)

**Comment by casprwang** [comment]
wow, you rock! 🚀

**Comment by gdh1995** [comment]
Hello, the `ow` search engine needs an update to replace `$s` with `${s:%20}`:
```
ow: vimium://run/openUrl#reuse=new-wnd&url=${s:%20}
```
