### ISSUE TITLE
Vomnibar 界面鼠标滚轮不灵敏

### ISSUE THREAD

**Issue by actforjason** [gdh1995/vimium-c#764]
针对搜索结果，滚轮划得很快才识别为翻页，否则没反应。能提高灵敏度吗，因为搜索结果很多

**Comment by gdh1995** [comment]
呃这是为了兼容触摸板双指滑动，做了最小滑动距离的限制。你多滚动几次应该就行了吧，其实更建议用 Shift+上下箭头 来翻页，操作起来更稳定。

回头我加一个参数吧。

**Comment by gdh1995** [comment]
v1.99.96 现在支持了 `wheel-speed` 参数，表示对滚动消息里的”滚动距离“的放大倍数，默认是 1，你可以试试：
![image](https://user-images.githubusercontent.com/5547703/209478324-01518218-f831-406f-96ef-eb5dfede5354.png)

**Comment by actforjason** [comment]
工作正常
