### ISSUE TITLE
Comma (`,`) not working on google.com

### ISSUE THREAD

**Issue by hacker-DOM** [gdh1995/vimium-c#765]
I like to use `j k m ,` instead of `h j k l`. For that reason I'd like comma to `goForward`. It works on all websites, but not on www.google.com: I get `Press / to jump to search box` (even though comma and slash are different keys)

Is there any way to get past this with the powerful machinery of Vimium? :-)

- Browser name: 5.5.2805.38 (Stable channel) (arm64)
- OS name: MacOS 12.6
- Vimium C 1.99.3

**Comment by gdh1995** [comment]
So, did you mean "`,` on google.com on your Vivaldi browser didn't work"? Then do `j k m` work on it?

The tip of `press ... jump ...` is not Vimium C's, but Google's, and it means Vimium C didn't grab and block the key which "might be `Comma`" . I'm not sure why.

Is your system's keyboard layout English QWERTY or anything else? Will this issue occur again if you switch to an English IME?

**Comment by hacker-DOM** [comment]
Yes, all the other keys work, just comma doesn't work on google.com. It's been like that for a year, and for that reason I had to use `j k m .` but it's not good for my muscle memory.
It just seems that google.com is for some reason binding `,`, but it's strange, because normally when a website supports shortcuts (like github), vimium-c's take priority, whereas here google's do...

**Comment by gdh1995** [comment]
Then what's your keyboard layout? Google shows the tip on `keypress#comma`, while if Vimum C blocks a comma key, there should not be any `keypress#comma` event.

What's your key mapping line that you used to map `comma` key?

**Comment by hacker-DOM** [comment]
Standard US Layout

`map , goForward`

**Comment by gdh1995** [comment]
Could you test the comma key on https://gdh1995.cn/vimium-c/keyboard-test.html ?

macOS has a special mode, in which a system IME will convert punctuation keys into other non-ASCII characters.

And, what about disabling all other browser extensions except Vimium C ?

**Comment by hacker-DOM** [comment]
Yeah I get 

<img width="641" alt="image" src="https://user-images.githubusercontent.com/18601956/198847807-169f97e1-2784-48e9-b017-d6e426cd8ef2.png">

I tried disabling all extension (in incognito) and even VPNing in case it's a Czech google thing, to no avail

In the end though, I found it does work on Brave, so it might be a Vivaldi thing. I checked and I don't have any keyboard shortcuts bound to `,`. Do you know if there is some kind of debugger I could open in Chromium to investigate and be able to submit a Vivaldi issue? :)

**Comment by gdh1995** [comment]
Okay, then let me try Vivaldi.

**Comment by gdh1995** [comment]
I installed Vivaldi 5.5.2805.42 x64 on Win11, but didn't reproduct this.

Do you have any exclusion rules applied on google.com? If you once added some keys joined with `,`, then it would cause this issue - exclusion passKeys should be joined with not comma but space characters.
![image](https://user-images.githubusercontent.com/5547703/199278121-c9621fc3-a6b0-40c9-ac9e-46fad417cb0a.png)


Or could you export your Vimium C settings and share the file to me (gdh1995@qq.com) ?

**Comment by hacker-DOM** [comment]
Ah yes I had a , there. Sorry for this 😀🤦
