### ISSUE TITLE
建议在Vomnibar中翻页（Tab）到底可以循环到开始

### ISSUE THREAD

**Issue by actforjason** [gdh1995/vimium-c#769]
比如标签也就有两三页，一个按键循环遍历不需要另外一个按键倒回，这样比较便捷

**Comment by gdh1995** [comment]
这样不容易注意到“翻到最后，没有下一页了”，而且大部分网页、app都不会让正文循环滚动，也就广告图，或者水平循环滚动的轮播图会这样。
