### ISSUE TITLE
特定网站使用特定按键

### ISSUE THREAD

**Issue by backuponeday** [gdh1995/vimium-c#770]
感谢作者,插件很好用.只是有些用法自己没有设置成功.
所以请问高级用法中的`Map a key to different commands on different websites` 能出个中文的吗?不太能理解.

**问题**:
    **我想在特定的网页只使用特定的几个按键,我该如何设置?**

你的例子:
```env hn host="https://news.ycombinator.com/"

map F runKey expect={"hn":"<v-fhn>"} keys="<v-fd>"
map <v-fd> LinkHints.activateModeToOpenInNewTab
map <v-fhn> LinkHints.activateModeToOpenInNewTab match=".titlelink"
```

其中 
expect={"hn":"<v-fhn>"} keys="<v-fd>" 和
map <c-j:i> runKey expect={"input":"<v-j1>","select":{"keys":"<v-j2>",options:{}}} keys="<v-j0>" 是什么意思呢?

_使用版本_
MS Edge - 106.0.1370.52 (正式版本) (64 位) 
Vimium C [1.99.3]

**Comment by gdh1995** [comment]
`expect` 是一组条件，满足某个条件就会执行对应的快捷键，这里 `hn` 是条件名字，`<v-fhn>` 是条件对应的快捷键；`<v-fd>` 是 `expect` 都不满足的时候，默认执行的快捷键。

`hn` 和下边的 `input`、`select`都是条件名字。条件是用 `env` 开头的语句定义的。

https://github.com/gdh1995/vimium-c/wiki/Map-a-key-to-different-commands-on-different-websites 这种用法比较复杂，我是按设计功能的思路写的“语法描述”，而不是从使用者视角写的，所以确实难懂。有啥不确定的可以多试试，常用写法一般就是（对我来说）最直观的那种，试出来然后沿用、慢慢改进就行；也可以来 github 问我。
