### ISSUE TITLE
查看github代码时会崩溃

### ISSUE THREAD

**Issue by actforjason** [gdh1995/vimium-c#771]
https://github.com/stevencohn/OneMore/blob/main/OneMore/Properties/AssemblyInfo.cs
悬浮在文本上时会卡死

**Comment by gdh1995** [comment]
具体网址、浏览器名字和版本？vimium c配置导出成文件贴上来？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月27日(周四) 中午1:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [gdh1995/vimium-c] 查看github代码时会崩溃 (Issue #771)

**Comment by actforjason** [comment]
Chrome和360Chrome都会，都是最新版。
[vimium_c-20221027_143810.zip](https://github.com/gdh1995/vimium-c/files/9876407/vimium_c-20221027_143810.zip)

**Comment by actforjason** [comment]
不好意思，我又试了试好像没事了，之前情况是：
> Chrome和360Chrome都会，都是最新版。
[vimium_c-20221027_143810.zip](https://github.com/gdh1995/vimium-c/files/9876407/vimium_c-20221027_143810.zip)
网址就是上边那个

**Comment by gdh1995** [comment]
是直接提示“网页崩溃了”吗？那确实不应该出现。我这边不好复现，你可以查查是不是系统内存不够了。

或者，有可能是别的插件影响了，比如有个 Katalon Recorder 会导致一执行 enterFindMode 网页就崩溃。https://github.com/gdh1995/vimium-c/issues/457#issuecomment-945316509
