### ISSUE TITLE
duplicate in (background) new tab

### ISSUE THREAD

**Issue by hacker-DOM** [gdh1995/vimium-c#772]
Long story short: would it be possible to add an option `background` to `duplicateTab`, that would retain focus on the current tab? :-)

**Comment by gdh1995** [comment]
You may use `map yt duplicateTab active=false`

**Comment by hacker-DOM** [comment]
Nice! I don't see the option though 👀

<img width="331" alt="image" src="https://user-images.githubusercontent.com/18601956/198506579-c9744ef3-3cfc-44e2-9219-8863f1a0ccf3.png">

**Comment by gdh1995** [comment]
Yes the help dialog only shows quite limited parameter names. There're too many parameters to show.
