### ISSUE TITLE
How to temporarily disable Vimium C when activating other extension

### ISSUE THREAD

**Issue by fjchen7** [gdh1995/vimium-c#773]
When I activate the extension [Bookmark Sidebar](https://chrome.google.com/webstore/detail/bookmark-sidebar/jdbnofccmhefkmjbkkdkfiicjkgofkdh), the Vimnium C still works. As a result Vimium C still takes over the keys and I can't type in the search bar.

![image](https://user-images.githubusercontent.com/10106636/198841008-c7e52f05-d780-4d59-a8af-f9b89de8a835.png)

Only if I type keys (like `s`) that are not taken over by Vimium C, the cursor is focused on the search bar. That is much inconvenient for me.

What I'd like that is when I activate Bookmark Sidebar the Vimium C will be temporarily disabled. And after Bookmark Sidebar is dismissed (like I switch to another tab or open a new URL and jump) the Vimnium C returns to work.

How to do that? Very appreciate it if you can give some insights.

Environment: Chrome

**Comment by gdh1995** [comment]
You may disable features of Vimium C manually, by:
- pressing `i` to trigger `enterInsertMode`
- or press `gi` to trigger `focusInput` and focus an input element
- or turning on/off Vimium C in a single shortcut, as said in https://github.com/gdh1995/vimium-c/wiki/Enable-or-Disable-all-frames-by-a-shortcut

**Comment by gdh1995** [comment]
I tried the extension, and found a simple working around is to disable Vimium C on all `about:blank` pages:

![image](https://user-images.githubusercontent.com/5547703/198843367-e553c16b-8d67-4d84-bd84-900237b1e397.png)

**Comment by fjchen7** [comment]
Thanks. It works.
