### ISSUE TITLE
FR: Select text and enter visual LINE mode

### ISSUE THREAD

**Issue by random-un** [gdh1995/vimium-c#775]
Currently, there are three commands to enter visual mode:
1) `enterVisualMode`: enters "regular" visual mode
1) `enterVisualLineMode`: enters "line" visual line mode
1) `LinkHints.activateSelect`: shows hints before entering "regular" visual mode

Context:
* The amazing option 3 `LinkHints.activateSelect` unlocks incredible productivity workflows for me

Feature request:
* Introduce a command or option that shows hints before entering "line" visual mode
* To reproduce this currently I trigger the command, select my hint, and hit `V` to turn on line mode retroactively. Would be great to cut down a keystroke!

Thank you for the `activateSelect` feature! It's adds a ton of value on top of core Vimium.

**Comment by gdh1995** [comment]
```
map yV LinkHints.activateSelect then="mode=line"
```

**Comment by random-un** [comment]
Seems to work perfectly. Thank you again!! Wonderful extension. I'm resolving this bug.
