### ISSUE TITLE
复制图片功能失灵

### ISSUE THREAD

**Issue by Puuaru** [gdh1995/vimium-c#778]
**Describe the bug**

在edge浏览器下使用 yi 复制图片时会提示“已复制HTTP图片”，此情况会导致复制图片功能失灵，而在vimium c的设置页面中复制logo时显示“已复制PNG图片”则能成功复制

**Browser, OS and Vimium C versions**

- Browser name: Edge
- Browser version: 107.0.1418.26 (正式版本) (64 位)
- Vimium C version: 1.99.3
- OS name and version: Windows 10

![WOG6_X{AXGKQGV ZQQ7 1S](https://user-images.githubusercontent.com/38312096/199217494-70e8108d-4736-4b7c-b78c-df13a7fc8a53.png)

**Comment by gdh1995** [comment]
v1.99.99 已经发布，麻烦试试。
