### ISSUE TITLE
如何让 t 新建标签页在当前标签页的右边而不是最右边

### ISSUE THREAD

**Issue by wuqunzhi** [gdh1995/vimium-c#779]
如何让<kbd>t</kbd>新建标签页在当前标签页的右边而不是最右边
另外,问一下哪里可以看到带参数的所有命令, 例如removeRightTab可以带参数count=-1,  
我只找到[List-of-all-commands](https://github.com/gdh1995/vimium-c/wiki/List-of-all-commands),有没有一个规范的命令列表文档之类的

**Comment by gdh1995** [comment]
至于每个参数要怎么用、字符串类的参数可以取什么值，我一直没整理过，我自己也需要看源码才能确定。

**Comment by wuqunzhi** [comment]
好的,多谢

**Comment by retina007** [comment]
@gdh1995 
你好，但是使用newtab-adapter的时候，这个命令失灵了，只能在最右边新建标签页。怎么办，谢谢
（https://chrome.google.com/webstore/detail/newtab-adapter/cglpcedifkgalfdklahhcchnjepcckfn）
