### ISSUE TITLE
Link Hints on Scroll Bars

### ISSUE THREAD

**Issue by pc00per** [gdh1995/vimium-c#780]
Many websites have sub windows (such as chapters section in https://kavin.piped.rocks video playback) that needs to be scrolled. Although you can choose to select any element inside the sub window inorder to scroll. But the very example website I gave above, is to just scroll the subwindow, without need to activate any link inside it. Is it possible to have link hints on scroll bars, so that we can switch scrollable sections within a website ?

**Comment by gdh1995** [comment]
If a box is scrollable but not clickable, then `LinkHints` will mark its hint characters using dark red color; you may also use the command of `LinkHints.activateHover` to select a child element without activating (aka. clicking) it.

**Comment by pc00per** [comment]
Tqvm. Never explored vimium till now, getting used to know it perfectly now !
