### ISSUE TITLE
需要openSelectedUrlInNewTab

### ISSUE THREAD

**Issue by xchnotxzh** [gdh1995/vimium-c#782]
**What command or commands**

已经有openCopiedUrlInNewTab，得 c-c 然后 c-v 才能打开选中的url。
希望有一个openSelectedUrlInNewTab，一键打开选中的url。

**How should a feature do**

When a user has done such steps:

1. 选中url
2. 按openSelectedUrlInNewTab的关联按键

then Vimium C should do:

在新标签打开选中的url

**Comment by backuponeday** [comment]
vimium-c 有这个参数`LinkHints.activateOpenInNewForegroundTab`默认是按F.

**Comment by xchnotxzh** [comment]
> 

我说的选中url不是 LinkHints能选中的，比如在github里搜索url的结果，得手动鼠标选中。
例子：https://github.com/search?q=github.io&type=code

**Comment by xchnotxzh** [comment]
> 

我说的选中url不是 LinkHints能选中的，比如在github里搜索url的结果，得手动鼠标选中。
例子：https://github.com/search?q=github.io&type=code

**Comment by xchnotxzh** [comment]
> vimium-c 有这个参数`LinkHints.activateOpenInNewForegroundTab`,可以设置为`map F LinkHints.activateOpenInNewForegroundTab`.

我说的选中url不是 LinkHints能选中的，比如在github里搜索url的结果，得手动鼠标选中。
例子：https://github.com/search?q=github.io&type=code

**Comment by gdh1995** [comment]
试试 autoOpen 这个命令



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月4日(周五) 下午3:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [gdh1995/vimium-c] 需要openSelectedUrlInNewTab (Issue #782)




  
vimium-c 有这个参数LinkHints.activateOpenInNewForegroundTab,可以设置为map F LinkHints.activateOpenInNewForegroundTab.
  
我说的选中url不是 LinkHints能选中的，比如在github里搜索url的结果，得手动鼠标选中。
 例子：https://github.com/search?q=github.io&amp;type=code

**Comment by xchnotxzh** [comment]
> 试试 autoOpen 这个命令
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年11月4日(周五) 下午3:08 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [gdh1995/vimium-c] 需要openSelectedUrlInNewTab (Issue #782) vimium-c 有这个参数LinkHints.activateOpenInNewForegroundTab,可以设置为map F LinkHints.activateOpenInNewForegroundTab. 我说的选中url不是 LinkHints能选中的，比如在github里搜索url的结果，得手动鼠标选中。 例子：https://github.com/search?q=github.io&amp;type=code — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

autoOpen的确可以完成需求，我之前找过这个命令，但给命令注释误导了。

Cv Cd Cb Cg <a-f3>
--
  | Open selected or copied text in a new tab (autoOpen)

上面的注释看上去都是autoOpen，其实只有Cv是纯粹的autoOpen，其他的会让搜索引擎在打开，我试了几个就是没试过Cv。

**Comment by gdh1995** [comment]
大部分命令是可以带参数的，帮助页面没法列出参数只能这么聚合着显示。具体参数可以ctrl-f 搜 `map Cv` 或者 `run Cv`，搜到的才是具体参数
