### ISSUE TITLE
[Feature Request] Select/Highlight Tabs

### ISSUE THREAD

**Issue by hunkyburrito** [gdh1995/vimium-c#784]
**What command or commands**
Select multiple tabs to act on. Maybe with different ways to select such as selecting a range or holding a binding to select adjacent tabs.

**How should a feature do**

When a user has done such steps:

1. Map binding(s) to select tab (e.g. \<c-space\>)
2. Move to tab you want to select
3. Push keybind (e.g. \<c-space\>)

then Vimium C should do:

[Highlight](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/highlight) the tab

**Browser and OS**

- Browser name: Firefox 106.0.3 running Vimium C Version 1.99.3
- OS name: Windows Windows_NT 10.0 19043

**Comment by gdh1995** [comment]
Sorry, but I never use the `tabs.highlight` feature. What do you want to do if you highlight more than one tab?

**Comment by hunkyburrito** [comment]
The main use I was thinking of is actually to use with the Simple Tab Groups extension on firefox. It would allow me to select multiple tabs and then move them all to a new group. It could also be used with other vimium commands like deleting tabs, moving tabs to a new window, or pinning tabs that aren't in a row.

**Comment by gdh1995** [comment]
Currently, all of Vimium C commands support "count prefix", so `3x` will remove 3 neighboring tabs
To achieve this "range selection" feature, I've added tons of ugly code to compute left and right ends, which can be affected by quite a few different parameters and states.

Therefore, I'm afarid it would be too complex to support handling highlighted tabs well, so I think I won't implement it.
