### ISSUE TITLE
Feature Request: support commands in Vomnibar

### ISSUE THREAD

**Issue by hacker-DOM** [gdh1995/vimium-c#785]

**Comment by gdh1995** [comment]
Not supported directly, because Vomnibar has its own big key mappings, while you may use `mapKey xxx <v-xxx>` to do this trick - `Vomnibar` treats all `<v-xxx>` keys as command shortcuts.

That is to say, this means to `Alt-C` to go to left tab:
```
mapKey <a-c> <v-left_tab>
map <v-left_tab> previousTab
```
