### ISSUE TITLE
previousTab 和 nextTab 在 firefox 中突然失灵了

### ISSUE THREAD

**Issue by fightyz** [gdh1995/vimium-c#787]
**Describe the bug**

我自定义了 previousTab 和 nextTab：
<img width="926" alt="image" src="https://user-images.githubusercontent.com/1697504/200179811-ea942c86-a05e-4652-8632-082616aed18a.png">
可以看到 previousTab 为 K, nextTab 为 J，而且下方为 no changes，说明我已保存改配置。

但是按 ? 后，显示 K 依然为默认的 nextTab，J 为默认的 previousTab：
<img width="276" alt="image" src="https://user-images.githubusercontent.com/1697504/200180003-6ccec9cf-c5b3-4313-be8a-095a2ec491df.png">

按键事实上的行为也确实还是默认行为。

**To Reproduce**

无法复现，之前还是好的，今天突然就失灵了。我已重复设置过多次，enable/disable, install/uninstall 多次，依然无效。

**Browser, OS and Vimium C versions**

- Browser name: FireFox
- Browser version: 106.0.5
- Vimium C version: 1.99.5
- OS name and version: MacOS 13.0

**Comment by avnigo** [comment]
I can confirm I'm experiencing the same behavior after the update to [v1.99.5](https://github.com/gdh1995/vimium-c/tree/v1.99.5). I had the same mapping as follows, but it seems to be ignored:

```
map K previousTab
map J nextTab
```

I have the same browser version and OS too.

**Comment by gdh1995** [comment]
Confirmed that v1.99.5 has a related bug. I'll fix it today.

**Comment by gdh1995** [comment]
The details is, default mappings override your customized key mappings (by accident), so you may insert
```
unmap K
unmap J
```

to the first line of key mappings.

**Comment by gdh1995** [comment]
hello, v1.99.6 has been published and you may take a try.

**Comment by gdh1995** [comment]
hello, v1.99.6 has been published and you may take a try.

**Comment by avnigo** [comment]
Thanks for the great effort, @gdh1995!

`map` now overrides default mappings without needing to unmap, but v1.99.6 unfortunately breaks `unmap` for any default mappings if no custom mapping exists.

<img width="265" alt="image" src="https://user-images.githubusercontent.com/43263288/200287618-7b8fd860-2ac6-48ac-8d93-3395fdc015f6.png">

To unmap a default mapping you have to map it first (to something arbitrary) and then unmap it:

```
map <c-e> nextTab
unmap <c-e>
```

**Comment by the1derer** [comment]
@gdh1995  Any idea when will v1.99.6 will be available on Chrome Web store?
Thanks.

**Comment by gdh1995** [comment]
Hello, v1.99.7 was uploaded to Chrome Web Store on 2022/11/07, but their officers are still reviewing it. There's nothing I can do about this state - I can neither hurry them, nor withdraw v1.99.7 (to publish v1.99.8/9 instead).

BTW, `goNext` is still broken till v1.99.7, and the working around is:
```
unmap ]]
map ]] goNext noRel
```

(v1.99.6 was only available on Firefox and now it should have been hidden, so `unmap` is not broken up to now)

**Comment by gdh1995** [comment]
@avnigo Sorry I forgot to share the progress of fixing broken `unmap`. v1.99.7 has been released on Firefox Add-Ons and its `unmap` should work as expected.

**Comment by gdh1995** [comment]
Hello, v1.99.90 has been released on both Firefox Add-Ons and Chrome Web Store, and you may take a try. All above tricks should not be needed any more.
