### ISSUE TITLE
New Update Issues with Keybindings

### ISSUE THREAD

**Issue by sgreenden** [gdh1995/vimium-c#788]
**Describe the bug**
I have several custom keybindings that I use, however something I noticed in the new version is that even though they are set in the configuration section, it doesn't take effect anymore.

![image](https://user-images.githubusercontent.com/56249225/200195034-4e301168-861b-4271-9353-2c6e0f9a1aa1.png)
![image](https://user-images.githubusercontent.com/56249225/200195046-a1edaf12-eb4d-418d-b285-614b48e9da42.png)
As can be seen here, the mappings don't seem to be going in place now, and I am not sure why that is the case.

I am on Firefox Version 106.0.4 (64-bit) on Arch Linux
Vimium C 1.99.5

**Comment by gdh1995** [comment]
Confirmed that v1.99.5 has such a bug. Sorry. I'll fixd it today.

The details is, default mappings override your customized key mappings (by accident), so you may insert
```
unmap K
unmap J
```
to the first line of key mappings.

**Comment by gdh1995** [comment]
hello, v1.99.6 has been published and you may take a try.

**Comment by esfox** [comment]
On the Chrome Web Store, the version is still 1.99.5, so I can't update.

**Comment by gdh1995** [comment]
Um yes, Chrome Web Store will review every extension package before it publishes a newer version, and this process takes for days and can not be cancelled.

**Comment by sgreenden** [comment]
The new update fixed it, thanks.

**Comment by Itay123TheKing** [comment]
How do I get the new update or even downgrade until this is updated on chrome web store? My entire workflow is messed up now :P I guess I'll use the original Vimium for now

**Comment by gdh1995** [comment]
@Itay123TheKing You may insert some `unmap ***` rules to the start of key mappings, to work around this bug. Every `map xxx yyy` which `xxx` has a default binding will need a corresponding `unmap xxx`.

**Comment by random-un** [comment]
> hello, v1.99.6 has been published and you may take a try.

Vimium-C's [Chrome Web Store page](https://chrome.google.com/webstore/detail/vimium-c-all-by-keyboard/hfjbmagddngcpeloejdejnfgbamkjaeg?hl=en) still shows 1.99.5.

Have been holding off from unmapping -- hopefully the fixed version appears on the store soon!

**Comment by gdh1995** [comment]
Sorry again. Chrome Web Store is reviewing the new version, while the needed time is irregular.

**Comment by gdh1995** [comment]
Hello, v1.99.90 has been released on Chrome Web Store, and you may take a try. All above tricks should not be needed any more.
