### ISSUE TITLE
[BUG] Text manipulation in search frame not functional

### ISSUE THREAD

**Issue by n4n0GH** [gdh1995/vimium-c#79]
**Describe the bug**
When using the search frame `/`, it is not possible to select the entire typed text by using `Ctrl+A` or delete words using `Ctrl+Backspace/Delete`. Jumping over words with `Ctrl+Left/Right` works as expected.

**To Reproduce**
1. Open search bar
2. Enter any string to search for
3. Try using `Ctrl+A`

**Expected behavior**
Vimium enables users to still use general keyboard shortcuts to quickly delete search strings, this should work just the same in Vimium C.

**Additional context**
Browser: Firefox 69.0.1 64-Bit
Vimium-C: 1.78.1
OS: OpenSUSE Tumbleweed Linux

**Comment by gdh1995** [comment]
Thanks. Then I expect some more information:

Is there any error message on the console of the page when you press `Ctrl+A` and `Ctrl+Backspace`? The "console" can be opened by: click the main menu at the top-right corner, select "Web Developer" and then select "Web Console" .

What it does on Vimium C Options page?

What it will do, if you disable all other installed web-extensions (except Vimium C) of the Firefox?

**Comment by n4n0GH** [comment]
Console: No additional output appears when using the mentioned combinations.
Vimium-C Options Page: No observable behavior; just like on other pages. Also no console output.
Other plugins disabled: No change to behavior.

**Comment by gdh1995** [comment]
What about Chrome or Chromium?

**Comment by n4n0GH** [comment]
I don't know, I don't use those browsers.

10. Okt. 2019, 07:54 von notifications@github.com:

**Comment by gdh1995** [comment]
What's your desktop environment, Gnome or KDE ?

I know little about openSUSE, and the line above was just learned a few minutes ago... So any other information is also useful.

**Comment by n4n0GH** [comment]
I'm using KDE 6.62 with Plasma 5.16.

**Comment by gdh1995** [comment]
Confirmed on KDE.

**Comment by n4n0GH** [comment]
Great! Looking forward to that :)

**Comment by gdh1995** [comment]
Vimum C v1.78.2 has been released on Firefox Add-ons, so you may take a try. Thanks!

**Comment by n4n0GH** [comment]
Update fixed the problem. Very nice!

**Comment by naoric** [comment]
I experience almost the same behavior in version 1.90.2 (Firefox), with the only exception that Cmd+A is working. 
Other than that, when I select everything and start typing, the selected text remains and the text is being inserted at the beginning of the search box. 

The only way to clear the input is by closing and reopening the search box. 

No console errors, I can't tell why it happens. I have disabled other extensions and the problem persists. 
Using Firefox Developer Edition 91.0b6 (64-bit) for Mac.

**Comment by gdh1995** [comment]
@naoric Seems a new bug of Firefox. Vimium C doesn't nothing on a `Backspace` / `Delete` key but Firefox 91.0b7 x64 on Win10 also has such an issue.
