### ISSUE TITLE
vomnibar white flash

### ISSUE THREAD

**Issue by rivke41levp656** [gdh1995/vimium-c#790]
sometimes when opening the vomnibar there is a brief white flash before it opens. I think this is a regression introduced in 1.99.4 or 1.99.5 - I do not notice the behavior on another machine that is running 1.99.3

Sorry for the imprecision, I am not really sure since it doesn't happen on every webpage but:
open a new tab and open the vomnibar. Most of the time it will flash white before loading. It seems that all subsequent calls of vomnibar on that tab will then be OK

I am using:
firefox 106.0.5
vimium c 1.99.6

**Comment by gdh1995** [comment]
Um it may be caused by a patch which is to fix a obvious latency when Vomnibar shows on Chrome... I'll take a try in days.

**Comment by gdh1995** [comment]
Have you enabled a dark theme of your system or Firefox, or used extensions like Dark Reader ?

**Comment by gdh1995** [comment]
Hello, v1.99.7 for Firefox has been publishd, and you may take a try.

**Comment by rivke41levp656** [comment]
I am using dark reader and a dark theme yes. I forgot to check if it occurs with those disabled, sorry.
1.99.7 seems to have fixed it. Thank you

**Comment by gdh1995** [comment]
OK.

BTW, v1.99.7 rollbacks some changes about the detection of color theme , which means I have to invent another idea to detect it in the future ...
