### ISSUE TITLE
Firefox下1.99.5版本缺失“搜索历史记录并在新标签页打开”功能

### ISSUE THREAD

**Issue by alayamanas** [gdh1995/vimium-c#791]
1. 在edge浏览器中，vimium-c版本1.99.3，搜索历史记录并在新标签页打开，该功能存在
2. 在Firefox浏览器中，vimium-c版本1.99.5，搜索历史记录并在新标签页打开，该功能不存在
3. 在Firefox的vimium-c配置页面中，添加map h Vomnibar.activateHistoryInNewTab无效

**Comment by gdh1995** [comment]
嗯已知问题。1.99.6应该已经能下载到了，等Firefox自动更新或者手动删了重装试试

**Comment by alayamanas** [comment]
> 嗯已知问题。1.99.6应该已经能下载到了，等Firefox自动更新或者手动删了重装试试
> 
> duplicate of #787

了解，感谢作者的辛苦工作

**Comment by gdh1995** [comment]
另外，帮助对话框里显示`高级命令`的时候会能搜到这个命令，此时右下角按钮的标题是`隐藏高级命令`：
![image](https://user-images.githubusercontent.com/5547703/200250739-210b7f5d-c0de-484a-acdc-5493e00d992b.png)

1.99.5 版里也能搜到它，只是`map`指令可能被默认快捷键给覆盖掉，需要先 `unmap` (https://github.com/gdh1995/vimium-c/issues/787#issuecomment-1304903876) .

**Comment by alayamanas** [comment]
对
unmap h
map h Vomnibar.activateHistoryInNewTab
这样有效。
但是Firefox 下帮助对话里边倒是的确没有你上图标绿的部分，见下图
![微信截图_20221107154350](https://user-images.githubusercontent.com/10472264/200254237-13a97e8c-2ee1-4ab0-adcc-e4a2a42de31f.png)

**Comment by gdh1995** [comment]
你这是在别的页面打开的帮助对话框，只显示“已经绑定快捷键的命令”，需要在 Vimium C 设置 页面才会自动显示所有命令

**Comment by alayamanas** [comment]
你说得对。我找到了，谢谢！
