### ISSUE TITLE
some customized mappings seem to break in v1.99.5

### ISSUE THREAD

**Issue by acelticsfan** [gdh1995/vimium-c#792]
**Describe the bug**

I have a key bound to moveTabToNewWindow

In v1.99.5, it moves it to the next window and not to a new window.

**To Reproduce**

1. map the key:   map W moveTabToNewWindow
2. use the key
3. see tab move to existing window and not a new one

I downgraded to Vimium-C 1.99.3 and the problem does not exist.

**Browser, OS and Vimium C versions**

- Browser name:   Vivaldi 
- Browser version: 5.4.2753.51 and above  (Chrome/104.0.5112.126).
- Vimium C version:  1.99.5
- OS name and version:   MacOS 12.6

Vimium C - All by Keyboard  1.99.5

User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.126 Safari/537.36

**Comment by gdh1995** [comment]
Sorry, as said in https://github.com/gdh1995/vimium-c/issues/788#issuecomment-1304904068 , this is a known bug that default key mappings override your customized ones in Vimium C v1.99.5.

Vimium C v1.99.7 has been published and is waiting for reviews from Chrome Web Store.

As a working around, you may insert `unmap` rules before your `map` rules, like:
```
unmap W
map W moveTabToNewWindow
```

**Comment by acelticsfan** [comment]
Thanks for the update.  I'm glad there is a fix and thanks for the great extension.

**Comment by gdh1995** [comment]
Hello, v1.99.90 has been released on Chrome Web Store, and you may take a try. All above tricks should not be needed any more.
