### ISSUE TITLE
What does this option do?

### ISSUE THREAD

**Issue by ActualBest** [gdh1995/vimium-c#793]
"Close the download bar and allow an alternative API to download files"
I tried downloading a file with option enabled, didn't seem to make a difference.
Tested in latest stable version of Chrome and Vivaldi on Windows 11

**Comment by gdh1995** [comment]
The permission is for the command named `closeDownloadBar`. You may need to enable it before you trigger `closeDownloadBar`.

To trigger `closeDownloadBar`, you also need to map a key sequence to it, and the mapping rule should be added into the textbox of `Custom key mappings`:
```
map <a-s-d> closeDownloadBar  # Alt+Shift+D
```

**Comment by ActualBest** [comment]
Oh that makes sense, thank you!
