### ISSUE TITLE
无法复制图片到剪贴板(LinkHints.activateCopyImage无法正常工作)

### ISSUE THREAD

**Issue by backuponeday** [gdh1995/vimium-c#795]
请问复制图片到剪贴板无法正常工作,复制后只会在剪贴板生产空白内容.查找了issue没有看尽相同问题,不知是否是自己问题,
网站复制权限禁止和开启都无法工作.

- Browser name: egde 107.0.1418.35 (正式版本) (64 位) 
- OS name: win10
- Vimium-C:  [1.99.3]

**Comment by gdh1995** [comment]
chrome/edge 107 的新问题，最新代码已经修了，等过阵子会发布 v1.99.7 或者 v1.99.8，就该正常了。

duplicate of #778 .
