### ISSUE TITLE
可以在设置中添加一个选项不，x关闭标签后选择展示左边标签，而不是默认的右边标签

### ISSUE THREAD

**Issue by hurricanedjp** [gdh1995/vimium-c#796]
浏览本标签时，看到一个新概念，O打开搜索，会在当前标签的右边出现新标签。看完了之后，x关闭，这时理想的是回到左边标签继续浏览，而不是展示右边完全不相关的标签，打破了思维的连贯性。
chrome默认关闭当前标签后，展示的右边标签。
之前使用鼠标手势插件时，可以设置关闭当前标签后展示左边标签。
对于这一点，不知作者可否支持一下，多谢！！

**Browser and OS**

- Browser name: chrome v106.0.5249.119
- vimium C version: 1.99.5
- OS name: Windows 10

**Comment by gdh1995** [comment]
```
map x removeTab goto="previous"
```

**Comment by hurricanedjp** [comment]
多谢大佬。刚开始试了下没起作用，后来发现要在前面加下
```
unmap x 
```
让原有的映射失效😂

**Comment by gdh1995** [comment]
哦这个是v1.99.5的bug，等几天v1.99.7发布了就好了
