### ISSUE TITLE
LinkHints can't hint a last matched element since v1.99.4 for Firefox

### ISSUE THREAD

**Issue by dogancelik** [gdh1995/vimium-c#797]
**Describe the bug**

I can't activate on `[contenteditable]` elements after v1.99.4+

I can activate `[contenteditable]` in v1.99.3 (released on August)

**To Reproduce**

1. Add `map q LinkHints.activate match="input,[contenteditable]"` to Vimium settings
2. Go to https://fh.dogancelik.com/vimium-c-test.html
3. Press <kbd>q</kbd> to activate `input` and `[contenteditable]`

**Demo v1.99.3**
![v1993](https://user-images.githubusercontent.com/486818/201187647-e93f9cb8-cbf2-48a8-b17a-9bffa93bbafb.gif)

**Demo v1.99.7**
![v1997](https://user-images.githubusercontent.com/486818/201187489-c3a8d481-0c48-4d7b-8dd7-b1def2b71994.gif)

**Browser, OS and Vimium C versions**

- Browser name: Firefox
- Browser version: 106.0.5
- Vimium C version: 1.99.6
- OS name and version: Windows 10

**Comment by gdh1995** [comment]
Reproduced. Sorry.

To bypass this bug, you may use the command named `LinkHints.activateEdit` and it still works.

**Comment by gdh1995** [comment]
Hello, v1.99.8 for Firefox has been published and you may retry mappings like `map q LinkHints.activate match="input,[contenteditable]"`

**Comment by dogancelik** [comment]
@gdh1995 Thank you so much, I really appreciate it! :heart:
