### ISSUE TITLE
can Vomnibar.activateTabs sort by tab order?

### ISSUE THREAD

**Issue by zyf0330** [gdh1995/vimium-c#798]
It seems that the current order is misorder.

**Comment by gdh1995** [comment]
Please try: ```map T Vomnibar.activateTabs tree``` or ```map T Vomnibar.activateTabs tree="from-start"```

**Comment by zyf0330** [comment]
Both map gives this order _11, 10, 8, 1, 2, 7, 3, 4_.

**Comment by gdh1995** [comment]
Are you using Vimium C v1.99.5. It has a bug affecting key mappings, so please retry with:
```
unmap T
map T Vomnibar.activateTabs tree="from-start"
```

**Comment by zyf0330** [comment]
Yes, and I have done like this.

**Comment by gdh1995** [comment]
Could you give snapshots of your key mappings and Vomnibar status?

**Comment by zyf0330** [comment]
![image](https://user-images.githubusercontent.com/11958657/201305196-a4e1576b-dbae-4aea-95be-c63d34a62d54.png)
I open three tabs in a window.
![image](https://user-images.githubusercontent.com/11958657/201305706-07c4674e-4fda-4f31-9cbb-06f726fca3d1.png)

**Comment by gdh1995** [comment]
Oh, sorry. It should be something like:
```
unmap T
map T Vomnibar.activateTabs tree="from-start" currentWindow
```

**Comment by zyf0330** [comment]
Now it works.
By the way, it is good if can filter tab by input _#number_.

**Comment by gdh1995** [comment]
Then the results can be only be one suggestion? You may use `<PageDown>` or `<Shift+ArrowDown>` to see more tabs, or just type (a space after query and) `+10` to see 11th-20th tabs.
