### ISSUE TITLE
Vimium-C does not work on edge://*/* pages.

### ISSUE THREAD

**Issue by NicolasZapata** [gdh1995/vimium-c#799]
It works for example in other Chromium-based browsers like Brave, but it doesn't work in Microsoft Edge, I have both the #extensions-on-edge-urls option active and the “Run on edge://*/* pages” checkbox in the options, but it still doesn't work. What could be the cause?

Thanks

Best Regards

**Comment by gdh1995** [comment]
Sorry there's a typo bug, and I'll fix it in v1.99.8 .

**Comment by NicolasZapata** [comment]
@gdh1995 Thanks 👍

**Comment by gdh1995** [comment]
Hello, v1.99.96 has been published and it should fix this bug.

**Comment by NicolasZapata** [comment]
That's right, works perfectly, thank you. :)

Best regards
