### ISSUE TITLE
`mapKey` for `goNext` does not work since v1.99.4

### ISSUE THREAD

**Issue by dogancelik** [gdh1995/vimium-c#801]
**Describe the bug**

MapKey with Turkish keyboard layout setting does not work since v1.99.4

Settings used:
```
mapKey ğ [
mapKey ü ]
```

**To Reproduce**

1. Go to https://fh.dogancelik.com/vimium-c-test-2.html
2. Press <kbd>]</kbd> <kbd>]</kbd> or <kbd>ü</kbd> <kbd>ü</kbd> (Turkish Q keyboard layout)
3. Counter should go up 1, 2, 3, etc.

Demo v1.99.3
![mapkey v1993 v2](https://user-images.githubusercontent.com/486818/201495751-971d0928-6aad-431d-a1b3-4bd0c3c36fc0.gif)

Demo v1.99.7
![mapkey v1997 v2](https://user-images.githubusercontent.com/486818/201495758-85199255-2a00-4b79-ac0b-e65b20b6b9ce.gif)

**Browser, OS and Vimium C versions**

- Browser name: Firefox
- Browser version: 106.0.5
- Vimium C version: 1.99.7
- OS name and version: Windows 10

**Comment by gdh1995** [comment]
Sorry for the bug, but in fact it's a bug of `goNext` (https://github.com/gdh1995/vimium-c/issues/789#issuecomment-1305652288), and a trick to working it around is:
```
map ]] goNext noRel
map [[ goPrevious noRel
```

BTW, v1.99.x has added a feature named `Ignore keyboard layout if a key is not located in 7-bit ASCII`, and if you enable it, those `mapKey` rules for non-English letters may be not needed any more. So you may take a try.

**Comment by dogancelik** [comment]
Okay I added them to my settings and it works now, thank you! @gdh1995
```
mapKey ğ [
mapKey ü ]
map ]] goNext noRel
map [[ goPrevious noRel
```
