### ISSUE TITLE
最新版本的“上一页”“下一页”功能失效了吧？

### ISSUE THREAD

**Issue by lededev** [gdh1995/vimium-c#803]
- Vimium C version: 1.99.5
无论我按 `]]` `[[` 还是自己定义的 a A，都去不到上一页或者下一页了。
```
map a goNext
map A goPrevious

```

**Comment by gdh1995** [comment]
See https://github.com/gdh1995/vimium-c/issues/789#issuecomment-1305652288
> There's a working around for this bug, by disabling some features of `goNext`:
> ```
> map ]] goNext noRel
> map [[ goPrevious noRel
> ```
> 
> With `noRel`, `goNext` may find less next URLs, so when a new version fixes it, please remove `noRel` to ensure it works as in v1.99.3.

**Comment by lededev** [comment]
加上noREL之后解决了，谢谢
