### ISSUE TITLE
Feature Request: follow link under cursor in caret mode

### ISSUE THREAD

**Issue by philipphutterer** [gdh1995/vimium-c#805]
When scrolling through a page in caret mode, I think it would be nice to have the ability to directly follow a link under the cursor. Since neither `f` nor `F` has an effect in caret mode at the moment, this seems like a well suited option.

**Comment by gdh1995** [comment]
Hello, in a latest version of Vimium C, its command `LinkHints.click` can be used to "click selected text", so if you write:
```
map xxx LinkHints.click direct="selected"
```

then you may press `xxx` (after exiting VisualMode) to click a link which has text selection.

And, to exit VisualMode without copying text, you may press `Escape` , `Ctrl+Enter` or `Meta+Enter`.
