### ISSUE TITLE
Make vimiumC works in blob url pages

### ISSUE THREAD

**Issue by eastarpen** [gdh1995/vimium-c#806]
### What is blob urls

* [wiki Blob URI scheme](https://en.wikipedia.org/wiki/Blob_URI_scheme)
*  simple explaination
  > Blob is just byte sequence. Browsers recognize Blobs as byte streams. It is used to get byte stream from source. According to [Mozilla's documentation](https://developer.mozilla.org/en-US/docs/Web/API/Blob) <br>
 >  A Blob object represents a file-like object of immutable, raw data. Blobs represent data that isn't necessarily in a JavaScript-native format. The File interface is based on Blob, inheriting blob functionality and expanding it to support files on the user's system.

### Description

In blob url page, I found the extension doesn't work and got info below:

> Vimium C is not running on this page
Your browser does not run web extensions like Vimium / Vimium C on certain pages, usually for security reasons.
Unless your browser's developers change their policy, then unfortunately it is not possible to make Vimium / Vimium C (or any other web extension, for that matter) work on this page.
Configure more on the options page. Version 1.99.5.

I opened the options page but didn't find related settings

I checked other extensions,  some turned dark, but some did not. 

By the way, bitwarden(a password management extension) generated password normally after I pressed specific keys.

So, can vimiumC works in blob url pages?

**Comment by gdh1995** [comment]
When you say another extension generated a password correctly, where did it display the password, on its popup dialog or an input bar in the blob web page?


According to my memory, about:/blobs pages doesn't allow any extension to run on them. I'll recheck it when I'm in rest.



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 15, 2022 21:40 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] Make vimiumC works in blob url pages (Issue #806)




 
What is blob urls
  
wiki Blob URI scheme
 
simple explaination
   
Blob is just byte sequence. Browsers recognize Blobs as byte streams. It is used to get byte stream from source. According to Mozilla's documentation 

 A Blob object represents a file-like object of immutable, raw data. Blobs represent data that isn't necessarily in a JavaScript-native format. The File interface is based on Blob, inheriting blob functionality and expanding it to support files on the user's system.
  
Description
 
In blob url page, I found the extension doesn't work and got info below:
  
Vimium C is not running on this page
 Your browser does not run web extensions like Vimium / Vimium C on certain pages, usually for security reasons.
 Unless your browser's developers change their policy, then unfortunately it is not possible to make Vimium / Vimium C (or any other web extension, for that matter) work on this page.
 Configure more on the options page. Version 1.99.5.
  
I opened the options page but didn't find related settings
 
I checked other extensions,  some turned dark, but some did not.
 
By the way, bitwarden(a password management extension) generated password normally after I pressed specific keys.
 
So, can vimiumC works in blob url pages?

**Comment by gdh1995** [comment]
I've tested a tab of `blob:` and Chrome does refuse any extension to run on it.

**Comment by eastarpen** [comment]
> I've tested a tab of `blob:` and Chrome does refuse any extension to run on it.

Sorry for the late reply

I did such experiment:

1. create a blob page with login form
2. call bitwarden to fill content
3. it didn't work

It proves that bitwarden doesn't work on blob pages too. 

The "generate password" shortkey works because it was set by page "chrome://extensions/shortcuts", it seems that shortcuts set by that page has higher pemisson.
