### ISSUE TITLE
输入法开启时，使用ESC退出Vomnibar后，按键会首先被输入法捕获

### ISSUE THREAD

**Issue by Generalost** [gdh1995/vimium-c#807]
**Describe the bug**

输入法开启时，使用ESC退出已经打开的Vomnibar后，按键会首先被输入法捕获。

**To Reproduce**

1. 开启微软或搜狗的中文输入法；
2. 在网页上使用O打开Vomnibar；
3. 使用ESC退出Vomnibar；
4. 使用a-z任何按键键位首先被输入法捕获

切换到英文模式或者关闭输入法可以恢复。

除了Vimium C配置页之外，几乎所有页面都有上述问题

**Browser, OS and Vimium C versions**

- Browser name: Chrome 
- Browser version: 107.0.5304.107
- Vimium C version: 1.99.5
- OS name and version: Windows 10 Version 21H2

**Comment by gdh1995** [comment]
已知bug，在v1.99.7会修，但Chrome Web Store审查v1.99.7审了10天了还没动静

**Comment by gdh1995** [comment]
Hello, v1.99.90 has been released on Chrome Web Store, and you may take a try.
