### ISSUE TITLE
Page scrolling is slower on Wayland than on X.org

### ISSUE THREAD

**Issue by maxigaz** [gdh1995/vimium-c#808]
**Describe the bug**

Under Arch Linux and Sway, when Firefox is run as a native Wayland application (with the environment variable `MOZ_ENABLE_WAYLAND=1`), scrolling down/up with j/k with Vimium C is slower than when Firefox is in XWayland mode (`MOZ_ENABLE_WAYLAND=0`) or run under an X.org session with i3.

A workaround is to increase the value of pixels in Options -> Scroll step size, but this makes scrolling too fast under i3. This is a problem because while generally I prefer using Sway, sometimes I have to use i3 for certain applications.

**To Reproduce**

1. Run `MOZ_ENABLE_WAYLAND=0 firefox` from a terminal.
1. Go to the Options of Vimium C and set Scroll step size to 120 pixels and 120 milliseconds.
1. Go to the URL https://github.com/gdh1995/vimium-c
1. Scroll down to the bottom by holding `j`.
1. Completely exit Firefox and run it again, this time with `MOZ_ENABLE_WAYLAND=1 firefox`.
1. Go to the URL https://github.com/gdh1995/vimium-c again and scroll down with `j`. Notice that it takes about 1 second more to reach the bottom of the page.

**Browser, OS and Vimium C versions**

- Browser name: Firefox
- Browser version: 107.0
- Vimium C version: 1.99.8
- OS name and version: Arch Linux

**Comment by gdh1995** [comment]
Well, it's because Firefox has some bugs with Wayland or when `MOZ_USE_XINPUT2=1`, and won't report correct information about "a pressed key is being held on". I'll add a trick to work it around.

Please try this commit: [vimium_c-1.99.8-firefox-3e440ee.zip](https://github.com/gdh1995/vimium-c/files/10049333/vimium_c-1.99.8-firefox-3e440ee.zip) (usage is in https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package)

**Comment by maxigaz** [comment]
I can confirm it to be working. Thank you very much!

**Comment by gdh1995** [comment]
Hello, Vimium C v1.99.9 for Firefox has been released, and you may take a try.

**Comment by maxigaz** [comment]
I've just tried v.1.99.9 and the scrolling still works fine.

However, I've found a glaring issue in this version. I'm not sure if it is related, so I'm going to open a separate issue for it.
