### ISSUE TITLE
[Request] Change opacity of navigation hints when using Space to cycle

### ISSUE THREAD

**Issue by n4n0GH** [gdh1995/vimium-c#81]
Current behaviour after invoking the navigation hints with `f` and then cycling through them with `Space` is a change in z-index on each item. However, I would like to see an option to also change the opacity of "unfocused" hints. This would allow to clear up cluttered areas like this one:
![scrot_20191017234727](https://user-images.githubusercontent.com/27410256/67050303-7f6fb280-f138-11e9-87b5-cf223dba9945.png)

With the proposed change, cycling could look like this, which is much better in terms of visual appearance:
![scrot_20191017234921](https://user-images.githubusercontent.com/27410256/67050438-d07fa680-f138-11e9-9280-76d1be0ee15e.png)

**Comment by gdh1995** [comment]
An interesting idea. So, what if 3~5 hints are stacked (one covers another)?

**Comment by n4n0GH** [comment]
> So, what if 3~5 hints are stacked (one covers another)?
It depends on how Vimium-C currently selects the "focused" element. I guess there's no proper logic embedded to actively make elements the "focus" and instead it just cycles through `z-index` properties, right? If there was a method to make Vimium-C actively set an element as "this item right here is now in focus" you could make _all other_ elements less visible. So if 3~5 items are stacked, only one of those would be visible at all times when using the cycle method.

> Added: I also wonder why `WK` is transparent, since none has covered it.
Oh that's just for demonstration purposes. I used a `:nth-of-type(odd)` pseudoclass to select the elements.

**Comment by gdh1995** [comment]
In the next released version of Vimium C, you can write such "Custom CSS":
``` css
.OH { opacity: 0.4; } .SH { color: red; }
```
to style behind hints and the top one. And these class names (now) only occurs when you have pressed "space" to rotate them.

**Comment by gdh1995** [comment]
In the next released version of Vimium C, you can write such "Custom CSS":
``` css
.OH { opacity: 0.4; } .SH { color: red; }
```
to style behind hints and the top one.

Currently, the logic is:
* these class names (now) only occurs when you have pressed "space" to rotate them;
* those never covering others / being covered will not be affected.

If any new idea please put it here.

**Comment by gdh1995** [comment]
Firstly, thank you very much for your appreciation of my work.

I'm in China and currently has no VISA/master cards, so I've put a QR-code image of [Alipay](https://intl.alipay.com/) on https://github.com/gdh1995/vimium-c#donate--%E6%8D%90%E8%B5%A0 for anyone who wants to donate some to me.
