### ISSUE TITLE
Excluded URLs : editing pattern not detected as changes and thus can not be saved.

### ISSUE THREAD

**Issue by Fred-Vatin** [gdh1995/vimium-c#811]
**Describe the bug**
Excluded URLs : editing pattern not detected as changes and thus can not be saved.

**To Reproduce**

1. Edit an existing excluded URL.
2. Can not be saved as no changes detected

**Note** : url in the input can only be selected with the keyboard. Mouse doesn’t work. Could it be related to the bug ?

![image](https://user-images.githubusercontent.com/22337329/203546750-3fb4eee6-16f1-4f95-916a-da4820504179.png)
![image](https://user-images.githubusercontent.com/22337329/203546825-5c9c2f62-6a29-481e-bca7-030857f72719.png)

**Browser, OS and Vimium C versions**

- Browser name: Firefox
- Browser version: 107.0 (64 bits)
- Vimium C version: 1.99.90
- OS name and version: Windows 10 21H2

**Comment by gdh1995** [comment]
Hello, v1.99.96 has been published and it should fix this bug.
