### ISSUE TITLE
Visual line mode can only move in one direction

### ISSUE THREAD

**Issue by dylanpjx** [gdh1995/vimium-c#813]
Bug:
Visual line mode can only go in one direction. If you move down in visual line mode, you cannot move up any more and vice versa.

Caret mode still works as intended.

**Browser, OS and Vimium C versions**

- Browser name:  Firefox
- Browser version: 107.0
- Vimium C version: 1.99.90
- OS name and version: Linux

**Comment by gdh1995** [comment]
Hello, please try this version - I added complex detection and tricks to make it movable on my Chrome.
[vimium_c-2.0.0-firefox-285fa90-mv2-mod.zip](https://github.com/gdh1995/vimium-c/files/10104444/vimium_c-2.0.0-firefox-285fa90-mv2-mod.zip)

Usage: https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package

**Comment by gdh1995** [comment]
Hello, this version should work better: [vimium_c-2.0.0-firefox-41915ad-mv2.zip](https://github.com/gdh1995/vimium-c/files/10106902/vimium_c-2.0.0-firefox-41915ad-mv2.zip)

**Comment by gdh1995** [comment]
Hello, v1.99.96 has been published, and you may take a try directly.
