### ISSUE TITLE
请问"智能切换到其它搜索引擎"如何在新标签页打开切换后的搜索引擎,默认是在当前页打开

### ISSUE THREAD

**Issue by WrathGluttony** [gdh1995/vimium-c#814]
**What command or commands**

"searchInAnother": "智能切换到其它搜索引擎"
**How should a feature do**

在新标签页打开切换后的搜索引擎,而不是在当前页打开

then Vimium C should do:
在新标签页打开切换后的搜索引擎,而不是在当前页打开

**Browser and OS**

- Browser name: Google Chrome 107.0.5304.107（正式版本） （64 位）
- OS name: Win10 21H2 19044.2251
- Vimium C: 1.99.90

**Comment by WrathGluttony** [comment]
> ```
> map xxx searchInAnother keyword="yyy" reuse="new-fg"
> # 或者 reuse=new-bg 来在后台打开
> ```

谢谢大神
①还有个问题，就是在360极速浏览器X(是X，64位的360极速浏览器)里按F，大部分链接识别不出来，就是无法按链接对应的字母转到该链接
②360极速浏览器X版本号：21.0.1139.0
    360极速浏览器内核版本：95.0.4638.69

**Comment by gdh1995** [comment]
360浏览器X的问题，它假装自己是Chrome21，太旧了，导致为了Vimium C兼容旧版本写的代码影响了功能。

我想想怎么凑合绕过去

**Comment by WrathGluttony** [comment]
谢谢大神的敬业精神,bow!

**Comment by gdh1995** [comment]
v1.99.96 已经发布了，针对”21“这种错的版本号做了修复，请测试。

**Comment by WrathGluttony** [comment]
谢谢大神适配,用Vimium C(版本是当前最新版:1.99.97),360极速浏览器X没问题
