### ISSUE TITLE
如何用插件来操作视频

### ISSUE THREAD

**Issue by gansihao** [gdh1995/vimium-c#815]
有时候操作视频需要把鼠标移到视频的位置才会弹出一些操作，如放大、弹窗、静音等，用插件怎么模拟？
例如虎牙的网页，eg：https://www.huya.com/880214

**Browser and OS**

- Browser name: edge 107.0.1418.56
- OS name: win10
- Vimium C: 1.99.90

**Comment by backuponeday** [comment]
可以使用css选择器绑定按键直接操作`map af LinkHints.click direct="element" match=".player-fullscreen-btn"`

**Comment by gdh1995** [comment]
嗯可以用`LinkHints.click`指定选择器直接模拟点击。比如 https://github.com/gdh1995/vimium-c/issues/639#issuecomment-1133826165 、 https://github.com/gdh1995/vimium-c/issues/783#issuecomment-1303094795

或者用 `LinkHints.activateHover` 这个命令选择视频画面（也就是在视频左上角的提示字母），这个命令可以假装鼠标挪到视频上了，这样部分支持这种模拟消息的网页就会显示自己的按钮了，试了试虎牙可以。

**Comment by gdh1995** [comment]
也可以用 https://github.com/gdh1995/vimium-c/issues/687#issuecomment-1214142290 这里的办法，手写 JS 函数来执行播放控制、静音等通用操作。
