### ISSUE TITLE
activateCopyImage fail on sinaimg   | 复制图片对微博原图页面无效

### ISSUE THREAD

**Issue by scarletfrank** [gdh1995/vimium-c#816]
**What command or commands**

_yi_ LinkHints.activateCopyImage

**How should a feature do**

When a user has done such steps:

1. Go to URL [a](https://weibo.com/2155384092/MgYT87mRf)
2. Select 图片
3. 鼠标焦点放在图片上，点击【查看大图】
4. 在新出现的遮罩上，点击【原图】
5. 浏览器会跳转到 [b](https://wx2.sinaimg.cn/large/80788d1cgy1h8jtre2bxkj212f0opwhf.jpg)
6. 输入指令 _yi_

then Vimium C should do:

1. 成功复制链接b 里面的图片

我还没搞清楚微博到底这里做了什么处理，但这里图片有个点击放大的交互，和推特其实很像，但推特到最后一步是能正常复制的。

**How should a feature do (Twitter Case)**

When a user has done such steps:

1. Go to URL [status/1592071286326702080](https://twitter.com/Blueblade0913/status/1592071286326702080)
2. Select 图片，Go to URL [status/1592071286326702080/photo/1](https://twitter.com/Blueblade0913/status/1592071286326702080/photo/1)
3. issue里抄的一个快捷命令，Yi (LinkHints.activateOpenImage)，复制图片链接
4. 命令P (openCopiedUrlInNewTab)，转到URL [FhgsYpEagAEnrrc?format=jpg&name=large](https://pbs.twimg.com/media/FhgsYpEagAEnrrc?format=jpg&name=large)
5. 输入指令 _yi_

then Vimium C should do:

1. 成功复制图片

推特这个我现在是用这样的步骤去复制原图，也分享出来，主要我细看页面源代码大致结构差不多，没搞懂为啥一个能生效一个不行。

**Browser and OS**

- Browser name:  107.0.1418.56
- OS name: Win10 21H2

**Comment by gdh1995** [comment]
你好，v1.99.96 已经发布了，请试试看。

复制图片失败的本质原因是，浏览器JS扩展的权限不够高，某些网站的服务器配置会让浏览器拒绝把图片数据告诉扩展程序，就复制不了。v1.99.96 添加了个别绕过的办法，但不够普适。你先在微博上测试看看吧。

**Comment by scarletfrank** [comment]
> 

我自己写的微博上的步骤，测试通过，可以正常复制
