### ISSUE TITLE
Also Parse Directories in Bookmark Search

### ISSUE THREAD

**Issue by CouscousPie** [gdh1995/vimium-c#817]
When you search through bookmarks with `b` vimium only parses through the url and the name of the bookmark. It would be great if it also parsed through the folder names of the bookmarks. Doing so, you wouldn't have to remember the name you or your browser gave the bookmark. It would allow to browse through bookmarks as if they were tagged. Furthermore, it would allow to easilzy differentiate between bookmars with similar urls and/or names.

For instance, consider two bookmarks that are both named `foo` and are subdomains of the same domain, but one is saved in a folder `Phantasy Project` and the other in a folder `Real Project`. You could then find it easily via `real foo` or `phantasy phoo` respectively.

**Comment by gdh1995** [comment]
There has been such a feature: if only a query word starts with `/`, then it will be used to search in bookmark path:
![image](https://user-images.githubusercontent.com/5547703/204144754-47f1bd46-a0cf-4eff-b040-6494bacdfc3c.png)

**Comment by CouscousPie** [comment]
I feel that it would still improve the utility if it was possible to search both: name/url _and_ folders at the same time. However, this is already pretty useful.
