### ISSUE TITLE
请问focusinput命令参数正确的写法是map gi focusInput keep select="all"吗？期望进入文本框并选中文本框所有文本

### ISSUE THREAD

**Issue by WrathGluttony** [gdh1995/vimium-c#818]
**What command or commands**
map gi focusInput keep select="all"

**How should a feature do**
期望进入文本框并选中文本框所有文本，上面的写法正确吗？请问参数keep是什么意思？如何设定keep?
When a user has done such steps:
gi

then Vimium C should do:
进入文本框并选中文本框所有文本

**Browser and OS**

- Browser name: Chrome 版本 107.0.5304.122（正式版本） （64 位）
- OS name: Win10 21H2 19044.2251
- Vimium C:1.99.90

**Comment by gdh1995** [comment]
`select="all"` 就够了；keep是说不在下一个键自动退出。keep不用设定，有就是开启，没有它就是关掉。这种你找个文本框试一下就知道效果了。

**Comment by WrathGluttony** [comment]
谢谢大神指点
