### ISSUE TITLE
Next match (`n`) in `FindMode` doesn't scroll far enough to result

### ISSUE THREAD

**Issue by mangkoran** [gdh1995/vimium-c#819]
**Describe the bug**

In long webpage, pressing `n` (select next match) in `FindMode` sometimes doesn't scroll to the next match. It will still scroll upwards/downwards, but the viewport is not scrolled far enough to show the next match in the viewport.

**To Reproduce**

1. Go to https://neovim.io/doc/user/lua.html
2. `/return<CR>`. First match of `return`. Still inside the current viewport.
![image](https://user-images.githubusercontent.com/57625126/204788652-e58302bb-e98f-4465-8e75-25684c562336.png)

3. `n`. Second match of `return`. Not shown in the current viewport.
![image](https://user-images.githubusercontent.com/57625126/204788909-0a3362b7-7713-446e-a56c-6774bac5b1d1.png)

**Browser, OS and Vimium C versions**

- Browser name: Chrome
- Browser version: 107.0.5304.122 (Official Build) (64-bit)
- Vimium C version: 1.99.90.
- OS name and version: Windows 11 22H2 22621.900

**Comment by mangkoran** [comment]
Thank you for the fix! I can confirm that this is now fixed. (In this commit? db09cef0425ac90d98d49ef7428fa733d14b48df) (also you could automatically close issue with commit by using several keywords ([ref](https://github.com/gitbucket/gitbucket/wiki/How-to-Close-Reference-issues-and-pull-request)))

However, I have a question. Could we configure how the "out of boundary" search result is brought into viewport? For example, in the attachment below, the viewport will be scrolled enough so that the "return" result is on the bottom of the viewport. I would like to have the viewport to be scrolled far enough so that the result is at the middle of the viewport. (is it more or less like scrollOff in Vim?)

![image](https://user-images.githubusercontent.com/57625126/209310430-0c8f9c8a-1129-434f-9814-6d48f9b92e54.png)

**Comment by gdh1995** [comment]
Um, up to now not available in Vimium C. The current logic is to scroll as few times as possible, so if an element "looks like visible", then Vimium C won't scroll the page.

Your idea sounds useful in some situations, but unfortunately I have no much rest time in next several months to implement it.

In 2023 Chrome will abort all extensions "using the old extension API platform 'V2' " on its Web Store (see https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/),
so I have to upgrade Vimium C to use `Manifest V3`, and there're still a few big features which are waiting for rewriting.

**Comment by mangkoran** [comment]
@gdh1995 It's alright. Thank you for solving this issue anyway!

Maybe for my feature suggestion, I think it's better to create a new issue/feature request ticket as my original issue has been solved. I will do so.
