### ISSUE TITLE
Don't know how to inject vimium into "New Tab" extension

### ISSUE THREAD

**Issue by Solar-Lancelo** [gdh1995/vimium-c#82]
> Chrome 
"New Tab" extensionID: jmalocgcmlilelcdekhigpadlhfbjpnp

![DeepinScreenshot_select-area_20191023185911](https://user-images.githubusercontent.com/52375886/67387051-ae6aa600-f5c8-11e9-998d-1ada6c0dfbd5.png)
I add the script into iSearch.html of that extenion, but the vimium not working.
```
    <script>
        var extensionInjector_ = localStorage.interactWithExtension !== "0" && localStorage.targetExtensionInjector,
            loadExtension_ = function () {
                if (!extensionInjector_) {
                    return;
                }
                var script = document.createElement("script");
                script.src = extensionInjector_;
                script.dataset.extensionId = "hfjbmagddngcpeloejdejnfgbamkjaeg";
                document.head.appendChild(script);
            };
        loadExtension_();
    </script>
```
[jmalocgcmlilelcdekhigpadlhfbjpnp.zip](https://github.com/gdh1995/vimium-c/files/3761998/jmalocgcmlilelcdekhigpadlhfbjpnp.zip)

**Comment by Solar-Lancelo** [comment]
```
Console: Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' chrome-extension://jmalocgcmlilelcdekhigpadlhfbjpnp/ga.js". Either the 'unsafe-inline' keyword, a hash ('sha256-zhbUcoEtZ5x+iH1uaHA+WZpLzPV6bkJvfBST7e0i+58='), or a nonce ('nonce-...') is required to enable inline execution.

```
![DeepinScreenshot_select-area_20191023192223](https://user-images.githubusercontent.com/52375886/67387994-77958f80-f5ca-11e9-80b0-686dc01cd787.png)

**Comment by gdh1995** [comment]
The CSP needs to be updated: https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions#modify-extension-properties-only-required-on-chrome

![Uploading image.png…]()

**Comment by gdh1995** [comment]
A raw `<script>...</script>` is not allowed - JavaScript code must be put into a file and use `<script src="..."></script>` to refer it.

**Comment by Solar-Lancelo** [comment]
还有这种操作

**Comment by Solar-Lancelo** [comment]
原本manifest.json里有的 chrome-extension://..  不用删除吗

**Comment by gdh1995** [comment]
可以留着，不影响。那个看起来是个统计使用情况的脚本，`ga.js`是Google Analystics的常用文件名。不过按我对Chrome扩展的开发经验来看，这一串在这里毫无意义。

**Comment by Solar-Lancelo** [comment]
修改后, 添加白名单还不行啊. 也每个反应, 连错都不报
[modifiedExtension.zip](https://github.com/gdh1995/vimium-c/files/3762395/modifiedExtension.zip)

**Comment by Solar-Lancelo** [comment]
大佬有空再看吧, 额吃饭去了

**Comment by gdh1995** [comment]
我拿newtab那个扩展程序当例子，不是说能直接用。newtab这个扩展是有设置页面会写入`localStorage.interactWithExtension`和`localStorage.targetExtensionInjector`，你这是直接照搬，它找不到这两个值，就啥都没做。

改动: 把这俩换成`'chrome-extension://hfjbmagddngcpeloejdejnfgbamkjaeg/lib/injector.js'`
![image](https://user-images.githubusercontent.com/5547703/67394248-71a5ab80-f5d6-11e9-8a83-997559a623c0.png)

**Comment by Solar-Lancelo** [comment]
OK, 成了. 之前把那个js放到idea中没看到报错, 还以为这个localStorage是 js中的函数也就没改.
