### ISSUE TITLE
Is it possible to move tab to new window?

### ISSUE THREAD

**Issue by sohanglal** [gdh1995/vimium-c#820]
Pressing `shift + w` in vimium would open tab in new window, however in vimium-c it shifts the tab to next window. 
Can you please guide me as to how the same can be achieved in vimium-c with less keystrokes as possilbe?

**Comment by gdh1995** [comment]
There's a command named `moveTabToNewWindow`, though it doesn't have a default key binding. You may write your custom key mappings manually, like:
```
map W moveTabToNewWindow
```

**Comment by gdh1995** [comment]
No direct way - you have to try the command to get what's a "next" window.

If you write `map W moveTabToNextWindow last`, then `W` will move a current tab to a last-focused window, and `2W` moves 2 tabs. There're no other ways to specify a target window directly except the `last` parameter.

**Comment by sohanglal** [comment]
Thanks a lot for your help! This plugin is truly amazing! 
Just one last question is there some resource where these options are well-documented? I went through the wiki, the `Show available commands` option on the vimium options pages,  and the past issues but I couldn't find the option `last` of `moveTabToNextWindow`. 
The most similar option that I could find was `newtab="last-window"` of `LinkHints.activate` by searching through the release notes. Is there any resource you recommend I go through so that I can learn more?
