### ISSUE TITLE
如何实现在域名下搜索

### ISSUE THREAD

**Issue by xchnotxzh** [gdh1995/vimium-c#821]
我在docs.github.com 的任意页面下，想用默认搜索引擎（Google）搜索选中的关键字，要求
1. 搜索当前子域，相当于 key site:docs.github.com
2. 搜索全域，相当于 key site:github.com

想要这个功能不仅仅用在docs.github.com，而是能用在任意域名下。
![image](https://user-images.githubusercontent.com/59308951/205471294-3ab3ba56-17a7-499d-8a4a-ddd8d6f8d4a2.png)
效果类似这个插件 [search-site-we](https://addons.mozilla.org/en-US/firefox/addon/search-site-we)

**Comment by backuponeday** [comment]
wiki里面有说明.

**Comment by gdh1995** [comment]
还挺复杂的，wiki里应该没写到，我想想

**Comment by gdh1995** [comment]
添加`自定义快捷键`：
```
map xxx autoOpen keyword="search-domain"
```

然后添加`自定义搜索引擎`：
```
search-domain: vimium://run/openUrl#url_mask&host_mark="$h"&#url=site:$h\ $s
```

就是按域名搜索了。至于按顶级域名搜索，目前没有办法能在判断是否是顶级域名时保证正确（浏览器有，但太复杂了，不适合放到 Vimium C 里），你可以自己写文字替换规则，比如：

先指定`sed="1"`、指定`keyword`：
```
search-domain: vimium://run/openUrl#url_mask&host_mark="$h"&sed="1"&keyword="bi"&#url=site:$h\ $s
bi: https://www.bing.com/search?q=$s
```

然后添加到`文字自动替换`：
```
1@^site:(www|docs)\.@site:@
1@^site:(mails?|ftp)\.@site:@
```

这种，替换规则可以有多个，把你想去掉的前缀都写进去就行了。可以参考 https://github.com/gdh1995/vimium-c/wiki/Substitute-URLs-and-text-during-commands

**Comment by xchnotxzh** [comment]
> 添加`自定义快捷键`：
> 
> ```
> map xxx autoOpen keyword="search-domain"
> ```
> 
> 然后添加`自定义搜索引擎`：
> 
> ```
> search-domain: vimium://run/openUrl#url_mask&host_mark="$h"&#url=site:$h\ $s
> ```
> 
> 就是按域名搜索了。至于按顶级域名搜索，目前没有办法能在判断是否是顶级域名时保证正确（浏览器有，但太复杂了，不适合放到 Vimium C 里），你可以自己写文字替换规则，比如：
> 
> 先指定`sed="1"`、指定`keyword`：
> 
> ```
> search-domain: vimium://run/openUrl#url_mask&host_mark="$h"&sed="1"&keyword="bi"&#url=site:$h\ $s
> bi: https://www.bing.com/search?q=$s
> ```
> 
> 然后添加到`文字自动替换`：
> 
> ```
> 1@^site:(www|docs)\.@site:@
> 1@^site:(mails?|ftp)\.@site:@
> ```
> 
> 这种，替换规则可以有多个，把你想去掉的前缀都写进去就行了。可以参考 https://github.com/gdh1995/vimium-c/wiki/Substitute-URLs-and-text-during-commands
> 
> 补充：`keyword`和`sed`不是必须同时有的，可以只指定其中一个。试一试就知道了

谢谢指导，
我把顶级域名的替换规则，改成了更通用的正则表达式，
`1/(?<=site:).*\.([0-9a-zA-Z-]+)(\.[0-9a-zA-Z-]+)(?=\s.*)/$1$2/`
这样基本上能代替 search-site-we 的功能了。

**Comment by gdh1995** [comment]
更正一下，上边规则里的 `$s` 应该换成 `$S`，表示不需要对选中文字做（额外的）URL编码操作。

**Comment by xchnotxzh** [comment]
我发现很多时候想搜索的是"剪切板里的关键字"而非“选中的关键字”。
相同的功能，如何实现搜索"剪切板里的关键字"。

**Comment by xchnotxzh** [comment]
我发现很多时候想搜索的是"剪切板里的关键字"而非“选中的关键字”。
相同的功能，如何实现搜索"剪切板里的关键字"。

**Comment by gdh1995** [comment]
添加自定义快捷键：
```
map xxx openCopiedUrlInNewTab keyword="search-domain"
```

然后添加自定义搜索引擎：
```
search-domain: vimium://run/openUrl#url_mask&host_mark="$h"&#url=site:$h\ $S
```

**Comment by xchnotxzh** [comment]
谢谢，搞定了😃
