### ISSUE TITLE
vimium-c 有没有可能插件平台化？

### ISSUE THREAD

**Issue by xchnotxzh** [gdh1995/vimium-c#822]
对于某个比较通用小功能，比如在控制播放器、域名下搜索、拷贝markdown格式的标题和url等。
现在产品模式是，用户得自己想办法实现。
理想的产品模式类似Violentmonkey， vimium-c 作为这些小功能插件的平台，用户能用选择安装想要的小功能。

**Comment by gdh1995** [comment]
啊不至于，插件互相配合的坑太多了。因为浏览器厂家（主要是Google）不希望这么做，他们设计接口的时候就不照顾甚至故意破坏这类需求，所以坑填不了。

真弄的话，用 Vimium C 的 `map xxx openUrl url="javascript:xxxxxxx"`（或者`openBookmark title=xxx`）来执行特定 JS 命令，比如`window.dispatchEvent`一个特定类型的事件，然后别的插件可以监听这个事件执行动作，这样也能联动。

Vimium C 还有一个 `dispatchEvent` 可以按参数派发事件，不过参数有点多，不想用的就直接编写JS url吧。

**Comment by xchnotxzh** [comment]
> 啊不至于，插件互相配合的坑太多了。因为浏览器厂家（主要是Google）不希望这么做，他们设计接口的时候就不照顾甚至故意破坏这类需求，所以坑填不了。
> 
> 真弄的话，用 Vimium C 的 `map xxx openUrl url="javascript:xxxxxxx"`（或者`openBookmark title=xxx`）来执行特定 JS 命令，比如`window.dispatchEvent`一个特定类型的事件，然后别的插件可以监听这个事件执行动作，这样也能联动。
> 
> Vimium C 还有一个 `dispatchEvent` 可以按参数派发事件，不过参数有点多，不想用的就直接编写JS url吧。

我没有考虑到详细实现的难点。
我说的小功能，指的是能基于Vimium C 命令组合出来的功能，
编写javascript 是另外一个层次的功能了。

作者觉得不可行的话，麻烦帮我关下这个issue。

**Comment by gdh1995** [comment]
现在已经可以组合多条命令来绑到一个快捷键了，也支持条件分支，参考 https://github.com/gdh1995/vimium-c/wiki/Auto-run-a-tree-of-commands

比如下边这个
```
map W scrollToTop
map i runKey keys="focusInput?:(mainFrame:W+150wait)%cfocusInput" \
  o.keep o.select="all-line" o.reachable \
  o.prefer="#js-issues-search,#searchEngines"
```

就是我为了增强 `focusInput` 功能写的，如果在当前可视区域找不到文本框，就会去聚焦到顶级框架、滚动到页面开头，再尝试一次 `focusInput` 。
