### ISSUE TITLE
最新的v1.99.96版本会导致 LinkHints trigger dispatchEvent 失效

### ISSUE THREAD

**Issue by Wooolfboy** [gdh1995/vimium-c#823]
**Describe the bug**

之前添加的这2条规则在vimium-c更新为v1.99.96后失效，回退到v1.99.90后恢复正常
map f LinkHints.activateHover $then="\<v-notify\>"
map \<v-notify\> dispatchEvent class="custom" type="vimium:notify"

**To Reproduce**
更新到v1.99.96后100%失效

这2条规则是在之前的540中的解决方案 #540 

**Browser, OS and Vimium C versions**

- Browser name:    firefox 
- Browser version:     v107.0.1 (64位)
- Vimium C version:     v1.99.96
- OS name and version:    archlinux 6.0.11-arch1-1

**Comment by gdh1995** [comment]
Confirmed. Sorry it's caused by a simple typo while there's no way to work it around in Vimium C v1.99.96.

I'll fix it in a next version.

**Comment by Wooolfboy** [comment]
v1.99.97 已修复，问题关闭。非常感谢 @gdh1995
