### ISSUE TITLE
add bookmark folder to Block list of words for Vomnibar does not work

### ISSUE THREAD

**Issue by S-Aarab** [gdh1995/vimium-c#824]
**Describtion**

adding a folder to Block list of words for Vomnibar does not work in a new started firefox enless we modifie the block list and save the changes

**Steps to reproduce the behavior:**
1. create a bookmarks folder e.g: `hidden` and add some bookmarks to it e.g: `https://github.com/gdh1995/vimium-c`
2. add `/hidden` to the block list of words for vomnibar
3. restart firefox or just disable/enable vimium-c
4. launch vomnibar and search for one of the bookmarks that you added to the `/hidden` forlder e.g: `gdh`
5. the bookmark shows in the result despite being in the folder `/hidden` 
6. now make any change to the block list (just add empty line or comment)
7. do the search again, and the bookmark wont be in the result as expected
8. if you restarted firefox or disable/enable vimium-c the ploblem comes back again

**Browser, OS and Vimium C versions**

- Browser name: Firefox
- Browser version: 107.0.1
- Vimium C version: 1.99.96
- OS name and version: Archlinux

**Comment by gdh1995** [comment]
Confirmed. I'll fix it then.

**Comment by S-Aarab** [comment]
I can confirme that version 1.99.97 solved the issue, thank you for the amazing work.
