### ISSUE TITLE
提供选项禁止输出日志

### ISSUE THREAD

**Issue by tjx666** [gdh1995/vimium-c#825]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/207768112-5b03e592-947c-4959-b2b0-79eab3715a69.png">

**Comment by tjx666** [comment]
而且很奇怪，明明都已经在这个网页停用了，还有日志输出：
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/207768347-82c4205f-847e-4c01-9722-c15109d9cd6a.png">

**Comment by gdh1995** [comment]
这是设计问题。目前有一个日志会在初始化阶段就输出，这时候还不知道要在这个页面上完全禁用。我回头改改加一个等待。

不过我不打算加配置项来禁止日志，因为（给初始化期间的日志加等待后）这么做的必要性实在太小。

**Comment by gdh1995** [comment]
Hello, Vimium C v1.99.96+ has been available on Chrome Web Store, and you may take a try - it should not log the warning any more when it's disabled according to exclusion rule configurations.
