### ISSUE TITLE
如何改变visual模式下的keybinding?

### ISSUE THREAD

**Issue by cowboyliao** [gdh1995/vimium-c#827]
本人不是qwety用户, 用hjkl很别扭, 普通模式下都可以自定, 但浏览了wiki似乎visual模式没有rebing的方法?

**Comment by gdh1995** [comment]
参见 https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout#per-mode-mapkey ，可以逐个替换成你想用的键。

当前的visual mode映射参见
https://github.com/gdh1995/vimium-c/blob/fb16636f57acad100d5e5c9b8df4ca4bda132bed/background/key_mappings.ts#L789-L814

**Comment by cowboyliao** [comment]
对我来说,mapkey <n:v> <h>掉hjkl就可以了,但总之,学会了新的玩法,感谢回答!

**Comment by 2eronia** [comment]
> 参见 https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout#per-mode-mapkey ，可以逐个替换成你想用的键。
> 
> 当前的visual mode映射参见
> 
> https://github.com/gdh1995/vimium-c/blob/fb16636f57acad100d5e5c9b8df4ca4bda132bed/background/key_mappings.ts#L789-L814

搜了下，貌似没找到PageUp PageDown的键值。
(自带的scrollPageUp scrollPageDown在我的电脑上不够顺滑)
若要将 a 映射成键盘的 PageDown，A 映射成PageUp，想问问应该如何设置？

**Comment by gdh1995** [comment]
vimium c 的映射功能只在 vimium c 内部生效，不能影响浏览器原本的按键识别，因此不能让某一个键起到`对浏览器按下 pagedown`的效果
