### ISSUE TITLE
Open Image in New Tab

### ISSUE THREAD

**Issue by 50-sys** [gdh1995/vimium-c#828]
Hi, I have been enjoying this extension for more than a year now and would really like to have the same functionality for opening images in tabs as with the links in a page.

Thank you in advance.

**Comment by gdh1995** [comment]
There's a command named `LinkHints.activateOpenImage`, and you may write rules in `Custom key mappings` on Vimium C Options to use it, like:
```
map xxx LinkHints.activateOpenImage
```

![image](https://user-images.githubusercontent.com/5547703/209476425-069f0d5c-1c2c-4a34-8a7d-d906ce7a6546.png)
