### ISSUE TITLE
zoom

### ISSUE THREAD

**Issue by Monirzadeh** [gdh1995/vimium-c#83]
hi please add an option for zoom in and zoom out

**Comment by gdh1995** [comment]
Are `<c-=>` and `<c-->` not enough?

**Comment by Monirzadeh** [comment]
I try to set all tings with minimum keypress and effort
that keys are the opposite sides of the keyboard. I think if I can set key z and Z for zoom in and zoom out.
most important thing is the speed of Extention. if more feature makes that slow, I don't persist on that.

**Comment by gdh1995** [comment]
Hello. Vimium C v1.78.4 has been reeased and it has two new commands: `zoomIn` and `zoomOut`. So please take a try.
