### ISSUE TITLE
如果想修改omni bar 的宽度应该怎么做? 

### ISSUE THREAD

**Issue by woshichuanqilz** [gdh1995/vimium-c#833]
就是在按下 o 或者 b 调出一个输入栏, 怎么才能让这个输入栏的宽度短一些. 

我右键查看这个omni bar的元素信息, 知道这个bar的id是"bar", 
我在自定义css里面添加
```css
#bar{
width: 40%;
}
```
无效

我又查看了这个链接, 
https://github.com/gdh1995/vimium-c/wiki/Style-the-UI-of-Vimium-C-using-Custom-CSS

我把sizes的最后一个参数修改成了 0.4 但是没有反应
这个是我的代码

```css
{
  "actions": "",
  "maxMatches": 10,
  "queryInterval": 333,
  "sizes": "77,3,44,0.4",
  "styles": "mono-url"
}

```

![image](https://user-images.githubusercontent.com/11295355/209509877-5872d2de-7431-452a-935c-4f024838d31f.png)

**Comment by gdh1995** [comment]
你要改的是整个Vomnibar的宽度吧？

``` css
.Omnibar { left: 30vw; width: 40vw; }
```

然后 sizes 的 0.8 改 0.4 。

![image](https://user-images.githubusercontent.com/5547703/210123043-22b78835-6fb2-44f5-94e1-b39b4f1483fa.png)

**Comment by woshichuanqilz** [comment]
> 

谢谢这个是管用的但是我之前的两种方法为什么不行? 

您这个方法是在手册哪里有写?

**Comment by woshichuanqilz** [comment]
> 你要改的是整个Vomnibar的宽度吧？
> 
> ```css
> .Omnibar { left: 30vw; width: 40vw; }
> ```
> 
> 然后 sizes 的 0.8 改 0.4 。
> 
> ![image](https://user-images.githubusercontent.com/5547703/210123043-22b78835-6fb2-44f5-94e1-b39b4f1483fa.png)

谢谢这个是管用的但是我之前的两种方法为什么不行?

您这个方法是在手册哪里有写?

**Comment by gdh1995** [comment]
就是 https://github.com/gdh1995/vimium-c/wiki/Style-the-UI-of-Vimium-C-using-Custom-CSS

你对 CSS 的理解不符合 Vimium C 的实际用发，给 `#bar` 设宽度本来就没意义，要给整个iframe设宽度。

另外`#bar` 属于 Vomnibar的iframe内部样式，应该加上 `/* #omni */` 前缀。
