### ISSUE TITLE
shortcut userCustomized1 stops working randomly

### ISSUE THREAD

**Issue by Fred-Vatin** [gdh1995/vimium-c#834]
I always used `<c-f1>` as `shortcut userCustomized1 command="Vomnibar.activateInNewTab"` to call the vomnibar in any case. Since version [1.99.96](https://github.com/gdh1995/vimium-c/tree/v1.99.96), this shortcut stopped working. It works a few times on a site but after a while, it stopped triggering the command. It’s very hard to reproduce because it needs time to stop working. I know for sure it happens on twitter and youtube.

**Browser, OS and Vimium C versions**

- Browser name: firefox 
- Browser version: 108.0.1
- Vimium C version: [1.99.96](https://github.com/gdh1995/vimium-c/tree/v1.99.96)
- OS name and version:  Windows 10 21H2

**Workaround**

Downgrade to [1.99.90](https://github.com/gdh1995/vimium-c/tree/v1.99.90) solved this issue.

**Comment by gdh1995** [comment]
Um, if this issue is correct, then the `a while` is at least 2 minutes and 20 seconds and at most 5 minutes, so it's not easy to test.

I'll test it in days.

**Comment by Fred-Vatin** [comment]
Yes it is very hard to tell. And I switch tabs a lot. The best way to test is using `shortcut userCustomized1 command="Vomnibar.activateInNewTab"` instead of `o` until reproducing the bug.

I didn’t analyse the [changes](https://github.com/gdh1995/vimium-c/compare/v1.99.90...v1.99.96) between 1.99.96 and 1.99.90 but it happened there for sure.

**Comment by gdh1995** [comment]
Hello Vimium C v1.99.99 has been published and you may take a try.
