### ISSUE TITLE
Is there a pre-set command in vimium that I can jump address bar to search sth? 

### ISSUE THREAD

**Issue by heissonly** [gdh1995/vimium-c#835]
I am actually asking to assign this command as a global key with the help of [this ](https://chrome.google.com/webstore/detail/shortcut-forwarding-tool/clnalilglegcjmlgenoppklmfppddien?hl=en) extension. 

![image](https://user-images.githubusercontent.com/10747792/209985909-2b331f18-1dcd-4b2a-b7cf-08f8f906f053.png)

![image](https://user-images.githubusercontent.com/10747792/209985301-ec32beda-39e3-47d1-b9b8-e8421f930eff.png)

As you can see above I would like to go directly address bar with ctrl+t(e.g) since chrome (ctrl+t) doesn't work globally. 
it's going to be useful to search sth quickly in google since my default search engine google. (In other words, it will reduce to extra alt+tab keystroke , and it is  especially  beneficial when working with multiple screens to jump in directly chrome)

**Comment by gdh1995** [comment]
Um no, extensions can not move focus to the address bar without any side effect.

By default, Chrome uses `Alt+D` to focus the address bar on Windows, and `⌘ + l` on macOS.

You may find all built-in shortcuts of Chrome on https://support.google.com/chrome/answer/157179 .

**Comment by Cruising0904** [comment]
I might know the solution..

If you are on Window you can use power toys to implement with alt+space to search or you could change the hotkey
if you are on linux use ulauncher do the same thing on respective os.
