### ISSUE TITLE
Open a bookmark & Add tabs into a bookmark folder

### ISSUE THREAD

**Issue by anhth99** [gdh1995/vimium-c#838]
I don't know how to use these 2 features. Can you guide me?

**Comment by gdh1995** [comment]
### open

1. Open 1
  - see https://github.com/gdh1995/vimium-c/issues/596#issuecomment-1084389663
2. Open a folder
  - see https://github.com/gdh1995/vimium-c/issues/730#issuecomment-1340279361
3. for example, `map xxx openBookmark title="<your-bookmark-title>"` should select a bookmark or a folder of bookmarks, and then open it

### create bookmarks

1. see https://github.com/gdh1995/vimium-c/issues/663#issuecomment-1162290626
2. for example, `map xxx addBookmark folder="<your-bookmark-folder-title>" all` may select a folder and add all opened tabs into the folder
