### ISSUE TITLE
尝试给 visual mode 更多提示

### ISSUE THREAD

**Issue by uhuame** [gdh1995/vimium-c#839]
visual mode 需要更多提示 
对于刚刚接触的人真的会一头雾水 不知道如何切换 visual mode 或者 Caret Mode

把[Vimium](https://github.com/philc/vimium/wiki/Visual-Mode) 的wiki贴到常见问题？ 
或者将 按c切换到 Caret Mode 放到 显示帮助页面

我不知道如何做到，但是需要提示

**Comment by gdh1995** [comment]
这个模式是从vim里借鉴、简化出来的，所以不少命令对不知道vim的人来说很怪。

只能说等几年也许就有我写的帮助文档了……
