### ISSUE TITLE
passNextKey

### ISSUE THREAD

**Issue by rdewolff** [gdh1995/vimium-c#84]
Do you have an option like Vimium to `passNextKey` ?
Or a shortcut to enable and disable vimium c ?

**Comment by Monirzadeh** [comment]
an example
`map ; passNextKey`

**Comment by gdh1995** [comment]
There has been "passNextKey" and its function is much like the origin Vimium's.


If you can not see it on the command list dialog on Vimium C Options page, please scroll to the bottom of the dialog and click "show advanced commands".



---Original---

**Comment by gdh1995** [comment]
BTW, on Vimium C's popup page (the one showing when you click the top-right extension icon), there's buttons like "Disable Once", "Enable Once" and "Reset". A user may click one of the buttons to toggle Vimium C's working status on a current tab (not just a current HTML frame). The buttons also have shortcut keys like <kbd>Alt+X</kbd> (for Disable/Enable) and <kbd>Alt+Z</kbd> (for Reset).
