### ISSUE TITLE
Some key doesn't work with specific words:

### ISSUE THREAD

**Issue by heissonly** [gdh1995/vimium-c#841]
Custom key mappings
```
run <v-o2> autoOpen#selected&copied&keyword=$s mask
	
run <v-open>yw o2 yw
run <v-open>yyy o2 yy
```

Custom search engines

```

yw: https://www.youtube.com/results?search_query=%s Youtube
yy: https://www.youtube.com

```
So I would like to select a word and go to youtube with a search result page on youtube(y+w) but also sometimes directly go to youtube without searching anything. (y+y). Therefore I made the above setting. But there is an interesting bug.

The above setting not working with some specific (i.e y+w  or y+x ) key combination but work with others(y+a and y+c). I didn't understand why it is the case. 

Could you please identify issue ?

**Comment by gdh1995** [comment]
During my test both `yw` and `yyy` worked. I'm not sure why you failed, but you may check:
1. what's your keyboard layout - is it QWERTY-English, or another like French / Russian / Dvorak?
  - you may test what keys Vimium C will receive on "Vimium C Options":
 
![image](https://user-images.githubusercontent.com/5547703/218269630-51b864e9-199b-4097-918a-84035461ccbd.png)

2. what's your `mapKey` rules? I mean, now that you use `<v-open>` as a forced prefix key, then what key is mapped to `<v-open>` on your browser?
  - I tested `mapKey q <v-open>`, and then both `qyw` and `qyyy` worked as expected.
