### ISSUE TITLE
网页静音问题

### ISSUE THREAD

**Issue by OrangeCatSleepless** [gdh1995/vimium-c#842]
大佬，请问该如何给同一域名下的所有网站静音？

**Comment by gdh1995** [comment]
```
map xxx toggleMuteTab filter="host"
```

默认对所有同域名的标签页切换静音状态，切换到当前网页的相反状态。

**Comment by OrangeCatSleepless** [comment]
> ```
> map xxx toggleMuteTab filter="host"
> ```
> 
> 默认对所有同域名的标签页切换静音状态，切换到当前网页的相反状态。

感谢大佬！问题已解决！
