### ISSUE TITLE
It does not work when there are such pages

### ISSUE THREAD

**Issue by LeePheon** [gdh1995/vimium-c#844]
**What command or commands**

It does not work when there are such pages
       - pages failed to load like: [![23ubE.png](https://i.328888.xyz/2023/01/15/23ubE.png)](https://imgloc.com/i/23ubE)
       - internal browser page like: edge://version OR edge://extensions OR edge://flags/

**How should a feature do**

Is there solutions? Above pages make me use mouse when i encounter them and feel awful

**Browser and OS**

- Browser name: Edge 109.0.1518.52 (Official build) (64-bit) 
- OS name: windows 11 10.0.22621 Build 22621

- extension version: 1.99.96

**Comment by LeePheon** [comment]
pages failed to load : <img src="https://i.328888.xyz/2023/01/15/23ubE.png" alt="23ubE.png" border="0" />

**Comment by barrrricade** [comment]
It's a browser security 'feature'. For chrome at least. Extensions are not allowed to run on internal pages and https://chrome.google.com/.
I think it's to do with not letting extensions modify/change browser configs or send data.

But a solution would be to use. `ctrl + tab` to switch to an extension enabled tab.

**Comment by LeePheon** [comment]
thanks for your reply.
This extension is wonderful for browser users,&nbsp;



李贤
***@***.***







                       
Original
                       
                     

From:"D. Ip"< ***@***.*** &gt;;

Date:2023/1/24 16:03

To:"gdh1995/vimium-c"< ***@***.*** &gt;;

CC:"LeePheon"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [gdh1995/vimium-c] It does not work when there are such pages(Issue #844)




 
It's a browser security 'feature'. For chrome at least. Extensions are not allowed to run on internal pages and https://chrome.google.com/.
 I think it's to do with not letting extensions modify/change browser configs or send data.
 
But a solution would be to use. ctrl + tab to switch to an extension enabled tab.

**Comment by gdh1995** [comment]
you may go to "chrome://extensions/shortcut" to add some global shortcuts for Vimium C's several commands, and then you may use a different key to switch among tabs - myself use Alt-C and Alt-V.

**Comment by LeePheon** [comment]
Wow, it is a solution! I set alt+k/j for two cases: when extension works, and when can not work.
Thank for your effort to make developments on this extension!

**Comment by Acumane** [comment]
> you may go to "chrome://extensions/shortcut" to add some global shortcuts for Vimium C's several commands

@gdh1995 This works for keys listed there, but what about other tab actions like pin, duplicate, and move left/right?
![Screenshot from 2023-05-10 17-39-06](https://github.com/gdh1995/vimium-c/assets/94324138/47ac97ec-cbd0-4904-8800-492149b11140)

**Comment by gdh1995** [comment]
You may remap them using `shortcut` directive in "custom key mappings" - see https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box#global-shortcuts

**Comment by LeePheon** [comment]
Thanks very much, I appreciate these functionality, which can increase productivity

Sent from Mail for Windows
