### ISSUE TITLE
Trying to make F4 to switch to previously visited tab

### ISSUE THREAD

**Issue by srikat** [gdh1995/vimium-c#845]
I am trying to have F4 keypress switch to previously visited tab in Chrome using

```
map f4 visitPreviousTab
```

but nothing happens when F4 is pressed. Any idea?

It works fine if I set it to a key like this:

```
map ` visitPreviousTab
```

**Comment by srikat** [comment]
had to put f4 in angular brackets.

```
map <f4> visitPreviousTab
```

**Comment by gdh1995** [comment]
```map <f4> visitPreviousTav```
