### ISSUE TITLE
Wikipedia's new look: language selection problems

### ISSUE THREAD

**Issue by philipphutterer** [gdh1995/vimium-c#848]
Since Wikipedia's [introduction of a new look](https://wikimediafoundation.org/wikipedia-desktop/), the language selection is not accessible via Vimium anymore, as it is now an input tag and is no longer wrapped by an anchor tag. I don't know if there is a reasonable solution for this on Vimium side, but if not this thread might keep track of the problem and possible solutions. Probably Wikipedia will fix this in some future iteration.

**Comment by gdh1995** [comment]
Confirm, and it's because the new page uses some non-standard trick to implement the clickable input box.

I'll fix it in a next version.
