### ISSUE TITLE
[Feature request] Move selected tab as next tab

### ISSUE THREAD

**Issue by rieje** [gdh1995/vimium-c#849]
Vimium is a life saver for those with many tabs. However, often times it is more convenient to open a new tab to an existing webpage on another tab than to switch to the old tab because you want this duplicate tab to be next to your current tab.

It would be really nice to allow the option to not only switch to existing matched tab but move it next to your current tab. That makes it very easy to move existing tabs to adjacent tabs for organization.

**Comment by backuponeday** [comment]
try this `map t createTab position="right"` command, when creating a new label, it will be on the right side of the current label
support `"next" | "prev" | "previous" | "left" | "right" | "start" | "begin" | "end" | "before" `

**Comment by rieje** [comment]
I mean when using Vomnibar.activateTabs (`T`), on hovered open tab, move it next to current tab. The suggested binding `map t createTab position="right"` is for new tabs and with my Firefox settings is already the behavior I have but is not what I'm describing (I should have described it better, updated original post).
