### ISSUE TITLE
map <esc> to close omnibar?

### ISSUE THREAD

**Issue by GLodi** [gdh1995/vimium-c#85]
Back in Vimium I was able to set: mapkey <c-g> <esc> to close the omnibar with c-g instead of using escape directly. That same mapkey now won't close the omnibar, even though it will still escape the character selection after pressing f.

Are key mappings not enabled when the omnibar is shown?

I'm on firefox, if it's helpful.

Thanks.

**Comment by gdh1995** [comment]
Yes, not implemented currently, because Vomnibar runs in an independent environment and mapped keys are not in use there.


I'll add this feature of "map keys" in the next released version of Vimium C, and it may be v1.79.0 .



---Original---

**Comment by gdh1995** [comment]
Hello, Vimium C v1.78.6 has been released on Firefox Add-ons, and you may take a try.

**Comment by GLodi** [comment]
Thank you! It works!
