### ISSUE TITLE
Issues regarding copying percent-encoded URLs

### ISSUE THREAD

**Issue by sharimot** [gdh1995/vimium-c#850]
When I use `copyCurrentUrl` or `LinkHints.activateCopyLinkUrl`, I occasionally get slightly different results than what I would get by using the browser's default methods.

Take the following URLs for example:

- <https://example.com/%27>
- <https://example.com/%F0%9F%98%80>

When you compare the URL obtained by using `LinkHints.activateCopyLinkUrl` to the one obtained by the default method of right click -> copy link address, you can see that they are different in that Vimium-C gives the decoded version of the URL. Likewise, when you are on one of the above pages, the copied address obtained by using `copyCurrentUrl` and that obtained by clicking on the address bar and copying the entire URL are different.

Is this a feature or a bug? If this is a feature, what would justify this type of behavior?

**Comment by gdh1995** [comment]
Yes it's a feature. You may try "map xxxx LinkHints.activateCopyText decode=false"

**Comment by sharimot** [comment]
Thank you! I was able to disable it.

**Comment by gdh1995** [comment]
Hello, in a latest version of Vimium C, the first link will be copied as-is, because its last character is not in `a-z`, `0-9` or emoji characters; while the second link will be auto-decoded by defaullt - `decode=false` should be enough for most copying-URL commands.
