### ISSUE TITLE
[需求] 希望能给Vomnibar搜索出来的书签增加右键菜单

### ISSUE THREAD

**Issue by iamqiz** [gdh1995/vimium-c#853]
增加 取消收藏, 修改名称, 在书签管理器(ctrl+shift+O)中打开 等菜单项
这样不仅可以搜索书签,还可以管理书签

右键菜单希望可以通过windows的菜单键(appkey)来触发

😄谢谢大佬,新年快乐🎈

**Comment by gdh1995** [comment]
从整体设计上，Vimium C 不会负责管理书签，而是只提供搜索书签的功能。需要管理的话请用别的更专业的书签管理工具。

另外右键菜单几乎没法修改东西，自己重画整个右键菜单也太浪费精力了没意义。

**Comment by iamqiz** [comment]
好吧,谢谢大佬的解答~
