### ISSUE TITLE
[Request] Error for lacking ':' in "Custom search engines" option

### ISSUE THREAD

**Issue by Dugesia7** [gdh1995/vimium-c#855]
Currently "Custom search engines" column in Vimium-C Options seems not throw any error when saving though it has some values without ':'.
This caused me to be in trouble for 30min, so I want an error for this like when invalid values are in "Custom key mappings" column.

**Comment by gdh1995** [comment]
Um the work would be too heavy, so I didn't spend time in adding it in the past 7 years.

Up to now "custom key mappings" is the only option item which has detailed error messages; while "custom search engines" and "Auto substitution of various text" will ignore mistakes silently.
