### ISSUE TITLE
LinkHints.activateSelect cowork with web marker extension

### ISSUE THREAD

**Issue by cadem** [gdh1995/vimium-c#856]
I used web marker extension, such as "Get liner", when I select some text by mouse, Get Liner button popup, I can click this button to mark selected text.
But I use LinkHints.activateSelect to select text, the text is selected but Get Liner button popup is not trigger.
Can I make LinkHints.activateSelect with this kind extension?

**Comment by gdh1995** [comment]
Um, up to now you need to trigger a key mapping in Vimium C to notify other extensions that "some text has been selected":
```
map xxx dispatchEvent type="click" direct="selection"
```
