### ISSUE TITLE
Firefox 70: Hovering does not activate menus

### ISSUE THREAD

**Issue by norbert-op** [gdh1995/vimium-c#86]
From the name of this command, I expected it to act like a mouse cursor hovering over a spot, or to actually move the cursor. I mapped them to the following keys and link hints do pop up, but the menu does not activate after entering the link hint.

This is the page I was trying to open menus by hovering on: https://www.dominicanajournal.org

These are my mappings;
```
map gf LinkHints.activateModeToHover
map gF LinkHints.activateModeToLeave
map gl LinkHints.unhoverLast
```

**Comment by gdh1995** [comment]
Well, it's a limitation of browsers that makes Vimium C can not "hover" the menus.

In fact, there are 2 things named "hover", and when we use a mouse to hover a thing, there will be:
1. move mouse (from other places) to the target, which is a "hover" action (`MouseEvent#mouseover`, `mouseenter` and then `mousemove`)
2. then the browser knows the target is being hovered, and paints it in "hover" mode (`:hover` CSS selector)

Using the web-extension APIs and standard DOM APIs, Vimium C can only simulate the first item, so a target will lack the CSS state of `:hover` and shows nothing.

**Comment by norbert-op** [comment]
That's too bad, but thanks for the explanation. I guess we still have to use a mouse, then.

**Comment by RealYukiSan** [comment]
If that's the case, how can the command `map X LinkHints.activateMode action=hover` be useful? I saw it on the Tips and Tricks page of the Wiki, but I’m not sure if it works effectively.

**Comment by gdh1995** [comment]
@RealYukiSan The command sends "simulated" (aka. fake) `mouseover`, `mouseenter` and `mousemove` events to a selected element, and then webpages, not your browser itself, may respond on such events and do whatever they want.
