### ISSUE TITLE
Unexpected Behavior of Link Hints When Chromium Flags To Force Dark Mode Is Enabled

### ISSUE THREAD

**Issue by eeriemyxi** [gdh1995/vimium-c#860]
I use the Chromium flag instead of some external extension to force dark mode to all sites; it is not perfect as Dark Reader is, but I really cannot afford the RAM usage and extra CPU usage that it takes on each tab (I am presuming here that the flag will not take too many resources).

When I have that option enabled, this is how link hints look:
![image](https://user-images.githubusercontent.com/86738916/216110927-9267b395-a1cb-4113-8450-8c83dacd3c6e.png)

As you can see, it is not really that visibly cozy to ordinary people like me; I think this can be fixed by disabling the gradient the creator had added and then using a dark color as the background (and bright text color of course) through the custom CSS on UI elements option.

However, I have no idea where to get the attributes of the elements to customise them nor am I good at CSS. Can somebody help me on this?

**Comment by gdh1995** [comment]
See https://github.com/gdh1995/vimium-c/wiki/Style-the-UI-of-Vimium-C-using-custom-CSS#work-with-enable-force-dark .

I have no good ideas. So I'm afraid you have to write your own CSS.

Fortunately CSS is not difficult - you just need to take a look at https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient .

**Comment by gdh1995** [comment]
Um, please try this:

1. add this CSS code to `Custom CSS for Vimium C UI`.
``` css
.LH, .D>.LH { background: linear-gradient(hsl(56deg 100% 30%),hsl(42deg 100% 25%)); color: #f1f1f1; }
```
2. and add `dark` to `styles` in `Vomnibar settings`, so that it looks like `"style": "mono-url dark"`.

**Comment by eeriemyxi** [comment]
> Um, please try this:
> 
> 1. add this CSS code to `Custom CSS for Vimium C UI`.
> ``` css
> .LH, .D>.LH { background: linear-gradient(hsl(56deg 100% 30%),hsl(42deg 100% 25%)); color: #f1f1f1; }
> ```
> 2. and add `dark` to `styles` in `Vomnibar settings`, so that it looks like `"style": "mono-url dark"`.
> 

Hello, thank you for the link to the theming guide and the steps you provided successfully convinced Chromium that it is indeed dark enough not apply the imposed dark mode. Thank you.
