### ISSUE TITLE
[Help Wanted] Visual Mode Controls

### ISSUE THREAD

**Issue by X2Zii** [gdh1995/vimium-c#863]
<help wanted>

Is there a way to edit the visual mode controls?

- Browser name: Chrome, version:**109.0.5414.120 (Official Build) (64-bit) (cohort: Stable)** 
- OS name: **Windows 11 Version 22H2 (Build 22621.1194)**
- Vimium Version: **1.99.96**

**Comment by gdh1995** [comment]
Um, you may use `mapKey` to change what keys VisualMode receives without affecting other modes: https://github.com/gdh1995/vimium-c/wiki/Use-in-another-keyboard-layout#per-mode-mapkey .

For example: `map <j:v> k` will make `j`  select one line above in visual mode.

**Comment by X2Zii** [comment]
Okay thanks. I'm new to github and the likes.
Didn't know there was a wiki with all the documentation.
But I'll remember for the future.

Thanks.
