### ISSUE TITLE
Still don't understand how to map a customized key to an action for a specific website after reading the doc

### ISSUE THREAD

**Issue by zxfdev** [gdh1995/vimium-c#866]
Question about mapping a key to an action:

I wanna map a key to click an element on a **specific** webpage, and map the **same** key to click a **different** element on a **different** webpage(different URL). 

But after reading the [documentation](https://github.com/gdh1995/vimium-c/wiki/Map-a-key-to-different-commands-on-different-websites), I still don't understand how to make it work **only** on a specific webpage, for example:

I wanna map `s` to click `.bpx-player-ctrl-web-enter` only on `https://www.bilibili.com/video/*`:
```env biliplaying host="^https://www.bilibili.com/video/*"
map s runKey expect={"biliplaying":"<v-findwebenter>"} keys="<v-clickwebenter>"
map <v-findwebenter> LinkHints.click direct="element" match=".bpx-player-ctrl-web-enter"
map <v-clickwebenter> LinkHints.click
```
It seems it works on every webpage now(when pressing `s` on any other webpage, it would popup a toast with 'No matching targets found'), not **only** on `https://www.bilibili.com/video/*`. I know I didn't fully understand the documentation.
BTW, here I map `s` to click one element on bilibili, and I intend to map s to click **another**  element on **another** webpage, like `https://www.youtube.com/watch*`.

Thanks for helping.

- Browser name:  Google Chrome, 109.0.5414.87 (Official Build) (arm64) 
- OS name: macOS Version 13.2 (Build 22D49)
- Vimium C: 1.99.96

**Comment by gdh1995** [comment]
The mapping you provided here doesn't contain any rule of `env biliplaying`, so `s` won't go to `<v-findwebenter>`.

Please try this:
```
env biliplaying url=":https://www.bilibili.com/video/"
map s runKey expect="biliplaying:<v-find_web_enter>" keys="<v-click_web_enter>"
map <v-find_web_enter> LinkHints.click direct="element" match=".bpx-player-ctrl-web-enter"
map <v-click_web_enter> LinkHints.click
```

**Comment by xianfengzhu340** [comment]
Thanks, I forgot to paste the env line.

I tried your codes, but it seems the key `s` also works on other webpages. How to make it only work on the page specified by env?

**Comment by gdh1995** [comment]
On other websites, it should act as `<v-click_web_enter>`. So do you mean you want Vimium C to pass `s` on other webpages?

**Comment by xianfengzhu340** [comment]
right, I want it to bypass `s` on other webpages, like google.com. According to my understanding, this is defined by `expect ` and `biliplaying `

**Comment by backuponeday** [comment]
`env biliplaying url=":https://www.bilibili.com/video/"`
`map <v-ssss> LinkHints.click direct="element" match=".bpx-player-ctrl-web-enter"`
`map s runKey expect={"biliplaying":"<v-ssss>"} keys="blank"`
这样?

**Comment by xiaoxiang52** [comment]
> 有关将键映射到操作的问题：
> 
> 我想映射一个键来单击**特定**网页上的元素，并映射**相同的**键来单击不同网页（不同的 URL）上的**不同**元素。
> 
> 但是在阅读[文档](https://github.com/gdh1995/vimium-c/wiki/Map-a-key-to-different-commands-on-different-websites)后，我仍然不明白如何使其**仅在**特定网页上工作，例如：
> 
> 我只想映射以单击：`s``.bpx-player-ctrl-web-enter``https://www.bilibili.com/video/*`
> 
> ```shell
> map s runKey expect={"biliplaying":"<v-findwebenter>"} keys="<v-clickwebenter>"
> map <v-findwebenter> LinkHints.click direct="element" match=".bpx-player-ctrl-web-enter"
> map <v-clickwebenter> LinkHints.click
> ```
> 
> 它现在似乎适用于每个网页（当按下任何其他网页时，它会弹出一个带有“找不到匹配目标”的吐司），**而不仅仅是**在.我知道我没有完全理解文档。顺便说一句，在这里我映射以单击哔哩哔哩上的一个元素，我打算映射 s 以单击**另一个**网页上**的另一个**元素，例如.`s``https://www.bilibili.com/video/*``s``https://www.youtube.com/watch*`
> 
> 感谢您的帮助。
> 
> * 浏览器名称：谷歌浏览器，109.0.5414.87（官方版本）（arm64）
> * 操作系统名称：macOS 版本 13.2（内部版本 22D49）
> * Vimium C： 1.99.96

能否付费请您帮我写一段代码，排除掉网页大部分元素，f键只针对readwise插件按钮

![image](https://user-images.githubusercontent.com/127318734/226377524-614165be-378a-4ed5-bcb7-bc2f594a8b4f.png)

**Comment by gdh1995** [comment]
The last comment has been solved by https://github.com/gdh1995/vimium-c/issues/895#issuecomment-1479926112 , so close it.

**Comment by talhagozutok** [comment]
From https://github.com/gdh1995/vimium-c/issues/866#issuecomment-1430169425 I wrote some key mappings to take action on specific elements on a specific website using Vimium C.

Here's Vimium C like mappings.
```
# You can test this env with https://videojs.com/advanced/?video=elephantsdream
env vdjsEnv url=":https://videojs.com/"
map t runKey expect="vdjsEnv:<v-vdjs_pl>+<v-vdjs_menu>+<v-vdjs_sSwitch>+<v-vdjs_pl>" keys="vdjs_t-vdjs_t"
map <v-vdjs_pl> LinkHints.click direct="element" match="#preview-player_html5_api"
map <v-vdjs_menu> LinkHints.click direct="element" match=".vjs-subs-caps-button\u0020>\u0020button"
map <v-vdjs_sSwitch> LinkHints.click direct="element" match="li.vjs-menu-item.vjs-subtitles-menu-item:not(.vjs-selected)"
run <v-vdjs_t> dispatchEvent#key=t
```

We can run JavaScript code as well.
```
env vdjsEnv url=":https://videojs.com/"
map t runKey expect="vdjsEnv:<v-vdjs_sSwitch>" keys="vdjs_t-vdjs_t"
map <v-vdjs_sSwitch> openUrl url="javascript:(()=>{document.querySelector('button.vjs-subs-caps-button')?.click(),setTimeout(()=>{document.querySelector('.vjs-subtitles-menu-item:not(.vjs-selected)')?.click();document.querySelector('video')?.focus();},20);})();"
run <v-vdjs_t> dispatchEvent#key=t
```

<details><summary>Explanations</summary>

```
# Specify the environment.
env vdjsEnv url=":https://videojs.com"

# Define a key mapping for sequential actions.
# `expect` specifies a sequence of virtual keys (`v-`) to be executed consecutively using the `+` operator.
# The keys are mapped to a specific keypress (`vdjs_t`) for triggering these actions in the environment.
# Further read: https://github.com/gdh1995/vimium-c/wiki/Auto-run-a-tree-of-commands#tree-sytnax
map t runKey expect="vdjsEnv:<v-vdjs_pl>+<v-vdjs_menu>+<v-vdjs_sSwitch>+<v-vdjs_pl>" keys="vdjs_t-vdjs_t"

# The following lines define the specific actions to perform when each mapped key is triggered.

# Map the virtual key `<v-vdjs_pl>` to simulate a click event no.
# The click is targeted at an element matching the CSS selector `#preview-player_html5_api`, 
# which likely corresponds to the main video player or a similar component.
map <v-vdjs_pl> LinkHints.click direct="element" match="#preview-player_html5_api"

# Map the virtual key `<v-vdjs_menu>` to simulate a click on the subtitle or captions menu.
# The target is a button inside a `.vjs-subs-caps-button` container.
map <v-vdjs_menu> LinkHints.click direct="element" match=".vjs-subs-caps-button\u0020>\u0020button"

# Map the virtual key `<v-vdjs_sSwitch>` to select an unselected caption or subtitle option.
# The CSS selector targets a menu item that is not currently selected.
map <v-vdjs_sSwitch> LinkHints.click direct="element" match="li.vjs-menu-item.vjs-subtitles-menu-item:not(.vjs-selected)"

# Handle cases where the environment is not specified.
# If `vdjsEnv` is not active, only the mapped key `t` will be sent as a key event (`key=t`),
# without performing any of the defined clicks.
run <v-vdjs_t> dispatchEvent#key=t
```

</details>

I'm not sure of the correct way to click certain elements with delays in Vimium C, but this works for my case. Hope this helps someone!
