### ISSUE TITLE
How to add a new keyboard shortcut with modifier keys

### ISSUE THREAD

**Issue by iKineticate** [gdh1995/vimium-c#867]
I hope you can add letters before the Alt or CTRL keys to achieve shortcut key combinations.
For example, map j < A > scrollPageDown. 
Implement scrollPageDown with the J + Alt key combination.
Wish you good health.

**Comment by gdh1995** [comment]
If you mean to hold on `Alt` and then press down `J`, then it has been supported - you may see https://github.com/philc/vimium#keyboard-bindings :
> Modifier keys are specified as `<c-x>`, `<m-x>`, and `<a-x>` for `ctrl+x`, `meta+x`, and `alt+x` respectively.

Note: on Vimium C, for `shift+x` and `ctrl-shift-x`, you need to type `X` and <c-s-x>.

If you mean a key of `j` and a following key of `Alt`, then you may enable the `Allow mapping right-hand (or left-hand) modifier keys`, add `map j<a-modifier> scrollPageDown` and then press `j` and `Right Alt`.

**Comment by iKineticate** [comment]
Thank you very much
