### ISSUE TITLE
建议增加翻译单词功能

### ISSUE THREAD

**Issue by git708** [gdh1995/vimium-c#868]
建议增加翻译单词功能，翻译光标所在英文为中文也可以输入不同单词翻译，可以参考surfingkeys，它是连接到网上的翻译接口

**Comment by gdh1995** [comment]
Vimium C 不是专业的翻译工具，建议用“沙拉查词 ( https://github.com/crimx/ext-saladict )”、“侧边翻译/EdgeTranslate (https://github.com/EdgeTranslate/EdgeTranslate)” 做这个。

Vimium C 可以用来做“模拟点击”，来触发沙拉查词的对话框，参考 https://github.com/gdh1995/vimium-c/issues/247#issuecomment-753818398
