### ISSUE TITLE
建议LinkHints.activate增加检测可以点击的地方

### ISSUE THREAD

**Issue by git708** [gdh1995/vimium-c#869]
很多网页上代码收缩的地方，有个下箭头，点击代码可以展开。
vimium c不支持检测该箭头，无法按键展开代码。
可以参考surfingkeys

**Comment by backuponeday** [comment]
有些需要自己添加. 可以参考#638

**Comment by git708** [comment]
![image](https://user-images.githubusercontent.com/56986312/219822419-b3ad4304-9003-4135-8598-639a1ee3c95c.png)
像上图的下箭头，还没找到方法

**Comment by git708** [comment]
https://blog.csdn.net/feikudai8460/article/details/124636915,谢谢

**Comment by backuponeday** [comment]
`map f  LinkHints.activate clickable=".look-more-preCode" exclude=`
`clickable`可点击, `exclude`排除可点击.

**Comment by git708** [comment]
好的，谢谢，不过还要自己配置，能不配置就好了，毕竟它是可点击元素。

**Comment by gdh1995** [comment]
csdn、百度知道这种网页设计得都比较老了，各种按钮都是随便画出来的，不按约定的网页开发规范设置标记，Vimum C 就没法知道哪些可以点、哪些不能。所以必须用 `clickable=xxx` 来辅助。
