### ISSUE TITLE
有些页面元素无法点击，网页好像使用的antd的框架

### ISSUE THREAD

**Issue by zhiquanchi** [gdh1995/vimium-c#871]
xpath路径如下 ，公司内部系统，无法发送网址。望见谅。
这种的选择器的 class="ant-table-tbody"  下属成员。无法点击

**Comment by gdh1995** [comment]
xpath没贴上来？可以考虑 https://github.com/gdh1995/vimium-c/wiki/Add-or-remove-hints 来手动标记哪些元素能点击

**Comment by gdh1995** [comment]
这个 xpath 没啥用，能在 https://ant.design/components/table-cn 页面上截图圈出来类似的位置吗？

仍然建议自己加 clickable 参数来指定。

**Comment by zhiquanchi** [comment]
![image](https://user-images.githubusercontent.com/29973289/226186577-cc52681f-00f2-4c70-8559-4bfdd9db4c5b.png)
在公司的网站上无法点击的是红框圈起来的这个地方。但是在ant的官网是可以点击的。

**Comment by gdh1995** [comment]
那可能是版本问题，或者是你们公司内部实现页面的时候，自己画了链接按钮，而不是用的 ant design 的标准做法。写 `clickable` 参数吧。

**Comment by zhiquanchi** [comment]
我用selenium的时候是可以选择这个地方的
vim-c找不到这个元素
![image](https://user-images.githubusercontent.com/29973289/226513426-a99c5019-6d18-4787-bdc8-20f8a5f6328b.png)
----
selenium可以找到这个元素
![image](https://user-images.githubusercontent.com/29973289/226513576-e7693e2a-c07f-4e88-8edb-ab7ef984249d.png)

**Comment by zhiquanchi** [comment]
<div class="ant-spin-nested-loading">
        <div class="ant-spin-container">
            <div class="ant-table ant-table-default ant-table-scroll-position-right">
                <div class="ant-table-content">
                    <div class="ant-table-scroll">
                        <div tabindex="-1" class="ant-table-body" style="overflow-x: scroll;">
                            <table class="ant-table-fixed" style="width: max-content;">
                                <colgroup>
                                    <col style="width: 180px; min-width: 180px;">
                                    <col>
                                    <col style="width: 150px; min-width: 150px;">
                                    <col style="width: 150px; min-width: 150px;">
                                    <col>
                                    <col style="width: 100px; min-width: 100px;">
                                    <col style="width: 150px; min-width: 150px;">
                                    <col style="width: 200px; min-width: 200px;">
                                    <col>
                                    <col>
                                    <col>
                                    <col>
                                    <col>
                                    <col style="width: 200px; min-width: 200px;">
                                    <col>
                                    <col>
                                    <col>
                                </colgroup>
                                <thead class="ant-table-thead">
                                    <tr>
                                        <th class="ant-table-row-cell-break-word"><span class="ant-table-header-column">
                                                <div><span class="ant-table-column-title">工单id</span><span
                                                        class="ant-table-column-sorter"></span></div>
                                            </span></th>
                                        <th class=""><span class="ant-table-header-column">
                                                <div><span class="ant-table-column-title">工单标题</span><span
                                                        class="ant-table-column-sorter"></span></div>
                                            </span></th>
                                        <th class="ant-table-row-cell-break-word"><span class="ant-table-header-column">
                                                <div><span class="ant-table-column-title">工单类型</span><span
                                                        class="ant-table-column-sorter"></span></div>
                                            </span></th>
                                        <th class="ant-table-row-cell-break-word"><span class="ant-table-header-column">
                                                <div><span class="ant-table-column-title">未读的用户留言</span><span
                                                        class="ant-table-column-sorter"></span></div>
                                            </span></th>
                                        <th class=""><span class="ant-table-header-column">
                                                <div><span class="ant-table-column-title">预警订单个数<i
                                                            aria-label="图标: question-circle"
                                                            class="anticon anticon-question-circle"><svg
                                                                viewBox="64 64 896 896" focusable="false" class=""
                                                                data-icon="question-circle" width="1em" height="1em"
                                                                fill="currentColor" aria-hidden="true">
                                                                <path
                                                                    d="M512 64C264.6 64 64 264.6 64 512s200.6 448 448 448 448-200.6 448-448S759.4 64 512 64zm0 820c-205.4 0-372-166.6-372-372s166.6-372 372-372 372 166.6 372 372-166.6 372-372 372z">
                                                                </path>
                                                                <path
                                                                    d="M623.6 316.7C593.6 290.4 554 276 512 276s-81.6 14.5-111.6 40.7C369.2 344 352 380.7 352 420v7.6c0 4.4 3.6 8 8 8h48c4.4 0 8-3.6 8-8V420c0-44.1 43.1-80 96-80s96 35.9 96 80c0 31.1-22 59.6-56.1 72.7-21.2 8.1-39.2 22.3-52.1 40.9-13.1 19-19.9 41.8-19.9 64.9V620c0 4.4 3.6 8 8 8h48c4.4 0 8-3.6 8-8v-22.7a48.3 48.3 0 0 1 30.9-44.8c59-22.7 97.1-74.7 97.1-132.5.1-39.3-17.1-76-48.3-103.3zM472 732a40 40 0 1 0 80 0 40 40 0 1 0-80 0z">
                                                                </path>
                                                            </svg></i></span><span
                                                        class="ant-table-column-sorter"></span></div>
                                            </span></th>
                                        <th class="ant-table-row-cell-break-word"><span class="ant-table-header-column">
                                                <div><span class="ant-table-column-title">工单备注</span><span
                                                        class="ant-table-column-sorter"></span></div>
                                            </span></th>
                                        <th class="ant-table-row-cell-break-word"><span class="ant-table-header-column">
                                                <div><span class="ant-table-column-title">售后类型</span><span
                                                        class="ant-table-column-sorter"></span></div>
                                            </span></th>
                                        <th class="ant-table-row-cell-break-word"><span class="ant-table-header-column">
                                                <div><span class="ant-table-column-title">售后状态</span><span
                                                        class="ant-table-column-sorter"></span></div>
                                            </span></th>
                                        <th class=""><span class="ant-table-header-column">
                                                <div><span class="ant-table-column-title">二级订单号</span><span
                                                        class="ant-table-column-sorter"></span></div>
                                            </span></th>
                                        <th class=""><span class="ant-table-header-column">
                                                <div><span class="ant-table-column-title">商品</span><span
                                                        class="ant-table-column-sorter"></span></div>
                                            </span></th>
                                        <th class=""><span class="ant-table-header-column">
                                                <div><span class="ant-table-column-title">供应商名称</span><span
                                                        class="ant-table-column-sorter"></span></div>
                                            </span></th>
                                        <th class=""><span class="ant-table-header-column">
                                                <div><span class="ant-table-column-title">上门取件状态</span><span
                                                        class="ant-table-column-sorter"></span></div>
                                            </span></th>
                                        <th class=""><span class="ant-table-header-column">
                                                <div><span class="ant-table-column-title">商品价值</span><span
                                                        class="ant-table-column-sorter"></span></div>
                                            </span></th>
                                        <th class="ant-table-row-cell-break-word"><span class="ant-table-header-column">
                                                <div><span class="ant-table-column-title">创建人名称</span><span
                                                        class="ant-table-column-sorter"></span></div>
                                            </span></th>
                                        <th class=""><span class="ant-table-header-column">
                                                <div><span class="ant-table-column-title">跟进组</span><span
                                                        class="ant-table-column-sorter"></span></div>
                                            </span></th>
                                        <th class=""><span class="ant-table-header-column">
                                                <div><span class="ant-table-column-title">创建时间</span><span
                                                        class="ant-table-column-sorter"></span></div>
                                            </span></th>
                                        <th class="ant-table-fixed-columns-in-body ant-table-row-cell-last"><span
                                                class="ant-table-header-column">
                                                <div><span class="ant-table-column-title">操作</span><span
                                                        class="ant-table-column-sorter"></span></div>
                                            </span></th>
                                    </tr>
                                </thead>
                                <tbody class="ant-table-tbody">
                                    <tr class="ant-table-row ant-table-row-level-0" data-row-key="3606420756868730667">
                                        <td class="ant-table-row-cell-break-word"><span
                                                style="word-break: break-all;">3606420756868730667</span></td>
                                        <td class="">
                                            <div>疫苗诉求</div>
                                        </td>
                                        <td class="ant-table-row-cell-break-word">其他</td>
                                        <td class="ant-table-row-cell-break-word"></td>
                                        <td class="">-</td>
                                        <td class="ant-table-row-cell-break-word"></td>
                                        <td class="ant-table-row-cell-break-word">-</td>
                                        <td class="ant-table-row-cell-break-word">-</td>
                                        <td class=""><a target="blank"
                                                href="/manage/order/3560648903844049985/detail?orderSplitId=3560648903843982960">E3560648903843982960</a>
                                        </td>
                                        <td class="">
                                            <div><img
                                                    src="https://img1.dxycdn.com/2022/0417/337/4364052029929963453-68.png"
                                                    alt="商品logo"
                                                    style="width: 50px; height: 50px; margin-right: 5px;"><span
                                                    class="ant-tag ant-tag-has-color"
                                                    style="background-color: rgb(250, 173, 20); border-radius: 0px; width: 60px; text-align: center;">到店服务</span><span>HPV
                                                    4 价进口三针套餐（接种时间以工作人员联系为准）</span></div>
                                        </td>
                                        <td class=""><span><span
                                                    class="Service__tagSpan--ZxUCA">青岛创忆美健康管理有限公司</span></span></td>
                                        <td class="">-</td>
                                        <td class="">-</td>
                                        <td class="ant-table-row-cell-break-word">李佳澄</td>
                                        <td class="">疫苗组</td>
                                        <td class="">2023-03-21 11:48</td>
                                        <td class="ant-table-fixed-columns-in-body"><span class="textClick">编辑</span>
                                            <div class="ant-divider ant-divider-vertical" role="separator"></div><span
                                                class="textClick">领取</span><br><span class="textClick">查看详情</span>
                                            <div class="ant-divider ant-divider-vertical" role="separator"></div><span
                                                class="textClick">工单备注</span>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="ant-table-fixed-right">
                        <div class="ant-table-body-outer">
                            <div class="ant-table-body-inner">
                                <table class="ant-table-fixed">
                                    <colgroup>
                                        <col>
                                    </colgroup>
                                    <thead class="ant-table-thead">
                                        <tr style="height: 54px;">
                                            <th class="ant-table-row-cell-last"><span class="ant-table-header-column">
                                                    <div><span class="ant-table-column-title">操作</span><span
                                                            class="ant-table-column-sorter"></span></div>
                                                </span></th>
                                        </tr>
                                    </thead>
                                    <tbody class="ant-table-tbody">
                                        <tr class="ant-table-row ant-table-row-level-0"
                                            data-row-key="3606420756868730667" style="height: 83px;">
                                            <td class=""><span class="textClick">编辑</span>
                                                <div class="ant-divider ant-divider-vertical" role="separator"></div>
                                                <span class="textClick">领取</span><br><span class="textClick">查看详情</span>
                                                <div class="ant-divider ant-divider-vertical" role="separator"></div>
                                                <span class="textClick">工单备注</span>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

**Comment by gdh1995** [comment]
看起来这些按钮都是 `<span class="textClick">`，明显是你司前端自己写的。

```
map f LinkHints.activate clickable=".textClick"
```

应该能用。还是参考 https://github.com/gdh1995/vimium-c/wiki/Add-or-remove-hints

**Comment by zhiquanchi** [comment]
我明白了，我试下自定义clickable
