### ISSUE TITLE
feature request: 在切换标签页后自动将焦点移出文本编辑框，返回normal模式

### ISSUE THREAD

**Issue by Generalost** [gdh1995/vimium-c#872]
**What command or commands**

添加设置项，开启后可以切换标签页后自动将焦点移出文本编辑框

**How should a feature do**

When a user has done such steps:

1. 进入文本编辑框
2. 使用ctrl tab或鼠标切换标签页
3. 再次返回该页面

常常发生于使用了搜索框并在新标签页打开结果时，此时再返回原先搜索框所在的页面会处于insert模式而不是normal模式

then Vimium C should do:

切换页面时焦点移出文本框，返回normal模式；或切换到任何页面时都默认normal模式

**Browser and OS**

- Browser name: Chrome/Edge
- OS name: any

**补充**

是否可以通过给切换标签页的快捷键绑定一个脚本来解决呢？例如gt或gT时后面自动加一个Escape？

**Comment by gdh1995** [comment]
可以默认带escape，但有副作用，就是如果没在文本框里，会走escape的默认行为——如果选择了文字，就移除选区；否则会尝试聚焦到外层frame。写法是：
```
run c previousTab+dispatchEvent#esc
run v nextTab+dispatchEvent#esc
```

主要是切换页面后，要`dispatchEvent#esc`来触发 Vimium C 内部处理escape的动作

**Comment by gdh1995** [comment]
我下版本加一下参数吧

**Comment by gdh1995** [comment]
哦已经完美支持了：
```
run c previousTab+-dispatchEvent#esc
run v nextTab+-dispatchEvent#esc
```

区别是多了个“`-`”号，表示焦点不在文本框的话就不做别的

**Comment by gdh1995** [comment]
v1.99.99 已经正式发布，新版里支持新的写法：
```
map c previousTab blur
map v nextTab blur
```
