### ISSUE TITLE
[Feature request] want an explanation of the feature to show hidden link hints with the space key in the help dialog

### ISSUE THREAD

**Issue by UUGTech** [gdh1995/vimium-c#874]
Thank you for this great chrome extension!
Sorry for my poor English, but I have a small feature request.

I noticed that I can use the **space key** to show link hints that are hidden by other hints.
This is very **useful**!

However, I could not find it in the help by `?`.
Could you please add this feature to help for those who remain unaware of it?

**Comment by gdh1995** [comment]
Sorry but there're so many usage details other than `space`, and the help dialog is not suitable for this need. In fact, some wiki pages (table or commands-parameters-keys tree) should help, if only I have much more time to write them.

**Comment by UUGTech** [comment]
I see.
Thank you for your point. As you say, there is no end to the list of detailed functions.
Those who want to show link hints hidden by other hints can search this repository and will find this issue.😊
So, I will now close this issue.
