### ISSUE TITLE
Trigger moveTabToNextWindow on a newly opened window

### ISSUE THREAD

**Issue by firefoxfirefox** [gdh1995/vimium-c#876]
**Describe the bug**

Using moveTabToNextWindow only works when there are multiple tabs in the window. I have it mapped to W. Sometimes I have a windows with one tab and I want to merge it with other windows, so I expect moveTabToNextWindow to be able to do that. 

**To Reproduce**

Open any new window with a single tab and go to any website. Press the shortcut key for moveTabToNextWindow

**Browser, OS and Vimium C versions**

- Browser name: Firefox
- Browser version: 110.0.1 (64-bit)
- Vimium C version: 1.99.97
- OS name and version: Arch Linux

**Comment by gdh1995** [comment]
On my Firefox 110.0.1, Vimium C v1.99.97, and Windows 11, it (`moveTabToNextWindow`) works well.

Could you re-check you key mappings?
- Did you map `W` to `moveTabToNewWindow` (`new`)?
- Were you 2 windows in a same context? I mean, an incognito tab can only be moved in incognito windows, while a normal tab only in normal windows.

**Comment by gdh1995** [comment]
Um, or you may try this: click the single tab in a window, and then press `W` to try moving.

**Comment by firefoxfirefox** [comment]
Sorry for the incredibly late response. Yes, after trying, it seems I indeed do have to click somewhere in the window in order for the moveTabToNextWindow to work. Is there some way to focus the window from the keyboard, so I don't have to use the mouse?

**Comment by gdh1995** [comment]
There's no shortcut to do so directly. You may try press `Tab` key several times to move focus from your browser's address bar to links/buttons/inputs on webpage content.

**Comment by thenbe** [comment]
@firefoxfirefox On firefox, try pressing `F6` to toggle focus the address bar and webpage content.

On chromium, `F6` might take 2 presses. Instead use `shift` + `F6` to make to go in the opposite direction where it'll now require 1 click to reach the webpage content.

**Comment by ASong5** [comment]
> @firefoxfirefox On firefox, try pressing `F6` to toggle focus the address bar and webpage content.
> 
> On chromium, `F6` might take 2 presses. Instead use `shift` + `F6` to make to go in the opposite direction where it'll now require 1 click to reach the webpage content.

This works but it is a bit of a cumbersome workaround. I find myself often detaching tabs into new windows, but not being able to immediately use vimium shortcuts on the new detached tab without clicking the window with my mouse or pressing F6 and then esc (to unfocus address bar) is quite bothersome.
