### ISSUE TITLE
经常不能用

### ISSUE THREAD

**Issue by git708** [gdh1995/vimium-c#878]
chrome设置：启动时->继续浏览上次打开的网页

启动chrome后，发现vimium c无法使用，按键不生效。
ctrl+r刷新网页后，可以使用。
但是还是经常发生不能使用的，浏览别的网页再回来当前的网页会发生不能用的情况，有时候需要等待一会再按键，vimium c才能响应。

是不是我开的网页太多了，我有三四十个网页不关闭

- Browser name: chrome
- Browser version: 最新版 110.0.5481.178
- Vimium C version: 最新版
- OS name and version: win10

**Comment by git708** [comment]
是不是我开的网页太多了，我有三四十个网页不关闭

**Comment by gdh1995** [comment]
呃Chrome 106以前、Vimium C v1.99.0以前的话，基本上不会出现这个问题，除非是切换到的目标网页上键盘焦点在文本框里，这时候处于输入文字的状态，Vimium C 会自动禁用大部分快捷键；按 `Escape` 键可以移除焦点，就能用vimium c 快捷键了。

最近两三个小版本的话，加了一个自动释放旧页面资源的功能，似乎偶尔会有bug，导致在某个页面上始终不能用，但不至于“等一会才能用”。

最新版的 Chrome 似乎增强了页面冻结的功能，我还没详细测试过对 Vimium C 的影响，不敢说没问题。

你现在还会遇到吗？

**Comment by gdh1995** [comment]
please try this:
1. open `chrome://flags`
2. find the item whose name looks like "bfc cache"
3. disable the option
4. restart your chrome

**Comment by gdh1995** [comment]
update: the key flag is backward forward cache

**Comment by gdh1995** [comment]
Hello please try this version: [vimium_c-1.99.98-chrome-05b583a-mv2-mod.zip](https://github.com/gdh1995/vimium-c/files/11072627/vimium_c-1.99.98-chrome-05b583a-mv2-mod.zip) (usage: https://github.com/gdh1995/vimium-c/wiki/Test-a-zip-package)

**Comment by gdh1995** [comment]
[vimium_c-1.99.98-chrome-411c6e7-mv2-mod.zip](https://github.com/gdh1995/vimium-c/files/11081549/vimium_c-1.99.98-chrome-411c6e7-mv2-mod.zip)

**Comment by gdh1995** [comment]
测试发现 Chrome 110 之后开启了一些预先加载、休眠长期未使用的标签页的功能，影响了 Vimium C 的逻辑，已经尝试修复了。

v1.99.99 已经正式发布，麻烦试试。

**Comment by git708** [comment]
新版本没问题了，谢谢。
