### ISSUE TITLE
Visual模式在bing.com/new的chat页面无法使用

### ISSUE THREAD

**Issue by bushnerd** [gdh1995/vimium-c#879]
在new bing的chat页面，聊天记录的信息进入Visual模式后，再进入caret模式，无法移动光标，也无法正常复制。
**Describe the bug**

**To Reproduce**

**Browser, OS and Vimium C versions**

- Browser name: 
- Browser version: 
- Vimium C version: 
- OS name and version:

**Comment by gdh1995** [comment]
这玩意不好测试……且等等吧

**Comment by bushnerd** [comment]
测试了一下vimium，功能正常。

**Comment by gdh1995** [comment]
测出来了，是一个bug，谢谢反馈。

**Comment by gdh1995** [comment]
v1.99.99 已经正式发布了，麻烦试试。

**Comment by bushnerd** [comment]
还是不正常。
![动画](https://user-images.githubusercontent.com/28666253/233936586-daae69a3-05fb-4fd5-ab28-5a62dcacbfe5.gif)

**Comment by gdh1995** [comment]
Vimum C 最近更新了，麻烦重新测试一下。

**Comment by bushnerd** [comment]
非常感谢，刚才测试已经解决这个问题了。
