### ISSUE TITLE
On the options page in Chrome, I'm not seeing the option to use filtered hints instead of alphabet hints

### ISSUE THREAD

**Issue by alexTMGH** [gdh1995/vimium-c#880]
<img width="882" alt="Screenshot on 2023-03-07 at 23-33-34" src="https://user-images.githubusercontent.com/473767/223620672-132831bf-e84d-4291-bb1f-ccbd44a9703d.png">

**Comment by alexTMGH** [comment]
Is anyone else experiencing this?

**Comment by gdh1995** [comment]
Um you are using Vimium (https://github.com/philc/vimium) but not Vimium C (this repo), so you need to click a button named `Show Advanced Options` at the bottom of the Vimium Options page.

And then you can find the checkbox named `Use the link's name and characters for link-hint filtering`.

If you do want to use Vimium C, you may search for the name of `Use the link's name and characters for link-hint filtering` on its options page directly.

**Comment by alexTMGH** [comment]
> Um you are using Vimium (https://github.com/philc/vimium) but not Vimium C (this repo), so you need to click a button named `Show Advanced Options` at the bottom of the Vimium Options page.
> 
> And then you can find the checkbox named `Use the link's name and characters for link-hint filtering`.
> 
> If you do want to use Vimium C, you may search for the name of `Use the link's name and characters for link-hint filtering` on its options page directly.

Thanks, @gdh1995.  I'm not seeing this "Show Advanced Options" button on the Vimium options page.  (See the screenshot I originally shared for reference...you'll see that there's no such button.)

**Comment by gdh1995** [comment]
Um, the page should look like this snapshot:
![image](https://user-images.githubusercontent.com/5547703/226184271-5bdb76a6-2992-4667-b673-53dc9407152d.png)

I don't know why there was no the bottom bar on your browser...

**Comment by gdh1995** [comment]
Closed because this issue is "not so related" with Vimium C.
