### ISSUE TITLE
After updated to Chrome 111.0.5563.64, scrollPageDown can only trigger once in a hit.

### ISSUE THREAD

**Issue by YaQia** [gdh1995/vimium-c#882]
**Describe the bug**

ScrollPageDown can not be continuous currently. However, scrollPageUp can still be used.

**To Reproduce**

1. update your chrome
2. try to hit j once and hold it, then the screen will not be scrolled down.

**Browser, OS and Vimium C versions**

- Browser name: Chrome
- Browser version: 111.0.5563.64
- Vimium C version: 1.99.96
- OS name and version: Arch Linux, gnome desktop environment

**Comment by YaQia** [comment]
I've tested vimium, it is okay to use.

**Comment by gdh1995** [comment]
Not reproduced on Chrome `110.0.5481.178` on Win11. What's the URL of your test page?

**Comment by YaQia** [comment]
> Not reproduced on fresh profiles of Chrome `110.0.5481.178` and `111.0.5563.65` on Win11. What's the URL of your test page?

Well, in my case, every page has this problem.

One more information: 
![image](https://user-images.githubusercontent.com/61108050/224591228-0d8433db-42e1-43d6-b17f-01f571932032.png)

If I turn this off, scrollDown is continuous.

I guess probably I've messed up some configurations?

**Comment by YaQia** [comment]
Here is another possibility that cause this bug: I use wayland in Arch Linux. I was trying to render Chrome in wayland session, but the Chinese IME ibus was not working at all, so I switched chrome back to X11. After that operation, I found this unexpected behavior occured.

**Comment by gdh1995** [comment]
My Chrome on Ubuntu 20/22 works well. Still not sure why.

**Comment by YaQia** [comment]
Well, in my new laptop this problem disappears. I decided to close this issue as I can't reproduce it anymore.
