### ISSUE TITLE
【需求】按"T"时显示标签页索引，高亮（/突出）当前标签页。

### ISSUE THREAD

**Issue by dyguests** [gdh1995/vimium-c#884]
**What command or commands**

【需求】按"T"时显示标签页索引，高亮（/突出）当前标签页。

**How should a feature do**

【需求】按"T"时显示标签页索引，高亮（/突出）当前标签页。

2. 按T
3. 显示当前标签页

then Vimium C should do:

显示标签页索引，高亮（/突出）当前标签页

**Browser and OS**

- Browser name:  Chrome
- OS name:  Win11

**Comment by gdh1995** [comment]
已经有了，在标题右侧：
![image](https://user-images.githubusercontent.com/5547703/226183514-43fbc220-c618-40f4-b8c0-459ebe94529b.png)

* 没访问过的标签会用`**`包起来
* 每个窗口的当前标签页用 `(` / `)` 包起来
* 不在当前窗口的标签页会标记成`x:y`，冒号左边是窗口创建的顺序号
* 隐身标签会加 `*` 后缀
* 隐藏的标签，或者太久没用释放了资源的，会标记 `~`
* 播放声音的，标记 `♪` （静音）和 `♬` （没静音）

**Comment by gdh1995** [comment]
没有搜索词的时候，会把当前网页排到最后，所以一般不用管哪个是当前的，前几个都是别的网页。

**Comment by dyguests** [comment]
感谢~~！！

一直在找 chrome全屏后（笔记本屏幕太小了） 替代 标签栏/地址栏的方式。
这是目前最好的办法了。
