### ISSUE TITLE
调用浏览器翻译

### ISSUE THREAD

**Issue by OrangeCatSleepless** [gdh1995/vimium-c#886]
大佬，想问一下可以绑定快捷键调用 chrome 或者 edge 自带的翻译功能吗？每次都用鼠标点太麻烦了

**Comment by conrad000000** [comment]
Lol, I am in the same boat. I'm always having to translate from Chinese. I have two options, both are suboptimal but work. 
1. You can create a shortcut to open the "google translate" extension pop-up in chrome from [chrome://extensions/shortcuts](url) and use tab to select "translate page" - annoying to do but it works
2. You can use an app like "BetterTouchTool" on mac to select the option "translate" from the right click menu

I don't like either of these very much and translating is a pain and usually requires using the mouse. If you find something else that works, please let me know! :)

**Comment by gdh1995** [comment]
No Vimium C can not trigger the built-in translation feature of browsers like Edge, Chrome and Firefox - quite a few features are not exposed to web-extensions.

You may add other translation extensions and assign a shortcut to it, like saladict ([#247 (comment)](https://github.com/gdh1995/vimium-c/issues/247#issuecomment-749481669) )、edgetranslate (#383 ) 。



Duplicated as https://github.com/gdh1995/vimium-c/issues/337 .

**Comment by OrangeCatSleepless** [comment]
好的，我知道了。非常感谢大佬的帮助。
