### ISSUE TITLE
按下O 地址补全 以及 下一页无法找到

### ISSUE THREAD

**Issue by linjunji** [gdh1995/vimium-c#890]
感谢你的插件，让我终于可以好好用浏览器了，本来一直觉得 edge很难用 没有F2 F3翻页，终于解决了问题，而且还能用更多的不同的快捷键浏览网页，真的是超级方便。以下是几个问题还请大佬看看能不能解决

问题1
按下O 一般可以搜索网页，或者 根据打的地址在历史记录里面找到对应的但是他不会自动填充必须按TAB，不知道能否做一个自动填充的开关

问题2
能否有一个老板键。。。可以让浏览器 隐藏 或者 出现

问题3
翻页不能，特别遇到 只有 2页的情况， 翻到第二页，第一页就不能回去了，例如当遇到下面这个情况
这种箭头怎么办？
![image](https://user-images.githubusercontent.com/7846662/226153885-9c72dff3-473c-497e-a1af-7ae5981c7aeb.png)

**Comment by linjunji** [comment]
包括什么值得买 也不能翻页
![image](https://user-images.githubusercontent.com/7846662/226153922-19fdfdbc-b266-4f27-9d20-42ea4f2a1111.png)

**Comment by linjunji** [comment]
新的问题

比如我设置 a 是往下翻一页

就无法设置 aa 直接翻到底部，请问这个有办法解决吗

**Comment by gdh1995** [comment]
1. Vomnibar里省略tab
 -1. 可以去设置页面的“自定义快捷键”里加 `map o Vomnibar.activateInNewTab autoSelect`，其他 Vomnibar 命令也都支持 `autoSelect` 这个参数
2. 隐藏浏览器
- 1. 目前没有，可以搜搜别的工具
- 2. 下一版本会加上最小化/最大化窗口的命令，就可以从`chrome://extensions/shortcuts`上设置了：
![image](https://user-images.githubusercontent.com/5547703/226196794-51cc33b0-fe85-4f21-bdfd-59d38457390d.png)
3. 翻页
- 1. 这一般是因为网页设计的不完善，导致没自动识别到翻页按钮
- 2. 可以配置`“上一页”的关键词`和`“下一页”的关键词`，它支持`#`、`.`、`[`开头的CSS选择器，填对了选择器就可以识别到按钮了
- 3. 也可以直接配置网址的翻页规则（如果网址确实有规律可以的话），参考 https://github.com/gdh1995/vimium-c/discussions/885 ，往`文字自动替换`里增加 `n` 开头的规则，来把要变化的数字部分用 `(\d+)` 对应上，就能自动识别前后页了
4. `a` 和 `aa`
- 1. 本来就该这样拒绝设置`aa`。“让a和aa同时生效”这件事情不合逻辑

**Comment by linjunji** [comment]
谢谢

> 1. Vomnibar里省略tab
>    -1. 可以去设置页面的“自定义快捷键”里加 `map o Vomnibar.activateInNewTab autoSelect`，其他 Vomnibar 命令也都支持 `autoSelect` 这个参数
> 2. 隐藏浏览器
> 
> * 1. 目前没有，可以搜搜别的工具
> * 2. 下一版本会加上最小化/最大化窗口的命令，就可以从`chrome://extensions/shortcuts`上设置了：
>      ![image](https://user-images.githubusercontent.com/5547703/226196794-51cc33b0-fe85-4f21-bdfd-59d38457390d.png)
> 
> 3. 翻页
> 
> * 1. 这一般是因为网页设计的不完善，导致没自动识别到翻页按钮
> * 2. 可以配置`“上一页”的关键词`和`“下一页”的关键词`，它支持`#`、`.`、`[`开头的 CSS 选择器，填对了选择器就可以识别到按钮了
> * 3. 也可以直接配置网址的翻页规则（如果网址确实有规律可以的话），参考 [change part of url with key-binding? #885](https://github.com/gdh1995/vimium-c/discussions/885) ，往`文字自动替换`里增加 `n` 开头的规则，来把要变化的数字部分用 `(\d+)` 对应上，就能自动识别前后页了
> * 4. 什么值得买的网页上，按钮是他们自己瞎画的，没遵守网页开发的习俗，所以没认出来。可以加 CSS 选择器来让 Vimium C 识别它们
> 
> 4. `a` 和 `aa`
> 
> * 1. 本来就该这样拒绝设置`aa`。“让a和aa同时生效”这件事情不合逻辑

谢谢，下版本啥时候有啊。哈哈哈

**Comment by linjunji** [comment]
最新的版本1.99.96吗？

下个版本啥时候来啊

**Comment by gdh1995** [comment]
一个月吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月21日(周二) 晚上9:15
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.******@***.***&gt;;
主题: Re: [gdh1995/vimium-c] 按下O 地址补全 以及 下一页无法找到 (Issue #890)




 
最新的版本1.99.96吗？
 
下个版本啥时候来啊

**Comment by linjunji** [comment]
太感谢了
shortcut userCustomized1 command="toggleWindow" states=["maximized","minimized"]
实现了老板键，爱你


另外问下
-----------------------
# 默认在 普通 和 最大化 之间切换
map x1 toggleWindow
# 还原
map x2 toggleWindow states="normal"
# 最小化，要注意最小化的窗口不接收键盘消息，这时候大部分 vimium c 快捷键都不会被触发
map x3 toggleWindow states="minimized"
# 全屏或者最大化
map x4 toggleWindow states=["fullscreen","maximized"]
-------------------------


如果map两个按钮一起用，例如 ALT+~ 或者 CTRL+~ 来实现一个功能？

**Comment by linjunji** [comment]
![image](https://user-images.githubusercontent.com/7846662/233515850-7d7a5378-dd90-46b1-8e61-5f35cb22bf37.png)


自定义快捷键不能定义成

alt+~ 之类吗，必须要求子母或者数值

也不能定义成单独的 F2 F3之类的去切换标签？

**Comment by gdh1995** [comment]
不能。这个是浏览器的设置页面，这些限制都是chrome浏览器的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月21日(周五) 上午8:54
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.******@***.***&gt;;
主题: Re: [gdh1995/vimium-c] 按下O 地址补全 以及 下一页无法找到 (Issue #890)




 

 
自定义快捷键不能定义成
 
alt+~ 之类吗，必须要求子母或者数值
 
也不能定义成单独的 F2 F3之类的去切换标签？

**Comment by gdh1995** [comment]
如果不用浏览器全局快捷键，而是写 `map` 规则，可以更自由地组合快捷键，参考 https://github.com/gdh1995/vimium-c#custom-key-mappings
