### ISSUE TITLE
希望能够将数字键释放出来

### ISSUE THREAD

**Issue by xiaoxiang52** [gdh1995/vimium-c#892]
我有的插件需要使用数字键1-5
使用v-c后，按键无法被使用
请问如何设置能释放这几个键，谢谢

**Comment by gdh1995** [comment]
unmap 1
unmap 2
unmap 3
unmap 4
unmap 5


就行了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月20日(周一) 下午4:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [gdh1995/vimium-c] 希望能够将数字键释放出来 (Issue #892)




 
我有的插件需要使用数字键1-5
 使用v-c后，按键无法被使用
 请问如何设置能释放这几个键，谢谢

**Comment by xiaoxiang52** [comment]
![image](https://user-images.githubusercontent.com/127318734/226309001-0483ceca-303c-4b48-b2a0-0f4ba1282050.png)
感谢您及时耐心的回答，我请教最后一个问题，如果只想给红圈中的元素显示文字按钮（或者排除页面其他按钮）我应该如何设置

**Comment by xiaoxiang52** [comment]
该元素是readwise的highlight插件

**Comment by xiaoxiang52** [comment]
感谢您及时耐心的回答，我请教最后一个问题，如果只想给红圈中的元素显示文字按钮（或者排除页面其他按钮）我应该如何设置
该元素是readwise的highlight插件

**Comment by xiaoxiang52** [comment]
> 感谢，原来这么简单，我设置成了： map 1 1 unmap <1>

感谢您及时耐心的回答，我请教最后一个问题，如果只想给红圈中的元素显示文字按钮（或者排除页面其他按钮）我应该如何设置
该元素是readwise的highlight插件

**Comment by gdh1995** [comment]
参考 https://github.com/gdh1995/vimium-c/wiki/Add-or-remove-hints#zh 配置 match 就行了，不过这只能固定映射到特定键，不能根据页面状态自动切换“全都能选”和“只match这几个”

**Comment by xiaoxiang52** [comment]
map f LinkHints.activate match=".button"
目前这样写是无效的
![image](https://user-images.githubusercontent.com/127318734/226391097-aaeb7ebf-dc47-4710-8d45-ae11e2f7911e.png)
