### ISSUE TITLE
Global marks to open in same tab please. 

### ISSUE THREAD

**Issue by mhertz** [gdh1995/vimium-c#894]
As title, it would be much appreciated if such could be optionally implemented thanks, just like qutebrowser, cvim, pentadactyl/vimperator etc.

Edit: Meanwhile you can workaround this through:

map 'a openUrl url="https://www.foo.bar" reuse=0

Would be nice if 'Marks.activate' supported 'reuse=0' also. Thanks in advance.

**Comment by gdh1995** [comment]
If you mean to only open when a marked tab is not existing, then I'll add this feature in a next version.

**Comment by mhertz** [comment]
First really appreciate your reply!

Sorry if unclear, and I just meant possibility of opening global marks in same tab, not possible now - most other vim-style browsers/plugins support this, as gloal marks is a bookmark alternative and you neither want bookmarks to always open in new tabs.

Thanks for considering.

**Comment by gdh1995** [comment]
a global mark will remember ID of its source tab, so when the tab still exists, jump to it firstly.


Do you mean to always ignore the source tab and open in a current tab? Or just open in current when the source tab has been removed?



---Original---
From: "Martin ***@***.***&gt;
Date: Thu, Mar 23, 2023 05:53 AM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] Global marks to open in same tab please. (Issue #894)




 
First really appreciate your reply!
 
Sorry if unclear, and I just meant possibility of opening global marks in same tab, not possible now - most other vim-style browsers/plugins support this, as gloal marks is a bookmark alternative and you neither want bookmarks to always open in new tabs.
 
Thanks for considering.

**Comment by mhertz** [comment]
I'm sorry, the latter(open in current when the source tab has been removed). So I can do same with global marks as can with bookmarks and regular urls I.e open in new or current tab - retaining source ID or not isn't important for me honestly, but makes sense jumping to it if available I guess. 

Don't know if you feel otherwise, but just noticed this was missing here, compared to many alternatives.

Thanks for thinking about it atleast.

**Comment by mhertz** [comment]
Just wanted to say I'm very grateful and thank you so much!
