### ISSUE TITLE
Do not store recent sessions in Firefox

### ISSUE THREAD

**Issue by MahdiNazemi** [gdh1995/vimium-c#900]
**What command or commands**

Vomnibar

**What should a feature do**

Prevent Vimium C from storing recently-closed sessions when a user uses the ["Temporary Containers" add-on](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/) with the "Deletes History Temporary Containers" feature.

I suspect Vimium C cannot easily access the Temporary Containers' settings, so it would be great to add an option in Vimium C's settings to manually disable the storage of recently-closed sessions.

**Browser and OS**

- Browser name: Firefox 111.0
- OS name: macOS Ventura 13.2.1

**Comment by gdh1995** [comment]
the session is not long-term saved inside Vimium C, while it's only saved in Firefox itself.


If what you said is exactly what the other extension does, then it should be responsible to remove unwanted closed sessions, by calling Firefox's API forgetClosedTab ( https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sessions/forgetClosedTab ).



---Original---
From: "Mahdi ***@***.***&gt;
Date: Thu, Mar 23, 2023 07:07 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] Do not store recent sessions in Firefox (Issue#900)




 
What command or commands
 
Vomnibar
 
What should a feature do
 
Prevent Vimium C from storing recently-closed sessions when a user uses the "Temporary Containers" add-on with the "Deletes History Temporary Containers" feature.
 
I suspect Vimium C cannot easily access the Temporary Containers' settings, so it would be great to add an option in Vimium C's settings to manually disable the storage of recently-closed sessions.
 
Browser and OS
  
Browser name: Firefox 111.0
 
OS name: macOS Ventura 13.2.1

**Comment by MahdiNazemi** [comment]
Thank you. I will file an issue in the other add-on's GitHub repository then.
