### ISSUE TITLE
[Feature Request] Remove the pop-up opened by `LinkHints.activateHover` on `scrollDown` and `scrollUp`

### ISSUE THREAD

**Issue by MahdiNazemi** [gdh1995/vimium-c#901]
**What should a feature do**

Remove a pop-up opened by `LinkHints.activateHover` when scrolling down or up.

I found a `keepHover` option and defined the following mappings, but none of them worked.

```
map j scrollDown keepHover="never"
map k scrollUp keepHover="never"
```

```
map j scrollDown keepHover=false
map k scrollUp keepHover=false
```

Example page:
https://en.wikipedia.org/wiki/Logistic_regression

**Browser and OS**

- Browser name: Firefox 111.0.1
- OS name: macOS Ventura 13.2.1

**Comment by gdh1995** [comment]
Um, usually a next `<esc>` can remove pop-up cards which only show on hover.

`keepHover` of `scroll*` is only to avoid further hover effects during scrolling smoothly.

**Comment by gdh1995** [comment]
I think it's a too rare case to use scrolling actions to remove pop-ups - you know, too frequent scrolling may even hurt my eyes.

If you really want to do so, you map trigger `LinkHints.unhoverLast` before `scroll*`, like:
```
map <v-unhover> LinkHints.unhoverLast
run j unhover+scrollDown
run k unhover+scrollUp
# also map others
```

**Comment by MahdiNazemi** [comment]
<esc> was not closing the pop-up on my other machine so I opened this issue. However, it seems to work just fine on my current machine and on the same Wikipedia page.

It's good to know there is another way to close the pop-up with the `unhover` option.

Thank you!

**Comment by gdh1995** [comment]
BTW, the `unhover` in my last key mapping is not a parameter, but a short name of the mapped key `<v-unhover>`, so its real triggered command is `LinkHints.unhoverLast`.
