### ISSUE TITLE
有些元素不能点击

### ISSUE THREAD

**Issue by Higurashi-kagome** [gdh1995/vimium-c#902]
**Describe the bug**

按 F 开启链接跳转，尝试点击有的元素无效。

**To Reproduce**

1. 进入微信读书阅读页比如[42032500722f75104206cf7](https://weread.qq.com/web/reader/42032500722f75104206cf7?)
2. 按 F
3. 按对应按键尝试点击主题切换按钮
   <details>
	<summary>Details</summary>
	
	![image](https://user-images.githubusercontent.com/51501079/227755571-adc98d0d-eef8-40b7-a9d8-911f48e1b240.png)
	
	</details>

**Browser, OS and Vimium C versions**

- Browser name: Chrome
- Browser version: 111.0.5563.111
- Vimium C version: 1.99.96
- OS name and version: Win11

**Comment by gdh1995** [comment]
这个网页对一些按钮禁止用脚本模拟点，也就禁止掉了浏览器的扩展程序，没法绕

**Comment by Higurashi-kagome** [comment]
哦，好
