### ISSUE TITLE
请问RUN 和 MAP 什么区别？

### ISSUE THREAD

**Issue by linjunji** [gdh1995/vimium-c#903]
run c previousTab+dispatchEvent#esc
run v nextTab+dispatchEvent#esc
是不是 每次 按C或者V切换的时候不会把 焦点弄到 地址栏 ，因为这样会导致切换失效

map c 或者 v previousTab 后面不能加+-dispatchEvent#esc

但是run 和 map 看起来执行的结果都一样，这个之间是什么区别呢

**Comment by gdh1995** [comment]
`run xxx yyy` 是 `map xxx runKey keys=["yyy"]` 的缩写，见 https://github.com/gdh1995/vimium-c/wiki/Auto-run-a-tree-of-commands#short-syntax ，所以执行的东西一样。

焦点到浏览器地址栏（即网页之外）后，vimium c 就做不了什么了，只有全局快捷键能用，见 https://github.com/gdh1995/vimium-c/wiki/Trigger-commands-in-an-input-box#global-shortcuts 。
