### ISSUE TITLE
How to search selected text in custom engine and at the same time copying the selected text to clipboard

### ISSUE THREAD

**Issue by cesm1980** [gdh1995/vimium-c#904]
I would like to know, by using a single mapped key without entering visual modes, how do i copy the currently selected text (which i selected previously using LinkHints.activateSelect) to the clipboard AND right after that searches the string using one of my custom search engines.

I already spent hours trying douzens of different combinations with tree commands but the best i am able to achieve is getting the URL of the searched string on the search engine but i dont want that, i want the actual selected text to the clipboard, but apparently none of the other commands to copy the selected text to clipboard works alongside autoOpen when i try using in list nodes.

update : so far for the moment i discovered a temporary solution, which is putting my custom search engine as the main one, and that way it works when i press the key i map it to, like this :

run z autoOpen copy selected

Apparently it's the "keyword" setting to choose a custom engine that is making the url of the search being copied to the clipboard instead of the selected text, like this :
run z autoOpen copy selected keyword="ygmpl"

So far this workaround have to do, there isn't a alternative to this? Like for example some kind of boolean option to toggle which is copied to the clipboard? I find a bit strange that it's not possible to choose which info gets copied to the clipboard and that it's just possible to copy the url of the search itself when using a custom engine with the keyword option, unless there's other way to choose a custom engine that i am not aware of, until then, this workaround will have to do.

**Comment by gdh1995** [comment]
Sorry it looks like a bug that the `keyword` are used in so many places. I'll fix it in a next version.

**Comment by gdh1995** [comment]
Hello, with v1.99.99, when you use rules like `map xxx autoOpen selected copy keyword="bing"`, it won't copy converted query URL any more, but just copy original selected text as expected.
