### ISSUE TITLE
How to expand selection by word? (similar to how the first word is selected with LinkHints.activateSelect)

### ISSUE THREAD

**Issue by cesm1980** [gdh1995/vimium-c#905]
I am a heavy user of LinkHints.activateSelect, but unfortunately i notice that sometimes webpages do have more than 1 text element in the same line of text (for example, three separate sentences, 1 separate text element each) and sometimes i do need to select the entirety of only one of the elements, not the full line of text, so shift+end isnt a solution here unfortunately because it ignores text elements on that line, neither is the vim keys J, L, etc and visual line mode also has the same problem, it's also ignoring the text elements and selecting the full line.

But i notice that vimium c automatically is able to preselect the first word in the text element i choose, which is great, so it would be great if we should increase the selection by each words (or space, actually if it was possible to we choose a custom delimeter it would be great but if it's too much work to code, just spaces would be enough to me) instead of having to manually select the rest of the text with shift+right.

Is this doable with current commands or it's something that would take too much work to implement?

**Comment by cesm1980** [comment]
Solved : just in case someone has the same doubt, i discovered that there's native keys for this on the browser for example ctrl+shift+right arrow does exactly what i want, didnt even know about such keys...

**Comment by gdh1995** [comment]
`VisualMode` supports `w`, `e` and `b` to modify selection by words.
