### ISSUE TITLE
/ 和 新的 github 搜索引擎冲突

### ISSUE THREAD

**Issue by tjx666** [gdh1995/vimium-c#906]
url: https://github.com/search?q=changelog&type=repositories

你需要开启 github 的这个预览特性：

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/228369092-38e08b64-b418-4196-87f4-272553d17b7c.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/228368894-259e3395-1a85-4a1e-978f-7714d9b8c5dc.png">

**Comment by gdh1995** [comment]
快捷键都是可以自己改的，参考 https://github.com/gdh1995/vimium-c#keyboard-bindings 的用法；或者可以在特定网站禁用部分快捷键，参考 https://github.com/philc/vimium/wiki/Disabling-Vimium#partially-disable-vimium-on-a-site

**Comment by tjx666** [comment]
thanks
