### ISSUE TITLE
`<esc>` does not remove link hints when `permissions.default.shortcuts` is enabled

### ISSUE THREAD

**Issue by MahdiNazemi** [gdh1995/vimium-c#907]
**Describe the bug**

Firefox has the option to prevent a website (like slack.com) from overriding browser shortcuts. This can be achieved by setting Tools -> Page Info -> Permissions -> Override keyboard shortcuts to Block for individual websites or globally by setting `permissions.default.shortcuts` to 2.

After setting this option, I can no longer use the <kbd>ESC</kbd> key to remove link hints.

**To Reproduce**

1. Go to slack.com
2. Go to Tools -> Page Info -> Permissions, uncheck Use Default below Override keyboard shortcuts and set to Block
3. Press <kbd>f</kbd> to show link hints
4. Press <kbd>ESC</kbd>

- Browser name: Firefox
- Browser version: 111.0.1
- Vimium C version: 1.99.97
- OS name and version: macOS Ventura 13.2.1

**Comment by MahdiNazemi** [comment]
This could be a Firefox bug; <kbd>BACKSPACE</kbd> and <kbd>DELETE</Kbd> used to have [similar issues](https://bugzilla.mozilla.org/show_bug.cgi?id=1604970), but I am not sure how <kbd>ESC</kbd> is treated.

**Comment by gdh1995** [comment]
This is not a bug but a feature of `permissions.default.shortcuts` in Firefox. Firefox has a list of keys to hide in this mode and then extensions can not see them.

It seems Vimium C's `Ctrl+[` still works even when this is enabled.
