### ISSUE TITLE
How do I change the hint characters?

### ISSUE THREAD

**Issue by Hund** [gdh1995/vimium-c#908]
I'm used to using `asdfhjkl` with qutebrowser (my own setting), but I can't figure out how to change the hint characters with Vimium? How do I change them? It doesn't seem to be documented.

**Comment by gdh1995** [comment]
It's `Characters used for link hints` on Vimium C Options:
![image](https://user-images.githubusercontent.com/5547703/229576354-41bdb084-d3cf-47bd-a2aa-27ce63ab80f2.png)

**Comment by Hund** [comment]
I don't have that option with Firefox. :/

**Comment by Hund** [comment]
How could I have missed this? This is awkward. Thank you! :)
