### ISSUE TITLE
select frame not working correctly in twitter

### ISSUE THREAD

**Issue by Monirzadeh** [gdh1995/vimium-c#91]
hi
i usually zoom in twiitter until i had only two column 
1.timeline 
2. icon-bar( home,bell icon , etc..)
if you hint in one of this icons frame selected change to icon-bar frame and you can't change it to timeline frame with "mainFrame" or "nextFrame".so every time you should scroll icon-bar than timeline.
the only way that you can focus into timeline is click somewhere with mouse.
UPDATE: i test that in Firefox and Brave on Linux

**Comment by gdh1995** [comment]
`LinkHints.activateModeToHover` is enough.

I use this: `map Ff LinkHints.activateModeToHover`, so that I use `Ff` to make Vimium C "hover and remember" what hint I select in the mode, and after this step, `j` / `k` will scroll the main area.

`nextFrame` is not suitable in this case, just because there's no `<iframe>` DOM element in the pages.

**Comment by Monirzadeh** [comment]
it is work but when i open a terminal beside my browser reset this `LinkHints.activateModeToHover`
and problem happen again - every time i comeback to browser window i should `Ff` again .
if you need more information for debugging, tell me what do you need to know?

**Comment by gdh1995** [comment]
When you switch to another window and then go back to a browser window, what's the effect of a `j` / `k`, if you do not `Ff` again?

**Comment by gdh1995** [comment]
OKay I think I've found some key points. Here's what Vimium C knows:

1. A button (let's say it's "Button A") at the left sidebar is clicked by LinkHints
- 1. Vimium C knows that an area including the button is "active", and Scroller will use it
- 2. the button gets focused
2. `Ff` tell Vimium C's Scroller that an element (named "Element B") in the main part is "active"
- 1. now `j` scrolls the main part
4. You switch to another window and then switch back
- 1. The "Button A" gets focused again
- 2. Vimium C learns "Button A" becomes "active" from the "focus" event
5. Now `j` scrolls A again

Maybe I need to find a better strategy to find and setup "active" targets.

**Comment by gdh1995** [comment]
Vimium C v1.79.3 has been released, so has this been solved?

**Comment by Monirzadeh** [comment]
hi it's not update on chrome web store(i report that on brave that time)
but i test that on Firefox and this problem solve there.
if you update chrome version i can test that with brave too.

**Comment by gdh1995** [comment]
Oh, I forgot that the version on Chrome Web Store is still waiting for reviews. Just in 3~5 days.

**Comment by Monirzadeh** [comment]
> Oh, I forgot that the version on Chrome Web Store is still waiting for reviews. Just in 3~5 days.

OK :smile: 
i will test that when update and report here
for now it is work on Firefox like a charm :+1: 
it can be good to connect your commit to issue for better history (some one like me can find your solution for any bug and learn from that)

**Comment by gdh1995** [comment]
Thanks. It's commit 3ec641dd716cd9fc2b0681fa7b50d9768d706bdc .

**Comment by gdh1995** [comment]
Hello, Vimium C v1.79.3 has been available on Chrome Web Store, Firefox Add-ons and Microsoft Edge Addons.

**Comment by Monirzadeh** [comment]
> Hello, Vimium C v1.79.3 has been available on Chrome Web Store, Firefox Add-ons and Microsoft Edge Addons.

hi
i test that on brave and problem solve
thank you for fix the bug
