### ISSUE TITLE
[Bug] Link hints not shown for `next` and `prev` elements on Hacker News

### ISSUE THREAD

**Issue by MahdiNazemi** [gdh1995/vimium-c#911]
**Describe the bug**

Link hints are not shown for some elements on the page, including `next` and `previous`.

**To Reproduce**

1. Go to https://news.ycombinator.com/item?id=34650987
2. Press `f`

<img width="1440" alt="Screenshot 2023-04-02 at 8 46 43 PM" src="https://user-images.githubusercontent.com/11276349/229406949-892265ff-2e3a-4271-97cb-6dcc601491af.png">

**Browser, OS and Vimium C versions**

- Browser name: Firefox
- Browser version: 111.0.1
- Vimium C version: 1.99.97
- OS name and version: macOS Ventura 13.3

**Comment by MahdiNazemi** [comment]
I was able to resolve the issue by defining the following mapping:
`map f LinkHints.activate clickableOnHost="\\bycombinator##.clicky;"`

Detailed instructions can be found in the Wiki:
https://github.com/gdh1995/vimium-c/wiki/Add-or-remove-hints

Leaving the issued open in case this is something that needs to be fixed in the main branch.

**Comment by gdh1995** [comment]
It's because the page gives those links a special mark of `aria-hidden="true"`, so Vimium C ignores them unless they also match `clickable`.
