### ISSUE TITLE
请问打开Vomnibar之后，无法用鼠标单击空白处退出，必须使用键盘ESC才能退出吗？

### ISSUE THREAD

**Issue by Langeeker** [gdh1995/vimium-c#912]
有时误操作打开 Vomnibar，想及时退出，但是鼠标单击空白处搜索框呈半透明状态，无法直接退出，除非单击 bar 右侧的关闭按钮或者ESC。

刚使用 Vimium C 不久，之前使用 Vimium 的时候，鼠标单击空白处就直接退出 Vomnibar 的搜索框了。请问有什么办法，可以直接使用鼠标单击空白处，退出 Vomnibar 搜索框，而不是半透明状态吗？谢谢开发者。

- Browser name: chrome
- OS name: macos 13.0

**Comment by gdh1995** [comment]
可以点击输入框最右边的叉号：
![image](https://user-images.githubusercontent.com/5547703/229861949-d38986b9-9ce2-46c1-b8db-41091066670f.png)

或者修改“自定义快捷键”，给触发的 vomnibar 指定参数：
```
map o Vomnibar.activate exitOnClick
```

**Comment by gdh1995** [comment]
另外一般 `Ctrl+[` 和 `ESC` 都能用来退出 vimium c 的大多数命令。

**Comment by Langeeker** [comment]
> 可以点击输入框最右边的叉号： ![image](https://user-images.githubusercontent.com/5547703/229861949-d38986b9-9ce2-46c1-b8db-41091066670f.png)
> 
> 或者修改“自定义快捷键”，给触发的 vomnibar 指定参数：
> 
> ```
> map o Vomnibar.activate exitOnClick
> ```
加上这个参数 exitOnClick 就可以了，感谢！
