### ISSUE TITLE
"LinkHints.activateSelect caret" and "key h" 

### ISSUE THREAD

**Issue by bommbo** [gdh1995/vimium-c#917]
**Describe the bug**
使用 LinkHints.activateSelect caret 后， 按键 h 失效，只能使用 jkl三个键

**To Reproduce**

**Browser, OS and Vimium C versions**

- Browser name: Chromium 
- Browser version: 112.0.5615.49 Arch Linux
- Vimium C version: 1.99.98
- OS name and version: manjaro linux gnome 43.4

**Comment by gdh1995** [comment]
请说细一点，是在 LinkHints 模式下不能用，还是 LinkHints结束后自动进入的 VisualMode 里不能用，又或者都退出后的普通模式下还不能用？

**Comment by bommbo** [comment]
应该是叫作linkhins结束后的visualmode里不能使用，退出后的普通模式没问题。

**Comment by gdh1995** [comment]
直接用 enterVisualMode 进的 visualmode 的呢？



---Original---
From: ***@***.***&gt;
Date: Thu, Apr 13, 2023 07:29 AM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] "LinkHints.activateSelect caret" and "key h" (Issue #917)




 
应该是叫作linkhins结束后的visualmode里不能使用，退出后的普通模式没问题。

**Comment by bommbo** [comment]
没问题，只影响到了LinkHints.activateSelect caret，firefox的 1.99.97 版本也没问题。

**Comment by Fuann-Kinoko** [comment]
Guess there might be a bug with `VisualAction.dec`, since pressing b in caret mode doesn't seem to work either.

**Comment by bommbo** [comment]
yeah,It'fixed now. thx!!!
