### ISSUE TITLE
[BUG问题反馈]vimiumc按v(或V)进入文字选择模式,然后切换到光标模式下,按h不能往左移,l向右、j向下、k向上是正常的

### ISSUE THREAD

**Issue by WrathGluttony** [gdh1995/vimium-c#919]
**Describe the bug**

vimiumc按v(或V)进入文字选择模式,然后切换到光标模式下,按h不能往左移,l向右、j向下、k向上是正常的

**To Reproduce**

在谷歌浏览器和360极速浏览器X(看好,有个X,不是360极速浏览器)下随机打开1个网页,都会出现这个问题
(注:360极速浏览器X是64位系统,而360极速浏览器是32位系统)

**Browser, OS and Vimium C versions**

- Browser name: 谷歌浏览器
- Browser version: 112.0.5615.86（正式版本） （64 位）
- Vimium C version: 1.99.98
- OS name and version: Win10 Pro 版本22H2(操作系统内部版本19045.2788)

- Browser name: 360极速浏览器X(看好,有个X,不是360极速浏览器)
- (注:360极速浏览器X是64位系统,而360极速浏览器是32位系统)
- Browser version: 版本号：21.0.1200.0(内核版本：95.0.4638.69)
- Vimium C version: 1.99.98
- OS name and version: Win10 Pro 版本22H2(操作系统内部版本19045.2788)

**Comment by gdh1995** [comment]
Yes it's a bug. Duplicate of #917 .
