### ISSUE TITLE
Reserve Specific Link Hints for Specific Selectors

### ISSUE THREAD

**Issue by christianmagill** [gdh1995/vimium-c#920]
**What command or commands**

LinkHints

**How should a feature do**

I'm wondering if it would be possible to reserve specific hints for specific selectors. For applications that don't have shortcuts, this could be useful to maintain the same hints.

**Comment by gdh1995** [comment]
There's an option named `Use the link's name and characters for link-hint filtering` on Vimium C Options page. You may take a try, though I'm afraid it might not work as you expect.

There's no plan to add the "reserving hint names" feature in recent months and years.
