### ISSUE TITLE
[Feature Request] An alternative to `LinkHints.activateWithQueue` that does not open selections in new tabs

### ISSUE THREAD

**Issue by MahdiNazemi** [gdh1995/vimium-c#921]
**What command or commands**

`LinkHints.activateWithQueue`

**What should a feature do?**

Keep generating link hints similar to `LinkHints.activateWithQueue` (without opening the selected item in a new tab) so the user can interact with a website that opens a modal or has hoverable items (without having to press <kbd>f</kbd> repeatedly).

Example:
1. Go to a workspace on https://slack.com
2. `LinkHints.activateHover` on a person's name in a conversation
3. `LinkHints.activate` to select reactions (e.g., emojis)
4. Press <kbd>Esc</kbd> to defocus the search box
5. `LinkHints.activate` to select an emoji

Steps 2. to 5. (and possibly 1. to 5.) can be combined when the requested feature is implemented.

**Comment by gdh1995** [comment]
You may press `Ctrl`, `Shift` and `Alt` Keys to switch working mode of LinkHints, and when the HUD at the bottom right corner shows `Open multiple links in current tab` (usually a single `Shift` after `Alt+F`), it will click buttons and links without the signal of "opening a link in a new tab"

**Comment by MahdiNazemi** [comment]
Thank you! Is it possible to use a `$then` block or something else to map <kbd>Alt</kbd><kbd>f</kbd> followed by <kbd>Shift</kbd> to a single shortcut?

**Comment by gdh1995** [comment]
Not suggested although it's does possible...

Here's a much simpler way if you prefer opening in current tab:
```
map <a-f> LinkHints.activateWithQueue mode="cur-queue"
```

**Comment by parogen** [comment]
Is there a mode string I can use for the Ctrl option?
