### ISSUE TITLE
KodeKloud not working with <esc> function

### ISSUE THREAD

**Issue by wolfdate25** [gdh1995/vimium-c#925]
**Describe the bug**

The KodeKloud is a website that emulate the terminal. Students can practice in the website.
When I entered the vim mode in website's emulator, the \<esc\> function dosen't work, so I interrupted the enter mode and no way to escape.
I do exclude the website through vitaminc option. but it seems not working.

**To Reproduce**

1. Go https://kodekloud.com/topic/readiness-probes-2/
2. Focus the web terminal emulator
3. type 'vim' and enter the input mode
4. now \<esc\> key doesn't work. I'm stucked.

![image](https://user-images.githubusercontent.com/4906999/232349395-1da57465-f1dd-47d9-a0e5-868a6738e9d9.png)

**Browser, OS and Vimium C versions**

- Browser name: edge
- Browser version: 112
- Vimium C version: 1.99.96
- OS name and version: windows10

**Comment by gdh1995** [comment]
How did you "exclude the website"? I wonder what's the exclusion configuration on Vimium C Options page when you tested it.

If all related functions work as expected, you may add an exclusion rule like this to ensure Vimium C ignore `Escape` keys on the page:

![image](https://user-images.githubusercontent.com/5547703/233146364-3feeaf7e-93a0-4f7d-8d83-dfab9794c95f.png)

**Comment by wolfdate25** [comment]
@gdh1995 I tried to wildcard the URL, but I'm having trouble.
The original URL looks like this
:https://terminal-a856d8aa800c4e1b.labs.kodekloud.com/
If I enter the URL :https://kodekloud.com/ into the filter, it doesn't work, but if I enter the URL explicitly, the exception handling works.
Is there a solution?

**Comment by gdh1995** [comment]
The domain means the page uses a method named "iframe", so the URL on your browser's address bar was not what Vimium C saw when you pressed `Escape`. And, in this case you should use an iframe's URL as exclusion pattern.

If you want a exclusion rule to match all pages of similar domains, then the prefix `:` character is not suitable in your case - please try "RegExp" patterns in exclusion rules:
```
^https://[^.]+\.labs\.kodekloud\.com/
```

![image](https://user-images.githubusercontent.com/5547703/233446407-9eb73711-7ded-4f90-beff-eb66dc579167.png)

**Comment by wolfdate25** [comment]
@gdh1995 Thanks to you, we were able to solve it.
