### ISSUE TITLE
[Bug] Continuous scrolling breaks after pinching to zoom on the page

### ISSUE THREAD

**Issue by MahdiNazemi** [gdh1995/vimium-c#927]
**Describe the bug**

Continuous scrolling stops working after pinching to zoom on a page. The user has to press <kbd>j</kbd>/<kbd>k</kbd> keys multiple times to move down/up a few pixels. After a few key presses, the scrolling issue disappears.

https://user-images.githubusercontent.com/11276349/232400149-d0caeac0-384f-4916-95e2-001f7ea7bd4d.mov

**Update 1**
Scrolling sometimes stops working altogether, i.e., pressing <kbd>j</kbd>/<kbd>k</kbd> keys does not do anything.

**Browser, OS and Vimium C versions**

- Browser name: Firefox
- Browser version: 112.0
- Vimium C version: 1.99.99
- OS name and version: macOS Ventura (13.3.1)

**Comment by gdh1995** [comment]
Does it also happen on Chrome v110 or later on macOS 13 ?

**Comment by gdh1995** [comment]
Browsers haven't provided any API to allow extensions to scroll to the end of a zoomed viewport. So it's not a bug of Vimium C.


As for firefox, I'll do some tests when I am in rest.



---Original---
From: "Mahdi ***@***.***&gt;
Date: Thu, Apr 20, 2023 06:31 AM
To: ***@***.***&gt;;
Cc: "Dahan ***@***.******@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] [Bug] Continuous scrolling breaks afterpinching to zoom on the page (Issue #927)




 
I tested the extension on Brave 112; the scrolling is smooth, but it doesn't scroll all the way to the end of the page (which I can open a separate issue for).
 
https://user-images.githubusercontent.com/11276349/233213874-497238a8-3940-40f1-9c47-40937f0a8020.mov
 
Are there any settings in Firefox that can help resolve the issue?

**Comment by gdh1995** [comment]
reproduced

**Comment by gdh1995** [comment]
Hello, Vimium C has published a new version and you may have a retry.

**Comment by MahdiNazemi** [comment]
Thank you, the updated version is working well for me.
