### ISSUE TITLE
[Feature Request]执行autoOpen指令时网页中没有选中文字时,执行openCopiedUrlInNewTab指令

### ISSUE THREAD

**Issue by awaken233** [gdh1995/vimium-c#929]
**现状**
我给autoOpen指令映射了快捷键, 当网页中没有选中文字时, 执行此快捷键不起作用, 不会打开新的标签页. 我需要按下P键, 才会打开新的标签页.

**期望**
当我网页中没有选中文字时, 我期望能直接使用系统剪贴板中的内容作为搜索内容打开一个新的标签页

**Browser and OS**

- Browser name:  Chrome  112.0.5615.121 (正式版本) (arm64) 
- OS name:  macos
- vimium-c: [1.99.99](https://github.com/gdh1995/vimium-c/blob/master/RELEASE-NOTES.md#19999)

**Comment by gdh1995** [comment]
`autoOpen` 本来就会在没选中文字时自动读剪贴板，你怎么写的映射规则？

试试 `map xxx autoOpen copied` 呢？
