### ISSUE TITLE
Cannot find the initial commit date

### ISSUE THREAD

**Issue by alexherbo2** [gdh1995/vimium-c#93]
The initial commit of the project looks like an import.

**Comment by gdh1995** [comment]
The real first commit is from compiled Javascript files of Vimium, but I've modified a lot of lines and then rebased messy commits into the current "first" one.

**Comment by alexherbo2** [comment]
The creation of the project corresponds to the initial commit, _2014-05-14_?

**Comment by gdh1995** [comment]
Yes, it's created from rebasing.
