### ISSUE TITLE
[feature request] Vomnibar open result on current tab if current is "New tab URL"

### ISSUE THREAD

**Issue by touch-feel** [gdh1995/vimium-c#930]
**What command or commands**

Vomnibar.activateBookmarksInNewTab, or any other  "Vomnibar.***InNewTab"

**How should a feature do**
These command  open result on current tab if current url is  a blank new tab.
![2345截图20230419151928](https://user-images.githubusercontent.com/73594022/232998880-eaa7d302-f4c8-4d9b-9bdd-0799368012f3.png)

**Browser and OS**

- Browser name: 
- OS name:

**Comment by gdh1995** [comment]
You may just press `Shift+Enter` to force Vomnibar to open selected URL in a current tab.

**Comment by gdh1995** [comment]
Here's another way using conditional key mappings:
```
# replace "a9....................." with a real hostname as you want
env newtab host=":moz-extension://a9...................../"
run o Vomnibar.activateInNewTab expect="newtab:Vomnibar.activate"
run b Vomnibar.activateBookmarksInNewTab expect="newtab:Vomnibar.activateBookmarks"
# and all others
```
