### ISSUE TITLE
Open Vomnibar with starting text

### ISSUE THREAD

**Issue by ghost** [gdh1995/vimium-c#931]
Basically, I would like to use different keymaps to trigger the Vomnibar for different custom search engines

I have Vomnibar configured to use youtube custom search engine when I start the entry with `yt`. One way would be to trigger the Vomnibar with a keymap to open the vomnibar with the text `yt ` already entered in it, so I can just starty typing.

I have looked into using something lie: `map x Vomnibar.activate $then="send keystrokes='yt ' "`, but I cannot figure out a command to send keystrokes. Is this possible?

Another possibility is to open the vomnibar with no starting text, but instead have it set to use youtube as the default search engine for just this once, when I use the keybind. Is this possible?

Thank you for consideration :)

**Comment by gdh1995** [comment]
For example:
```
map b Vomnibar.activateInNewTab keyword="bing"
```

**Comment by gdh1995** [comment]
> Another possibility is to open the vomnibar with no starting text, but instead have it set to use youtube as the default search engine for just this once, when I use the keybind. Is this possible?

Not suggested.
