### ISSUE TITLE
请教VimC如何在其它拓展的主页（例如iTab新标签页)

### ISSUE THREAD

**Issue by EricWong1994** [gdh1995/vimium-c#932]
你好，我浏览器安装了iTab新标签页拓展，Vimc的任何命令在该页面都不生效，这个有什么方法能解决吗？

**Comment by gdh1995** [comment]
需要找到并修改目标扩展的文件，参考 https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions

**Comment by EricWong1994** [comment]
> 需要找到并修改目标扩展的文件，参考 https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions 

我不是这个拓展的开发者，也能这样做吗？

**Comment by gdh1995** [comment]
可以。参考文档里说了，找到文件后复制一份就能改





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月2日(周二) 上午8:14
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.******@***.***&gt;;
主题: Re: [gdh1995/vimium-c] 请教VimC如何在其它拓展的主页（例如iTab新标签页) (Issue #932)




  
需要找到并修改目标扩展的文件，参考 https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions
  
我不是这个拓展的开发者，也能这样做吗？
