### ISSUE TITLE
请教如何在复制URL时自动删除后面带的？参数

### ISSUE THREAD

**Issue by LarryKHite** [gdh1995/vimium-c#934]
比如访问的URL是：https://github.com/vimium-c/?swcfpc=1
但我只想提取 https://github.com/vimium-c/ 部分
该如何设置？
非常感谢！

**Comment by gdh1995** [comment]
需要编写 “文字自动替换” 的规则，参考 https://github.com/gdh1995/vimium-c/issues/349#issuecomment-853785589

替换规则本身类似于 sed 命令的替换写法，支持 JS 正则和 JS String.replace 参数写法，参考 https://github.com/gdh1995/vimium-c/wiki/Substitute-URLs-and-text-during-commands
