### ISSUE TITLE
firefox上能识别到按钮，在chrome上不行

### ISSUE THREAD

**Issue by cppddz** [gdh1995/vimium-c#936]
![图片](https://user-images.githubusercontent.com/15965505/236756151-f63de881-44f7-4c8a-a1b8-ec27eca7c95f.png)
这个是edge浏览器上的，很多按钮不行

![图片](https://user-images.githubusercontent.com/15965505/236756390-1080cb5e-9c0c-4cb1-89a0-5a9e5132f351.png)
这个shi火狐上的，按钮都是正常识别

**Comment by gdh1995** [comment]
这个区别是因为有个“识别元素有没有动态绑上 onclick 事件”的操作在 Firefox 上很容易，但在 Chrome、Edge 上比较费 CPU，需要手动触发。

- 可以在 LinkHints 刚启动时按 Tab，就会强制它扫描一遍带 onclick 的元素，再重启 LinkHints；
- 也可以在 LinkHints 模式下按 `F2` ，同样会扫一遍 onclick 元素

你也可以参考 https://github.com/gdh1995/vimium-c/wiki/Add-or-remove-hints#zh 来让 LinkHints 默认标记出来这些方格
