### ISSUE TITLE
limit number of Vomnibar.activateTabs 

### ISSUE THREAD

**Issue by playdougher** [gdh1995/vimium-c#939]
**map t Vomnibar.activateTabs noSessions="start"** may take one second to show up, I think it's slow if I want to switch between 4 or 5 tabs often

**I think activate slow because it has 126 entries show up every time I activate it and it needs time to sort entries. Can I limit the number to about 30? I think it will be much faster? Thanks!**

When a user has done such steps:
1. open 130 tabs
2. type 't'

**Browser and OS**

- Browser name: Mozilla Firefox 108.0.2
- OS name: cpe:/o:opensuse:tumbleweed:20230112

Name 	Firefox
Version 	108.0.2
Build ID 	20230104165113
Distribution ID 	openSUSE
User Agent 	Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0
OS 	Linux 6.2.10-1-default #1 SMP PREEMPT_DYNAMIC Thu Apr 6 10:36:55 UTC 2023 (ba7816e)

vimium C version 1.99.99

**Comment by gdh1995** [comment]
Sorry but it's an issue of Firefox:
1. There's no API to get "tab number" of a window
2. Now that Vimium C needs to sort tabs, it have to access all tabs in a current window
3. This action should have been fast enough, but Firefox has a special feature making it slowing down:
- 1. Firefox provides favicon data as a "base64" URL to info of every tab
- 2. Such a URL may be 4KB~200KB
- 3. As a result, 130 tabs means 1~10 MB URL string - and took much time to show

**Comment by gdh1995** [comment]
Chrome doesn't use base64 URL to provide favion to extensions.

Unfortunately, Firefox always send it and there's no way to avoid them.

**Comment by gdh1995** [comment]
> Can start the sort task in the background as soon as I switch to a tab

No, because this way will waste CPU and slow down Vimium C when you don't open a Vomnibar.

**Comment by playdougher** [comment]
Yes, but is there a way to show only tabs in current winodw? then it doesn't need to sort all tabs.

**Comment by gdh1995** [comment]
`map xxx Vomnibar.activateTabs currentWindow`

**Comment by playdougher** [comment]
> `map xxx Vomnibar.activateTabs currentWindow`

it works great because usually not that much tabs exist in one window
