### ISSUE TITLE
What does Chinese support mean?

### ISSUE THREAD

**Issue by alexherbo2** [gdh1995/vimium-c#94]

**Comment by gdh1995** [comment]
> Some websites use Chinese characters in their URLs. For example, a URL may be https://www.baidu.com/s?ie=UTF-8&wd=%E7%99%BE%E5%BA%A6, and %E7%99%BE%E5%BA%A6 is URL-encoded 百度. What's more, some Chinese characters may even be encoded by the GBK charset, then the encoded text is %B0%D9%B6%C8. Vimium++ supports them and your search text on Vomnibar will be used to match decoded text.
> 
> And for other languages and charsets, users may set the advanced option Locale encoding (default to GBK) to make Vimium++ auto decode URLs.

--- as said in https://github.com/gdh1995/vimium-c/issues/12#issuecomment-344901071 .

BTW, could you put these questions in a single issue?
