### ISSUE TITLE
[Feature Request] Vomnibar don't show history (presentation mode)

### ISSUE THREAD

**Issue by hacker-DOM** [gdh1995/vimium-c#940]
He there! I'm recording my first podcast episode in half an hour, and I was wondering how I'll be able to screenshare but keeping privacy. It seems that in private/incognito windows, the browser still autocompletes history and bookmarks (in the address bar) and Vimium-C does the same. It would be great if VC had options to disable this (separately for history and for bookmarks) in the Vomnibar.

Thanks 🙏

**Comment by gdh1995** [comment]
&nbsp;If Vomnibar doesn't show any history, then why is do you activate it?



---Original---
From: ***@***.***&gt;
Date: Fri, May 12, 2023 21:55 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] [Feature Request] Vomnibar don't show history(presentation mode) (Issue #940)




 
He there! I'm recording my first podcast episode in half an hour, and I was wondering how I'll be able to screenshare but keeping privacy. It seems that in private/incognito windows, the browser still autocompletes history and bookmarks (in the address bar). It would be great if VC had options to disable this (separately for history and for bookmarks) in the Vomnibar.
 
Thanks 🙏

**Comment by hacker-DOM** [comment]
to use it as a search box :-) I guess I could use my browser's, but Vomnibar is much easier to activate using keyboard, is better positioned and has larger text font..

**Comment by gdh1995** [comment]
```map o Vomnibar.activateInNewTab mode="search"``` may help - it only complete your query using the search engine completer. But it doesn't recognize whether you're in an incognito window or not.

I'll add a way to run another command if in incognito, and the new key mapping may look like:
```
env my_env incognito
map <v-omni> Vomnibar.activateInNewTab
run o omni expect="my_env:omni#mode=search"
```

**Comment by hacker-DOM** [comment]
No, this mode thing is perfect. I personally don't need the incognito functionality. Btw, have you considered documenting all command options? :-) It seems VC has a lot of functionality that I only ever unlock by opening an issue. The source code references might be readable, but they can still be a challenge, especially if I wasn't familiar with Javascript.
