### ISSUE TITLE
shortcut problem 

### ISSUE THREAD

**Issue by witfish007** [gdh1995/vimium-c#941]
**Describe the bug**

i have unmap z,but i can not use z in other extention shortcut.
when remove the vimium-c, shortcut z is work in other extention shortcut.so why?
i use edge and chrome having the same problem.

**Comment by gdh1995** [comment]
&nbsp;Why did you close this？



---Original---
From: ***@***.***&gt;
Date: Mon, May 15, 2023 16:55 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [gdh1995/vimium-c] shortcut problem  (Issue #941)




 
Closed #941 as completed.
