### ISSUE TITLE
`nextTab` and `previousTab` are unreliable.

### ISSUE THREAD

**Issue by hacker-DOM** [gdh1995/vimium-c#943]
Hi, I am on vivaldi [6.0.2979.18 (Stable channel) (arm64)]

I have map J nextTab, map K previousTab.

The thing is, it doesn't work reliably. Like right now, I have tabs O ... A B C D

On A, the sequence for nextTab is A, D, B, C, O. I don't think it does it by history either, it's just ever so slightly unreliable that I end up not using J and K, which imho is a big pity.

Do the commands have any options that I could experiment with? Thanks!

PS I have

<img width="293" alt="image" src="https://github.com/gdh1995/vimium-c/assets/18601956/149fa818-0148-41bb-b602-9db6057a3a5a">

and still new tabs almost always skip the next tab. This might be an issue in Vivaldi, in the New Tab Adapter or whatnot, but it might be related to the issue above.

**Comment by gdh1995** [comment]
> new tabs almost always skip the next tab

Sounds like a compatibility issue of NewTab Adapter.

> `A D B C O`

I'm not sure why. I just installed a fresh Vivaldi 6.0.2979.22 stable x64 on Win11, and `J` and `K` work well.
