### ISSUE TITLE
Edge 浏览器里选中文字后无法触发快捷键

### ISSUE THREAD

**Issue by iKineticate** [gdh1995/vimium-c#944]
比如我在百度搜索的结果里对某段文字选择，并使用autoOpen的功能，可以对已选中的文字进行搜索。
但是在绝大部分的网站里我对某段文字选择后，使用autoOpen的功能是无效的，不能搜索已选中的文字。
请问有什么办法能解决这个问题吗？感谢！

**Comment by gdh1995** [comment]
右下角有什么提示？


你选的不是文字输入框里的吧？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月21日(周日) 晚上11:12
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [gdh1995/vimium-c] 关于autoOpen的选中搜素问题 (Issue #944)




 
比如我在百度搜索的结果里对某段文字选择，并使用autoOpen的功能，可以对已选中的文字进行搜索。
 但是在绝大部分的网站里我对某段文字选择后，使用autoOpen的功能是无效的，不能搜索已选中的文字。
 请问有什么办法能解决这个问题吗？感谢！

**Comment by iKineticate** [comment]
右下角没有提示，使用这个功能后也没有任何反应，除了百度搜素的结果里面能用。

选的不是文本框里的内容（文本框是指能打字输入文字的框吗？）。

**Comment by gdh1995** [comment]
有具体例子吗，比如在哪个 URL 的网页上会出现这个问题？

什么浏览器、浏览器版本是多少、什么操作系统？你浏览器上的 Vimium C 版本是多少？

你确定触发了 autoOpen 吗？你的 “自定义快捷键” 怎么映射的 autoOpen ？

**Comment by iKineticate** [comment]
Edge浏览器版本：113.0.1774.50
Vimium版本：1.99.99
Windows11 on Arm：22H2_25357.1
 
我设置"v"映射autoOpen，
映射其他键也是类似情况。

比如百度的搜索结果https://www.baidu.com/s?wd=vimium+c
按下"v"是可以实现搜索选取的内容
![Vimium_可搜](https://github.com/gdh1995/vimium-c/assets/115683118/933c7011-c7a0-4bb5-ad2a-8602c29a00cc)

其他的大部分网页基本都不可以，比如百度知道的内容就不可以选取搜索
![Vimium_不可搜](https://github.com/gdh1995/vimium-c/assets/115683118/9c33b132-410a-43a4-8c89-8081df76138e)




> 有具体例子吗，比如在哪个 URL 的网页上会出现这个问题？
> 
> 什么浏览器、浏览器版本是多少、什么操作系统？你浏览器上的 Vimium C 版本是多少？
> 
> 你确定触发了 autoOpen 吗？你的 “自定义快捷键” 怎么映射的 autoOpen ？

**Comment by gdh1995** [comment]
哦这个是键盘焦点被 edge 浏览器拦截了，选中后焦点在“使用 xx 搜索”那儿。去`edge://settings/accessibility`设置页面关掉就行：

![image](https://github.com/gdh1995/vimium-c/assets/5547703/cdc6aa38-df55-4a03-ac50-c227697c698d)

**Comment by iKineticate** [comment]
> 哦这个是键盘焦点被 edge 浏览器拦截了，选中后焦点在“使用 xx 搜索”那儿。去设置页面关掉就行：`edge://settings/accessibility`
> 
> ![图像](https://user-images.githubusercontent.com/5547703/242019555-cdc6aa38-df55-4a03-ac50-c227697c698d.png)

非常感谢！！！！祝你生活愉快，身体健康！
