### ISSUE TITLE
Multi-key mapping is interrupted by "r"

### ISSUE THREAD

**Issue by cyberhuman** [gdh1995/vimium-c#946]
**Describe the bug**

I have custom key mappings like these:
```
map pvse openCopiedUrlInCurrentTab keyword="vse"
map pvrt openCopiedUrlInCurrentTab keyword="vrt"
```
and custom search engines like these:
```
vse: https://test.com/path?param=se&input=$S Search se
vrt: https://test.com/path?param=rt&input=$S Search rt
```

Now, copying some text and pressing <kbd>p</kbd> <kbd>v</kbd> <kbd>s</kbd> <kbd>e</kbd> will open `https://test.com/path?param=se&input=some+text`. But pressing <kbd>p</kbd> <kbd>v</kbd> <kbd>r</kbd>... will cause the page to reload.

**To Reproduce**

Described above.

**Browser, OS and Vimium C versions**

- Browser name: Chrome 
- Browser version: Version 113.0.5672.126 (Official Build) (64-bit)
- Vimium C version: 1.99.99
- OS name and version: Arch Linux

**Comment by gdh1995** [comment]
Not reproduced on Chrome 113 x64 on Win 11. Here's my test configuration:
![image](https://github.com/gdh1995/vimium-c/assets/5547703/34ab1de3-9d04-47ed-8409-d9528eefc818)

If there's no key pressed in 30 seconds, then old keys will be aborted, so you may need to press `p`, `v`, `r` and `t` in normal speed

**Comment by cyberhuman** [comment]
@gdh1995 thanks. Indeed, my above example works.
Here is the reproducible configuration that I did by removing parts of my configuration and making sure the problem still persists:
```
map Pvrt openCopiedUrlInNewTab keyword="vrt"
map Psrt openCopiedUrlInNewTab keyword="vse"
```
Notice the capital <key>P</key>.
Also, my keyboard layout is Dvorak, if that matters, and the option "Always ignore keyboard layout" is disabled.

**Comment by gdh1995** [comment]
Sorry you're right. There's a but about long key sequences (`>=` 3 keys) since 2022/10/31.

I'll fix it in days.

**Comment by cyberhuman** [comment]
No problem! Thank you for this great extension!

**Comment by gdh1995** [comment]
Hello a new version has been released and you may take a try.

**Comment by cyberhuman** [comment]
I checked and it works! Thank you very much for your time.
