### ISSUE TITLE
'Hover' feature unavailable

### ISSUE THREAD

**Issue by gokussjx** [gdh1995/vimium-c#95]
Have you considered adding the 'mouse-hover' feature?
It's extremely useful and allows mimicking a mouse hover on a link/frame, instead of clicking it.
Allows tooltips or other info (such as URL) to be displayed by the browser.
cVim does have it, and I was hoping to see it under this project as well. (I prefer Vimium-C over the alternatives in general)

**Comment by gdh1995** [comment]
There has been `LinkHints.activateModeToHover`, and it will dispatch simulated `mouseover` events to hint targets.

Neither the tooptip at the bottom left, nor CSS `:hover` styles, is not accessible from web extensions, but if a page uses JavaScript to act on hover, simulated events may work.

For example, on Github I can use this command to show the user info card.

![image](https://user-images.githubusercontent.com/5547703/71478682-d32f0400-282b-11ea-8f1d-293ab7146674.png)

![image](https://user-images.githubusercontent.com/5547703/71478662-c14d6100-282b-11ea-968c-a3f172584cab.png)

**Comment by gokussjx** [comment]
This is actually wonderful. I didn't notice when this was added in. Thanks for bringing it to my attention.
Tried it out, and as you mentioned, apart from tooltip and certain `:hover` features, it works as expected.
