### ISSUE TITLE
Doesn't work on new tab in Firefox 114

### ISSUE THREAD

**Issue by kuator** [gdh1995/vimium-c#951]
**Describe the bug**

I upgraded to Firefox 114 and the extension now doesn't work in a new tab

**To Reproduce**
Press `ctrl-t` to open a new tab. Press `O` to open a Vomnibar search. It doesn't work, the extension says `Can't read or change data on this site`

![Screenshot from 2023-05-30 10-24-14](https://github.com/gdh1995/vimium-c/assets/25168308/dbbada5e-3ee5-4b2e-beee-145125b175c3)

**Browser, OS and Vimium C versions**

- Browser name: Firefox
- Browser version: 114
- Vimium C version: Latest
- OS name and version:  Ubuntu 22.04

**Comment by kuator** [comment]
Nevermind, fixed it

**Comment by gdh1995** [comment]
Um how did you fix it?

**Comment by kuator** [comment]
> Um how did you fix it?

The new version of firefox changed the default `blank.html` page content. I ended up manually editing to what it was before. Here's the script: https://github.com/kuator/dotfiles/blob/main/scripts/patch-the-fox.sh
