### ISSUE TITLE
LinkHints.activate and LinkHints.activateOpenInNewTab seem to be switched

### ISSUE THREAD

**Issue by gabrieljreed** [gdh1995/vimium-c#953]
**Describe the bug**
`LinkHints.activate` and `LinkHints.activateOpenInNewTab` appear to have swapped functionality for me on a fresh install of Vimium C (I tried both Chrome and Firefox, but I mainly use Firefox). I have to do the following remapping to get `f` to open in current tab and `F` to open in new tab:

```
map f LinkHints.activateOpenInNewForegroundTab
map F LinkHints.activate
```

This could very well just be user error, but I'd really like to get `F` to open the link in a new active tab, but I can't seem to find a binding that works for that.

**To Reproduce**

Fresh install of Vimium C in Firefox or Chrome from the webstore.

![image](https://github.com/gdh1995/vimium-c/assets/60671652/d8f83028-5475-4a17-9bb4-106ebc6c357f)

**Browser, OS and Vimium C versions**

- Browser name: Firefox 
- Browser version: 113.0.2
- Vimium C version: 1.99.991
- OS name and version: Windows 10

**Comment by gdh1995** [comment]
Did you hold on Shift when you pressed a letter key to select a hint?


Although hint shows upper-case letters, you just need to press the letter itself, but not Shift or CapsLock.



---Original---
From: "Gabriel ***@***.***&gt;
Date: Fri, Jun 2, 2023 03:41 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] LinkHints.activate andLinkHints.activateOpenInNewTab seem to be switched (Issue #953)




 
Describe the bug
 LinkHints.activate and LinkHints.activateOpenInNewTab appear to have swapped functionality for me on a fresh install of Vimium C (I tried both Chrome and Firefox, but I mainly use Firefox). I have to do the following remapping to get f to open in current tab and F to open in new tab:
 map f LinkHints.activateOpenInNewForegroundTab map F LinkHints.activate  
To Reproduce
 
Fresh install of Vimium C in Firefox or Chrome from the webstore.
 

 
Browser, OS and Vimium C versions
  
Browser name: Firefox
 
Browser version: 113.0.2
 
Vimium C version: 1.99.991
 
OS name and version: Windows 10

**Comment by gabrieljreed** [comment]
Wow, that was it. Thanks so much, can't believe I didn't figure this out before now!
