### ISSUE TITLE
关于参数的使用教程

### ISSUE THREAD

**Issue by yuan-ge** [gdh1995/vimium-c#955]
大佬你好，这款工具用起来很方便，很感谢。
有一个个人建议或者是困惑，就是关于命令里面参数的设置和作用感觉不是很明确。能不能在文档中详细介绍一下？非常感谢。
如果是我看漏了，请给出链接【捂脸】。

**Comment by gdh1995** [comment]
没啥时间写这方面文档，有需求可以在 issues 里问，我看看能不能用参数凑出来。或者就只能看源码了，可以把 https://github.com/gdh1995/vimium-c/wiki/List-of-all-commands 当入口搜关键词
