### ISSUE TITLE
feature request: want to have a "command mode"

### ISSUE THREAD

**Issue by screw-hand** [gdh1995/vimium-c#956]
vim have a command mode: start with `:`, we can use the `:w` `:q` command;
vimium-c should also has a command mode to use [List of all commands · gdh1995/vimium-c Wiki](https://github.com/gdh1995/vimium-c/wiki/List-of-all-commands);
And we will don't must bind the key to use the command.
Would you consider activating command mode with `:c` ([available letters](https://github.com/gdh1995/vimium-c/wiki/How-to-...-on-Vomnibar) like `o/b/B/w/W`） in Vomnibar ?

**The point is we can use all commands without binding keys.**

**Comment by gdh1995** [comment]
As said in https://github.com/gdh1995/vimium-c/wiki/Vimium-inner-URLs, `vimium://run/*****` can be used to trigger any command with any options as you want.

And the `***` part should be replaced with a valid `key` of the `run` directive in key mappings(https://github.com/gdh1995/vimium-c/wiki/Auto-run-a-tree-of-commands#short-syntax):
- aka "a command, a `#` character, and some URL-query-param encoded options joined by `&`".

For example, `vimium://run/autoOpen#keyword=g&reuse=new-fg` means to trigger `autoOpen` with `keyword="g"` and `reuse="new-fg"`.

Then, you may add such a search engine:
```
\:c: vimium://run/$S Run Directly
```

And then `:c scrollDown` + `<Enter>` on Vomnibar will scroll a page down

**Comment by screw-hand** [comment]
Thank you for your reply, and I apologize for the delay in my reply. I spent some time understanding your comments, and overall, you are correct. However, I used ChatGPT to help me understand better. 

1. `vimium://run/*****` is incorrect syntax. It should be `vimium://run *****`. You can try entering `vimium://run scrollDown` in the Vomnibar.
2. `vimium://run/autoOpen#keyword=g&reuse=new-fg` is not a great example. When I copied this command without understanding it, it led to some confusion. 
    - It wasn't until I understood [autoOpen](https://github.com/gdh1995/vimium-c/blob/master/i18n/zh/help_dialog.json#L75) that I realized this command uses the search engine with `keyword` as `g` to open the recently copied address.
    - So when I ran this command in the Vomnibar, the browser opened `https://www.google.com/search?q=vimium%3A%2F%2Frun%2FautoOpen%23keyword%3Dg%26reuse%3Dnew-fg` 🙁🙁
3. The `search engine` mentioned in `Then, you may add such a search engine` refers to the configuration in the `Custom Search Engines` section of Vimium C's `vimium://run options` page: `\:c: vimium://run/%s Run Vimium C commands`.
---
Despite the challenging process, I can now trigger all commands by entering `:c ` in the Vomnibar. Thank you for your help, project owner!

![image](https://github.com/gdh1995/vimium-c/assets/26453811/83a483e2-571b-45d7-a959-ff61b273b1b0)

**Comment by gdh1995** [comment]
Well, most are correct ^_^, although `vimium://run/*****` is absolute equal with `vimium://run *****`.
