### ISSUE TITLE
add undoRemoveTab

### ISSUE THREAD

**Issue by benedikt-bartscher** [gdh1995/vimium-c#958]
**What command or commands**

undoRemoveTab / reopenRemovedTab

**How should a feature do**

Qutebrowser for example has an "undo" command which can reopen the last removed tabs. It would be awesome to have this in vimium-c.

**Comment by gdh1995** [comment]
There have been such commands: please try `restoreTab` and `restoreGivenTab`.

The difference is, when `restoreTab` is triggered with `count=2`, then Vimium C will restore 2 closed tabs; while `restoreGiveTab` with `2` will restore the 2nd-recent (closed) tab.

**Comment by benedikt-bartscher** [comment]
Sorry, i missed that. Works great!
Thank you very much for this awesome project.
