### ISSUE TITLE
查找模式下使用中文输入法有问题

### ISSUE THREAD

**Issue by YandLiu** [gdh1995/vimium-c#96]
如截图所示
Win10 自带微软拼音，Firefox 71，扩展AMO上最新版
![2](https://user-images.githubusercontent.com/26127104/71513756-db507780-28ef-11ea-8586-22dd56ae2dea.gif)
![1](https://user-images.githubusercontent.com/26127104/71513757-db507780-28ef-11ea-9deb-06ca079b373f.gif)

**Comment by gdh1995** [comment]
呃Firefox里ShadowDOM+contenteditable配合的bug挺多的，之前就遇到过Linux上才有的一个问题，我晚上调一下。

**Comment by gdh1995** [comment]
1.79.2 已经发布到Firefox扩展中心了，我在Win10和Ubuntu 18上测了下基本操作已经能用了。可以试一下了。

**Comment by YandLiu** [comment]
赞！感谢修复！测试没问题！
