### ISSUE TITLE
Smooth scrolling doesn't feel smooth

### ISSUE THREAD

**Issue by bastianpedersen** [gdh1995/vimium-c#966]
I keep comparing the "smooth scrolling" offered by Vimium C against the native smooth scrolling in Edge. Maybe it's just me, but smooth scrolling in Edge feels really smooth. I can't seem to figure out how to get the same feeling using Vimium.

Using Vivaldi for what it's worth.

**Comment by gdh1995** [comment]
No there are no enough browser APIs to achieve this.


Edge and other Chromium-like browsers trends to disable web pages' JS code execution during scrolling, but Vimium C can not do so.



---Original---
From: "Bastian ***@***.***&gt;
Date: Thu, Jul 6, 2023 04:26 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] Smooth scrolling doesn't feel smooth (Issue #966)




 
I keep comparing the "smooth scrolling" offered by Vimium C against the native smooth scrolling in Edge. Maybe it's just me, but smooth scrolling in Edge feels really smooth. I can't seem to figure out how to get the same feeling using Vimium.
 
Using Vivaldi for what it's worth.

**Comment by gdh1995** [comment]
But, if you hold on a key, Vimium C can scroll at smoothly changed speeds, by rewriting the smooth scrolling behavior.


If using the native scrolling, there's no way for extensions to control the speed change.



---Original---
From: "Bastian ***@***.***&gt;
Date: Thu, Jul 6, 2023 04:26 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [gdh1995/vimium-c] Smooth scrolling doesn't feel smooth (Issue #966)




 
I keep comparing the "smooth scrolling" offered by Vimium C against the native smooth scrolling in Edge. Maybe it's just me, but smooth scrolling in Edge feels really smooth. I can't seem to figure out how to get the same feeling using Vimium.
 
Using Vivaldi for what it's worth.

**Comment by bastianpedersen** [comment]
Alright, thank you for clarifying.
