### ISSUE TITLE
onekey close vimium_c

### ISSUE THREAD

**Issue by zxszx4** [gdh1995/vimium-c#97]
Sorry, my English is not good. This passage is translated by translation software.

First of all, I'm glad to use your plug-in, and it's really unexpected that there are Chinese instructions.

Secondly, I would like to talk about my suggestion, to add a shortcut key that can turn on / off vimium with one click.

I often browse different websites, some of which have video function, or my own shortcut key, and using your plug-in will affect the normal function use, but I can't confirm which websites need to be closed. In addition, I browse synchronously on multiple devices, and it's difficult to add exceptions every time. Some websites may not be browsed once and will not be browsed again Cost matching consumption, so I want to add this function. Maybe i or I can try it. I remember a version of similar plug-ins is implemented with this key, thank you!

**Comment by gdh1995** [comment]
Uh, I think there has been an advanced usage to do this.I t's about `openUrl`, so it will work only on a current page. Is it enough?

By the way, the first option ”Exclusion rules” is about how to control states on web pages according to their URLs.

If you can understand Chinese, here's  translation: 已经有了一个命令的高级用法，可以来临时禁用或者启用。但是目前这个命令只适用于当前页面，如果你刷新页面或者切换到别的标签页的话，它的状态还是旧的默认状态。这够不够啊？具体明天等我一会儿找电脑确认一下。

另外目前，设置页面的第1个设置项，是根据网页的网址来决定有哪些快捷键就是被允许或者被禁止的，这个是你打开相应的页面之后，它默认就会被生效。

**Comment by gdh1995** [comment]
Example: `map <f7> openUrl url="vimium://status\u0020toggle\u0020^\u0020<f7>"`

Explain:
* `openUrl` means to execute specified URL / URLs, and following `url=` is a JSON-encoded URL
* `vimium://`

**Comment by zxszx4** [comment]
额，谢谢，我之前可能看帮助没有太仔细，我又看了一遍，找到了那个i键临时禁用，esc关闭禁用。

**Comment by gdh1995** [comment]
哦enterInsertMode是方便编辑文字的，默认esc退出禁用模式，可以用参数stat、code来调整用于退出的键是哪个，比如`map <a-?> enterInsertMode stat=8`表示遇到Shift+Esc才退出。

相对来说openUrl这个办法更彻底些，会关闭内部的事件绑定、销毁当前标签页里已打开的Vomnibar页面，而且对当前标签页的所有iframe都生效。看你需求了。
