### ISSUE TITLE
searchInAnother but pick search engine through Vomnibar

### ISSUE THREAD

**Issue by archelaus** [gdh1995/vimium-c#973]
**Feature Request:** Select search engine through Vomnibar for searchInAnother command

**Description:**
Currently, the `searchInAnother` command in Vimium C performs a search using the preferreed search engine. This feature request proposes enhancing the command to allow users to select the search engine directly through the Vomnibar.

I'm not sure if this functionality already exists, so I thought I'd ask for it to be implemented if it isn't currently available.

**Expected Behavior:**
When invoking the `searchInAnother` command, a prompt should be displayed in the Vomnibar allowing the user to select the desired search engine. Once selected, the command should perform the search using the chosen search engine.

Thank you for considering this enhancement.

**Comment by gdh1995** [comment]
There has been `Vomnibar.activateUrl` to do so - it will auto parse a current tab's URL using your `custom search engines`, and then you may edit the search engine keyword and query words easily.

**Comment by archelaus** [comment]
> Vomnibar.activateUrl

Thanks a bunch, that works for me.
