### ISSUE TITLE
Url regex substitution

### ISSUE THREAD

**Issue by hacker-DOM** [gdh1995/vimium-c#977]
Hi there!

I was wondering if it is possible to set up a keybinding for a specific host that will perform a redirect. In particular, i would like:

- on github.com
- `'` will perform:
- `https://github\.com/([^/])+/([^/])+/issues\?q=is%3Aissue\+is%3Aopen\+sort%3Aupdated-desc` will redirect to (for example) `example.com/$1`.

Basically I want a keybinding that will change the default issue filter to a custom one, but I'm having trouble navigating the different ways to approach this

Update: I actually got it to work using a search engine with javascript code, but I would still like it as a mapping (the code is the following:)

```
js: javascript:\ location.href=location.href.replace(/=.*/,'=sort%3Acomments-desc'); Run JavaScript
```

**Comment by gdh1995** [comment]
Hello, I'm glad that you have found a effective mapping.

Here's another idea to use `text substitution`:
1. add to `Auto substitution of various text` on Vimium C Options:
- 1. `_issue/=.*$/=sort%3Acomments-desc/`
2. add a key mapping of `map ' openUrl url_mask url="$S" sed="_issue"`
