### ISSUE TITLE
add yd (yank domain) shortcut

### ISSUE THREAD

**Issue by macmoritz** [gdh1995/vimium-c#978]
**What command or commands**
Personally I used yd in qutebrowser a lot of, I am missing this shortcut here.

**How should a feature do**
Copy only the FQDN (full qualified domain name) of the current url triggered by the comment yd (yank domain).

**Comment by gdh1995** [comment]
Try this: `map yd copyWindowInfo type="tab" format="${host}"`

**Comment by macmoritz** [comment]
Works! Thanks.
