### ISSUE TITLE
Can't complete hints

### ISSUE THREAD

**Issue by parogen** [gdh1995/vimium-c#981]
On Firefox.

I'm unable to complete any hints for any of the link functions. I can press all letters except the last one, including being unable to complete single letter hints.

**Comment by gdh1995** [comment]
sorry it's a bug of the new version today. I'll fix it in minutes.

**Comment by gdh1995** [comment]
Hello, has this been fixed on the new v1.99.995 ?

**Comment by Knew1t** [comment]
> Hello, has this been fixed on the new v1.99.995 ?

yes! thank you

**Comment by qsantos** [comment]
Thanks!

**Comment by parogen** [comment]
Works for me.
