### ISSUE TITLE
'gi' shortcut doesn't work

### ISSUE THREAD

**Issue by uniresuto** [gdh1995/vimium-c#982]
**Describe the bug**

Recently 'gi' shortcut stopped working in Firefox.

**To Reproduce**

1. Go to any website with input box
2. Press 'gi' shortcut

**Browser, OS and Vimium C versions**

- Browser name: Firefox
- Browser version: 115.0.2
- Vimium C version: 1.99.994
- OS name and version: Windows_NT 10.0 19045

**Comment by uniresuto** [comment]
Updated the extension to 1.99.995. Everything works fine now.

**Comment by gdh1995** [comment]
Sorry again for the inconvenience.

Just a personal note: duplicate of #981 .
