### ISSUE TITLE
focusing text boxs and openning links stopped working after update 

### ISSUE THREAD

**Issue by ntriisii** [gdh1995/vimium-c#983]
**Describe the bug**
suddenly the `gi` , `f` and `F` keys stopped working (properly) after I vimium updated to version **1.99.994** 
1. as for the `gi` keys it doesn't work at all, but I can do `gg` etc.
2. as for `f` and `F` keys I'm presented with the link keys to press but I only can press the first key the second key is like not being sent to browser like this:

![Screenshot from 2023-07-23 12-45-52](https://github.com/gdh1995/vimium-c/assets/137733641/ac6eab00-37d8-45dd-8314-1ca52da62439)

looking in the console I see this error: `TypeError: 'queueMicrotask' called on an object that does not implement interface Window.`

**Browser, OS and Vimium C versions**

- Browser name: firefox
- Browser version: 114.0.2
- Vimium C version:  1.99.994
- OS name and version: Linux 5.13.0-40-generic 45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022

**Comment by gdh1995** [comment]
Hello now v1.99.995 has been published, so could you wait a while for Firefox to update Vimium C and then try again?

Duplicate of #981.

**Comment by ntriisii** [comment]
sure I will wait, thanks.

**Comment by ntriisii** [comment]
vimium updated and it is now works with no problem, thanks.
