### ISSUE TITLE
请问如何修改firefox的扩展程序以兼容vimium-c 

### ISSUE THREAD

**Issue by StirrerCymbal5zn** [gdh1995/vimium-c#986]
最近换到firefox使用，扩展为Tabliss  https://tabliss.io/

根据 #178 与wiki参考修改扩展文件以兼容vimium-c 。但不清楚该在哪个js文件中添加js代码段或是新建一个js文件。除了CSS与json文件没有修改过以外均尝试过在JS文件中添加或新建、并尝试添加新标签页修改器填入扩展地址”moz-extension://UUID/index.html“与在vimium-c 设置newtab、添加信任扩展名称等方式，但都无法在扩展主页调用vimium-c 
不知道自己是否哪里没有理解正确

![tabliss folder](https://github.com/gdh1995/vimium-c/assets/48485664/ba2e7a09-5d8f-44d9-b826-9c13b0f2490d)

![only one html](https://github.com/gdh1995/vimium-c/assets/48485664/3d15ca58-6568-48c0-996e-38ea48d4abfe)
![new js](https://github.com/gdh1995/vimium-c/assets/48485664/b1d6d725-c9fa-4dba-958c-f9456c767869)

**Comment by gdh1995** [comment]
这段代码要放到已有 js 里；也可以放到新建 js 文件，但要去修改相应的 HTML 文件，让它用起来这个 js。

新标签页修改器的那个填入url的地方只能作用于它自己，影响不了其它插件

**Comment by gdh1995** [comment]
哦另一个问题是，firefox里临时扩展是纯临时的，重启 firefox 后就没了要再手动添加。所以不是很推荐在 firefox 上自己搞，除非你已经想好了，愿意长时间不关闭 firefox，或者愿意把改出来的版本发布成一个新扩展再自己去安装这个扩展

**Comment by StirrerCymbal5zn** [comment]
> 哦另一个问题是，firefox里临时扩展是纯临时的，重启 firefox 后就没了要再手动添加。所以不是很推荐在 firefox 上自己搞，除非你已经想好了，愿意长时间不关闭 firefox，或者愿意把改出来的版本发布成一个新扩展再自己去安装这个扩展

感谢回复，firefox的文档允许第三方无签名扩展运行在开发者、ESR与nightly版本上。这似乎是非临时的。而根据本项目的wiki指引，firefox对所有扩展安装时都会分配一个临时UUID，这使得修改HTML文件中替换URL部分的UUID无法在安装前确定并进行修改。请问有什么办法吗？

**Comment by gdh1995** [comment]
vimium c扩展id是固定的 ***@***.*** ，所以就有了上边那一大段js代码，就是用来向vimium c扩展询问它当前的uuid是多少，然后动态引入它的 injector.js





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月6日(周日) 晚上11:02
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.******@***.***&gt;;
主题: Re: [gdh1995/vimium-c] 请问如何修改firefox的扩展程序以兼容vimium-c  (Issue #986)




  
哦另一个问题是，firefox里临时扩展是纯临时的，重启 firefox 后就没了要再手动添加。所以不是很推荐在 firefox 上自己搞，除非你已经想好了，愿意长时间不关闭 firefox，或者愿意把改出来的版本发布成一个新扩展再自己去安装这个扩展
  
感谢回复，firefox的文档允许第三方无签名扩展运行在开发者、ESR与nightly版本上。这似乎是非临时的。而根据本项目的wiki指引，firefox对所有扩展安装时都会分配一个临时UUID，这使得修改HTML文件中替换URL部分的UUID无法在安装前确定并进行修改。请问有什么办法吗？

**Comment by StirrerCymbal5zn** [comment]
> vimium c扩展id是固定的 ***@***.*** ，所以就有了上边那一大段js代码，就是用来向vimium c扩展询问它当前的uuid是多少，然后动态引入它的 injector.js
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月6日(周日) 晚上11:02 收件人: ***@***.***&gt;; 抄送: "Dahan ***@***.******@***.***&gt;; 主题: Re: [gdh1995/vimium-c] 请问如何修改firefox的扩展程序以兼容vimium-c (Issue #986) 哦另一个问题是，firefox里临时扩展是纯临时的，重启 firefox 后就没了要再手动添加。所以不是很推荐在 firefox 上自己搞，除非你已经想好了，愿意长时间不关闭 firefox，或者愿意把改出来的版本发布成一个新扩展再自己去安装这个扩展 感谢回复，firefox的文档允许第三方无签名扩展运行在开发者、ESR与nightly版本上。这似乎是非临时的。而根据本项目的wiki指引，firefox对所有扩展安装时都会分配一个临时UUID，这使得修改HTML文件中替换URL部分的UUID无法在安装前确定并进行修改。请问有什么办法吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

感谢帮助。已经在nightly环境实现兼容其他扩展的新标签页。但是出现了一个奇怪的问题：关闭浏览器后在任务管理器中可见所有的浏览器进程都假死在后台，如图
![Snipaste_2023-08-07_01-10-55](https://github.com/gdh1995/vimium-c/assets/48485664/d957637e-9c21-4670-9c3c-45d170bb9cda)

再次打开浏览器将无反应。而如果强制中断并重新打开则会必会报告如此页面
![Snipaste_2023-08-07_01-10-16](https://github.com/gdh1995/vimium-c/assets/48485664/96766b3c-c1fd-4762-9a90-0cd27e298ed0)
偶尔情况下，可完全关闭并重新打开浏览器后vimium-c会在新标签页失效 ，请问这是否有可能与提到的“firefox里临时扩展是纯临时的，重启 firefox 后就没了要再手动添加”的firefox问题有关？

**Comment by gdh1995** [comment]
nightly这版本太激进了，出啥问题都可能。日常用的话我最多用dev。建议你换到dev试试看


另外，按我几年前的体会，chrome dev仍然有可能崩溃，stable就没遇到过。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月7日(周一) 凌晨1:16
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.******@***.***&gt;;
主题: Re: [gdh1995/vimium-c] 请问如何修改firefox的扩展程序以兼容vimium-c  (Issue #986)




  
vimium c扩展id是固定的 @.*** ，所以就有了上边那一大段js代码，就是用来向vimium c扩展询问它当前的uuid是多少，然后动态引入它的 injector.js
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年8月6日(周日) 晚上11:02 收件人: @.&gt;; 抄送: "Dahan @.@.&gt;; 主题: Re: [gdh1995/vimium-c] 请问如何修改firefox的扩展程序以兼容vimium-c (Issue #986) 哦另一个问题是，firefox里临时扩展是纯临时的，重启 firefox 后就没了要再手动添加。所以不是很推荐在 firefox 上自己搞，除非你已经想好了，愿意长时间不关闭 firefox，或者愿意把改出来的版本发布成一个新扩展再自己去安装这个扩展 感谢回复，firefox的文档允许第三方无签名扩展运行在开发者、ESR与nightly版本上。这似乎是非临时的。而根据本项目的wiki指引，firefox对所有扩展安装时都会分配一个临时UUID，这使得修改HTML文件中替换URL部分的UUID无法在安装前确定并进行修改。请问有什么办法吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
感谢帮助。已经在nightly环境实现兼容其他扩展的新标签页。但是出现了一个奇怪的问题：关闭浏览器后在任务管理器中可见所有的浏览器进程都假死在后台，如图
 
 
再次打开浏览器将无反应。而如果强制中断并重新打开则会必会报告如此页面
 
 偶尔情况下，可完全关闭并重新打开浏览器后vimium-c会在新标签页失效 ，请问这是否有可能与提到的“firefox里临时扩展是纯临时的，重启 firefox 后就没了要再手动添加”的firefox问题有关？

**Comment by StirrerCymbal5zn** [comment]
> 

换用DEV版测试后未发现崩溃问题，但打开浏览器后扩展主页依旧无法调用vimium-c，必须新建标签页（即使依旧是扩展控制的）后才能使用

**Comment by gdh1995** [comment]
在扩展主页里用鼠标点一下空白位置后呢？

也许是加载顺序问题，vimium c 加载需要些时间，如果`runtime.sendMessage`发太早了就会取不到扩展ID从而失败。
如果是这个问题的话，你可以：
- 包一个 setTimeout(..., 500) 来延迟加载
- 或者失败后重试一次
- 最好的办法是，runtime.sendMessage 成功后旧把 ID 记下来，下次直接用，不用 sendMessage 了

抱歉我这周末或者下周末才有时间测。

**Comment by StirrerCymbal5zn** [comment]
> 在扩展主页里用鼠标点一下空白位置后呢？
> 
> 也许是加载顺序问题，vimium c 加载需要些时间，如果`runtime.sendMessage`发太早了就会取不到扩展ID从而失败。 如果是这个问题的话，你可以：
> 
>     * 包一个 setTimeout(..., 500) 来延迟加载
> 
>     * 或者失败后重试一次
> 
>     * 最好的办法是，runtime.sendMessage 成功后旧把 ID 记下来，下次直接用，不用 sendMessage 了
> 
> 
> 抱歉我这周末或者下周末才有时间测。

感谢你的回复，在扩展主页里用鼠标点一下空白位置后依旧无法解决。都是要新建标签页才可调用

**Comment by gdh1995** [comment]
我今天测了一下，刚启动的时候 firefox 默认创建 Firefox Home 页面，我改成 Custom URL、填入 newtab adapter 页面 URL 后，重启 firefox 就能直接用 vimium c 的快捷键了。

但这么设置有个问题，每台电脑都要单独修改一遍，因为 url 里有扩展的 UUID，即使是同一个 firefox 账号，在不同机器上也不一样。

![image](https://github.com/gdh1995/vimium-c/assets/5547703/a4d489fd-67b8-4297-9785-4fa71b1e9232)

**Comment by gdh1995** [comment]
你创建新的隐私窗口的时候，显示的是什么？firefox内置的隐私保护说明页面？还是主页插件的页面？
你的“新标签页”选的是newtab adapter，还是你改了的主页插件？
你的homepage设置的呢？
你改造好的主页插件能不能压缩成zip发我，我测测



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月29日(周二) 晚上10:49
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.******@***.***&gt;;
主题: Re: [gdh1995/vimium-c] 请问如何修改firefox的扩展程序以兼容vimium-c  (Issue #986)




  
我今天测了一下，刚启动的时候 firefox 默认创建 Firefox Home 页面，我改成 Custom URL、填入 newtab adapter 页面 URL 后，重启 firefox 就能直接用 vimium c 的快捷键了。
 
但这么设置有个问题，每台电脑都要单独修改一遍，因为 url 里有扩展的 UUID，即使是同一个 firefox 账号，在不同机器上也不一样。
 

  
可能是我没沟通清楚，按照您的设置的意思是，主页扩展与newtab adapter扩展均需要被修改吗。也就是说在Custom URL中填入修改后的newtab adapter的URL。newtab adapter设置成主页扩展的URL，而把vimium c的默认网址修改成newtab adapter的URL？
 我尝试把浏览器Custom URL仅设置成主页扩展的页面URL并无效果

**Comment by StirrerCymbal5zn** [comment]
> 你创建新的隐私窗口的时候，显示的是什么？firefox内置的隐私保护说明页面？还是主页插件的页面？ 你的“新标签页”选的是newtab adapter，还是你改了的主页插件？ 你的homepage设置的呢？ 你改造好的主页插件能不能压缩成zip发我，我测测
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月29日(周二) 晚上10:49 收件人: ***@***.***&gt;; 抄送: "Dahan ***@***.******@***.***&gt;; 主题: Re: [gdh1995/vimium-c] 请问如何修改firefox的扩展程序以兼容vimium-c (Issue #986) 我今天测了一下，刚启动的时候 firefox 默认创建 Firefox Home 页面，我改成 Custom URL、填入 newtab adapter 页面 URL 后，重启 firefox 就能直接用 vimium c 的快捷键了。 但这么设置有个问题，每台电脑都要单独修改一遍，因为 url 里有扩展的 UUID，即使是同一个 firefox 账号，在不同机器上也不一样。 可能是我没沟通清楚，按照您的设置的意思是，主页扩展与newtab adapter扩展均需要被修改吗。也就是说在Custom URL中填入修改后的newtab adapter的URL。newtab adapter设置成主页扩展的URL，而把vimium c的默认网址修改成newtab adapter的URL？ 我尝试把浏览器Custom URL仅设置成主页扩展的页面URL并无效果 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

新标签页与homepage均尝试过共同修改为主页插件或把新标签页单独设置为newtab adapter，由于主页插件我已默认不允许在隐私窗口运行。故新建隐私窗口显示隐私保护说明页面

此为图例，只截取将newtab adapter设置为新标签页的情况
[pic.zip](https://github.com/gdh1995/vimium-c/files/12474476/pic.zip)

此为扩展
[tabil.zip](https://github.com/gdh1995/vimium-c/files/12474473/tabil.zip)

此为vimuimc配置

[vimium_c-20230830_180120.zip](https://github.com/gdh1995/vimium-c/files/12474471/vimium_c-20230830_180120.zip)

**Comment by gdh1995** [comment]
我还是没读懂你具体怎么操作的，能不能录一下屏，然后标注第几秒按了什么键



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月30日(周三) 晚上6:06
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.******@***.***&gt;;
主题: Re: [gdh1995/vimium-c] 请问如何修改firefox的扩展程序以兼容vimium-c  (Issue #986)




  
你创建新的隐私窗口的时候，显示的是什么？firefox内置的隐私保护说明页面？还是主页插件的页面？ 你的“新标签页”选的是newtab adapter，还是你改了的主页插件？ 你的homepage设置的呢？ 你改造好的主页插件能不能压缩成zip发我，我测测
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年8月29日(周二) 晚上10:49 收件人: @.&gt;; 抄送: "Dahan @.@.&gt;; 主题: Re: [gdh1995/vimium-c] 请问如何修改firefox的扩展程序以兼容vimium-c (Issue #986) 我今天测了一下，刚启动的时候 firefox 默认创建 Firefox Home 页面，我改成 Custom URL、填入 newtab adapter 页面 URL 后，重启 firefox 就能直接用 vimium c 的快捷键了。 但这么设置有个问题，每台电脑都要单独修改一遍，因为 url 里有扩展的 UUID，即使是同一个 firefox 账号，在不同机器上也不一样。 可能是我没沟通清楚，按照您的设置的意思是，主页扩展与newtab adapter扩展均需要被修改吗。也就是说在Custom URL中填入修改后的newtab adapter的URL。newtab adapter设置成主页扩展的URL，而把vimium c的默认网址修改成newtab adapter的URL？ 我尝试把浏览器Custom URL仅设置成主页扩展的页面URL并无效果 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
新标签页与homepage均尝试过共同修改为主页插件或把新标签页单独设置为newtab adapter，由于主页插件我已默认不允许在隐私窗口运行。故新建隐私窗口显示隐私保护说明页面
 
此为图例，只截取将newtab adapter设置为新标签页的情况
 pic.zip
 
此为扩展
 tabil.zip
 
此为vimuimc配置
 
vimium_c-20230830_180120.zip

**Comment by StirrerCymbal5zn** [comment]
> 我还是没读懂你具体怎么操作的，能不能录一下屏，然后标注第几秒按了什么键
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月30日(周三) 晚上6:06 收件人: ***@***.***&gt;; 抄送: "Dahan ***@***.******@***.***&gt;; 主题: Re: [gdh1995/vimium-c] 请问如何修改firefox的扩展程序以兼容vimium-c (Issue #986) 你创建新的隐私窗口的时候，显示的是什么？firefox内置的隐私保护说明页面？还是主页插件的页面？ 你的“新标签页”选的是newtab adapter，还是你改了的主页插件？ 你的homepage设置的呢？ 你改造好的主页插件能不能压缩成zip发我，我测测 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年8月29日(周二) 晚上10:49 收件人: @.&gt;; 抄送: "Dahan @.@.&gt;; 主题: Re: [gdh1995/vimium-c] 请问如何修改firefox的扩展程序以兼容vimium-c (Issue #986) 我今天测了一下，刚启动的时候 firefox 默认创建 Firefox Home 页面，我改成 Custom URL、填入 newtab adapter 页面 URL 后，重启 firefox 就能直接用 vimium c 的快捷键了。 但这么设置有个问题，每台电脑都要单独修改一遍，因为 url 里有扩展的 UUID，即使是同一个 firefox 账号，在不同机器上也不一样。 可能是我没沟通清楚，按照您的设置的意思是，主页扩展与newtab adapter扩展均需要被修改吗。也就是说在Custom URL中填入修改后的newtab adapter的URL。newtab adapter设置成主页扩展的URL，而把vimium c的默认网址修改成newtab adapter的URL？ 我尝试把浏览器Custom URL仅设置成主页扩展的页面URL并无效果 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 新标签页与homepage均尝试过共同修改为主页插件或把新标签页单独设置为newtab adapter，由于主页插件我已默认不允许在隐私窗口运行。故新建隐私窗口显示隐私保护说明页面 此为图例，只截取将newtab adapter设置为新标签页的情况 pic.zip 此为扩展 tabil.zip 此为vimuimc配置 vimium_c-20230830_180120.zip — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

原始操作即为根据文档 [https://github.com/gdh1995/vimium-c/wiki/Inject-into-other-extensions](url)
1. 在火狐环境中先修改扩展的.html
2. 把所有的.js文件加入

``browser.runtime.sendMessage('vimium-c@gdh1995.cn', { handler: 99 }).then(res => {
  const { host } = res;
  console.log(host); // for example, log "d1ba02e9-ec90-46dc-8623-69e15961cc86"
  // localStorage.vimiumHost = host; // may cache it for further usages
  const injector = `moz-extension://${host}/lib/injector.js`;
  const script = document.createElement('script');
  script.src = injector;
  document.head.appendChild(script);
});
``
这一段代码后重新打包为zip文件
3. 火狐设置为开发者模式，鼠标拖动zip包至浏览器窗口加载扩展后进入about:addons页面
4. 进入 `about:debugging#/runtime/this-firefox`（调试扩展程序）获取主页扩展的UUID与扩展ID
5. 根据[https://github.com/gdh1995/vimium-c/wiki/Use-another-extension-as-the-New-Tab](url)进入vimuim c设置页面，在"新标签页默认网址"中填入`moz-extension://UUID/index.html`并在"受信任的其它扩展"中填入扩展ID并保存
6. 重启浏览器，结束
感谢您耐心的回复

**Comment by StirrerCymbal5zn** [comment]
> 我还是没读懂你具体怎么操作的，能不能录一下屏，然后标注第几秒按了什么键
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月30日(周三) 晚上6:06 收件人: ***@***.***&gt;; 抄送: "Dahan ***@***.******@***.***&gt;; 主题: Re: [gdh1995/vimium-c] 请问如何修改firefox的扩展程序以兼容vimium-c (Issue #986) 你创建新的隐私窗口的时候，显示的是什么？firefox内置的隐私保护说明页面？还是主页插件的页面？ 你的“新标签页”选的是newtab adapter，还是你改了的主页插件？ 你的homepage设置的呢？ 你改造好的主页插件能不能压缩成zip发我，我测测 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年8月29日(周二) 晚上10:49 收件人: @.&gt;; 抄送: "Dahan @.@.&gt;; 主题: Re: [gdh1995/vimium-c] 请问如何修改firefox的扩展程序以兼容vimium-c (Issue #986) 我今天测了一下，刚启动的时候 firefox 默认创建 Firefox Home 页面，我改成 Custom URL、填入 newtab adapter 页面 URL 后，重启 firefox 就能直接用 vimium c 的快捷键了。 但这么设置有个问题，每台电脑都要单独修改一遍，因为 url 里有扩展的 UUID，即使是同一个 firefox 账号，在不同机器上也不一样。 可能是我没沟通清楚，按照您的设置的意思是，主页扩展与newtab adapter扩展均需要被修改吗。也就是说在Custom URL中填入修改后的newtab adapter的URL。newtab adapter设置成主页扩展的URL，而把vimium c的默认网址修改成newtab adapter的URL？ 我尝试把浏览器Custom URL仅设置成主页扩展的页面URL并无效果 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 新标签页与homepage均尝试过共同修改为主页插件或把新标签页单独设置为newtab adapter，由于主页插件我已默认不允许在隐私窗口运行。故新建隐私窗口显示隐私保护说明页面 此为图例，只截取将newtab adapter设置为新标签页的情况 pic.zip 此为扩展 tabil.zip 此为vimuimc配置 vimium_c-20230830_180120.zip — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
此为录屏
[2023.zip](https://github.com/gdh1995/vimium-c/files/12503427/2023.zip)

**Comment by gdh1995** [comment]
shi'le试了一下，确实存在这个问题，是扩展加载顺序导致的。我写了个重试和缓存 uuid 的逻辑，问题就解决了。

[tabil-2.6.0-auto-load-vimium-c.zip](https://github.com/gdh1995/vimium-c/files/12565892/tabil-2.6.0-auto-load-vimium-c.zip)

其他人需要类似地改造 firefox 的扩展的话，可以从这个 zip 里拷贝走 injector.js，然后去 html 里加载。

**Comment by StirrerCymbal5zn** [comment]
> shi'le试了一下，确实存在这个问题，是扩展加载顺序导致的。我写了个重试和缓存 uuid 的逻辑，问题就解决了。
> 
> [tabil-2.6.0-auto-load-vimium-c.zip](https://github.com/gdh1995/vimium-c/files/12565892/tabil-2.6.0-auto-load-vimium-c.zip)
> 
> 其他人需要类似地改造 firefox 的扩展的话，可以从这个 zip 里拷贝走 injector.js，然后去 html 里加载。

问题已解决，感谢回复
