### ISSUE TITLE
内存占用异常

### ISSUE THREAD

**Issue by ccoob** [gdh1995/vimium-c#989]
浏览b站评论区，不断往下拉加载出更多评论，过了几分钟发现浏览器变得有些卡顿，打开任务管理器发现浏览器占用了3G内存，把b站标签页关闭后释放了将近2G的内存。
一开始以为是浏览器的问题，结果从Edge换到chrome问题还是存在，把这个插件关闭后成功解决了问题，网页打开的速度似乎还变快了一些。
不知道是不是bug，如果是的话希望大佬能优化一下，感谢。

**Comment by gdh1995** [comment]
用 chrome 商店版本，测试了 Edge 115 / Chrome 115，测不出来内存异常：
1. Edge 115：
- 1. ![Snipaste_2023-08-06_17-24-16](https://github.com/gdh1995/vimium-c/assets/5547703/405b167f-d74e-4600-ad34-365aa214e5b6)
2. Chrome 115：
- 1. ![Snipaste_2023-08-06_17-40-33](https://github.com/gdh1995/vimium-c/assets/5547703/5612d63d-97e5-4018-b4e0-02aead8d021a)

测试细节：
1. Win 11 Pro + 32GB 内存台式机 + 4k 屏幕 200% 缩放
- 1. Edge 115：我日常用的环境 + Vimium C v1.99.995（重新编译的 chrome47_ndebug_nomangle）+ 安装并开启 uBlock Origin 1.51.0 去广告
- 2. Chrome 115：全新安装、没修改任何设置 + Vimium C 的 chrome 商店版本 v1.99.994 原版
2. 对 B站 禁用图片加载，在 B 站播放器设置里关掉自动播放，手动选 360P，都登录我的账号
3. 上边两张图，左侧都是禁用 vimium c 后记录的内存，右侧都是开着 vimium c 后记录的内存
4. 每次测试都先彻底关掉 B站 页面，创建浏览器默认的新标签页，再从历史记录里直接访问视频播放页面
5. `***-0` 表示按 3-4 次 pagedown 滚动到 14000~16000 像素后捕捉的；`***-1` 表示在同一页面再按 3-4 次 pagedown，使其多滚动 10000 像素，再捕捉
6. 测试期间不触发 vimium c 命令，即不触发 `LinkHints`、`Vomnibar`、`scroll*` 等

分析：
1. 实测都是涨 100MB 左右内存，从涨得最多的那几类来看，看不出来有什么可感知的内存区别
2. 理论分析：
- 1. vimium c 没有长期保存页面内容过，在必要地方用了WeakSet、WeakRef，以前没遇到过释放不掉的情况
- 2. vimium c 对加载有性能影响，但已经应用了不少优化措施，时间上占比挺少
  - 1. 1.99.99x 版本里可能在页面刚加载好的某一时刻造成很短卡顿，其余时间不影响；在未来 2.xx 版本里没有此问题

=========

推测：
1. 可能是 别的浏览器扩展程序 和 vimium c 冲突了
2. 也可能单纯是个错觉，比如在不同页面、不同滚动距离上做的测试
3. 至于卡顿，可能是 cpu 睿频、网速波动、浏览器缓存 等因素的影响

**Comment by ccoob** [comment]
系统：win10 22H2    Chrome：115   vimium：1.99.99

1、chrome是官网下的，Vimium C是chrome应用商店下的。

2、b站播放同一个1080p视频，解码方式为hevc，都登录账号。

3、全程使用vimium滚动页面，往下浏览评论区，内存占用如图。
![问题复现](https://github.com/gdh1995/vimium-c/assets/138659768/13e07537-9d59-4f76-aaed-ae0b76642925)

4、全程使用鼠标操作，往下浏览评论区，内存占用如图。
![鼠标操作](https://github.com/gdh1995/vimium-c/assets/138659768/ccb11efe-ee90-4c21-b8fd-7eec4508b4eb)

5、我说的卡顿是指用vimium，按住j或k上下滚动页面时，卡成ppt了，用鼠标滚轮则正常。

6、应该不是插件冲突的原因，因为一共就两个插件，vimium和AdGuard，AdGuard在B站禁用。

**Comment by gdh1995** [comment]
j/k 滚屏这个是“正常现象”，用扩展程序做滚动，在超长页面只能做到这个效果；鼠标滚轮的话，是浏览器有特殊优化，滚动期间临时禁止了大部分 JS 执行，才做到这么顺滑。但是这个优化没有开放出来接口，扩展程序禁止不了这些。

**Comment by gdh1995** [comment]
我开着vimium c，用鼠标滚动期间也能出现 1.3G-2.4G 的波动，停下来不动后，过一阵子会自动释放降低到 1.3G，然后在 1.3G-1.6G 波动。老实说这个波动范围就不正常，B站的网页代码应该是做了什么垃圾死循环，能费1/4个核心。

**Comment by gdh1995** [comment]
b站网页的代码真是一坨套一坨。测试下来确实开着 vimium c 滚动会增加消耗，但是不开也能蹦上 3GB 以上。

另外，如果关掉了视频的自动播放，需要点一下播放、再暂停，能省一半 CPU，内存也更平缓。
![image](https://github.com/gdh1995/vimium-c/assets/5547703/156b10e5-3fe1-4d37-ac09-8827397c1cec)

**Comment by ccoob** [comment]
重启电脑后又测试了几次，发现就算把插件关掉，有时内存占用还是能飙到4G，然后突然降到2.5G，此时如果不关闭这个网页，就会不断循环这个过程。
结论：**不是该插件的问题**，已经向B站反馈。
最后，感谢大佬的帮助。

**Comment by gdh1995** [comment]
我的实验里还是有区别的，开着 vimium c 滚动到 4W 像素，内存就保底 2.5G 了，关掉后到 6W 像素才会这么高，还能落回去。我再测两下。

**Comment by gdh1995** [comment]
最新测试：
1. 关掉 vimium c 的一些特性，滚动到 6W+ 像素，保底还是1.2GB，开 DevTools 就会蹦到 3GB 多；
2. 重新用完整 vimium c 测，内存 1.5GB，开 DevTools 后增加到 2.x GB，再关掉 devtools 后 1.0GB
3. 所以新的结论是，内存增长情况和 vimium c 无关；和 dev tools 是否开启有关……

另外有一个发现，如果你说的“卡成PPT”是那种速度很稳定的 PPT，那应该是 chrome 限制了扩展脚本的“滚动速度”：
1. 我测试里，4W 多像素下，扩展脚本（被限制到）每秒只能滚动 20 次，挺卡的
2. 到 7W 像素的时候，只剩 10~11 次了，滚动起来就没有动画的感觉
