### ISSUE TITLE
Dosen't work on Dvorak layout.

### ISSUE THREAD

**Issue by JimMoen** [gdh1995/vimium-c#99]
After 2020.1.4th update.It doesn't work on Dvorak layout.It always works on QWERTY Layout.
(I have turned off the "Ignore Keyboard Layout" setting.)
Chromium Version 79.0.3945.88 Arch Linux
Vimium C Version 1.79.2

**Comment by gdh1995** [comment]
Confirmed and it's a bug on all platforms. Thanks!

I'll release a new version to fix it, but Chrome Web Store has some strict validation on extensions requiring lots of permissions, so a new version will only get available in 3~6 days. Sorry for the inconvenience.

**Comment by gdh1995** [comment]
Hello, Vimium C v1.79.3 has been available on Chrome Web Store.

**Comment by JimMoen** [comment]
Thanks,Updated.It works now.
谢谢，应用商店已经更新。现在可以正常工作了。
