### ISSUE TITLE
Different commands for alphabet or filtered hints

### ISSUE THREAD

**Issue by aaron-a-f** [gdh1995/vimium-c#990]
**What command or commands**

Add a feature so that `LinkHints.*` commands have an option where you can choose alphabet of filtered hints

**How should a feature do**

Example:

map f LinkHints.activate hintMode=alphabet
map F LinkHints.activate hintMode=filtered

**Why**
I think alphabet and filtered hints are great for different things and I think the option to choose between them depending on the situation would be really valuable.

Thanks for all your hard work!

**Comment by gdh1995** [comment]
Try:
```
map F LinkHints.activate useFilter
```

**Comment by aaron-a-f** [comment]
Amazing, this is perfect. Thanks Dahan
