### ISSUE TITLE
在openai的网站上，mark不能正常工作

### ISSUE THREAD

**Issue by clapat-bb** [gdh1995/vimium-c#991]
**Describe the bug**
在同一个页面内，我用m标记上面的内容，当我回到底部的时候，用`m不能回到之前标记的地方。

**To Reproduce**

**Browser, OS and Vimium C versions**

- Browser name: chrome
- Browser version: 最新的版本
- Vimium C version: 最新的版本
- OS name and version: window10  稳定版

**Comment by lipppchen** [comment]
测试页面就是那个问答的页面，然后标记这些都是正常标记 系统已经提示我标记成功就是不能跳转 那就有劳作者加强一下了
