### ISSUE TITLE
Quickest way to change the language of a wikipedia article

### ISSUE THREAD

**Issue by 11100010** [gdh1995/vimium-c#993]
Is it possible to use Vimium C to have a shortcut like: type "en" ( change to English ), "zh" ( change to Chinese ) in a wikipedia article?

If the name of article were not changing in the URL, the issue would be much easy. But it changes according to the language written in.

**Comment by 11100010** [comment]
My FAULT, looks like simply changing the language code part of the domain name would work very well in most cases.

**Comment by gdh1995** [comment]
Well, maybe you can use `LinkHints.click` to click a target element directly.

**Comment by 11100010** [comment]
> The language menu on Wikipedia is hidden, so it takes quite a few clicks to get to the language one wants. Instead I'm now using "Custom search engines": `wcn: javascript:location.href='https://zh'+location.hostname.substring(location.hostname.indexOf('.'))+location.pathname;`

The only shame of this is: it does not always work.
E.g.:
Given this article: https://en.wikipedia.org/wiki/Evergrande_Group
After `wcn`, the URL becomes: https://zh.wikipedia.org/wiki/Evergrande_Group
Meanwhile the valid article URL should be: https://zh.wikipedia.org/wiki/恒大集团

Some wiki articles maybe do have a connected link between the names in different languages, so it will automatically translate the article names. If not, it fails.

**Comment by gdh1995** [comment]
Hello, you may try:
```
map xxx goNext patterns=".interlanguage-link[data-code=zh]>a"
```

BTW, if you have other situations to substitute tab URLs, you may use not `Custom search engines` but `Auto substitution of various text`:
1. add such a key mapping
```
# open in a new tab
map xxx openUrl url="$S" url_mask sed="_zh"
# replace a current tab
map yyy openUrl url="$S" url_mask sed="_zh" reuse="current"
```
2. add such a text substitution rule:
```
_zh@^https://en\.wikipedia\.org@https://zh.wikipedia.org@
```

**Comment by gdh1995** [comment]
Update: the key mapping should be:
```
map <f7> goNext match="fake" patterns=".interlanguage-link.interwiki-zh>a"
```

**Comment by 11100010** [comment]
> Update: the key mapping should be:
> 
> ```
> map <f7> goNext match="fake" patterns=".interlanguage-link.interwiki-zh>a"
> ```

**WOW, it works like a charm!**
Could you explain how this command `goNext match="fake" patterns=".interlanguage-link.interwiki-zh>a"` works for me ?

I've read it short description. But still don't have a clue how it works.
Follow the link labeled next or ">" (use sed=true, patterns:string, rel:string, noRel, isNext)(goNext)

Thank you very much~~~~

**Comment by 11100010** [comment]
I'd like to map keys to switch between traditional and simplified chinese 
```
map 1tw goNext match="fake" patterns=".interlanguage-link.interwiki-zh-tw>a"
map 1cn goNext match="fake" patterns=".interlanguage-link.interwiki-zh-cn>a"
```
But it doesn't work, looks like those links don't belong to "the links labeled next" according to the short description of the command?
`Follow the link labeled next or ">" (use sed=true, patterns:string, rel:string, noRel, isNext)(goNext)`

**Comment by gdh1995** [comment]
Um, in `.interlanguage-link.interwiki-zh>a`, the first `.` character tell Vimium C's `goNext` command that it's a `CSS selector`, but  not link text / title, so that `goNext` will find the specified element.

As for `1tw` didn't work, it may be because of the mapped key itself:
- If you write a key mapping rule looking like `map 1tw goNext ....`, then Vimium C should have given an error when you saved options
  - the error text should be `Error: Invalid key: "1tw" - a first char can not be '-' or numbers, unless before is `unmap 1`.`

Vimium C doesn't recommend to use a number character as a first key of a key mapping, because it will prevent commands from receiving a "count prefix"
- for example, by default `j` is `scrollDown`, and `2j` is `scrollDown` by 2x distance, `10j` by 10x distance

**Comment by 11100010** [comment]
Yeah, 'cause I already 'unmap 1' so the keys '1cn', '1tw' work fine just like other language cases:
```
map 1zh goNext match="fake" patterns=".interlanguage-link.interwiki-zh>a"
map 1en goNext match="fake" patterns=".interlanguage-link.interwiki-en>a"
map 1ja goNext match="fake" patterns=".interlanguage-link.interwiki-ja>a"
```

OH YEAH, finally figured it out, thanks for your explanation so much

```
map 1tw goNext match="fake" patterns=".ca-variants-zh-Hant-TW>a"
map 1cn goNext match="fake" patterns=".ca-variants-zh-Hans-CN>a"
```
