### ISSUE TITLE
请教如何在当前URL后面快速添加参数

### ISSUE THREAD

**Issue by LarryKHite** [gdh1995/vimium-c#999]
比如当前的URL是 https://github.com/gdh1995/，我想通过快捷方式添加参数变为：https://github.com/gdh1995/?LSCWP_CTRL=before_optm，该如何写map？

我测试 map cs openUrl url="$s?LSCWP_CTRL=before_optm" url_mask="$s"，总是到搜索页面！

谢谢！

**Comment by gdh1995** [comment]
需要用$S
注意是大写S，表示不做url-encoding，就能拼出来网址了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月20日(周日) 晚上9:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [gdh1995/vimium-c] 请教如何在当前URL后面快速添加参数 (Issue #999)




 
比如当前的URL是 https://github.com/gdh1995/，我想通过快捷方式添加参数变为：https://github.com/gdh1995/?LSCWP_CTRL=before_optm，该如何写map？
 
我测试 map cs openUrl url="$s?LSCWP_CTRL=before_optm" url_mask="$s"，总是到搜索页面！
 
谢谢！
